MAINTAINERS.md

This is based on the maintainers list that CEHENKLE posted in the [forums](https://discuss.opendistrocommunity.dev/t/preparing-opensearch-and-opensearch-dashboards-for-release/5567).
It is similar to the [maintainers file merged for OpenSearch](https://github.com/opensearch-project/OpenSearch/blob/main/MAINTAINERS.md)
Signed-off-by: Dawn M. Foster <fosterd@vmware.com>

Added a maintainers file 

---

README.md

Added link to the opensearch dev guide.
Fixed the URL for the clone to work for OpenSearch Dashboards
Signed-off-by: Jonah Kowall <jkowall@kowall.net>

Clarify instructions in README

---

src/dev/build/tasks/os_packages/docker_generator/run.ts
src/dev/build/tasks/os_packages/docker_generator/templates/Dockerfile
src/dev/build/tasks/os_packages/docker_generator/templates/opensearch_dashboards_yml.template.ts

This fixes the Docker image building process that was still trying to build kibana
#285

Fix Docker image build process

---

src/plugins/timeline/public/directives/timeline_help/timeline_help.html
test/functional/apps/timeline/_expression_typeahead.js

This includes tests when running the following:
node scripts/functional_tests.js --config test/functional/config.js --include ciGroup1
One fix related to the source code and had to ignore the other code to move onto later.
Will return with [FIXME], basically it works when actually running the application.
It's just not loading the data in and failing because it has no clue about the logstash-*
index pattern.
1/12 of https://github.com/opensearch-project/OpenSearch-Dashboards/issues/247

[Tests] ciGroup1 func test fixes

---

src/plugins/saved_objects_management/public/lib/resolve_saved_objects.test.ts
src/plugins/saved_objects_management/public/lib/resolve_saved_objects.ts
test/functional/apps/dashboard/create_and_add_embeddables.js
test/functional/apps/dashboard/dashboard_back_button.ts
test/functional/apps/dashboard/dashboard_error_handling.ts
test/functional/apps/dashboard/dashboard_filter_bar.js
test/functional/apps/dashboard/dashboard_filtering.js
test/functional/apps/dashboard/dashboard_grid.js
test/functional/apps/dashboard/dashboard_options.js
test/functional/apps/dashboard/dashboard_query_bar.js
test/functional/apps/dashboard/dashboard_saved_query.js
test/functional/apps/dashboard/dashboard_snapshots.js
test/functional/apps/dashboard/data_shared_attributes.js
test/functional/apps/dashboard/edit_embeddable_redirects.js
test/functional/apps/dashboard/edit_visualizations.js
test/functional/apps/dashboard/embed_mode.js
test/functional/apps/dashboard/embeddable_rendering.js
test/functional/apps/dashboard/empty_dashboard.js
test/functional/apps/dashboard/full_screen_mode.js
test/functional/apps/dashboard/legacy_urls.ts
test/functional/apps/dashboard/panel_expand_toggle.js
test/functional/apps/dashboard/time_zones.js
test/functional/apps/dashboard/url_field_formatter.ts
test/functional/apps/dashboard/view_edit.js

This does not fix everything in group 2, there are still failures which I believe
are being caused by some data being imported but this fixes an error in the plugins
of a incomplete rename of applyOpenSearchResp.
node scripts/functional_tests.js --config test/functional/config.js --include ciGroup2
Partially https://github.com/opensearch-project/OpenSearch-Dashboards/issues/247

[Tests] ciGroup2 functional test fixes

---

package.json

Signed-off-by: Mihir Soni <mihirsoni.123@gmail.com>
[Describe what this change achieves] This change will reset the version of Dashboards to `1.0.0`. This will be going to main branch as of now more details on this https://github.com/opensearch-project/OpenSearch/issues/95#issuecomment-819813769
* All unit test cases passes.
* All integration test pases.
* FTR is still pending.
In order to test this
* Clone this branch [opensearch](https://github.com/opensearch-project/OpenSearch/tree/opensearch/rebaseVersion)
* `./gradlew :distribution:archives:oss-linux-tar:assemble`
* Use generated distribution to start the OpenSearch
* Start dashbaords.
[List any issues this PR will resolve] #226

Change Version to 1.0.0

---

CONTRIBUTING.md

Fixes the example flag passed in the DCO CLI example to not have added whitespace.

Fix DCO CLI example in CONTRIBUTING.md

---

CONTRIBUTING.md

Added a link to the maintainer file in the step where we talk about merging PRs in the contributing guide. This provides a bit more visibility into who could be expected to be merging those changes.
Signed-off-by: Dawn M. Foster <fosterd@vmware.com>

Added link to MAINTAINERS.md from the Contributing guide

---

src/plugins/data/public/ui/filter_bar/filter_editor/lib/filter_editor_utils.test.ts
src/plugins/data/public/ui/filter_bar/filter_editor/lib/filter_editor_utils.ts

Signed-off-by: Michael Torres <mic.ric.tor@gmail.com>
Users of Dashboards will be able to specify CIDR strings as filters against IP fields
Issue posted initially against the upstream (Kibana) - https://github.com/elastic/kibana/issues/50520
Users are not able to specify a CIDR netmask when using the filter UI.
- [n/a] New functionality has been documented.
- [n/a] New functionality has javadoc added

Add support for CIDR mask filters on IP fields

---

src/plugins/maps_legacy/config.ts
src/plugins/maps_legacy/public/map/base_maps_visualization.js
src/plugins/maps_legacy/public/map/service_settings.js
src/plugins/maps_legacy/public/map/service_settings.test.js
src/plugins/maps_legacy/server/index.ts

This doesn't fix the maps out of the box but fixes the issues that prevented users from settings the maps service in the config.
Which can be set by adding the following to opensearch_dashboards.yml:
```
map.tilemap.url: "https://tiles.maps.search-services.aws.a2z.com/tiles/{z}/{x}/{y}.png"
map.includeOpenSearchMapsService: false
```
Partial: https://github.com/opensearch-project/OpenSearch-Dashboards/issues/221

[BUILD] Maps service config

---

packages/osd-opensearch/src/artifact.js
packages/osd-opensearch/src/artifact.test.js
packages/osd-opensearch/src/custom_snapshots.js
src/dev/build/lib/build.test.ts
src/dev/build/lib/platform.test.ts
src/dev/build/lib/platform.ts
src/dev/build/tasks/nodejs/verify_existing_node_builds_task.test.ts
src/dev/build/tasks/os_packages/create_os_package_tasks.ts
src/dev/build/tasks/os_packages/docker_generator/run.ts
src/plugins/apm_oss/server/tutorial/instructions/apm_server_instructions.ts
src/plugins/home/server/tutorials/instructions/auditbeat_instructions.ts
src/plugins/home/server/tutorials/instructions/filebeat_instructions.ts
src/plugins/home/server/tutorials/instructions/functionbeat_instructions.ts
src/plugins/home/server/tutorials/instructions/heartbeat_instructions.ts
src/plugins/home/server/tutorials/instructions/metricbeat_instructions.ts
src/plugins/vis_type_vislib/public/fixtures/mock_data/filters/_columns.js
src/plugins/vis_type_vislib/public/fixtures/mock_data/range/_rows.js
tasks/config/run.js

Move Dashboards to the naming convention as the plugins.
Here are the naming changes required:
* x86_64 to x64
* aarch64 to arm64
[#311](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/311)

Change x86_64 to x64 and aarch64 to arm64 following industry conventions

---

packages/osd-plugin-helpers/src/cli.ts

Main branch is on version 1.0.0, but there is a version check expecting 7.9 when building plugins. This PR fixes the issue by revising the version check to unblock plugin build. 
[#309](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/309)
[#224](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/224)

[Bug]Fix version conflict for plugins

---

README.md

This commit adds the installation steps of yarn and npm in the README.md file before the setup.
Closes https://github.com/opensearch-project/OpenSearch-Dashboards/issues/270
---
@seraphjiang, do you have any suggestions?

Update README.md with the nvm, yarn setup steps

---

packages/osd-plugin-helpers/src/integration_tests/build.test.ts

Signed-off-by: Ubuntu <ubuntu@ip-172-31-24-239.us-west-2.compute.internal>
Due to code change in [#312](https://github.com/opensearch-project/OpenSearch-Dashboards/commit/b563989c41ea367a6fc37ef9ae3a307e7a7fc1f9) on packages/osd-plugin-helpers/src/cli.ts , packages/osd-plugin-helpers/src/integration_tests/build.test.ts does not work. This PR fixed this particular integration test.
na

[Tests] Fix integration test due to code change in osd-plugin-helper

---

src/plugins/opensearch_dashboards_overview/public/components/add_data/__snapshots__/add_data.test.tsx.snap
src/plugins/opensearch_dashboards_overview/public/components/add_data/add_data.tsx

The 'Try our sample data' link in the opensearch dashboards overview page is broken. It has to be pointed to the path `/app/home#/tutorial_directory/sampleData`. This commit fixes this bug. The snapshots are updated accordingly.
Fixes #193

Fix broken link in the Overview page

---

src/dev/build/tasks/os_packages/docker_generator/resources/bin/opensearch-dashboards-docker
src/legacy/server/config/schema.js
src/plugins/maps_legacy/config.ts
src/plugins/maps_legacy/public/__tests__/map/ems_mocks/sample_files.json
src/plugins/maps_legacy/public/common/opensearch_maps_client.js
src/plugins/maps_legacy/public/map/map_messages.js
src/plugins/maps_legacy/public/map/opensearch_dashboards_map.js
src/plugins/maps_legacy/public/map/service_settings.js
src/plugins/maps_legacy/public/map/service_settings.test.js
src/plugins/maps_legacy/server/index.ts
src/plugins/region_map/public/choropleth_layer.js
src/plugins/region_map/public/components/region_map_options.tsx
test/functional/apps/dashboard/dashboard_state.js
test/functional/apps/visualize/_region_map.js
test/functional/apps/visualize/_tile_map.js

Update the map client to use: `https://maps.search-services.aws.a2z.com/`. Potentially further cleanup can be made but this makes map client work out of the box.
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/221

Update map client

---

src/plugins/newsfeed/public/components/__snapshots__/loading_news.test.tsx.snap
src/plugins/newsfeed/public/components/loading_news.tsx
src/plugins/saved_objects_management/public/management_section/objects_table/components/flyout.tsx
src/plugins/saved_objects_management/public/management_section/objects_table/components/relationships.test.tsx
src/plugins/saved_objects_management/public/management_section/objects_table/components/relationships.tsx
src/plugins/saved_objects_management/public/management_section/objects_table/saved_objects_table.tsx

We found some logo hidden in Stack Management > Saved Objects > Import > select a file > Import> Elastic logo (spinner)
[#338 ](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/338)
Replace EuiLoadingElastic to EuiLoadingSpinner.
Test(local): unit and integration

[Bug] Replace EuiLoadingElastic to EuiLoadingSpinner

---

CONTRIBUTING.md
README.md

Signed-off-by: GitHub <mihirsoni.123@gmail.com>
Updating README and CONTRIBUTING guide to reflect real links and get ready for beta1

[DOCS] Updated Readme and Contributing.md guide

---

src/dev/build/tasks/notice_file_task.ts
src/dev/notice/generate_notice_from_source.ts

Update the notice generator so that builds come with the expected header
n/a
- [] New functionality includes testing.

[BUILD] Update notice generator

---

src/plugins/data/public/ui/filter_bar/filter_bar.tsx

Signed-off-by: galangel <gal0angel@gmail.com>
Added Auto-focus on the Field input when clicking Add filter
Done by setting the initial focus of the popover with the relevant selector
example:
[Add filter form initial focus should be the Field input](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/354)

Auto-focus on the Field input when clicking Add filter

---

src/cli_plugin/install/install.js
src/cli_plugin/install/opensearch_dashboards.js

This change intends to default the folder name for plugins being installed through cli to kebab-case. 
To test the change, I ran `./bin/opensearch-dashboards-plugin install file:///anomalyDetectionDashboards-1.0.0.0-beta1.zip` to verify the folder name generated which is now in kebab-case: `anomaly-detection-dashboards`.
Part 1 of #322

Default to converting folder name for cli plugin to kebab-case

---

release-notes/opensearch-dashboards.release-notes-1.0.0-rc1.md

Adding release notes for OpenSearch 1.0.0-rc1.
This is generated using the tool: [git-release-notes](https://github.com/ariatemplates/git-release-notes). The command is:
`git-release-notes <since>..<until> <template> > <path to release-notes>`
Here we need to change the inputs `<since>` and `<until>` which is the range of commits as in git log. `<template>`is set as markdown.
match OpenSearch release note [#794](https://github.com/opensearch-project/OpenSearch/pull/794) and issue #[789](https://github.com/opensearch-project/OpenSearch/issues/789)

Add release note for 1.0.0-rc1

---

src/plugins/data/public/ui/typeahead/__snapshots__/suggestion_component.test.tsx.snap
src/plugins/data/public/ui/typeahead/suggestion_component.tsx
src/plugins/saved_objects_management/public/management_section/objects_table/components/__snapshots__/table.test.tsx.snap
src/plugins/saved_objects_management/public/management_section/objects_table/components/table.tsx

Icons were renamed from `kql` to `dql` which doesn't exist. Restoring the
correct icon fixes the error in the browser as well.
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/431

[Build] fix icons in stack management

---

src/core/public/chrome/chrome_service.tsx
src/core/public/chrome/ui/header/header_breadcrumbs.tsx

Some minor spacing issues in OpenSearch Dashboards fixed by updating the
title and replacing with Overview.
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/428

[Build] fix overview and default app titles

---

src/core/server/core_app/core_app.ts
src/core/server/core_app/integration_tests/default_route_provider_config.test.ts

If default route was stored as kibana_overview, the default route will
modified in code to the updated opensearch_dashboards_overview.
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/334

[Build] fix overview default route

---

package.json
yarn.lock

There are warnings present in the `yarn osd bootstrap` process because of the current dependency resolutions. This change resolves all of the warnings that are not related to Typescript. Typescript will need to be addressed in a separate PR which will involve upgrading the version of `@elastic/eui` to one that utilizes Typescript >=4.0.0.
**Before**:
```
$ yarn osd clean
...
$ yarn osd bootstrap
$ node scripts/osd bootstrap
info [opensearch-dashboards] running yarn
$ node ./preinstall_check
[1/5] Validating package.json...
[2/5] Resolving packages...
warning Resolution field "prismjs@1.22.0" is incompatible with requested version "prismjs@~1.23.0"
warning Resolution field "trim@0.0.3" is incompatible with requested …
```

[Build] Reduce yarn bootstrap warnings

---

config/opensearch_dashboards.yml
src/core/server/opensearch/opensearch_config.test.ts
src/core/server/opensearch/opensearch_config.ts
src/core/server/opensearch/opensearch_service.ts
src/core/server/opensearch/version_check/ensure_opensearch_version.test.ts
src/core/server/opensearch/version_check/ensure_opensearch_version.ts

Ensures that Dashboards checks only the local OpenSearch node when
cluster_id node attribute is present and all nodes have some cluster_id
value; Otherwise, it uses default behavior
Tested on both older 7.10 and newer 1.0 versions:
- using clean 7.10 engine and 7.10 in `package.json` for 7.10 version
- using OpenSearch 1.0 engine and 1.0 in `package.json` for 1.0 version
Tested using local OpenSearch cluster. Configurable setting is read from `opensearch_dashboards.yml` config file and is able to move through separate code paths for the setting being enabled and disabled in the config file. 
The `getNodeId()` function is called in the optimized path and correctly returns a promise
Value used when `cluster_id` is set as node attr and all nodes have the same value:
Signed-off-by: Bishoy …

Implement optimized healthcheck for Dashboards

---

src/plugins/home/public/application/components/add_data/__snapshots__/add_data.test.tsx.snap
src/plugins/home/public/application/components/add_data/add_data.test.tsx
src/plugins/home/public/application/components/add_data/add_data.tsx
src/plugins/home/public/application/components/tutorial_directory.js
src/plugins/home/public/plugin.ts
src/plugins/opensearch_dashboards_overview/public/components/add_data/__snapshots__/add_data.test.tsx.snap
src/plugins/opensearch_dashboards_overview/public/components/add_data/add_data.test.tsx
src/plugins/opensearch_dashboards_overview/public/components/add_data/add_data.tsx
test/functional/apps/home/_add_data.js

Currently we don't have instructions/code samples/docs  that instruct users to use apps to add data or download agents from `artifacts.opensearch.org`. Therefore, we decide to temporarily remove tutorials from `add data` page.
There are 3 places cx can enter into `add data` page. 2 of them is on home page (upper left and `Ingest your data` section) and 1 on overview page. This PR remove the `add data` page and only keep `try sample data`. Now the home page, overview page and add data page look like below:
1) Home page:
2)Overview page:
3)When click `add data` or `Add sample data `, all goes to add data page:
[#426 ](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/426)
1)Unit
2)Integration
3)Functional

Temporarily remove Tutorials from "Add Data" page

---

packages/osd-opensearch-archiver/src/lib/docs/__tests__/generate_doc_records_stream.ts
packages/osd-opensearch/src/artifact.js
packages/osd-opensearch/src/artifact.test.js
src/core/server/ui_settings/create_or_upgrade_saved_config/integration_tests/create_or_upgrade.test.ts
src/core/server/ui_settings/integration_tests/index.test.ts

Updating artifact to enable running integration tests and functional
tests to pull an artifact from the current hosted distributions.
At the time of this commit, there is not manifest hosted but there are
static links which can have an unknown amount of RC versions if the
GA snapshot does not exist for that version. But the assumption
is that it will not be too high.
Deprecating the previous implementation but we can remove that in a
future iteration. Wanted to leave that available incase others use
that for custom manifests.
Enable tests that depended on snapshots as well.
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/242
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/19

[Tests] updated artifact script

---

package.json
yarn.lock

Dependabot bumped the dependency from 1.3.1 to 1.3.4 in #381, but it edited the yarn.lock file directly. This is not the recommended short- or long-term solution.
```
$ yarn why dns-packet
[1/4] Why do we have the module "dns-packet"...?
=> Found "dns-packet@1.3.4"
- "_project_#@osd#ui-framework#webpack-dev-server#bonjour#multicast-dns" depends on it
- Hoisted from "_project_#@osd#ui-framework#webpack-dev-server#bonjour#multicast-dns#dns-packet"
info Disk size without dependencies: "44KB" …
```

Add proper dependency resolution for dns-packet

---

package.json
yarn.lock

Dependabot bumped the dependency from 6.0.1 to 6.0.2 in #332, but it edited the yarn.lock file directly. This left older versions of the dependency in the lockfile.
```
$ yarn why ssri
[1/4] Why do we have the module "ssri"...?
=> Found "ssri@8.0.0"
- "_project_#cacache" depends on it
- Hoisted from "_project_#cacache#ssri"
info Disk size without dependencies: "56KB"
info Disk size with unique dependencies: "104KB"
info Disk size with transitive dependencies: "136KB"
info Number of shared …
```

Add proper dependency resolution for ssri

---

package.json
yarn.lock

Dependabot bumped url-parse from 1.4.7 to 1.5.1 in #343, but it edited the yarn.lock file directly. This is not the recommended short- or long-term solution. This is a downstream dependency of @elastic/eui, so this line should be removed after that dependency is upgraded.
```
$ yarn why url-parse
[1/4] Why do we have the module "url-parse"...?
=> Found "url-parse@1.5.1"
- "_project_#@elastic#eui" depends on it
- Hoisted from "_project_#@elastic#eui#url-parse"
- Hoisted from …
```

Add proper dependency resolution for url-parse

---

package.json
yarn.lock

Dependabot bumped locutus from 2.0.10 to 2.0.14 in #348, but it edited the lockfile directly. This is not the recommended short- or long-term solution.
```
$ yarn why locutus
[1/4] Why do we have the module "locutus"...?
=> Found "locutus@2.0.14"
- "_project_#@osd#ui-framework#yo#yeoman-doctor#twig" depends on it
- Hoisted from "_project_#@osd#ui-framework#yo#yeoman-doctor#twig#locutus"
info Disk size without dependencies: "4.11MB"
info Disk size with unique dependencies: "4.49MB"
info Disk …
```

Add proper dependency resolution for locutus

---

package.json
yarn.lock

Dependabot bumped immer from 1.10.0 to 8.0.1 in #433, but it did not add a resolution to prevent older versions from remaining in the lockfile.
```
$ yarn why immer
[1/4] Why do we have the module "immer"...?
=> Found "immer@8.0.1"
info Has been hoisted to "immer"
- "workspace-aggregator-62005fd5-e986-4599-9851-789db848ca40" depends on it
- Specified in "devDependencies"
- Hoisted from "_project_#immer"
info Disk size without dependencies: "1.02MB"
info Disk size with unique dependencies: …
```

Add proper dependency resolution for immer

---

packages/osd-config-schema/src/errors/__snapshots__/schema_error.test.ts.snap
packages/osd-config-schema/src/errors/schema_error.test.ts

This is skipped because in 2017 there is no decision around error handling in the new platform. We can enable the unit test for error handling. 
The error message is:
```
{ Error: test
at Object.<anonymous>.it (/home/anan/work/OpenSearch-Dashboards/packages/osd-config-schema/src/errors/schema_error.test.ts:61:11)
at Object.asyncJestTest (/home/anan/work/OpenSearch-Dashboards/node_modules/jest-jasmine2/build/jasmineAsyncInstall.js:106:37)
at resolve (/home/anan/work/OpenSearch-Dashboards/node_modules/jest-jasmine2/build/queueRunner.js:45:12)
at new Promise (<anonymous>)
at mapper (/home/anan/work/OpenSearch-Dashboards/node_modules/jest-jasmine2/build/queueRunner.js:28:19)
at promise.then …
```

[Test] Enable schema_error.test.ts

---

src/core/server/opensearch/opensearch_config.test.ts
src/core/server/opensearch/opensearch_config.ts
src/core/server/opensearch_dashboards_config.test.ts
src/core/server/opensearch_dashboards_config.ts
src/plugins/home/server/index.ts
src/plugins/maps_legacy/server/index.ts
src/plugins/opensearch_dashboards_legacy/server/index.ts
src/plugins/region_map/server/index.ts
src/plugins/vis_type_timeline/server/index.ts
src/plugins/vis_type_vega/server/index.ts

While renaming after the fork, configurations were renamed
and replaced with keywords related to OpenSearch.
This meant that anyone who migrated to OpenSearch Dashboards
who had configured their YAML file no longer were able to
carry over those changes and run the application. This
prevented the application from starting due to unknown config
keys. Although, this still does not allow the application to
work out of the box because people will need to make sure
then rename their kibana.yml to opensearch_dashboards.yml,
but once they do they do not need to modify the content
of the config.
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/440
Partial: https://github.com/opensearch-project/OpenSearch-Dashboards/issues/334

[Build] deprecate renamed configurations

---

src/plugins/newsfeed/public/components/loading_news.test.tsx

All the unit tests related to unused newsfeed are temporarily
skipped at forking. To build a clean unit test, we decide to
check and enable all the working unit tests. This PR checks
and enables loading_news.test.tsx.
[#492 ](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/492)
unit test for empty_news.test.tsx
```
yarn test:jest /home/anan/work/OpenSearch-Dashboards/src/plugins/newsfeed/public/components/loading_news.test.tsx
$ node scripts/jest /home/anan/work/OpenSearch-Dashboards/src/plugins/newsfeed/public/components/loading_news.test.tsx
PASS  src/plugins/newsfeed/public/components/loading_news.test.tsx
news_loading
rendering
✓ renders the default News Loading (8 ms)
Test Suites: 1 passed, 1 total …
```

[Test] Enable unit test suite: loading_news.test.tsx

---

src/plugins/newsfeed/public/components/__snapshots__/empty_news.test.tsx.snap
src/plugins/newsfeed/public/components/empty_news.test.tsx

All the unit tests related to unused newsfeed are temporarily
skipped at forking. To build a clean unit test, we decide to
check and enable all the working unit tests. This PR checks
and enables empty_news.test.tsx.
[#491 ](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/491)
unit test for empty_news.test.tsx
```
yarn test:jest /home/anan/work/OpenSearch-Dashboards/src/plugins/newsfeed/public/components/empty_news.test.tsx
$ node scripts/jest /home/anan/work/OpenSearch-Dashboards/src/plugins/newsfeed/public/components/empty_news.test.tsx
PASS  src/plugins/newsfeed/public/components/empty_news.test.tsx
empty_news
rendering
✓ renders the default Empty News (9 ms)
Test Suites: 1 passed, 1 total
Tests:       1 …
```

[Test] Enable unit test suite: empty_news.test.tsx

---

src/plugins/newsfeed/public/lib/api.test.ts

All the unit tests related to unused newsfeed are temporarily
skipped at forking. To build a clean unit test, we decide to
check and enable all the working unit tests. This PR checks
and enables api.test.ts.
[#490 ](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/490)
unit test for api.test.ts
```
yarn test:jest /home/anan/work/OpenSearch-Dashboards/src/plugins/newsfeed/public/lib/api.test.ts
$ node scripts/jest /home/anan/work/OpenSearch-Dashboards/src/plugins/newsfeed/public/lib/api.test.ts
console.error
sorry, try again later!
217 |       driver.fetchNewsfeedItems(http, config.service).pipe(
218 |         catchError((err) => {
> 219 |           window.console.error(err);
|                          ^
220 …
```

[Test] Enable unit test suite: api.test.ts

---

src/plugins/telemetry/server/telemetry_repository/get_telemetry_saved_object.test.ts

get_telemetry_saved_object.test.ts.
[#515](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/515)
unit test for get_telemetry_saved_object.test.ts
```
yarn test:jest /home/anan/work/OpenSearch-Dashboards/src/plugins/telemetry/server/telemetry_repository/get_telemetry_saved_object.test.ts
$ node scripts/jest /home/anan/work/OpenSearch-Dashboards/src/plugins/telemetry/server/telemetry_repository/get_telemetry_saved_object.test. …
```

[Test] Enable unit test suite: get_telemetry_saved_object.test.ts

---

src/plugins/telemetry/server/telemetry_collection/get_data_telemetry/get_data_telemetry.test.ts

get_data_telemetry.test.ts.
[#514](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/514)
unit test for get_data_telemetry.test.ts
```
yarn test:jest /home/anan/work/OpenSearch-Dashboards/src/plugins/telemetry/server/telemetry_collection/get_data_telemetry/get_data_telemetry.test.ts
$ node scripts/jest /home/anan/work/OpenSearch-Dashboards/src/plugins/telemetry/server/telemetry_collection/get_data_telemetry/get_data_telemetry …
```

[Test] Enable unit test suite: get_data_telemetry.test.ts

---

src/plugins/telemetry/server/telemetry_collection/get_nodes_usage.test.ts

get_nodes_usage.test.ts.
[#513](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/513)
unit test for get_nodes_usage.test.ts
```
yarn test:jest /home/anan/work/OpenSearch-Dashboards/src/plugins/telemetry/server/telemetry_collection/get_nodes_usage.test.ts
$ node scripts/jest /home/anan/work/OpenSearch-Dashboards/src/plugins/telemetry/server/telemetry_collection/get_nodes_usage.test.ts
PASS …
```

[Test] Enable unit test suite: get_nodes_usage.test.ts

---

src/plugins/telemetry/server/telemetry_collection/get_cluster_stats.test.ts

get_cluster_stats.test.ts.
[#510](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/510)
unit test for get_cluster_stats.test.ts
```
yarn test:jest /home/anan/work/OpenSearch-Dashboards/src/plugins/telemetry/server/telemetry_collection/get_cluster_stats.test.ts
$ node scripts/jest /home/anan/work/OpenSearch-Dashboards/src/plugins/telemetry/server/telemetry_collection/get_cluster_stats.test.ts
PASS …
```

[Test] Enable unit test suite: get_cluster_stats.test.ts 

---

src/plugins/telemetry/server/telemetry_collection/get_cluster_info.test.ts

get_cluster_info.test.ts.
[#509 ](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/509)
unit test for get_cluster_info.test.ts
```
yarn test:jest /home/anan/work/OpenSearch-Dashboards/src/plugins/telemetry/server/telemetry_collection/get_cluster_info.test.ts
$ node scripts/jest /home/anan/work/OpenSearch-Dashboards/src/plugins/telemetry/server/telemetry_collection/get_cluster_info.test.ts
PASS …
```

[Test] Enable unit test suite: get_cluster_info.test.ts

---

src/plugins/telemetry/server/fetcher.test.ts

All the unit tests related to unused telemetry are temporarily skipped after the fork. Unit tests of the disabled telemetry
functions should also be modified correspondingly. To build a clean unit test, we decide to modify and enable all the
working unit tests. This PR checks and enables fetcher.test.ts.
The unit test 'fetches usage and send telemetry' checks function [sendIfDue](https://github.com/opensearch-project/OpenSearch-Dashboards/blob/4293f92190a98b16ea82a06caafe80394376b6b5/src/plugins/telemetry/server/fetcher.ts#L116) in [FetcherTask class](https://github.com/opensearch-project/OpenSearch-Dashboards/blob/4293f92190a98b16ea82a06caafe80394376b6b5/src/plugins/telemetry/server/fetcher.ts#L71). The mocked FetcherTask object calls function …

[Test] Enable unit test suite: fetcher.test.ts

---

src/plugins/telemetry/public/services/telemetry_notifications/telemetry_notifications.test.ts

telemetry_notifications.test.ts.
[#507](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/507)
unit test for telemetry_notifications.test.ts
```
yarn test:jest /home/anan/work/OpenSearch-Dashboards/src/plugins/telemetry/public/services/telemetry_notifications/telemetry_notifications.test.ts
$ node scripts/jest /home/anan/work/OpenSearch-Dashboards/src/plugins/telemetry/public/services/telemetry_notifications/telemetry_notific …
```

[Test] Enable unit test suite:telemetry_notifications

---

src/plugins/telemetry/public/services/telemetry_notifications/render_opted_in_notice_banner.test.ts

working unit tests. This PR modifies and enables
render_opted_in_notice_banner.test.ts.
[#504](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/504)
unit test for render_opted_in_notice_banner.test.ts
```
yarn test:jest /home/anan/work/OpenSearch-Dashboards/src/plugins/telemetry/public/services/telemetry_notifications/render_opted_in_notice_banner.test.ts
$ node scripts/jest /home/anan/work/OpenSearch-Dashboards/src/plugins/telemetry/public/services/telemetry_notificatio …
```

[Test]Enable unit test suite: render_opted_in_notice_banner.test.ts

---

src/plugins/telemetry/public/services/telemetry_notifications/render_opt_in_banner.test.ts

working unit tests. This PR modifies and enables
render_opt_in_banner.test.ts.
[#503  ](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/503)
unit test for render_opt_in_banner.test.ts
```
yarn test:jest /home/anan/work/OpenSearch-Dashboards/src/plugins/telemetry/public/services/telemetry_notifications/render_opt_in_banner.test.ts
$ node scripts/jest /home/anan/work/OpenSearch-Dashboards/src/plugins/telemetry/public/services/telemetry_notifications/render_opt_in_banner.t …
```

[Test] Enable unit test suite: render_opt_in_banner.test.ts 

---

packages/osd-dev-utils/src/run/help.test.ts

Don't find any specific reasons to skip this unit test. Unit test for `getCommandLevelHelp` function passes no `usage `parameters. We can either 1) change the inline snapshot:
`node node_modules/jest-worker/build/workers/processChild.js foo [...names]` ---> `node scripts/jest foo [...names]`
or 2) pass a `usage` parameter to match inline snapshot. No specific pros and cons between these two options.
This PR uses option 2) and passes a `usage` parameter to match inline snapshot.
[#487  ](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/487)
unit test for help.test.ts
```
$ node scripts/jest /packages/osd-dev-utils/src/run/help.test.ts
PASS  packages/osd-dev-utils/src/run/help.test.ts
getHelp()
✓ returns the expected output (5 …
```

[Test] Enable help.test.ts

---

packages/osd-ui-framework/package.json
yarn.lock

This addresses known security vulnerabilities related to node-forge: https://github.com/advisories/GHSA-92xj-mqp7-vmcj
**Before**
```
$ yarn why node-forge
[1/4] Why do we have the module "node-forge"...?
=> Found "node-forge@0.10.0"
info Has been hoisted to "node-forge"
- "workspace-aggregator-769bdfc4-0bbe-4d84-b300-6e610c789125" depends on it
- Specified in "dependencies"
- Hoisted from "_project_#node-forge"
- Hoisted from "_project_#@elastic#request-crypto#node-jose#node-forge"
info Disk size without dependencies: "1.77MB"
info Disk …
```

Bump webpack-dev-server from 3.8.2 to 3.11.0

---

src/plugins/telemetry/public/components/__snapshots__/opt_in_banner.test.tsx.snap
src/plugins/telemetry/public/components/__snapshots__/opt_in_message.test.tsx.snap
src/plugins/telemetry/public/components/__snapshots__/opted_in_notice_banner.test.tsx.snap
src/plugins/telemetry/public/components/opt_in_banner.test.tsx
src/plugins/telemetry/public/components/opt_in_message.test.tsx
src/plugins/telemetry/public/components/opted_in_notice_banner.test.tsx

working unit tests. This PR enables three test suites in dir
src/plugins/telemetry/public/components, which includes:
1) opt_in_banner.test.tsx,
2) opt_in_message.test.tsx,
3) opted_in_notice_banner.test.tsx
[#516](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/516)
[#517](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/517)
[#518](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/518)
unit test for opt_in_banner.test.tsx
```
yarn test:jest …
```

[Test] Enable unit test suites in telemetry/public/components

---

src/plugins/telemetry_management_section/public/components/__snapshots__/opt_in_security_example_flyout.test.tsx.snap
src/plugins/telemetry_management_section/public/components/__snapshots__/telemetry_management_section.test.tsx.snap
src/plugins/telemetry_management_section/public/components/opt_in_example_flyout.test.tsx
src/plugins/telemetry_management_section/public/components/opt_in_security_example_flyout.test.tsx
src/plugins/telemetry_management_section/public/components/telemetry_management_section.test.tsx

All the unit tests related to unused telemetry are temporarily skipped after the fork. Unit tests of the disabled telemetry functions should also be modified correspondingly. To build a clean unit test, we decide to modify and enable all the working unit tests. This PR checks and enables three test suites in src/plugins/telemetry_management_section including: 1) opt_in_example_flyout.test.tsx, 2) opt_in_security_example_flyout.test.tsx, and 3) telemetry_management_section.test.tsx.
[#519](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/519)
[#520](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/520)
[#521](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/521)
unit test for …

[Test] Enable unit test suites in telemetry_management_section

---

src/plugins/telemetry/server/telemetry_collection/get_local_stats.test.ts

get_local_stats.test.ts.
[#512](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/512)
unit test for get_local_stats.test.ts
```
yarn test:jest /home/anan/work/OpenSearch-Dashboards/src/plugins/telemetry/server/telemetry_collection/get_local_stats.test.ts
$ node scripts/jest /home/anan/work/OpenSearch-Dashboards/src/plugins/telemetry/server/telemetry_collection/get_local_stats.test.ts
PASS …
```

[Test] Enable unit test suite: get_local_stats.test.ts

---

src/plugins/telemetry/public/services/telemetry_service.test.ts

working unit tests. This PR modifies and enables
telemetry_service.test.ts
[#499](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/499) (1 test case is skipped)
unit test for telemetry_service.test.ts
```
yarn test:jest /home/anan/work/OpenSearch-Dashboards/src/plugins/telemetry/public/services/telemetry_service.test.ts
yarn run v1.22.5
$ node scripts/jest /home/anan/work/OpenSearch-Dashboards/src/plugins/telemetry/public/services/telemetry_service.test.ts
PASS …
```

[Test] Enable unit test suite: telemetry_service.test.ts

---

src/plugins/telemetry/public/services/telemetry_sender.test.ts

skipped at forking. Unit tests of the disabled telemetry
working unit tests. This PR modifies and enables
telemetry_sender.test.ts.
[#498  ](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/498)
unit test for telemetry_sender.test.ts
```
yarn test:jest /home/anan/work/OpenSearch-Dashboards/src/plugins/telemetry/public/services/telemetry_sender.test.ts
$ node scripts/jest /home/anan/work/OpenSearch-Dashboards/src/plugins/telemetry/public/services/telemetry_sender.test.ts
PASS …
```

[Test] Enable unit test suite: telemetry_sender.test.ts

---

package.json
yarn.lock

Addresses known CVE: https://github.com/advisories/GHSA-6c8f-qphg-qjgp
N/A

Require kind-of v6.0.3

---

src/plugins/index_pattern_management/public/components/edit_index_pattern/edit_index_pattern.tsx

Replacing previous upstream reference within the edit index
pattern page. This does not fully resolve the current issue
due to the link being replaced with a temporary link, and
the link being related to Mappings API documentation but
does not fully replace the content that the original provided.
Will track replacement with:
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/335
Partially: https://github.com/opensearch-project/OpenSearch-Dashboards/issues/482

[DOCS] Replace edit_index_pattern link

---

package.json
yarn.lock

Addresses [WS-2021-0153](https://github.com/mde/ejs/commit/abaee2be937236b1b8da9a1f55096c17dda905fd)
`ejs` is a downstream dependency of `yeoman-generator`, and the newest version of that package still depends on the older version of `ejs`.
Bumps [ejs](https://github.com/mde/ejs) from 2.7.4/3.1.5 to 3.1.6
- [Release notes](https://github.com/mde/ejs/releases)
- [Changelog](https://github.com/mde/ejs/blob/v3.1.6/CHANGELOG.md)
- [Commits](https://github.com/mde/ejs/compare/v2.7.4...v3.1.6)
N/A

Require `ejs` v3.1.6

---

package.json
yarn.lock

Addresses https://github.com/advisories/GHSA-7wpw-2hjm-89gp
Bumps [merge](https://github.com/yeikos/js.merge) from 1.2.1 to 2.1.1
- [Release notes](https://github.com/yeikos/js.merge/releases)
- [Commits](https://github.com/yeikos/js.merge/compare/v1.2.1...v2.1.1)
Merge 1.2.1 is a downstream dependency of `sass-lint` which is an unmaintained repo without any newer versions. I've opened #551 to address this as a longer-term solution.
**Before**
```
$ yarn why merge
[1/4] Why do we have the module "merge"...?
=> Found "merge@1.2.1"
- …
```

Upgrade merge from 1.2.1 to 2.1.1

---

src/cli_plugin/install/zip.test.js

With existing fixture, test verify consistency of modes of files inside zip.test.js fails. This is due to diff file mode in different system when doing same command or operation. For example, in our ubuntu, when create a file using mkdir cmd, the file mode is 775. But local machine, the file mode is 755.
```
local env: drwxr-xr-x  62 ananzh  staff   1.9K Jun 23 19:12 OpenSearch-Dashboards (755)
Ubuntu: drwxrwxr-x 24 anan anan 4096 Jun 24 01:04 OpenSearch-Dashboards (775)
```
After unzip executable has mode 777 and not-executable has mode 644. These two numbers are fixed. They are not dependent on diff system or folder mode where you unzip the files. However, the following two results:
```
getMode(path.resolve(tempPath,'executable'))
getMode(path.resolve(tempPath,’not-executable'))
```
are …

[Test] Remove unit test case in zip.test.js

---

packages/osd-ui-framework/package.json
yarn.lock

Addresses security vulnerabilities related to versions of `diff` before v3.5.0: 
* https://github.com/advisories/GHSA-h6ch-v84p-w6p9
* https://github.com/advisories/GHSA-hr2v-3952-633q
v4.13.0 is the most recent version that supports Node v10.
None of the breaking changes listed impact the build.
- [Release notes](https://github.com/yeoman/generator/releases)
- [Commits](https://github.com/yeoman/generator/compare/v1.1.1...v4.13.0)
**Before**
```$ yarn why diff
[1/4] Why do we have the module "diff"...?
=> Found "diff@3.5.0"
info Has been hoisted to "diff"
info Reasons …
```

Bump yeoman-generator from 1.1.1 to 4.13.0

---

Dockerfile
package.json
yarn.lock

Functional tests were failing in Jenkins pipelines because Docker was pulling the latest version of Chrome instead of using the same version that is defined for `chromedriver`. This changes fixes that bug by fetching a specific version of Chrome.
Upgrades [chromedriver](https://github.com/giggio/node-chromedriver) from 88.0.0 to 91.0.1
- [Release notes](https://github.com/giggio/node-chromedriver/releases)
Resolves #546

Upgrade chromedriver, match version in Dockerfile

---

package.json
yarn.lock

Addresses [WS-2020-0341](https://github.com/jxson/front-matter/commit/f71652cfef6f296f7b5ab495461914ae61d76da2)
Also removes unnecessary resolutions for dependencies that didn't have conflicts.
`front-matter` 2.1.2 is a downstream dependency of `sass-lint` which is an unmaintained repo without any newer versions. I've opened #551 to address this as a longer-term solution.
Upgrades [front-matter](https://github.com/jxson/front-matter) from 2.1.2 to 4.0.2
- [Release notes](https://github.com/jxson/front-matter/releases)
- [Commits](https://github.com/jxson/front-matter/compare/v2.1.2...v4.0.2)
**Before**
```
$ yarn why front-matter
[1/4] Why do we have the module "front-matter"...?
warning Resolution field "typescript@4.0.2" is …
```

Require front-matter v4.0.2, fix resolutions

---

package.json
yarn.lock

Addresses https://github.com/advisories/GHSA-7p7h-4mm5-852v
Older versions of `trim-newlines` are downstream dependencies of `yo` and `node-sass` which do not have newer versions available/compatible.
```
$ yarn why trim-newlines
[1/4] Why do we have the module "trim-newlines"...?
=> Found "trim-newlines@3.0.0"
info Has been hoisted to "trim-newlines"
- "workspace-aggregator-02cb94b9-b0be-47c0-838d-cf7b24fa9781" depends on it
- Hoisted from "_project_#@osd#config-schema#tsd#meow#trim-newlines"
- Hoisted from …
```

Require `trim-newlines` v3.0.1

---

src/core/public/doc_links/doc_links_service.ts
src/core/server/ui_settings/settings/date_formats.ts
src/plugins/console/server/lib/spec_definitions/json/generated/msearch.json
src/plugins/console/server/lib/spec_definitions/json/generated/msearch_template.json
src/plugins/dashboard/public/application/help_menu/help_menu_util.ts
src/plugins/data/server/ui_settings.ts
src/plugins/discover/public/application/angular/context/api/utils/get_opensearch_query_sort.ts
src/plugins/discover/public/application/components/help_menu/help_menu_util.js
src/plugins/index_pattern_management/public/components/index_pattern_table/empty_state/__snapshots__/empty_state.test.tsx.snap
src/plugins/maps_legacy/server/ui_settings.ts
src/plugins/vis_type_vega/public/components/vega_help_menu.tsx

Replacing previous upstream references with working links.
This does not fully resolve the current issue due to the link
being replaced with a temporary link, and the link directing
to related documentation if it exists but some do not so it
sends it to the basic OpenSearch Dashboards documentation which
is a bad experience but better than a 404.
Will track replacement with:
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/335
Partial: https://github.com/opensearch-project/OpenSearch-Dashboards/issues/335

[DOCS] Replace settings and help menu links

---

src/cli_plugin/install/install.js
src/cli_plugin/install/opensearch_dashboards.js

This reverts commit 747ef8eb6fc15b62c26a9af832561254b3522c42.
Reverting for now because the full impact is not known and requires
subsequent commits to mitigate some confusion related to CLI output.
Also, it seems like in the code there exists verification on the code
that plugins should explicitly be camelCase. So this merits more
discussion but also could be bundled into a feature branch related to kebab
casing and prioritized for a vNext release.
Will create a new PR to re-enable this casing.
Issues related:
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/322
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/465
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/366

Revert "Default to converting folder name for cli plugin to kebab-case (#347)"

---

src/cli_plugin/install/install.js
src/cli_plugin/install/opensearch_dashboards.js

This reverts commit 747ef8eb6fc15b62c26a9af832561254b3522c42.
Reverting for now because the full impact is not known and requires
subsequent commits to mitigate some confusion related to CLI output.
Also, it seems like in the code there exists verification on the code
that plugins should explicitly be camelCase. So this merits more
discussion but also could be bundled into a feature branch related to kebab
casing and prioritized for a vNext release.
Will create a new PR to re-enable this casing.
Issues related:
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/322
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/465
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/366

Revert "Default to converting folder name for cli plugin to kebab-case (#357)"

---

release-notes/opensearch-dashboards.release-notes-1.0.0.md

Adding the release note for OpenSearch-Dashboards 1.0.0 (GA)
This is generated using the tool: 
https://github.com/ariatemplates/git-release-notes
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/585

Add Release note for 1.0.0

---

release-notes/opensearch-dashboards.release-notes-1.0.0.md

Adding the release note for OpenSearch-Dashboards 1.0.0 (GA)
This is generated using the tool:
https://github.com/ariatemplates/git-release-notes
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/585
https://github.com/opensearch-project/OpenSearch-Dashboards/pull/587

[1.0] Add Release note for 1.0.0

---

release-notes/opensearch-dashboards.release-notes-1.0.0.md

Adding the release note for OpenSearch-Dashboards 1.0.0 (GA)
This is generated using the tool:
https://github.com/ariatemplates/git-release-notes
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/585
https://github.com/opensearch-project/OpenSearch-Dashboards/pull/587

[1.x] Add Release note for 1.0.0

---

src/core/TESTING.md

Remove incorrect reference in testing.md

[Bug] remove incorrect reference in testing.md

---

github_checks_reporter.json

github-checks-reporter is a task wrapper that provides expressive
CI feedback via GitHub checks. Currently, we don’t have our own
appKey. To avoid any confusions, this PR removed the old key.

[Bug] Remove appKey in github-checks-reporter

---

package.json

Package.json has a broken homepage link. This PR fixes this link.

[Bug] Fix broken link in package.json

---

packages/opensearch-eslint-config-opensearch-dashboards/README.md
packages/opensearch-eslint-config-opensearch-dashboards/package.json

/packages/opensearch-eslint-config-opensearch-dashboards/package.json
has broken homepage and bug report links. This PR fixes these two links.

[Bug] Fix broken links in package.json in opensearch-eslint-config-opensearch-dashboards

---

packages/osd-plugin-generator/README.md

The versions in packages/osd-plugin-generator/README.md are still 6.x
like test using mocha, which should be cleaned. This PR fixes the versions
and cleans out the old concepts.

[Bug] Clean concepts in packages/osd-plugin-generator/README.md

---

packages/osd-plugin-helpers/README.md

The versions in packages/osd-plugin-helpers/README.md are still 6.3
like checking versions, which should be cleaned. This PR fixes the
versions and cleans out the old concepts.

[Bug] Clean concepts in packages/osd-plugin-helpers/README.md

---

packages/opensearch-safer-lodash-set/LICENSE
packages/opensearch-safer-lodash-set/package.json

Both LICENSE and package.json in packages/opensearch-safter-lodash-set
have broken links. This PR fixes links in these two files.

[Bug] Fix broken links in packages/opensearch-safter-lodash-set

---

packages/osd-opensearch/README.md

Currenlty, /packages/osd-opensearch/README.md still have license concepts. This PR cleans the concepts.

[Bug] Remove license concepts in packages/osd-opensearch

---

package.json

Package.json has a broken homepage link. This PR fixes this link.
https://github.com/opensearch-project/OpenSearch-Dashboards/pull/604

[1.x][Bug] Fix broken link in package.json

---

package.json

Package.json has a broken homepage link. This PR fixes this link.
https://github.com/opensearch-project/OpenSearch-Dashboards/pull/604

[1.0][Bug] Fix broken link in package.json

---

github_checks_reporter.json

github-checks-reporter is a task wrapper that provides expressive
CI feedback via GitHub checks. Currently, we don’t have our own
appKey. To avoid any confusions, this PR removed the old key.
https://github.com/opensearch-project/OpenSearch-Dashboards/pull/603

[1.x][Bug] Remove appKey in github-checks-reporter

---

packages/osd-opensearch/README.md

Currenlty, /packages/osd-opensearch/README.md still have license
concepts. This PR cleans the concepts.
https://github.com/opensearch-project/OpenSearch-Dashboards/pull/602

[1.x][Bug] Remove license concepts in packages/osd-opensearch

---

packages/osd-opensearch/README.md

Currenlty, /packages/osd-opensearch/README.md still have license
concepts. This PR cleans the concepts.
https://github.com/opensearch-project/OpenSearch-Dashboards/pull/602

[1.0][Bug] Remove license concepts in packages/osd-opensearch

---

packages/opensearch-safer-lodash-set/LICENSE
packages/opensearch-safer-lodash-set/package.json

Both LICENSE and package.json in packages/opensearch-safter-lodash-set
have broken links. This PR fixes links in these two files.
https://github.com/opensearch-project/OpenSearch-Dashboards/pull/607

[1.x][Bug] Fix links in packages/opensearch-safter-lodash-set

---

packages/opensearch-safer-lodash-set/LICENSE
packages/opensearch-safer-lodash-set/package.json

Both LICENSE and package.json in packages/opensearch-safter-lodash-set
have broken links. This PR fixes links in these two files.
https://github.com/opensearch-project/OpenSearch-Dashboards/pull/607

[1.0][Bug] Fix links in packages/opensearch-safter-lodash-set

---

packages/osd-plugin-helpers/README.md

The versions in packages/osd-plugin-helpers/README.md are still 6.3
like checking versions, which should be cleaned. This PR fixes the
versions and cleans out the old concepts.
https://github.com/opensearch-project/OpenSearch-Dashboards/pull/610

[1.x][Bug] Clean concepts in packages/osd-plugin-helpers

---

packages/osd-plugin-helpers/README.md

The versions in packages/osd-plugin-helpers/README.md are still 6.3
like checking versions, which should be cleaned. This PR fixes the
versions and cleans out the old concepts.
https://github.com/opensearch-project/OpenSearch-Dashboards/pull/610

[1.0][Bug] Clean concepts in packages/osd-plugin-helpers

---

packages/osd-plugin-generator/README.md

The versions in packages/osd-plugin-generator/README.md are still 6.x
like test using mocha, which should be cleaned. This PR fixes the versions
and cleans out the old concepts.
https://github.com/opensearch-project/OpenSearch-Dashboards/pull/609

[1.x][Bug] Clean concepts in packages/osd-plugin-generator

---

packages/osd-plugin-generator/README.md

The versions in packages/osd-plugin-generator/README.md are still 6.x
like test using mocha, which should be cleaned. This PR fixes the versions
and cleans out the old concepts.
https://github.com/opensearch-project/OpenSearch-Dashboards/pull/609

[1.0][Bug] Clean concepts in packages/osd-plugin-generator

---

packages/opensearch-datemath/readme.md

/packages/opensearch-datemath/readme.md still has old concepts.
This PR replaces the word Kibana to OpenSearch Dashboards.
https://github.com/opensearch-project/OpenSearch-Dashboards/pull/606

[1.x][Bug] Replace words in /packages/opensearch-datemath

---

packages/opensearch-datemath/readme.md

/packages/opensearch-datemath/readme.md still has old concepts.
This PR replaces the word Kibana to OpenSearch Dashboards.
https://github.com/opensearch-project/OpenSearch-Dashboards/pull/606

[1.0][Bug] Replace words in /packages/opensearch-datemath

---

packages/opensearch-eslint-config-opensearch-dashboards/README.md
packages/opensearch-eslint-config-opensearch-dashboards/package.json

Both package.json and README.md in
/packages/opensearch-eslint-config-opensearch-dashboards
have some broken links or old concepts. This PR fixes these two files.
https://github.com/opensearch-project/OpenSearch-Dashboards/pull/605

[1.x][Bug] Fix links in opensearch-eslint-config-opensearch-dashboards

---

packages/opensearch-eslint-config-opensearch-dashboards/README.md
packages/opensearch-eslint-config-opensearch-dashboards/package.json

Both package.json and README.md in
/packages/opensearch-eslint-config-opensearch-dashboards
have some broken links or old concepts. This PR fixes these two files.
https://github.com/opensearch-project/OpenSearch-Dashboards/pull/605

[1.0][Bug] Fix links in opensearch-eslint-config-opensearch-dashboards

---

github_checks_reporter.json

github-checks-reporter is a task wrapper that provides expressive
CI feedback via GitHub checks. Currently, we don’t have our own
appKey. To avoid any confusions, this PR removed the old key.
https://github.com/opensearch-project/OpenSearch-Dashboards/pull/603

[1.0][Bug] Remove appKey in github-checks-reporter

---

src/core/TESTING.md

There is a kibana closed issue reference under test
"authenticated / non-authenticated user access".
We removed the reference in this PR.
https://github.com/opensearch-project/OpenSearch-Dashboards/pull/597

[1.x][Bug] remove incorrect reference in testing.md

---

src/core/TESTING.md

There is a kibana closed issue reference under test
"authenticated / non-authenticated user access".
We removed the reference in this PR.
https://github.com/opensearch-project/OpenSearch-Dashboards/pull/597

[1.0][Bug] remove incorrect reference in testing.md

---

packages/osd-optimizer/README.md

/packages/osd-optimizer/README.md has a kibana issue reference. This PR
removes the issue.

[Bug] Remove kibana issue from /packages/osd-optimizer/README.md

---

packages/osd-optimizer/README.md

/packages/osd-optimizer/README.md has a kibana issue reference. This PR
replaces the kibana issue with an open discuss issue.
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/608

[1.0][Bug] Replace issue in /packages/osd-optimizer/README.md

---

packages/osd-optimizer/README.md

/packages/osd-optimizer/README.md has a kibana issue reference. This PR
replaces the kibana issue with an open discuss issue.
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/608

[1.x][Bug] Replace issue in /packages/osd-optimizer/README.md

---

packages/osd-opensearch/src/artifact.js
packages/osd-opensearch/src/artifact.test.js

Removing the graceful failures for ARM64 snapshot testing and
updating tests.
Previously, snapshots for ARM64 were not available but now they are
so this allows developers to run tests for that arch out of the box
whereas before they had to set the snapshot manually.
Partial: https://github.com/opensearch-project/OpenSearch-Dashboards/issues/475

[Tests] ARM64 artifacts for testing

---

src/plugins/data/public/ui/filter_bar/_index.scss
src/plugins/data/public/ui/filter_bar/filter_bar.tsx
src/plugins/data/public/ui/filter_bar/filter_editor/_filter_editor.scss
src/plugins/data/public/ui/filter_bar/filter_editor/_index.scss
src/plugins/data/public/ui/filter_bar/filter_editor/index.tsx
src/plugins/data/public/ui/filter_bar/filter_editor/phrase_value_input.tsx
src/plugins/data/public/ui/filter_bar/filter_editor/phrases_values_input.tsx
src/plugins/data/public/ui/filter_bar/filter_editor/range_value_input.tsx
src/plugins/data/public/ui/filter_bar/filter_editor/value_input_type.tsx
src/plugins/data/public/ui/filter_bar/filter_item.tsx

Signed-off-by: galangel <gal0angel@gmail.com>
The change resizes the modal to 600 ( instead of 400 ) and uses the full-width prop in the form components to take advantage of the space.
also Removed the unused styles 
I explicitly left the range input at false because I think it looks better like this than with full width
Fullscreen at 100%
[Filters popover modal is too small](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/351)

Increase filters popover size and use full width in form components 

---

src/core/public/application/ui/app_container.test.tsx
src/core/public/core_app/status/components/server_status.test.tsx
src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/components/header/__snapshots__/header.test.tsx.snap
src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/components/header/header.test.tsx
src/plugins/index_pattern_management/public/components/edit_index_pattern/scripted_fields_table/components/header/__snapshots__/header.test.tsx.snap
src/plugins/index_pattern_management/public/components/edit_index_pattern/scripted_fields_table/components/header/header.test.tsx
src/plugins/index_pattern_management/public/components/field_editor/components/scripting_call_outs/__snapshots__/warning_call_out.test.tsx.snap
src/plugins/index_pattern_management/public/components/field_editor/components/scripting_call_outs/warning_call_out.test.tsx
src/plugins/telemetry_management_section/public/components/telemetry_management_section.test.tsx
src/plugins/vis_default_editor/public/components/controls/percentiles.test.tsx
src/test_utils/public/enzyme_helpers.tsx

In the FunctionComponent unit tests, we see many console errors:
```
Could not find required intl object. <IntlProvider> needs to
exist in the component ancestry. 
```
This is because for some unit tests, we mount the FunctionComponent(with Enzyme's mount()) , which access to the react-intl context by FormattedMessage without their <IntlProvider /> parent wrapper.
This PR solves 7 out of 8 unit tests with this issue by wrapping the <IntlProvider />. The enzyme_helper contains functions with injected intl object and 4 unit tests can eliminate console error by switching mount to mountWithIntl and render to renderWithIntl. For the other 3 unit tests, the argument type wrappingComponent is not assignable to parameter of type context. This PR wraps these components with simple IntlProvider. …

[Test] Wrap FunComponent in unit test with IntlProvider

---

src/core/public/application/ui/app_container.test.tsx
src/core/public/core_app/status/components/server_status.test.tsx
src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/components/header/__snapshots__/header.test.tsx.snap
src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/components/header/header.test.tsx
src/plugins/index_pattern_management/public/components/edit_index_pattern/scripted_fields_table/components/header/__snapshots__/header.test.tsx.snap
src/plugins/index_pattern_management/public/components/edit_index_pattern/scripted_fields_table/components/header/header.test.tsx
src/plugins/index_pattern_management/public/components/field_editor/components/scripting_call_outs/__snapshots__/warning_call_out.test.tsx.snap
src/plugins/index_pattern_management/public/components/field_editor/components/scripting_call_outs/warning_call_out.test.tsx
src/plugins/telemetry_management_section/public/components/telemetry_management_section.test.tsx
src/plugins/vis_default_editor/public/components/controls/percentiles.test.tsx
src/test_utils/public/enzyme_helpers.tsx

In the FunctionComponent unit tests, we see many console errors:
`Could not find required intl object. <IntlProvider> needs to
exist in the component ancestry. `
This is because for some unit tests, we mount the FunctionComponent
(with Enzyme's mount()) , which access to the react-intl context by
FormattedMessage without their <IntlProvider /> parent wrapper.
This PR solves 7 out of 8 unit tests with this issue by wrapping the
<IntlProvider /> either through original enzyme_helper functions or
a simple wrapper wrapWithIntl.
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/593
https://github.com/opensearch-project/OpenSearch-Dashboards/pull/654

[1.x][Test] Wrap FunComponent in unit test with IntlProvider

---

README.md

* Add darkmode logo
* Add a ToC and relevant sections
* Add Project Resources to replace how can you help", "running tests", "guiding principles", etc.
* Add CoC
* Add License
* Add Copyright
Partially Resolve: Issue #592

Adding updated content to README.md and remove superfluous sections 

---

CONTRIBUTING.md

* Move ToC to top to match the OpenSearch repo
* Minor formatting changes
* Remove reference to pre-alpha state
* Add links for opening issues
* Remove "w00t!!!" from end of file
Partially Resolve: Issue #592

Removing incorrect CONTRIBUTING.md language and adding updated links

---

MAINTAINERS.md

* Add path to .github maintainer doc. 
* Add path to CONTRIBUTING.md
Partially Resolve: Issue #592

Updating MAINTAINERS.md with correct links

---

src/plugins/vis_type_timeline/public/timeline_vis_type.tsx

Icon was not loading in the Visualize list because it was
referencing a non-existant icon. Other parts of the code
loads the icon correctly, so updated the icon to an existing
icon.
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/658

[Bug] fix timeline icon in Visualize list

---

src/plugins/data/server/search/search_service.ts

Run unit test suite search_service.test.ts has a console error:
```
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'aggs' of undefined
```
This is caused by a missing promise result check in the setup fun
in search_service.ts. If the promise result is empty (or null/undefined),
then any properties of the empty result is undefined. In our case,
`aggs` in `if (value.search.aggs.shardDelay.enabled)` is undefined.
In this PR, we fixed this issue by adding a value check in setup fun.
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/594
```
yarn test:jest /home/anan/work/OpenSearch-Dashboards/src/plugins/data/server/search/search_service.test.ts
yarn run v1.22.5
$ node scripts/jest …
```

[Test] Fix console error in search_service.test.ts 

---

src/plugins/data/server/search/search_service.ts

Run unit test suite search_service.test.ts has a console error:
```
UnhandledPromiseRejectionWarning: TypeError: Cannot read
property 'aggs' of undefined
```
This is caused by a missing promise result check in the setup fun
in search_service.ts. If the promise result is empty (or null/undefined),
then any properties of the empty result is undefined. In our case,
`aggs` in `if (value.search.aggs.shardDelay.enabled)` is undefined.
In this PR, we fixed this issue by adding a value check in setup fun.
Issues resolved:
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/594
Backport PR:
https://github.com/opensearch-project/OpenSearch-Dashboards/pull/595

[1.x][Test] Fix console error in search_service.test.ts 

---

packages/osd-opensearch/src/artifact.js
packages/osd-opensearch/src/artifact.test.js

Removing the graceful failures for ARM64 snapshot testing and
updating tests.
Previously, snapshots for ARM64 were not available but now they are
so this allows developers to run tests for that arch out of the box
whereas before they had to set the snapshot manually.
Backport PR:
https://github.com/opensearch-project/OpenSearch-Dashboards/pull/641
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/475 [Partially]

[1.x][Tests] ARM64 artifacts for testing

---

src/plugins/vis_type_timeline/public/timeline_vis_type.tsx

Icon was not loading in the Visualize list because it was
referencing a non-existant icon. Other parts of the code
loads the icon correctly, so updated the icon to an existing
icon.
Backport PR:
https://github.com/opensearch-project/OpenSearch-Dashboards/pull/659
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/658

[1.x][Bug] fix timeline icon in Visualize list

---

src/plugins/index_pattern_management/public/components/field_editor/field_editor.test.tsx

Currently, unit test field_editor.test.tsx shows a console warning:
```
React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. 
```
This warning is because EuiCodeEditor is missing in the mock of elastic/eui, which causes undefined EuiCodeEditor in the test.
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/673
unit test for field_editor.test.tsx
```
yarn test:jest src/plugins/index_pattern_management/public/components/field_editor/field_editor.test.tsx -u
yarn run v1.22.5
$ node scripts/jest src/plugins/index_pattern_management/public/components/field_editor/field_editor.test.tsx -u
PASS  src/plugins/index_pattern_management/public/components/field_editor/field_editor.test.tsx …
```

[Test] Fix console warning in field_editor.test.tsx

---

CODE_OF_CONDUCT.md

Signed-off-by: Sagar Rout <sagar@sagarrout.com>
Fixes broken Code of Conduct markdown link in README.md
Resolves #676

Add CODE_OF_CONDUCT markdown file to fix broken link in README

---

src/plugins/index_pattern_management/public/components/field_editor/field_editor.test.tsx

Currently, unit test field_editor.test.tsx shows a console warning:
```
React.createElement: type is invalid -- expected a string
(for built-in components) or a class/function (for composite components)
but got: undefined. 
```
This warning is because EuiCodeEditor is missing in the mock of elastic/eui,
which causes undefined EuiCodeEditor in the test.
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/673
https://github.com/opensearch-project/OpenSearch-Dashboards/pull/674

[1.x][Test] Fix console warning in field_editor.test.tsx

---

DEVELOPER_GUIDE.md
README.md

* Add development environment setup link to Welcome section of the README.
* Remove broken Admin Responsibilities link from the README.
Resolves https://github.com/opensearch-project/OpenSearch-Dashboards/issues/666

Add Getting Started section to the Developer Guide

---

CODE_OF_CONDUCT.md

Signed-off-by: Sagar Rout <sagar@sagarrout.com>
Backport of #677 to 1.x.

[1.x] [BUG] fix CODE_OF_CONDUCT link in README.md (#677)

---

src/plugins/index_pattern_management/public/components/field_editor/__snapshots__/field_editor.test.tsx.snap

Previous PR #674 did not include updated snapshots.
Related to https://github.com/opensearch-project/OpenSearch-Dashboards/issues/673
```
$ yarn test:jest
...
Test Suites: 1 skipped, 1434 passed, 1434 of 1435 total
Tests:       24 skipped, 9 todo, 10637 passed, 10670 total
Snapshots:   2410 passed, 2410 total
Time:        47.32 s
Ran all test suites.
Done in 49.23s.
$ yarn test:jest_integration
...
Test Suites: 50 passed, 50 total
Tests:       4 skipped, 433 passed, 437 total
Snapshots:   73 passed, 73 total
Time:        307.323 s
Ran all test suites.
│ info [opensearch] cleanup complete
Done in 309.62s.
```

Update FieldEditor test snapshots

---

yarn.lock

Bumps [postcss](https://github.com/postcss/postcss) from 7.0.32 to 7.0.36
- [Release notes](https://github.com/postcss/postcss/releases/tag/7.0.36)
- [Changelog](https://github.com/postcss/postcss/blob/7.0.36/CHANGELOG.md)
- [Commits](https://github.com/postcss/postcss/compare/7.0.32...7.0.36)
Addresses https://github.com/advisories/GHSA-hwj9-h5mp-3pm3

Bump `postcss` from 7.0.32 to 7.0.36

---

yarn.lock

Bumps [ws](https://github.com/websockets/ws) from 7.3.1 to 7.5.3
- [Release notes](https://github.com/websockets/ws/releases/tag/7.5.3)
- [Commits](https://github.com/websockets/ws/compare/7.3.1...7.5.3)
Addresses https://github.com/advisories/GHSA-6fc8-4gx4-v693

Bump `ws` from 7.3.1 to 7.5.3

---

src/plugins/home/server/services/tutorials/tutorials_registry.ts

We removed the ability to access the tutorials page because we do
not have replacement for the links provided by the tutorials.
However, users could directly navigate to those pages if they typed
into the browser or had a bookmark.
This removes those routes from the router.
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/647

[Bug] remove tutorials from router temporarily

---

src/plugins/home/server/services/tutorials/tutorials_registry.ts

We removed the ability to access the tutorials page because we do
not have replacement for the links provided by the tutorials.
However, users could directly navigate to those pages if they typed
into the browser or had a bookmark.
This removes those routes from the router.
Issues resolved:
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/647
Backport PR:
https://github.com/opensearch-project/OpenSearch-Dashboards/pull/675

[1.x][Bug] remove tutorials from router temporarily

---

yarn.lock

[1.x] Bump `postcss` from 7.0.32 to 7.0.36 (#698)

---

TESTING.md

Adding TESTING.md to the project as referenced in the README.
The content is some general information about testing and should not
be considered exhaustive.
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/667

[Docs] Added TESTING.md

---

SECURITY.md

Adding SECURITY.md as it is defined in the README. Will inform developers
how to report security issues.
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/714

[Docs] Added SECURITY.md

---

DEVELOPER_GUIDE.md

As discussed in [this PR](https://github.com/opensearch-project/documentation-website/pull/123) and [this forum thread](https://discuss.opendistrocommunity.dev/t/error-when-starting-a-single-node-opensearch-on-docker/6645/2), running OpenSearch Dashboards using a docker image for OpenSearch is not possible straight away if you don't change the default configuration in `opensearch_dashboards.yml`.
I felt like it was a good idea to document it, and I used this opportunity to improve the developer guide. As the docker images have now been published, I also felt like it was a better idea to offer this way of running an OpenSearch instance, over the other two.
Feel free to tell me if you'd prefer to keep the other options!
**Screenshot of the generated markdown:**
N/A

[Docs] Improve the getting started section of the developer guide

---

package.json
packages/osd-opensearch/src/artifact.js

Bumps the minor to 1.1 for the 1.0 release.
Needed to modify the artifact.js file to the newly formatted artifact URL
so that tests work out of the box.
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/681

[Build] Version bump for 1.1 release

---

yarn.lock

[1.x] Bump `ws` from 7.3.1 to 7.5.3 (#699)

---

DEVELOPER_GUIDE.md

- Add more detailed explanations to setup a dev environment
- Recommend the docker version of OpenSearch as the default backend
- Improve the UI of the guide with a new header
- Remove the nvm installation section, and link to its docs instead
Backport PR:
https://github.com/opensearch-project/OpenSearch-Dashboards/pull/710
Signed-off-by: closingin <2735603+closingin@users.noreply.github.com>

[1.x][Docs] Improve the getting started section of the developer guide

---

package.json
packages/osd-opensearch/src/artifact.js

Bumps the minor to 1.1 for the 1.0 release.
Needed to modify the artifact.js file to the newly formatted artifact URL
so that tests work out of the box.
Backport PR:
https://github.com/opensearch-project/OpenSearch-Dashboards/pull/722
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/681

[1.x][Build] Version bump for 1.1 release

---

.dockerignore
DEVELOPER_GUIDE.md

The change adds an entry in the README on how to build the Docker image,
additionally a `.dockerignore` has been added.
None

docker: add .dockerignore, add build instructions

---

src/core/server/opensearch/version_check/opensearch_opensearch_dashboards_version_compatability.test.ts
src/core/server/opensearch/version_check/opensearch_opensearch_dashboards_version_compatability.ts

Enables the version check to work specifically in the case of OSD 1.X and
legacy 7.10.2. This will avoid conflicts in future versions of the application
where Dashboards is not compatible with the Engines on version differences.
Testing for verifying compatible legacy version.
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/720

[Build] Dashboards working with legacy engines 7.10.2

---

src/core/public/doc_links/doc_links_service.test.ts
src/core/public/doc_links/doc_links_service.ts
src/core/server/ui_settings/settings/date_formats.ts
src/plugins/console/server/lib/spec_definitions/json/generated/msearch.json
src/plugins/console/server/lib/spec_definitions/json/generated/msearch_template.json
src/plugins/data/server/ui_settings.ts
src/plugins/discover/public/application/angular/context/api/utils/get_opensearch_query_sort.ts
src/plugins/index_pattern_management/public/components/edit_index_pattern/edit_index_pattern.tsx
src/plugins/index_pattern_management/public/components/index_pattern_table/empty_state/__snapshots__/empty_state.test.tsx.snap
src/plugins/maps_legacy/public/map/map_messages.js
src/plugins/maps_legacy/server/ui_settings.ts
src/plugins/vis_type_vega/public/components/vega_help_menu.tsx

Updating references to the doc site from docs-beta.opensearch.org
to the production site of opensearch.org/docs.
Did not remove the TODOs because we do not have replacements for the
content yet.
Backport PR:
https://github.com/opensearch-project/OpenSearch-Dashboards/pull/733
Partial: https://github.com/opensearch-project/OpenSearch-Dashboards/issues/335

[1.x][Docs] Update doc refs from beta to prod

---

packages/osd-ui-framework/doc_site/src/components/guide_nav/_guide_nav.scss
packages/osd-ui-framework/doc_site/src/components/guide_nav/guide_nav.js
packages/osd-ui-framework/doc_site/webpack.config.js
src/plugins/data/common/field_formats/field_formats_registry.ts

Allowing for the following builds to complete successfully:
* `yarn build:types`
* `yarn uiFramework:build`
* `yarn uiFramework:start`
Not positive about the expected results when running uiFramework:start
but it seems to be on par with the legacy 7.10.2 version.
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/680

[Build] build:types and uiFramework run successfully

---

src/plugins/data/server/ui_settings.ts

Remove deprecation message from batchSearches in advanced settings.
It referenced OpenSearch Dashboards 8.0, which is just from the legacy
application.
No plan to deprecate yet.
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/363

[Purify] Remove deprecation message in batchSearches settings

---

packages/osd-ui-framework/doc_site/src/components/guide_nav/_guide_nav.scss
packages/osd-ui-framework/doc_site/src/components/guide_nav/guide_nav.js
packages/osd-ui-framework/doc_site/webpack.config.js
src/plugins/data/common/field_formats/field_formats_registry.ts

Allowing for the following builds to complete successfully:
* `yarn build:types`
* `yarn uiFramework:build`
* `yarn uiFramework:start`
Not positive about the expected results when running uiFramework:start
but it seems to be on par with the legacy 7.10.2 version.
Issue resolved:
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/680
Backport PR:
https://github.com/opensearch-project/OpenSearch-Dashboards/pull/734

[1.x][Build] build:types and uiFramework run successfully

---

src/plugins/data/server/ui_settings.ts

Remove deprecation message from batchSearches in advanced settings.
It referenced OpenSearch Dashboards 8.0, which is just from the legacy
application.
No plan to deprecate yet.
Issue resolved:
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/363
Backport PR:
https://github.com/opensearch-project/OpenSearch-Dashboards/pull/735

[1.x][Purify] Remove deprecation message in batchSearches settings

---

package.json
yarn.lock

Requires [tar](https://github.com/npm/node-tar) 6.1.6 - upgrade from 4.4.13 and 6.0.2
- [Release notes](https://github.com/npm/node-tar/releases/tag/v6.1.6)
- [Changelog](https://github.com/npm/node-tar/blob/main/CHANGELOG.md)
- [Commits](https://github.com/npm/node-tar/compare/v4.4.13...v6.1.6)
There are no breaking changes from 4.4 to 6.0, so I chose to upgrade instead of bumping each of the minor versions.
**Before**:
```
$ yarn why tar
[1/4] Why do we have the module "tar"...?
=> Found "tar@4.4.13"
info Has been …
```

Upgrade `tar` from 4.4.13/6.0.2 to 6.1.6

---

yarn.lock

[1.x] Bump url-parse from 1.5.1 to 1.5.3 (#727)

---

yarn.lock

[1.x] Bump jszip from 3.3.0 to 3.7.1 (#728)

---

package.json
yarn.lock

Addresses https://github.com/advisories/GHSA-5955-9wpr-37jh
Bumps [tar](https://github.com/npm/node-tar) from 6.1.6 to 6.1.11.
- [Release notes](https://github.com/npm/node-tar/releases)
- [Changelog](https://github.com/npm/node-tar/blob/main/CHANGELOG.md)
- [Commits](https://github.com/npm/node-tar/compare/v6.1.6...v6.1.11)
N/A

Bump `tar` from 6.1.6 to 6.1.11

---

package.json
yarn.lock

[1.x] Bump `tar` from 6.1.6 to 6.1.11 (#762)

---

README.md

Removed Amazon copyright, the correct copyright for OpenSearch projects is "Copyright OpenSearch Contributors".
Resolves https://github.com/opensearch-project/OpenSearch-Dashboards/issues/711

Correct copyright notices to reflect Copyright OpenSearch Contributors

---

README.md

Correct copyright notices in README (#712)

---

config/opensearch_dashboards.yml
src/core/server/opensearch_dashboards_config.ts
src/core/server/rendering/rendering_service.test.ts
src/core/server/rendering/rendering_service.tsx
src/core/server/rendering/types.ts
src/core/server/rendering/views/__snapshots__/template.test.tsx.snap
src/core/server/rendering/views/styles.tsx
src/core/server/rendering/views/template.test.tsx
src/core/server/rendering/views/template.tsx
src/legacy/server/config/schema.js

US3: User can set animated version of logo and title in the opensearch_dashboards.yml and see it in the application at run time for the loading page.
User need to input a valid URL for opensearchDashboards.branding.loadingLogoUrl and a valid string for opensearchDashboards.branding.title in the opensearch_dashboards.yml file.
* If the URL is invalid or does not end with gif or svg, the default OpenSearch Dashboard logo will be shown. An application error log will be shown.
* If no loadingLogoUrl is not provided, the static logoUrl with a horizontal loading bar will be shown. If logoUrl is not provided, the default OpenSearch spinner will be displayed.
* User can input URL with image of any size, and the image will be formatted to a fixed size.
* User needs to be responsible for the …

Make loading page logo and title configurable 

---

package.json
packages/osd-dev-utils/package.json
packages/osd-release-notes/package.json
yarn.lock

Addresses https://github.com/advisories/GHSA-cph5-m8f7-6c5x
Bumps [axios](https://github.com/axios/axios) from 0.21.1 to 0.21.4
- [Release notes](https://github.com/axios/axios/releases/tag/v0.21.4)
- [Changelog](https://github.com/axios/axios/blob/v0.21.4/CHANGELOG.md)
- [Commits](https://github.com/axios/axios/compare/v0.21.1...v0.21.4)
**Before**
```
$ yarn why axios
[1/4] Why do we have the module "axios"...?
=> Found "axios@0.21.1"
- "_project_#@osd#dev-utils" depends on it
- Hoisted …
```

Bump `axios` from 0.21.1 to 0.21.4

---

package.json
packages/osd-dev-utils/package.json
packages/osd-release-notes/package.json
yarn.lock

https://github.com/advisories/GHSA-cph5-m8f7-6c5x
Bumps [axios](https://github.com/axios/axios) from 0.21.1 to 0.21.4
- [Release notes](https://github.com/axios/axios/releases/tag/v0.21.4)
- [Changelog](https://github.com/axios/axios/blob/v0.21.4/CHANGELOG.md)
- [Commits](https://github.com/axios/axios/compare/v0.21.1...v0.21.4)

[1.0] Bump `axios` from 0.21.1 to 0.21.4

---

package.json
packages/osd-dev-utils/package.json
packages/osd-release-notes/package.json
yarn.lock

https://github.com/advisories/GHSA-cph5-m8f7-6c5x
Bumps [axios](https://github.com/axios/axios) from 0.21.1 to 0.21.4
- [Release notes](https://github.com/axios/axios/releases/tag/v0.21.4)
- [Changelog](https://github.com/axios/axios/blob/v0.21.4/CHANGELOG.md)
- [Commits](https://github.com/axios/axios/compare/v0.21.1...v0.21.4)

[1.x] Bump `axios` from 0.21.1 to 0.21.4

---

package.json
packages/osd-dev-utils/package.json
packages/osd-release-notes/package.json
yarn.lock

- [Release notes](https://github.com/axios/axios/releases/tag/v0.21.4)
- [Changelog](https://github.com/axios/axios/blob/v0.21.4/CHANGELOG.md)
- [Commits](https://github.com/axios/axios/compare/v0.21.1...v0.21.4)

[1.1] Bump `axios` from 0.21.1 to 0.21.4

---

config/opensearch_dashboards.yml
src/core/public/chrome/ui/header/__snapshots__/header.test.tsx.snap
src/core/public/chrome/ui/header/branding/__snapshots__/opensearch_dashboards_custom_logo.test.tsx.snap
src/core/public/chrome/ui/header/branding/opensearch_dashboards_custom_logo.test.tsx
src/core/public/chrome/ui/header/branding/opensearch_dashboards_custom_logo.tsx
src/core/public/chrome/ui/header/header.test.tsx
src/core/public/chrome/ui/header/header.tsx
src/core/public/chrome/ui/header/header_logo.scss
src/core/public/index.ts
src/core/public/injected_metadata/injected_metadata_service.ts
src/core/server/opensearch_dashboards_config.ts
src/core/server/rendering/__snapshots__/rendering_service.test.ts.snap
src/core/server/rendering/rendering_service.tsx
src/core/server/rendering/types.ts
src/core/server/rendering/views/__snapshots__/template.test.tsx.snap
src/core/server/rendering/views/template.test.tsx
src/core/server/rendering/views/template.tsx
src/legacy/server/config/schema.js
src/plugins/home/public/application/components/welcome.test.tsx
src/plugins/home/public/application/components/welcome.tsx
src/plugins/home/public/application/opensearch_dashboards_services.ts
test/common/config.js

This PR changes the branding related config to a map structure in the opensearch_dashboards.yml file.
It also renames the configs according to the official branding guidelines. The full logo on the main page header will be called logo, and it has two modes: default and dark mode; the small logo icon will be called mark, and it has two modes: default and dark mode; the loading logo will be called loadingLogo, and has two modes: default and dark mode. The logic is the same as the previous PR.
Signed-off-by: Abby Hu <abigailhu2000@gmail.com>

Branding config structure change and renaming

---

src/plugins/inspector/public/views/data/lib/export_csv.ts
src/plugins/vis_type_table/public/agg_table/agg_table.js
src/plugins/vis_type_table/public/agg_table/agg_table.test.js

Signed-off-by: Miki <mehranb@amazon.com>
Blobs representing CSV content are generated on the browser which are then exported as downloadables. The mime-types were incorrectly set to `text/plain` in a few places. This commit changes the mime-type to be `text/csv`.
#640

Correct the mime-type of exported CSVs

---

config/opensearch_dashboards.yml
src/core/public/injected_metadata/injected_metadata_service.ts
src/core/server/opensearch_dashboards_config.ts
src/core/server/rendering/__snapshots__/rendering_service.test.ts.snap
src/core/server/rendering/rendering_service.tsx
src/core/server/rendering/types.ts
src/core/server/rendering/views/__snapshots__/template.test.tsx.snap
src/core/server/rendering/views/template.test.tsx
src/core/server/rendering/views/template.tsx
src/legacy/server/config/schema.js

Added a favicon configuration inside opensearchDashboards.branding in the yml file to provide basic favicon configuration.
If user inputs a valid URL, we guarantee basic browser favicon customization(Chrome, FireFox, Edge, Safari)
while remaining places such as Windows tile icon, Android device icon etc. show the default browser/device favicon icon. 
(For Safari browser favicon, we recommend to input a PNG URL, SVG URL might not work on Safari)
If user does not provide a valid URL for favicon, the opensearch favicon icon will be used.
Signed-off-by: Abby Hu <abigailhu2000@gmail.com>

Add favicon configuration

---

DEVELOPER_GUIDE.md
package.json
src/dev/build/args.test.ts
src/dev/build/args.ts
src/dev/build/build_distributables.ts
src/dev/build/cli.ts
src/dev/build/lib/build.test.ts
src/dev/build/lib/config.test.ts
src/dev/build/lib/config.ts
src/dev/build/lib/platform.ts
src/dev/build/tasks/clean_tasks.ts
src/dev/build/tasks/create_archives_task.ts
src/dev/build/tasks/nodejs/clean_node_builds_task.ts
src/dev/build/tasks/nodejs/download_node_builds_task.ts
src/dev/build/tasks/nodejs/extract_node_builds_task.ts
src/dev/build/tasks/nodejs/verify_existing_node_builds_task.ts
src/dev/build/tasks/notice_file_task.ts

When running yarn build --skip-os-packages it will build 4 tarballs
for Dashboards (2x linux, 1x macOS, 1x windows) and takes 10+min to
do so.
In this PR, we break the building process to allow single linux to
build. If run `yarn build-platform --linux-x64` only linux x64 tarball
is created. Same for linux arm64 and darwin x64. You could run `yarn
build-platform --linux-arm64` and `yarn build-platform darwin-x64`.
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/473
https://github.com/opensearch-project/OpenSearch-Dashboards/pull/795
support multiple CLI options and fix comments
Signed-off-by: AnanZ <ananzh@amazon.com>
fix wording to artifacts
Signed-off-by: AnanZ <ananzh@amazon.com>

[1.x] De-Couple Dashboards linux building process

---

src/plugins/inspector/public/views/data/lib/export_csv.ts
src/plugins/vis_type_table/public/agg_table/agg_table.js
src/plugins/vis_type_table/public/agg_table/agg_table.test.js

Blobs representing CSV content are generated on the browser which are then exported as downloadables. The mime-types were incorrectly set to text/plain in a few places. This commit changes the mime-type to be text/csv.
Issues Resolved
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/640
Signed-off-by: Miki <mehranb@amazon.com>
Backport of #792 to 1.x.

[1.x] Correct the mime-type of exported CSVs (#792)

---

yarn.lock

Bumps [tmpl](https://github.com/daaku/nodejs-tmpl) from 1.0.4 to 1.0.5.
- [Release notes](https://github.com/daaku/nodejs-tmpl/releases)
- [Commits](https://github.com/daaku/nodejs-tmpl/commits/v1.0.5)
---
- dependency-name: tmpl
dependency-type: indirect
...
Backport #807 to 1.1.

[1.1] Bump tmpl from 1.0.4 to 1.0.5 (#807)

---

yarn.lock

Bumps [tmpl](https://github.com/daaku/nodejs-tmpl) from 1.0.4 to 1.0.5.
- [Release notes](https://github.com/daaku/nodejs-tmpl/releases)
- [Commits](https://github.com/daaku/nodejs-tmpl/commits/v1.0.5)
---
- dependency-name: tmpl
dependency-type: indirect
...
Backport #807 to 1.x.

[1.x] Bump tmpl from 1.0.4 to 1.0.5 (#807)

---

yarn.lock

Bumps [prismjs](https://github.com/PrismJS/prism) from 1.24.0 to 1.25.0.
- [Release notes](https://github.com/PrismJS/prism/releases)
- [Changelog](https://github.com/PrismJS/prism/blob/master/CHANGELOG.md)
- [Commits](https://github.com/PrismJS/prism/compare/v1.24.0...v1.25.0)
---
- dependency-name: prismjs
dependency-type: indirect
...
Backport of #805 to 1.x.

[1.x] Bump prismjs from 1.24.0 to 1.25.0 (#805)

---

yarn.lock

Bumps [prismjs](https://github.com/PrismJS/prism) from 1.24.0 to 1.25.0.
- [Release notes](https://github.com/PrismJS/prism/releases)
- [Changelog](https://github.com/PrismJS/prism/blob/master/CHANGELOG.md)
- [Commits](https://github.com/PrismJS/prism/compare/v1.24.0...v1.25.0)
---
- dependency-name: prismjs
dependency-type: indirect
...
Backport of #805 to 1.1.

[1.1] Bump prismjs from 1.24.0 to 1.25.0 (#805)

---

release-notes/opensearch-dashboards.release-notes-1.1.0.md

Backport PR:
https://github.com/opensearch-project/OpenSearch-Dashboards/pull/821

[1.1] Update release note OSD 1.1 

---

src/core/public/chrome/ui/header/__snapshots__/collapsible_nav.test.tsx.snap
src/core/public/chrome/ui/header/__snapshots__/header.test.tsx.snap
src/core/public/chrome/ui/header/collapsible_nav.test.tsx
src/core/public/chrome/ui/header/collapsible_nav.tsx
src/core/public/chrome/ui/header/header.tsx
src/plugins/home/public/application/components/__snapshots__/home.test.js.snap
src/plugins/home/public/application/components/home.js
src/plugins/opensearch_dashboards_overview/public/application.tsx
src/plugins/opensearch_dashboards_overview/public/components/app.tsx
src/plugins/opensearch_dashboards_overview/public/components/overview/__snapshots__/overview.test.tsx.snap
src/plugins/opensearch_dashboards_overview/public/components/overview/overview.test.tsx
src/plugins/opensearch_dashboards_overview/public/components/overview/overview.tsx
src/plugins/opensearch_dashboards_overview/public/plugin.ts
src/plugins/opensearch_dashboards_react/public/index.ts
src/plugins/opensearch_dashboards_react/public/overview_page/overview_page_header/__snapshots__/overview_page_header.test.tsx.snap
src/plugins/opensearch_dashboards_react/public/overview_page/overview_page_header/overview_page_header.test.tsx
src/plugins/opensearch_dashboards_react/public/overview_page/overview_page_header/overview_page_header.tsx
test/functional/apps/visualize/_custom_branding.js

1. Side Menu Logo
Make side menu opensearch dashboard logo to be configurable. Use config mark.defaultUrl in default mode
and mark.darkModeUrl in dark mode. 
Also replace the original door logo with default opensearch mark in default mode and dark mode opensearch mark
in dark mode. 
2. Overview Header Logo
Make overview page header logo to be configurable. Use config mark.defaultUrl in default mode
and mark.darkModeUrl in dark mode. 
Also replace the original door logo with default opensearch mark in default mode and dark mode opensearch mark
in dark mode. 
In default mode, a valid mark.defaultUrl is required for custom side menu logo/custom overview header logo; otherwise, default opensearch mark will be rendered;
In dark mode, a valid mark.darkModeUrl is required for custom side menu …

Side menu logo and Overview header logo configuration

---

src/plugins/vis_type_timeline/server/series_functions/opensearch/index.js
src/plugins/vis_type_timeline/server/series_functions/opensearch/lib/build_request.js
src/plugins/vis_type_timeline/server/series_functions/opensearch/opensearch.test.js
test/functional/apps/timeline/_expression_typeahead.js

While renaming we changed values from legacy naming schema to
OpenSearch Dashboards naming schema. However, after realizing
we impacted backwards compatibility, we restored some of the
"under the hood" components backed to legacy application to
allow for seemless migration.
However, upon attempting to restore Timeline to work with saved
objects we neglected to restore the Timeline functions.
Previously users could set kibana=false to ignore filters on
the dashboards being applied to their Timeline visualizations.
Now, if users tried to set it then it would fail because it
didn't know what that function was.
This commit fixes this issue by keeping the update since we
do not want to impact people who have now updated their functions
and re-added the legacy functions.
In this commit, I also …

[Bug] Restore timeline legacy functions and filters

---

src/plugins/vis_type_timeline/server/series_functions/opensearch/index.js
src/plugins/vis_type_timeline/server/series_functions/opensearch/lib/build_request.js
src/plugins/vis_type_timeline/server/series_functions/opensearch/opensearch.test.js
test/functional/apps/timeline/_expression_typeahead.js

While renaming we changed values from legacy naming schema to
OpenSearch Dashboards naming schema. However, after realizing
we impacted backwards compatibility, we restored some of the
"under the hood" components backed to legacy application to
allow for seemless migration.
However, upon attempting to restore Timeline to work with saved
objects we neglected to restore the Timeline functions.
Previously users could set kibana=false to ignore filters on
the dashboards being applied to their Timeline visualizations.
Now, if users tried to set it then it would fail because it
didn't know what that function was.
This commit fixes this issue by keeping the update since we
do not want to impact people who have now updated their functions
and re-added the legacy functions.
In this commit, I also …

[1.x][Bug] Restore timeline legacy functions and filters

---

release-notes/opensearch-dashboards.release-notes-1.1.0.md
src/plugins/vis_type_timeline/server/series_functions/opensearch/index.js
src/plugins/vis_type_timeline/server/series_functions/opensearch/lib/build_request.js
src/plugins/vis_type_timeline/server/series_functions/opensearch/opensearch.test.js
test/functional/apps/timeline/_expression_typeahead.js

While renaming we changed values from legacy naming schema to
OpenSearch Dashboards naming schema. However, after realizing
we impacted backwards compatibility, we restored some of the
"under the hood" components backed to legacy application to
allow for seemless migration.
However, upon attempting to restore Timeline to work with saved
objects we neglected to restore the Timeline functions.
Previously users could set kibana=false to ignore filters on
the dashboards being applied to their Timeline visualizations.
Now, if users tried to set it then it would fail because it
didn't know what that function was.
This commit fixes this issue by keeping the update since we
do not want to impact people who have now updated their functions
and re-added the legacy functions.
In this commit, I also …

[1.1][Bug] Restore timeline legacy functions and filters

---

src/core/server/rendering/rendering_service.tsx

Add an additional parameter to the checkUrlValid function
so that max redirect count is 0. We do not allow URLs that
can be redirected because of potential security issues.
Signed-off-by: Abby Hu <abigailhu2000@gmail.com>

Redirect URL not allowed

---

DEVELOPER_GUIDE.md
package.json
src/dev/build/args.test.ts
src/dev/build/args.ts
src/dev/build/build_distributables.ts
src/dev/build/cli.ts
src/dev/build/lib/build.test.ts
src/dev/build/lib/config.test.ts
src/dev/build/lib/config.ts
src/dev/build/lib/platform.ts
src/dev/build/tasks/clean_tasks.ts
src/dev/build/tasks/create_archives_task.ts
src/dev/build/tasks/nodejs/clean_node_builds_task.ts
src/dev/build/tasks/nodejs/download_node_builds_task.ts
src/dev/build/tasks/nodejs/extract_node_builds_task.ts
src/dev/build/tasks/nodejs/verify_existing_node_builds_task.ts
src/dev/build/tasks/notice_file_task.ts

When running yarn build --skip-os-packages it will build 4 tarballs
for Dashboards (2x linux, 1x macOS, 1x windows) and takes 10+min to
do so.
In this PR, we break the building process to allow single linux to
build. If run `yarn build-platform --linux-x64` only linux x64 tarball
is created. Same for linux arm64 and darwin x64. You could run `yarn
build-platform --linux-arm64` and `yarn build-platform darwin-x64`.
partially solved:
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/473
backport PR:
https://github.com/opensearch-project/OpenSearch-Dashboards/pull/795

[1.1] De-Couple Dashboards linux building process

---

DEVELOPER_GUIDE.md
src/dev/build/args.test.ts
src/dev/build/cli.ts

yarn build flags in /src/dev/build/cli.ts are not updated to match
the renamed flags in de-couple PR (#795). This PR fixes the issue
and update the tests. Also modify words in DEVELOPER_GUIDE.md.
PR resolved:
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/836

Fix yarn build docs and update test

---

DEVELOPER_GUIDE.md
src/dev/build/args.test.ts
src/dev/build/cli.ts

yarn build flags in /src/dev/build/cli.ts are not updated to match
the renamed flags in de-couple PR (#795). This PR fixes the issue
and update the tests. Also modify words in DEVELOPER_GUIDE.md.
PR resolved:
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/836
Backport PR:
https://github.com/opensearch-project/OpenSearch-Dashboards/pull/840

[1.x] Fix yarn build docs and update test

---

DEVELOPER_GUIDE.md
src/dev/build/args.test.ts
src/dev/build/cli.ts

yarn build flags in /src/dev/build/cli.ts are not updated to match
the renamed flags in de-couple PR (#795). This PR fixes the issue
and update the tests. Also modify words in DEVELOPER_GUIDE.md.
PR resolved:
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/836
Backport PR:
https://github.com/opensearch-project/OpenSearch-Dashboards/pull/840

[1.1] Fix yarn build docs and update test

---

src/core/public/chrome/ui/header/branding/opensearch_dashboards_custom_logo.tsx
src/core/server/rendering/__mocks__/rendering_service.ts
src/core/server/rendering/rendering_service.test.ts
src/core/server/rendering/rendering_service.tsx

Handling the helper function rename and grammar issues.
To avoid risk, we will not remove the duplicate code for 1.2 and
everything related to those comments (ie function renames).
That will be handled in 1.3. Here is the issue tracking it:
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/895

[Branding] handle comments from PR

---

cypress/integration/osd/check_advanced_settings.js
cypress/integration/osd/check_default_page.js
cypress/integration/osd/check_filter_and_query.js

We need bwc tests on vanilla osd for release to verify
there is no issues from the dashboards. This PR modifies
the previous bwc tests on bundled osd by removing the
login page. Currently all the tests are exactly the same
for two versions but they might be different in the future.
There is no requirement that we need to test the same thing
for osd with and without bundles.

Add bwc cypress test for osd without bundles

---

src/legacy/server/config/schema.js
src/plugins/maps_legacy/config.ts

Signed-off-by: Junqiu Lei <junqiu@amazon.com>
Currently the maps end point can't be accessed from India and China, we are going to update maps end point to the new one "maps.opensearch.org" for OpenSearch community users, which will solve the pain for opensource users from some region can't access to the existing one.
https://discuss.opendistrocommunity.dev/t/status-of-kibana-maps/5106/36 
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/777

Update dashboard maps end point

---

src/legacy/server/config/schema.js
src/plugins/maps_legacy/config.ts

Currently the maps end point can't be accessed from India and China, we are going to update maps end point to the new one "maps.opensearch.org" for OpenSearch community users, which will solve the pain for opensource users from some region can't access to the existing one.
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/777
Signed-off-by: Junqiu Lei <junqiu@amazon.com>

1.x Update the dashboard maps end point (#893)

---

src/dev/build/tasks/bin/scripts/opensearch-dashboards

Fixed node selection to use the node executable instead of the user local node.
Signed-off-by: Sven R <admin@hackacad.net>
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/908

[1.x] Fix Node selection when using built in node (#912)

---

src/dev/build/tasks/bin/scripts/opensearch-dashboards

Fixed node selection to use the node executable instead of the user local node.
Signed-off-by: Sven R <admin@hackacad.net>
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/908

[1.2] Fix Node selection when using built in node (#912)

---

.eslintrc.js
packages/osd-eslint-plugin-eslint/rules/__tests__/require_license_header.js
packages/osd-eslint-plugin-eslint/rules/require_license_header.js

Allows for the simplified license header to exist alongside the modified license header. (Issue: https://github.com/opensearch-project/.github/issues/21). If neither license header is present, the simplified license is used.
https://github.com/opensearch-project/.github/issues/21

[LIC] Allows the simplified header for new files

---

.github/pull_request_template.md

Update template to remove javadoc check box since we do not have any
javadocs and include how to run the tests we use to verify the build.
n/a

[Git] update PR template

---

release-notes/opensearch-dashboards.release-notes-1.2.0.md

Signed-off-by: Neumann <neumanns@amazon.com>

Add release notes for Dashboards 1.2.0

---

src/core/server/rendering/rendering_service.test.ts
src/core/server/rendering/rendering_service.tsx

Out of the box, the rendering service will check the config
and see the default value and log an info message saying that
the branding config is invalid or not set. Everytime
you refresh the browser you will get those log messages.
This sets it to only log error messages if the user sets
the branding config and it is invalid.
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/725

[Branding] prevent logging when config not set

---

package.json

Bump OpenSearch Dashboards from 1.2.0 to 1.3.0.
n/a

[1.x][Version] Bump to 1.3.0

---

package.json
src/plugins/wizard/public/application/app.tsx
src/plugins/wizard/public/application/components/data_tab/config_panel.tsx
src/plugins/wizard/public/application/components/data_tab/config_section.tsx
src/plugins/wizard/public/application/components/data_tab/field_selector.tsx
src/plugins/wizard/public/application/components/data_tab/index.tsx
src/plugins/wizard/public/application/components/side_nav.tsx
src/plugins/wizard/public/application/components/top_nav.tsx
src/plugins/wizard/public/application/index.tsx
src/plugins/wizard/public/application/utils/state_management/config_slice.ts
src/plugins/wizard/public/application/utils/state_management/datasource_slice.ts
src/plugins/wizard/public/application/utils/state_management/hooks.ts
src/plugins/wizard/public/application/utils/state_management/index.ts
src/plugins/wizard/public/application/utils/state_management/store.ts
yarn.lock

Adds Redux and RTK based state management to the drag and drop plugin. 
#947

Adds state management to Drag and Drop

---

.github/workflows/links_checker.yml

Signed-off-by: Zuocheng Ding <zding817@gmail.com>
There is a bug introduced recently into latest Lychee linker checker. Previously, our link check workflow will pull the latest binary from `@master`. Change the Lychee dependency version to a stable v1.0.9. 
Errors in Lychee Link checker.

Fix Lychee Link Checker Error

---

src/dev/jest/config.js

Fixes jest unit test failures by removing lmdb-store from transformIgnorePatterns
Fixes jest unit test failures by removing lmdb-store from transformIgnorePatterns
Closes #990

[Node 14 upgrade] Fix unit test failures

---

.github/workflows/pr_check_workflow.yml
packages/osd-pm/src/run.test.ts
src/dev/jest/config.js
src/plugins/embeddable/public/lib/embeddables/error_embeddable.test.tsx
src/plugins/vis_type_markdown/public/markdown_vis_controller.test.tsx
src/plugins/vis_type_tagcloud/public/components/tag_cloud_visualization.test.js
src/plugins/visualize/public/application/utils/use/use_visualize_app_state.test.ts

Add unit tests to github workflow and also creating a "bad apples"
environment variable. Some unit tests just fail on the CI for
hardware issues. They should be improved but step one will be
calling out the bad apples.
Also due to the flakiness we can cache the previous run results
and only run the tests that failed. It's too random to catch
with the bad apples mechanism. But still added the continue on
error for unit tests because it takes so long to re-run on the
CI. So instead if it does fail we automatically echo there
was a failure and ask them to re-run. However, if we can get
permission for a github action that can add a comment to the PR
then we could automatically add to PR.
Next step will be improving.
Also needed to limit the amount of workers because otherwise the
hardware …

[CI] Add tests to github workflow

---

src/plugins/visualizations/public/wizard/__snapshots__/new_vis_modal.test.tsx.snap
src/plugins/visualizations/public/wizard/type_selection/type_selection.tsx
src/plugins/wizard/opensearch_dashboards.json
src/plugins/wizard/public/index.ts
src/plugins/wizard/public/plugin.ts
src/plugins/wizard/public/types.ts

Moves the entry point for the drag and drop plugin to the "create visualization" menu.
#959

Moves Drag and Drop to create visualization menu

---

cypress/integration/osd/check_advanced_settings.js
cypress/integration/osd/check_default_page.js
cypress/integration/osd/check_filter_and_query.js
cypress/integration/osd/check_loaded_data.js
cypress/integration/osd/check_timeline.js

This PR adds the following bwc tests:
1) verify sample data work properly for bwc
2) verify timeline visualization work properly for bwc
This PR also simplifies check_filter_and_query bwc test.
It first removes Unique Visitors check because even fix
the time interval, the number of unique visitors number
is random. Then it simplifies this bwc test.

[Backwards Compatibility][OSD] check advanced_settings, default page, loaded sample date, timeline and filter&query

---

cypress/integration/osd-bundle/check_loaded_data.js
cypress/integration/osd-bundle/check_timeline.js

This PR adds the following bwc tests:
1)verify sample data work properly for bwc
2)verify timeline visualization work properly for bwc

[Backwards Compatibility][OSD bundle] add timeline and sample data check

---

src/plugins/data/common/field_formats/converters/url.test.ts
src/plugins/opensearch_dashboards_utils/public/state_management/url/format.test.ts
src/plugins/opensearch_dashboards_utils/public/state_management/url/hash_unhash_url.test.ts
src/plugins/opensearch_dashboards_utils/public/state_management/url/osd_url_storage.test.ts
src/plugins/saved_objects_management/public/management_section/objects_table/components/__snapshots__/relationships.test.tsx.snap
src/plugins/saved_objects_management/public/management_section/objects_table/components/relationships.test.tsx
src/plugins/share/public/lib/url_shortener.test.ts
src/plugins/url_forwarding/public/forward_app/forward_app.ts
src/plugins/url_forwarding/public/plugin.ts

Forwarding legacy app to the current format of the application.
This enables the usage of stored URLs and other links that referenced
the format of the application URL that mentioned the application name.
Since we changed the URL forwarding we changed this value and released.
So incase forks were made and depended on this legacy formatted reference
of the application. It will still work. There are also references of the
application.
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1013

[Backwards Compatibility] restore URL forwarding from legacy app

---

.lycheeexclude

Issue: https://yarnpkg.com/latest.msi is unavailable now and will be rerouted to a 404 page.
Signed-off-by: Zuocheng Ding <zding817@gmail.com>
https://yarnpkg.com/latest.msi is unavailable now and will be rerouted to a 404 page.
Add it to link checker allow list to unblock the PR process.
Link checker error

[Link] Fix yarnpkg link error

---

.whitesource
whitesource.config

We @bbarani already enable the access of [WhiteSource integration](https://whitesource.atlassian.net/wiki/spaces/WD/pages/697696422/WhiteSource+for+GitHub.com) with Github.com for this repo.  However, the automatic PR of `.whitesource` is not created. We asked for the support from WhiteSource side and they suggested we could raise one by ourselves. This PR will also set the WhiteSource integration config mode to `Local` to be using the `whitesource.config`. Dashboards team can modify this configuration on their own to customize it. We are providing the one we had for all repos at this time. 
https://github.com/opensearch-project/opensearch-build/issues/721

Add .whitesource file to activate integration scan

---

packages/osd-plugin-helpers/src/integration_tests/build.test.ts
packages/osd-plugin-helpers/src/tasks/write_server_files.ts

Removes the SEMVAR check for external plugins. 7.9 is not relevant
to the application.
The semvar library was also preventing major.minor.patch.x which is the
format from OpenSearch plugins.
Related issue:
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/992
n/a

[Build] remove legacy version check for plugin builds

---

package.json
scripts/bwctest-osd.sh

Currently, even we have bwc tests and data, to run bwc, we need
to copy and unzip data in opensearch, then run opensearch,
dashboards and cypress. This script will add more automation to
allow us use one command to run all the tests. Here is the cmd:
./scripts/bwctest-osd.sh
-o /path/to/opensearch.tar.gz
-d /path/to/opensearch-dashboards.tar.gz
-v versions
-b true/false
-o is the path to the tested opensearch. Here we need to rename
the folder to opensearch and zip it
-d is the path to the tested opensearch-dashboards. Also need to
rename the folder to opensearch-dashboards and zip it
-v is the optional version para. You can specify one version or
multiple versions like "odfe-1.1.0, osd-1.0.0". If no pass, it will
run all the versions defined in the script.
-b is the optional osd type …

[Backwards Compatibility] add a script to use one command to run all bwc tests

---

config/opensearch_dashboards.yml
src/legacy/server/config/schema.js
src/plugins/maps_legacy/config.ts
src/plugins/maps_legacy/public/map/opensearch_dashboards_map.js
src/plugins/maps_legacy/server/index.ts
src/plugins/region_map/public/choropleth_layer.js
src/plugins/vis_type_vega/public/vega_view/vega_map_view.js

Clean up temp aws paths in code base.
Add a configurable flag `captureRegionBlockedError` into map plugin level config file.
Signed-off-by: Zuocheng Ding <zding817@gmail.com>
Clean up temp aws paths in code base.
Add a configurable flag `captureRegionBlockedError` into map plugin level config file.
Customer should able to modify the config in `opensearch_dashboards.yml` if they want.
- #362

[Map] Remove hardcoded AWS paths

---

src/core/CONVENTIONS.md

Removed missed reference in CONVENTIONS.md.
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1109

[Docs] remove invalid reference in CONVENTIONS.md

---

packages/osd-config-schema/src/types/object_type.ts
src/plugins/dashboard/public/application/embeddable/viewport/dashboard_viewport.test.tsx
src/plugins/home/server/services/tutorials/lib/tutorials_registry_types.ts
src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/components/step_index_pattern/step_index_pattern.test.tsx
src/plugins/saved_objects/public/saved_object/saved_object.test.ts
src/plugins/vis_default_editor/public/components/controls/components/number_list/number_row.test.tsx

Found errors when running `yarn lint` with the most recent changes, even though the fixes aren't related to recent changes. Fixed with `yarn lint:es --fix`.
N/A

Fixes linting errors

---

config/opensearch_dashboards.yml
packages/osd-plugin-helpers/src/integration_tests/build.test.ts
packages/osd-plugin-helpers/src/tasks/write_server_files.ts
src/core/CONVENTIONS.md
src/core/server/rendering/rendering_service.test.ts
src/core/server/rendering/rendering_service.tsx
src/legacy/server/config/schema.js
src/plugins/data/common/field_formats/converters/url.test.ts
src/plugins/maps_legacy/config.ts
src/plugins/maps_legacy/public/map/opensearch_dashboards_map.js
src/plugins/maps_legacy/server/index.ts
src/plugins/opensearch_dashboards_utils/public/state_management/url/format.test.ts
src/plugins/opensearch_dashboards_utils/public/state_management/url/hash_unhash_url.test.ts
src/plugins/opensearch_dashboards_utils/public/state_management/url/osd_url_storage.test.ts
src/plugins/region_map/public/choropleth_layer.js
src/plugins/saved_objects_management/public/management_section/objects_table/components/__snapshots__/relationships.test.tsx.snap
src/plugins/saved_objects_management/public/management_section/objects_table/components/relationships.test.tsx
src/plugins/share/public/lib/url_shortener.test.ts
src/plugins/url_forwarding/public/forward_app/forward_app.ts
src/plugins/url_forwarding/public/plugin.ts
src/plugins/vis_type_vega/public/vega_view/vega_map_view.js

Backport PR for:
* https://github.com/opensearch-project/OpenSearch-Dashboards/pull/941
* https://github.com/opensearch-project/OpenSearch-Dashboards/pull/1015
* https://github.com/opensearch-project/OpenSearch-Dashboards/pull/1021
* https://github.com/opensearch-project/OpenSearch-Dashboards/pull/1110
* https://github.com/opensearch-project/OpenSearch-Dashboards/pull/1029

[1.x] Backport PR for build, maps, branding logging

---

TESTING.md

[Backwards Compatibility] update instructions in TESTING.md

---

.whitesource
whitesource.config

* WhiteSource is not properly comparing scans against the latest changes in `main`. This prevents the need to override checks to merge PRs for those who don't have access (like the Dashboards Core members).
* Cleans up the WhiteSource config file. We don't need gradle, maven, go, python, or ruby scans enabled.
* Replaces the deprecated `ignoreSourceFiles` config with `fileSystemScan`.
Resolves #1150

Disable WhiteSource check fails on commits/PRs

---

src/plugins/home/server/index.ts

disableWelcomeScreen was erroneously removed from being exposed to browser (for testing purposes)
and was not able to pass the config to disable the welcome screen showing.
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1138

[BUG] fix disableWelcomeScreen config

---

src/plugins/home/server/index.ts

disableWelcomeScreen was erroneously removed from being exposed to browser (for testing purposes)
and was not able to pass the config to disable the welcome screen showing.
Issue:
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1138
Backport PR:
https://github.com/opensearch-project/OpenSearch-Dashboards/pull/1143

[1.x][BUG] fix disableWelcomeScreen config (#1143)

---

src/setup_node_env/exit_on_warning.js

The last AWS SDK for Javascript that supports Node 10 (v3.45.0) emits a NodeDeprecationWarning to indicate that Node 10
is no longer supported. Without this workaround, this crashes the OSD server, so it becomes impossible to interact with
other AWS services from within OSD (e.g., in a custom plugin) until the Node 14 upgrade is done.
Signed-off-by: Thilo-Alexander Ginkel <tg@tgbyte.de>
See above. Without this fix the OSD server crashes with the following warning as soon as any AWS SDK functionality is used:
```
(node:74504) NodeDeprecationWarning: The AWS SDK for JavaScript (v3) will
no longer support Node.js v10.24.1 as of January 1, 2022.
To continue receiving updates to AWS services, bug fixes, and security
updates please upgrade to Node.js 12.x or later.
More information can be found …
```

Don't terminate the server on NodeDeprecationWarning

---

package.json
packages/osd-opensearch/package.json
yarn.lock

v2.6.7 includes the security fix: https://github.com/node-fetch/node-fetch/releases/tag/v2.6.7
Resolves #1162

Bumps `node-fetch` from v2.6.1 to v2.6.7

---

package.json
packages/osd-opensearch/package.json
yarn.lock

Backport PR for #1169 
Resolves #1162

[Backport 1.x] Bumps `node-fetch` from v2.6.1 to v2.6.7 (#1169)

---

.whitesource

* WhiteSource seems to have resolved the previous bug, and we are still able to merge even if the check fails.
Example of a correct check: https://github.com/opensearch-project/OpenSearch-Dashboards/pull/1172/checks?check_run_id=5096076004
N/A

Re-enable WhiteSource check fails on commits/PRs

---

.github/workflows/pr_check_workflow.yml

* Skips feature branches
* Use the `.nvmrc` file for the `node` version instead of a hard-coded version.
Followed the [filter pattern workflow syntax](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet).
Resolves #1023

Run build and test workflow on all branches

---

packages/osd-interpreter/package.json
packages/osd-monaco/package.json
packages/osd-monaco/scripts/build.js
packages/osd-pm/package.json
packages/osd-ui-framework/package.json
yarn.lock

* Upgrades `webpack-cli` from v3.3.10 to v4.9.2
* [CHANGELOG](https://github.com/webpack/webpack-cli/blob/webpack-cli%404.9.2/CHANGELOG.md)
* `webpack-cli` changed the way that the `--env` flag is parsed. See https://github.com/webpack/webpack-cli/issues/1216 for more information.
* Upgrades `webpack-dev-server` from v3.11.2 to v4.7.4
* [CHANGELOG](https://github.com/webpack/webpack-dev-server/blob/v4.7.4/CHANGELOG.md)
* [Migration guide](https://github.com/webpack/webpack-dev-server/blob/master/migration-v4.md)
Resolves #1065

Upgrades `webpack-dev-server` and `webpack-cli`

---

.github/workflows/backport.yml
.github/workflows/delete_backport_branch.yml
CONTRIBUTING.md

Adding VachaShah/backport@v1.1.4 for automating backport PRs.
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1211
~~- [ ] New functionality has been documented.~~

[CI] Add backport action for automated backports

---

src/core/server/opensearch/opensearch_config.test.ts
yarn.lock

openseasrch_config.test.ts was failing with yarn test:jest
Introduced:
https://github.com/opensearch-project/OpenSearch-Dashboards/pull/1234
n/a

[Tests] unit test for config was failing

---

src/plugins/data/common/search/aggs/agg_types_registry.test.ts
src/plugins/data/common/search/aggs/agg_types_registry.ts
src/plugins/data/common/search/aggs/aggs_service.test.ts
src/plugins/data/common/search/aggs/aggs_service.ts
src/plugins/data/common/search/aggs/test_helpers/mock_agg_types_registry.ts
src/plugins/data/public/search/aggs/aggs_service.ts
src/plugins/data/server/search/aggs/aggs_service.ts
src/plugins/visualizations/common/constants.ts
src/plugins/visualizations/server/index.ts
src/plugins/visualizations/server/plugin.ts

Signed-off-by: sitbubu <royi.sitbon@logz.io>
We don't have an option to remove bucket aggregation types by demand. e.g. we want to disable the option of choosing ‘significant_terms’ bucket aggregation because it can be very heavy when run on large indices.
We wish to add a configuration in order to disable nonrelevant bucket aggregation types.
Further explanation inside the attached issue.
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1195

Add option to configure available bucket agg types + jest tests

---

packages/osd-optimizer/src/node/cache.ts

Replace kbn to osd to solve Resource temporarily unavailable error
when functional test fails.

Fix cache.ts for Resource temporarily unavailable

---

src/plugins/data/common/search/aggs/agg_types_registry.ts
src/plugins/data/server/search/aggs/aggs_service.ts

Test failure introduced:
https://github.com/opensearch-project/OpenSearch-Dashboards/pull/1196
Updating to handle the if that configuration is not found or if it is
not an array.
n/a

[Tests] update disable bucket agg feature for tests

---

DEVELOPER_GUIDE.md

Signed-off-by: Ashwin PC <ashwinpc@amazon.com>
Updates the developer docs to use the latest nightly snapshot build for OpenSearch instead of the docker container. The current developer guide mentions the docker container as the easiest way to setup the OpenSearch Server for development. This however is broken since the main branch for OpenSearch Dashboards is on version 2.0 while the latest Docker container is on version 1.1 causing a version mismatch on startup.

docs(Dev Guide): Updates how to run OpenSearch

---

tsconfig.base.json

add path in tsconfig.base.json to let nodejs types point to api/new.d.ts which is the new defined types

[nodejs client] modify tsconfig to route types to new.d.ts

---

packages/osd-opensearch-archiver/src/lib/docs/__tests__/generate_doc_records_stream.ts

Failure introduced here:
https://github.com/opensearch-project/OpenSearch-Dashboards/pull/1289/files
OpenSearch Archiver loads data to OpenSearch from data.json into OpenSearch for
E2E tests and integration tests but will need to verify if this causes breakage in
migration from older versions of the application.
Mocha tests do not run in the current CI so these were missed.
n/a

[Tests] fix mocha tests related to `type`

---

src/core/server/core_usage_data/core_usage_data_service.ts

Fix issues in src/core/server/core_usage_data_service.ts.
Change types of property docsCount,docsDeleted,storeSizeBytes
and primaryStoreSizeBytes from 'string | undefined to 'number'.

[nodejs client] fix hookup issues in src/core/server/core_usage_data_service.ts

---

DEVELOPER_GUIDE.md
src/dev/build/args.test.ts
src/dev/build/args.ts
src/dev/build/build_distributables.ts
src/dev/build/lib/runner.test.ts
src/dev/build/tasks/nodejs/download_node_builds_task.test.ts
src/dev/build/tasks/nodejs/extract_node_builds_task.test.ts
src/dev/build/tasks/nodejs/verify_existing_node_builds_task.test.ts
src/dev/build/tasks/os_packages/create_os_package_tasks.test.ts
src/dev/build/tasks/os_packages/create_os_package_tasks.ts
src/dev/build/tasks/os_packages/package_scripts/pre_install.sh
src/dev/build/tasks/os_packages/package_scripts/pre_remove.sh
src/dev/build/tasks/os_packages/run_fpm.ts

Build ARM64 for deb with the following commands:
yarn build --deb-arm --skip-archives
yarn build --deb-arm --skip-archives --release
Build ARM64 for rpm with the following commands:
yarn build --rpm-arm --skip-archives
yarn build --rpm-arm --skip-archives --release
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1259

[Build] Build ARM64 for deb and rpm

---

src/core/server/index.ts
src/core/server/saved_objects/index.ts
src/core/server/saved_objects/mappings/index.ts
src/core/server/saved_objects/mappings/lib/get_property.test.ts
src/core/server/saved_objects/mappings/lib/get_property.ts
src/core/server/saved_objects/mappings/lib/get_root_properties_objects.test.ts
src/core/server/saved_objects/mappings/lib/get_root_properties_objects.ts
src/core/server/saved_objects/mappings/types.ts
src/core/server/saved_objects/migrations/core/__snapshots__/opensearch_index.test.ts.snap
src/core/server/saved_objects/migrations/core/build_active_mappings.test.ts
src/core/server/saved_objects/migrations/core/build_index_map.test.ts
src/core/server/saved_objects/migrations/core/call_cluster.ts
src/core/server/saved_objects/migrations/core/index_migrator.test.ts
src/core/server/saved_objects/migrations/core/index_migrator.ts
src/core/server/saved_objects/migrations/core/migration_context.test.ts
src/core/server/saved_objects/migrations/core/opensearch_index.test.ts
src/core/server/saved_objects/migrations/core/opensearch_index.ts
src/core/server/saved_objects/migrations/opensearch_dashboards/opensearch_dashboards_migrator.test.ts
src/core/server/saved_objects/saved_objects_type_registry.ts
src/core/server/saved_objects/service/lib/filter_utils.test.ts
src/core/server/saved_objects/service/lib/repository.test.js
src/core/server/saved_objects/service/lib/repository.ts
src/core/server/saved_objects/service/lib/search_dsl/sorting_params.test.ts
src/core/server/saved_objects/version/encode_hit_version.ts
src/core/server/saved_objects/version/encode_version.ts
src/core/server/server.api.md

1.import Client from '@opensearch-project/opensearch/api/new' to hook
up the new types
2.add support functions. for example, add a support function for
converting a possibly not existant doc to an existant doc.
3.add @ts-expect-error to expected mismatches
4.fix undefined and mismatched types
5.fix unit tests in src/core/server/saved_objects
```
yarn test:jest src/core/server/saved_objects/mappings/lib/get_property.test.ts
yarn run v1.22.5
$ node scripts/jest src/core/server/saved_objects/mappings/lib/get_property.test.ts
 PASS  src/core/server/saved_objects/mappings/lib/get_property.test.ts
  getProperty(mappings, path)
    string key
      ✓ finds root properties (2 ms)
      ✓ finds nested properties (1 ms)
      ✓ finds nested multi-fields (1 ms)
    array of string keys
      ✓ finds …
```

[nodejs client] fix hookup issues in src/core/server/saved_objects

---

src/plugins/data/common/search/aggs/metrics/__snapshots__/median.test.ts.snap
src/plugins/data/common/search/aggs/metrics/median.test.ts
src/plugins/data/common/search/aggs/metrics/median.ts

Create a script using sample eCommerce data:
```
if (doc.containsKey('base_price') && !doc['base_price'].empty) {
    if (doc['base_price'].value <30) {
    return -10;
}
}
return 10;
```
Previously, the result is:
After fix, now we could see the correct median:

[BUG] fix median.ts to work for scripted field

---

src/plugins/data/public/query/saved_query/saved_query_service.test.ts
src/plugins/data/public/query/saved_query/saved_query_service.ts

In Discover, when loading a saved query with double quotes, double quotes are gone and term query becomes match query. 
To do a term query, we need to keep the quotes.  When parsing a string with quotes, JSON.parse function will trim the quotes and return its value. For example, `"Men's Shoes"` is parsed to `Men's Shoes`. Then dashboards will break the term using its analyzer and search each word which causes the issue. Please check the [comments](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1254#issuecomment-1061191659) in the resolved issue for more details. 
To solve this, we added an `isObject` checker which filters a regular string from a json string. After we get the regular string, the query will use its original value and quotes are able to be kept. After …

[Bug] Solve saved query bug

---

packages/osd-opensearch/src/artifact.test.js
src/cli_plugin/install/settings.js
src/cli_plugin/install/settings.test.js

Update old and invalid reference to custom plugins within
the OpenSearch Project.
Note: At the time that this is committed there is no gurantee
that the latest build is the build that was select as the
final build.
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1038

[Plugins] update default url for installing plugins

---

assets/.gitignore
src/core/server/core_app/core_app.ts
src/core/server/rendering/rendering_service.tsx
src/dev/build/tasks/clean_tasks.ts
src/dev/build/tasks/create_empty_dirs_and_files_task.ts
src/dev/build/tasks/os_packages/run_fpm.ts
test/server_integration/http/ssl/index.js

Adding `assets` folder that gets served up under UI for ease of us.
SSL support when OpenSearch Dashboards SSL is enabled.
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1164

[Branding] assets folder and SSL support

---

package.json

`branch` in the package.json is used for pointing links to the right
site. For example: `https://opensearch.org/docs/1.3/dashboards/index/`.
NOTE: At the time this commit was made the doc site for `1.3`, is
not available.
There is an existing issue here:
https://github.com/opensearch-project/documentation-website/issues/296
We can point this to `latest` but the problem with that is that we
don't re-release versions. When the next major or minor release
occurs then `latest` will point to that version and now all
OpenSearch Dashboards 1.3 downloads will point to the newest version.
So to avoid that, I suggest we point this to `1.3` and I got confirmation
that it will be `1.3`.
n/a

[Docs] update branch version to 1.3

---

packages/osd-opensearch-archiver/src/lib/indices/__tests__/create_index_stream.ts
packages/osd-opensearch-archiver/src/lib/indices/create_index_stream.ts

include_type_name was removed in https://github.com/opensearch-project/OpenSearch/pull/2397
OpenSearch Archiver loads data to OpenSearch from data.json into OpenSearch for
E2E tests and integration tests but will need to verify if this causes breakage in
migration from older versions of the application.
n/a

[Tests] remove include_type_name from OpenSearch Archiver

---

src/dev/jest/integration_tests/__fixtures__/test.js

Interesting flakiness in the test. After the jest upgrade, our tests
got more performant.
The JUnit Report integ test was actually expecting `anything` for a field
`time`. This `time` was calculated on elapsed time to the `0.00x` value
anything faster would actually be undefined and at that point `anything`
fails because `anything` cannot be undefined.
tl;dr: This test became flakey because our tests now run too fast.
n/a

[Tests] fix JUnit Reporter test

---

package.json
yarn.lock

Not sure how, but I botched the other PR #1314. git kept telling me I didn't have permissions to update it after it let me rebase Tengda's branch without the new commit, so here we are.
* Addresses known Inefficient Regular Expression Complexity CVE in `ansi-regex` < 5.0.1: CVE-2021-3807
* `webpack-dev-server` has a downstream dependency on `ansi-regex` v6.0.1 but it's still compatible with v5.0.1.
Signed-off-by: Tengda He <tengh@amazon.com>
Resolves #1084

Resolves `ansi-regex` to v5.0.1

---

.github/workflows/pr_check_workflow.yml

* Runs the functional test jobs in parallel instead of waiting for the Build and Verify job to complete in order to reduce time to success/failure.
* Deletes a leftover cache step that was not removed in #1306.
Resolves #1355

Runs functional test jobs in parallel w/ build job

---

src/cli_plugin/install/settings.test.js

* The tests assumed that the platform/architecture combo the tests were run from was always linux/x64.
* Introduced in #1316.
N/A

Fixes inconsistent plugin installation tests

---

src/dev/build/lib/get_build_number.test.ts
src/dev/build/lib/get_build_number.ts

When running a release build for example:
```
yarn build-platform --linux --skip-os-packages --release
```
The build task runs through get_build_number and
checks how many commits you have locally and determines the
build number. From there, and this is the value that
is used to as a cache busting mechanism.
However, in the release build repo
https://github.com/opensearch-project/opensearch-build
When this gets packaged and verified it actually pulls
from the specified branch and only retrieves the HEAD
commit. Thus making the count of commits locally equal
to `1` and get_build_number always return `1` for releases
essentially breaking the cache buster.
The build repo however, sets an env variable of `BUILD_NUMBER`
so if this value is available it will use it instead of commit
count. …

[CI][Build] Use BUILD_NUMBER for building bundles

---

package.json
yarn.lock

This is a stopgap to address the CVE now so that we can get the fix into 1.x instead of waiting for the Webpack upgrade.
* [Changes](https://github.com/kriszyp/json-schema/compare/v0.2.3...v0.4.0)
Resolves #1066 - CVE-2021-3918

Bumps `json-schema` from 0.2.3 to 0.4.0

---

src/core/public/chrome/ui/header/__snapshots__/collapsible_nav.test.tsx.snap
src/core/public/chrome/ui/header/__snapshots__/header.test.tsx.snap
src/core/public/chrome/ui/header/collapsible_nav.tsx

After the EUI bump, clicking the nav trigger button quickly closes and opens the collapsible nav. `outsideClickCloses` of `EuiCollapsibleNav` defaulting to `true` was resulting in the click-outside being triggered when the nav button was clicked and that hid the nav before the click handler for the nav button being triggered to open it again.
#1391

Fixes the header's nav trigger button not closing the nav

---

src/core/server/opensearch/version_check/ensure_opensearch_version.ts

Health check when enabled checked the entire cluster to get
the value set from the nodeId. Switching the health check to
query /_cluster/state/nodes should provide the same data needed
for the health check without transmitting the rest of the
cluster state data over the network.
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1354

[Improvement] node healthcheck optimization

---

.github/workflows/pr_check_workflow.yml

Bump Chromedriver to version 100 to match github
N/A

bumps chromedriver to v100

---

src/core/server/opensearch/version_check/ensure_opensearch_version.ts

Health check when enabled checked the entire cluster to get
the value set from the nodeId. Switching the health check to
query /_cluster/state/nodes should provide the same data needed
for the health check without transmitting the rest of the
cluster state data over the network.
Issue:
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1354
(cherry picked from commit 920cd5e45d28784ebd6406e332d2275efecd6026)

[Backport 1.x] [Improvement] node healthcheck optimization (#1386)

---

src/core/server/opensearch/version_check/ensure_opensearch_version.ts

Health check when enabled checked the entire cluster to get
the value set from the nodeId. Switching the health check to
query /_cluster/state/nodes should provide the same data needed
for the health check without transmitting the rest of the
cluster state data over the network.
Issue:
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1354
(cherry picked from commit 920cd5e45d28784ebd6406e332d2275efecd6026)

[Backport 1.3] [Improvement] node healthcheck optimization (#1386)

---

yarn.lock

Dashboards builds were failing because re2 version was overridden to 1.17.4 when it was checking for 1.15.4

Reverts re2 back to 1.15.4 from 1.17.4 to fix build issues

---

package.json
yarn.lock

`nth-check` is a dependency of `cheerio > css-select`. Even though our dependency on `cheerio@0.22.0` pulls in `nth-check@~1.0.1`, its signature hasn't changed* in `nth-check@2.0.1` and a resolution to bump works.
(*) The signature has changed but is backward compatible. 
Resolves #1081

Bumps the nested dependency of `nth-check` to v2.0.1

---

yarn.lock

Backport https://github.com/opensearch-project/OpenSearch-Dashboards/commit/ae8917263e1e20872aa5918cb517adb7148d35c8 from #1377

[Backport 1.x] Bump minimist from 1.2.5 to 1.2.6 (#1377)

---

package.json
yarn.lock

Backport https://github.com/opensearch-project/OpenSearch-Dashboards/commit/9e4e5ff43900b3875c1653b251aa5c71efa2569e from #1385

[Backport 1.x] Bumps `json-schema` from 0.2.3 to 0.4.0 (#1385)

---

MAINTAINERS.md

Adding Miki Barahmand and Ashwin P Chandran
to the maintainers doc.
n/a

[Admin] add current maintainers as of 04/2022

---

config/opensearch_dashboards.yml
package.json
packages/osd-opensearch/package.json
src/core/server/opensearch/client/client_config.ts
src/core/server/opensearch/opensearch_config.test.ts
src/core/server/opensearch/opensearch_config.ts
src/dev/build/tasks/os_packages/docker_generator/resources/bin/opensearch-dashboards-docker
yarn.lock

Add responseMaxHeapPercentage, memoryCircuitBreakerEnabled flags in opensearch_dashboards.yml
Signed-off-by: Zuocheng Ding <zding817@gmail.com>
This PR is going to add the capability for OSD to control the memory circuit breaker limits. 
Comment out some code due to the dependency from `opensearch-js` client. Tested through local modification in `elasticsearch`
Dependency : https://github.com/opensearch-project/opensearch-js/pull/207
https://github.com/opensearch-project/opensearch-js/issues/202

[Circuit-Breaker] Add memory circuit breaker configuration

---

src/plugins/vis_type_vislib/public/vislib/components/tooltip/_pointseries_tooltip_formatter.js
src/plugins/vis_type_vislib/public/vislib/components/tooltip/_pointseries_tooltip_formatter.test.js

On split series charts, the y axis label is incorrect. This change uses the value from the raw table data to correctly assign the value
#1262

fix(Tooltip): Fixes tooltip when split series charts are used

---

src/core/server/opensearch/version_check/opensearch_opensearch_dashboards_version_compatability.test.ts
src/core/server/opensearch/version_check/opensearch_opensearch_dashboards_version_compatability.ts
src/core/server/ui_settings/create_or_upgrade_saved_config/is_config_version_upgradeable.test.ts
src/core/server/ui_settings/create_or_upgrade_saved_config/is_config_version_upgradeable.ts

Allows for migrating from legacy app 6.8 to 7.10 to OSD 2.0,
without losing any settings.
Caught with BWC tests.
We should probably evalulate the strategy when we plan to split
from version sync from OpenSearch and if we want to make a
configurable matrix here. But for now making this an explicit
commit is preferable.
n/a

[2.x] support legacy config

---

package.json
packages/osd-config/package.json
packages/osd-dev-utils/package.json
packages/osd-telemetry-tools/package.json
packages/osd-ui-shared-deps/package.json
yarn.lock

This reverts commit 1f013aefac1f138a222cc12ce7c617c2b3407847.
n/a

Revert "Bump moment from 2.29.1 to 2.29.2 (#1439)"

---

src/dev/build/tasks/patch_native_modules_task.ts

Update re2 to 83
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1452

update re2 for linux, darwin, and windows

---

bwctest.sh
scripts/bwc/opensearch_dashboards_service.sh
scripts/bwc/opensearch_service.sh
scripts/bwc/utils.sh
scripts/bwctest_osd.sh

There were a couple issues related the BWC that was not supported
within the current iteration of the BWC script.
This fixes the following:
* Format of files being saved with color looks unreadable in txt form
* Exit code not being cypress exit code which would be the amount of errors.
* Issue because texts would fail but would return 0 to test runner because the script worked
* CI test runner expects to be able to call the same files twice (security:no-security)
* Issue because results for both were saved at the same time while original it was wiped clean
* Support from 'Playground' environments
* Source to actually call the script
* wget not available in CI runner
* Track PID of process instead of greping since greping was not reliable.
* OpenSearch config setup …

[Tests] BWC test improvements

---

src/dev/build/tasks/patch_native_modules_task.test.ts
src/dev/build/tasks/patch_native_modules_task.ts

We build and restore re2 for arm. With a license built in,
we zip the build artifact as .tar.gz. The original patchModule
method has a default extract method and path which causes issues
for extracting and using re2 arm build artifact. Therefore, we
modify the method in this PR by passing an overriddenExtractMethod
and an overriddenDestinationPath.
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1436

update re2 build for arm under node 14

---

src/cli_plugin/install/settings.js
src/cli_plugin/install/settings.test.js

Location of artifacts was updated here:
https://github.com/opensearch-project/opensearch-build/pull/1944
Updating the CLI for the out of the box experience with the same
warning as before:
At the time that this is committed there is no gurantee
that the latest build is the build that was select as the
final build.
n/a

[Plugins] fix default path to plugins

---

packages/osd-config/src/deprecation/deprecation_factory.test.ts
packages/osd-config/src/deprecation/deprecation_factory.ts
packages/osd-config/src/deprecation/types.ts
src/core/server/config/deprecation/core_deprecations.test.ts
src/core/server/config/deprecation/core_deprecations.ts
src/core/server/opensearch/opensearch_config.test.ts
src/core/server/opensearch/opensearch_config.ts

Adds deprecation functionality that uses new name without replacing old
Deprecates but not changes `opensearch.requestHeadersWhitelist`
Deprecates but not changes `server.xsrf.whitelist`
Deprecates but not changes `server.compression.referrerWhitelist`
Currently, this change is allowing the user to use `allowlist` version of the config names but under the hood, we're mapping the new value back to the old value used in code so that we don't have breaking changes for plugins. If the old non-inclusive config is used, a deprecation warning will be logged.

Deprecates non-inclusive config names

---

bwctest.sh
scripts/bwctest_osd.sh

The original BWC scripts did not expect qualifiers from the CI.
This allows for CI pass distributions with qualifiers for example:
`opensearch-dashboards-2.0.0-rc1`
n/a

[Tests][BWC][CI] handle distributions with qualifiers

---

bwctest.sh

Previously users could migrate from 6.8 to OpenSearch.
But for OpenSearch 2.x, users need to at least migrate to 7.0 in
the legacy application.
For BWC tests, we were previously testing 6.8 but now we start
from 7.0.
Related issue:
https://github.com/opensearch-project/OpenSearch/issues/1674
n/a

[Tests][BWC][CI] use ODFE 1.0.2

---

scripts/bwc/opensearch_service.sh

Performance analyzer was moved. It was causing a silent failure
which prevented the disable security plugin from being set.
Thus BWC tests were timing out with security disabled.
So I also moved to the security plugin config setup to the top
of the function to ensure this gets executed.
Source:
https://github.com/opensearch-project/performance-analyzer/commit/81d019af51a62d42592905cffc51f9c77cb8aaac
https://github.com/opensearch-project/opensearch-build/commit/6183df2bcb71c17d6b829f8184fb119c3b9a0a06
n/a

[Tests][BWC][CI] update performance analzyer location

---

src/plugins/console/public/application/components/console_menu.tsx

Copy as curl doesn't work in Dev Tools console due to usage of a
deprecated method:
https://developer.mozilla.org/en-US/docs/Web/API/Document/queryCommandSupported#browser_compatibility
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1471

[Bug] fix copy as curl

---

package.json

Adds the src/test_utils and src/core directories to the list of paths that should have their target directories cleaned. This fixes the Cheerio failure during `yarn osd bootstrap` and is recommended for the extensive restyling that comes with the stylelint change.
#1418

Adds src/test_utils/ and src/core paths to the target clean patterns

---

examples/expressions_example/common/expression_functions/render/avatar_fn.ts
examples/expressions_example/opensearch_dashboards.json
examples/expressions_example/public/components/playground_section.tsx
src/plugins/expressions/README.md
src/plugins/expressions/common/expression_renderers/types.ts
src/plugins/expressions/public/render.ts
src/plugins/input_control_vis/public/input_control_fn.ts
src/plugins/vis_type_table/public/table_vis_fn.ts
src/plugins/vis_type_timeseries/public/metrics_fn.ts
src/plugins/vis_type_vega/public/vega_fn.ts
src/plugins/vis_type_vislib/public/pie_fn.ts
src/plugins/vis_type_vislib/public/vis_type_vislib_vis_fn.ts
src/plugins/visualizations/public/expressions/visualization_function.ts
src/plugins/visualizations/public/expressions/visualization_renderer.tsx
src/plugins/visualizations/public/index.ts
src/plugins/visualizations/public/types.ts

Changes in this PR:
- Allows changing visualization expressions in the expressions demo playground. Using different visualization expressions or even editing the existing expression in `ReactExpressionRenderer` throws an error that uiState cannot be changed for a Visualization. This mitigates that by persisting the uiState for `ReactExpressionRenderer` for the playground.
- Improves the types of different render expression functions tied to visualizations.
- Corrects minor readme styling issues

Fix: Re-rendering visualization when expression changes and improves typing

---

.github/workflows/build_and_test_workflow.yml
dev-tools/get-version.sh
package.json
src/core/server/opensearch/version_check/opensearch_opensearch_dashboards_version_compatability.test.ts
src/core/server/opensearch/version_check/opensearch_opensearch_dashboards_version_compatability.ts
src/core/server/ui_settings/create_or_upgrade_saved_config/is_config_version_upgradeable.test.ts
src/core/server/ui_settings/create_or_upgrade_saved_config/is_config_version_upgradeable.ts

Increment from 2.0.0 to 3.0.0, also some version checks.
Also, add a release build verification workflow. To verify x64
and ARM64 artifacts are built successfully with dependencies.
n/a

[Version] Increment to 3.0

---

yarn.lock

Backport https://github.com/opensearch-project/OpenSearch-Dashboards/commit/0c3f901c569838b2708a079d058c7d09970b944c from #1173 
Resolves #1160 - CVE-2021-23566

[Backport 1.3] Bump nanoid from 3.1.30 to 3.2.0

---

yarn.lock

Backport https://github.com/opensearch-project/OpenSearch-Dashboards/commit/ae8917263e1e20872aa5918cb517adb7148d35c8 from #1377 
Resolves #1364 - CVE-2021-44906

[Backport 1.3] Bump minimist from 1.2.5 to 1.2.6

---

examples/ui_actions_explorer/public/context_menu_examples/util.ts
src/core/public/application/types.ts
src/core/public/chrome/nav_links/nav_link.ts
src/core/public/chrome/nav_links/to_nav_link.test.ts
src/core/types/app_category.ts
src/plugins/dashboard/public/application/actions/add_to_library_action.tsx
src/plugins/dashboard/public/application/actions/clone_panel_action.tsx
src/plugins/dashboard/public/application/actions/expand_panel_action.tsx
src/plugins/dashboard/public/application/actions/library_notification_action.tsx
src/plugins/dashboard/public/application/actions/replace_panel_action.tsx
src/plugins/dashboard/public/application/actions/unlink_from_library_action.tsx
src/plugins/embeddable/public/lib/actions/edit_panel_action.ts
src/plugins/embeddable/public/lib/panel/panel_header/panel_actions/add_panel/add_panel_action.ts
src/plugins/embeddable/public/lib/panel/panel_header/panel_actions/customize_title/customize_panel_action.ts
src/plugins/embeddable/public/lib/panel/panel_header/panel_actions/inspect_panel_action.ts
src/plugins/embeddable/public/lib/panel/panel_header/panel_actions/remove_panel_action.ts
src/plugins/index_pattern_management/public/management_app/mount_management_section.tsx
src/plugins/management/public/plugin.ts
src/plugins/management/public/types.ts
src/plugins/management/public/utils/management_item.ts
src/plugins/navigation/public/top_nav_menu/top_nav_menu_data.tsx
src/plugins/ui_actions/public/actions/action.ts
src/plugins/ui_actions/public/actions/action_internal.ts
src/plugins/ui_actions/public/service/ui_actions_service.test.ts
src/plugins/ui_actions/public/util/presentable.ts
src/plugins/visualize/public/application/utils/get_top_nav_config.tsx

Backport https://github.com/opensearch-project/OpenSearch-Dashboards/commit/ef3a9c07a07ffb7f7bfa662d29c88ed487b7e187 from #1496 
#1475

[Backport 1.x] fix(actions): Better type checks for icons

---

examples/ui_actions_explorer/public/context_menu_examples/util.ts
src/core/public/application/types.ts
src/core/public/chrome/nav_links/nav_link.ts
src/core/public/chrome/nav_links/to_nav_link.test.ts
src/core/types/app_category.ts
src/plugins/dashboard/public/application/actions/add_to_library_action.tsx
src/plugins/dashboard/public/application/actions/clone_panel_action.tsx
src/plugins/dashboard/public/application/actions/expand_panel_action.tsx
src/plugins/dashboard/public/application/actions/library_notification_action.tsx
src/plugins/dashboard/public/application/actions/replace_panel_action.tsx
src/plugins/dashboard/public/application/actions/unlink_from_library_action.tsx
src/plugins/embeddable/public/lib/actions/edit_panel_action.ts
src/plugins/embeddable/public/lib/panel/panel_header/panel_actions/add_panel/add_panel_action.ts
src/plugins/embeddable/public/lib/panel/panel_header/panel_actions/customize_title/customize_panel_action.ts
src/plugins/embeddable/public/lib/panel/panel_header/panel_actions/inspect_panel_action.ts
src/plugins/embeddable/public/lib/panel/panel_header/panel_actions/remove_panel_action.ts
src/plugins/index_pattern_management/public/management_app/mount_management_section.tsx
src/plugins/management/public/plugin.ts
src/plugins/management/public/types.ts
src/plugins/management/public/utils/management_item.ts
src/plugins/navigation/public/top_nav_menu/top_nav_menu_data.tsx
src/plugins/ui_actions/public/actions/action.ts
src/plugins/ui_actions/public/actions/action_internal.ts
src/plugins/ui_actions/public/service/ui_actions_service.test.ts
src/plugins/ui_actions/public/util/presentable.ts
src/plugins/visualize/public/application/utils/get_top_nav_config.tsx

Backport https://github.com/opensearch-project/OpenSearch-Dashboards/commit/ef3a9c07a07ffb7f7bfa662d29c88ed487b7e187 from #1496 
#1475

[Backport 1.3] fix(actions): Better type checks for icons

---

packages/osd-plugin-generator/package.json
yarn.lock

Backport https://github.com/opensearch-project/OpenSearch-Dashboards/commit/886f3e345201209cafd2ba49a8224662b238cd88 from #1512 
Resolves #1501 - CVE-2022-29078

[Backport 1.3] Bump ejs from 3.1.6 to 3.1.7

---

packages/osd-plugin-generator/package.json
yarn.lock

Backport https://github.com/opensearch-project/OpenSearch-Dashboards/commit/886f3e345201209cafd2ba49a8224662b238cd88 from #1512 
Resolves #1501 - CVE-2022-29078

[Backport 1.x] Bump ejs from 3.1.6 to 3.1.7

---

package.json
yarn.lock

Backports https://github.com/opensearch-project/OpenSearch-Dashboards/commit/9e4e5ff43900b3875c1653b251aa5c71efa2569e from #1385 
Resolves #1066 - CVE-2021-3918

[Backport 1.3] Bumps `json-schema` from 0.2.3 to 0.4.0

---

yarn.lock

Backport https://github.com/opensearch-project/OpenSearch-Dashboards/commit/e8c2121d852c9942c186d73e6fd7f498d3bb8ef0 from #1343
Addresses CVE-2020-8203, CVE-2021-23337, CVE-2020-28500

[Backport 1.3] Bump lodash-es from 4.17.15 to 4.17.21

---

yarn.lock

Backport 364ba75b7c73b88b71e6e01ef5b1203eca6f78de from #1456 
Resolves #1432 - CVE-2022-24785

[Backport 1.x] Bumps `moment` from 2.29.1 to 2.29.2

---

yarn.lock

Backport 364ba75b7c73b88b71e6e01ef5b1203eca6f78de from #1456 
Resolves #1432 - CVE-2022-24785

[Backport 1.3] Bumps `moment` from 2.29.1 to 2.29.2

---

package.json

https://opensearch.org/docs/2.0/ is now available.
n/a

[Docs] update doc reference to point to 2.0 docs

---

package.json
packages/osd-dev-utils/package.json
packages/osd-ui-shared-deps/package.json
yarn.lock

Addresses [CVE-2022-1214](https://github.com/advisories/GHSA-qg38-jmhh-6mj7)
[CHANGELOG](https://github.com/axios/axios/blob/master/CHANGELOG.md)
Bumps Chromedriver to v100 to match github actions
Bumps and pins axios to ^0.27.2 to address CVE
Resolves #1546

[CVE] Bumps Chromedriver to v100 and axios to v0.27.2

---

src/plugins/discover/public/get_inner_angular.ts

Add back icon directive, which injects SVG for EUI icons
Corrects rendering of discover context table row expansion buttons. The directive appears to have been removed when partially de-angularizing discover, without realizing the impact on the context doc table rendering.
fixes #1281

[Bug] fix missing discover context icon

---

release-notes/opensearch-dashboards.release-notes-2.0.0.md

Adds commits from #1552 and #1545. Any new PRs targeted for 2.0 must add an entry to the release notes.
Follow-up on #1566

Updates 2.0 release notes with latest commits

---

release-notes/opensearch-dashboards.release-notes-2.0.0.md
yarn.lock

Addresses CVE-2022-1537
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1579

[CVE] Resolves grunt to 1.5.3

---

.github/.codecov.yml

* Utilizes Codecov yaml configuration: https://docs.codecov.com/docs/codecov-yaml
The purpose of enforcing increasing code coverage over time is to attempt to improve the quality of changes via testing, reduce the need to request tests in PRs, and stay away from enforcing an ambiguous coverage percentage.
Validated the config:
```
$ curl -X POST --data-binary @.github/.codecov.yml https://codecov.io/validate
Valid!
{
"coverage": {
"status": {
"project": {
"default": {
"target": "auto"
}
}
}
}
}
```
N/A

Enforces equal or increasing code coverage in PRs

---

release-notes/opensearch-dashboards.release-notes-2.0.0.md
src/core/server/ui_settings/settings/theme.ts

There is currently to a PR to remove the v7 and v8 (beta) theme
versions within the application but it is getting stale:
https://github.com/opensearch-project/OpenSearch-Dashboards/pull/978
Since the v8 (beta) theme isn't actually planned and has the incorrect
version, we do not want end users to be able to change this setting.
In the essence of time, this will prevent this setting from showing in
the Advanced Settings page but will also not break users who set this
version already (however it will lock them into theme until they switched
by manually updating or deleting the config doc). Removing this setting
will force the default to be v8 (beta).
Temporary fix for:
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/494
But it should be removed completely.
Signed-off-by: …

[Purify] hide option for theme version in settings

---

.lycheeexclude
release-notes/opensearch-dashboards.release-notes-2.0.0.md
src/plugins/data/public/index.ts
src/plugins/data/public/public.api.md
src/plugins/data/public/search/errors/timeout_error.test.tsx
src/plugins/data/public/search/errors/timeout_error.tsx
src/plugins/data/public/search/search_interceptor.ts

Replaces the upsell with a more helpful message: `Your query has timed out. Contact your system administrator to review your index strategy or increase the run time.`
Resolves #1594

Removes irrelevant upsell in the timeout message

---

Dockerfile

package.json and yarn.lock already updated to 100.0.0
Updates the version of Chrome installed by Dockerfile, which is used for running Jenkins tests
Fixes #1623

[Tests] Update Dockerfile chrome version to match

---

src/plugins/region_map/public/index.ts
src/plugins/region_map/public/plugin.ts
src/plugins/region_map/public/region_map_type.js
src/plugins/vis_default_editor/public/components/sidebar/use_option_tabs.ts

Signed-off-by: Shivam Dhar <dhshivam@amazon.com>
[dashboards-maps](https://github.com/opensearch-project/dashboards-maps) repository contains `cutomImportMap` plugin which will be used for uploading custom GeoJSON files via region map plugin in OSD.
This PR helps in establishing the connection via usage of appropriate props and interfaces so that the extra tab (new component that will be added in dashboards-maps repo for taking user input) appears at the correct place in the region map visualization section.
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1408

Logic to integrate dashboards-maps plugin with OSD for custom GeoJSON upload feature

---

src/dev/build/tasks/os_packages/docker_generator/resources/bin/opensearch-dashboards-docker

Signed-off-by: manasvis <manasvis@amazon.com>
Removes duplicate variable defined in the opensearch-dashboards-docker file
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1429

[BUG] Remove duplicate var in the opensearch-dashboards-docker

---

.github/workflows/build_and_test_workflow.yml
TESTING.md
bwctest.sh
cypress/integration/with-security/check_loaded_data.js
cypress/integration/with-security/helpers/generate_data.js
cypress/integration/without-security/check_loaded_data.js
cypress/integration/without-security/helpers/generate_data.js
scripts/bwc/generate_test_data.sh
scripts/bwc/opensearch_dashboards_service.sh
scripts/bwc/utils.sh
scripts/bwctest_osd.sh

Add backwards compatibility tests to github workflow for PRs.
Also, fix for checking status of OpenSearch Dashboards since
api/status/ is not protected.
Also, enable ability to create test data since migration from
1.0.0 to 3.0.0 is not supported for OpenSearch currently.
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1465
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1651

[CI][BWC] add BWC tests to github actions

---

src/plugins/vis_type_metric/public/components/metric_vis.scss

Add container width to enable correct truncation
Normalize line height to prevent clipped descenders
Fixes #1643
Because of https://github.com/opensearch-project/OpenSearch-Dashboards/blob/6d1675cd989cdb8c271ee0d89227166162658b17/src/plugins/vis_type_metric/public/components/metric_vis.scss#L16-L17
The truncating styles set overflow to hidden. By adding container width, we enable the intended truncation effect, and normalizing the line-height prevents the descenders from overflowing.
Before:
After:
Note that in some cases, such as the currency metric with large text size in the After example, truncation doesn't behave great, because it's unaware of the underlying metric formatting. In the future, we may consider some sort of …

[Bug] Fix metric vizualization cut off text

---

.github/workflows/pr_check_workflow.yml
TESTING.md
bwctest.sh
cypress/integration/with-security/check_loaded_data.js
cypress/integration/with-security/helpers/generate_data.js
cypress/integration/without-security/check_loaded_data.js
cypress/integration/without-security/helpers/generate_data.js
dev-tools/get-version.sh
package.json
scripts/bwc/generate_test_data.sh
scripts/bwc/opensearch_dashboards_service.sh
scripts/bwc/utils.sh
scripts/bwctest_osd.sh

[CI][BWC] add BWC tests to github actions (#1624)
Add backwards compatibility tests to github workflow for PRs.
Also, fix for checking status of OpenSearch Dashboards since
api/status/ is not protected.
Also, enable ability to create test data since migration from
1.0.0 to 3.0.0 is not supported for OpenSearch currently.
Issue:
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1465
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1651
Backport PR:
https://github.com/opensearch-project/OpenSearch-Dashboards/pull/1624
Includes changes from:
https://github.com/opensearch-project/OpenSearch-Dashboards/pull/1502

[Backport 2.0][CI][BWC] add BWC tests to github actions (#1624) (#1659)

---

config/opensearch_dashboards.yml

Updates the config name `opensearch.requestHeadersWhitelist` to `opensearch.requestHeadersAllowlist` in the `opensearch_dashboards.yml` file

Changes config name in yml file to new non-deprecated name

---

src/setup_node_env/node_version_validator.js
src/setup_node_env/node_version_validator.test.js

This adjusts the runtime node version check to only compare major and minor version requirements. Systems that don't use the bundled NodeJS might update their node due to security patches, [which would currently break OpenSearch Dashboards unnecessarily](https://github.com/opensearch-project/project-website/pull/642#issuecomment-1024136539).
```bash
% grep 14.18 ../../package.json
"node": "14.18.2",
% nvm use 12
Now using node v12.22.8 (npm v6.14.15)
% node node_version_validator.js
OpenSearch Dashboards does not support the current Node.js version v12.22.8. Please use Node.js ~v14.18.
% nvm use 14
Now using node v14.18.3 (npm v6.14.15)
% node node_version_validator.js
%
```

Allow node patch versions to be higher on runtime

---

MAINTAINERS.md

I nominate Josh Romero (@joshuarrrr) as co-maintainer and the OpenSearch Dashboards maintainers unanimously approve this nomination.
Josh has consistently contributed high-quality PRs and is actively improving both the developer and user experience through contributions such as migrating all mocha tests to jest (#215)  and working with the community to redesign the OpenSearch Dashboards global header (#1583).
https://github.com/opensearch-project/OpenSearch-Dashboards/pulls/joshuarrrr
Josh privately accepted this nomination.
Thank you for your contributions Josh!
N/A

Adds Josh Romero as co-maintainer

---

.lycheeexclude
src/plugins/maps_legacy/public/common/opensearch_maps_client.js
src/plugins/maps_legacy/public/common/opensearch_maps_client.test.js
src/plugins/maps_legacy/public/map/service_settings.js
src/plugins/maps_legacy/public/map/service_settings.test.js
src/plugins/region_map/public/region_map_visualization.js

Signed-off-by: Junqiu Lei <junqiu@amazon.com>
Fix the bug that users can't load their own map tiles service by custom WMS when the environment unable access to default maps service(VPC or air-gapped region).
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1506

Fix wms maps can't load when can't request default map service

---

src/core/server/ui_settings/settings/notifications.ts
src/plugins/data/server/ui_settings.ts
src/plugins/home/public/application/components/__snapshots__/welcome.test.tsx.snap
src/plugins/home/public/application/components/welcome.tsx
src/plugins/maps_legacy/server/ui_settings.ts
src/plugins/telemetry/public/components/__snapshots__/opt_in_message.test.tsx.snap
src/plugins/telemetry/public/components/__snapshots__/opted_in_notice_banner.test.tsx.snap
src/plugins/telemetry/public/components/opt_in_message.tsx
src/plugins/telemetry/public/components/opted_in_notice_banner.tsx
src/plugins/vis_default_editor/public/components/agg_select.tsx

Signed-off-by: manasvis <manasvis@amazon.com>
Stemming from this PR: https://github.com/opensearch-project/OpenSearch-Dashboards/pull/565. Links inconsistently have noreferrer on the reference.
This change might not include adding noreferrer to all the links in the package, but links which already have 'rel="noopener"' in it to make it consistent throughout the repo as called out in the above PR.
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/567

[Improvement] Adding noreferrer on doc links

---

yarn.lock

Addresses Denial of Service (DoS) issue where a particular piece of input
will cause to enter an infinite loop and never return.
CVE: https://vuln.whitesourcesoftware.com/vulnerability/CVE-2022-25851
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1725

[CVE] Resolve `jpeg-js` to 0.4.4

---

packages/osd-config/src/__mocks__/env.ts
packages/osd-config/src/__snapshots__/env.test.ts.snap
packages/osd-config/src/env.test.ts
packages/osd-config/src/env.ts
src/core/server/bootstrap.ts
src/core/server/http/http_service.test.ts
src/core/server/http/http_service.ts
src/core/server/legacy/legacy_service.test.ts
src/core/server/legacy/legacy_service.ts
src/core/server/plugins/plugins_service.ts
src/core/test_helpers/osd_server.ts
src/legacy/server/logging/rotate/index.ts
src/legacy/server/logging/rotate/log_rotator.ts

Signed-off-by: manasvis <manasvis@amazon.com>
Coming from https://github.com/opensearch-project/OpenSearch/issues/2589.
[OpenSearch](https://github.com/opensearch-project/OpenSearch) repository is going to replace the terminology "master" with "cluster manager".
issue: https://github.com/opensearch-project/OpenSearch/issues/472#issuecomment-960298995, with the plan for its terminology replacement.
In this change we are replacing the instances of the terminology "isDevClusterMaster" with "isDevClusterManager".
https://github.com/opensearch-project/opensearch-dashboards/issues/1690
Parent https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1318

[Non-Inclusive Language] Replace isDevClusterMaster with isDevClusterManager

---

src/cli/cluster/cluster.mock.ts
src/cli/cluster/cluster_manager.ts
src/cli/cluster/worker.ts

Signed-off-by: manasvis <manasvis@amazon.com>
As part of the meta issue https://github.com/opensearch-project/OpenSearch/issues/2589 to track the plan and progress of applying inclusive naming across OpenSearch Repositories
Every repository that uses non-inclusive words should replace all the non-inclusive usages in the code base.
We are deprecating setupMaster in favor of setupClusterManager
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1689
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1318

[Deprecation] Deprecate setupMaster in favor of setupClusterManager

---

cypress/integration/with-security/check_loaded_data.js
cypress/integration/without-security/check_loaded_data.js

Incorrectly set the date range of the library. This sets the value
correctly and turns the dates into constants.
n/a

[CI][BWC] Date range for tests incorrect params

---

src/plugins/console/public/lib/osd/osd.js
src/plugins/console/server/lib/spec_definitions/json/generated/cluster.state.json

Signed-off-by: manasvinibs <manasvis@amazon.com>
As part of the meta issue opensearch-project/OpenSearch#2589 to track the plan and progress of applying inclusive naming across OpenSearch Repositories.
In this change we are replacing the instance of 'master' node with 'cluster_manager'.
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1688

[Deprecation] Deprecate master nodes and replace with cluster_manager nodes

---

packages/opensearch-safer-lodash-set/package.json
packages/osd-apm-config-loader/package.json
packages/osd-config-schema/package.json
packages/osd-config/package.json
packages/osd-std/package.json
packages/osd-utility-types/package.json
yarn.lock

- Partially addresses: CVE-2022-33987
- bumps `tsd` dependencies from `0.16.0` to `0.21.0` (latest)
- [Release change log](https://github.com/SamVerschueren/tsd/releases)
- Breaking changes:
- `0.17.0` includes "Require Node.js 12" - this is not a breaking change as we've already update to node `14.19.1`
`tsd v0.17.0` removes dependency chain:
- `update-notifier`
- `latest-version`
- `package-json`
- `got`
Partial fix for #1764

[CVE] Bump `tsd` to `0.21.0`

---

.github/workflows/create_doc_issue.yml

Example:
https://github.com/opensearch-project/OpenSearch-Dashboards/runs/7015324767?check_suite_focus=true
If we checkout the run, we can see the run fails with:
`Resource not accessible by integration`
Which I believe because the `documentation` label is not available in the doc repo. So instead of
creating a `documentation` label which seems redudant for a doc repo issue, we should use
`dashboards` because it exists and makes it more specific for the doc repo maintainers.
n/a

[CI] Update labels for doc issue creation workflow

---

src/core/server/http/http_service.ts
src/core/server/opensearch/version_check/ensure_opensearch_version.ts
src/plugins/telemetry/server/telemetry_collection/get_local_license.ts
src/plugins/vis_type_timeseries/server/lib/vis_data/request_processors/series/date_histogram.js

Signed-off-by: manasvinibs <manasvis@amazon.com>
As part of the meta issue opensearch-project/OpenSearch#2589 to track the plan and progress of applying inclusive naming across OpenSearch Repositories.
In this change, we are replacing 'master' in comments with 'cluster_manager'.
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1692

[Non-Inclusive Language] Replace master in comments

---

config/opensearch_dashboards.yml
src/core/public/chrome/ui/header/__snapshots__/header.test.tsx.snap
src/core/public/chrome/ui/header/__snapshots__/home_icon.test.tsx.snap
src/core/public/chrome/ui/header/header.test.tsx
src/core/public/chrome/ui/header/header.tsx
src/core/public/chrome/ui/header/home_icon.test.tsx
src/core/public/chrome/ui/header/home_icon.tsx
src/core/public/core_system.ts
src/core/server/opensearch_dashboards_config.ts
src/core/server/rendering/__snapshots__/rendering_service.test.ts.snap
src/core/server/rendering/rendering_service.tsx
src/core/server/rendering/types.ts
src/core/types/custom_branding.ts
src/legacy/server/config/schema.js

`useExpandedHeader` instead of `useExpandedMenu`
fixes #1583

[UX] Change name of expanded header config

---

src/core/server/opensearch/legacy/api_types.ts
src/core/server/server.api.md
src/plugins/console/server/lib/spec_definitions/json/generated/cat.cluster_manager.json

As part of the meta issue https://github.com/opensearch-project/OpenSearch/issues/2589 to track the plan and progress of applying inclusive naming across OpenSearch Repositories.
In this change, we are deprecating cat/_master API and adding _cat/cluster_manager endpoint.
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1686

[Deprecation] Deprecate cat master API in favor of cat cluster_manager

---

test/functional/apps/visualize/_tile_map.js

Maps zoom level were updated to be 14 as noted here:
https://github.com/opensearch-project/maps/issues/4#issuecomment-1162013693
n/a

[Tests] update tests to reflect max zoom level for maps

---

src/core/server/core_usage_data/core_usage_data_service.mock.ts
src/core/server/opensearch/legacy/cluster_client.test.ts
src/core/server/opensearch/legacy/opensearch_client_config.test.ts
src/core/server/opensearch/opensearch_config.ts

As part of the meta issue https://github.com/opensearch-project/OpenSearch/issues/2589 to track the plan and progress of applying inclusive naming across OpenSearch Repositories.
In this change, we are replacing 'apiVersion: master' with 'apiVersion:main'. 
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1687

[Deprecation] Deprecate the apiVersion: master value and replace with main

---

src/plugins/saved_objects_management/README.md
src/plugins/saved_objects_management/opensearch_dashboards.json
src/plugins/saved_objects_management/public/plugin.ts
src/plugins/saved_objects_management/public/register_services.ts
src/plugins/wizard/public/index.ts
src/plugins/wizard/public/plugin.ts
src/plugins/wizard/public/saved_visualizations/_saved_vis.ts
src/plugins/wizard/public/saved_visualizations/index.ts
src/plugins/wizard/public/saved_visualizations/saved_visualizations.ts
src/plugins/wizard/public/services/type_service/type_service.ts
src/plugins/wizard/public/types.ts
src/plugins/wizard/server/capabilities_provider.ts
src/plugins/wizard/server/plugin.ts
src/plugins/wizard/server/saved_objects/wizard_app.ts

Enables expected behavior in saved_object_managment plugin so that D&D saved objects can be inspected and edited just like native visualizations. Initializing the SavedObjectClass and SavedObjectLoader also provides the foundation for other saving/loading functionality
- Create README stub for saved_objects_management plugin
- Register wizard saved object loader with management plugin
- Add management methods to SavedObjectsType
- Add capabilities provider to wizard
- Add saved wizard vis SavedObjectClass and SavedObjectLoader
- Add public plugin start method
resolves #1817

[D&D] Enable basic saved object management

---

src/plugins/vis_type_timeseries/server/routes/vis.ts

Fixes https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1832
Signed-off-by: Brooke Green <cptn@amazon.com>
Fixes https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1832
Signed-off-by: Brooke Green <cptn@amazon.com>
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1832

[Bug] Fix new issue link

---

release-notes/opensearch-dashboards.release-notes-2.1.0.md

https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1771

Adds v2.1.0 release notes

---

src/plugins/wizard/public/plugin.ts
src/plugins/wizard/public/visualizations/index.ts

When navigating in and out of the app, the app is mounted multiple times. This causes the viz types to be registered multiple times causing an error that crashes it. This fix moves the registration out to the setup phase allowing the registration to happen only once.
-

fix(D&D): fixes reloading app

---

.github/workflows/pr_check_workflow.yml

GitHub env runs on Chrome 102. This is done to get the CI
working again on 1.x however there is a follow-up issue here:
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1746
However, there's an issue with Node existing on an a user that
the GitHub CI doesn't have permissions too.
n/a

[CI] Bump chromedriver to 102

---

src/plugins/wizard/public/application/components/data_tab/dropbox.scss
src/plugins/wizard/public/application/components/data_tab/dropbox.tsx
src/plugins/wizard/public/application/components/data_tab/use/use_prefers_reduced_motion.ts
src/plugins/wizard/public/application/components/workspace.tsx

This PR has the following changes
- Fixed minor dropbox css imperfections
- Adds dropbox animations (with prefers-reduced-motion support)
- Fixes issue where invalid expression does not clear visualization

[D&D] Dropbox style and animations

---

src/plugins/saved_objects_management/README.md
src/plugins/wizard/common/index.ts
src/plugins/wizard/common/wizard_saved_object_attributes.ts
src/plugins/wizard/public/application/app.tsx
src/plugins/wizard/public/application/components/top_nav.tsx
src/plugins/wizard/public/application/index.tsx
src/plugins/wizard/public/application/utils/breadcrumbs.ts
src/plugins/wizard/public/application/utils/get_saved_wizard_vis.ts
src/plugins/wizard/public/application/utils/get_top_nav_config.tsx
src/plugins/wizard/public/application/utils/state_management/store.ts
src/plugins/wizard/public/application/utils/state_management/style_slice.ts
src/plugins/wizard/public/application/utils/state_management/visualization_slice.ts
src/plugins/wizard/public/application/utils/use/use_saved_wizard_vis.ts
src/plugins/wizard/public/plugin.test.ts
src/plugins/wizard/public/plugin.ts
src/plugins/wizard/public/saved_visualizations/_saved_vis.ts
src/plugins/wizard/public/types.ts
src/plugins/wizard/server/saved_objects/wizard_app.ts

- Allows saving new d&d visualizations (both visualization and styling)
- Saved visualizations can be loaded using a new `/edit/:id` route
- Saved visualizations can be updated (edited and re-saved)
- Initial handling of editor state and "savability", although more work needed.
- Fixes #1867
- Fixes  #1868

[D&D] Basic saving, loading, and updating

---

src/plugins/maps_legacy/public/common/types/region_map_types.ts
src/plugins/region_map/public/region_map_type.js
src/plugins/region_map/public/region_map_visualization.js

Signed-off-by: Shivam Dhar <dhshivam@amazon.com>
Modifies region map rendering logic to show saved visualizations correctly.

Fixes issue on saving custom vector map options as part of visualization

---

config/opensearch_dashboards.yml
src/plugins/wizard/config.ts
src/plugins/wizard/public/plugin.ts
src/plugins/wizard/server/index.ts

As part of this https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1708 this PR is adding a flag in the YAML config to enable and disable the D&D plugin.
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1877

[D&D] Add a flag in the YAML config to enable and disable the D&D plugin

---

src/plugins/saved_objects_management/README.md
src/plugins/wizard/public/embeddable/index.ts
src/plugins/wizard/public/embeddable/wizard_component.tsx
src/plugins/wizard/public/embeddable/wizard_embeddable.tsx
src/plugins/wizard/public/embeddable/wizard_embeddable_factory.tsx
src/plugins/wizard/public/plugin.ts
src/plugins/wizard/public/services/type_service/visualization_type.tsx
src/plugins/wizard/public/types.ts
src/plugins/wizard/public/visualizations/metric/to_expression.ts

Enables adding a saved d&d visualization to a dashboard. Embedded d&d panel correctly uses saved object state, `toExpression`, and `ReactExpressionRenderer` to render a panel that matches the rendering in the d&d edit canvas.
This is just the implementation, and there are a number of todo items and refactoring remaining, as summarized in #1703. There are also some left over pieces from the embeddables example that will be removed (see #1910)
Fixes #1908

[D&D] Enable basic embeddable panels

---

src/plugins/visualizations/public/vis_types/vis_type_alias_registry.ts
src/plugins/wizard/public/plugin.ts

via appExtensions of alias registration
Updates alias registration with necessary `appExtensions`
fixes #1887

[D&D] Add wizard saved objects to vis list

---

package.json

Increment from 2.1 to 2.2.
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1771

[Version] Increment to 2.2

---

.github/workflows/build_and_test_workflow.yml
bwctest.sh

Test data generated with:
`yarn test:bwc -o https://artifacts.opensearch.org/releases/bundle/opensearch/2.1.0/opensearch-2.1.0-linux-x64.tar.gz -d https://artifacts.opensearch.org/releases/bundle/opensearch-dashboards/2.1.0/opensearch-dashboards-2.1.0-linux-x64.tar.gz -g true`
`yarn test:bwc -o https://artifacts.opensearch.org/releases/bundle/opensearch/2.1.0/opensearch-2.1.0-linux-x64.tar.gz -d https://artifacts.opensearch.org/releases/bundle/opensearch-dashboards/2.1.0/opensearch-dashboards-2.1.0-linux-x64.tar.gz -g true -s true`
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1771

[CI][Tests] add BWC tests for 2.2.0

---

src/plugins/wizard/public/application/components/data_tab/config_panel.tsx
src/plugins/wizard/public/application/components/data_tab/secondary_panel.tsx
src/plugins/wizard/public/application/components/data_tab/use/use_dropbox.tsx
src/plugins/wizard/public/application/components/workspace.tsx
src/plugins/wizard/public/application/utils/state_management/metadata_slice.ts
src/plugins/wizard/public/application/utils/state_management/preload.ts
src/plugins/wizard/public/application/utils/state_management/store.ts
src/plugins/wizard/public/application/utils/state_management/visualization_slice.ts

Adds autosave while editing aggregation
-

[D&D] Adds autosave while editing aggregation

---

.github/workflows/build_and_test_workflow.yml
cypress/integration/with-security/check_filter_and_query.js
cypress/integration/without-security/check_filter_and_query.js

Backport PRs will also run actions for pushs and PRs which is just
unneeded double work everytime. So this prevents that.
Also, BWC will run a complete array for every job in the matrix.
Now we set the environment variable to prevents the running of
the default versions.
n/a

[CI] Clean up for BWC tests & run only on PRs for backports

---

src/core/README.md

Fixing some of the broken links in core plugin API documentations
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1895

[BUG] Fixing some of the broken links in core plugin API documentations

---

src/plugins/wizard/public/application/_variables.scss
src/plugins/wizard/public/application/app.scss
src/plugins/wizard/public/application/components/data_tab/secondary_panel.tsx
src/plugins/wizard/public/application/components/workspace.scss
src/plugins/wizard/public/application/utils/state_management/metadata_slice.ts

- Autosave while editing was broken. This fixes it
- fixes compressed header ui
- minor fix in empty workspace animation
#1961

[D&D] Fixes autosave with debounce

---

src/plugins/credential_management/.eslintrc.js
src/plugins/credential_management/.i18nrc.json
src/plugins/credential_management/README.md
src/plugins/credential_management/common/index.ts
src/plugins/credential_management/opensearch_dashboards.json
src/plugins/credential_management/public/application.tsx
src/plugins/credential_management/public/components/app.tsx
src/plugins/credential_management/public/index.scss
src/plugins/credential_management/public/index.ts
src/plugins/credential_management/public/plugin.ts
src/plugins/credential_management/public/types.ts
src/plugins/credential_management/server/index.ts
src/plugins/credential_management/server/plugin.ts
src/plugins/credential_management/server/routes/index.ts
src/plugins/credential_management/server/types.ts

Signed-off-by: Louis Chu [clingzhi@amazon.com](mailto:clingzhi@amazon.com)
1. Instantiate credential management plugin code structure
2. Adopt New OSD Header
1. **RFC**: https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1388
2. **Epic**: https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1733
```
% node scripts/generate_plugin credential_management 
? Plugin name (use camelCase) credentialManagement
? Will this plugin be part of the OpenSearch Dashboards repository? Yes
? What type of internal plugin would you like to create OpenSearch Dashboards OSS
? Should an UI plugin be generated? Yes
? Should a server plugin be generated? Yes
succ 🎉
Your plugin has been created in src/plugins/credential_management
```
N/A

[MD] Instantiate credential management plugin code structure

---

packages/osd-std/src/__snapshots__/validate_object.test.ts.snap
packages/osd-std/src/index.ts
packages/osd-std/src/validate_object.test.ts
packages/osd-std/src/validate_object.ts
src/plugins/vis_type_vega/public/data_model/utils.test.js
src/plugins/vis_type_vega/public/data_model/utils.ts
src/plugins/vis_type_vega/public/vega_view/vega_base_view.js

Potential way to prevent XSS vulnerability discovered in the Vega charts OSD integration.
CVE link:
https://nvd.nist.gov/vuln/detail/CVE-2022-23713
Signed-off-by: Bandini Bhopi <bandinib@amazon.com>
Testing:
Sanity testing by creating Vega visualization from [Vega Example Gallery](https://vega.github.io/vega/examples/)

[CVE] Handle invalid query, index and date in vega charts filter handlers

---

src/core/public/_variables.scss
src/core/public/chrome/public/assets/round_filter.svg
src/core/public/chrome/ui/header/__snapshots__/header.test.tsx.snap
src/core/public/chrome/ui/header/__snapshots__/header_breadcrumbs.test.tsx.snap
src/core/public/chrome/ui/header/header_breadcrumbs.scss
src/core/public/chrome/ui/header/header_breadcrumbs.tsx

Signed-off-by: kaddy645 <xdeskart@amazon.com>
We'd like to enhance the breadcrumb component in the global header to be more useful and integrated into the overall look and feel
[Issue-1858](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1858)

[UX] Restyle global breadcrumbs

---

src/plugins/wizard/public/embeddable/wizard_embeddable_factory.tsx
src/plugins/wizard/public/plugin.ts
src/plugins/wizard/public/plugin_services.ts

Only show the edit visualization panel action if the user has the save visualization capability.
No issue, but related to #1922

[D&D] Add edit capability check to embeddable

---

src/plugins/data_source_management/README.md
src/plugins/data_source_management/common/index.ts
src/plugins/data_source_management/opensearch_dashboards.json
src/plugins/data_source_management/public/components/create_data_source_wizard/create_data_source_wizard.tsx
src/plugins/data_source_management/public/components/create_data_source_wizard/index.ts
src/plugins/data_source_management/public/components/data_source_table/data_source_table.tsx
src/plugins/data_source_management/public/components/data_source_table/index.ts
src/plugins/data_source_management/public/index.ts
src/plugins/data_source_management/public/management_app/index.ts
src/plugins/data_source_management/public/management_app/mount_management_section.tsx
src/plugins/data_source_management/public/plugin.ts
src/plugins/data_source_management/public/types.ts

Data source inside stack management setup. This will enable ramp up tasks #2028 and #2029
#2017

Data source inside stack management setup (#2017)

---

.github/workflows/build_and_test_workflow.yml

Enable CI for multi datasource feature branch

Enable CI for multi datasource feature branch

---

src/plugins/data_source/README.md
src/plugins/data_source/common/index.ts
src/plugins/data_source/opensearch_dashboards.json
src/plugins/data_source/server/index.ts
src/plugins/data_source/server/plugin.ts
src/plugins/data_source/server/types.ts

This PR adds an empty dataSource plugin, for future data source saved objects type and related function implementation
Signed-off-by: Yan Zeng <zengyan@amazon.com>
part of #1971

Add empty data source plugin

---

src/plugins/telemetry/server/telemetry_collection/get_cluster_info.ts

Introduced when renaming, I accidentally typed the param
incorrectly.
n/a

[BUG] Telemetry plugin cluster info rename error

---

src/plugins/maps_legacy/public/map/base_maps_visualization.js
src/plugins/maps_legacy/public/map/service_settings.js
src/plugins/vis_type_vega/public/services.ts
src/plugins/vis_type_vega/public/vega_view/vega_map_view.js

The configuration wasn't passed down to the options that was
expecting it to be available for the plugin to run the conditional
logic.
Value was undefined for region map. Also, cleaned up the vega map
view code.
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/2041

[BUG] show region blocked warning config not respected

---

src/plugins/data_source/common/data_sources/index.ts
src/plugins/data_source/common/data_sources/types.ts
src/plugins/data_source/server/plugin.ts
src/plugins/data_source/server/saved_objects/data_source.ts
src/plugins/data_source/server/saved_objects/index.ts
src/plugins/data_source_management/common/index.ts
src/plugins/data_source_management/opensearch_dashboards.json
src/plugins/data_source_management/public/components/create_data_source_wizard/create_data_source_wizard.tsx
src/plugins/data_source_management/public/components/create_data_source_wizard/index.ts
src/plugins/data_source_management/public/components/data_source_table/data_source_table.tsx
src/plugins/data_source_management/public/components/data_source_table/index.ts
src/plugins/data_source_management/public/index.ts
src/plugins/data_source_management/public/management_app/mount_management_section.tsx
src/plugins/data_source_management/public/plugin.ts
src/plugins/data_source_management/public/types.ts

Add data source register to savedObject
#1729
- [ x] Commits are signed per the DCO using --signoff

[MD] Add data source register to savedObject (#1729)

---

src/plugins/data_source_management/public/components/breadcrumbs.ts
src/plugins/data_source_management/public/components/data_source_table/data_source_table.tsx
src/plugins/data_source_management/public/components/data_source_table/index.ts
src/plugins/data_source_management/public/management_app/mount_management_section.tsx
src/plugins/data_source_management/public/types.ts

This PR will fix the breadcrumb and title issue on datasources management page
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/2029
Before:
After:

breadcrumbfix for datasource management

---

.github/workflows/build_and_test_workflow.yml
Jenkinsfile
TESTING.md
src/plugins/wizard/public/application/components/data_tab/dropbox.tsx
src/plugins/wizard/public/application/components/data_tab/title.tsx
src/plugins/wizard/public/application/components/searchable_dropdown.scss
src/plugins/wizard/public/application/components/searchable_dropdown.tsx
src/plugins/wizard/public/application/components/workspace.tsx
src/plugins/wizard/public/visualizations/metric/to_expression.test.ts
test/common/config.js
test/examples/embeddables/dashboard.ts
test/functional/apps/wizard/_base.ts
test/functional/apps/wizard/_experimental_vis.ts
test/functional/apps/wizard/index.ts
test/functional/config.js
test/functional/page_objects/index.ts
test/functional/page_objects/wizard_page.ts
test/mocha_decorations.d.ts
test/plugin_functional/test_suites/panel_actions/index.js

- Adds a few basic functional tests and sets up the page objects for running functional tests for the Wizard editor
- Updates readme for testing with details for chrome version
- Fixes a bug with the datasource selector styling

[D&D] Initial functional tests

---

package.json
packages/osd-ui-framework/package.json
packages/osd-ui-shared-deps/package.json
test/interpreter_functional/plugins/osd_tp_run_pipeline/package.json
test/plugin_functional/plugins/osd_sample_panel_action/package.json
test/plugin_functional/plugins/osd_tp_custom_visualizations/package.json

Adds OUI as a dependency to replace EUI
Fixes #1864

Alias OUI onto EUI

---

src/plugins/index_pattern_management/opensearch_dashboards.json
src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/__snapshots__/create_index_pattern_wizard.test.tsx.snap
src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/components/step_data_source/components/header/header.tsx
src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/components/step_data_source/components/header/index.ts
src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/components/step_data_source/index.ts
src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/components/step_data_source/step_data_source.tsx
src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/components/step_index_pattern/step_index_pattern.tsx
src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/create_index_pattern_wizard.test.tsx
src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/create_index_pattern_wizard.tsx
src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/lib/creation_flow.ts
src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/lib/index.ts
src/plugins/index_pattern_management/public/components/index_pattern_table/index_pattern_table.tsx
src/plugins/index_pattern_management/public/management_app/mount_management_section.tsx
src/plugins/index_pattern_management/public/types.ts

Add data source step into IndexPattern with Mock switch (#2064)
(#2064)

[MD][IP]Add data source step into IndexPattern with Mock switch (#2064)

---

src/plugins/vis_type_timeseries/public/application/components/vis_types/timeseries/vis.js

Signed-off-by: AbhishekReddy1127 <nallamsa@amazon.com>
Fixed the TSVB y-axis.
#1873

[Bug] fix TSVB y-axis

---

release-notes/opensearch-dashboards.release-notes-2.2.0.md

[Release] Adds v2.2.0 release note

---

src/plugins/credential_management/public/components/create_credential_wizard/create_credential_wizard.tsx
src/plugins/credential_management/public/components/edit_credential/edit_credential.tsx
src/plugins/credential_management/public/components/text_content/text_content.ts

Adding a button which can delete an existing credential page. 
Resolved issue #2027 
The listing page of credential management: 
The detail page of one credential:
The pop up window when click the delete button:
The listing page after deleting the credential:

[MD] Add delete an existing credential page button

---

src/plugins/data/common/index_patterns/index_patterns/index_pattern.ts
src/plugins/data/common/index_patterns/index_patterns/index_patterns.ts
src/plugins/data/common/index_patterns/types.ts
src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/create_index_pattern_wizard.tsx
src/plugins/index_pattern_management/public/management_app/mount_management_section.tsx

Link data source to Index Pattern:
```
{
"_index" : ".kibana_2",
"_id" : "index-pattern:949a8430-182e-11ed-b3f2-41cdf0d42687",
"_score" : 2.0281482,
"_source" : {
"index-pattern" : {
"title" : "op*",
"timeFieldName" : "customer_birth_date",
"fields" :  ...       
"type" : "index-pattern",
"references" : [
{
"id" : "642b19c0-182b-11ed-b09d-7906f0b40b66",
"type" : "data-source",
"name" : "dataSource"
}
],
"migrationVersion" : {
"index-pattern" : "7.6.0"
},
"updated_at" : "2022-08-09T21:59:45.906Z"
}
```
#2112 ,#2113

[MD][IP]Link datasource to index pattern

---

src/plugins/maps_legacy/public/map/base_maps_visualization.js

Signed-off-by: Junqiu Lei <junqiu@amazon.com>
When using WMS to customize base tile maps in region map or coordinate maps, user aren’t able to get into higher zoom levels than opensearch maps service default maximum zoom level.
By this PR fixed, the WMS max zoom value can be reached to 22 which is originally deigned [here](https://github.com/opensearch-project/OpenSearch-Dashboards/blob/9678a4bed88361574dc75f872c31d68834986562/src/plugins/maps_legacy/public/map/base_maps_visualization.js#L39)
https://github.com/opensearch-project/maps/issues/19

Fixes maps wms zoom limitation

---

package.json
src/dev/jest/config.js
src/plugins/credential_management/public/components/create_credential_wizard/create_credential_wizard.tsx
src/plugins/credential_management/public/components/credential_table/credentials_table.tsx
src/plugins/credential_management/public/components/edit_credential/edit_credential.tsx
src/plugins/credential_management/public/components/text_content/index.ts
src/plugins/credential_management/public/components/utils.ts
src/plugins/data_source/common/credentials/index.ts
src/plugins/data_source/common/credentials/types.ts
src/plugins/data_source/common/index.ts
src/plugins/data_source/config.ts
src/plugins/data_source/server/cryptography/cryptography_client.test.ts
src/plugins/data_source/server/cryptography/cryptography_client.ts
src/plugins/data_source/server/cryptography/index.ts
src/plugins/data_source/server/index.ts
src/plugins/data_source/server/plugin.ts
src/plugins/data_source/server/saved_objects/credential_saved_objects_client_wrapper.ts
src/plugins/data_source/server/saved_objects/credential_saved_objects_type.ts
src/plugins/data_source/server/saved_objects/index.ts

Signed-off-by: Louis Chu <clingzhi@amazon.com>
Add encrypt/decrypt module on data source plugin
1. #1850 
2. #2081

[MD] Add encrypt/decrypt module on data source plugin

---

src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/__snapshots__/create_index_pattern_wizard.test.tsx.snap
src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/components/step_data_source/components/header/header.tsx
src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/components/step_data_source/step_data_source.tsx
src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/components/step_index_pattern/components/header/__snapshots__/header.test.tsx.snap
src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/components/step_index_pattern/components/header/header.test.tsx
src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/components/step_index_pattern/components/header/header.tsx
src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/components/step_index_pattern/step_index_pattern.tsx
src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/components/step_time_field/components/header/__snapshots__/header.test.tsx.snap
src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/components/step_time_field/components/header/header.test.tsx
src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/components/step_time_field/components/header/header.tsx
src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/components/step_time_field/step_time_field.tsx
src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/create_index_pattern_wizard.tsx
src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/lib/creation_flow.test.ts
src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/lib/creation_flow.ts
src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/types.ts

Make step info in index pattern creation dynamic.
Before the step information was hard coded in index pattern management. this change make it dynamic base on flow.

[MD][IP]Make step info in index pattern creation dynamic

---

src/plugins/credential_management/public/components/create_credential_wizard/create_credential_wizard.tsx
src/plugins/credential_management/public/components/credential_table/credentials_table.tsx
src/plugins/credential_management/public/components/edit_credential/edit_credential.tsx
src/plugins/credential_management/public/components/utils.ts

Signed-off-by: Yibo Wang <yibow@amazon.com>
Optimization for credential listing page
1. Current listing page with modified layout of delete button
2. Solved text cases(singular vs plural)
3. Spinning in progress page when doing an action (eg. delete, update)
4. Confirmation pops up after delete button clicking. (Need to confirm the content in the confirmation box)
#2055

[MD][CM]credential listing page

---

src/plugins/data_source/server/client/configure_client.test.ts
src/plugins/data_source/server/client/configure_client.ts
src/plugins/data_source/server/data_source_service.ts
src/plugins/data_source/server/plugin.ts

integrate with crypto module to decrypt password
#1983

integrate with crypto module to decrypt password

---

src/plugins/data_source_management/public/components/create_data_source_wizard/create_data_source_wizard.tsx
src/plugins/data_source_management/public/components/create_edit_data_source_wizard/components/credentials_combox_box/credentials_combo_box.tsx
src/plugins/data_source_management/public/components/create_edit_data_source_wizard/create_edit_data_source_wizard.tsx
src/plugins/data_source_management/public/components/edit_data_source/edit_data_source.tsx
src/plugins/data_source_management/public/components/utils.ts
src/plugins/home/server/tutorials/haproxy_metrics/index.ts

- noAuth integration with API
- credential & endpoint fields validation
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/2019
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/2020

[MD] noAuth integration, credential & endpoint validation

---

src/plugins/data/common/search/opensearch_search/types.ts
src/plugins/data/common/search/search_source/search_source.test.ts
src/plugins/data/common/search/search_source/search_source.ts
src/plugins/data/opensearch_dashboards.json
src/plugins/data/server/search/opensearch_search/decide_client.ts
src/plugins/data/server/search/opensearch_search/opensearch_search_strategy.test.ts
src/plugins/data/server/search/opensearch_search/opensearch_search_strategy.ts

Refactor search strategy to conditionally user datasource client
#1988

[MD] Refactor search strategy to conditionally user datasource client

---

src/plugins/data_source_management/public/components/create_edit_data_source_wizard/create_edit_data_source_wizard.tsx

- Adding relation between Credential selection & NoAuth checkbox (User can select only one of them)
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/2021
https://user-images.githubusercontent.com/109986843/185689558-e28b5756-4870-4bc8-9010-5deecc9e3d08.mov

adding relation between credential selection and no auth checkbox

---

package.json
yarn.lock

```
opensearch-dashboards@1.4.0 /Users/szhongna/Projects/OpenSearch-Dashboards
└─┬ @elastic/eui@29.3.2
└── url-parse@1.5.10 
```
CVE-2022-0686

Fix CVE-2022-0686, add resolution for url-parse

---

.github/workflows/pr_check_workflow.yml

Bump chrome driver version to 1.4
```
│ warn Failure while creating webdriver instance
│ warn { SessionNotCreatedError: session not created: This version of ChromeDriver only supports Chrome version 102
│      Current browser version is 104.0.5112.79 with binary path /usr/bin/google-chrome
│          at Object.throwDecodedError (/home/runner/work/OpenSearch-Dashboards/OpenSearch-Dashboards/node_modules/selenium-webdriver/lib/error.js:550:15)
│          at parseHttpResponse (/home/runner/work/OpenSearch-Dashboards/OpenSearch-Dashboards/node_modules/selenium-webdriver/lib/http.js:565:13)
│          at Executor.execute (/home/runner/work/OpenSearch-Dashboards/OpenSearch-Dashboards/node_modules/selenium-webdriver/lib/http.js:491:26)
│          at …
```

Bump chrome driver version in PR check workflow

---

src/plugins/data_source/server/client/configure_client.ts

Add null auth header to child client spawn. See issue below for more details  and discussion
#2182

Add null auth header to child client spawn

---

yarn.lock

Original PR - https://github.com/opensearch-project/OpenSearch-Dashboards/pull/1890 (#1931)
Bump moment from 2.29.2 to 2.29.4
Bumps [moment](https://github.com/moment/moment) from 2.29.2 to 2.29.4.
- [Release notes](https://github.com/moment/moment/releases)
- [Changelog](https://github.com/moment/moment/blob/develop/CHANGELOG.md)
- [Commits](https://github.com/moment/moment/compare/2.29.2...2.29.4)
---
- dependency-name: moment
dependency-type: direct:production
...
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
(cherry picked from commit 30255abadc7db398406798e2588d8187407d6c4b) …

[Backport] [1.x] Bump moment from 2.29.2 to 2.29.4

---

src/plugins/vis_type_vislib/public/vislib/lib/binder.ts

* remove angular import and $scope from Binder class since there is
no usage in the code
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/2137

[DeAngular][visualization][vislib] remove angular from vislib

---

src/plugins/data_source/server/saved_objects/data_source.ts
src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/components/step_data_source/components/header/header.tsx
src/plugins/management/server/capabilities_provider.ts

Enable datasource link in saveObjectManagement.
-- Now can click and open the edit page of data source in save object management page.

[MD]Enable datasource link in saveObjectManagement

---

src/plugins/wizard/public/application/components/data_tab/secondary_panel.tsx
src/plugins/wizard/public/application/components/top_nav.tsx
src/plugins/wizard/public/application/utils/get_top_nav_config.tsx
src/plugins/wizard/public/application/utils/state_management/metadata_slice.ts
src/plugins/wizard/public/application/utils/state_management/store.ts
src/plugins/wizard/public/application/utils/use/use_can_save.ts
src/plugins/wizard/public/application/utils/use/use_saved_wizard_vis.ts
yarn.lock

Add two new state in metadata slice, disable save button when the visualization is not savable and display error messages using tooltip. 
Visualization is not savable when:
1. Empty visualization
2. No new changes detected after the visualization is loaded
3. Has unapplied/unsaved aggregation changes
4. Immediately after clicking the save button
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1879

[D&D] metadata slice 1879

---

src/plugins/wizard/public/application/components/data_tab/field_selector.tsx
src/plugins/wizard/public/application/components/data_tab/field_selector_field.tsx
src/plugins/wizard/public/application/components/data_tab/use/use_dropbox.tsx
src/plugins/wizard/public/application/utils/drag_drop/types.ts

Adds a `Count` field to the field picker in Wizard

[D&D] Adds count field to field picker

---

src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/create_index_pattern_wizard.tsx

Tweak fetch data back to original pattern - as it is not a good practice to have sideEffect in the legacy lifecycle  UNSAFE_componentWillMount
Related PR: https://github.com/opensearch-project/OpenSearch-Dashboards/pull/2146/files#diff-fe9f5fddd56a46e7e832e116eaef58350d813a4847106dbacfadc7046025fbed

[MD][IP]Tweak fetch data back to original

---

config/opensearch_dashboards.yml
src/core/server/opensearch/opensearch_config.test.ts
src/core/server/opensearch/opensearch_config.ts
src/core/server/opensearch/opensearch_service.ts
src/core/server/opensearch/version_check/ensure_opensearch_version.test.ts
src/core/server/opensearch/version_check/ensure_opensearch_version.ts

Enable filtering with custom health checks based on node attributes:
```
opensearch.optimizedHealthcheck.filters: {
attribute_key: "attribute_value",
}
```
Also, fixes issue that expects the response to array when it was a
dictionary.
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/2214
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/2203

Custom healthcheck with filters

---

src/plugins/vis_type_timeline/public/timeline_vis_type.tsx
src/plugins/visualizations/public/wizard/type_selection/type_selection.tsx

Signed-off-by: Bandini Bhopi <bandinib@amazon.com>
Changed Timeline Viz icon on the visualization type selection screen.
#2155

[UX] Change timeline icon

---

src/plugins/visualizations/public/legacy/build_pipeline.ts

In pipeline building, this PR adds `visConfig.title` and `uiState` properties for "visualization" function.
This aims 2 goals:
-    To be consistent with pipelines built with "buildPipelineVisFunction".
-    To provide "title" and "uiState" informations for visualizations.
This is currently a missing information for community plugins.

 [Visualizations] Adds visConfig.title and uiState to build pipeline function

---

src/core/server/http/router/router.ts
src/plugins/data_source/server/client/configure_client.ts
src/plugins/data_source/server/data_source_service.ts
src/plugins/data_source/server/lib/error.test.ts
src/plugins/data_source/server/lib/error.ts
src/plugins/data_source/server/plugin.ts

- remove useless and redundant try catch
- create `DataSourceConfigError`, which cast all 4xx to 400 and all 5xx to 400, and assign a 400 for non savedObjectClient error
- Refactor `router.ts` to conditionally deal with 400 DataSourceClientError
- TODO： 
#2210

[MD] Wrap datasource errors for route handlers to understand

---

src/plugins/wizard/public/application/components/data_tab/secondary_panel.tsx

[D&D] Persists index field on agg type change if possible

---

.github/workflows/pr_check_workflow.yml
bwctest.sh

add bwc test data (v2.2.0)
backport PR: https://github.com/opensearch-project/OpenSearch-Dashboards/pull/2148

[backport 2.x][CI][Tests] add BWC tests for 2.3.0

---

src/core/server/opensearch/version_check/ensure_opensearch_version.test.ts
src/core/server/opensearch/version_check/ensure_opensearch_version.ts

Original implementation incorrectly assumed the return list of nodes was an object array.
This PR:
https://github.com/opensearch-project/OpenSearch-Dashboards/pull/2232
Addressed the return but didn't catch the nodes.find in the return which is a function for an array.
Also, refactors to return a list of node_ids because the original implementation indicated that it should but it can return node ids but it never did. It only returned `null` or `_local`, the problem with this approach is that it doesn't expect valid node version with different DIs or filter out nodes when we pass `null` as the node ID for the node info call because it was fan out the request to all nodes.
Now this function will return `_local` if all the nodes share the same cluster_id using a greedy approach since we can …

[BUG] fix healthcheck logic to expect object and return ids

---

config/opensearch_dashboards.yml
src/core/server/opensearch/opensearch_config.test.ts
src/core/server/opensearch/opensearch_config.ts
src/core/server/opensearch/opensearch_service.ts
src/core/server/opensearch/version_check/ensure_opensearch_version.test.ts
src/core/server/opensearch/version_check/ensure_opensearch_version.ts

Backport e6bbb405441c7d59a8d5df6a477c5e432fa88b87 from #2232

[Backport 1.x] Custom healthcheck with filters (#2232)

---

src/core/server/opensearch/version_check/ensure_opensearch_version.test.ts
src/core/server/opensearch/version_check/ensure_opensearch_version.ts

Backport 349652685f84aa0c058315d846b110fcf8d23ee2 from #2277

[Backport 1.x] [BUG] fix healthcheck logic to expect object and return ids

---

src/core/server/opensearch/version_check/ensure_opensearch_version.test.ts
src/core/server/opensearch/version_check/ensure_opensearch_version.ts

Backport 349652685f84aa0c058315d846b110fcf8d23ee2 from #2277

[Backport 2.0] [BUG] fix healthcheck logic to expect object and return ids

---

package.json

Signed-off-by: Louis Chu <clingzhi@amazon.com>
Increment the version on the parent branch (2.x) to the next development iteration (2.4) after 2.3 branch cut.
Ref PR: https://github.com/opensearch-project/OpenSearch-Dashboards/pull/2096
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/2293

Increment from 2.3 to 2.4

---

src/plugins/wizard/public/application/utils/get_top_nav_config.tsx
src/plugins/wizard/public/application/utils/use/use_can_save.ts
src/plugins/wizard/public/visualizations/vislib/area/to_expression.ts
src/plugins/wizard/public/visualizations/vislib/common/get_pipeline_params.ts
src/plugins/wizard/public/visualizations/vislib/common/index.ts
src/plugins/wizard/public/visualizations/vislib/histogram/to_expression.ts
src/plugins/wizard/public/visualizations/vislib/line/to_expression.ts

Fixes rendering timeseries for the bar, line and area charts.
#2307

[D&D] Fixes time series for new chart types

---

src/plugins/saved_objects/README.md

Document on saving index pattern relationship in the saved object plugin.
resolves #2205 #2218

README.md for saving index pattern relationship

---

DEVELOPER_GUIDE.md
package.json
src/dev/build/args.test.ts
src/dev/build/args.ts
src/dev/build/build_distributables.ts
src/dev/build/cli.ts
src/dev/build/lib/build.test.ts
src/dev/build/lib/config.test.ts
src/dev/build/lib/config.ts
src/dev/build/lib/platform.ts
src/dev/build/tasks/clean_tasks.ts
src/dev/build/tasks/create_archives_task.ts
src/dev/build/tasks/nodejs/clean_node_builds_task.ts
src/dev/build/tasks/nodejs/download_node_builds_task.ts
src/dev/build/tasks/nodejs/extract_node_builds_task.ts
src/dev/build/tasks/nodejs/verify_existing_node_builds_task.ts
src/dev/build/tasks/notice_file_task.ts

* De-Couple Dashboards linux building process
When running yarn build --skip-os-packages it will build 4 tarballs for Dashboards (2x linux, 1x macOS, 1x windows) and takes 10+min to do so.
In this PR, we break the building process to allow single linux to build. If run `yarn build-platform --linux-x64` only linux x64 tarball is created. Same for linux arm64 and darwin x64. You could run `yarn build-platform --linux-arm64` and `yarn build-platform darwin-x64`.
partially solved:
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/473
* support multiple CLI options and fix comments
Signed-off-by: AnanZ <ananzh@amazon.com>
* fix wording to artifacts
Signed-off-by: AnanZ <ananzh@amazon.com>
Co-authored-by: Ubuntu …

[1.0-healthcheck] De-Couple Dashboards linux building process (#795) (#2345)

---

.github/workflows/build_and_test_workflow.yml

To save resources and job runners, some PRs do not need to run the full test suite. For PRs and pushes with markdown changes only, the build and test workflow will be skipped. (Linter test should be okay to skipped since it will automatically run with every commit). For PRs and pushes with markdown changes along with other changes, the build and test workflow will not be skipped. 
resolves #1214

add path ignore for markdown files

---

yarn.lock

Updates `moment-timezone`
dependabot PR: #2229 
#2262
#2263

Bump moment-timezone from 0.5.34 to 0.5.37

---

src/plugins/data_source/server/saved_objects/data_source_saved_objects_client_wrapper.ts
src/plugins/data_source_management/public/components/edit_data_source/components/edit_form/edit_data_source_form.tsx
src/plugins/data_source_management/public/types.ts

- Fix update data source with no Auth type  -- will get `500` Internal Error
- Validation on data source update/bulk update request to block updating data source URL

[MD] Fix update data source & block update endpoint

---

src/plugins/data_source_management/README.md
src/plugins/data_source_management/public/components/data_source_table/data_source_table.tsx
src/plugins/data_source_management/public/components/utils.test.ts
src/plugins/data_source_management/public/components/utils.ts

Resolving PR #2334 comments
[[List any issues this PR will resolve]](https://github.com/opensearch-project/OpenSearch-Dashboards/pull/2334)
- [] All tests pass

reafctor based on PR 2334 comments to merge to main

---

src/plugins/index_pattern_management/public/components/index_pattern_table/empty_index_pattern_prompt/empty_index_pattern_prompt.tsx
src/plugins/index_pattern_management/public/components/index_pattern_table/index_pattern_table.tsx
src/plugins/management/public/components/landing/landing.tsx

Fixes console error when loading management app
#2048

Fixes management app breadcrumb error

---

.github/workflows/build_and_test_workflow.yml
bwctest.sh

Test data generated with:
yarn test:bwc -o https://artifacts.opensearch.org/releases/bundle/opensearch/2.3.0/opensearch-2.3.0-linux-x64.tar.gz -d https://artifacts.opensearch.org/releases/bundle/opensearch-dashboards/2.3.0/opensearch-dashboards-2.3.0-linux-x64.tar.gz -g true
yarn test:bwc -o https://artifacts.opensearch.org/releases/bundle/opensearch/2.3.0/opensearch-2.3.0-linux-x64.tar.gz -d https://artifacts.opensearch.org/releases/bundle/opensearch-dashboards/2.3.0/opensearch-dashboards-2.3.0-linux-x64.tar.gz -g true -s true
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/2230

[CI][Tests] Add BWC tests for 2.4.0

---

yarn.lock

Backport 06abe83e0180f391a84c742cf5594866bc747ea2 from https://github.com/opensearch-project/OpenSearch-Dashboards/pull/2166

[Backport 2.x] Upgrade geckodriver to 3.0.2 to partially fix CVE-2022-33987 (#2166)

---

src/plugins/vis_type_table/opensearch_dashboards.json
src/plugins/vis_type_table/public/components/table_vis_app.tsx
src/plugins/vis_type_table/public/components/table_vis_component.tsx
src/plugins/vis_type_table/public/plugin.ts
src/plugins/vis_type_table/public/table_vis_renderer.tsx
yarn.lock

implement a plain EuiDataGrid component use the basic pagenation, sort and format.
After implementing a plain datagrid component, we have this display in the table vis:
This is just to show it could render a basic data grid component. Column will be formatted to grid column with appropriate title in the coming PRs.

[Table Visualization] add a plain datagrid component

---

MAINTAINERS.md

I nominated Abby Hu (@abbyhu2000) to be a co-maintainer for OpenSearch Dashboards through our [nomination process](https://github.com/opensearch-project/.github/blob/main/MAINTAINERS.md#nomination). The maintainers have agreed, and Abby has kindly accepted.
Abby has made multiple contributions to OpenSearch Dashboards, the most notable of which is [Custom Branding (#826)](https://github.com/opensearch-project/OpenSearch-Dashboards/commit/9037b61e9d4da3c44f0ba0fab8f803db5873ef89) along with many other bug fixes and changes, including some of her recent contributions to VisBuilder. ([Commits](https://github.com/opensearch-project/OpenSearch-Dashboards/commits?author=abbyhu2000))

Adding @abbyhu2000 as a Dashboards co-maintainer

---

.github/pull_request_template.md
.github/workflows/changelog_verifier.yml
CHANGELOG.md

Adding a CHANGELOG.md to be manually update per PR
This should be automated though in the future.
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/2394

Add CHANGELOG.md and related workflows

---

CHANGELOG.md
MAINTAINERS.md

Signed-off-by: Neumann <neumanns@amazon.com>
Adding Yan Zeng as Maintainer

Adding @zengyan-amazon as a Dashboards co-maintainer

---

package.json

Version increment to 2.3.1
Part of https://github.com/opensearch-project/opensearch-build/issues/2648

Version increment to 2.3.1

---

.github/workflows/pr_check_workflow.yml
bwctest.sh

(cherry picked from commit 08d05047d125afa7a6f5426de400b1a8b9be62c5)
Backport to this PR https://github.com/opensearch-project/OpenSearch-Dashboards/pull/2393
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/2230

[Backport 2.x][CI][Tests] Add BWC tests for 2.4.0 (#2393)

---

CHANGELOG.md
src/plugins/wizard/opensearch_dashboards.json
src/plugins/wizard/public/application/components/data_tab/config_panel.scss
src/plugins/wizard/public/application/components/data_tab/secondary_panel.tsx
src/plugins/wizard/public/application/components/top_nav.tsx
src/plugins/wizard/public/application/components/workspace.scss
src/plugins/wizard/public/application/utils/get_top_nav_config.tsx
src/plugins/wizard/public/application/utils/use/use_index_pattern.tsx
src/plugins/wizard/public/plugin.ts
src/plugins/wizard/public/plugin_services.ts
src/plugins/wizard/public/saved_visualizations/transforms.test.ts
src/plugins/wizard/public/saved_visualizations/transforms.ts
src/plugins/wizard/public/visualizations/common/expression_helpers.ts
src/plugins/wizard/public/visualizations/vislib/area/to_expression.ts
src/plugins/wizard/public/visualizations/vislib/common/create_vis.ts
src/plugins/wizard/public/visualizations/vislib/histogram/histogram_vis_type.ts
src/plugins/wizard/public/visualizations/vislib/histogram/to_expression.ts
src/plugins/wizard/public/visualizations/vislib/line/to_expression.ts
test/functional/apps/wizard/_base.ts

This fixes the following issues with the VisBuilder bar chart:
- Fixes timeseries bar chart visualization using `src/plugins/wizard/public/visualizations/vislib/common/create_vis.ts`
- Fixes visualization shift when editing agg by passing `metricAggs` in `src/plugins/wizard/public/application/components/data_tab/secondary_panel.tsx`
- Renames "Histogram" to "Bar" in vis type picker since it is more accurate and histogram is a subset of Bar chart visualizations
Misc styling fixes in 
- `src/plugins/wizard/public/application/components/workspace.scss`: Reduces animation impact
- `src/plugins/wizard/public/application/components/data_tab/config_panel.scss`: fixes incorrect margin for custom styled `visEditorAggParam`
Misc improvements:
- Consolidates transform from redux state to saved …

[Vis Builder] Misc Bar chart fixes

---

yarn.lock

Updated yarn.lock file for leaflet-vega and vega-interpreter package.
Seem like there is a version mismatch between package.json and yarn.lock in this [commit](https://github.com/opensearch-project/OpenSearch-Dashboards/commit/bebbcca30d4b3f43c800eb5360681d2072d0ba7c#diff-51e4f558fae534656963876761c95b83b6ef5da5103c4adef6768219ed76c2de) in PR: #2352

Fix leaflet-vega and vega-interpreter mismatch in yarn.lock file

---

CHANGELOG.md
package.json
src/plugins/wizard/public/application/utils/schema.json
src/plugins/wizard/public/application/utils/use/use_saved_wizard_vis.ts
src/plugins/wizard/public/application/utils/wizard_state_validation.test.ts
src/plugins/wizard/public/application/utils/wizard_state_validation.ts
yarn.lock

Validate style and visualization state schema before dispatching state updates when loading wizard. Error messages are shown via toast.
resolves #1882

[Viz Builder] State validation before dispatching and loading

---

CHANGELOG.md
src/core/server/http/router/router.ts
src/core/server/opensearch/legacy/cluster_client.ts
src/plugins/data/server/index_patterns/fetcher/index_patterns_fetcher.ts
src/plugins/data/server/index_patterns/fetcher/lib/field_capabilities/field_capabilities.ts
src/plugins/data/server/index_patterns/fetcher/lib/opensearch_api.ts
src/plugins/data/server/index_patterns/fetcher/lib/resolve_time_pattern.ts
src/plugins/data/server/index_patterns/routes.ts
src/plugins/data_source/server/client/client_pool.ts
src/plugins/data_source/server/client/configure_client.test.ts
src/plugins/data_source/server/client/configure_client.ts
src/plugins/data_source/server/client/index.ts
src/plugins/data_source/server/data_source_service.test.ts
src/plugins/data_source/server/data_source_service.ts
src/plugins/data_source/server/legacy/client_config.test.ts
src/plugins/data_source/server/legacy/client_config.ts
src/plugins/data_source/server/legacy/configure_legacy_client.test.mocks.ts
src/plugins/data_source/server/legacy/configure_legacy_client.test.ts
src/plugins/data_source/server/legacy/configure_legacy_client.ts
src/plugins/data_source/server/legacy/index.ts
src/plugins/data_source/server/lib/error.ts
src/plugins/data_source/server/plugin.ts
src/plugins/data_source/server/types.ts
src/plugins/index_pattern_management/server/routes/resolve_index.ts

Legacy clients are using `elasticsearch.js` 
new clients are using `openearch.js`
```
Usage:
data_source.context.legacy.getClient(datasourceId).callAPI("ping", {params: something}, {options: something})
```
- Add support for data source legacy client
- launch another pool within the `data-source service` setup stage, specifically for legacy clients
- returns a function interface `LegacyAPICaller` as required by elasticsearch.js clients
- Refactor index pattern related logic to use `data_source.legacy.getClient`
- Added UT
#2133 
#2386

Support legacy client for data source

---

src/plugins/data/common/field_formats/field_format.ts
src/plugins/vis_type_table/public/components/table_vis_component.tsx
src/plugins/vis_type_table/public/components/table_vis_grid_columns.tsx
src/plugins/vis_type_table/public/types.ts
src/plugins/vis_type_table/public/utils/convert_to_formatted_data.ts
src/plugins/vis_type_table/public/utils/index.ts

Datagrid column is not properly displayed. Title is missing. No filter-in and filter-out.
In this PR, we restore couple of things:
* display column title correctly
* deangular and re-use formatted column
* convert formatted column to data grid column
* restore filter in and filter out value functions
current table vis:
filter in:
filter out:

[Table Visualization] restore datagrid columns

---

CHANGELOG.md
package.json
src/dev/jest/config.js
yarn.lock

Addresses potential ReDoS issue from d3-color version < 3.1.0
d3-color is used as a sub-dependency of elastic/chart package. since there is no function change form 1.4 to 3.1.0, we could add resolution in package.json to overwrite the version.
```
yarn why d3-color
[1/4] Why do we have the module "d3-color"...?
warning Resolution field "typescript@4.0.2" is incompatible with requested version "typescript@~4.5.2"
=> Found "d3-color@1.4.1"
info Has been hoisted to "d3-color"
- "workspace-aggregator-26115f01-dd15-42ff-8fa9-cd8d075aae02" depends on it
- Hoisted from "_project_#@elastic#charts#d3-color"
- Hoisted from …
```

fix d3-color and potential security issue

---

CHANGELOG.md
packages/osd-plugin-helpers/README.md
packages/osd-plugin-helpers/src/cli.ts
packages/osd-plugin-helpers/src/contexts.ts
packages/osd-plugin-helpers/src/tasks/clean.ts
packages/osd-plugin-helpers/src/tasks/create_archive.ts
packages/osd-plugin-helpers/src/tasks/index.ts
packages/osd-plugin-helpers/src/tasks/optimize.ts
packages/osd-plugin-helpers/src/tasks/update_versions.ts
packages/osd-plugin-helpers/src/tasks/write_public_assets.ts
packages/osd-plugin-helpers/src/tasks/write_server_files.ts
packages/osd-plugin-helpers/src/tasks/yarn_install.ts

This extends the existing plugin-helpers package by adding a `version` command to facilitate updating the versions in the manifest and package files of a plugin.
Addresses the #1801 for OSD plugins

Extends plugin-helpers to be used for automating version changes

---

.github/pull_request_template.md
.github/workflows/changelog_verifier.yml
CHANGELOG.md

Backport 806e96c18672fcb7b7587740b2dec32aa48d6ec7 from #2414

[Backport 1.x] Add CHANGELOG.md and related workflows (#2414)

---

yarn.lock

Backport 77b6068f1206af5682affaa2e977540c69a330f2 from #2361

[Backport 1.3] Bump moment-timezone from 0.5.34 to 0.5.37 (#2361)

---

yarn.lock

Backport 77b6068f1206af5682affaa2e977540c69a330f2 from #2361

[Backport 1.x] Bump moment-timezone from 0.5.34 to 0.5.37 (#2361)

---

CHANGELOG.md
src/plugins/discover/public/application/components/doc/use_opensearch_doc_search.ts

Add datasource param to low-level search call in Discover, that fixes the rendering issue of single document, while searching against data source
Part of #2400, issue reported by @abbyhu2000

[MD] Fix view single document issue by updating low-level search call param

---

CHANGELOG.md
packages/osd-plugin-helpers/src/tasks/update_versions.ts

In Node v10, there was no dedicated module for fs/promises. Causing the plugin helpers to fail while building out plugins.
Solved by importing promises from fs then using the desired methods.
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/2485

[BUG] Plugin helpers fix related to fs promises module

---

CHANGELOG.md
config/opensearch_dashboards.yml

Add sample config of multi data source to yml template.
#2427

Add sample config of multi data source to yml template.

---

CHANGELOG.md
src/plugins/data_source/README.md
src/plugins/data_source_management/README.md

Add dataSource & dataSourceManagement Readme
#2436 
#2437
#2199 
#2158

Add dataSource & dataSourceManagement Readme

---

src/core/server/http/router/router.ts
src/plugins/data/server/index_patterns/fetcher/index_patterns_fetcher.ts
src/plugins/data/server/index_patterns/fetcher/lib/field_capabilities/field_capabilities.ts
src/plugins/data/server/index_patterns/fetcher/lib/opensearch_api.ts
src/plugins/data/server/index_patterns/fetcher/lib/resolve_time_pattern.ts
src/plugins/data/server/index_patterns/routes.ts
src/plugins/data_source/server/client/client_pool.ts
src/plugins/data_source/server/client/configure_client.test.ts
src/plugins/data_source/server/client/configure_client.ts
src/plugins/data_source/server/client/index.ts
src/plugins/data_source/server/data_source_service.test.ts
src/plugins/data_source/server/data_source_service.ts
src/plugins/data_source/server/legacy/client_config.test.ts
src/plugins/data_source/server/legacy/client_config.ts
src/plugins/data_source/server/legacy/configure_legacy_client.test.mocks.ts
src/plugins/data_source/server/legacy/configure_legacy_client.test.ts
src/plugins/data_source/server/legacy/configure_legacy_client.ts
src/plugins/data_source/server/legacy/index.ts
src/plugins/data_source/server/lib/error.ts
src/plugins/data_source/server/plugin.ts
src/plugins/data_source/server/types.ts
src/plugins/index_pattern_management/server/routes/resolve_index.ts

Backport commit 746b9df179f9f095befe5a2ec9df841fc287baf7 from #2204

[Backport 2.x] [MD] Support legacy client for data source (#2204)

---

src/plugins/vis_type_table/public/components/table_vis_component.tsx
src/plugins/vis_type_table/public/types.ts
src/plugins/vis_type_table/public/utils/index.ts
src/plugins/vis_type_table/public/utils/use_pagination.ts

* add pagination
patically resolved:

[Table Visualization] restore pagination to table vis

---

CHANGELOG.md
config/opensearch_dashboards.yml
src/plugins/wizard/public/application/components/top_nav.tsx
src/plugins/wizard/public/application/utils/get_top_nav_config.test.tsx
src/plugins/wizard/public/application/utils/get_top_nav_config.tsx
src/plugins/wizard/public/application/utils/mocks.ts
src/plugins/wizard/public/plugin.ts
src/plugins/wizard/public/types.ts

After selecting a dashboard, create a new wizard directly from the dashboard and have the option to add to that dashboard.
resolves #2381

[VizBuilder] Create a new wizard directly on a dashboard

---

src/plugins/vis_type_table/public/components/table_vis_component.tsx
src/plugins/vis_type_table/public/components/table_vis_grid_columns.tsx
src/plugins/vis_type_table/public/types.ts

* add resizable state to column
Partially resolve:
Now table vis column width can be adjusted:

[Table Visualization] make table vis column resizable

---

.github/workflows/cypress_workflow.yml
CHANGELOG.md

Run the functional test repo here:
https://github.com/opensearch-project/opensearch-dashboards-functional-test
Apart of github actions.
n/a

[CI] Run functional test repo as workflow

---

.github/workflows/pr_check_workflow.yml
CHANGELOG.md

Current browser version is 106 whereas chromedriver is 104. This PR bump the version to solve the mismatch.

[1.x] bump chromedriver to 106 to fix function test fail issue

---

CHANGELOG.md
package.json
release-notes/opensearch-dashboards.release-notes-1.3.6.md
yarn.lock

* Resolves [CVE-2022-0144](https://github.com/advisories/GHSA-4rq4-32rv-6wp6) by bumping package shelljs to 0.8.5

[backport 1.x][CVE-2022-0144] bump shelljs from 0.8.4 to 0.8.5

---

CHANGELOG.md
src/plugins/index_pattern_management/opensearch_dashboards.json
src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/components/step_data_source/components/header/__snapshots__/header.test.tsx.snap
src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/components/step_data_source/components/header/header.test.tsx
src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/components/step_data_source/components/header/header.tsx
src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/components/step_data_source/step_data_source.tsx
src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/components/step_index_pattern/components/header/header.scss
src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/components/step_index_pattern/components/header/header.tsx
src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/components/step_index_pattern/step_index_pattern.tsx
src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/types.ts
src/plugins/index_pattern_management/public/components/utils.ts
src/plugins/index_pattern_management/public/types.ts

Address UX comments for index pattern pages
1. Switch from SaveObjectFinder to EUISelectable 
2. Add data source title to step index pattern
3. Error toast while fetching existing data sources
TBA

[MD] Address UX comments for index pattern pages

---

CHANGELOG.md
src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/create_index_pattern_wizard.tsx
src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/lib/get_indices.test.ts
src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/lib/get_indices.ts

Display error toast for create index pattern with data source.
Make use of the existing toast component instead of swallowing error, we generate the pop-up for data source use case in index pattern
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/2285

[MD] Display error toast for create index pattern with data source

---

CHANGELOG.md
src/plugins/data/common/index_patterns/index_patterns/index_pattern.ts
src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/components/step_data_source/components/header/__snapshots__/header.test.tsx.snap
src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/components/step_data_source/components/header/header.scss
src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/components/step_data_source/components/header/header.test.tsx
src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/components/step_data_source/components/header/header.tsx

Update copy on index patten config DS step
https://github.com/opensearch-project/ux/issues/40

[MD]Update copy on index patten config DS step

---

CHANGELOG.md
src/plugins/wizard/public/application/utils/get_top_nav_config.tsx

Edit wizard directly on dashboard following the steps:
1. choose a dashboard
2. click `Edit` button on the top nav bar of the dashboard
3. select the setting button on the top right of a wizard on that dashboard
4. click edit wizard
When finish editing wizard, there are some different options for saving that wizard, this PR ensures the below five different flows for editing wizard all work as expected:
1. `Save and return` button on top nav bar --> will save the original wizard and return back to the dashboard without displaying an additional save modal
2. `Save as` button on top nav bar --> will open a save modal
* `save as new wizard` toggle on + `add to dashboard after saving` toggle on + Save and return button
* `save as new wizard` toggle on + `add to dashboard after saving` toggle …

Edit wizard directly on dashboard

---

CHANGELOG.md
TESTING.md

Updates the Readme to call out the change in functional testing for OpenSearch Dashboards
- #2462

Updates functional test readme

---

CHANGELOG.md
src/plugins/data_source/public/index.ts
src/plugins/data_source/public/plugin.ts
src/plugins/data_source/public/types.ts
src/plugins/data_source_management/opensearch_dashboards.json
src/plugins/data_source_management/public/components/data_source_column/data_source_column.tsx
src/plugins/data_source_management/public/plugin.ts
src/plugins/index_pattern_management/public/components/__snapshots__/utils.test.ts.snap
src/plugins/index_pattern_management/public/components/index_pattern_table/index_pattern_table.tsx
src/plugins/index_pattern_management/public/components/utils.ts
src/plugins/index_pattern_management/public/index.ts
src/plugins/index_pattern_management/public/management_app/mount_management_section.tsx
src/plugins/index_pattern_management/public/service/column_service/column_service.ts
src/plugins/index_pattern_management/public/service/column_service/index.ts
src/plugins/index_pattern_management/public/service/index_pattern_management_service.ts
src/plugins/index_pattern_management/public/types.ts

Adding data source column to index pattern table.
- Created column service in index pattern management public plugin, so that other plugin can register column to index pattern table
- Created data source column and register it to index pattern table, the column cell will show
- Data source title if present
- Deleted tag if configured data source deleted
UX mock up:

[MD]Add column service to index pattern & Register data source column

---

CHANGELOG.md
src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/create_index_pattern_wizard.tsx
src/plugins/index_pattern_management/public/components/experimental_callout/__snapshots__/experimental_callout.test.tsx.snap
src/plugins/index_pattern_management/public/components/experimental_callout/experimental_callout.test.tsx
src/plugins/index_pattern_management/public/components/experimental_callout/experimental_callout.tsx
src/plugins/index_pattern_management/public/components/experimental_callout/index.ts
src/plugins/index_pattern_management/public/components/index_pattern_table/index_pattern_table.tsx

Signed-off-by: Yibo Wang <yibow@amazon.com>
This PR fixes several issues from https://github.com/opensearch-project/ux/issues/16
Index pattern listing page:
Index pattern create page-step one:
Index pattern create page-step two:
Index pattern create page-step three:
https://github.com/opensearch-project/ux/issues/37
https://github.com/opensearch-project/ux/issues/39
https://github.com/opensearch-project/ux/issues/41
https://github.com/opensearch-project/ux/issues/43

[MD] Add experimental callout for index pattern section

---

CHANGELOG.md
config/opensearch_dashboards.yml
src/dev/build/tasks/os_packages/docker_generator/resources/bin/opensearch-dashboards-docker

Add data source config to opensearch-dashboards-docker

[MD]Add data source config to opensearch-dashboards-docker

---

src/plugins/vis_type_table/public/components/table_vis_component.tsx
src/plugins/vis_type_table/public/components/table_vis_grid_columns.tsx
src/plugins/vis_type_table/public/table_vis_fn.ts
src/plugins/vis_type_table/public/types.ts

* add sort state (asc | desc)  to column

[Table Visualization] make table vis column sortable

---

src/plugins/vis_type_table/public/components/table_vis_component.tsx
src/plugins/vis_type_table/public/types.ts
src/plugins/vis_type_table/public/utils/convert_to_formatted_data.ts

* format table cell to show formatted Date and percent
* restore showTotal feature: it allows table vis to show total, avg, min, max and count statics on count
* fix some type errors
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/2379

[Table Visualization] format table cell and restore showTotal feature

---

src/plugins/vis_type_table/opensearch_dashboards.json
src/plugins/vis_type_table/public/components/table_vis_component.tsx
src/plugins/vis_type_table/public/components/table_vis_control.tsx
src/plugins/vis_type_table/public/to_ast.ts
src/plugins/vis_type_table/public/types.ts
src/plugins/vis_type_table/public/utils/convert_to_csv_data.ts

* add addtional action in toolbar to allow export data to csv. there are two types of csv, raw and formatted. raw is the original data and formatted is to show formatted Date and percentage data when needed.
* when table is not saved, export csv file will be named as unsaved-raw.csv if choose raw. when table is saved with a filename, it will be saved as [filename]-[raw/formatted].csv
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/2379
Previous table export feature is build in agg_table.js and agg_table.html : 
With DataGrid component, we could use its toolbar. Toolbar is on top of the table vis. We could put export left or right of the toolbar. See what is shown in the example:
We could also add a toolbar option, so toolbar, by default, is not shown when click table …

[Table Visualization]restore export csv feature to table vis

---

CHANGELOG.md
src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/components/step_index_pattern/components/header/header.tsx

Skip data source view when pick default - When OSD enable data source feature, user can still choose to use default cluster, in this case, index pattern creation should render with previous experience for this phase.

[MD] skip data source view when pick default

---

src/plugins/vis_type_table/public/components/table_vis_app.scss
src/plugins/vis_type_table/public/components/table_vis_app.tsx
src/plugins/vis_type_table/public/components/table_vis_component.tsx
src/plugins/vis_type_table/public/components/table_vis_component_group.tsx
src/plugins/vis_type_table/public/table_vis_response_handler.ts

This PR implement a group component TableVisGroupComponent utilizing TableVisComponent as sub component. It also adds a title to TableVisComponent.
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/2379
Split in rows:
Split in columns:

[Table Visualization] split table in rows and columns

---

CHANGELOG.md
src/plugins/wizard/public/application/_variables.scss
src/plugins/wizard/public/application/app.scss
src/plugins/wizard/public/application/app.tsx
src/plugins/wizard/public/application/components/data_tab/config_panel.scss
src/plugins/wizard/public/application/components/data_tab/config_panel.tsx
src/plugins/wizard/public/application/components/data_tab/field_selector.scss
src/plugins/wizard/public/application/components/data_tab/field_selector.tsx
src/plugins/wizard/public/application/components/data_tab/field_selector_field.scss
src/plugins/wizard/public/application/components/data_tab/field_selector_field.tsx
src/plugins/wizard/public/application/components/data_tab/index.scss
src/plugins/wizard/public/application/components/data_tab/index.tsx
src/plugins/wizard/public/application/components/data_tab/schema_to_dropbox.tsx
src/plugins/wizard/public/application/components/data_tab/secondary_panel.tsx
src/plugins/wizard/public/application/components/data_tab/title.tsx
src/plugins/wizard/public/application/components/left_nav.tsx
src/plugins/wizard/public/application/components/option.scss
src/plugins/wizard/public/application/components/option.tsx
src/plugins/wizard/public/application/components/right_nav.tsx
src/plugins/wizard/public/application/components/searchable_dropdown.scss
src/plugins/wizard/public/application/components/searchable_dropdown.tsx
src/plugins/wizard/public/application/components/side_nav.scss
src/plugins/wizard/public/application/components/top_nav.scss
src/plugins/wizard/public/application/components/top_nav.tsx
src/plugins/wizard/public/application/components/workspace.scss
src/plugins/wizard/public/application/components/workspace.tsx
src/plugins/wizard/public/embeddable/disabled_visualization.scss
src/plugins/wizard/public/embeddable/disabled_visualization.tsx

Replace class name prefixes wiz with vb for visualization builder.
solve bullet three of #1706

[VisBuilder] Change classname prefix wiz to vb

---

CHANGELOG.md
src/plugins/vis_builder/public/embeddable/disabled_visualization.tsx
src/plugins/vis_builder/public/embeddable/vis_builder_embeddable.tsx
src/plugins/vis_builder/public/embeddable/vis_builder_embeddable_factory.tsx
src/plugins/vis_builder/public/visualizations/vislib/area/area_vis_type.ts
src/plugins/vis_builder/public/visualizations/vislib/histogram/histogram_vis_type.ts
src/plugins/vis_builder/public/visualizations/vislib/line/line_vis_type.ts
src/plugins/visualize/public/application/components/visualize_listing.tsx

This PR consists of 2 main changes
- Fixes for issues identified from Functional tests (commit: 563342)
- Adds additional aggregation parameters for Vislib charts (Bar, Line and Area) (Commit: d96669)

[Vis Builder] Update vislib params and misc fixes

---

src/plugins/vis_type_table/public/utils/convert_to_formatted_data.ts

Currently, when we split table by columns, the split column is shown both in the table title and as a separate column. This is not needed. In this PR, we remove the repeated column in split tables in col.
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/2579#issuecomment-1281099947
Now if you split a table with city, city will not repeat itself as a separate column:

[Table Visualization][IMPROVE] remove repeated column from split tables

---

CHANGELOG.md
src/plugins/data_source_management/public/components/create_button/create_button.test.tsx
src/plugins/data_source_management/public/components/create_button/create_button.tsx
src/plugins/data_source_management/public/components/create_data_source_wizard/__snapshots__/create_data_source_wizard.test.tsx.snap
src/plugins/data_source_management/public/components/create_data_source_wizard/components/create_form/__snapshots__/create_data_source_form.test.tsx.snap
src/plugins/data_source_management/public/components/create_data_source_wizard/components/create_form/create_data_source_form.tsx
src/plugins/data_source_management/public/components/create_data_source_wizard/create_data_source_wizard.tsx
src/plugins/data_source_management/public/components/data_source_table/__snapshots__/data_source_table.test.tsx.snap
src/plugins/data_source_management/public/components/data_source_table/data_source_table.tsx
src/plugins/data_source_management/public/management_app/compoenent/experimental_callout/experimental_callout.tsx

Signed-off-by: Yibo Wang <yibow@amazon.com>
Resolve the meta issue for datasource list page and create page from Multi-datasource UX sign off meeting. 
Below are screenshots for UX modification:
1. Datasource experimental callout wording: 
2. Datasource table column header wording:
3. Datasource listing page delete button refactor:
4. Datasource listing page create button in empty state:
5. Datasource create page spacing between header description and Connection Details:
6. Datasource create page endpoint field placeholder wording:
7. Datasource create page toast that fail to save: 
8. Datasource list page fail toast: 
#2614 
#2615 
#2616 
#2617 
#2618 
#2619 
#2620
#2626

[MD]Address comments from UX sign-off meeting-Datasource list and create page

---

CHANGELOG.md
src/plugins/vis_builder/public/application/components/data_source_select.tsx
src/plugins/vis_builder/public/application/components/data_tab/field_search.tsx
src/plugins/vis_builder/public/application/components/experimental_info.tsx
src/plugins/vis_builder/public/application/components/right_nav.tsx
src/plugins/vis_builder/public/application/utils/breadcrumbs.ts
src/plugins/vis_builder/public/application/utils/get_top_nav_config.tsx
src/plugins/vis_builder/public/application/utils/use/use_can_save.ts
src/plugins/vis_builder/public/embeddable/disabled_visualization.tsx
src/plugins/vis_builder/public/embeddable/vis_builder_embeddable_factory.tsx
src/plugins/vis_builder/public/plugin.ts

Rename wizard to visBuilder in i18n id and formatted message id
resolves part of #1706

[Vis Builder] Rename wizard to visBuilder in i18n id and formatted message id

---

CHANGELOG.md
src/plugins/data/public/ui/typeahead/_suggestion.scss

In this PR, we fixed the suggestion list cutoff in an easy way. We remove width 250px and add block display to allow browser to select a width and add ellipsis at the bottom.
However, we might have longer input that can't fit into the search. When we truncate the search, the elements look the same which might be still an issue for customer usage. We definitely need more feedbacks on the cutoff behavior.
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/2555
Previous:
Current:

[BUG] fix suggestion list cutoff issue

---

src/plugins/vis_type_table/public/components/table_vis_component.tsx
src/plugins/vis_type_table/public/types.ts
src/plugins/vis_type_table/public/utils/use_pagination.ts

* remove local col width state to allow split tables to fetch updated col width state
* fix type errors in usePagination
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/2579#issuecomment-1281078065
Now col width state is sharing to all split tables in row/col

[Table Visualization][BUG] remove local column width state

---

CHANGELOG.md
package.json
yarn.lock

Signed-off-by: himsgupta1122 <hmsgupt@gmail.com>
[IBM X-Force ID: 220063](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/2641)
[CVE 2022-3517](https://nvd.nist.gov/vuln/detail/CVE-2022-3517)

[CVE 2022-3517] Bump minimatch to 3.0.5  and [IBM X-Force ID: 220063] unset-value to 2.0.1

---

CHANGELOG.md
src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/__snapshots__/create_index_pattern_wizard.test.tsx.snap
src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/components/step_index_pattern/step_index_pattern.test.tsx
src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/components/step_index_pattern/step_index_pattern.tsx
src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/create_index_pattern_wizard.tsx

Error handling only happens before loading the indices to step index pattern but not within. Therefore pass the error handling inside the step as well to render error state.
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/2598

Apply get indice error handling in step index pattern

---

src/plugins/vis_type_table/public/to_ast.ts

Currently, when we enable Show partial rows in the Options panel, we see metrics been added to every column even though Show metrics for every bucket/level is not enabled.
Metrics are added and returned when we enable the partial rows. This PR fixed the bug by slice the returned data to allow only the last set of metrices.
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/2579#issuecomment-1287435381

[Table Visualization][BUG] partical rows shows metrics for all columns

---

CHANGELOG.md
yarn.lock

Signed-off-by: Zilong Xia <zilongx@amazon.com>
* Resolves [CVE-2022-23647](https://github.com/advisories/GHSA-3949-f494-cm99) by bumping `prismjs` up to 1.29.0
* This one is mainly a lock file refresh (aka remove the `prismjs` entry in lock file and then re-run `yarn osd bootstrap`)
Resolves https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1358

[CVE] Bump prismjs to 1.29.0 to fix CVE-2022-23647

---

CHANGELOG.md
src/core/server/http/router/router.ts
src/plugins/data/server/plugin.ts
src/plugins/data/server/search/opensearch_search/opensearch_search_strategy.ts
src/plugins/data/server/search/search_service.ts
src/plugins/data_source/server/client/configure_client.ts
src/plugins/data_source/server/index.ts
src/plugins/data_source/server/legacy/configure_legacy_client.ts
src/plugins/data_source/server/lib/error.test.ts
src/plugins/data_source/server/lib/error.ts
src/plugins/data_source/server/plugin.ts
src/plugins/data_source/server/types.ts
src/plugins/index_pattern_management/server/routes/resolve_index.ts

Refactor data source server side error handling
- Rename `DataSourceConfigError` to `DataSourceError`
- Add helper `createDataSourceError()` to create data source error from:
- Opensearch client error
- legacy client error
- saved object client error
- other runtime errors
- Replace  usage of `new DataSourceError(e)` with `createDataSourceError(e) `
- can't directly import `createDataSourceError()` to `data` plugin, have to import from data source plugin setup interface, otherwise, some other UTs in other modules fail
- refactor to move data source error response logic from `router.ts` to `resolve_index.ts`.  I check all our codebase, only the route handler defined  resolve_index is missing error handling. All other `internal/xxx/xxx` API has err …

[MD] Refactor data source server side error handling

---

CHANGELOG.md
packages/osd-config-schema/src/errors/__snapshots__/schema_error.test.ts.snap
src/plugins/wizard/public/application/components/top_nav.tsx
src/plugins/wizard/public/application/utils/get_top_nav_config.test.tsx
src/plugins/wizard/public/application/utils/get_top_nav_config.tsx
src/plugins/wizard/public/application/utils/mocks.ts
src/plugins/wizard/public/plugin.ts
src/plugins/wizard/public/types.ts

* Create a new wizard directly on a dashboard
After selecting a dashboard, create a new wizard directly from the dashboard and have the option to add to that dashboard.
* hook change to solve browser warning
* Move onsave out from getTopNavConfig function and added unit tests
* Add changelog

[Backport 2.x] [VizBuilder] Create a new wizard directly on a dashboard (#2384)

---

CHANGELOG.md
src/plugins/data/public/ui/typeahead/_suggestion.scss

In this PR, we fixed the suggestion list cutoff in an easy way. We remove width 250px and add block display to allow browser to select a width and add ellipsis at the bottom.
However, we might have longer input that can't fit into the search. When we truncate the search, the elements look the same which might be still an issue for customer usage. We definitely need more feedbacks on the cutoff behavior.
Issue resolved:
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/2555
Backport PR:
https://github.com/opensearch-project/OpenSearch-Dashboards/pull/2607

[Backport 1.x][BUG]fix suggestion list cutoff issue

---

CHANGELOG.md
docs/multi-datasource/client_management_design.md

Update MD design doc to fix some typos

[MD] Tweak multiple data source design doc

---

CHANGELOG.md
src/plugins/index_pattern_management/public/components/index_pattern_table/empty_state/__snapshots__/empty_state.test.tsx.snap
src/plugins/index_pattern_management/public/components/index_pattern_table/empty_state/empty_state.tsx

Signed-off-by: Bandini Bhopi <bandinib@amazon.com>
`Add Integration` and `Add sample data` both take the user to the add sample data page. This PR removes `Add Integration` button until we have long term fix for Integration workflow.
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/2684
**Before:**
**After fix:**

Removes Add Integration button

---

.github/workflows/backport.yml

Prevent backport workflow from running on umerged PRs

---

.github/workflows/backport.yml
CHANGELOG.md

GitHub action for backporting got updated to change custom branch to head template.
This was causing issues in clean up and skipping steps
n/a

[CI] update backport custom branch name

---

CHANGELOG.md
MAINTAINERS.md

Backport PR:
https://github.com/opensearch-project/OpenSearch-Dashboards/pull/2419

[Backport 2.4] Adding @zengyan-amazon as a Dashboards co-maintainer

---

CHANGELOG.md
MAINTAINERS.md

Backport PR:
https://github.com/opensearch-project/OpenSearch-Dashboards/pull/2419

[Backport 2.x] Adding @zengyan-amazon as a Dashboards co-maintainer

---

CHANGELOG.md
packages/osd-pm/src/utils/validate_dependencies.ts
src/core/server/saved_objects/migrations/core/index_migrator.test.ts
src/core/server/saved_objects/migrations/core/opensearch_index.ts
src/dev/notice/cli.js
src/plugins/apm_oss/server/tutorial/instructions/apm_server_instructions.ts
src/plugins/data/README.md

backport 82f82a197426d94bb9ec126c1d9b3fc736fddca3 from #2638

[Backport 1.x] Removed Leftover X Pack references

---

CHANGELOG.md
package.json
yarn.lock

https://github.com/opensearch-project/OpenSearch-Dashboards/issues/2771

change geckodriver version to make consistency

---

CHANGELOG.md
src/plugins/data_source/README.md
src/plugins/data_source/audit_config.ts
src/plugins/data_source/config.ts

- Fix the issue on seen on windows platform. 
- Change audit log to disable by default
#2792

[MD] Update default audit log path

---

package.json
yarn.lock

change geckodriver version
combine https-proxy-agent in yarn.lock
Issue Resolved:
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/2771
Backport PR:
https://github.com/opensearch-project/OpenSearch-Dashboards/pull/2772

[Backport 2.x]Change geckodriver version to make consistency

---

package.json
yarn.lock

change geckodriver version
combine https-proxy-agent in yarn.lock
Issue Resolved:
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/2771
Backport PR:
https://github.com/opensearch-project/OpenSearch-Dashboards/pull/2772

[Backport 2.4]Change geckodriver version to make consistency

---

CHANGELOG.md
yarn.lock

* Bump makelogs to remove dependency on got
* Also dusted off the lock file a bit
Fixes #1764

Bump makelogs to remove dependency on got

---

yarn.lock

* Bump makelogs to remove dependency on got
* Also dusted off the lock file a bit
Fixes #1764

[Backport 2.x][CVE-2022-33987]Bump makelogs to remove dependency on got (#2801)

---

yarn.lock

* Bump makelogs to remove dependency on got
* Also dusted off the lock file a bit
Fixes #1764

[Backport 2.4][CVE-2022-33987]Bump makelogs to remove dependency on got

---

src/dev/build/tasks/os_packages/docker_generator/resources/bin/opensearch-dashboards-docker

Updates missing visbuilder flag rename
-

[VisBuilder] Change VisBuilder flag for docker config

---

CHANGELOG.md
release-notes/opensearch-dashboards.release-notes-2.4.0.md

* Add CHANGELOG.md for 2.4.0
* Add "Release Notes" for 2.4.0

Adds CHANGELOG.md and Release Notes for 2.4.0

---

CHANGELOG.md
src/plugins/data_source_management/public/components/create_data_source_wizard/__snapshots__/create_data_source_wizard.test.tsx.snap
src/plugins/data_source_management/public/components/create_data_source_wizard/components/create_form/__snapshots__/create_data_source_form.test.tsx.snap
src/plugins/data_source_management/public/components/create_data_source_wizard/components/create_form/create_data_source_form.tsx
src/plugins/data_source_management/public/components/edit_data_source/__snapshots__/edit_data_source.test.tsx.snap
src/plugins/data_source_management/public/components/edit_data_source/components/edit_form/__snapshots__/edit_data_source_form.test.tsx.snap
src/plugins/data_source_management/public/components/edit_data_source/components/edit_form/edit_data_source_form.tsx
src/plugins/data_source_management/public/components/edit_data_source/components/update_password_modal/__snapshots__/update_password_modal.test.tsx.snap
src/plugins/data_source_management/public/components/edit_data_source/components/update_password_modal/update_password_modal.tsx

https://github.com/opensearch-project/OpenSearch-Dashboards/issues/2657

[MD] Add explicit no spellcheck on password fields

---

CHANGELOG.md
src/plugins/vis_type_table_new/public/components/table_vis_component.tsx

Currently, the first column of table vis won't sort. This PR fixes the bug.
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/2827

[Bug][Table Visualization] Fix first column sort issue

---

CHANGELOG.md
release-notes/opensearch-dashboards.release-notes-2.4.0.md

Update 2.4 release note to include:
https://github.com/opensearch-project/OpenSearch-Dashboards/pull/2828

[2.4] Update release note for fixing table vis bug

---

CHANGELOG.md
packages/osd-opensearch/src/cluster.js

OSD uses `tree-kill` [[npm](https://www.npmjs.com/package/tree-kill)], a library that terminates a process and all of its children, for stopping processes started using `Cluster`. This library behaves differently on different platforms. If the `pid` it is asked to terminate is not running:
* on darwin and linux, it silently returns without throwing and exception
* on win32 in produces an exception
As a result, calling cluster.stop() on an already terminated cluster will throw and exception on Windows but will silently continue on other operating systems.
Ref: #2811

Temporarily prevents `task-kill` exceptions on Windows when it is passed a `pid` for a process that is already dead

---

CHANGELOG.md
src/plugins/vis_builder/public/application/components/workspace.scss
src/plugins/vis_builder/public/application/components/workspace.tsx

Signed-off-by: raintygao <tygao@amazon.com>
The visbuilder animation in firefox does not work. 
This PR fixed the bug by modifying the dom structure and adding css attributes.  Since `osd-ui-shared` will provide `width: 100%` style by default with a higher priority, `!important` is added to ensure that it meets expectations.
Normal condition:
Error condition
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/2443

[VisBuilder] [BUG] fix empty workspace animation does not work in firefox

---

CHANGELOG.md
src/plugins/vis_builder/public/application/components/data_tab/dropbox.tsx
src/plugins/vis_builder/public/application/components/workspace.tsx

Signed-off-by: AbhishekReddy1127 <nallamsa@amazon.com>
Removed Hard Coded Strings and Used i18n to translate. As of now we cannot implement the Localization methods we had here due to the variables.
Partially resolves #958

[Vis Builder] Removed Hard Coded Strings and Used i18n to translate

---

package.json

Bump version on 2.x branch to 2.5.0
Part of post release activities as we just launched the 2.4.0 release.

Bump version on 2.x branch to 2.5.0

---

CHANGELOG.md
docs/charts/current_usage.md
src/plugins/charts/DEVELOPER_GUIDE.md
src/plugins/charts/README.md

* Update README with full capabilities
* Add `current_usage` doc to track current usage
The primary value in documenting usage is to identify UX gaps to close as part of https://github.com/opensearch-project/OpenSearch-Dashboards/issues/2667, https://github.com/opensearch-project/OpenSearch-Dashboards/issues/2507, and https://github.com/opensearch-project/OpenSearch-Dashboards/issues/2385
fixes #2585

[Doc] Document `charts` plugin

---

CHANGELOG.md
DEVELOPER_GUIDE.md
packages/osd-opensearch/src/cli_commands/snapshot.js
packages/osd-opensearch/src/cluster.js
packages/osd-opensearch/src/integration_tests/cluster.test.js
packages/osd-opensearch/src/paths.js

As a developer working on an external plugin (for example the AD dashboards plugin) that requires a corresponding OpenSearch plugin, but we can not use the `yarn opensearch snapshot` command to start up the cluster because it will install a min of OpenSearch.
With this change we can run`yarn opensearch snapshot --P {URL}/anomaly-detection.zip`and it will download the AD opensearch plugin on the cluster snapshot and run the snapshot of OpenSearch. So that OSD plugin developers can work completely in OpenSearch Dashboards without having to download opensearch and AD opensearch repo's. 
`yarn opensearch snapshot --version 2.2.0 --P https://repo1.maven.org/maven2/org/opensearch/plugin/opensearch-job-scheduler/2.2.0.0/opensearch-job …

Adding yarn opensearch args to setup opensearch plugin dependencies on cluster snapshot

---

CHANGELOG.md
src/dev/build/lib/scan_copy.ts

Fixes folder timestamps being updated before copying files into them.
When updating the timestamps were requested, `scanCopy` first set the times and then copied content into the destination folder. On certain platforms, copying files into a folder updates its "Last Access Time" and that overwrites the just set timestamps. This PR, makes sure the timestamps are set only after copying the content.

[Build] Update folder timestamps after copying files into them using `scanCopy`

---

CHANGELOG.md
src/dev/jest/junit_reporter.js

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/808129bcf077912c2ed4af5aea517c32ec1315a5/src/dev/jest/junit_reporter.js#L73-L74
These two lines, consider `ms = 0` as invalid. If `ms` is `0`, for example when a test takes no time and `0` is passed in, the report doesn't include `time`.

Fix incorrect validation of time values in JUnit Reporter

---

.github/workflows/build_and_test_workflow.yml
CHANGELOG.md

Tests are expected to fail until #2963, #2964, #2965, and a future automation of ChromeDriver detection are merged in.
This should be manually backported to 1.x.

Add Windows CI to the GitHub workflow

---

CHANGELOG.md
packages/osd-opensearch/src/integration_tests/cluster.test.js

Tests introduced in #2734 don't pass on Windows due to expecting the non-Windows CLI execution.

Make tests covering plugin installation on cluster snapshots work across platforms

---

CHANGELOG.md
package.json
packages/osd-optimizer/package.json
packages/osd-ui-shared-deps/package.json
yarn.lock

Signed-off-by: Zilong Xia <zilongx@amazon.com>
* Resolved [CVE-2022-37599] (https://github.com/advisories/GHSA-hhq3-ff78-jv3g) and [CVE-2022-37603](https://github.com/advisories/GHSA-3rfm-jhwj-7488) in `1.x` branch
* Manually backport CVE fix from this PR (https://github.com/opensearch-project/OpenSearch-Dashboards/pull/2892) to catch the v1.3.7 release train
* A similar PR before to bump `loader-utils` to `2.0.3` (https://github.com/opensearch-project/OpenSearch-Dashboards/pull/2689) for reference
Resolved https://github.com/opensearch-project/OpenSearch-Dashboards/issues/2560

[CVE] Bump loader-utils to 2.0.4 to fix CVE-2022-37599 and CVE-2022-37603

---

MAINTAINERS.md

* [OSD] 16 submitted PRs (https://github.com/opensearch-project/OpenSearch-Dashboards/pulls/manasvinibs)
* [OSD] 74 reviewed PRs (https://github.com/opensearch-project/OpenSearch-Dashboards/issues?q=reviewed-by%3Amanasvinibs)
* [OSD] 28 issues involved (https://github.com/opensearch-project/OpenSearch-Dashboards/issues?page=1&q=involves%3Amanasvinibs+is%3Aissue)
* Mana is assisting with extensions project which will be the next evolution of extending core functionality from OpenSearch Dashboards 
* Mana implemented https://github.com/opensearch-project/OpenSearch-Dashboards/pull/2734 which allows for a huge quality of life for local development for external plugin developers to utilize snapshots with a single CLI command compared to before when they would had to pull down OpenSearch …

Add @manasvinibs as maintainer

---

MAINTAINERS.md

Basic data points
[OSD] 16 submitted PRs (https://github.com/opensearch-project/OpenSearch-Dashboards/pulls/manasvinibs) [OSD] 74 reviewed PRs (https://github.com/opensearch-project/OpenSearch-Dashboards/issues?q=reviewed-by%3Amanasvinibs) [OSD] 28 issues involved (https://github.com/opensearch-project/OpenSearch-Dashboards/issues?page=1&q=involves%3Amanasvinibs+is%3Aissue)
Highlight
Mana is assisting with extensions project which will be the next evolution of extending core functionality from OpenSearch Dashboards Mana implemented https://github.com/opensearch-project/OpenSearch-Dashboards/pull/2734 which allows for a huge quality of life for local development for external plugin developers to utilize snapshots with a single CLI command compared to before when they would had to pull down …

[Backport 2.x] Add @manasvinibs as maintainer (#3006) along with resolving conflict with main branch

---

.github/workflows/build_and_test_workflow.yml
.gitignore
CHANGELOG.md
scripts/upgrade_chromedriver.js

Add automatic selection of the appropriate version of chrome driver to run functional tests

Automates chromedriver version selection for tests

---

CHANGELOG.md
packages/osd-eslint-plugin-eslint/rules/no_restricted_paths.js
packages/osd-eslint-plugin-eslint/rules/no_restricted_paths.test.js

`no-restricted-paths` compares source files and import statements, and their membership in restricted zones. However, when `allowSameFolder` is true, it failed to remove a trailing slash before validation which results in a false-positive.

Trim trailing slashes before checking no-restricted-path rule

---

release-notes/opensearch-dashboards.release-notes-1.3.7.md

[Chore] Add release notes for 1.3.7

---

CHANGELOG.md
package.json
yarn.lock

* The `minimatch` resolution was no longer necessary because an upstream library that depended on `minimatch@3.0.4` was removed in #2711.
N/A - related to https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1298

[Maintenance] Removes `mimimatch` manual resolution

---

CHANGELOG.md
package.json
packages/osd-opensearch/package.json
yarn.lock

Bumps simple-git from 3.4.0 to 3.15.0: https://advisories.aws.barahmand.com/advisory/GHSA-9p95-fxvg-qgq2
Followed these steps to test with this change:
```
yarn remove @opensearch-project/opensearch
yarn osd clean
Check yarn.lock to make sure it is removed. If not, run
yarn osd bootstrap 
Go to packages/osd-opensearch/package.json remove @opensearch-project/opensearch
yarn add --dev file:../opensearch-js
Finally, run bootstrap
yarn osd bootstrap
yarn start
```

Bumps simple-git from 3.4.0 to 3.15.0

---

.github/workflows/add_untriaged_label.yml

Credit to Peter Nied <petern@amazon.com> via https://github.com/opensearch-project/.github/pull/111
Automatically applies `untriaged` label to all new, reopened, and transferred issues. This helps us be able to trust that label, because it isn't dependent on issue templates.

[Infrastructure] Add `untriaged` label to issues workflow

---

CHANGELOG.md
src/plugins/console/public/application/contexts/services_context.tsx
src/plugins/console/public/application/hooks/use_send_current_request_to_opensearch/send_request_to_opensearch.test.ts
src/plugins/console/public/application/hooks/use_send_current_request_to_opensearch/send_request_to_opensearch.ts
src/plugins/console/public/application/hooks/use_send_current_request_to_opensearch/use_send_current_request_to_opensearch.ts
src/plugins/console/public/application/index.tsx
src/plugins/console/public/lib/opensearch/opensearch.ts
test/functional/apps/console/_console.ts

Signed-off-by: Yan Zeng <zengyan@amazon.com>
Update console plugin browser side to use `core.http` when calling OSD server APIs, get rid of use of jQuery.ajax.
#3044

Update console to use core.http instead of jQuery.ajax

---

src/plugins/console/public/application/contexts/services_context.tsx
src/plugins/console/public/application/hooks/use_send_current_request_to_opensearch/send_request_to_opensearch.test.ts
src/plugins/console/public/application/hooks/use_send_current_request_to_opensearch/send_request_to_opensearch.ts
src/plugins/console/public/application/hooks/use_send_current_request_to_opensearch/use_send_current_request_to_opensearch.ts
src/plugins/console/public/application/index.tsx
src/plugins/console/public/lib/opensearch/opensearch.ts
test/functional/apps/console/_console.ts

* Update console to use core.http instead of jQuery.ajax
Signed-off-by: Yan Zeng <zengyan@amazon.com>
(cherry picked from commit 5764d6ca0b7199e49e0006a6f38daea6c14ddfeb)

[backport-2.0] Update console to use core.http instead of jQuery.ajax (#3080)

---

.github/workflows/changelog_verifier.yml

Skip CHANGELOG verification workflow for feature branches
N/A - from discussion in https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3107#issuecomment-1362175146
Because feature branch PRs may not be standalone changes once merged to `main`, it's not worth the development friction to enforce them on every PR to the feature branch, only when the branch itself is merged or sync'd with `main`.

[Maintenance] Exempt feature branches from changelog verification

---

CHANGELOG.md
package.json
src/dev/ci_setup/setup_env.sh
tasks/config/run.js
yarn.lock

`@elastic/github-checks-reporter` is a task wrapper that provides expressive CI feedback via GitHub checks; I don't believe we use it in anyway and it has vulnerable deps.

Gets rid of `github-checks-reporter`

---

CHANGELOG.md
src/plugins/data/public/mocks.ts
src/plugins/vis_builder/public/application/utils/mocks.ts
src/plugins/vis_builder/public/application/utils/state_management/redux_persistence.test.tsx
src/plugins/vis_builder/public/application/utils/state_management/redux_persistence.ts
src/plugins/vis_builder/public/application/utils/state_management/store.ts

Implement redux persistence without using state container or state sync utils, and it works with both the URL and session storage.
#2898

[Vis Builder] Add redux store persistence

---

CHANGELOG.md
src/core/server/ui_settings/ui_settings_client.test.ts
src/core/server/ui_settings/ui_settings_config.ts

The theme was marked hidden in Advanced Settings within the UI but is still can be utilized and configurable. Users who have originally set the theme version from v7 (or unset) to v8 (beta) experienced rendering issues within OpenSearch Dashboards. With this changes, we are adding override to the `theme:version` config property to always default to `v7`.
[#3032](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/3032)

Adds config override to fix obsolete theme:version config value of v8 (beta) rendering issue

---

CHANGELOG.md
src/plugins/data_source/common/data_sources/types.ts
src/plugins/data_source/server/client/configure_client.ts
src/plugins/data_source/server/data_source_service.ts
src/plugins/data_source/server/legacy/configure_legacy_client.test.ts
src/plugins/data_source/server/legacy/configure_legacy_client.ts
src/plugins/data_source/server/lib/error.ts
src/plugins/data_source/server/routes/data_source_connection_validator.ts
src/plugins/data_source/server/routes/test_connection.ts
src/plugins/data_source/server/types.ts
src/plugins/data_source_management/public/components/utils.test.ts
src/plugins/data_source_management/public/components/utils.ts

This PR aims to resolve small follow-up items for the original PR, see #3060. These items are 
- Unskip UT (UT that previous mark as "skip" to unblock PR merge).
- Removing unnecessary specific error handling of `403`. It should be handled by the generic logic within data source module.
- Update data source `id` param from `required` to `optional`, when calling test connection api.
- improve error handing in test connection, to avoid invalid 500 error.(should return 400 instead)
#3060

[MD] Improve test connection

---

.github/workflows/build_and_test_workflow.yml
CHANGELOG.md
DEVELOPER_GUIDE.md

Yarn 1.x seems to have an issue with timing on windows and mac when running.
Source:
https://github.com/yarnpkg/yarn/issues/8242#issuecomment-776561223
Increase timeout just for windows.
Issue:
n/a
n/a

[CI] update yarn timeout for GitHub workflow on Windows

---

.github/workflows/build_and_test_workflow.yml
CHANGELOG.md
DEVELOPER_GUIDE.md

Yarn 1.x seems to have an issue with timing on windows and mac when running.
Source:
https://github.com/yarnpkg/yarn/issues/8242#issuecomment-776561223
Increase timeout for Windows only.
Issue:
n/a
(cherry picked from commit 038968d154c8bcc9d9c75e7abbf9b9435b9a0e42)

[Backport 2.x][Manual][CI] update yarn timeout for GitHub workflow on Windows (#3118)

---

.github/workflows/build_and_test_workflow.yml
.gitignore
CHANGELOG.md
scripts/upgrade_chromedriver.js

backport a26fb43cc3e4072a45e32c40ba59e37ae65cb83b from #2990

[Manual] [Backport 2.x] Automates chromedriver version selection for tests (#2990)

---

.github/workflows/build_and_test_workflow.yml
CHANGELOG.md

[CI] Improve yarn's performance in workflows by caching yarn's cache folder

---

CHANGELOG.md
docs/plugins/data_persistence.md
src/plugins/data/public/index.ts
src/plugins/data/public/public.api.md
src/plugins/data/public/query/state_sync/README.md
src/plugins/data/public/query/state_sync/connect_to_query_state.test.ts
src/plugins/data/public/query/state_sync/connect_to_query_state.ts
src/plugins/data/public/query/state_sync/index.ts
src/plugins/vis_builder/public/application/components/top_nav.tsx

App filter and query date will persist across refresh without using state container. Hook state managers from data plugin directly with OsdUrlStateStorage. Use a new flag '_q' to indicate filter and query data in the URL. Work with both app filter and global filter. App filter only persist within the app, and global filter will persist across the dashboards.
Signed-off-by: abbyhu2000 [abigailhu2000@gmail.com](mailto:abigailhu2000@gmail.com)
#3089

[Vis Builder] Add app filter and query persistence without using state container

---

.github/workflows/build_and_test_workflow.yml

Since the upload of images in the docs folder cause tests to fail, add steps to skip tests for changes inside the docs folder.
https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3176#issuecomment-1373979340

[Tests] Skip tests inside the docs folder

---

CHANGELOG.md
package.json
src/dev/ci_setup/setup_env.sh
tasks/config/run.js
yarn.lock

(cherry picked from commit 5116f1619b7deb76fbefd1c91b346ec2aef2b584)

[Backport 2.x][Manual] Gets rid of `github-checks-reporter` (#3126)

---

CHANGELOG.md
yarn.lock

Signed-off-by: Matt Provost <provomat@amazon.com>
Updates `json5` from 1.0.1 and 2.2.1 to 1.0.2 and 2.2.3 respectively. This fixes a CVE in older versions.
An interesting note, some vulnerability reporting services report that 1.0.2 does not have the vulnerability fixed, however [the fix was indeed backported to 1.0.2](https://github.com/json5/json5/releases/tag/v1.0.2). It seems that these services need to fix their audits.
#3148

Update json5 to 1.0.2 and 2.2.3

---

.github/workflows/build_and_test_workflow.yml
CHANGELOG.md

Co-authored-by: Qingyang(Abby) Hu <abigailhu2000@gmail.com>
(cherry picked from commit b57f3cc83bdd58588bf956a781e7ad45645fd8f5)

[Backport 2.x][Manual] [CI] Improve yarn's performance in workflows by caching yarn's cache folder (#3194)

---

CHANGELOG.md
yarn.lock

* Update json5 to 1.0.2 and 2.2.3
Signed-off-by: Matt Provost <provomat@amazon.com>
* Update changelog
Signed-off-by: Matt Provost <provomat@amazon.com>
Signed-off-by: Matt Provost <provomat@amazon.com>
(cherry picked from commit 68d503d110862d55baaf90a190ab17990e9e0f08)

[Backport 2.x] [Manual] Update json5 to 1.0.2 and 2.2.3 (#3201)

---

CHANGELOG.md
src/plugins/region_map/public/region_map_visualization.js

Remove updating join field to first field always.
Signed-off-by: Vijayan Balasubramanian <balasvij@amazon.com>
#2888

Fix bug that prevents selected join field to be used

---

CHANGELOG.md
package.json
packages/osd-babel-preset/common_preset.js
packages/osd-babel-preset/package.json
packages/osd-optimizer/src/worker/webpack.config.ts
src/plugins/vis_type_vega/public/data_model/vega_parser.test.js
src/plugins/vis_type_vega/public/default.spec.hjson
src/plugins/vis_type_vega/public/lib/vega.js
src/plugins/vis_type_vega/public/test_utils/default.spec.json
src/plugins/vis_type_vega/public/test_utils/vegalite_graph.json
src/plugins/vis_type_vega/public/vega_visualization.test.js
src/plugins/vis_type_vega/server/usage_collector/get_usage_collector.test.ts
yarn.lock

Manual backport of https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3076
- Add `vega-lite@^5.6.0 dependency`, aliased to `vega-lite-next` to maintain backwards compatibility for any plugins dependent on v4
- Update webpack config to build `vega-lite-next` from typescript source to target es5 (this prevents our old webpack from tripping on new ES syntax in `.js` files)
- Add babel plugin for logical assignment operators
- Selectively import only the vega-lite modules used (`import`, `version`)
- Update vega_parser tests
fixes #2717

[2.x] Add aliased vega-lite v5 dependency and bundle from source

---

CHANGELOG.md
package.json

Increment the version on the parent branch (2.x) to the next development iteration (2.6) after 2.5 branch cut.
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/3228

Increment version from 2.5.0 to 2.6.0

---

CHANGELOG.md
release-notes/opensearch-dashboards.release-notes-2.5.0.md

I've copied over the change log entries from changelog file in main which are tagged 2.5, as 2.x is not updated.
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/3230
Ref: https://github.com/opensearch-project/OpenSearch-Dashboards/issues/3174

Add v2.5.0 release notes

---

package.json

Signed-off-by: suzhou <suzhou@amazon.com>
IM plugin has an issue that the docLinks’ version is not correct. It gives 2.x in 2.5 build.
Need to add a test to check the branch property when we build any artifacts.

feat: modify the branch to 2.5

---

src/core/public/doc_links/doc_links_service.ts
src/plugins/vis_default_editor/public/components/controls/date_ranges.tsx

- Add new documentation link
- move from `noDocumentation` to `opensearch`
Fixes https://github.com/opensearch-project/OpenSearch-Dashboards/issues/2849

[Docs] Fix documentation link for date math

---

.github/workflows/pr_check_workflow.yml
.gitignore
CHANGELOG.md
scripts/upgrade_chromedriver.js

backport a26fb43cc3e4072a45e32c40ba59e37ae65cb83b from #2990 
Note that I manually ported the changes from [.github/workflows/build_and_test_workflow.yml](https://github.com/opensearch-project/OpenSearch-Dashboards/pull/2990/files#diff-c0983182839615df54f21254770a452eda733bc01ed0c7805ac1f4d48b1e47c9) to [.github/workflows/pr_check_workflow.yml](https://github.com/opensearch-project/OpenSearch-Dashboards/compare/1.x...joshuarrrr:OpenSearch-Dashboards:backport/backport-2990-to-1.x?expand=1#diff-8dbcf55675442f749d73e30a0314188743c4171c3622b787032768d06358f878)

[Manual] [Backport 1.x] Automates chromedriver version selection for tests (#2990)

---

CHANGELOG.md
scripts/upgrade_chromedriver.js

A bad copy-paste made the detection not escape the white-spaces in the path to Chrome.

[CI] Fix detection of Chrome's version on Darwin

---

packages/osd-eslint-plugin-eslint/rules/__tests__/no_restricted_paths.js

Update tests in backport PR 3020 with correct paths

Update tests in backport PR 3020 with correct paths

---

CHANGELOG.md
package.json
packages/osd-opensearch/package.json
yarn.lock

Backport PR: https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3036
https://advisories.aws.barahmand.com/advisory/GHSA-9p95-fxvg-qgq2

[Manual Backport 1.x]Bumps simple-git from 3.4.0 to 3.15.0

---

CHANGELOG.md
package.json
packages/osd-opensearch/package.json
yarn.lock

Backport PR: https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3036
https://advisories.aws.barahmand.com/advisory/GHSA-9p95-fxvg-qgq2

[Manual Backport 1.3]Bumps simple-git from 3.4.0 to 3.15.0

---

CHANGELOG.md
yarn.lock

Bumps json5 version from 1.0.1 and 2.2.1 to 1.0.2 and 2.2.3
https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3201 
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/3148

[Manual Backport 1.x][CVE-2022-46175] Update json5 to 1.0.2 and 2.2.3

---

CHANGELOG.md
yarn.lock

Bumps json5 version from 1.0.1 and 2.2.1 to 1.0.2 and 2.2.3
https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3201 
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/3148

[Manual Backport 1.3][CVE-2022-46175] Update json5 to 1.0.2 and 2.2.3

---

CHANGELOG.md
package.json
packages/osd-opensearch/package.json
yarn.lock

Issue Resolved
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/3329

[CVE-2022-25860] Bumps simple-git from 3.15.1 to 3.16.0

---

CHANGELOG.md
package.json
packages/osd-opensearch/package.json
yarn.lock

Backport PR
https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3345
Issue Resolved
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/3329

[Manual Backport 2.x][CVE-2022-25860] Bumps simple-git from 3.15.1 to 3.16.0

---

CHANGELOG.md
package.json
packages/osd-opensearch/package.json
yarn.lock

Backport PR
https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3345
Issue Resolved
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/3329

[Manual Backport 1.x][CVE-2022-25860] Bumps simple-git from 3.15.1 to 3.16.0

---

CHANGELOG.md
package.json
packages/osd-opensearch/package.json
yarn.lock

Backport PR
https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3345
Issue Resolved
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/3329

[Manual Backport 1.3][CVE-2022-25860] Bumps simple-git from 3.15.1 to 3.16.0

---

MAINTAINERS.md

Coming from opensearch-project/.github#121, updated MAINTAINERS.md to match opensearch-project recommended format. Also modify this file to include all the missing updates.
Backport PR:
https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3338
- [] Update [CHANGELOG.md](./../CHANGELOG.md)

[1.3] Update MAINTAINERS.md

---

release-notes/opensearch-dashboards.release-notes-1.3.8.md

Signed-off-by: Aozixuan Priscilla Guan <aoguan@amazon.com>

Add 1.3.8 release notes

---

src/plugins/vis_augmenter/common/types.test.ts
src/plugins/vis_augmenter/common/types.ts

This PR updates the data models for the `VisLayer`s such that we are passing sufficient information to the 'View Events' flyout to render it correctly. Details on the flyout & its mocks are in the related issue #3373 
Note there will still be some added field(s) related to error handling - details on that as part of issue #3267 
Closes #3373

Update `VisLayer` data models
