opensearch-project/OpenSearch-Dashboards

src/plugins/saved_objects/README.md
src/plugins/saved_objects_management/opensearch_dashboards.json
src/plugins/saved_objects_management/public/lib/in_app_url.test.ts
src/plugins/saved_objects_management/public/lib/in_app_url.ts
src/plugins/saved_objects_management/public/management_section/object_view/saved_object_view.tsx
src/plugins/saved_objects_management/public/management_section/objects_table/components/__snapshots__/relationships.test.tsx.snap
src/plugins/saved_objects_management/public/management_section/objects_table/components/relationships.test.tsx
src/plugins/saved_objects_management/public/plugin.ts
src/plugins/saved_objects_management/public/register_services.ts
src/plugins/vis_augmenter/public/index.ts
src/plugins/vis_augmenter/public/plugin.ts
src/plugins/vis_augmenter/public/saved_augment_vis/_saved_augment_vis.ts
src/plugins/vis_augmenter/public/saved_augment_vis/index.ts
src/plugins/vis_augmenter/public/saved_augment_vis/saved_augment_vis.test.ts
src/plugins/vis_augmenter/public/saved_augment_vis/saved_augment_vis.ts
src/plugins/vis_augmenter/public/saved_augment_vis/saved_augment_vis_references.test.ts
src/plugins/vis_augmenter/public/saved_augment_vis/saved_augment_vis_references.ts
src/plugins/vis_augmenter/public/saved_augment_vis/utils/helpers.ts
src/plugins/vis_augmenter/public/saved_augment_vis/utils/index.ts
src/plugins/vis_augmenter/public/saved_augment_vis/utils/test_helpers.ts
src/plugins/vis_augmenter/public/services.ts
src/plugins/vis_augmenter/public/types.ts
src/plugins/vis_augmenter/server/capabilities_provider.ts
src/plugins/vis_augmenter/server/plugin.ts
src/plugins/vis_augmenter/server/saved_objects/augment_vis.ts
src/plugins/vis_augmenter/server/saved_objects/index.ts
src/plugins/visualize/public/application/types.ts
src/plugins/visualize/public/plugin.ts

This PR adds a new `augment-vis` saved object type. Details on the design can be found in the [related issue](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/2893)
Specifically, this PR makes the following changes:
Client-side:
- creates & defines an augment vis saved object class
- creates helper fns to convert from client-side definition (with no references) to server-side definition (with references) & vice-versa
- introduce a saved object loader for the new saved object type. This loader provides a clean way to interact with all saved objects of this type, and can be consumed in dependent plugins for performing CRUD operations on saved objects of this type
- creates and sets the new loader in the `vis_augmenter` plugin's `start` lifecycle step
Server-side:
- creates …

Add a new `augment-vis` saved object type

---

.eslintrc.js
CHANGELOG.md
src/setup_node_env/node_version_validator.test.js
src/setup_node_env/root/force.test.js
src/setup_node_env/root/is_root.test.js

Previously, test files under `src/setup_node_env` were held to the same low standard as the other `*.js` files that need to support ancient versions of Node.js because they are run before a version check has occurred. This change, allows those tests to now include modern concepts, since they cannot run without complete bootstrapping anyway.

Prevent primitive linting limitations from being applied to unit tests found under `src/setup_node_env`

---

CHANGELOG.md
yarn.lock

Bump hapi/statehood to 7.0.4 to solve security concerns.
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/3406

[Security]Bump hapi/statehood to 7.0.4

---

CHANGELOG.md
yarn.lock

[CVE-2022-25881] Resolve `http-cache-semantics` to `4.1.1`

---

CHANGELOG.md
yarn.lock

[CVE-2023-25166] Bumps formula to 3.0.1
#3404

[CVE-2023-25166] Bump formula to 3.0.1

---

CHANGELOG.md
src/plugins/region_map/common/constants/shared.ts
src/plugins/region_map/common/index.ts
src/plugins/region_map/public/choropleth_layer.js
src/plugins/region_map/public/components/map_choice_options.tsx
src/plugins/region_map/public/region_map_visualization.js
src/plugins/region_map/public/services.ts
src/plugins/region_map/server/routes/opensearch.ts
src/plugins/region_map/server/ui_settings.ts

With Custom Import Vector map, Region Maps loads only first 10 GeoJSON Features from previously imported Custom GeoJSON file( default size for OpenSearch ) . Hence, only top 10 Feature is available for joining index pattern in Region Maps and users might mistake, that only 10 features are available for join.
This solution will introduce new parameter in ui settings to configure size. 
Signed-off-by: Vijayan Balasubramanian <balasvij@amazon.com>
https://github.com/opensearch-project/dashboards-maps/issues/220

Add ui setting to configure custom vector map's size parameter

---

CHANGELOG.md
src/plugins/data/server/plugin.ts
src/plugins/data/server/search/collectors/usage.ts
src/plugins/data/server/search/search_service.test.ts
src/plugins/data/server/search/search_service.ts

Signed-off-by: Tao Liu <liutaoaz@amazon.com>
The search telemetry was disabled by default, there is a issue when search telemetry read configuration and creates an Observable object that won't be GC-ed.

[search telemetry] Fixes search telemetry's observable object that won't be GC-ed

---

CHANGELOG.md
package.json
yarn.lock

Signed-off-by: Zilong Xia <zilongx@amazon.com>
* Bump package `flat` from `4.1.1` to `5.0.2` to resolve [CVE-2020-36632](https://github.com/advisories/GHSA-2j2x-2gpw-g8fm) in branch `2.x` (release candidate for `OSD 2.6.0`)
* `flat` is introduced into OSD by `mocha@^7.2.0`
* `CVE-2020-36632` is fixed from `mocha@8.2.0` (https://github.com/mochajs/mocha/blob/v8.2.0/package-lock.json)
* Yet since `mocha 8.0.0` brings in a bunch of breaking changes (https://github.com/mochajs/mocha/blob/master/CHANGELOG.md), leveraging `resolutions` here instead of the major version bumping
* `mocha` has been bumped up to `10.1.0` in `main` branch btw (https://github.com/opensearch-project/OpenSearch-Dashboards/pull/2711), which would be released as part of `OSD 3.0.0`
* No breaking changes identified for …

[CVE-2020-36632] Bumps flat from 4.1.1 to 5.0.2

---

CHANGELOG.md
package.json
src/dev/ci_setup/setup_env.sh
tasks/config/run.js
yarn.lock

(cherry picked from commit 5116f1619b7deb76fbefd1c91b346ec2aef2b584)
Coming from https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3126

[Manual backport 1.x] Gets rid of `github-checks-reporter` (#3126)

---

CHANGELOG.md
package.json
yarn.lock

Signed-off-by: Jovan Cvetkovic <jovanca.cvetkovic@gmail.com>
Upgrades the vega-tooltip to version 0.30.0
Resolves #3358

Upgrade vega-tooltip to 0.30.0 to support custom tooltips #3358

---

CHANGELOG.md
src/setup_node_env/__snapshots__/node_version_validator.test.js.snap
src/setup_node_env/node_version_validator.js
src/setup_node_env/node_version_validator.test.js

With this change, the `engines.node` of `package.json` need not be a fixed version; it can be a range using a subset of formats defined by `semver`.
A very limited subset of what [semver](https://github.com/npm/node-semver/blob/cb1ca1d5480a6c07c12ac31ba5f2071ed530c4ed/README.md#ranges) supports has been added; only a single comparator, composed of an operator and a version, is supported.
The supported operators are
*   `>`    Greater than
*   `>=`   Greater than or equal to
*   `=`    Equal
*   `~`    Tilde ranges: Allows patch changes if a minor version is specified but if only a major version is specified, it allows minor changes.
*   `^`    Caret ranges: Allows patch and minor updates when major is non-zero (and we will never have that).
If no …

Allow relaxing the Node.js runtime version requirement

---

CHANGELOG.md
yarn.lock

Manual backport https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3409 to `2.5`

[Manual backport 2.5][CVE-2022-25881] Resolve http-cache-semantics to 4.1.1 (#3409)

---

CHANGELOG.md
yarn.lock

Manual backport #3409  to `2.x`

[Manual backport 2.x][CVE-2022-25881] Resolve http-cache-semantics to 4.1.1 (#3409)

---

CHANGELOG.md
yarn.lock

Backport https://github.com/opensearch-project/OpenSearch-Dashboards/commit/0cab6fe336768aeb3e6416f42205244f41633541 from https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3416

[Manual Backport 2.x] [CVE-2023-25166] Bump formula to 3.0.1 (#3416)

---

CHANGELOG.md
package.json
packages/osd-optimizer/package.json
packages/osd-ui-framework/package.json
yarn.lock

Bump node-sass to 7.0.3 and sass-loader to 10.4.1
More analysis:
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1842#issuecomment-1435227797
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1067 
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1842

[CVE-2022-25758][CVE-2020-24025] Bump node-sass to 7.0.3 and sass-loader to 10.4.1 in 2.x

---

CHANGELOG.md
package.json
yarn.lock

https://github.com/opensearch-project/OpenSearch-Dashboards/issues/3449

[CVE-2022-2499][backport 1.x]  Resolve qs from 6.5.3 to 6.11.0

---

CHANGELOG.md
src/dev/build/lib/config.test.ts
src/dev/build/lib/config.ts
src/dev/build/tasks/create_archives_sources_task.ts
src/dev/build/tasks/nodejs/download_node_builds_task.ts
src/dev/build/tasks/nodejs/extract_node_builds_task.test.ts
src/dev/build/tasks/nodejs/extract_node_builds_task.ts
src/dev/build/tasks/nodejs/node_download_info.ts
src/dev/build/tasks/nodejs/verify_existing_node_builds_task.test.ts
src/dev/build/tasks/nodejs/verify_existing_node_builds_task.ts
src/dev/build/tasks/notice_file_task.ts
src/dev/build/tasks/verify_env_task.ts

* While building distributables, Node.js runtime is downloaded to be placed in the archivea. This logicwas modified to honor a range for `engines.node` by fetching the latest release of Node.js that satisfied the range.
* Some tests covering the build, read a version from `.node-version` to compare with the results of actual function runs; these were changed to either use mocked values or honor the range and use the latest Node.js version.
* Some variable and functions referred to `engines.node` as a version; they were corrected to call it a range.

Make build scripts find and use the latest version of Node.js that satisfies `engines.node`

---

package.json

In 2.5 we use https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3274 to manually update `pkg.branch`.
We have raised https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3483 to do it automatically but shall not be able to catch up with 2.6 release, so do it manually.
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/3490

Feature: bump branch to 2.6

---

CHANGELOG.md
src/plugins/vis_type_timeseries/public/application/components/aggs/serial_diff.js

Doc link was invalid and causing an undefined error. This prevented the UI from mounting properly.
* https://github.com/opensearch-project/OpenSearch-Dashboards/issues/3498
* https://github.com/opensearch-project/OpenSearch-Dashboards/issues/3327

[BUG][TSVB] Fix serial diff agg link

---

CHANGELOG.md
package.json
yarn.lock

Backport PR:
https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3445

[Manual backport 1.x][CVE-2023-25653] Bump node-jose to 2.2.0

---

CHANGELOG.md
yarn.lock

Ran npx browserslist@latest --update-db to update caniuse package so the integration tests will pass.
Will be fixed in:
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/2329
n/a
But causing test failures here: 
https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3537

Update caniuse to fix failed integration tests

---

CHANGELOG.md
DEVELOPER_GUIDE.md
packages/osd-opensearch/src/artifact.js
packages/osd-opensearch/src/artifact.test.js

Enable the downloading of Darwin for running the command `yarn opensearch snapshot`.
Darwin is not officially supported but snapshots are being built here:
https://build.ci.opensearch.org/job/distribution-build-opensearch/
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/2944

[Dev] enable `opensearch snapshot` for Darwin

---

CHANGELOG.md
yarn.lock

Backport 33c7c3d9ddeb76b2d65958ee61f19c1b28b929fb from https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3538

[Backport][2.x] Update caniuse to fix failed integration tests (#3538)

---

CHANGELOG.md
src/dev/build/tasks/patch_native_modules_task.ts

* Follow-up from #3018 based on [Miki's suggestion](https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3018#discussion_r1085708386).
N/A

Simplifies `re2` upgrade instructions

---

CHANGELOG.md
package.json
yarn.lock

manual backport of https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3520
Resolves https://github.com/opensearch-project/OpenSearch-Dashboards/issues/3167

[Manual Backport 1.x] [CVE-2020-36632] Bump flat from 4.1.1 to 5.0.2

---

CHANGELOG.md
package.json
yarn.lock

Backport 1a8c68f110e8eb3c24c52651ec3f2a371c2d4a66 from #3542.

[Manual Backport 1.3] [CVE-2022-24999] Bump express from 4.17.1 to 4.18.2 (#3542)

---

CHANGELOG.md
release-notes/opensearch-dashboards.release-notes-1.3.9.md

- add 1.3.9 release notes
- also update/sync changelog to reflect release notes from 1.3.6 until now, including dates and links to releases
Ideally, we would only move the CHANGELOG items from Unreleased to `1.3.9` section after the release, but for timeliness, I went ahead and did it so I could easily generate the release notes at the same time.
Note that `1.x` and `1.3` branches are still out of sync, so there should be even more changes listed in the unreleased section: https://github.com/opensearch-project/OpenSearch-Dashboards/compare/1.3...1.x
Fixing all those missing `1.3` backports is out of scope for this PR.

[1.x] Chore: Add release notes for 1.3.9

---

CHANGELOG.md
DEVELOPER_GUIDE.md
packages/osd-opensearch/src/artifact.js
packages/osd-opensearch/src/artifact.test.js

Backport 81a5fadca1b5417c204b94c94a7b6e3196be95dd from #3537

[Manual Backport][2.6] [Dev] enable `opensearch snapshot` for Darwin (#3537)

---

CHANGELOG.md
src/plugins/vis_builder/public/application/components/right_nav.tsx
src/plugins/vis_builder/public/application/utils/mocks.ts
src/plugins/vis_builder/public/application/utils/state_management/shared_actions.ts
src/plugins/vis_builder/public/application/utils/state_management/visualization_slice.ts
src/plugins/vis_builder/public/application/utils/use/use_persisted_agg_params.test.tsx
src/plugins/vis_builder/public/application/utils/use/use_persisted_agg_params.ts

This PR implements the aggregation persistence feature in Vis Builder when switching vis type. 
Detailed research doc can be found here: #2900
The proposal, mapping rules and examples can be found here: #3482 
#3482

[Vis Builder] Add metric to metric, bucket to bucket aggregation persistence

---

release-notes/opensearch-dashboards.release-notes-1.3.9.md

Add 1.3.9 release notes. Forwardport of https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3576 (generated from `1.x` CHANGELOG)

[Forwardport main] Add 1.3.9 release notes

---

.github/workflows/build_and_test_workflow.yml
CHANGELOG.md

Backport of 1e127b0a52925ee51d185798f00362d8eb59d2ce from #3514

[Manual Backport 2.x][CI] Reduce redundancy by using matrix strategy on workflows (#3514)

---

CHANGELOG.md
examples/developer_examples/public/app.tsx
examples/expressions_example/public/components/explorer_tab.tsx
examples/state_containers_examples/public/plugin.ts
examples/ui_actions_explorer/public/app.tsx
examples/ui_actions_explorer/public/basic_tab.tsx
examples/ui_actions_explorer/public/explorer_tab.tsx
examples/ui_actions_explorer/public/plugin.tsx
examples/ui_actions_explorer/public/trigger_context_example.tsx
examples/ui_actions_explorer/public/types.ts
src/plugins/ui_actions/README.md
src/plugins/ui_actions/public/service/ui_actions_service.ts

UI Actions is a sparsely documented plugin like many of our other plugins. This PR aims to improve the docs for this plugin so that it is more accessible to plugin developers.
- Adds UI Actions explorer
- Adds docs for UI Actions
- Cleaning up Developer Examples view
- Done as a part of #2868 but does not close that issue.

[Doc] UI actions explorer

---

src/plugins/vis_augmenter/public/index.ts
src/plugins/vis_augmenter/public/types.ts

Add error types to VisLayers. This way, errors can be processed and handled in different ways, as described in #3580 .
Closes #3267

Add error types to VisLayers

---

CHANGELOG.md
src/core/public/doc_links/doc_links_service.test.ts
src/core/public/doc_links/doc_links_service.ts
src/dev/build/tasks/create_package_json_task.ts

This is a TODO after [PR](https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3274).
The `CoreStart.docLinks.docVersion` is using `pkg.branch`. In 2.5 we changed it manually.
In this PR I want to add a mechanism into CI flow to prevent human error(If build team forget to change the value, which is `2.x` now in current build flow, it will break down all the new doc links inside IM plugin because the link will become like `https://opensearch.org/docs/2.x/api-reference/index-apis/create-index/`.).
#3490 https://github.com/opensearch-project/OpenSearch-Dashboards/issues/3490

Add downgrade logic for branch in DocLinkService

---

CHANGELOG.md
packages/osd-babel-preset/package.json
packages/osd-ui-shared-deps/package.json
yarn.lock

This will remove the political message in the package.
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/3677

Bump styled-components from 5.3.5 to 5.3.9

---

CHANGELOG.md
src/plugins/data/common/opensearch_query/filters/geo_shape_filter.test.ts
src/plugins/data/common/opensearch_query/filters/geo_shape_filter.ts
src/plugins/data/common/opensearch_query/filters/get_filter_field.ts
src/plugins/data/common/opensearch_query/filters/index.ts
src/plugins/data/common/opensearch_query/filters/types.ts

Add new filter query, 'geo_shape' to search geospatial field types . This is required as part of Maps plugin which
uses geo_shape filter query to search documents.
https://github.com/opensearch-project/dashboards-maps/issues/213

[Geospatial] Add new geo shape filter field to support geospatial search query

---

CHANGELOG.md
src/plugins/vis_type_vega/public/vega_view/vega_base_view.js

Vega 'opensearchDashboardsAddFilter' allows to add OpenSearch Query DSL and index. The implementation buildQueryFilter takes in third parameter to set a custom label in 'Add Filter'. At the moment, opensearchDashboardsAddFilter can only take query and index parameters. 
This PR adds in the third 'alias' parameter to set the custom label from Vega
`buildQueryFilter = (query: QueryStringFilter['query'], index: string, alias: string)`
Below image is self explanatory. The first filter in the image is without custom label (ugly, in my opinion), and the second filter is with custom label set in Vega.

[Vega] Add Filter custom label for opensearchDashboardsAddFilter

---

src/plugins/vis_type_vega/public/data_model/vega_parser.test.js
src/plugins/vis_type_vega/public/data_model/vega_parser.ts
src/plugins/vis_type_vega/public/vega_view/vega_base_view.js

rather than relying on vega.scheme. Also update vega.scheme name
https://user-images.githubusercontent.com/1679762/228105161-4688eba4-cb85-4fea-9149-18e1df25cde9.mov
(note that the color palette scale is still applied correctly)
https://user-images.githubusercontent.com/1679762/228105170-39bdadb5-1d1c-4dcd-b520-9b37fada789b.mov
The only usage of the `elastic` custom scheme previously was to set the default value for `config.range.category`, and that behavior is restored by this PR. However, it was previously possible to explicitly set `scheme: "elastic"` within a spec - that's no longer possible. I think it's highly unlikely that there's a vega property that accepts a `scheme` property that doesn't also use the default `config.range.category`, but it may be possible. I'm also unsure if …

fix(vis_type_vega): Use default categorical color palette directly

---

CHANGELOG.md
package.json
yarn.lock

`nth-check` is @v1.0.2 and we needs @v2.0.1 to fix the CVE.
```
ubuntu@ip-172-31-55-237:~/work/OpenSearch-Dashboards$ yarn why nth-check
[1/4] Why do we have the module "nth-check"...?
warning Resolution field "shelljs@0.8.5" is incompatible with requested version "shelljs@^0.6.0"
=> Found "nth-check@1.0.2"
- "_project_#cheerio#css-select" depends on it
- Hoisted from "_project_#cheerio#css-select#nth-check"
info Disk size without dependencies: "24KB"
info Disk size with unique dependencies: "36KB"
info Disk size with transitive …
```

[CVE-2021-3803][1.x] Bump nth-check from 1.0.2 to 2.0.1

---

CHANGELOG.md
package.json
packages/osd-optimizer/package.json
packages/osd-ui-framework/package.json
yarn.lock

https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1094
This CVE requires to bump `postcss` to be `<7.0.36||>=8.0.0 <8.2.13`. `The package postcss versions before 7.0.36 or between 8.0.0 and 8.2.13 are vulnerable to Regular Expression Denial of Service (ReDoS) via getAnnotationURL() and loadAnnotation() in lib/previous-map.js. The vulnerable regexes are caused mainly by the sub-pattern /*\s* sourceMappingURL=(.*).` In 1.x we are using `postcss` under two versions, 8.2.10 and 7.0.36. 
```
ubuntu@ip-172-31-55-237:~/work/OpenSearch-Dashboards$ yarn why postcss
[1/4] Why do we have the module "postcss"...?
warning …
```

[CVE-2021-23382][1.x] Bump postcss from 8.2.10 to 8.2.13

---

CHANGELOG.md
src/plugins/dashboard/public/application/application.ts
src/plugins/dashboard/public/application/legacy_app.js
src/plugins/dashboard/public/application/listing/__snapshots__/create_button.test.tsx.snap
src/plugins/dashboard/public/application/listing/__snapshots__/dashboard_listing.test.js.snap
src/plugins/dashboard/public/application/listing/create_button.test.tsx
src/plugins/dashboard/public/application/listing/create_button.tsx
src/plugins/dashboard/public/application/listing/dashboard_listing.js
src/plugins/dashboard/public/application/listing/dashboard_listing.test.js
src/plugins/dashboard/public/application/listing/dashboard_listing_ng_wrapper.html
src/plugins/dashboard/public/plugin.tsx
src/plugins/dashboard/public/types.ts
src/plugins/opensearch_dashboards_react/public/table_list_view/README.md
src/plugins/opensearch_dashboards_react/public/table_list_view/table_list_view.tsx
test/functional/apps/dashboard/dashboard_clone.js
test/functional/services/common/browser.ts

* Configure types for registration of Dashboard List "Providers"
These changes enable the interactions demonstrated in this animation:
Audio starts at 0:05.    Unmute to listen.
https://user-images.githubusercontent.com/11318/220466340-f069ffa8-bc30-4094-8922-20848a982390.mov
References : [observability#1308](https://github.com/opensearch-project/observability/pull/1308)
[[FEATURE] Dashboards List Extensibility & Integrate Observability Apps/Panels/EventAnalytics](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1866)
- includes alternate solutions, example animation, and further explanation of this solution.
**Pros :**
* Works in test suite w/o change.
**Cons :**
* Causes browser-reload in production due to operation of React Router / SPA and navigating "between" SPA's …

Dashboard Lists Integration

---

src/plugins/vis_augmenter/public/test_constants.ts
src/plugins/vis_augmenter/public/vega/helpers.test.ts
src/plugins/vis_augmenter/public/vega/helpers.ts
src/plugins/vis_type_vega/public/data_model/types.ts
src/plugins/vis_type_vega/public/data_model/vega_parser.test.js
src/plugins/vis_type_vega/public/data_model/vega_parser.ts

The change to using a `Map` for persisting visible `VisLayer`s in the vega spec config had a bug where during the string serialization/deserialization (necessary for passing through the expression functions), the `Map` obj could not be properly stringified which was leading to an empty `Map` when parsing in the `VegaParser`. This was causing no `VisLayer`s to be able to render.
This fixes that by converting the `Map` => array when serializing, and converting back to a `Map` when deserializing in the parser. 
Note another option could have been using a basic JS obj `{}` for persisting this, but that would limit us in not being able to use the `VisLayerTypes` enum as keys, and would need other conversion as well.
Also hardens a helper method by handling a case where `events` is undefined or …

[Feature Anywhere] Fix visibleVisLayers ser/deser

---

.gitignore

added  **opensearch-dashboards-docker-dev/**
fixes #3667
This is **convenience** change for our developers.
For those who are using docker, they need to delete **opensearch-dashboards-docker-dev** file everytime they commit

[FIX]gitignore

---

CHANGELOG.md
src/plugins/data_source_management/public/components/create_data_source_wizard/components/create_form/create_data_source_form.test.tsx
src/plugins/data_source_management/public/components/create_data_source_wizard/components/create_form/create_data_source_form.tsx
src/plugins/data_source_management/public/components/edit_data_source/components/edit_form/edit_data_source_form.test.tsx
src/plugins/data_source_management/public/components/edit_data_source/components/edit_form/edit_data_source_form.tsx
src/plugins/data_source_management/public/types.ts

[Multiple DataSource]Refactor authentication type selection in create and edit data source forms to use EuiSelect component
Based on https://github.com/opensearch-project/OpenSearch-Dashboards/issues/2110#issuecomment-1426591168, I made the UI changes to multiple datasource creation page
Current UI:
Updated UI:
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/3551
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/2110#issuecomment-1426591168

[Multiple DataSource]Refactor authentication type selection in create and edit data source forms

---

CHANGELOG.md
src/core/public/application/types.ts
src/plugins/console/opensearch_dashboards.json
src/plugins/console/public/application/containers/editor/editor.tsx
src/plugins/console/public/application/containers/editor/legacy/console_editor/editor.tsx
src/plugins/console/public/application/containers/main/main.tsx
src/plugins/console/public/application/containers/settings.tsx
src/plugins/console/public/application/hooks/use_send_current_request_to_opensearch/send_request_to_opensearch.ts
src/plugins/console/public/application/hooks/use_send_current_request_to_opensearch/use_send_current_request_to_opensearch.ts
src/plugins/console/public/application/index.tsx
src/plugins/console/public/application/stores/request.ts
src/plugins/console/public/lib/mappings/mappings.js
src/plugins/console/public/lib/opensearch/opensearch.ts
src/plugins/console/public/plugin.ts
src/plugins/console/server/routes/api/console/proxy/create_handler.ts
src/plugins/console/server/routes/api/console/proxy/tests/body.test.ts
src/plugins/console/server/routes/api/console/proxy/tests/mocks.ts
src/plugins/console/server/routes/api/console/proxy/tests/query_string.test.ts
src/plugins/console/server/routes/api/console/proxy/utils.ts
src/plugins/console/server/routes/api/console/proxy/validation_config.ts
src/plugins/data_source_management/opensearch_dashboards.json
src/plugins/dev_tools/opensearch_dashboards.json
src/plugins/dev_tools/public/application.tsx
src/plugins/dev_tools/public/index.scss
src/plugins/dev_tools/public/plugin.ts

[Multiple DataSource] Integrate multiple datasource with dev tool console
After #3775 fixes autocomplete issue, I updated this PR to adopt the change, autocomplete also works for datasources now
Video
https://user-images.githubusercontent.com/32652829/229190663-036b6e68-8a04-4d3c-9dbd-e0b0cf45280e.mov
#2699
part of #3577

[Multiple DataSource] Integrate multiple datasource with dev tool console

---

CHANGELOG.md
src/plugins/vis_type_table/public/components/table_vis_app.scss

Makes table component adjust its height on initial load. Before that it had fixed height on first load, resulting in table being rendered only in a small scrollable portion of the screen.
Fixes https://github.com/opensearch-project/OpenSearch-Dashboards/issues/3737

Fix: Data Table rendering only in a small scrollable portion of the screen

---

CHANGELOG.md
src/core/public/doc_links/doc_links_service.ts
src/plugins/timeline/public/components/timeline_deprecation.tsx
src/plugins/visualize/public/application/utils/utils.ts

[Added corresponding links from the documentation for non-working links
Edited DocLinksStart interface properties
Edited the usage of interface in other files correspondigly
]
fixes #3208

[Doc Links Service] Clean up noDocumentation links

---

CHANGELOG.md
src/plugins/discover/public/application/angular/doc_table/create_doc_table_react.tsx
src/plugins/discover/public/application/doc_views/doc_views_helpers.tsx

URL: http://roubenmeschian.com/rubo/?p=51 is not reachable by the link checker, which causes the link checker failure. We observed that this url is commented out in the following two files. Clean up is needed to fix the link checker failure.
src/plugins/discover/public/application/angular/doc_table/create_doc_table_react.tsx
src/plugins/discover/public/application/doc_views/doc_views_helpers.tsx
[Issue #3846](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/3846)
- [x ] Commits are signed per the DCO using --signoff

Remove unused url

---

CHANGELOG.md
src/plugins/vis_type_table/public/utils/use_pagination.ts

After the fix the table component no longer renders unused space for extra rows. Before the fix when the option max rows per page was larger than actual number of results, the table component was rendered with height that could fit max number of rows per page and not the actual number. Screenshot from the issue https://github.com/opensearch-project/OpenSearch-Dashboards/issues/3756:
The number of results in this screen is 50, while the max number of rows per page is 100. As the result, half of the table component is empty and the update button is pushed far below. I have checked the component from the docs in the sandbox and this is expected behavior. 
Therefore, to prevent this bug I assumed that we need to ensure that max number of rows is never larger than number of rows in resulting …

Fix: Update button position when number of rows per page is large

---

src/plugins/dev_tools/public/application.tsx
src/plugins/dev_tools/public/index.scss

[Console][Multiple Datasource]Fine tuned dev tool datasource selector UI
Coming from @KrooshalUX 's feedback https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3754#issuecomment-1499715892. Tuned the UI to make it look nicer, while not breaking the pattern of other dev tool registered plugins

[Console][Multiple Datasource]Fine tuned dev tool datasource selector UI

---

CHANGELOG.md
src/cli_keystore/get_keystore.test.js

resolved get_keystore unit test

---

CHANGELOG.md
TESTING.md
dev-tools/install-docker-dev.sh
docs/docker-dev/Dockerfile.selenium
docs/docker-dev/docker-compose.selenium.yml
docs/docker-dev/docker-dev-setup-manual.md
docs/docker-dev/start-vnc.sh

This PR introduces new Docker files to enable debugging of Selenium functional tests for Docker users. It configures a VNC viewer for real-time browser interaction monitoring during test execution.
Additionally, a new section is added to the documentation detailing the process of running and debugging Selenium functional tests using Docker and a VNC viewer.
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/3700

Add docker files and instructions for debugging Selenium functional tests

---

CHANGELOG.md
src/plugins/vis_type_table/public/components/table_vis_app.scss
src/plugins/vis_type_table/public/components/table_vis_app.test.tsx
src/plugins/vis_type_table/public/components/table_vis_app.tsx
src/plugins/vis_type_table/public/components/table_vis_cell.test.tsx
src/plugins/vis_type_table/public/components/table_vis_cell.tsx
src/plugins/vis_type_table/public/components/table_vis_component.test.tsx
src/plugins/vis_type_table/public/components/table_vis_component.tsx
src/plugins/vis_type_table/public/components/table_vis_component_group.test.tsx
src/plugins/vis_type_table/public/components/table_vis_component_group.tsx
src/plugins/vis_type_table/public/components/table_vis_grid_columns.tsx
src/plugins/vis_type_table/public/table_vis_fn.ts
src/plugins/vis_type_table/public/table_vis_renderer.test.tsx
src/plugins/vis_type_table/public/table_vis_response_handler.test.ts
src/plugins/vis_type_table/public/table_vis_response_handler.ts
src/plugins/vis_type_table/public/types.ts
src/plugins/vis_type_table/public/utils/__snapshots__/add_percentage_col.test.ts.snap
src/plugins/vis_type_table/public/utils/add_percentage_col.test.ts
src/plugins/vis_type_table/public/utils/add_percentage_col.ts
src/plugins/vis_type_table/public/utils/convert_to_csv_data.test.ts
src/plugins/vis_type_table/public/utils/convert_to_csv_data.ts
src/plugins/vis_type_table/public/utils/convert_to_formatted_data.test.ts
src/plugins/vis_type_table/public/utils/convert_to_formatted_data.ts
src/plugins/vis_type_table/public/utils/get_table_ui_state.test.ts
src/plugins/vis_type_table/public/utils/get_table_ui_state.ts
src/plugins/vis_type_table/public/utils/index.ts
src/plugins/vis_type_table/public/utils/use_pagination.test.ts
src/plugins/vis_type_table/public/utils/use_pagination.ts

Currently, table data is formatted by a until function convertToFormattedData in TableVisComponent. In this PR, we moved the formatting data process to table_vis_response_handler.ts to combine with other data process logics. In this way, component render and data handling logics are completely isolated. This PR also solidate some types.
fixes https://github.com/opensearch-project/OpenSearch-Dashboards/issues/3395

[Table Vis] move format table logic to table render and consolidate types

---

CHANGELOG.md
src/core/public/chrome/ui/header/__snapshots__/header.test.tsx.snap
src/core/public/chrome/ui/header/__snapshots__/header_help_menu.test.tsx.snap
src/core/public/chrome/ui/header/header.tsx
src/core/public/chrome/ui/header/header_help_menu.tsx

Added tooltip to a Help icon
fixes #3573

Add tooltip to help icon

---

src/plugins/dashboard/public/application/application.ts
src/plugins/dashboard/public/application/legacy_app.js

Fixes the edit button by not adding the base path to the URL when the route continues from the dashboards path.
Also re-add `addBasePath` to the interface defined by RenderDeps as before it was removed since we navigated away from using it but was missed in reverting back to the original implementation.
closes https://github.com/opensearch-project/OpenSearch-Dashboards/issues/3861
~~- [ ] Update [CHANGELOG.md](./../CHANGELOG.md)~~
- Skipping since unreleased.

[Dashboards Listing] Fix edit button

---

CHANGELOG.md
src/plugins/vis_type_table/public/components/table_vis_app.scss
src/plugins/vis_type_table/public/components/table_vis_app.test.tsx
src/plugins/vis_type_table/public/components/table_vis_app.tsx
src/plugins/vis_type_table/public/components/table_vis_cell.test.tsx
src/plugins/vis_type_table/public/components/table_vis_cell.tsx
src/plugins/vis_type_table/public/components/table_vis_component.test.tsx
src/plugins/vis_type_table/public/components/table_vis_component.tsx
src/plugins/vis_type_table/public/components/table_vis_component_group.test.tsx
src/plugins/vis_type_table/public/components/table_vis_component_group.tsx
src/plugins/vis_type_table/public/components/table_vis_grid_columns.tsx
src/plugins/vis_type_table/public/table_vis_fn.ts
src/plugins/vis_type_table/public/table_vis_renderer.test.tsx
src/plugins/vis_type_table/public/table_vis_response_handler.test.ts
src/plugins/vis_type_table/public/table_vis_response_handler.ts
src/plugins/vis_type_table/public/types.ts
src/plugins/vis_type_table/public/utils/__snapshots__/add_percentage_col.test.ts.snap
src/plugins/vis_type_table/public/utils/add_percentage_col.test.ts
src/plugins/vis_type_table/public/utils/add_percentage_col.ts
src/plugins/vis_type_table/public/utils/convert_to_csv_data.test.ts
src/plugins/vis_type_table/public/utils/convert_to_csv_data.ts
src/plugins/vis_type_table/public/utils/convert_to_formatted_data.test.ts
src/plugins/vis_type_table/public/utils/convert_to_formatted_data.ts
src/plugins/vis_type_table/public/utils/get_table_ui_state.test.ts
src/plugins/vis_type_table/public/utils/get_table_ui_state.ts
src/plugins/vis_type_table/public/utils/index.ts
src/plugins/vis_type_table/public/utils/use_pagination.test.ts
src/plugins/vis_type_table/public/utils/use_pagination.ts

Currently, table data is formatted by a until function convertToFormattedData in TableVisComponent. In this PR, we moved the formatting data process to table_vis_response_handler.ts to combine with other data process logics. In this way, component render and data handling logics are completely isolated. This PR also solidate some types.
https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3397
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/3395 https://github.com/opensearch-project/OpenSearch-Dashboards/issues/2856

[2.x Backport][Table Vis] move format table, consolidate types and add unit tests

---

CHANGELOG.md
src/core/public/chrome/ui/header/__snapshots__/header.test.tsx.snap
src/core/public/chrome/ui/header/header.tsx
src/core/public/chrome/ui/header/header_help_menu.tsx

[Manual Backport 1.3] Add tooltip to help icon (#3626)

---

.lycheeexclude
CHANGELOG.md
config/opensearch_dashboards.yml
src/plugins/data_source/config.ts
src/plugins/data_source/server/plugin.ts
src/plugins/data_source/server/saved_objects/data_source_saved_objects_client_wrapper.ts
src/plugins/data_source/server/util/endpoint_validator.test.js
src/plugins/data_source/server/util/endpoint_validator.ts

Add server side private IP blocking for data source endpoints validation. 
Tested locally data source creation with private IPs defined in the list will be blocked.

Add server side private IP blocking for data source endpoints validation

---

CHANGELOG.md
src/plugins/console/public/application/models/legacy_core_editor/__tests__/input.test.js
src/plugins/console/public/application/models/legacy_core_editor/__tests__/output_tokenization.test.js
src/plugins/console/public/application/models/legacy_core_editor/legacy_core_editor.ts
src/plugins/console/public/application/models/sense_editor/__tests__/integration.test.js
src/plugins/console/public/application/models/sense_editor/__tests__/sense_editor.test.js
src/plugins/console/public/application/models/sense_editor/sense_editor.test.mocks.ts
src/plugins/console/public/lib/ace_token_provider/token_provider.test.ts
src/plugins/console/public/lib/osd/osd.js

Reverts opensearch-project/OpenSearch-Dashboards#3733
This commit breaks:
1. The positioning of the action bar
2. Documentation links
3. Autocomplete

Revert "[CCI] Replace jquery usage in console plugin with native methods"

---

src/plugins/dashboard/public/application/legacy_app.js
src/plugins/dashboard/public/application/listing/create_button.test.tsx
src/plugins/dashboard/public/application/listing/create_button.tsx
test/plugin_functional/config.ts
test/plugin_functional/plugins/dashboard_listing_test_plugin/opensearch_dashboards.json
test/plugin_functional/plugins/dashboard_listing_test_plugin/package.json
test/plugin_functional/plugins/dashboard_listing_test_plugin/public/index.ts
test/plugin_functional/plugins/dashboard_listing_test_plugin/public/plugin.tsx
test/plugin_functional/plugins/dashboard_listing_test_plugin/tsconfig.json
test/plugin_functional/test_suites/dashboard_listing_plugin/dashboard_listing_plugin.ts
test/plugin_functional/test_suites/dashboard_listing_plugin/index.ts

History push will just to the current route. However, dashboardsProvider was implemented with the expectation that it was a different app.
So when a plugin registered it was attempting to navigate to `app/dashboard#/app/{url}`
n/a

[BUG][Dashboard listing] push to history if dashboard otherwise nav

---

release-notes/opensearch-dashboards.release-notes-2.7.0.md

for https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3929 revert

remove jquery console release note

---

CHANGELOG.md
package.json
yarn.lock

Bump package yaml to 2.2.2 to resolve CVE-2023-2251
Opensearch Dashboard has transitive dependency on package yaml. Upgrading direct dependencies to its updated version does not resolve package yaml to 2.2.2 version. Hence adding selective dependency resolution to yaml package.
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/3946

[CVE-2023-2251] Bump yaml to 2.2.2

---

examples/embeddable_examples/public/searchable_list_container/searchable_list_container_component.tsx
examples/embeddable_explorer/public/list_container_example.tsx
src/plugins/embeddable/docs/input_and_output_state.md

Add more description to the list container embeddable in the embeddable example plugin. Also remove a line of duplicate code.
resolve #3906

Fix wording and duplicate code in embeddable example plugin

---

test/interpreter_functional/plugins/osd_tp_run_pipeline/package.json
test/plugin_functional/plugins/app_link_test/package.json
test/plugin_functional/plugins/core_app_status/package.json
test/plugin_functional/plugins/core_plugin_a/package.json
test/plugin_functional/plugins/core_plugin_appleave/package.json
test/plugin_functional/plugins/core_plugin_b/package.json
test/plugin_functional/plugins/core_plugin_chromeless/package.json
test/plugin_functional/plugins/core_plugin_route_timeouts/package.json
test/plugin_functional/plugins/core_plugin_static_assets/package.json
test/plugin_functional/plugins/core_provider_plugin/package.json
test/plugin_functional/plugins/data_search/package.json
test/plugin_functional/plugins/doc_views_links_plugin/package.json
test/plugin_functional/plugins/doc_views_plugin/package.json
test/plugin_functional/plugins/index_patterns/package.json
test/plugin_functional/plugins/management_test_plugin/package.json
test/plugin_functional/plugins/opensearch_client_plugin/package.json
test/plugin_functional/plugins/osd_sample_panel_action/package.json
test/plugin_functional/plugins/osd_top_nav/package.json
test/plugin_functional/plugins/osd_tp_custom_visualizations/package.json
test/plugin_functional/plugins/rendering_plugin/package.json
test/plugin_functional/plugins/ui_settings_plugin/package.json

Backport  8f890e98f1af903a10b07ccb48065a9c843da990 from https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3783

[Manual backport 1.x][CCI] Replace `node` with `scripts/use_node` in functional tests

---

CHANGELOG.md
package.json
yarn.lock

This CVE is caught in github. It is about that `loadAsync` in `jszip` before 3.8.0 allows Directory Traversal via a crafted ZIP archive. `jszip` is a dependency of `selenium-webdriver` . This CVE requires to bump `jszip` to 3.8.0+. In 1.x, we are currently using `jszip@3.7.1` .
```
ubuntu@ip-172-31-55-237:~/work/OpenSearch-Dashboards$ yarn why jszip
[1/4] Why do we have the module "jszip"...?
warning Resolution field "shelljs@0.8.5" is incompatible with requested version "shelljs@^0.6.0"
=> Found "jszip@3.7.1"
- …
```

[CVE-2022-48285][1.x] Bump jszip from 3.7.1 to 3.10.1

---

.github/workflows/build_and_test_workflow.yml
CHANGELOG.md
scripts/upgrade_chromedriver.js

Within the CI, the virtual runner that we are utilizing has Chrome
installed already. The version of Chrome is installed periodically.
The most recent version of Chrome requires updates to dependencies
that drop support for Node 14.
This downloads chrome in the CI and then checks the chromedriver
from the environment variable `TEST_BROWSER_BINARY_PATH`.
See failures here: 
https://github.com/opensearch-project/OpenSearch-Dashboards/actions/runs/4896112900/jobs/8742518044

[CI] setup Chrome and utilize binary path

---

CHANGELOG.md
src/plugins/dashboard/public/application/legacy_app.js

Initial page size was passed to the search function instead of the listing limit causing the max amount received to be significantly less than the previously implementation.
Saved objects per page is `20` by default and the listing limit per page is `1000` by default.
resolves: https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4017

[Dashboards listing] fix listing limit

---

CHANGELOG.md
src/core/public/rendering/_base.scss
src/core/public/rendering/app_containers.test.tsx
src/core/public/rendering/app_containers.tsx
src/plugins/advanced_settings/public/management_app/_advanced_settings.scss
src/plugins/advanced_settings/public/management_app/components/form/form.test.tsx
src/plugins/advanced_settings/public/management_app/components/form/form.tsx

Fixed bottom bar visibility using createPortal.
https://user-images.githubusercontent.com/17855243/236097081-de85528f-d784-47c3-9e0c-5f5965c44181.mov
To clarify, the `<EuiPortal />` component cannot be used as a replacement for `createPortal` function. This is because `<EuiPortal />` creates a `<div>` wrapper element that breaks the "sticky" behavior.
Although there have been some efforts to make `<EuiPortal />` work in a similar way to `createPortal` function, more information about this can be found in https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3949 
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/3336

[CCI] Fix bottom bar visibility using createPortal

---

CHANGELOG.md
package.json
src/dev/build/tasks/patch_native_modules_task.test.ts
src/dev/build/tasks/patch_native_modules_task.ts
src/plugins/vis_type_timeline/server/series_functions/label.js
src/plugins/vis_type_timeline/server/series_functions/label.test.js
yarn.lock

Remove re2 usage and replace it with JavaScript built-in RegExp object. Also add more unit tests to make sure that using RegExp has same expressions as using re2 library.
fixes https://github.com/opensearch-project/OpenSearch-Dashboards/issues/3901

Replace `re2` with RegExp in timeline and add unit tests

---

src/plugins/vis_augmenter/common/augment_vis_saved_object_attributes.ts
src/plugins/vis_augmenter/common/constants.ts
src/plugins/vis_augmenter/common/index.ts
src/plugins/vis_augmenter/public/saved_augment_vis/_saved_augment_vis.ts
src/plugins/vis_augmenter/public/saved_augment_vis/saved_augment_vis.test.ts
src/plugins/vis_augmenter/public/saved_augment_vis/saved_augment_vis.ts
src/plugins/vis_augmenter/public/saved_augment_vis/saved_augment_vis_references.test.ts
src/plugins/vis_augmenter/public/saved_augment_vis/saved_augment_vis_references.ts
src/plugins/vis_augmenter/public/saved_augment_vis/types.ts
src/plugins/vis_augmenter/public/saved_augment_vis/utils/helpers.ts
src/plugins/vis_augmenter/public/saved_augment_vis/utils/test_helpers.ts
src/plugins/vis_augmenter/public/utils/utils.test.ts
src/plugins/vis_augmenter/server/plugin.ts
src/plugins/vis_augmenter/server/routes/stats.ts
src/plugins/vis_augmenter/server/routes/stats_helpers.test.ts
src/plugins/vis_augmenter/server/routes/stats_helpers.ts
src/plugins/vis_augmenter/server/saved_objects/augment_vis.ts

Adds a server-side API `/api/vis-augmenter/stats` to track usage of the feature. It does this by collecting all `augment-vis` saved objects, and aggregating values within them. Specifically:
- total number of saved objects
- breakdown and count of unique origin plugins
- breakdown and count of unique plugin resource types
- breakdown and count of plugin resource IDs
- breakdown and count of visualization IDs
This allows us to track what plugins and plugin resource types are being used (e.g., how many anomaly detectors are associated), as well as the individual IDs of the plugin resources and visualizations, to see if there are any unique patterns in how the feature is being used (e.g., many plugin resources to one visualization compared to roughly 1:1 mapping).
To collect these values, …

Add a `VisAugmenter` stats API

---

src/plugins/vis_augmenter/public/constants.ts
src/plugins/vis_augmenter/public/vega/helpers.ts

Show custom tooltip for point in time annotation mark in vega visualization
Solves remaining part of #3317 
N/A

showing default tooltip on mark

---

src/plugins/vis_augmenter/public/test_constants.ts
src/plugins/vis_augmenter/public/types.ts
src/plugins/vis_augmenter/public/vega/helpers.test.ts
src/plugins/vis_augmenter/public/vega/helpers.ts

Adds a custom `tooltip` field in the event marks in the vega lite spec to only show the relevant `VisLayer` fields we are interested in. See screenshot below, where there are 2 different `VisLayer` fields we are interested in - 'Anomalies' and 'Alerts'. Tooltip fns handle the automatic mapping/formatting, we just provide the fields.
This PR also updates the `VisLayer` interface to persist a new `pluginEventType` field to `PointInTimeEventsVisLayer`. This is so we can use this to derive the datatable columns, such that data on the charts will be aggregated into unique values for different plugin event types ; in other words, all events of type 'Anomalies' (could be from multiple detectors) should be grouped into this same event type. This is the expected behavior on UX side as well.

Support formatted tooltip for event marks

---

src/plugins/data_source_management/public/components/create_data_source_wizard/components/create_form/create_data_source_form.tsx
src/plugins/data_source_management/public/components/edit_data_source/components/edit_form/edit_data_source_form.tsx

[MD]Update data-test-subj for functional tests & fix bug in edit flow
related PR in functional test repo: **https://github.com/opensearch-project/opensearch-dashboards-functional-test/pull/669**
https://github.com/opensearch-project/opensearch-dashboards-functional-test/issues/665

[MD]Severless Support: update `data-test-subj`attribute for functional tests & fix bug in edit flow

---

CHANGELOG.md
scripts/use_node
src/dev/build/tasks/bin/scripts/opensearch-dashboards
src/dev/build/tasks/bin/scripts/opensearch-dashboards-plugin

OSD 2.6 in prior used `exec` in the CLI scripts to invoke `node`; this was removed when `use_node` was introduced. This change reintroduces `exec` which will prevent new processes from being created.
`exec` executes a command that completely replaces the current process where the current shell process is destroyed. When you exec a command, it replaces bash entirely — no new process is forked, no new PID is created, and all memory controlled by bash is destroyed and overwritten ([ref](https://www.computerhope.com/unix/bash/exec.htm)). This is useful for when the `bin` file calls `use_node` who then calls `node`; instead of having 3 PIDs to check for health, 2 of which will be doing nothing, `exec` allows `use_node` to replace the `bin` script and then `node` to replace the `use_node`, …

Use `exec` in the CLI shell scripts to prevent new process creation

---

src/plugins/vis_augmenter/public/saved_augment_vis/utils/helpers.ts
src/plugins/vis_augmenter/public/utils/utils.ts

There is an issue where plugins running helper fns from `visAugmenter` are failing, due to the `visAugmenter` plugin's services showing as not being set. Detail on issue: see #4138 
To fix this for now, we can update the helper fns to take in plugin-set services, which are defined.

[Feature Anywhere] Expose external services to helper fns

---

CHANGELOG.md
scripts/use_node
src/dev/build/tasks/create_archives_sources_task.ts
src/dev/build/tasks/nodejs/download_node_builds_task.test.ts
src/dev/build/tasks/nodejs/download_node_builds_task.ts
src/dev/build/tasks/nodejs/extract_node_builds_task.test.ts
src/dev/build/tasks/nodejs/extract_node_builds_task.ts
src/dev/build/tasks/nodejs/node_download_info.ts

Not all operating systems can run Node 18. Hence, Node 14 is bundled as a fallback for them.
* getNodeVersionDownloadInfo is responsible for generating the download information for a specific version of Node.js given the version number, architecture (e.g., x64), and the operating system.
* Node.js 14 binaries are downloaded and copied to node/fallback directory in the build path specific to a platform.
* Check if the desired Node.js version is available and executable, and if it is not, falling back to the path where Node.js 14 is stored (the "fallback" directory).
Hold merging until #3955 is merged.

Bundle Node 14 as a fallback for operating systems that cannot run Node 18

---

.github/workflows/cypress_workflow.yml
CHANGELOG.md

Snapshot checksum verification caused failure in test runs: https://github.com/opensearch-project/OpenSearch-Dashboards/pull/4187
Skipping the verification to enable the tests run as the snapshot of OpenSearch should not impact the tests.
n/a

[CI] skip checksum verification for cypress tests

---

CHANGELOG.md
src/plugins/vis_type_table/public/components/table_vis_app.scss
src/plugins/vis_type_table/public/components/table_vis_component.tsx

Replaces usage of ```.visTable__component__title``` custom class with OUI utility class ```oui-textCenter```.
Solves https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4163
Go to table visualizations, use `Split table`. Now we have multiple tables and each one should have centered title as in the screenshot.

[Table Visualization] Remove custom styling for text-align:center in favor of OUI utility class.

---

release-notes/opensearch-dashboards.release-notes-2.8.0.md

Add release notes for 2.8.0.
Related issue:
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4074

Add 2.8.0 release notes

---

CHANGELOG.md
src/core/server/legacy/legacy_service.ts
src/core/server/plugins/plugin_context.ts
src/core/server/saved_objects/saved_objects_service.mock.ts
src/core/server/saved_objects/saved_objects_service.test.ts
src/core/server/saved_objects/saved_objects_service.ts
src/core/server/saved_objects/service/lib/scoped_client_provider.ts

The **Repository Factory Provider** in OpenSearch-Dashboards will be responsible for creating and managing instances of the Repository (e.g. SavedObjectRepository, PostgresRepository, DynamoDBRepository etc.), which is used to interact with the metadata storage that stores the saved objects. Currently we have an repository interface named [ISavedObjectRepository](https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/src/core/server/saved_objects/service/lib/repository.ts#L134), and the [SavedObjectRepository](https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/src/core/server/saved_objects/service/lib/repository.ts#L139) is the implementation, which use an OpenSearch index as its data store. This approach would make the implementation of …

[Saved Object Service] Adds Repository Factory Provider

---

src/plugins/vis_augmenter/public/view_events_flyout/actions/view_events_option_action.tsx
src/plugins/vis_augmenter/public/view_events_flyout/components/event_vis_item.tsx
src/plugins/vis_augmenter/public/view_events_flyout/components/styles.scss
src/plugins/vis_augmenter/server/capabilities_provider.ts
src/plugins/vis_augmenter/server/saved_objects/augment_vis.ts

Various bug fixes:
1. Hides 'view events' option on eligible charts, if there is no existing vislayers.
2. Fixes text wrapping of plugin resource names in view events flyout by adding [word-break styling](https://developer.mozilla.org/en-US/docs/Web/CSS/word-break). Also expands width from 150px -> 200px to increase likelihood of the names fitting on one line and not looking too squished/compact
3. Adds external link to plugin resource names in view events flyout
4. Cleans up default saved obj title in the saved obj management plugin to be `augment-vis-<originPlugin>`
5. Disables/removes the 'View augment-vis' button in the saved obj details page in saved obj management plugin by updating the value in `capabilitiesProvider`.
6. Updates the view events icon to `inspect`
Screenshots of …

[Feature Anywhere] Various bug fixes

---

src/plugins/dashboard/public/application/components/dashboard_editor.tsx
src/plugins/dashboard/public/application/components/dashboard_top_nav.tsx
src/plugins/dashboard/public/application/utils/create_dashboard_app_state.tsx
src/plugins/dashboard/public/application/utils/use/use_chrome_visibility.ts
src/plugins/dashboard/public/application/utils/use/use_dashboard_app_state.tsx
src/plugins/dashboard/public/application/utils/use/use_saved_dashboard_instance.ts
src/plugins/dashboard/public/application/utils/utils.ts
src/plugins/dashboard/public/types.ts

This PR will add basic structure to render top nav bar, including a basic implementation for dashboard app state. This is not functionality complete, but to help implement a basic working dashboard app as the first step.
Not included in this PR but todo:
* make app state persist data
* the filter bar which is also part of the top nav bar: need to implement dashboard container embeddable first in order to render the filter bar
* URL parsing to correctly determine the params such as `embed`, `forceShowTopNavMenu`, `forceShowQueryInput`..etc
* top nav bar actions including `save`, `save as`...etc
resolves #4002

[Dashboard De-Angular] Add basic top nav bar structure

---

CHANGELOG.md
package.json
src/dev/build/tasks/patch_native_modules_task.test.ts
src/dev/build/tasks/patch_native_modules_task.ts
src/plugins/vis_type_timeline/server/series_functions/label.js
src/plugins/vis_type_timeline/server/series_functions/label.test.js
yarn.lock

Remove re2 usage and replace it with JavaScript built-in RegExp object. Also add more unit tests to make sure that using RegExp has same expressions as using re2 library.
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/3901
https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3908

[2.8 backport] Replace re2 with RegExp in timeline and add unit tests

---

src/plugins/vis_augmenter/public/utils/utils.test.ts
src/plugins/vis_augmenter/public/utils/utils.ts
src/plugins/vis_type_vega/public/vega_view/vega_view.js

Fixes 2 bugs:
1. Misaligned timeline chart in view events flyout - due to a missed conditional
2. NPE in `isEligibleForVisLayers()` helper fn, depending on the visualizations passed to it. For example, pie charts don't have `seriesParams` field, which was leading to the NPE. Adds couple other NPE checks as well, since `VisParams` unfortunately is very loosely typed so we have to account for lots of potential places where fields may exist in one vis type but not for others.

[Feature Anywhere] More bug fixes

---

src/plugins/vis_augmenter/public/index.ts
src/plugins/vis_augmenter/public/view_events_flyout/components/index.ts
src/plugins/vis_augmenter/public/view_events_flyout/components/utils.tsx
src/plugins/vis_augmenter/public/view_events_flyout/components/view_events_flyout.tsx
src/plugins/visualizations/public/embeddable/visualize_embeddable.ts

Allow plugins get vis embeddable to show in flyouts.
This prevents plugins from using the current embeddable object to show in the flyout as the breaks functionality in the main dashboard visualization.
This prevents plugins from using the current embeddable object to show in the flyout as the breaks functionality in the main dashboard visualization.

Allow plugins get vis embeddable to show in flyouts

---

CHANGELOG.md
packages/osd-optimizer/package.json
yarn.lock

Issue Resolve
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4260

Remove `lmdb-store` to fix backport issue

---

CHANGELOG.md

Validate and correct `main` change log after 2.8 release
part of #4263

Validate and correct change log after 2.8 release

---

CHANGELOG.md
package.json
packages/osd-ui-framework/package.json
yarn.lock

* This one is to fix [CVE-2022-1537](https://github.com/advisories/GHSA-rm36-94g8-835r) in 1.3 branch targeting release 1.3.11
* This is a manual backport of
https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3723 tailored for 1.3 as `Node 10` is in use for OSD 1.3
* Lock both major and minor as grunt 1.6 does requires `Node 16+`
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1579

[Backport 1.3][CVE-2022-1537] Bump grunt from 1.5.2 to 1.5.3

---

CHANGELOG.md
package.json
src/dev/build/tasks/patch_native_modules_task.test.ts
src/dev/build/tasks/patch_native_modules_task.ts
src/plugins/vis_type_timeline/server/series_functions/label.js
src/plugins/vis_type_timeline/server/series_functions/label.test.js
yarn.lock

Remove re2 usage and replace it with JavaScript built-in RegExp object. Also add more unit tests to make sure that using RegExp has same expressions as using re2 library.
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/3901
https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3908

[2.x backport]Replace re2 with RegExp in timeline and add unit tests

---

src/plugins/dashboard/public/application/app.tsx
src/plugins/dashboard/public/application/components/dashboard_editor.tsx
src/plugins/dashboard/public/application/components/dashboard_top_nav.tsx
src/plugins/dashboard/public/application/lib/save_dashboard.ts
src/plugins/dashboard/public/application/lib/update_saved_dashboard.ts
src/plugins/dashboard/public/application/utils/dashboard_embeddable_editor.tsx
src/plugins/dashboard/public/application/utils/get_nav_actions.tsx
src/plugins/dashboard/public/application/utils/use/use_dashboard_app_state.tsx
src/plugins/dashboard/public/application/utils/use/use_dashboard_container.tsx
src/plugins/dashboard/public/application/utils/use/use_editor_updates.ts
src/plugins/dashboard/public/application/utils/use/use_saved_dashboard_instance.ts
src/plugins/dashboard/public/types.ts

Added logics to use dashboard embeddable container to render the main dashboard editor page with some basic nav actions. 
This PR sets up some basic foundational logics for dashboard container, state container in order to render the page. The related functionality will be complated in subsequent PRs.
#4212
#4003 
https://github.com/opensearch-project/OpenSearch-Dashboards/assets/43937633/04b0fdcc-8d06-47a6-b36b-c37a4ecb318f

[Dashboard De-Angular] Render the main dashboard editor page with nav actions

---

CHANGELOG.md
scripts/use_node

The first time the `use_node` was executed in a session, while validating that the primary bundled Node binary was suitable for the OS, the version would be printed out in the case of success. This was a new bit of info with no labels to make it meaningful. The modified code supressed success or failure msgs.
resolves: https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4241

Hide any output from `use_node` checking for Node compatibility

---

src/plugins/vis_augmenter/public/view_events_flyout/components/utils.tsx

This allows the show visualization piece to work from the plugins since they need to call `fetchVisEmbeddable`
N/A
Setup remote cluster with this built and tested against Alerting plugin

Allow queryStart to be passed into fetchVisEmbeddable

---

src/plugins/dashboard/public/application/app.scss
src/plugins/dashboard/public/application/app.tsx
src/plugins/dashboard/public/application/dashboard_empty_screen.scss
src/plugins/dashboard/public/application/dashboard_empty_screen.tsx
src/plugins/dashboard/public/application/utils/use/use_dashboard_container.tsx

Render empty dashboard screen when creating a new dashboard. 
1. When clicking `Create New`, show the correct empty new dashboard page and the view mode should be default to `Edit` mode.
2. When clicking `Add an existing` button, the add panel will be triggered
3. When clicking `Create new` button, the create new visualization panel should be shown
4. When existing out of edit mode, view mode should correctly render the empty view page.
5. When clicking `Edit` button in the box, it should automatically switch to edit view mode.
https://github.com/opensearch-project/OpenSearch-Dashboards/assets/43937633/be2933fb-c9b0-43c5-8658-615e7030fe17

[Dashboard De-Angular] Render empty dashboard screen when creating new dashboards

---

CHANGELOG.md
src/plugins/vis_type_timeseries/public/metrics_type.ts

https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4318
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4324
Before:
After:

[Vis Colors] Update default color in TSVB to use `ouiPaletteColorBlind()[0]`

---

.github/workflows/build_and_test_workflow.yml
CHANGELOG.md
bwctest.sh
cypress/integration/with-security/helpers/generate_data.js
cypress/integration/without-security/helpers/generate_data.js
release-notes/opensearch-dashboards.release-notes-1.3.10.md
release-notes/opensearch-dashboards.release-notes-2.8.0.md

Test data generated with:
yarn test:bwc -o https://artifacts.opensearch.org/releases/bundle/opensearch/2.6.0/opensearch-2.6.0-linux-x64.tar.gz -d https://artifacts.opensearch.org/releases/bundle/opensearch-dashboards/2.6.0/opensearch-dashboards-2.6.0-linux-x64.tar.gz -g true
yarn test:bwc -o https://artifacts.opensearch.org/releases/bundle/opensearch/2.7.0/opensearch-2.7.0-linux-x64.tar.gz -d https://artifacts.opensearch.org/releases/bundle/opensearch-dashboards/2.7.0/opensearch-dashboards-2.7.0-linux-x64.tar.gz -g true
yarn test:bwc -o https://artifacts.opensearch.org/releases/bundle/opensearch/2.6.0/opensearch-2.6.0-linux-x64.tar.gz -d https://artifacts.opensearch.org/releases/bundle/opensearch-dashboards/2.6.0/opensearch-dashboards-2.6.0-linux-x64.tar.gz -g true -s true
yarn test:bwc …

[CI][Tests] Add BWC tests for 2.7 and 2.8

---

package.json

Bump version from 2.8 to 2.9
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4074

Bump version to 2.9

---

CHANGELOG.md
src/plugins/vis_type_timeline/public/helpers/panel_utils.ts

https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4318
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4322
Before:
After:

[Vis colors] Replace vis_type_timeline colors with `ouiPaletteColorBlind()`

---

CHANGELOG.md
src/core/server/rendering/__snapshots__/rendering_service.test.ts.snap
src/core/server/rendering/rendering_service.test.ts
src/core/server/rendering/rendering_service.tsx
src/core/server/ui_settings/types.ts
src/core/server/ui_settings/ui_settings_client.test.ts
src/core/server/ui_settings/ui_settings_client.ts
src/core/server/ui_settings/ui_settings_config.ts
src/core/server/ui_settings/ui_settings_service.mock.ts
src/core/server/ui_settings/ui_settings_service.test.ts
src/core/server/ui_settings/ui_settings_service.ts
src/legacy/ui/ui_render/ui_render_mixin.js

Add configurable `defaults` and `overrides` to `uiSettings`
There are 4 levels of uiSettings:
1) defaults hardcoded in code
2) defaults provided in the opensearch_dashboards.yml
3) values selected by the user and received from savedObjects
4) overrides provided in the opensearch_dashboards.yml
Each of these levels override the one above them.
Also now:
* `theme:darkMode` and `theme:version` can be configured via `defaults`
* `theme:darkMode` can be configured via `overrides`
* unauthenticated users are no longer forced to light mode
Sample config:
```yml
uiSettings:
overrides:
"theme:darkMode": false
defaults:
"theme:darkMode": true # will be overridden by the above
"theme:version": "v7"  # will have no effect due to the hard-coded override
```
Despite these changes, for now, …

Add configurable `defaults` and `overrides` to `uiSettings`

---

CHANGELOG.md

For 2.x branch:
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4263

Update CHANGELOG with new 2.8.0/2.7.0 sections and clean-up unreleased section

---

src/plugins/dashboard/public/application/app.tsx
src/plugins/dashboard/public/application/components/dashboard_listing.tsx
src/plugins/dashboard/public/application/components/dashboard_no_match.tsx
src/plugins/dashboard/public/application/utils/use/use_dashboard_container.tsx
src/plugins/dashboard/public/plugin.tsx
src/plugins/dashboard/public/types.ts

This PR fix the following routing related issues:
1. The edit action should get to that dashboard in edit mode.
2. When there is no match for the route, should navigate to default app route.
3. Append '_g' param to URL both on the listing page and on the editor page.
4. When we click dashboard tab from the side menu, it should navigate back to the listing page without refreshing.
https://github.com/opensearch-project/OpenSearch-Dashboards/assets/43937633/e8e417a4-86e4-4791-a1db-6aac948820d5

[Dashboard De-Angular] Add additional routing configurations

---

src/plugins/dashboard/public/application/components/dashboard_editor.tsx
src/plugins/dashboard/public/application/lib/update_saved_dashboard.ts
src/plugins/dashboard/public/application/utils/use/use_editor_updates.ts
src/plugins/dashboard/public/application/utils/use/use_saved_dashboard_instance.ts
src/plugins/dashboard/public/plugin.tsx
src/plugins/dashboard/public/types.ts
test/functional/apps/dashboard/index.js

This PR fixes time filter related functionalities for dashboard plugin. 
1. Time filter are able to update the child visualization embeddables. They are part of the global states, thus they are not stored in state container/app state; however, we still need to pass the information to dashboard embeddable container because it needs the info to update the child visualization embeddables.
https://github.com/opensearch-project/OpenSearch-Dashboards/assets/43937633/26f4b472-f037-4b96-a7c4-5d2d80b1f7d2
2. We need to be able to store dashboard with time filters/ without time filters by toggling the `Store time with dashboard` option on the save modal.
https://github.com/opensearch-project/OpenSearch-Dashboards/assets/43937633/e19f68c0-c6cb-43a0-a361-36e1a2fc1d0d
3. Any query and filters should …

[Dashboard De-Angular] Enable time filter functionalities 

---

packages/osd-ui-shared-deps/flot_charts/API.md

The link https://apidock.com/ruby/Time/to_i is currently down for maintenance, which is causing the link checker automation to fail on all PRs.
But we don't need this link anyway, because it's developer docs talking about standard methods in various languages. And we plan to deprecate flot_charts altogether: https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4267

Remove broken flot documentation link for Ruby API

---

CHANGELOG.md
package.json
packages/osd-ui-framework/package.json
packages/osd-ui-shared-deps/package.json
test/interpreter_functional/plugins/osd_tp_run_pipeline/package.json
test/plugin_functional/plugins/osd_sample_panel_action/package.json
test/plugin_functional/plugins/osd_tp_custom_visualizations/package.json
yarn.lock

Bump OUI to 1.1.2 to separate icon addition from other `1.2.0` changes. Intended to be immediately merged and backported to `2.x` while we continue to investigate concerns raised in https://github.com/opensearch-project/OpenSearch-Dashboards/pull/4170

Chore (deps): Bump OUI to 1.1.2 to add anomoly detection icon

---

CHANGELOG.md
src/plugins/home/opensearch_dashboards.json
src/plugins/home/public/application/components/sample_data_set_card.js
src/plugins/home/public/application/components/sample_data_set_cards.js
src/plugins/home/public/application/components/tutorial_directory.js
src/plugins/home/public/application/opensearch_dashboards_services.ts
src/plugins/home/public/plugin.ts

Add data source selector to sample data page according to UX experience.
The frontend section for: https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4240
https://github.com/opensearch-project/OpenSearch-Dashboards/assets/105667444/0431feb0-ce4d-41bc-8139-59bd6bd8b5ea
Tested as the recording recorded.

Enable sample data with Multiple datasource frontend

---

src/plugins/visualizations/public/embeddable/visualize_embeddable.ts

There was [some recent bug fixes](https://github.com/opensearch-project/OpenSearch-Dashboards/pull/4327) to prevent fetching vislayers in the context of the vis edit flow. This fix missed the scenario of rendering the charts in the view events flyout. This fixes that by checking the config that is passed to the visualize_embeddable, and checking if in the flyout context or not.

[Feature Anywhere] Fix bug of charts in view events flyout not fetching vislayers

---

src/plugins/dashboard/public/application/components/dashboard_top_nav.tsx
src/plugins/dashboard/public/application/utils/get_nav_actions.tsx
src/plugins/dashboard/public/application/utils/use/use_dashboard_container.tsx

UI should render based on URL param options. This PR should fix functional test: https://github.com/opensearch-project/OpenSearch-Dashboards/blob/70b3420fc18819f81fd8bf7efc4625f6ece77c63/test/functional/apps/dashboard/embed_mode.js
There are currently five URL param config options:
1. embed=true --> enter embed mode
once we enter embed mode:
1. show-top-menu=true --> show top menu 
2. show-query-input=true --> show query input
3. show-time-filter=true --> show time filter
4. hide-filter-bar=true --> hide filter bar
This issue documented the some buggy behavior related to the embed mode: https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4372#issuecomment-1605225746. However, since this is related to a common hook that is also used by other plugins, this PR still follows …

[Dashboard De-Angular] Add embed mode and other URL param options

---

test/functional/apps/visualize/_area_chart.js

CI group 9 has a frequently failing flakey test. This PR hopefully fixes the issue based on @ananzh's deepdive.
Possibly fixes #4422 
CI group 9 should not intermittently fail

possible fix for flakey ci9 test

---

CHANGELOG.md
COMMUNICATIONS.md
src/plugins/dashboard/public/plugin.tsx

Update main menu to display 'Dashboards' for consistency. 
This resolves the inconsistency highlighted in issue https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4296. The decision to make this change was made in issue https://github.com/opensearch-project/ux/issues/68.
fixes #4296

Update main menu to display 'Dashboards' for consistency

---

CHANGELOG.md
package.json
packages/osd-optimizer/package.json
packages/osd-ui-framework/package.json
yarn.lock

* This one is to fix [CVE-2021-23382](https://github.com/advisories/GHSA-566m-qj78-rww5) in 1.3 branch targeting `1.3.12`
* The current dependency config is looking good for `postcss` so just did a lock file refresh to pick up the patch.
* Here is the actual patch on postcss side https://github.com/postcss/postcss/commit/2b1d04c867995e55124e0a165b7c6622c1735956 fyi
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1094

[CVE-2021-23382] Bump postcss from 8.2.10 to 8.4.24

---

src/plugins/dashboard/public/application/components/dashboard_editor.tsx
src/plugins/dashboard/public/application/components/dashboard_top_nav.tsx
src/plugins/dashboard/public/application/lib/get_app_state_defaults.ts
src/plugins/dashboard/public/application/utils/create_dashboard_app_state.tsx
src/plugins/dashboard/public/application/utils/get_dashboard_instance.tsx
src/plugins/dashboard/public/application/utils/get_nav_actions.tsx
src/plugins/dashboard/public/application/utils/use/use_dashboard_app_state.tsx
src/plugins/dashboard/public/application/utils/use/use_dashboard_container.tsx
src/plugins/dashboard/public/application/utils/use/use_editor_updates.ts
src/plugins/dashboard/public/application/utils/use/use_saved_dashboard_instance.ts
src/plugins/dashboard/public/dashboard.ts
src/plugins/dashboard/public/plugin.tsx
src/plugins/dashboard/public/saved_dashboards/_saved_dashboard.ts
src/plugins/dashboard/public/types.ts

Make discard flow working on dashboard:
1. If there is no changes, the cancel button will return back to the view mode
2. If there are changes, the cancel button will show a warning window; the discard button will discard the unsaved changes and return back to the original states.
-- Add a Dashboard class to store the original state values, so they can be retrieved if `discard`
-- Add a `isDirty` flag in the app state to indicate if there are unsaved changes
#4433

[Dashboard De-Angular] Add dashboard class for discard flow

---

src/plugins/dashboard/public/application/components/dashboard_editor.tsx
src/plugins/dashboard/public/application/utils/breadcrumbs.ts
src/plugins/dashboard/public/application/utils/get_nav_actions.tsx

Add breadcrumb logics, the breadcrumb text will be changing based on view/edit mode, unsaved changes/or not, new dashboard/existing dashboard
1. When creating new dashboard
-- New dashboard  <-- when in view mode
-- Editing new dashboard  <-- when in edit mode with no changes
-- Editing new dashboard (unsaved) <-- when in edit with changes
similarly, 
2. When editing an existing dashboard
-- dashboard_name
-- Editing dashboard_name
-- Editing dashboard_name (unsaved)
3. The dashboard breadcrumb should take back to listing page.
#4358 
https://github.com/opensearch-project/OpenSearch-Dashboards/assets/43937633/333b1d30-0afe-412c-b1e0-66340f04133b

[Dashboard De-Angular] Add breadcrumb with view/edit mode and unsaved flow

---

src/plugins/dashboard/public/application/components/dashboard_listing.tsx

`title=xxx` can be append to dashboard listing URL and use as an initial filter.
1. when `title=xxx`, and xxx match exactly with one dashboard, the browser should navigate to that dashboard view page
2. If xxx does not have any exact match, then  all dashboards whose prefix that match will show
3. If xxx does not match any prefix, the listing will be empty
#4356 
Fix the dashboard_listing related functional tests in test group 5.
https://github.com/opensearch-project/OpenSearch-Dashboards/assets/43937633/71cb6138-42c8-407d-9b85-dc56f0255d33

[Dashboard De-Angular] Enable URL title param for initial filter on dashboard listing

---

CHANGELOG.md
src/core/server/rendering/views/styles.tsx

Add `color-scheme` to the root styling:
* The immediate benefit is visible in browsers' built-in styling applied to form elements:
Without `color-scheme` in dark mode:
With `color-scheme` in dark mode:
* The long-term benefit is the ability to use color-scheme-aware styling and imagery.

Add `color-scheme` to the root styling

---

src/plugins/dashboard/common/migrate_to_730_panels.ts
src/plugins/dashboard/public/application/app.tsx
src/plugins/dashboard/public/application/components/dashboard_editor.tsx
src/plugins/dashboard/public/application/components/dashboard_listing.tsx
src/plugins/dashboard/public/application/components/dashboard_top_nav.tsx
src/plugins/dashboard/public/application/lib/embeddable_saved_object_converters.ts
src/plugins/dashboard/public/application/lib/get_app_state_defaults.ts
src/plugins/dashboard/public/application/lib/migrate_app_state.ts
src/plugins/dashboard/public/application/utils/create_dashboard_app_state.tsx
src/plugins/dashboard/public/application/utils/get_nav_actions.tsx
src/plugins/dashboard/public/application/utils/use/use_dashboard_app_state.tsx
src/plugins/dashboard/public/application/utils/use/use_dashboard_container.tsx
src/plugins/dashboard/public/application/utils/use/use_editor_updates.ts
src/plugins/dashboard/public/application/utils/use/use_saved_dashboard_instance.ts
src/plugins/dashboard/public/types.ts

Fix function test: 
1. https://github.com/opensearch-project/OpenSearch-Dashboards/blob/1560a6c4e37013649d049dfa4569f4329e0d0118/test/functional/apps/dashboard/dashboard_back_button.ts
2. https://github.com/opensearch-project/OpenSearch-Dashboards/blob/1560a6c4e37013649d049dfa4569f4329e0d0118/test/functional/apps/dashboard/dashboard_save.js
Changes: 
* To make back button work, fix redundant browser updates 
1. Fix version migration for panels
2. Fix conversions between saved panel and container panel type
3. Re-structure app state and global state sync logic 
4. Add initialization isDirty flag so we do not mark dirty because of render initialization to panel structure
* Pass in saveOnCopy prop to make save dashboard function properly 
* Fix full mode filter bar ( Full mode should still …

[Dashboard De-Angular] Fix dashboard save and back button functional test

---

src/plugins/dashboard/public/application/components/dashboard_editor.tsx
src/plugins/dashboard/public/application/components/dashboard_top_nav.tsx
src/plugins/dashboard/public/application/embeddable/grid/_dashboard_grid.scss
src/plugins/dashboard/public/application/embeddable/grid/dashboard_grid.tsx
src/plugins/dashboard/public/application/lib/save_dashboard.ts
src/plugins/dashboard/public/application/utils/get_nav_actions.tsx

Fix the remaining functional tests. 
Fix dashboard state functional test: https://github.com/opensearch-project/OpenSearch-Dashboards/blob/1560a6c4e37013649d049dfa4569f4329e0d0118/test/functional/apps/dashboard/dashboard_state.js
and legacy URL functional test: https://github.com/opensearch-project/OpenSearch-Dashboards/blob/1560a6c4e37013649d049dfa4569f4329e0d0118/test/functional/apps/dashboard/legacy_urls.ts
by adding a history change after successfully saving a dashboard.
Also fix the expanded panels by importing the scss file.

[Dashboard De-Angular] Fix remaining functional test

---

CHANGELOG.md
COMMUNICATIONS.md
src/plugins/dashboard/public/plugin.tsx

* Update main menu to display 'Dashboards' for consistency. Fixes #4296 This resolves the inconsistency highlighted in issue #4296 (https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4296). The decision to make this change was made in issue #68 (https://github.com/opensearch-project/ux/issues/68)."
* Update OpenSearch Dashboard to OpenSearch Dashboards for consistence
* CHANGELOG.md update
---------
Signed-off-by: Danila Gulderov <gulderov@ya.ru>
(cherry picked from commit bbf8dfbe4fec15e94d72d6f473049456fbe07b46)

[Manual][Backport 2.x]Update main menu to display 'Dashboards' for consistency (#4453)

---

src/plugins/saved_objects_management/public/management_section/object_view/saved_object_view.tsx
src/plugins/saved_objects_management/public/triggers/saved_object_delete_trigger.ts
src/plugins/vis_augmenter/public/actions/saved_object_delete_action.ts
src/plugins/visualizations/public/embeddable/visualize_embeddable.ts
src/plugins/visualize/public/application/components/visualize_listing.tsx

Adding TODOs for followup related to #4499

Add TODOs regarding saved obj cleanup/deletion

---

CHANGELOG.md
packages/osd-opensearch-archiver/package.json
packages/osd-opensearch-archiver/src/actions/empty_opensearch_dashboards_index.ts
packages/osd-opensearch-archiver/src/actions/load.ts
packages/osd-opensearch-archiver/src/actions/save.ts
packages/osd-opensearch-archiver/src/actions/unload.ts
packages/osd-opensearch-archiver/src/cli.ts
packages/osd-opensearch-archiver/src/lib/docs/generate_doc_records_stream.test.ts
packages/osd-opensearch-archiver/src/lib/docs/generate_doc_records_stream.ts
packages/osd-opensearch-archiver/src/lib/docs/index_doc_records_stream.test.ts
packages/osd-opensearch-archiver/src/lib/docs/index_doc_records_stream.ts
packages/osd-opensearch-archiver/src/lib/docs/test_stubs.ts
packages/osd-opensearch-archiver/src/lib/indices/create_index_stream.test.ts
packages/osd-opensearch-archiver/src/lib/indices/create_index_stream.ts
packages/osd-opensearch-archiver/src/lib/indices/delete_index.ts
packages/osd-opensearch-archiver/src/lib/indices/delete_index_stream.ts
packages/osd-opensearch-archiver/src/lib/indices/generate_index_records_stream.test.ts
packages/osd-opensearch-archiver/src/lib/indices/generate_index_records_stream.ts
packages/osd-opensearch-archiver/src/lib/indices/opensearch_dashboards_index.ts
packages/osd-opensearch-archiver/src/lib/indices/test_stubs.ts
packages/osd-opensearch-archiver/src/opensearch_archiver.ts
test/common/services/opensearch_archiver.ts

Manual Backport https://github.com/opensearch-project/OpenSearch-Dashboards/commit/a44b09fd9f81ca1a10909a81b3a553a5c37e1617 from https://github.com/opensearch-project/OpenSearch-Dashboards/pull/4142.
In 2.x branch we are currently using opensearch-js client of v1.1.0 unlike main with v2.2.0 and hence updated osd-opensearch-archiver package to match other packages and refactored from legacy elastic search client to opensearch-js client v1.1.0.

[Manual][Backport 2.x]Migrate from legacy elasticsearch client to opensearch-js client in `osd-opensearch-archiver` package

---

CHANGELOG.md
src/plugins/dashboard/public/application/app.tsx
src/plugins/dashboard/public/application/components/dashboard_editor.tsx
src/plugins/dashboard/public/application/components/dashboard_top_nav.tsx
src/plugins/dashboard/public/application/embeddable/grid/_dashboard_grid.scss
src/plugins/dashboard/public/application/embeddable/grid/dashboard_grid.tsx
src/plugins/dashboard/public/application/top_nav/get_top_nav_config.ts
src/plugins/dashboard/public/application/utils/get_dashboard_instance.tsx
src/plugins/dashboard/public/application/utils/use/use_dashboard_container.tsx
src/plugins/dashboard/public/application/utils/use/use_saved_dashboard_instance.ts
src/plugins/dashboard/public/dashboard.ts
src/plugins/dashboard/server/saved_objects/migrations_730.test.ts

Fix linter and some clean ups.

[Dashboard De-Angular] Initial clean up and linter fix

---

.github/workflows/build_and_test_workflow.yml
CHANGELOG.md
TESTING.md
src/dev/jest/config.js

Split build and verify into parallel jobs
* Also made linter and NOTICE validation run only on Linux

[CI] Split build and verify into parallel jobs

---

src/plugins/dashboard/public/application/embeddable/_dashboard_container.scss
src/plugins/dashboard/public/application/embeddable/dashboard_container.tsx
src/plugins/dashboard/public/application/embeddable/grid/_dashboard_grid.scss
src/plugins/dashboard/public/application/embeddable/grid/dashboard_grid.tsx
src/plugins/dashboard/public/application/utils/create_dashboard_app_state.tsx
src/plugins/dashboard/public/application/utils/get_nav_actions.tsx
src/plugins/dashboard/public/application/utils/use/use_dashboard_container.tsx

Fix cypress for dashboard deangular.

[Dashboard De-Angular] Cypress fix

---

CHANGELOG.md
src/plugins/vis_augmenter/public/utils/utils.test.ts
src/plugins/vis_augmenter/public/utils/utils.ts
src/plugins/vis_augmenter/public/vega/helpers.test.ts
src/plugins/vis_augmenter/public/vega/helpers.ts

Adds unit tests to a few helper functions that were added later, that were missed in unit testing.
Removes unused fn in a helper file as well.

[Vis Augmenter Add UT for few fns

---

CHANGELOG.md
src/plugins/vis_augmenter/public/view_events_flyout/components/styles.scss
src/plugins/vis_augmenter/public/view_events_flyout/components/view_events_flyout.tsx

Update base vis height in view events flyout. Before, the base vis, when viewing the flyout on a normal laptop screen, would cut off the bottom part of the x-axis due to the styling and spacing params. This updates that a few ways:
1. Shrinks the bottom timeline vis by 10px to allocate more overall vertical space
2. Changes the ratio of the base vis and event vis panels from 5:5 to 7:3 so it can take up more vertical space when viewed in a smaller window
3. Sets the max height of the base vis panel to `40vh` so it doesn't grow too much when viewed in a bigger window.

[Vis Augmenter] Update base vis height in view events flyout

---

src/plugins/dashboard/public/application/app.tsx
src/plugins/dashboard/public/application/components/dashboard_listing.tsx
src/plugins/dashboard/public/application/index.tsx
src/plugins/dashboard/public/application/utils/breadcrumbs.ts
src/plugins/dashboard/public/application/utils/create_dashboard_app_state.tsx
src/plugins/dashboard/public/application/utils/get_dashboard_instance.tsx
src/plugins/dashboard/public/application/utils/use/use_chrome_visibility.ts
src/plugins/dashboard/public/application/utils/use/use_dashboard_app_state.tsx
src/plugins/dashboard/public/application/utils/use/use_saved_dashboard_instance.ts
src/plugins/dashboard/public/dashboard.ts

`renderEmpty` was not being set prior to the current container was being dispatched. Moved the set state to after the functions are defined.
Also, clean up license headers for new files to use the correct license headers.

Set dashboard container functions and fix license headers

---

CHANGELOG.md
src/dev/build/tasks/nodejs/node_download_info.ts

Node.js has removed the domain `mirrors.nodejs.org` and their advertised download URL has been from `nodejs.org` for some time now.

Fix Node.js download link

---

CHANGELOG.md
src/plugins/vis_augmenter/server/routes/stats_helpers.test.ts
src/plugins/vis_augmenter/server/routes/stats_helpers.ts

After refactoring of `augment-vis` obj attributes, there was a miss when collecting the vis ID counts in the `stats` API. This updates it to fetch it properly from the `references` section of the saved obj.
Testing on a local cluster after adding some associations of anomaly detectors to 2 different visualizations:
Before:
```
curl localhost:5601/api/vis_augmenter/stats
{"total_objs":3,"obj_breakdown":{"origin_plugin":{"anomalyDetectionDashboards":3},"plugin_resource_type":{"Anomaly Detectors":3},"plugin_resource_id":{"S-RAUIkBCKX6lNDQOxH6":2,"U-RAUIkBCKX6lNDQUxGG":1},"visualization_id":{"undefined":3}}}
```
After:
```
curl localhost:5601/api/vis_augmenter/stats
{"total_objs":3,"obj_breakdown":{"origin_plugin":{"anomalyDetectionDashboards":3},"plugin_resource_type":{"Anomaly …
```

[Vis Augmenter] Fix stats API visualization ID bug

---

src/plugins/vis_augmenter/public/test_constants.ts
src/plugins/vis_augmenter/public/vega/helpers.test.ts
src/plugins/vis_augmenter/public/vega/helpers.ts

Fix bug of undefined tooltip when all plugin layers are empty. There is a certain scenario where if one plugin has events (such that there is an event datapoint on a chart), but all VisLayers coming from a different plugin all have empty events, the tooltip will show as `undefined` for that plugin. This is because the existing logic blocks the population of `0` values into the source datatable. The fix is to remove that logic so it is always run. The original reason it had existed there was due to different ways of experimenting how to show the tooltips on the chart. With the final solution using default vega tooltip logic, the non-defined values in the source datatable unfortunately default to `undefined` using vega.
After:

[Vis Augmenter] Fix bug of undefined tooltip when all plugin layers are empty

---

src/plugins/data_explorer/opensearch_dashboards.json
src/plugins/data_explorer/public/application.tsx
src/plugins/data_explorer/public/components/app.tsx
src/plugins/data_explorer/public/components/app_container.tsx
src/plugins/data_explorer/public/index.scss
src/plugins/data_explorer/public/plugin.ts
src/plugins/data_explorer/public/services/view_service/types.ts
src/plugins/data_explorer/public/types.ts
src/plugins/discover/common/index.ts
src/plugins/discover/public/application/view_components/canvas/canvas.tsx
src/plugins/discover/public/application/view_components/canvas/index.tsx
src/plugins/discover/public/application/view_components/canvas/top_nav.tsx
src/plugins/discover/public/application/view_components/panel/index.tsx
src/plugins/discover/public/application/view_components/panel/panel.tsx
src/plugins/discover/public/index.ts
src/plugins/discover/public/plugin.ts
src/plugins/discover/server/ui_settings.ts
src/plugins/discover_legacy/opensearch_dashboards.json
src/plugins/discover_legacy/public/application/angular/discover.js
src/plugins/discover_legacy/public/plugin.ts

Adds toggle between Discover 2.0 and Legacy Discover
https://github.com/opensearch-project/OpenSearch-Dashboards/assets/20453492/1a52f3e8-b95a-4c70-80c6-04036d10c852

[Data Explorer] Adds toggle between legacy and new discover

---

CHANGELOG.md
src/plugins/saved_objects/public/saved_object/saved_object_loader.ts
src/plugins/vis_augmenter/public/saved_augment_vis/saved_augment_vis.ts
src/plugins/vis_augmenter/public/utils/utils.test.ts
src/plugins/vis_augmenter/public/utils/utils.ts
src/plugins/visualizations/public/embeddable/visualize_embeddable.ts

This PR provides optimizations to the saved object loader calls made in the vis embeddable. Specifically, when fetching the saved objects, it adds arguments to the query to filter by matching plugin resource IDs, when applicable. Before, all objects were returned and post-processing filtering was done. Now, we leverage OpenSearch to handle the filtering for us.
To make this change, a new optional argument has been added to the `findAll()` function to specify the search fields. Before, it was hardcoded to name and description. Now, we want to search on the `pluginResource.id` field such that we only return objects that match the input resource IDs.
This fix provides massive performance improvements when rendering the View Events flyout. Specifically, it prevents `n^2 - n` objects being …

Add resource ID filtering in fetch `augment-vis` obj queries

---

CHANGELOG.md
src/core/public/styles/_ace_overrides.scss
src/plugins/vis_default_editor/public/components/controls/raw_json.tsx
src/plugins/vis_type_timeseries/public/application/components/markdown_editor.js
src/plugins/vis_type_timeseries/public/application/components/panel_config/markdown.js

Fixes inconsistent code editor theming, particularly in dark mode. The vast majority of code editor components in OpenSearch Dashboards still use the deprecated `EuiCodeEditor` component, which is built around Ace editor. To enable dark mode theming, there are a series of ace editor SCSS style overrides, but these were only applied to children of the `application` class, which excluded editors in popovers or other portaled components. And TSVB used the `github` theme, which lacks dark mode overrides.
1. Use "textmate" theme everywhere
2. Update override selector to apply to root, to style portal-ed components, too (such as filter editor)
Data plugin edit filter DSL:
Default editor advanced json field:
TSVB markdown editor:
TSVB markdown custom CSS:
These are all the views that use the …

Fix (styles): Make ace code editor themes consistent

---

package.json

Increment the version on the parent branch (2.x) to the next development iteration (2.10) after 2.9 branch cut.
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4486

Version increment from 2.9 to 2.10

---

CHANGELOG.md

Add 2.9.0 release notes into changelog file
Follow-up task of https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4486

Chore(CHANGELOG): Update to CHANGELOG post 2.9 release

---

CHANGELOG.md
packages/osd-optimizer/package.json
packages/osd-optimizer/src/worker/webpack.config.ts
packages/osd-ui-framework/Gruntfile.js
packages/osd-ui-framework/dist/kui_dark.css
packages/osd-ui-framework/dist/kui_light.css
packages/osd-ui-framework/dist/kui_next_dark.css
packages/osd-ui-framework/dist/kui_next_light.css
packages/osd-ui-framework/package.json
packages/osd-ui-shared-deps/package.json
packages/osd-ui-shared-deps/webpack.config.js
yarn.lock

When CSS and SCSS files are combined in OSD, all of the copyright headers are retained. This ends up creating artifacts that are riddled with numerous duplicate copyright headers. `comment-stripper` is employed to ethically hoist a single copy of all copyright headers used in an artifact, resulting in smaller payloads.

Reduce the amount of comments in compiled CSS and bundled CSS-in-JS

---

CHANGELOG.md
src/plugins/dashboard/public/application/utils/breadcrumbs.test.tsx
src/plugins/dashboard/public/application/utils/create_dashboard_app_state.test.tsx

More unit tests for utils folder.
#4640

[Dashboard De-Angular] Add more unit tests for utils folder

---

packages/osd-ui-framework/src/global_styling/variables/_font.scss
src/plugins/maps_legacy/public/map/_custom_button.scss
src/plugins/maps_legacy/public/map/_leaflet_overrides.scss
src/plugins/maps_legacy/public/map/_legend.scss
src/plugins/maps_legacy/public/map/index.scss

Follow-up from https://github.com/opensearch-project/OpenSearch-Dashboards/pull/4658. We realized that there were usages of `--font-text` that included extraneous quotes. In addition to fixing, I added a couple additional overrides so that attribution, legend, and draw button text all use the correct theme font.
I was unable to reproduce any scenario where the `.leaflet-control-layers-expanded` class exists, so didn't verify that usage. Similarly, I searched but found no evidence that any components use a class that inherits the `$kuiFontFamily` SASS var, so I couldn't verify.
The draw buttons, legend, and attribution label (bottom right) all are using the correct theme font:

Fix --font-text CSS var usage and add more leaflet font overrides

---

.lycheeexclude

backport 497878642c43b5b07812ee24cf0079145139e73c from #4171

[Manual Backport 1.x] chore (lychee): Add company.net to exclusion list (#4171)

---

CHANGELOG.md
src/core/server/legacy/legacy_service.ts
src/core/server/plugins/plugin_context.ts
src/core/server/saved_objects/saved_objects_service.mock.ts
src/core/server/saved_objects/saved_objects_service.test.ts
src/core/server/saved_objects/saved_objects_service.ts

Provides more flexible interface so that user can customize saved object service status based on their chosen storage option. 
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4655

Add saved objects service status api

---

CHANGELOG.md
packages/osd-optimizer/package.json
packages/osd-optimizer/src/worker/webpack.config.ts
packages/osd-ui-framework/Gruntfile.js
packages/osd-ui-framework/dist/kui_dark.css
packages/osd-ui-framework/dist/kui_light.css
packages/osd-ui-framework/dist/kui_next_dark.css
packages/osd-ui-framework/dist/kui_next_light.css
packages/osd-ui-framework/package.json
packages/osd-ui-shared-deps/package.json
packages/osd-ui-shared-deps/webpack.config.js
yarn.lock

Backport 4bc1f55cf3e674a29bb2d18277ab143399b1131f from #4648

[Backport 2.x] Reduce the amount of comments in compiled CSS

---

CHANGELOG.md

1.3.12 Post release activity to update changelog.md file. Also add missing 1.3.11 release changes.

[Chore] Update CHANGELOG.md with 1.3.12 release changes

---

CHANGELOG.md
package.json
yarn.lock

Bump version of tinygradient from 0.4.3 to 1.1.5. The public API had no changes, and relevant tests pass.
Fixes #4730

Bump version of tinygradient from 0.4.3 to 1.1.5

---

test/functional/apps/dashboard/dashboard_state.js
test/functional/apps/dashboard/dashboard_time_picker.js
test/functional/apps/dashboard/index.js

Fix the failed dashboard functional test for discover. 
Need to add a line `await PageObjects.discover.loadSavedSearch('my search');` as a workaround since the discover link won't take it to the previously accessed saved search page link, it will only take it to the discover page. The issue is documented here: https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4698#issuecomment-1672592217
Since we plan to get rid of legacy discover soon, this should not be a problem.

[Data Explorer] Fix dashboard test for legacy discover

---

src/plugins/discover/public/application/components/data_grid/data_grid_table.tsx
src/plugins/discover/public/application/utils/state_management/common.test.ts
src/plugins/discover/public/application/utils/state_management/common.ts
src/plugins/discover/public/application/utils/state_management/discover_slice.test.tsx
src/plugins/discover/public/application/utils/state_management/discover_slice.tsx
src/plugins/discover/public/application/view_components/canvas/discover_table.tsx

[Data Explorer][Discover 2.0] Implement column actions

---

release-notes/opensearch-dashboards.release-notes-1.3.10.md
release-notes/opensearch-dashboards.release-notes-1.3.11.md
release-notes/opensearch-dashboards.release-notes-1.3.12.md
release-notes/opensearch-dashboards.release-notes-1.3.2.md
release-notes/opensearch-dashboards.release-notes-1.3.3.md
release-notes/opensearch-dashboards.release-notes-1.3.5.md
release-notes/opensearch-dashboards.release-notes-1.3.6.md
release-notes/opensearch-dashboards.release-notes-1.3.9.md

Add missing 1.3.x patch release notes to 2.x branch
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4646

Add missing 1.3.x patch release notes to 2.x branch

---

src/plugins/discover/public/application/components/data_grid/data_grid_table.tsx
src/plugins/discover/public/application/components/loading_spinner/loading_spinner.scss
src/plugins/discover/public/application/components/loading_spinner/loading_spinner.tsx
src/plugins/discover/public/application/components/no_results/no_results.tsx
src/plugins/discover/public/application/components/sidebar/discover_field.tsx
src/plugins/discover/public/application/components/sidebar/discover_sidebar.scss
src/plugins/discover/public/application/components/sidebar/discover_sidebar.tsx
src/plugins/discover/public/application/components/top_nav/get_top_nav_links.tsx
src/plugins/discover/public/application/components/top_nav/open_search_panel.test.tsx
src/plugins/discover/public/application/view_components/canvas/discover_chart_container.tsx
src/plugins/discover/public/application/view_components/canvas/index.tsx
src/plugins/discover/public/application/view_components/utils/use_search.ts
src/plugins/discover_legacy/public/application/angular/discover.js
src/plugins/navigation/public/top_nav_menu/top_nav_menu_data.tsx
src/plugins/navigation/public/top_nav_menu/top_nav_menu_item.tsx

This PR adds views for Loading and No results along with many other fixes such as:
1. variable row height based on selected columns i.e. when source is the only column, multiple rows are displayed
2. Fixes legacy discover styles from affecting discover 2.0
3. Adds switch button for legacy new discover toggle

[Data Explorer] Altrnate result state views + fixes

---

src/plugins/dashboard/public/application/utils/breadcrumbs.ts

Eliminate duplicate dashboard breadcrumb text ID
resolves #4794

Eliminate duplicate dashboard breadcrumb text ID

---

CHANGELOG.md
src/core/public/plugins/plugins_service.test.ts
src/core/server/plugins/discovery/plugin_manifest_parser.test.ts
src/core/server/plugins/discovery/plugin_manifest_parser.ts
src/core/server/plugins/integration_tests/plugins_service.test.ts
src/core/server/plugins/plugin.test.ts
src/core/server/plugins/plugin.ts
src/core/server/plugins/plugin_context.test.ts
src/core/server/plugins/plugins_service.test.ts
src/core/server/plugins/plugins_system.test.ts
src/core/server/plugins/plugins_system.ts
src/core/server/plugins/types.ts

This PR is an enhancement to the already existing plugin manifest ability to allow defining backend OpenSearch plugin dependencies. As part of decoupling Dashboards with OpenSearch Dashboards plugins and then with OpenSearch, we need a way to establish Dashboards plugin dependency with its counter part. 
This PR adds following changes -
* Modifying existing manifest config key `requiredOpenSearchPlugins` to define list of OpenSearch Plugin object and its version compatibility with that plugin.
* In the first iteration we can define version range in semver format only. 
* Compatible version defined in the manifest should be a valid version range.
* Validates if version compatible plugin is installed on the cluster or not.
* In this initial implementation, we are only logging the warning if …

[Decouple] Allow plugin manifest config to define semver compatible OpenSearch plugin and verify if it is installed on the cluster

---

.github/workflows/build_and_test_workflow.yml
scripts/bwc/opensearch_service.sh

The BWC tests on 2.x are failing: https://github.com/opensearch-project/OpenSearch-Dashboards/actions/runs/5895740470/job/16189125311.
BWC test files: https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/.github/workflows/build_and_test_workflow.yml#L349 utilize the release artifact which is built by a configuration sent externally. If there are issues in the build release for OpenSearch then we will be impacted, where snapshot is built more frequently.
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4814

[CI] Fix BWC related CI failures by swapping dist url with snapshot url

---

src/plugins/discover/public/application/components/chart/chart.tsx
src/plugins/discover/public/application/utils/state_management/discover_slice.tsx
src/plugins/discover/public/application/view_components/canvas/discover_table.tsx
src/plugins/discover/public/application/view_components/utils/use_search.ts

This PR is blocked by https://github.com/opensearch-project/OpenSearch-Dashboards/pull/4806
We currently decide to move from feature branch to main for all following fixes. After https://github.com/opensearch-project/OpenSearch-Dashboards/pull/4806 is merged, I will rebase the PR and remove draft.
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4847
Allow discover 2.0 histogram to update according to interval change.

[Data Explorer][Discover 2.0] Add missing change interval on TimeChart and improve fetch

---

src/plugins/discover/public/application/components/data_grid/constants.ts
src/plugins/discover/public/application/components/data_grid/data_grid_table.tsx
src/plugins/discover/public/application/components/data_grid/data_grid_table_columns.tsx
src/plugins/discover/public/application/components/doc_views/context_app.tsx
src/plugins/discover/public/application/utils/state_management/common.ts
src/plugins/discover/public/application/utils/state_management/discover_slice.tsx
src/plugins/discover/public/application/view_components/canvas/discover_table.tsx

* disable full screen mode (see investigation from https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4824). 
* customize hide column to delete column
* add move left and move right
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4822 
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4823 
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4824

[Data Explorer][Discover 2.0] Replace hide column and add move left/right

---

CHANGELOG.md
src/plugins/discover/public/application/view_components/canvas/index.tsx
src/plugins/discover_legacy/public/application/components/discover_legacy.tsx

Add callout for both legacy discover and data explorer to warn users.
https://github.com/opensearch-project/OpenSearch-Dashboards/assets/43937633/8c73abb7-df48-4672-9063-dce7954e2655

[Data Explorer] Add dismissible callout for discover

---

CHANGELOG.md
src/plugins/discover/public/application/components/chart/_histogram.scss
src/plugins/discover/public/application/components/chart/chart.tsx

Fix darkmode for histogram. Previously after switching to darkmode, histogram still have light mode color scheme.
https://github.com/opensearch-project/OpenSearch-Dashboards/assets/43937633/ff12ff69-9513-474e-a585-31036f444806

[Data Explorer] Fix darkmode for histogram

---

src/plugins/discover/public/application/components/data_grid/data_grid_table_columns.test.tsx
src/plugins/discover/public/application/components/doc_viewer_links/__snapshots__/doc_viewer_links.test.tsx.snap
src/plugins/discover/public/application/components/doc_viewer_links/doc_viewer_links.tsx
src/plugins/discover/public/application/utils/state_management/common.test.ts
src/plugins/discover/public/application/utils/state_management/discover_slice.test.tsx

https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4825

[Data Explorer][Discover 2.0] Append popout icon to oui link for doc viewer links

---

src/plugins/discover/public/application/components/sidebar/lib/get_index_pattern_field_list.ts
src/plugins/discover/public/application/view_components/canvas/index.tsx
src/plugins/discover/public/application/view_components/utils/filter_columns.test.ts
src/plugins/discover/public/application/view_components/utils/filter_columns.ts

* side nav only shows the selected index pattern fields after switch index pattern
* allow reset column state when switch index pattern
There are two conditions: 1) If there is common field, common field will be saved. 
2) if no common field, will show `_source` after switch
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4840 https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4846

[Data Explorer][Discover 2.0] Fix issues when change index pattern

---

src/plugins/data/public/ui/typeahead/_suggestion.scss

Icons don't need to be as high contrast as text, so the 3:1 threshold of `makeGraphicContrastColor` is more appropriate
fixes #4628 
These styles aren't actually currently used, because we don't have full typeahead support available in the query bar, except for historical queries. But I've manually updated some of the suggestions with the 4 color style classes affected by this change. The colors themselves haven't changed, but it fixes the error. **Note that this change is only for the color variants - the contrast for the grayscale ones are probably worse, but defined elsewhere**:
Before:
```
np bld    log   [21:29:23.956] [info][@osd/optimizer] starting worker [1 bundle]
np bld    log   [21:29:27.418] [warning][@osd/optimizer] worker stderr WARNING: High enough contrast could not be …
```

Change color fn used to calculate icon colors for search typeahead 

---

src/plugins/discover/public/application/components/chart/chart.tsx
src/plugins/discover/public/application/components/doc_views/context_app.tsx
src/plugins/discover/public/application/view_components/canvas/discover_chart_container.tsx
src/plugins/discover/public/application/view_components/canvas/discover_table.tsx
src/plugins/discover/public/application/view_components/canvas/top_nav.tsx

This PR is blocked by https://github.com/opensearch-project/OpenSearch-Dashboards/pull/4816
Please see the 2nd commit. Need to rebase after https://github.com/opensearch-project/OpenSearch-Dashboards/pull/4816 is merged.
* Before
* After
no date picker in the top nav
only show hits if index pattern has no time field
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4820

[Data Explorer][Discover 2.0] Fix display for index pattern without a default time field

---

CHANGELOG.md
src/plugins/charts/public/services/colors/colors.ts
src/plugins/charts/public/services/colors/mapped_colors.ts

Instead of trying to generate unique colors for an entire dashboard.
Visualizations that use the color mapper (VisLib, VisBuilder, TSVB) will now have the following behavior:
1. Every visualization will preferentially use the colors from [the OUI qualitative palette](https://oui.opensearch.org/1.2/#/utilities/color-palettes). Only if there are more than 10 colors needed for a single visualization, additional colors will be generated via rotations of that palette. (new feature)
2. Mapped colors on dashboards are no longer subject to race conditions, where multiple loads of the same dashboard would result in different mapped colors. That means dashboard colors are stable and there's no need to manually specify colors just to achieve consistency. (new feature)
3. Series labels that appear in …

[Vis Colors] Update color mapper to prioritize unique colors per vis

---

CHANGELOG.md
src/core/types/capabilities.ts
src/plugins/opensearch_dashboards_react/public/overview_page/overview_page_footer/overview_page_footer.tsx
src/plugins/vis_augmenter/public/ui_actions_bootstrap.ts

Then `management.enabled: false` is set in the config, the app now correctly loads without breaking.
fixes #4671
set `management.enabled: false` in the config file and startup OSD. All the pages should be working while the management pages are disabled.

Fixes broken app when management is turned off

---

CHANGELOG.md
package.json
scripts/postinstall.js

Remove examples and other unwanted artifacts from installed dependencies using a postinstall script.
List of folders that will be deleted:
```
% find node_modules -type d -name "demo"
node_modules/opentracing/lib/examples/demo
node_modules/opentracing/src/examples/demo
node_modules/argparse/node_modules/sprintf-js/demo
node_modules/leaflet.heat/demo
node_modules/grunt-peg/node_modules/argparse/node_modules/sprintf-js/demo
node_modules/leaflet-vega/demo
node_modules/grunt-run/node_modules/argparse/node_modules/sprintf-js/demo
node_modules/tinycolor2/demo
node_modules/grunt-available-tasks/node_modules/argparse/node_modules/sprintf-js/demo
% find node_modules -type d -name "example" 
node_modules/@types/http-aws-es/node_modules/is-typed-array/node_modules/object-inspect/example …
```

Remove examples and other unwanted artifacts from installed dependencies

---

CHANGELOG.md
src/plugins/advanced_settings/public/management_app/components/field/field.test.tsx
src/plugins/advanced_settings/public/management_app/components/form/form.test.tsx
src/plugins/advanced_settings/public/management_app/components/search/search.test.tsx
src/plugins/advanced_settings/public/management_app/components/search/search.tsx
src/plugins/data/public/ui/shard_failure_modal/shard_failure_open_modal_button.test.tsx
src/plugins/discover/public/application/components/chart/hits_counter/hits_counter.test.tsx
src/plugins/discover/public/application/components/chart/timechart_header/timechart_header.test.tsx
src/plugins/discover/public/application/components/doc/doc.test.tsx
src/plugins/discover/public/application/components/doc_viewer/doc_viewer.test.tsx
src/plugins/discover/public/application/components/loading_spinner/loading_spinner.test.tsx
src/plugins/discover/public/application/components/table/table.test.tsx
src/plugins/discover_legacy/public/application/angular/context/components/action_bar/action_bar.test.tsx
src/plugins/discover_legacy/public/application/angular/doc_table/components/pager/tool_bar_pager_buttons.test.tsx
src/plugins/discover_legacy/public/application/angular/doc_table/components/table_header/table_header.test.tsx
src/plugins/discover_legacy/public/application/components/context_error_message/context_error_message.test.tsx
src/plugins/embeddable/public/lib/embeddables/embeddable_root.test.tsx
src/plugins/embeddable/public/lib/panel/embeddable_panel.test.tsx
src/plugins/embeddable/public/lib/panel/panel_header/panel_actions/add_panel/add_panel_flyout.test.tsx
src/plugins/input_control_vis/public/components/editor/controls_tab.test.tsx
src/plugins/input_control_vis/public/components/editor/list_control_editor.test.tsx
src/plugins/input_control_vis/public/components/editor/range_control_editor.test.tsx
src/plugins/input_control_vis/public/components/vis/input_control_vis.test.tsx

cherrypick 0e25f2e6e0e906e2474e513a6784be9ac63b26da from #3798

[Manual Backport 2.x][CCI] Fix EUI/OUI type errors (#3798)

---

src/plugins/discover/public/application/view_components/canvas/index.tsx
src/plugins/discover_legacy/public/application/components/discover_legacy.tsx

Modify the call out texts based on UX input.

Modify call out text for discover

---

CHANGELOG.md
packages/osd-ui-shared-deps/theme.ts
src/core/server/rendering/views/fonts.tsx
src/core/server/rendering/views/styles.tsx
src/core/server/rendering/views/template.tsx
src/core/server/rendering/views/theme.ts

Use themes' definitions to render the initial view. This impacts the loading screen font and colors.

Use themes' definitions to render the initial view.

---

CHANGELOG.md
package.json
packages/osd-ui-framework/package.json
packages/osd-ui-shared-deps/package.json
test/interpreter_functional/plugins/osd_tp_run_pipeline/package.json
test/plugin_functional/plugins/osd_sample_panel_action/package.json
test/plugin_functional/plugins/osd_tp_custom_visualizations/package.json
yarn.lock

Bump OUI to `1.3.0`
fixes https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4584

Bump OUI to `1.3.0`

---

packages/osd-stylelint-config/config/global_selectors.json
src/plugins/data_explorer/public/components/sidebar/index.tsx
src/plugins/discover/public/application/components/data_grid/data_grid_table_cell_value.scss
src/plugins/discover/public/application/components/data_grid/data_grid_table_cell_value.test.tsx
src/plugins/discover/public/application/components/data_grid/data_grid_table_cell_value.tsx
src/plugins/discover/public/application/view_components/canvas/index.tsx
src/plugins/discover_legacy/public/application/components/discover_legacy.tsx

Fixes some small styling issues identified by @KrooshalUX and @kgcreative when reviewing `next` theming
1. Fix `onDismiss` prop of callout
2. Put callout in panel for better alignment in discover
3. Add `subdued` to combobox panel
4. Use `primary`-derived color for field titles in discover (and lint-ignore)
Note - I tried to fix the histogram rect highlight color in `next` dark mode, but can't figure out the problem. I got as far as confirming that both `discover` and `legacy_discover` pass the same styling props, but somehow it's not applied the same in each case.
I also notices some other minor fit and finish issues in the video:
1. Layout jank when hovering on the source, as the inline text adjusts its width to make room for the expand button
2. Loading spinner sometimes overlaps …

Fix (discover): Fix dismiss callout and next styling

---

.lycheeexclude
CHANGELOG.md
src/cli_plugin/install/settings.js
src/cli_plugin/install/settings.test.js

When OSD plugins are installed by their name, irrespective of the platform:
* the url path has `/tar` hard-coded,
* the url points to a zip file, even though the path is under `/tar`.
However, experimenting with the URLs, these two worked for me:
* https://ci.opensearch.org/ci/dbc/distribution-build-opensearch-dashboards/2.9.0/latest/windows/x64/zip/builds/opensearch-dashboards/plugins/anomalyDetectionDashboards-2.9.0.zip
* https://ci.opensearch.org/ci/dbc/distribution-build-opensearch-dashboards/2.9.0/latest/linux/x64/tar/builds/opensearch-dashboards/plugins/anomalyDetectionDashboards-2.9.0.zip
This indicates that Windows plugins are not in fact placed in `/tar/` but are placed in `/zip/`.
Fixes #4952

Correct the generated path for downloading plugins by their names on Windows

---

CHANGELOG.md
src/plugins/console/public/application/components/__snapshots__/import_flyout.test.tsx.snap
src/plugins/console/public/application/components/__snapshots__/import_mode_control.test.tsx.snap
src/plugins/console/public/application/components/__snapshots__/overwrite_modal.test.tsx.snap
src/plugins/console/public/application/components/import_flyout.test.tsx
src/plugins/console/public/application/components/import_flyout.tsx
src/plugins/console/public/application/components/import_mode_control.test.tsx
src/plugins/console/public/application/components/import_mode_control.tsx
src/plugins/console/public/application/components/index.ts
src/plugins/console/public/application/components/overwrite_modal.test.tsx
src/plugins/console/public/application/components/overwrite_modal.tsx
src/plugins/console/public/application/containers/editor/legacy/console_editor/editor.tsx
src/plugins/console/public/application/containers/main/get_top_nav.ts
src/plugins/console/public/application/containers/main/main.tsx
src/plugins/console/public/application/contexts/services_context.mock.ts
src/plugins/console/public/application/contexts/services_context.tsx
src/plugins/console/public/application/hooks/use_data_init/use_data_init.ts
src/plugins/console/public/application/hooks/use_send_current_request_to_opensearch/use_send_current_request_to_opensearch.test.tsx
src/plugins/console/public/application/index.tsx
src/plugins/console/public/plugin.ts

Add support for exporting and restoring the history of commands in Dev Tools #3767
https://github.com/opensearch-project/OpenSearch-Dashboards/assets/20453492/1c3d53b9-eb6e-48aa-ae8f-8ba35485e150

Feature: Dev Tools Query Export/Import

---

src/plugins/discover/public/application/components/doc_views/context/utils/use_query_actions.ts
src/plugins/discover/public/application/components/doc_views/single_doc_app.tsx
src/plugins/discover/public/application/view_components/utils/index_pattern_helper.ts
src/plugins/vis_type_vega/public/expressions/line_vega_spec_fn.ts
src/plugins/visualizations/public/embeddable/visualize_embeddable.ts

This is a follow-up fix to https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4794, after the initial bug was solved in [this pr](https://github.com/opensearch-project/OpenSearch-Dashboards/pull/4805). There were 2 additional errors that prevented script from running after I tried to running script later.
```
ERROR  I18N ERROR  Error in src/plugins/vis_type_vega/public/expressions/vega_fn.ts
Error: There is more than one default message for the same id "visTypeVega.function.help":
"Construct line vega spec" and "Vega visualization"
```
```
ERROR  I18N ERROR  Error in src/plugins/visualizations/public/embeddable/visualize_embeddable.ts
Error: expressions are not allowed in template literals ("visualizations.renderVisTitle").
```
I tried running script again after some time …

[Follow-up] Fix extraction script

---

CHANGELOG.md
yarn.lock

CVE-2023-26136
https://github.com/opensearch-project/OpenSearch-Dashboards/pull/4589

[1.3] [CVE-2023-26136] Bump word-wrap from 1.2.3 to 1.2.4

---

CHANGELOG.md
package.json
packages/osd-dev-utils/package.json
packages/osd-release-notes/package.json
yarn.lock

Backport from https://github.com/opensearch-project/OpenSearch-Dashboards/pull/1140. 
With the `SemVer` philosophy, when releasing a patch version, it should not introduce breaking changes, which includes bumping a dependency to its major version. This `markdown-it` is a devDependency and the two major bump doesn't include breaking changes affecting OSD usages. Meanwhile, it is not included in release artifact. 
[CVE-2022-21670](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1135)

[1.3][CVE-2022-21670] Bump markdown-it from 10.0.0 to 12.3.2

---

CHANGELOG.md
package.json
yarn.lock

With the `SemVer` philosophy, when releasing a patch version, it should not introduce breaking changes, which includes bumping a dependency to its major version. 
`got` is a not a direct dependency for OSD. Meanwhile, it is not included in release artifact. Therefore, bumping major versions should not break `SemVer` rules.
This CVE requires to update `got` to `11.8.5` or `12.1.0`. `got` is used in multiple versions:
3.3.1
5.6.0
6.7.1
7.1.0
8.3.2
9.6.0
11.8.2
Hoisted from dependencies "project#latest-version#package-json#got" and "project#@osd#ui-framework#yeoman-generator#github-username#gh-got#got"
* @osd-ui-framework uses yeoman-generator@^4.13.0. This is already the highest node compatible version. yeoman-generator@^5.0.0 requests node>=12: …

[1.3][CVE-2022-33987] Partially fix security issues for got by bumping @elastic/makelogs from 6.0.0 to 6.1.1 and update yarn.lock

---

CHANGELOG.md
packages/osd-ui-framework/package.json
yarn.lock

With the `SemVer` philosophy, when releasing a patch version, it should not introduce breaking changes, which includes bumping a dependency to its major version. 
`yo` is a dev dependency in package `@osd/ui-framework` for OSD. Meanwhile, it is not included in release artifact. Therefore, bumping major versions should not break `SemVer` rules.
Versions of `mem` prior to `4.0.0` are vulnerable to Denial of Service (DoS). `mem` is brought into OSD by` yo#fullname`:
```
ubuntu@ip-**:~/OpenSearch-Dashboards$ yarn why mem
[1/4] Why do we have the module "mem"...?
warning Resolution field "typescript@4.0.2" is incompatible with requested version "typescript@~4.8.4"
=> Found …
```

[1.3] Bump yo from 2.0.6 to 3.1.1

---

CHANGELOG.md
src/plugins/discover/public/application/components/chart/utils/point_series.test.ts

https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4865#issuecomment-1716282502
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4865

[BUG] Fix buildPointSeriesData unit test fails due to local timezone

---

src/plugins/discover/public/application/view_components/canvas/discover_chart_container.tsx
src/plugins/discover/public/application/view_components/canvas/discover_table.tsx
src/plugins/discover/public/application/view_components/canvas/index.tsx
src/plugins/discover/public/application/view_components/panel/index.tsx
src/plugins/discover/public/application/view_components/utils/filter_columns.ts
src/plugins/discover/public/application/view_components/utils/use_search.ts
src/plugins/discover_legacy/public/application/components/discover_legacy.tsx

This fixes 4 small issues:
1. Fixes the add filter in the sidebar for discover 2.0
2. Fixes the deprecation notice not persisting on page refresh
3. Loads the filters and query from a saved search
4. minor type errors.
fixes #5027
https://github.com/opensearch-project/OpenSearch-Dashboards/assets/20453492/36fc7c2c-ddf0-493f-b382-05126c193862
Pull down the changes and open the discover app. Adding filters in the side panel should work. The dismissable callout should stay dismissed after the page refresh.

[Discover 2.0] fixes add filter and dismissible callout

---

DEVELOPER_GUIDE.md

Fixes issue with yarn install step in developer guides
N/A
N/A
@cwperks  and I had run through the developer guide end to end and ran into issues with the current step but re-running with `npm i -g yarn` worked to install the right version of yarn so the dependencies could be installed.

Updating yarn installation step from the Dev guide

---

src/plugins/discover/public/application/components/data_grid/data_grid_table_docview_inspect_button.tsx
src/plugins/discover/public/application/components/data_grid/data_grid_table_flyout.tsx
src/plugins/discover/public/application/components/doc_viewer_links/doc_viewer_links.tsx

Add some necessary `data-test-subj` IDs for cypress tests.
Migrate selemium tests to cypress for data explorer PR: https://github.com/opensearch-project/opensearch-dashboards-functional-test/pull/862
resolves https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5003

Add `data-test-subj` for data explorer cypress test

---

CHANGELOG.md
src/plugins/discover/public/application/components/chart/chart.tsx
src/plugins/discover/public/application/components/doc_viewer_links/__snapshots__/doc_viewer_links.test.tsx.snap
src/plugins/discover/public/application/view_components/canvas/discover_chart_container.tsx

https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5068

[Data Explorer][Discover] Fix total hits issue for no time based data

---

DEVELOPER_GUIDE.md
package.json

Update developer guide after #5065 was merged. I was concerned because everything I've seen says to install yarn through `corepack`, so I did some digging. The old dev guide said to install yarn using the latest version from yarn trunk (v3 something), which would break bootstrap and everything with that. However, OSD is built using yarn v1, which is incompatible with yarn v3. Essentially, there are significant differences between yarn v1 and v3, which make all of the guides in Dashboards break, since they were built for v1 instead of v3. This PR updates the guides to use `corepack`, which is the recommended way to install yarn, but to still install v1.
N/a
N/a
Ran this on Node version 14, 16, and 18 to get yarn v1.22.18 installed and tested clean and bootstrap with that version.

Update yarn install step from dev guide

---

src/plugins/data_explorer/public/components/sidebar/index.tsx
test/functional/apps/management/_handle_alias.js
test/functional/page_objects/discover_page.ts

https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5103
Update index pattern fetch method in discover page due to changing to `EuiComboBox`.

[Data Explorer][Discover][Functional Test] fix ciGroup 8

---

src/plugins/discover/public/application/components/doc_viewer_links/__snapshots__/doc_viewer_links.test.tsx.snap
src/plugins/discover/public/application/components/doc_viewer_links/doc_viewer_links.tsx
test/functional/apps/context/_context_navigation.js
test/functional/apps/context/_date_nanos.js
test/functional/apps/context/_discover_navigation.js
test/functional/apps/context/_filters.js
test/functional/apps/context/_size.js
test/functional/apps/context/index.js
test/functional/apps/management/_scripted_fields.js
test/functional/page_objects/discover_page.ts
test/functional/services/data_grid.ts

Fix all context related functional tests
resolves #5100

Fix cigroup 1 with dataGridTable helper functions

---

test/functional/apps/dashboard/dashboard_filter_bar.js
test/functional/apps/dashboard/dashboard_filtering.js
test/functional/services/dashboard/expectations.ts
test/functional/services/data_grid.ts

Fix functional group 3 failures for save search on dashboard filtering
resolves #5107

[Data Explorer] Fix functional cigroup 3 for save search on dashboard filtering

---

src/plugins/discover/public/application/components/data_grid/data_grid_table.tsx
src/plugins/discover/public/application/view_components/canvas/discover_table.tsx
src/plugins/discover/public/embeddable/search_embeddable.tsx
src/plugins/discover/public/embeddable/search_embeddable_component.tsx
test/functional/apps/dashboard/dashboard_query_bar.js

- Add data-shared-item tags on save search object so the tags get rendered both in discover page and in dashboard page.
- Skip one test because of save search rendering error on dashboard. https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5116
resolves #5118 
resolves #5058

[Data Explorer] Fix ciGroup 2 with adding data-shared-item tags on save search 

---

src/plugins/discover/public/application/view_components/utils/use_search.ts
src/plugins/discover/public/build_services.ts

Fixes the setting `searchOnPageLoad`
> Note: Duplicate of https://github.com/opensearch-project/OpenSearch-Dashboards/pull/5096 since it had some rebasing issues
fixes #5057
https://github.com/opensearch-project/OpenSearch-Dashboards/assets/20453492/6005de3d-cf86-46d9-8f71-4ae805152ac5

[Discover] Search on load fix

---

test/functional/apps/context/_discover_navigation.js
test/functional/apps/management/_index_pattern_results_sort.js
test/functional/apps/management/_opensearch_dashboards_settings.js
test/functional/apps/management/_scripted_fields.js
test/functional/apps/management/_scripted_fields_preview.js
test/functional/page_objects/discover_page.ts
test/functional/services/data_grid.ts

https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5129

[Data Explorer][Discover][Functional Test] Fix ciGroup7

---

.github/workflows/cypress_workflow.yml
CHANGELOG.md

Utilizing the GitHub `workflow_dispatch`, we can trigger a job with a specific inputs.
By default, we run from this repo:
https://github.com/opensearch-project/opensearch-dashboards-functional-test
This workflow uses the target branch of the PR to pull down from the FTRepo and run the tests from that specific branch.
For example, PRs against `main` will pull down `main` from the FTRepo.
The problem occurs when new functionality is opened or a bug is fixed and, per industry standard, we want to see tests added to ensure functionality, stability, and raise the bar.
However, the cypress tests PR into the FTRepo depends on the new code to be merged for the CI within the FTRepo to work. So we have a stalemate that usually slows down PR review time.
Here, a manual run can be triggered by a …

[CI] allow for manual triggered cypress test jobs to accept inputs

---

.github/workflows/cypress_workflow.yml

Originally:
https://github.com/opensearch-project/OpenSearch-Dashboards/pull/5134
I believed it to be a good idea to ensure that triggering the CI should always run a batch of tests. But I realized that some tests can be added and just be bad tests until updated. Or if we want to verify a flaky test in the CI.
So instead of only making it additional tests, the spec input will complete replace the default tests (unless you append to the default).
Empty will run the default spec still. This will append on to the PR comment with the spec that was run. So at least maintainers can see it passed for a set of tests but it did not run the ones we usually run.
Also adding some formatting for empty values for the PR comment.
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4019

[CI] Cypress test run spec input

---

.github/workflows/cypress_workflow.yml
CHANGELOG.md

Set env variable of NODE_OPTIONS for OSD to reference on startup to ensure stable env.
Disable threshold enabled for disk allocation
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4019

[CI][Cypress] set NODE_OPTIONS and cluster disk allocation

---

DEVELOPER_GUIDE.md

In PR #5067, I introduced a change to make the yarn install instructions more consistent. However, they require OSD to be cloned and be the current working directory, which with that version of the dev guide, wasn't the case. This reorders the sections to work properly.

Reoder dev guide for yarn install to work

---

src/core/server/opensearch/client/cluster_client.test.ts
src/core/server/opensearch/client/cluster_client.ts
src/core/server/opensearch/client/configure_client.ts
src/core/server/opensearch/client/mocks.ts
src/core/server/opensearch/client/scoped_cluster_client.test.ts

Enhance support for JSON with long numerals: Followup to #4562
* Improve testing of clients with long numerals support
* Work around serializer inheritance in the JS client

[Console] Enhance support for JSON with long numerals

---

CHANGELOG.md
src/plugins/data_explorer/public/utils/state_management/store.ts
src/plugins/discover/public/application/components/doc_views/surrounding_docs_app.tsx
src/plugins/discover/public/application/components/doc_views/surrounding_docs_view.tsx
src/plugins/discover/public/application/components/sidebar/discover_field.scss
src/plugins/discover/public/application/components/top_nav/get_top_nav_links.tsx
src/plugins/discover/public/application/components/top_nav/open_search_panel.tsx
src/plugins/discover/public/application/helpers/breadcrumbs.ts
src/plugins/discover/public/application/utils/state_management/discover_slice.tsx
src/plugins/discover/public/application/view_components/canvas/discover_chart_container.tsx
src/plugins/discover/public/application/view_components/canvas/index.tsx
src/plugins/discover/public/application/view_components/canvas/top_nav.tsx
src/plugins/discover/public/application/view_components/context/index.tsx
src/plugins/discover/public/application/view_components/utils/use_search.ts
src/plugins/discover/public/opensearch_dashboards_services.ts
src/plugins/opensearch_dashboards_utils/docs/global_data_persistence.md

Noteable fixes here are:
- Replaces history api with application service's navigate method to correctly preserve state during redirection. The changes were made in:
-  Breadcrumbs
- Opening a saved search
- Creating a new saved search
- Adds a hydration action to load a url state into redux if a change to url should update the redux store. This fixes the issue where browser navigation did not update redux state.
> Note: Recreated from #5123 since targeting that branch to main caused some issues during rebase.
closes #5056
closes https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5157
closes https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5066
closes https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5136 …

[Discover] A bunch of navigation fixes

---

CHANGELOG.md
src/plugins/data_explorer/public/index.ts
src/plugins/discover/public/application/utils/state_management/index.ts
src/plugins/discover/public/application/view_components/canvas/discover_table.tsx
src/plugins/discover/public/application/view_components/context/index.tsx
src/plugins/discover/public/application/view_components/utils/use_index_pattern.ts
src/plugins/discover/public/application/view_components/utils/use_search.ts

This fix ensures that when add a default index pattern, Discover will automatically select and load its details.
* before 
https://github.com/opensearch-project/OpenSearch-Dashboards/assets/79961084/1ae2e18d-27fd-494d-ab47-e92903f7c1be
* after
https://github.com/opensearch-project/OpenSearch-Dashboards/assets/79961084/91daa15a-8375-46e8-b83f-2bcb529a60c5
closes https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5128

[BUG][Data Explorer][Discover] Automatically load solo added default index pattern

---

CHANGELOG.md
package.json
src/core/server/legacy/integration_tests/logging.test.ts
yarn.lock

Backport d017c5caddd732fafc1c2a2fc8ca4be99fac7c0b from https://github.com/opensearch-project/OpenSearch-Dashboards/pull/4949

[Manual Backport 2.x] Bump `agentkeepalive` to v4.5.0

---

CHANGELOG.md
src/plugins/discover/public/application/components/data_grid/data_grid_table.tsx
src/plugins/discover/public/application/view_components/canvas/discover_table.tsx
src/plugins/discover/public/application/view_components/canvas/index.tsx

* This PR adds a new rows state to the DiscoverCanvas component and updated it whenever the data$ observable emitted new row data.
* The DiscoverTable component was then refactored to accept rows as a prop, making it dependent on the parent component to provide the correct set of data. This ensures that the table renders correctly based on the current data and doesn't rely on its internal state, which could be outdated.
closes https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5181
https://github.com/opensearch-project/OpenSearch-Dashboards/assets/79961084/427069ee-0311-4f92-ae7f-029f2e79cf7a

[BUG][Data Explorer][Discover] Allow data grid to auto adjust size based on fetched data count

---

src/plugins/data_explorer/public/index.ts
src/plugins/discover/public/application/utils/state_management/index.ts
src/plugins/discover/public/application/view_components/canvas/discover_table.tsx
src/plugins/discover/public/application/view_components/utils/use_index_pattern.ts
src/plugins/discover/public/application/view_components/utils/use_search.ts

Reverts opensearch-project/OpenSearch-Dashboards#5189 to orchestrate merging in a specific order.

Revert "[Backport 2.x] [BUG][Data Explorer][Discover] Automatically load solo added default index pattern"

---

src/plugins/discover/public/application/components/data_grid/data_grid_table.tsx

Add a subject test id for testing `data-shared-attribute` for the discover table.

[Data Explorer] Add subject test id for testing data-shared-attribute

---

.github/workflows/cypress_workflow.yml

https://github.com/opensearch-project/OpenSearch-Dashboards/pull/5134
Incorrectly uses the source of the code to pull down to BASE REF,
which would likely be `main` or `2.x`, etc.
It should be pulling down the PR branch. Cypress tests at the time
of merging were failing due to unrelated issue of disk allocation.
Not setting the env variables causes the workflow to rely on the default
values which is a return back to the original implementation and if the
env is set then it will be not empty.
n/a

[CI][Cypress][Bug] use default `SOURCE` inputs for checkout

---

CHANGELOG.md
src/plugins/discover/public/application/view_components/canvas/top_nav.tsx
src/plugins/discover/public/application/view_components/context/index.tsx

https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5179 
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5071
https://github.com/opensearch-project/OpenSearch-Dashboards/assets/79961084/4648a28d-5a76-4146-a34e-8d51bd7624fc

[BUG][Data Explorer][Discover] Allow filter and query persist when refresh page or paste url to a new tab

---

src/plugins/discover/public/application/view_components/canvas/discover_table.tsx
src/plugins/discover/public/application/view_components/canvas/index.tsx

Fixes a memoization issue with the datatable component that caused unnecessary and expensive rerenders.

[Discover] Fixes DataTable rendering in discover

---

CHANGELOG.md
test/plugin_functional/plugins/doc_views_plugin/public/plugin.tsx
test/plugin_functional/test_suites/doc_views/doc_views.ts

* remove angular-based view from DocViewsPlugin
* remove the test case that validates the display and content of the angular doc view
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5020

[Tests-refactor] Remove angular code from plugin_functional and update tests

---

.github/pull_request_template.md
CHANGELOG.md

Removed ftr test step from PR template
fixes <https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5210>

[OSCI] Remove ftr test from PR template

---

CHANGELOG.md
test/functional/page_objects/time_picker.ts
test/plugin_functional/test_suites/doc_views/doc_views.ts
test/plugin_functional/test_suites/doc_views_links/doc_views_links.ts

* add a helper function setInputValueWithRetry for setAbsoluteRange to retry time range setup
* update doc_views test to click docTableExpandToggleColumn-0
* update doc_views_link to check new tab
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5241
* `test_suites/doc_views`
https://github.com/opensearch-project/OpenSearch-Dashboards/assets/79961084/534be03d-7b8c-4f8d-bbe8-193e93afd797
* `test_suites/doc_views_links`
https://github.com/opensearch-project/OpenSearch-Dashboards/assets/79961084/0093c9df-082e-4a17-b785-a285240801c9

[BUG][Fuctional Test] Make setDefaultAbsoluteRange more robust and update doc views tests

---

src/plugins/discover/public/application/utils/state_management/index.ts
src/plugins/discover/public/application/view_components/utils/use_index_pattern.ts
src/plugins/discover/public/application/view_components/utils/use_search.ts
src/plugins/discover/public/saved_searches/_saved_search.ts
src/plugins/discover/public/saved_searches/types.ts

Fixes accessing saved searches from recently accessed and adding visited saved searches to recently accessed. Also has a few small fixes to the code
fixes #5254
https://github.com/opensearch-project/OpenSearch-Dashboards/assets/20453492/1202a707-1e5e-49b5-b33b-38deda219673
- Go to 'Discover'.
- Add some columns
- Save it.
- Click side nav menu and select saved search from step 2.
- See saved search is loaded.

[Discover] Fixes recently accessed

---

CHANGELOG.md
src/plugins/data/public/data_sources/datasource_selector/datasource_selectable.tsx

Removed Discover datasource selector X icon
fixes https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5229

[Data Explorer] Removed X icon in data source selection.

---

src/plugins/discover/public/application/utils/state_management/discover_slice.tsx
src/plugins/discover/public/application/view_components/utils/filter_columns.test.ts
src/plugins/discover/public/application/view_components/utils/filter_columns.ts

This is a missing functionality. In this PR we enables the following:
* When user sets up `Default columns` in advanced settings, discover should display default columns if the selected idp has the columns.
* If selected idp has no such columns, display `_source` column.
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5246
https://github.com/opensearch-project/OpenSearch-Dashboards/assets/79961084/2185f139-b600-4a17-964b-42314774181b

[BUG][Discover] Allow default columns settings

---

release-notes/opensearch-dashboards.release-notes-2.11.0.md

First line of release note shows `2.10.0` and not `2.11.0`.
rel #5252 
_N/A_
_not subject for that, since it's only markdown related._

[Fix] typo in 2.11.0 release note header

---

.github/workflows/cypress_workflow.yml
CHANGELOG.md

Add ciGroups to handle the increase in tests added which also impact the allocation available on the machines that run these tests.
However, this deserves to be more optimized and utilized within the build infra repo so that we can ensure that release testing is also leverging ciGroups within plugins.
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5297

[CI] Cypress tests support ciGroups

---

CHANGELOG.md
DEVELOPER_GUIDE.md
src/plugins/home/server/services/tutorials/lib/tutorial_schema.ts
src/plugins/home/server/services/tutorials/lib/tutorials_registry_types.ts
src/plugins/opensearch_dashboards_legacy/public/notify/toasts/TOAST_NOTIFICATIONS.md

[Docs] Update EUI doc site links to point to OUI doc site
Fix #2862:Update EUI doc site links to point to OUI doc site

[OSCI][Doc]Updated EUI doc site links to OUI doc site

---

CHANGELOG.md
package.json
yarn.lock

Before fix: 
```
yarn why @babel/traverse
[1/4] Why do we have the module "@babel/traverse"...?
warning Resolution field "typescript@4.0.2" is incompatible with requested version "typescript@~4.5.2"
=> Found "@babel/traverse@7.17.3"
- "_project_#@babel#core" depends on it
- Hoisted from "_project_#@babel#core#@babel#traverse"
- Hoisted from "_project_#babel-eslint#@babel#traverse"
- Hoisted from "_project_#@babel#core#@babel#helper-module-transforms#@babel#traverse"
- Hoisted from "_project_#@babel#core#@babel#helpers#@babel#traverse"
- Hoisted from "_project_#@osd#ui-shared-deps#styled-components#@babel#traverse"
- Hoisted from …
```

[CVE-2023-45133] Add package resolution for `@babel/traverse` to  `7.23.2` to fix vulnerability

---

src/plugins/discover/public/application/components/top_nav/__snapshots__/open_search_panel.test.tsx.snap
src/plugins/discover/public/application/components/top_nav/open_search_panel.tsx

In the Discover page ("Open" tab), changed the panel header from "Open search" to "OpenSearch".
- closes #5145 
- add snapshots to #5152

[Fix] Change panel header & update snapshot

---

CHANGELOG.md
src/dev/build/lib/config.test.ts
src/dev/build/lib/config.ts
src/dev/build/lib/platform.ts
src/dev/build/tasks/nodejs/download_node_builds_task.test.ts
src/dev/build/tasks/nodejs/extract_node_builds_task.test.ts
src/dev/build/tasks/nodejs/verify_existing_node_builds_task.test.ts

All the test cases can now pass for Mac (arm64) users.
- Added platform "darwin-arm64" to the unit tests
- Updated related snapshots
- closes #5232 
- My local setup:
- Chip: Apple M1 Pro
- macOS: Sonoma 14.0
- Chrome Version: 117.0.5938.149 (Official Build) (arm64)
- All the test cases pass on my end:

[Fix] Add platform "darwin-arm64" to unit test

---

src/plugins/discover/public/application/components/top_nav/get_top_nav_links.tsx

Fix share link issue of save search for data explorer.
resolves #5323 
https://github.com/opensearch-project/OpenSearch-Dashboards/assets/43937633/01d1acb7-c2f8-4cee-a935-e17293936d71

[Data Explorer] Fix share link of save search

---

.github/workflows/build_and_test_workflow.yml
.github/workflows/cypress_workflow.yml
CHANGELOG.md

`set-output` command for workflows is deprecated according to Github documentation. Update done using `GITHUB_OUTPUT` environment files. More details [here](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/#examples).
#5322 
[Run cypress tests](https://github.com/vvavdiya/OpenSearch-Dashboards/actions/runs/6575545037/job/17862935424#logs)
https://github.com/vvavdiya/OpenSearch-Dashboards/actions/runs/6574727075/job/17864788175#logs

[OSCI][CI] set-output is deprecated

---

.github/workflows/build_and_test_workflow.yml
CHANGELOG.md
test/plugin_functional/config.ts
test/plugin_functional/test_suites/core_plugins/ui_settings.ts

Add tests for plugin functional on GitHub Actions. Also skip custom doc link because of https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5370
resolves https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5382

[CI][Test] Add plugin functional tests on GitHub Actions

---

CHANGELOG.md
src/core/server/index.ts
src/core/utils/constants.ts
src/core/utils/index.ts
src/plugins/workspace/common/constants.ts
src/plugins/workspace/config.ts
src/plugins/workspace/opensearch_dashboards.json
src/plugins/workspace/public/index.ts
src/plugins/workspace/public/plugin.ts
src/plugins/workspace/server/index.ts
src/plugins/workspace/server/integration_tests/routes.test.ts
src/plugins/workspace/server/plugin.ts
src/plugins/workspace/server/routes/index.ts
src/plugins/workspace/server/saved_objects/index.ts
src/plugins/workspace/server/saved_objects/workspace.ts
src/plugins/workspace/server/types.ts
src/plugins/workspace/server/utils.test.ts
src/plugins/workspace/server/utils.ts
src/plugins/workspace/server/workspace_client.ts
test/api_integration/apis/index.js
test/api_integration/apis/workspace/index.ts

This PR is the initial PR for workspace, as we know workspace will be a new function that provides:
1. Organization on saved objects.
2. Manage visibility of opensearch features
3. Authorization on operations on saved objects.
And before all of the features mentioned above, we need to setup the workspace as a core plugin.
This PR includes:
- Add feature flag on workspace plugin.
- Setup workspace plugin skeleton.
- Define data structure on `workspace`.
- Implementation on CRUD operations on `workspace`.
#4945 
The changes introduced by this PR is not related to UI change.

[Workspace][Feature]Setup workspace skeleton and implement basic CRUD API

---

CHANGELOG.md
src/plugins/dashboard/public/application/embeddable/dashboard_container.tsx

Add a dashboard id as a prop to pass into the <DashboardViewPort> to force react to rerender the component everytime it receives a new id.
resolves https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4694
resolves https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4819
https://github.com/opensearch-project/OpenSearch-Dashboards/assets/43937633/7d0aa1da-f76e-48d6-a9d1-f2d40e05acfd
https://github.com/opensearch-project/OpenSearch-Dashboards/assets/43937633/a10f91eb-8fe5-4abe-9246-b613ad447756

Fix navigation issue across dashboards

---

package.json

Bump from 2.10.0 to 2.10.1
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4584

[2.10] bump version to next patch version

---

CHANGELOG.md
packages/osd-eslint-import-resolver-opensearch-dashboards/package.json
yarn.lock

- `eslint-import-resolver-webpack` bump removes nested dep of `browserify-sign`
- because webpack 4 still has a nested dep of `browserify-sign`, just updated yarn.lock to compatible fixed patch version.
Fixes https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5410

Bump `eslint-import-resolver-webpack` and `browserify-sign`

---

CHANGELOG.md
src/plugins/discover/public/application/components/data_grid/data_grid_table.tsx
src/plugins/discover/public/embeddable/search_embeddable.scss
src/plugins/discover/public/embeddable/search_embeddable.tsx
src/plugins/discover/public/embeddable/search_embeddable_component.tsx

* Add React.memo on parent comp
* Restore embeddable panel style
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5415
https://github.com/opensearch-project/OpenSearch-Dashboards/assets/79961084/5a8ad865-d179-41b7-a49b-e0a269e7a1ed

[BUG] Fix Discover table panel size auto adjust in Dashboard

---

CHANGELOG.md
packages/osd-eslint-import-resolver-opensearch-dashboards/package.json
yarn.lock

https://github.com/opensearch-project/OpenSearch-Dashboards/pull/5414

[2.x] Bump eslint-import-resolver-webpack and browserify-sign

---

CHANGELOG.md
packages/osd-eslint-import-resolver-opensearch-dashboards/package.json
yarn.lock

https://github.com/opensearch-project/OpenSearch-Dashboards/pull/5414

[1.3] Bump eslint-import-resolver-webpack and browserify-sign

---

.github/workflows/build_and_test_workflow.yml
src/dev/build/args.test.ts
src/dev/build/args.ts
src/dev/build/cli.ts
src/dev/build/lib/fs.ts
src/dev/build/tasks/create_archives_sources_task.ts
src/dev/build/tasks/nodejs/__snapshots__/download_node_builds_task.test.ts.snap
src/dev/build/tasks/nodejs/download_node_builds_task.test.ts
src/dev/build/tasks/nodejs/download_node_builds_task.ts
src/dev/build/tasks/nodejs/extract_node_builds_task.test.ts
src/dev/build/tasks/nodejs/extract_node_builds_task.ts
src/dev/build/tasks/nodejs/node_shasums.test.ts
src/dev/build/tasks/nodejs/verify_existing_node_builds_task.test.ts

Enhance darwin-arm64 release
* Add min-builds for `darwin-x64` and `darwin-arm64`.
* Expose `--darwin-arm` as a parameter of the build script.
* Work around build's cleanup failure when removal of an already deleted folder is attempted.
* Exclude bundling fallbacks with `darwin-arm64` since Node.js v14 has no releases for them.
* Update tests to accommodate `darwin-arm64`.
* Generalize the Node.js versions used in some tests.
PS: Skipping changelog as this is an enhancement to a recent change that was merged [#5290]
Fixes #5413 
Succeeds #5424

Enhance darwin-arm64 release

---

CHANGELOG.md
Dockerfile
package.json
yarn.lock

https://github.com/opensearch-project/OpenSearch-Dashboards/pull/5454

Bump chromedriver from 107.0.3 to 119.0.1

---

CHANGELOG.md
src/core/public/plugins/plugin.test.ts
src/core/public/plugins/plugins_service.test.ts
src/core/server/cross_compatibility/README.md
src/core/server/cross_compatibility/cross_compatibility.mock.ts
src/core/server/cross_compatibility/cross_compatibility_service.test.ts
src/core/server/cross_compatibility/cross_compatibility_service.ts
src/core/server/cross_compatibility/index.ts
src/core/server/cross_compatibility/types.ts
src/core/server/index.ts
src/core/server/internal_types.ts
src/core/server/legacy/legacy_service.ts
src/core/server/mocks.ts
src/core/server/plugins/plugin_context.ts
src/core/server/plugins/plugins_service.test.ts
src/core/server/plugins/plugins_service.ts
src/core/server/plugins/plugins_system.test.ts
src/core/server/plugins/plugins_system.ts
src/core/server/plugins/types.ts
src/core/server/server.test.ts
src/core/server/server.ts
src/core/types/cross_compatibility.ts
src/core/types/index.ts

* Adds new core server service `cross_compatibility_service` which export feature that plugins can extend to decide what they want to do if their OpenSearch plugin counterpart is not installed or has incompatible version. 
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4903
https://github.com/orgs/opensearch-project/projects/63/views/27?pane=issue&itemId=34093291

[Decouple] Add new core service to expose functionality to verify plugin compatibility with OpenSearch plugins

---

CHANGELOG.md
src/core/public/chrome/ui/header/__snapshots__/header.test.tsx.snap
src/core/public/chrome/ui/header/header.tsx

Add border for header navigation control on right
#5449

Add border for header navigation on right

---

CHANGELOG.md
release-notes/opensearch-dashboards.release-notes-2.11.1.md

Due to https://github.com/opensearch-project/OpenSearch-Dashboards/pull/5482#issuecomment-1815379782 and the closure of https://github.com/opensearch-project/OpenSearch-Dashboards/pull/5482, update 2.11.1 release note and add PR back to unreleased section in CHANGELOG.

Remove #5428 from 2.11.1 release due to conflicts

---

CHANGELOG.md
release-notes/opensearch-dashboards.release-notes-2.11.1.md

https://github.com/opensearch-project/OpenSearch-Dashboards/pull/5491

[2.11 Backport] Remove #5428 from 2.11.1 release due to conflicts

---

CHANGELOG.md
release-notes/opensearch-dashboards.release-notes-2.11.1.md

https://github.com/opensearch-project/OpenSearch-Dashboards/pull/5491

[2.x Backport] Remove #5428 from 2.11.1 release due to conflicts

---

src/plugins/home/public/application/components/homepage/hero_section/get_started.tsx
src/plugins/home/public/application/components/homepage/hero_section/hero_section.tsx

Mainly adding stay connected link to olly homepage, but also some minor styling things, mainly: 1) align hero section to top and 2) make suggested questions title smaller.

[feat/2.11/os-assistant] Add stay connected link

---

src/plugins/home/public/application/components/homepage/hero_section/get_started.tsx

Forces the new video link button to open on a new tab instead of navigating away.

[Home] video opens to new tab

---

src/plugins/home/config.ts
src/plugins/home/public/application/components/homepage/hero_section/get_started.tsx
src/plugins/home/public/application/components/homepage/section/basics.tsx

Allows for configuring of the image src. Will default use the screenshot if nothing is supplied.
Configurable with:
```
home.hero.img.src: 'img.png'
```
Includes fix for getting started to use the dark/light mode mark icon.
Includes fix for default values for the prompts.
Does not handle not valid urls.

[Home] configurable image src for video link

---

CHANGELOG.md
DEVELOPER_GUIDE.md
package.json
packages/osd-opensearch/src/cli_commands/snapshot.js
packages/osd-opensearch/src/cluster.js
packages/osd-opensearch/src/paths.js
src/cli/serve/serve.js

Add the ability to run:
```
yarn opensearch snapshot --security
```
which will start the OpenSearch cluster with the security plugin.
And add the ability to run:
```
yarn start:security
```
which will start the OpenSearch Dashboards server if the security plugin is available.
This is only intended for demo and local purposes.
Issue:
n/a

[Chore] `--security` for snapshot and OSD server

---

package.json
yarn.lock

Add package resolution for @babel/traverse. Manual backport PR for 1.3 from https://github.com/opensearch-project/OpenSearch-Dashboards/pull/5309. 
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5303

[Manual Backport 1.3] Add package resolution for @babel/traverse

---

.github/CODEOWNERS
CHANGELOG.md
MAINTAINERS.md

Here are their current merge contributions, total contributions, and issues:
- https://github.com/opensearch-project/OpenSearch-Dashboards/pulls?q=is%3Apr+is%3Amerged+author%3Asuzhou-joe+
- https://github.com/opensearch-project/OpenSearch-Dashboards/pulls?q=is%3Apr+author%3Asuzhou-joe+
- https://github.com/opensearch-project/OpenSearch-Dashboards/issues?q=is%3Aissue+suzhou-joe+is%3Aopen
Issue:
n/a

[Admin] Add @SuZhou-Joe as a maintainer

---

src/plugins/dev_tools/public/application.tsx

Modify data source text for dev tool based on UX input.

Modify data source text for dev tool

---

src/plugins/vis_type_markdown/public/markdown_options.tsx

The revision makes the icon appear only once, aligning with the design of the user interface.
Resolves #5510

[Fix] Duplicate Icon Rendering in Markdown Visualization Editor

---

.github/CODEOWNERS
CHANGELOG.md
MAINTAINERS.md

Backport https://github.com/opensearch-project/OpenSearch-Dashboards/pull/5594 and update missing backports for MAINTAINERS.md and .github/CODEOWNERS.
https://github.com/opensearch-project/OpenSearch-Dashboards/pull/5594

[2.x Backport] Add @SuZhou-Joe as a maintainer (#5594)

---

src/core/public/plugins/plugin.test.ts
src/core/public/plugins/plugins_service.test.ts
src/core/server/cross_compatibility/README.md
src/core/server/cross_compatibility/cross_compatibility.mock.ts
src/core/server/cross_compatibility/cross_compatibility_service.test.ts
src/core/server/cross_compatibility/cross_compatibility_service.ts
src/core/server/cross_compatibility/index.ts
src/core/server/cross_compatibility/types.ts
src/core/server/index.ts
src/core/server/internal_types.ts
src/core/server/legacy/legacy_service.ts
src/core/server/mocks.ts
src/core/server/plugins/plugin_context.ts
src/core/server/plugins/plugins_service.test.ts
src/core/server/plugins/plugins_service.ts
src/core/server/plugins/plugins_system.test.ts
src/core/server/plugins/plugins_system.ts
src/core/server/plugins/types.ts
src/core/server/server.test.ts
src/core/server/server.ts
src/core/types/cross_compatibility.ts
src/core/types/index.ts

Backport of https://github.com/opensearch-project/OpenSearch-Dashboards/pull/4710

[Manual][Backport 2.x][Decouple] Add new core service to expose functionality to verify plugin compatibility with OpenSearch plugins

---

CHANGELOG.md
src/plugins/console/public/application/hooks/use_send_current_request_to_opensearch/send_request_to_opensearch.test.ts
src/plugins/console/public/lib/mappings/__tests__/mapping.test.ts
src/plugins/console/public/lib/mappings/mappings.ts
src/plugins/console/public/lib/opensearch/http_response.mock.ts

Resolves a bug in the Console Plugin Dev Tool where the retrieveSettings function was incorrectly called with 'fields' instead of 'indices'. for `retrieveAliases` function.
closes #5567

fix: Dev tools console autocomplete issue #5567

---

CHANGELOG.md
release-notes/opensearch-dashboards.release-notes-2.11.1.md
src/plugins/discover/public/application/view_components/panel/index.tsx

Issue #5527: Now the time field of an index pattern would not get wrongly added to the selected field when we click `remove column` on canvas.
Issue #5538:  When doc_table:hideTimeColumn is enabled, removing the last columns from the canvas would automatically add "_source" to the selected fields in the left nav bar.
issue #5527 #5538 
For #5527
For #5538 
- [x ] All tests pass
- [x ] `yarn test:jest`
- [ x] `yarn test:jest_integration`
- [ x] Commits are signed per the DCO using --signoff

[OSCI][Fix][Discover]Prevent Adding Timefield to the Side Nav Selected Fields on Column Removal

---

CHANGELOG.md
src/core/public/chrome/chrome_service.mock.ts
src/core/public/chrome/chrome_service.test.ts
src/core/public/chrome/chrome_service.tsx
src/core/public/chrome/index.ts
src/core/public/chrome/ui/header/collapsible_nav.tsx
src/core/public/chrome/ui/header/header.tsx
src/core/public/core_system.ts
src/core/public/index.ts
src/core/public/plugins/plugin_context.ts
src/core/public/plugins/plugins_service.test.ts

This commit introduces an enhancement to the ChromeService class within our core application. It adds a new method named `registerCollapsibleNavHeader`, allowing plugins to customize the rendering of the collapsible navigation header in the global chrome UI.
With this new capability, plugins can now register their own rendering logic for the collapsible navigation header. This feature enhances the extensibility of our core system, empowering plugins to provide a more tailored and user-friendly navigation experience.
Key changes in this commit include:
1. The addition of the `registerCollapsibleNavHeader` method to the ChromeService class.
2. Appropriate updates to tests and typings to support the newly introduced functionality.
The upcoming workspace feature will bring noticeable change …

feat: Introduce `registerCollapsibleNavHeader` to ChromeService

---

CHANGELOG.md
src/plugins/discover/public/application/components/chart/utils/create_histogram_configs.ts

If an index pattern is created programatically using saved object API but a corresponding index does not exist for the pattern, discover throws a full page error that blocks the app from being used. This change still displays the error but allows the user to continue using the app to make other changes and remedy the situation.
closes #5625
Before: 
After:

[Data Explorer] Fix missing field error from taking down the page

---

.github/CODEOWNERS
CHANGELOG.md
MAINTAINERS.md

Backport https://github.com/opensearch-project/OpenSearch-Dashboards/pull/5594 and update missing backports for MAINTAINERS.md and .github/CODEOWNERS.
https://github.com/opensearch-project/OpenSearch-Dashboards/pull/5594

[1.3 Backport] Add @SuZhou-Joe as a maintainer (#5594)

---

CHANGELOG.md
src/plugins/data_source_management/public/components/create_data_source_wizard/components/create_form/create_data_source_form.test.tsx
src/plugins/data_source_management/public/components/create_data_source_wizard/components/create_form/create_data_source_form.tsx
src/plugins/data_source_management/public/components/edit_data_source/components/edit_form/edit_data_source_form.test.tsx
src/plugins/data_source_management/public/components/edit_data_source/components/edit_form/edit_data_source_form.tsx
src/plugins/data_source_management/public/types.ts

Replace `OuiSelect` component with `OuiSuperSelect ` in data-source plugin

Replace OuiSelect component with OuiSuperSelect in data-source plugin

---

CHANGELOG.md
package.json
packages/osd-ui-framework/package.json
packages/osd-ui-shared-deps/package.json
test/interpreter_functional/plugins/osd_tp_run_pipeline/package.json
test/plugin_functional/plugins/osd_sample_panel_action/package.json
test/plugin_functional/plugins/osd_tp_custom_visualizations/package.json
yarn.lock

Bump OUI from 1.4.0-alpha.2 to the 1.4.0 release.

Bump OUI to 1.4.0

---

CHANGELOG.md
package.json
yarn.lock

* This one is to fix [CVE-2023-26159](https://github.com/advisories/GHSA-jchw-25xp-jwwc) in main branch 
* No auto-cut issue of this CVE was spotted yet.

[CVE-2023-26159] Bump follow-redirects from 1.15.2 to 1.15.4

---

CHANGELOG.md
package.json
yarn.lock

Remove residual angular dependency. Appears unused from code search, and I don't think it's usable without angular anyway.

Chore (deps): remove ui-select angular dev dep

---

CHANGELOG.md
src/plugins/expressions/public/react_expression_renderer.tsx
src/plugins/index_pattern_management/public/components/create_button/create_button.tsx
src/plugins/opensearch_dashboards_react/public/code_editor/editor_theme.ts
src/plugins/vis_type_vislib/public/vislib/components/tooltip/tooltip.js

As part of https://github.com/opensearch-project/OpenSearch-Dashboards/pull/5652, I looked into the various ways we consume OUI themes. One thing I realized is that, when using the JSON files to fetch SASS variables, we should always do it via `ui-shared-deps`, which is dark/light-mode aware. This change fixes the imports, although further refactoring is deferred to the linked issue: https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5661

Chore (ui-shared-deps): Clean up direct usage of OUI theme JSON

---

CHANGELOG.md
src/plugins/data/public/data_sources/datasource_selector/datasource_selectable.test.tsx
src/plugins/data/public/data_sources/datasource_selector/datasource_selectable.tsx

Sort datasource option list in each group alphabetically.
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5609

[Datasource selector] Sort datasource option list alphabetically

---

CHANGELOG.md
DEVELOPER_GUIDE.md
src/cli/serve/serve.js

The instructions in the dev guide were insufficient to setup OSD with security for development. Updated the instructions to what worked for me.
Follow the instructions and see of you can setup OSD with security for development.

[Security] Updates dev guide for security

---

CHANGELOG.md
src/plugins/data_source_management/opensearch_dashboards.json
src/plugins/data_source_management/public/components/data_source_picker/data_source_picker.js
src/plugins/dev_tools/public/application.tsx
src/plugins/home/public/application/components/tutorial_directory.js

This resolves https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5717. 
The datasource picker has different behavior in devtools and tutorial page when multiple datasource is enabled, it should be one component to ensure the behavior is the same. 
This change adds datasource picker component and use it in devtools and tutorial page when multiple datasource is enabled to unify the behavior: the default option for the picker when first opening the page with the picker should be `Local cluster`. After removing the option, it should display `Select a data source`. Also, the prepend should be `Data source` instead of `DataSource`
fixes https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5717
https://github.com/opensearch-project/OpenSearch-Dashboards/assets/177141 …

Add datasource picker component and use it in devtools and tutorial page when multiple datasource is enabled

---

src/plugins/discover/public/application/components/default_discover_table/default_discover_table.tsx
src/plugins/discover/public/application/components/default_discover_table/table_header.tsx
src/plugins/discover/public/application/components/default_discover_table/table_rows.tsx

Improve table performance when loading a large set of data. Use intersection observer API and also delete the unique key on list elements.

Table optimization with lazy loading

---

src/plugins/data/public/data_sources/datasource_selector/datasource_selectable.tsx
src/plugins/data/public/data_sources/datasource_selector/types.ts
src/plugins/data_explorer/public/components/app_container.tsx
src/plugins/data_explorer/public/components/sidebar/index.tsx
src/plugins/discover/public/application/components/data_grid/data_grid_table.tsx
src/plugins/discover/public/application/components/default_discover_table/_table_cell.scss
src/plugins/discover/public/application/components/default_discover_table/table_rows.tsx
src/plugins/discover/public/application/view_components/canvas/discover_canvas.scss
src/plugins/discover/public/application/view_components/canvas/index.tsx

[Discover] Fix more UI

---

src/plugins/discover/public/application/components/default_discover_table/table_header_column.tsx

Change sort icon according to current sort condition. 
up arrow when it is sorted ascending;
down arrow when it is sorted descending;
up and down arrow when it is not sorted.
https://github.com/opensearch-project/OpenSearch-Dashboards/assets/43937633/d13eff16-2ada-45c6-925e-a04e88b0da66

Change sort icon according to current sort conditions

---

src/plugins/discover/public/application/components/data_grid/data_grid_table.tsx
src/plugins/discover/public/application/components/default_discover_table/default_discover_table.tsx
src/plugins/discover/public/embeddable/search_embeddable_component.tsx

Add pagination to discover embeddable that is shown on the dashboard.
According to 2.9 legacy discover:
- always have pagination on discover embeddable on dashboard; default row number is 50 rows per table
- no pagination on discover table on the discover page, it is always infinite scrolling
https://github.com/opensearch-project/OpenSearch-Dashboards/assets/43937633/9bd88ddb-4563-4fdc-afb1-d695d73d54fd

Add pagination to discover embeddable

---

src/plugins/discover/public/application/components/default_discover_table/table_cell.tsx
src/plugins/discover/public/application/components/default_discover_table/table_rows.tsx

[Discover] Prevent wrapping of time series cells

---

src/plugins/data/public/ui/query_string_input/_query_bar.scss

Vertically align the text in QueryStringInputUI with other elements on the page

---

src/core/server/core_app/assets/legacy_dark_theme.css
src/core/server/core_app/assets/legacy_light_theme.css
src/plugins/discover/public/application/components/data_grid/data_grid_table_cell_value.tsx
src/plugins/discover/public/application/components/default_discover_table/_doc_table.scss
src/plugins/discover/public/application/components/default_discover_table/_table_cell.scss
src/plugins/discover/public/application/components/default_discover_table/table_header.tsx
src/plugins/discover/public/application/components/default_discover_table/table_rows.tsx

Use `ouiCodeFont` in Discover and reduce text size
Also:
* Fix react `key` errors
* vertically align source cells
* Clamp the height of the cells
Before:
After:

Use `ouiCodeFont` in Discover and reduce text size

---

src/plugins/discover/public/application/components/default_discover_table/_table_cell.scss

https://github.com/opensearch-project/OpenSearch-Dashboards/assets/3527403/20ad0aa8-4910-4c3b-b5eb-f774a2574fe2

[Discover] Display filter buttons at top right of the cell

---

src/plugins/discover/public/application/components/default_discover_table/_table_cell.scss
src/plugins/discover/public/application/components/default_discover_table/table_rows.tsx

[Discover] Fix overflow of the expanded document
Also
* Fix vertical alignment of expand details button
* Fix colspan of details cells due to bad cherry-pick

[Discover] Fix overflow of the expanded document

---

src/plugins/discover/public/application/components/data_grid/data_grid_table.tsx
src/plugins/discover/public/application/components/default_discover_table/_pagination.scss
src/plugins/discover/public/application/components/default_discover_table/default_discover_table.tsx
src/plugins/discover/public/application/components/default_discover_table/pagination.tsx
src/plugins/discover/public/application/components/doc_views/context_app.tsx
src/plugins/discover/public/application/components/sidebar/discover_sidebar.tsx
src/plugins/discover/public/application/view_components/canvas/discover_table.tsx
src/plugins/discover/public/application/view_components/utils/get_default_sort.ts
src/plugins/discover/public/embeddable/search_embeddable.tsx
src/plugins/discover/public/embeddable/search_embeddable_component.tsx
src/plugins/vis_augmenter/public/view_events_flyout/components/styles.scss

Fixes pagniation styling
2.9 for comparision

[Discover] Fixes pagination style

---

src/plugins/discover/public/migrate_state.ts

URLs such as /app/discover#/context/<document-id>/<index-id> which is a valid URL for the context page should work.
Previously the link will only work if there is a question mark append to it.
closes #5774 
https://github.com/opensearch-project/OpenSearch-Dashboards/assets/43937633/b0a4ba77-9d9d-4764-b4a2-1e4bf9a3de7e

Routing for surrounding doc link should work without a question mark appending to the end

---

CHANGELOG.md
packages/osd-pm/README.md
packages/osd-pm/dist/index.js
packages/osd-pm/package.json
packages/osd-pm/src/cli.ts
packages/osd-pm/src/commands/bootstrap.ts
packages/osd-pm/src/utils/project.ts
packages/osd-pm/src/utils/scripts.ts
packages/osd-pm/src/utils/validate_dependencies.ts

Add `--single-version` switch to `bootstrap` to manipulate the behavior of single-version validation

[PM] Enhance single version requirements imposed during bootstrapping

---

CHANGELOG.md
package.json
packages/osd-dev-utils/package.json
yarn.lock

CVE fix
https://advisories.aws.barahmand.com/advisories/CVE-2020-8203

[CVE-2020-8203] Bump `cheerio` to fix vulnerable `lodash` dependency

---

CHANGELOG.md
package.json
packages/osd-dev-utils/package.json
yarn.lock

Backport https://github.com/opensearch-project/OpenSearch-Dashboards/pull/5797 to 2.x

[Manual][Backport 2.x] [CVE-2020-8203] Bump `cheerio` to fix vulnerable `lodash` dependency

---

CHANGELOG.md
yarn.lock

Bump `msgpackr` from `1.9.7` to `1.10.1`

---

CHANGELOG.md
packages/osd-pm/README.md
packages/osd-pm/dist/index.js
packages/osd-pm/package.json
packages/osd-pm/src/cli.ts
packages/osd-pm/src/commands/bootstrap.ts
packages/osd-pm/src/utils/project.ts
packages/osd-pm/src/utils/scripts.ts
packages/osd-pm/src/utils/validate_dependencies.ts

cherry picked 7c0bd9f39ba95aa419cbda58502a66827bece580 from #5675

[Manual Backport 2.x][PM] Enhance single version requirements imposed during bootstrapping (#5675)

---

src/plugins/discover/public/application/components/top_nav/get_top_nav_links.tsx

Updates the toggle button text
part of https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5716

[Discover] Update toggle to button

---

test/functional/apps/context/_context_navigation.js
test/functional/apps/context/_date_nanos.js
test/functional/apps/context/_discover_navigation.js
test/functional/apps/context/_filters.js
test/functional/apps/context/_size.js
test/functional/apps/home/_sample_data.ts
test/functional/apps/management/_scripted_fields.js
test/functional/page_objects/discover_page.ts
test/functional/services/dashboard/expectations.ts

Add swith to datagrid table and fix ciGroup1

---

CHANGELOG.md
src/core/server/saved_objects/import/check_conflict_for_data_source.test.ts
src/core/server/saved_objects/import/check_conflict_for_data_source.ts
src/core/server/saved_objects/import/check_origin_conflicts.ts
src/core/server/saved_objects/import/collect_saved_objects.ts
src/core/server/saved_objects/import/create_saved_objects.test.ts
src/core/server/saved_objects/import/create_saved_objects.ts
src/core/server/saved_objects/import/import_saved_objects.test.ts
src/core/server/saved_objects/import/import_saved_objects.ts
src/core/server/saved_objects/import/regenerate_ids.test.ts
src/core/server/saved_objects/import/regenerate_ids.ts
src/core/server/saved_objects/import/resolve_import_errors.test.ts
src/core/server/saved_objects/import/resolve_import_errors.ts
src/core/server/saved_objects/import/types.ts
src/core/server/saved_objects/routes/import.ts
src/core/server/saved_objects/routes/resolve_import_errors.ts

backport PR
https://github.com/opensearch-project/OpenSearch-Dashboards/pull/5777

[Manual Backport 2.x ]Update import api to have data source id to allow import saved objects from uploading files to have data source

---

CHANGELOG.md
src/plugins/data_source/config.ts

When MD enabled, local cluster should be enabled by default
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5754
Tested when 
1. data_source.enabled = true
2. data_source.defaultCluster get comment out
We still able to add sample data successfully in local cluster

[MD] Support local cluster by default

---

CHANGELOG.md
package.json
yarn.lock

Maual backport f2a44ae0d3dd87ac9d693b71ad7fa9484c1df0ec from [#5669](https://github.com/opensearch-project/OpenSearch-Dashboards/pull/5669)

[Manual Backport 2.12][CVE-2023-26159] Bump follow-redirects from 1.15.2 to 1.15.4 (#5669)

---

package.json
yarn.lock

Bakport f2a44ae0d3dd87ac9d693b71ad7fa9484c1df0ec from [#5669](https://github.com/opensearch-project/OpenSearch-Dashboards/pull/5669)

[Manual Backport 2.x][CVE-2023-26159] Bump follow-redirects from 1.15.2 to 1.15.4 (#5669)

---

CHANGELOG.md
src/plugins/data_source/common/data_sources/types.ts
src/plugins/data_source/server/auth_registry/authentication_methods_registry.test.ts
src/plugins/data_source/server/auth_registry/authentication_methods_registry.ts
src/plugins/data_source/server/auth_registry/index.ts
src/plugins/data_source/server/plugin.ts
src/plugins/data_source/server/routes/test_connection.ts
src/plugins/data_source/server/types.ts
src/plugins/data_source_management/public/auth_registry/authentication_methods_registry.test.ts
src/plugins/data_source_management/public/auth_registry/authentication_methods_registry.ts
src/plugins/data_source_management/public/auth_registry/index.ts
src/plugins/data_source_management/public/index.ts
src/plugins/data_source_management/public/mocks.ts
src/plugins/data_source_management/public/plugin.test.ts
src/plugins/data_source_management/public/plugin.ts
src/plugins/index_pattern_management/public/mocks.ts

This PR adds the interfaces to register authentication method into the registry and get authentication registry. These interfaces are accessible via the setup and start hook in `plugin.ts`. Any core components or plugins that list dataSource and dataSourceManagement as a dependency will have access to these interfaces.
Partially resolves #5692

[Multi data source] Add interfaces to register add-on authentication method from plug-in module

---

CHANGELOG.md
docs/multi-datasource/client_management_design.md
src/plugins/data_source/server/client/client_config.ts
src/plugins/data_source/server/client/configure_client.test.ts
src/plugins/data_source/server/client/configure_client.ts
src/plugins/data_source/server/legacy/client_config.ts
src/plugins/data_source/server/legacy/configure_legacy_client.test.ts
src/plugins/data_source/server/legacy/configure_legacy_client.ts
src/plugins/data_source/server/plugin.ts
src/plugins/data_source/server/schema_registry/custom_api_schema_registry.test.ts
src/plugins/data_source/server/schema_registry/custom_api_schema_registry.ts
src/plugins/data_source/server/schema_registry/index.ts
src/plugins/data_source/server/types.ts

This change allows consumers of data source plugin to register the API schema to be used in OpenSearch client and legacy client. 
Fixes https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5854
https://github.com/opensearch-project/OpenSearch-Dashboards/assets/17714150/2f10f57e-08e7-418c-bcc6-0da26e7c2b0d
Here are the steps which was performed in the screenshot
1. disable data source plugin
2. add sample data from local cluster, and checked dashboard displays as expected
3. enable data source plugin
4. check the dashboard added from remote data source, and verified dashboard displays as expected
5. go to query bench which was changed locally to register the schema and use the new client, and verified that it can connect with remote data source and perform query as expected

Add api registry and allow it to be added into client config in data source plugin

---

CHANGELOG.md
src/plugins/data_source/common/data_sources/types.ts
src/plugins/data_source/server/auth_registry/authentication_methods_registry.test.ts
src/plugins/data_source/server/auth_registry/authentication_methods_registry.ts
src/plugins/data_source/server/auth_registry/index.ts
src/plugins/data_source/server/plugin.ts
src/plugins/data_source/server/routes/test_connection.ts
src/plugins/data_source/server/types.ts
src/plugins/data_source_management/public/auth_registry/authentication_methods_registry.test.ts
src/plugins/data_source_management/public/auth_registry/authentication_methods_registry.ts
src/plugins/data_source_management/public/auth_registry/index.ts
src/plugins/data_source_management/public/index.ts
src/plugins/data_source_management/public/mocks.ts
src/plugins/data_source_management/public/plugin.test.ts
src/plugins/data_source_management/public/plugin.ts
src/plugins/index_pattern_management/public/mocks.ts

Backport from [e08bf30](https://github.com/opensearch-project/OpenSearch-Dashboards/commit/e08bf3059896449d2c008059c47b0b3de8da8c9e) from #5851

[Manual Backport 2.x][Multi data source] Add interfaces to register add-on authentication method from plug-in module

---

CHANGELOG.md
docs/multi-datasource/client_management_design.md
src/plugins/data_source/server/client/client_config.ts
src/plugins/data_source/server/client/configure_client.test.ts
src/plugins/data_source/server/client/configure_client.ts
src/plugins/data_source/server/legacy/client_config.ts
src/plugins/data_source/server/legacy/configure_legacy_client.test.ts
src/plugins/data_source/server/legacy/configure_legacy_client.ts
src/plugins/data_source/server/plugin.ts
src/plugins/data_source/server/schema_registry/custom_api_schema_registry.test.ts
src/plugins/data_source/server/schema_registry/custom_api_schema_registry.ts
src/plugins/data_source/server/schema_registry/index.ts
src/plugins/data_source/server/types.ts

Backport https://github.com/opensearch-project/OpenSearch-Dashboards/pull/5895 to 2.x

[Manual Backport 2.x] Add api registry and allow it to be added into client config in data source plugin

---

CHANGELOG.md
package.json
yarn.lock

Bumps chromdriver dependency causing errors during bootstrap due to URL change.
Potentially #5925

Upgrade chromedriver to fix bootstrapping errors

---

CHANGELOG.md
src/plugins/data_source/common/data_sources/types.ts
src/plugins/data_source/server/auth_registry/authentication_methods_registry.mock.ts
src/plugins/data_source/server/auth_registry/index.ts
src/plugins/data_source/server/client/configure_client.test.mocks.ts
src/plugins/data_source/server/client/configure_client.test.ts
src/plugins/data_source/server/client/configure_client.ts
src/plugins/data_source/server/legacy/configure_legacy_client.test.mocks.ts
src/plugins/data_source/server/legacy/configure_legacy_client.test.ts
src/plugins/data_source/server/legacy/configure_legacy_client.ts
src/plugins/data_source/server/plugin.ts
src/plugins/data_source/server/routes/test_connection.ts
src/plugins/data_source/server/types.ts
src/plugins/data_source/server/util/credential_provider.ts

Refactoring [client](https://github.com/opensearch-project/OpenSearch-Dashboards/tree/main/src/plugins/data_source/server/client) and [legacy client](https://github.com/opensearch-project/OpenSearch-Dashboards/tree/main/src/plugins/data_source/server/legacy) to use authentication registry.
Partially fixes #5692, #5838

Refactor getClient and getLegacyClient to use authentication method registry

---

CHANGELOG.md
src/plugins/discover/public/embeddable/search_embeddable.tsx

Remove default sort to use saved search sort.
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5933
https://github.com/opensearch-project/OpenSearch-Dashboards/assets/79961084/b616acfa-2585-4d61-bd26-0361dbbd57d7

[Bug][Discover] Allow saved sort from search embeddable to load in Dashboard

---

CHANGELOG.md
src/plugins/data/public/data_sources/datasource_selector/datasource_selectable.test.tsx
src/plugins/data/public/data_sources/datasource_selector/datasource_selectable.tsx

Before
After
After adding the id key, the duplicate index pattern is able to be selected, and seeing the index pattern id is reflected in search url.

[BUG] Support duplicate index pattern name

---

CHANGELOG.md
src/plugins/discover/public/application/components/default_discover_table/_table_cell.scss

The translate prop on the source cell causes a glitch in Safari that causes the overflow property to not work as expected in some scenarios. Removing it fixes the issue.
fixes #5941

[Discover] Fixes safari overflow bug

---

CHANGELOG.md
src/plugins/data_source/server/plugin.ts
src/plugins/data_source/server/routes/test_connection.test.ts
src/plugins/data_source/server/routes/test_connection.ts

This change adds custom API registry to the test connection route
Fixes https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5937
https://github.com/opensearch-project/OpenSearch-Dashboards/assets/17714150/217dc0bd-885a-4c54-82b8-701ad7ca452e
The following steps were followed:
enabled data source plugin
click test connection and should be successful

Fix missing customApiRegistryPromise param for test connection

---

.github/workflows/build_and_test_workflow.yml

Reduces the number of times the build and test workflow runs to be just for the main and release branches. All other triggers stay the same. Tis only applies to the push trigger.

[CI] Skip workflow for non release branches on push

---

CHANGELOG.md
src/plugins/data_source/common/data_sources/types.ts
src/plugins/data_source/server/auth_registry/authentication_methods_registry.mock.ts
src/plugins/data_source/server/auth_registry/index.ts
src/plugins/data_source/server/client/configure_client.test.mocks.ts
src/plugins/data_source/server/client/configure_client.test.ts
src/plugins/data_source/server/client/configure_client.ts
src/plugins/data_source/server/legacy/configure_legacy_client.test.mocks.ts
src/plugins/data_source/server/legacy/configure_legacy_client.test.ts
src/plugins/data_source/server/legacy/configure_legacy_client.ts
src/plugins/data_source/server/plugin.ts
src/plugins/data_source/server/routes/test_connection.ts
src/plugins/data_source/server/types.ts
src/plugins/data_source/server/util/credential_provider.ts

Backport from [d56b04](https://github.com/opensearch-project/OpenSearch-Dashboards/commit/d56b04d0aac6aed21825f44eb70bb4a9b512dde0) from #5881

[Manual Backport 2.x] Refactor getClient and getLegacyClient to use authentication method registry (#5881)

---

src/plugins/data_source/server/auth_registry/index.ts
src/plugins/data_source/server/client/configure_client.test.ts
src/plugins/data_source/server/legacy/configure_legacy_client.test.ts
src/plugins/data_source/server/routes/test_connection.test.ts

The issue was OSD doesn't come up healthy when running the built artifact due to `Error: Cannot find module './authentication_methods_registry.mock`
#5952
```
yarn build
./bin/opensearch-dashboards
.
.
.
log   [18:57:48.280] [info][listening] Server running at http://localhost:5601
log   [18:57:48.323] [info][server][OpenSearchDashboards][http] http server running at http://localhost:5601
```

Fixes authentication_methods_registry.mock module

---

CHANGELOG.md
packages/osd-std/src/json.ts

The parsing of JSON strings with long numerals in @osd/std handled two false-positive scenarios. A new one was discovered where mixed escaped quotes inside a string value resulted in a different exception in browsers that the one already handled for Node.
Fixes #5923

[osd/std] Add additional recovery from false-positives in handling of long numerals

---

CHANGELOG.md
src/plugins/data_source/server/plugin.ts
src/plugins/data_source/server/routes/test_connection.test.ts
src/plugins/data_source/server/routes/test_connection.ts

This is cherry pick of 6d5560e00c31748ddfbcd031241d67abaaf58c91 from https://github.com/opensearch-project/OpenSearch-Dashboards/pull/5944

[Manual Backport 2.x]Fix missing customApiRegistryPromise param for test connection (#5944)

---

src/plugins/data_source/server/auth_registry/index.ts
src/plugins/data_source/server/client/configure_client.test.ts
src/plugins/data_source/server/legacy/configure_legacy_client.test.ts
src/plugins/data_source/server/routes/test_connection.test.ts

This is cherry pick of [a449f70](https://github.com/opensearch-project/OpenSearch-Dashboards/commit/a449f70fcf247b1622a2a5f675205b794767c9e6) from #5970
#5952

[Manual Backport 2.x] Fixes authentication_methods_registry.mock module (#5970)

---

.github/CODEOWNERS
CHANGELOG.md
MAINTAINERS.md

Here are their current merge contributions, total contributions, and issues:
- https://github.com/opensearch-project/OpenSearch-Dashboards/pulls?q=is%3Apr+is%3Amerged+author%3Aruanyl+
- https://github.com/opensearch-project/OpenSearch-Dashboards/pulls?q=is%3Apr+author%3Aruanyl+
- https://github.com/opensearch-project/OpenSearch-Dashboards/issues?q=is%3Aissue+ruanyl+is%3Aopen
Issue:
n/a
Signed-off-by: Su Zhou <suzhou@amazon.com>

[Admin] Add @ruanyl as a maintainer

---

CHANGELOG.md
package.json
yarn.lock

This reverts commit 4f1177577fdaf9cf5373d9701bb63b52f9714557 due to Node 14 requirements. Revert https://github.com/opensearch-project/OpenSearch-Dashboards/pull/5928

[Manual Revert 2.x] Upgrade chromedriver to fix bootstrapping errors (#5926) 

---

CHANGELOG.md
src/plugins/data_source/server/routes/test_connection.test.ts
src/plugins/data_source/server/routes/test_connection.ts

This change refactors the schema validation for test connection API to separate the validation based on auth type. Tests were added for no auth, sigv4 and basic auth.
Fixes https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5987
https://github.com/opensearch-project/OpenSearch-Dashboards/assets/17714150/24f5c77e-a0bc-4696-85e7-221e4baeac62
The following steps were performed:
1. enable data source plugin
2. before the change, test connection would fail for no auth at the time of creation
3. before the change, test connection would succeed for no auth after creation
4. after the fix, test connection is successful for no auth at the time of creation and after creation
5. after the fix, test connection is successful for basic auth at the time of creation and after creation
6. …

[MD]Fix schema for test connection to separate validation based on auth type

---

CHANGELOG.md
config/opensearch_dashboards.yml
src/core/server/mocks.ts
src/core/server/opensearch_dashboards_config.ts
src/core/server/plugins/plugin_context.test.ts
src/core/server/plugins/types.ts
src/legacy/server/config/schema.js
src/plugins/application_config/.eslintrc.js
src/plugins/application_config/.i18nrc.json
src/plugins/application_config/README.md
src/plugins/application_config/common/index.ts
src/plugins/application_config/config.ts
src/plugins/application_config/opensearch_dashboards.json
src/plugins/application_config/server/index.ts
src/plugins/application_config/server/opensearch_config_client.test.ts
src/plugins/application_config/server/opensearch_config_client.ts
src/plugins/application_config/server/plugin.test.ts
src/plugins/application_config/server/plugin.ts
src/plugins/application_config/server/routes/index.test.ts
src/plugins/application_config/server/routes/index.ts
src/plugins/application_config/server/string_utils.test.ts
src/plugins/application_config/server/string_utils.ts
src/plugins/application_config/server/types.ts

The PR is to add application configuration service. See related issue for context. The code is mostly extracted from my other PR https://github.com/opensearch-project/OpenSearch-Dashboards/pull/5641 Once the current PR is merged, I will update the related PR to use the function provided by current PR.
**We plan to release this feature in `2.13.0` and may need a backport to `2.x` branch.**
**Note to the maintainers: please help add the backport label for `2.x`**
closes https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5796

Add support for dynamic application configurations

---

CHANGELOG.md
src/plugins/discover/public/application/components/data_grid/data_grid_table.tsx
src/plugins/discover/public/application/components/default_discover_table/default_discover_table.tsx
src/plugins/discover/public/application/view_components/canvas/discover_table.tsx
src/plugins/discover/public/application/view_components/canvas/index.tsx

dscCanvas is the one with scrollable prop. Set window.scrollTo(0, 0) on table will not work. In this PR, we add a ref to EuiPanel directly.
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/6006
https://github.com/opensearch-project/OpenSearch-Dashboards/assets/79961084/12b38b56-e867-4a08-9a58-52c814a19320

[BUG][Discover] Enable 'Back to Top' Feature in Discover for scrolling to top

---

src/core/server/saved_objects/migrations/core/build_active_mappings.ts
src/core/server/saved_objects/migrations/core/migration_context.ts
src/core/server/saved_objects/migrations/opensearch_dashboards/opensearch_dashboards_migrator.ts
src/plugins/workspace/server/saved_objects/saved_objects_wrapper_for_check_workspace_conflict.test.ts
src/plugins/workspace/server/saved_objects/saved_objects_wrapper_for_check_workspace_conflict.ts

[Workspace]Following pr for #5949

---

release-notes/opensearch-dashboards.release-notes-1.3.15.md

Correct release notes typo

---

CHANGELOG.md
config/opensearch_dashboards.yml
src/plugins/data_source_management/public/auth_registry/authentication_methods_registry.ts
src/plugins/data_source_management/public/components/create_data_source_wizard/components/create_form/create_data_source_form.test.tsx
src/plugins/data_source_management/public/components/create_data_source_wizard/components/create_form/create_data_source_form.tsx
src/plugins/data_source_management/public/components/edit_data_source/components/edit_form/edit_data_source_form.test.tsx
src/plugins/data_source_management/public/components/edit_data_source/components/edit_form/edit_data_source_form.tsx

Partial of Refactoring [create](https://github.com/opensearch-project/OpenSearch-Dashboards/tree/main/src/plugins/data_source_management/public/components/create_data_source_wizard) and [edit](https://github.com/opensearch-project/OpenSearch-Dashboards/tree/main/src/plugins/data_source_management/public/components/edit_data_source) form to use authentication registry user story.
- Render credential form registered from AuthMethod
Partially fixes https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5692, https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5838
https://github.com/opensearch-project/OpenSearch-Dashboards/assets/139305463/93ea7cc9-c77d-40ee-b756-10fc487ec428
Test cases added

[Multi Data Source] Render credential form registered from AuthMethod

---

CHANGELOG.md
src/plugins/discover/public/application/components/default_discover_table/default_discover_table.tsx

The sentinel object in the legacy table on first page load (without query params) was being set after the component rendered for the first time. This caused the observer to not be set properly. This change triggers the effect only once the sentinel is actually attached to the DOM node
fixes #6033
Before:
https://github.com/opensearch-project/OpenSearch-Dashboards/assets/20453492/eca379bb-3aad-4ce3-8b48-a31c3128271c
After:
https://github.com/opensearch-project/OpenSearch-Dashboards/assets/20453492/b4612b8d-5dc0-4cfe-8307-7d7cd45e4cd5

[Discover] Fix lazy loading 

---

CHANGELOG.md
src/plugins/data_source/server/saved_objects/data_source.test.ts
src/plugins/data_source/server/saved_objects/data_source.ts

This PR is to add a migration function with version 2.4.0 for datasource to add a migrationVersion field. 
For more information, please refer to the RFC: https://github.com/opensearch-project/OpenSearch-Dashboards/issues/6022
#6022 
For the testing, it is included in this RFC: https://github.com/opensearch-project/OpenSearch-Dashboards/issues/6022

Create a migration function for datasource to add migrationVersion field

---

CHANGELOG.md
src/plugins/data_source_management/public/components/data_source_selector/__snapshots__/create_data_source_selector.test.tsx.snap
src/plugins/data_source_management/public/components/data_source_selector/__snapshots__/data_source_selector.test.tsx.snap
src/plugins/data_source_management/public/components/data_source_selector/create_data_source_selector.test.tsx
src/plugins/data_source_management/public/components/data_source_selector/data_source_selector.test.tsx
src/plugins/data_source_management/public/components/data_source_selector/data_source_selector.tsx
src/plugins/data_source_management/public/components/utils.ts
src/plugins/data_source_management/public/mocks.ts

This change exposes a few properties like 
- defaultOption: the defaulted selected option when the component renders
- placeholderText: the place holder text when the selected option is cleared, default is `Select a data source`
- removePrepend: whether there will be a prepend
- filterFn: the function that will be used to filter the data source options
- compressed
Fixes https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5992
https://github.com/opensearch-project/OpenSearch-Dashboards/assets/17714150/beaa10c3-4905-4805-8ff6-0c307d5ff7d1
The following steps are performed in the recording above:
1. enable data source plugin
2. go to add sample data and data source picker should render correctly and import sample data from a data source should be successful, going to the …

[MD] Expose a few properties for customize the appearance of the data source selector component

---

CHANGELOG.md
src/plugins/data_source_management/public/components/data_source_menu/__snapshots__/create_data_source_menu.test.tsx.snap
src/plugins/data_source_management/public/components/data_source_menu/__snapshots__/data_source_menu.test.tsx.snap
src/plugins/data_source_management/public/components/data_source_menu/__snapshots__/data_source_selectable.test.tsx.snap
src/plugins/data_source_management/public/components/data_source_menu/create_data_source_menu.test.tsx
src/plugins/data_source_management/public/components/data_source_menu/create_data_source_menu.tsx
src/plugins/data_source_management/public/components/data_source_menu/data_source_menu.test.tsx
src/plugins/data_source_management/public/components/data_source_menu/data_source_menu.tsx
src/plugins/data_source_management/public/components/data_source_menu/data_source_selectable.test.tsx
src/plugins/data_source_management/public/components/data_source_menu/data_source_selectable.tsx
src/plugins/data_source_management/public/components/data_source_menu/index.ts
src/plugins/data_source_management/public/components/data_source_selector/data_source_selector.tsx
src/plugins/data_source_management/public/index.ts
src/plugins/data_source_management/public/plugin.ts

This change add a new data source menu component which exposes function to allow plugins to consume and mount to the navigation bar.
This PR is to expose component without backporting to release branch yet.
https://github.com/opensearch-project/OpenSearch-Dashboards/assets/17714150/8f154592-3b63-4feb-b520-cbed68ce3574
The following steps were performed in the recording above
1. enable data source plugin
2. go to search relevance and see the mounted data source menu, selected option to be `data sources` which is passed in via selectedOption
3. set to disable the menu will make the menu unclickable
4. go to query workbench and see the mounted data source menu, selected a data source and make query, will see the results from data source

[MD] Create data source menu component able to be mount to nav bar

---

.github/workflows/cypress_workflow.yml
.github/workflows/release_cypress_workflow.yml
CHANGELOG.md
cypress/utils/commands.js
package.json
scripts/common/opensearch_service.sh
scripts/cypress_tests.sh

Addressing comments from this PR https://github.com/opensearch-project/OpenSearch-Dashboards/pull/5725
* Update to this: https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/.github/workflows/cypress_workflow.yml to execute the cypress tests within this repo.
This way we can get the release testing verification workflow triggered with a dispatch event with a specified build. While the existing cypress test workflow will address the code within opened pull requests and run the tests.
* Build in the concept of CiGroups like the selenium tests have similar to FT repo: https://github.com/opensearch-project/opensearch-dashboards-functional-test/blob/main/package.json#L28. Define a folder structure in package json file and use it to parallel trigger workflows based on the …

Add functional test cypress workflow improvements and enable the workflow for in-house tests

---

CHANGELOG.md
src/plugins/data_source/server/plugin.ts
src/plugins/data_source/server/saved_objects/data_source_saved_objects_client_wrapper.test.ts
src/plugins/data_source/server/saved_objects/data_source_saved_objects_client_wrapper.ts

This PR handles auth methods from auth registry in DataSourceSavedObjectsClientWrapper.
Partially fixes https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5692, https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5838

Handles auth methods from auth registry in DataSourceSavedObjectsClientWrapper

---

CHANGELOG.md
src/plugins/vis_type_vega/opensearch_dashboards.json
src/plugins/vis_type_vega/public/data_model/opensearch_query_parser.ts
src/plugins/vis_type_vega/public/data_model/search_api.test.ts
src/plugins/vis_type_vega/public/data_model/search_api.ts
src/plugins/vis_type_vega/public/data_model/types.ts
src/plugins/vis_type_vega/public/default.spec.hjson
src/plugins/vis_type_vega/public/plugin.ts
src/plugins/vis_type_vega/public/services.ts
src/plugins/vis_type_vega/public/vega_request_handler.ts

This PR adds Vega support for MDS. If `data_source.enabled: true` and a `data_source_id` field is provided in the Vega spec, then the Vega visualization will render with data from the data source (assuming the data source has the specified index).
closes #5927 
https://github.com/opensearch-project/OpenSearch-Dashboards/assets/73027756/2f36633b-075a-4e0b-accd-a141e4ae28a7
1. Enable MDS (set`data_source.enabled: true` in `opensearch_dashboards.yml`)
2. Add data source (in this example, it is `vegaDataSource`)
3. Add the newly created data source name to the `data_source_name` field under the `url` body
1. Go to Visualize -> Create visualization -> Vega
2. Copy-paste existing Vega visualization from the data source (or create a new one)
3. Add a field `data_source_id` to the vega spec under …

[MDS] Support Vega Visualizations

---

CHANGELOG.md
src/plugins/workspace/public/plugin.test.ts
src/plugins/workspace/public/plugin.ts
src/plugins/workspace/public/workspace_client.mock.ts
src/plugins/workspace/public/workspace_client.test.ts
src/plugins/workspace/public/workspace_client.ts

This PR mainly introduces a workspace client to perform CRUD operations request to server side and gives some useful utils function.
closes #6093 
As the changes only happen in a frontend client, there is no screenshot for that.
- Clone the branch and enable workspace in yml file.
- Open the file `src/plugins/workspace/public/plugin.ts`
- Perform some operations through the initialized workspaceClient like: `workspaceClient.create`, `workspaceClient.delete` and so on, it should making http request to server accordingly in browser side.

[Workspace] Add a workspace client in workspace plugin

---

CHANGELOG.md
src/plugins/data_source_management/public/components/data_source_menu/__snapshots__/data_source_menu.test.tsx.snap
src/plugins/data_source_management/public/components/data_source_menu/data_source_menu.test.tsx
src/plugins/data_source_management/public/components/data_source_menu/data_source_menu.tsx
src/plugins/data_source_management/public/components/data_source_view/__snapshots__/data_source_view.test.tsx.snap
src/plugins/data_source_management/public/components/data_source_view/data_source_view.test.tsx
src/plugins/data_source_management/public/components/data_source_view/data_source_view.tsx
src/plugins/data_source_management/public/components/data_source_view/index.ts

This change adds component to show single selected data source in read only mode
https://github.com/opensearch-project/OpenSearch-Dashboards/assets/17714150/e88fb8e3-076c-49aa-b9fc-7b476d14cd99
The following were performed in the recording:
1. enable data source plugin, and see the mounted single selected data source component
2. when clicking on the info icon, a drop down shows which displays the currently used data source
3. disable data source plugin, and we should not see the mounted single selected data source component

[Multiple Datasource] Add component to show single selected data source in read only mode

---

CHANGELOG.md
package.json
yarn.lock

From https://www.mend.io/vulnerability-database/CVE-2024-27088:
```
es5-ext contains ECMAScript 5 extensions. Passing functions with very long names or complex default argument names into `function#copy` or `function#toStringTokens` may cause the script to stall. The vulnerability is patched in v0.10.63.
```
This PR bumps `es5-ext` from 
```
=> Found "es5-ext@0.10.59"
- "_project_#gulp-sourcemaps#debug-fabulous#memoizee" depends on it
- Hoisted from "_project_#gulp-sourcemaps#debug-fabulous#memoizee#es5-ext"
- Hoisted from "_project_#gulp-sourcemaps#debug-fabulous#memoizee#es6-weak-map#es5-ext"
- Hoisted from "_project_#gulp-sourcemaps#debug-fabulous#memoizee#d#es5-ext"
- Hoisted from "_project_#gulp-sourcemaps#debug-fabulous#memoizee#event-emitter#es5-ext" …
```

[CVE-2024-27088] Bump es5-ext from `0.10.59` to `0.10.64`

---

CHANGELOG.md
src/plugins/data_source_management/public/components/data_source_selector/__snapshots__/data_source_selector.test.tsx.snap
src/plugins/data_source_management/public/components/data_source_selector/data_source_selector.test.tsx
src/plugins/data_source_management/public/components/data_source_selector/data_source_selector.tsx
src/plugins/data_source_management/public/components/utils.ts

This change fixes the bug for data source filter, rename the filter function, and added type for the datasource object 
Fixes https://github.com/opensearch-project/OpenSearch-Dashboards/issues/6151
https://github.com/opensearch-project/OpenSearch-Dashboards/assets/17714150/e98b9ac5-dc3a-414d-ba4a-9a78673b5cba
The following steps were performed in the recording:
1. enable data source plugin
2. go to add sample data page, and data source selector renders correctly with all available options
3. go to dev tools, and data source selector renders correctly with all available options
4. go to search relevance, and data source selector renders correctly with all available options
5. add filter function in search relevance remove all data sources, and should show local cluster option only

[Multiple Datasource] Fix data source filter bug and add tests

---

CHANGELOG.md
package.json
yarn.lock

Backport https://github.com/opensearch-project/OpenSearch-Dashboards/pull/6021
Issue Resolve
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/6004
(cherry picked from commit 3797fd882919ff3109ede788f18393613ab633ef)

[Manual][Backport 2.x][CVE-2024-27088] Bump es5-ext from `0.10.59` to `0.10.64` (#6021)

---

CHANGELOG.md
package.json
yarn.lock

Employ a patched version of hoek that addresses CVE-2020-36604.
Note: the patched library has tests added for prototype poisoning.
```
% npm run test
> @amoo-miki/hoek@6.1.3 test
> lab -a code -t 100 -L
..................................................
..................................................
..................................................
................................
182 tests complete
Test duration: 159 ms
Assertions count: 522 (verbosity: 2.87)
The following leaks were detected:globalThis, FinalizationRegistry, WeakRef
Coverage: 100.00%
Linting results: No issues
```

Employ a patched version of hoek that addresses CVE-2020-36604

---

TESTING.md

[Docs] Adds testing requirements for PR's

---

CHANGELOG.md
src/plugins/data_source_management/public/components/data_source_aggregated_view/__snapshots__/data_source_aggregated_view.test.tsx.snap

This change removes obsolete snapshots to fix the test under data source management plugin
The obsolete snapshots from the tests were removed by executing `yarn test:jest -u src/plugins/data_source_management/` and the following is the output
```
Snapshot Summary
› 2 snapshots removed from 1 test suite.
↳ src/plugins/data_source_management/public/components/data_source_aggregated_view/data_source_aggregated_view.test.tsx
• DataSourceAggregatedView should render normally with local cluster and actice selections 2
• DataSourceAggregatedView should render normally with local cluster and actice selections 3
Test Suites: 22 passed, 22 total
Tests:       133 passed, 133 total
Snapshots:   2 removed, 38 passed, 38 total
Time:        15.354 s
Ran all test suites matching …
```

[BUG] Fix obsolete snapshots for test within data source management plugin

---

package.json
src/plugins/data_source/server/auth_registry/authentication_methods_registry.test.ts
src/plugins/data_source/server/auth_registry/authentication_methods_registry.ts
src/plugins/data_source/server/client/configure_client.test.mocks.ts
src/plugins/data_source/server/client/configure_client.test.ts
src/plugins/data_source/server/client/configure_client.ts
src/plugins/data_source/server/client/configure_client_utils.ts
src/plugins/data_source/server/legacy/configure_legacy_client.test.ts
src/plugins/data_source/server/legacy/configure_legacy_client.ts
src/plugins/data_source/server/legacy/http_aws_es/connector.js
src/plugins/data_source/server/legacy/http_aws_es/connector.test.js
src/plugins/data_source/server/types.ts
src/plugins/data_source/server/util/credential_provider.ts
yarn.lock

This is cherry pick of 1999a23 from #6135 
Testing with Node 14.
1. Create data source with Username and password authentication type.
2. Create data source with AWS SigV4 authentication type.
After creating data sources, following scenarios tested:
* Create index pattern
* Dev tool
* Discover
* Add sample data
* Visualizations
* Dashboards

 [Manual][Backport 2.x] Improves connection pooling support for AWSSigV4 clients in data sources (#6135)

---

CHANGELOG.md
src/plugins/application_config/README.md
src/plugins/application_config/server/routes/index.test.ts
src/plugins/application_config/server/routes/index.ts
src/plugins/application_config/server/types.ts
src/plugins/csp_handler/server/csp_handlers.ts

Application config plugin allows external plugin to register a different storage other than the default OpenSearch. The external plugin may need some additional information about the request headers when handling the requests.
Update the csp rules.
call
```
curl 'http://localhost:5601/api/appconfig/csp.rules' -X POST -H 'Accept: application/json' -H 'Content-Type: application/json' -H 'osd-xsrf: osd-fetch' -H 'Sec-Fetch-Dest: empty' --data-raw '{"newValue":"frame-ancestors https://example-site.org"}'
```
response
```
{"newValue":"frame-ancestors https://example-site.org"}%
```
Confirm on UI that the new value is used.
Check API calls to all configs
`curl 'http://localhost:5601/api/appconfig'`
response
```
{"value":{"csp.rules":"frame-ancestors https://example-site.org"}}%
```
Check API to …

Pass request headers when making application config calls

---

CHANGELOG.md
src/plugins/data_source/server/plugin.ts
src/plugins/data_source/server/routes/data_source_connection_validator.test.ts
src/plugins/data_source/server/routes/data_source_connection_validator.ts
src/plugins/data_source/server/routes/fetch_data_source_version.test.ts
src/plugins/data_source/server/routes/fetch_data_source_version.ts
src/plugins/data_source_management/public/components/create_data_source_wizard/create_data_source_wizard.test.tsx
src/plugins/data_source_management/public/components/create_data_source_wizard/create_data_source_wizard.tsx
src/plugins/data_source_management/public/components/utils.ts
src/plugins/data_source_management/public/mocks.ts
src/plugins/data_source_management/public/types.ts

* This change is the first step per RFC https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5877 aiming at decouple the strict version constrains between OSD Core and Plugins
* To make it happen this first step change is to include the data source version number in the newly created `data-source` object which would be consumed by plugins as part of the proof for determining version support
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/6177
* Unit Test passed
* Demonstration Recording
https://github.com/opensearch-project/OpenSearch-Dashboards/assets/99905560/c0b82a86-2eb9-4f2b-a34d-1a46433146a0
In the recording we demoed two scenarios:
1. When data source connection checks out, the data source version number is added to the data-source saved object
2. …

add version number to newly created datasource object

---

CHANGELOG.md
src/plugins/data_source_management/public/components/data_source_aggregated_view/__snapshots__/data_source_aggregated_view.test.tsx.snap
src/plugins/data_source_management/public/components/data_source_selector/data_source_selector.tsx

This change will store all data sources fetched during initial load, then apply the datasource filter function before rendering so that it can filter based on changes in the filter function.
Fixes https://github.com/opensearch-project/OpenSearch-Dashboards/issues/6174
https://github.com/opensearch-project/OpenSearch-Dashboards/assets/17714150/27b5e077-3a90-4094-a311-19c402de1dd3
The following steps were performed in the recording:
1. go to add sample data, and data source selector should render correctly with currently available data sources
2. add sample data from a data source is successful, and dashboard renders successfully
3. go to dev tool, and data source selector should render correctly with currently available data sources
4. make a query and is successfully returning response
5. …

[Multiple Datasource] Use data source filter function before rendering

---

CHANGELOG.md
yarn.lock

Bump follow-redirects from 1.15.4 to 1.15.6
fixes https://github.com/opensearch-project/OpenSearch-Dashboards/issues/6199

[CVE-2024-28849] Bump follow-redirects from 1.15.4 to 1.15.6

---

.github/CODEOWNERS
MAINTAINERS.md

Move @kristenTian to emeritus maintainer, this is a manually backport 2.x PR from #6136

[Manually backport 2.x] Move @kristenTian to emeritus maintainer

---

.github/CODEOWNERS
MAINTAINERS.md

Add @xinruiba as a maintainer, this PR is backport 2.x from #6217

[manual][backport-2.x] Add @xinruiba as a maintainer

---

release-notes/opensearch-dashboards.release-notes-2.13.0.md

Addressed Miki's comment from here https://github.com/opensearch-project/OpenSearch-Dashboards/pull/6219

Add release notes for 2.13

---

CHANGELOG.md
src/plugins/workspace/common/constants.ts
src/plugins/workspace/opensearch_dashboards.json
src/plugins/workspace/public/application.tsx
src/plugins/workspace/public/components/workspace_fatal_error/__snapshots__/workspace_fatal_error.test.tsx.snap
src/plugins/workspace/public/components/workspace_fatal_error/index.ts
src/plugins/workspace/public/components/workspace_fatal_error/workspace_fatal_error.test.tsx
src/plugins/workspace/public/components/workspace_fatal_error/workspace_fatal_error.tsx
src/plugins/workspace/public/plugin.test.ts
src/plugins/workspace/public/plugin.ts
src/plugins/workspace/public/types.ts

When user enters a url with workspaceId pattern inside url, workspace plugin should validate if the id exists, or should show an friendly error page to ask user to go back to home page without a pattern in url.
closes #6155 
- Using the branch to bootstrap
- Enable workspace feature flag in yml file by set `workspace.enabled: true`
- Start OSD by using `yarn start --no-base-path` to make sure no random base path will be appended
- Navigate to devTools
- Insert test workspaces by calling
```
PUT .kibana/_doc/workspace:foo
{
"type": "workspace",
"workspace": {
"name": "foo"
}
}
```
- Visit devTools under the test workspace: `http://localhost:5601/w/foo/app/dev_tools`, the page should render successfully.
- Visit devTools under a unexisting workspace: …

[Workspace] Validate if workspace exists when setup inside a workspace

---

CHANGELOG.md
src/plugins/data_source_management/public/components/data_source_table/__snapshots__/data_source_table.test.tsx.snap
src/plugins/data_source_management/public/components/data_source_table/data_source_table.test.tsx
src/plugins/data_source_management/public/components/data_source_table/data_source_table.tsx

Add icon in datasource table page to show the default datasource
https://github.com/opensearch-project/OpenSearch-Dashboards/assets/53279298/d1662cf1-0328-4016-b5ec-1ba94d02afd0

Add icon in datasource table page to show the default datasource

---

CHANGELOG.md
src/core/public/http/http_service.test.ts
src/core/public/http/http_service.ts
src/core/utils/workspace.test.ts
src/core/utils/workspace.ts
src/plugins/workspace/public/plugin.ts
src/plugins/workspace/server/plugin.ts

Make basePath required in `getWorkspaceIdFromUrl` method.
fixes #6015
- Using the branch to bootstrap
- Enable workspace by adding `workspace.enabled` to opensearch_dashboards.yml file 
- Start OSD by using `yarn start` to enable `basePath` feature.
- Navigate to devTools
- Insert test workspaces by calling
```
PUT .kibana/_doc/workspace:foo
{
"type": "workspace",
"workspace": {
"name": "foo"
}
}
```
- Visit the OpenSearch Dashboards under `foo` workspace: `http://localhost:5603/{random_basePath}/w/foo/app/dev_tools`
- The page should be able to load.

[Workspace] Add base path when parsing url in http service

---

CONTRIBUTING.md

the doc reference in CONTRIBUTING.md link to COMMUNICATIONS.md is wrong.

fix a doc reference typo in CONTRIBUTING.md

---

CHANGELOG.md
src/plugins/data_source_management/public/components/data_source_menu/__snapshots__/create_data_source_menu.test.tsx.snap
src/plugins/data_source_management/public/components/data_source_menu/__snapshots__/data_source_selectable.test.tsx.snap
src/plugins/data_source_management/public/components/data_source_menu/data_source_selectable.tsx

This change is part of https://github.com/opensearch-project/OpenSearch-Dashboards/issues/6216 to remove arrowdown icon from data source selectable component
https://github.com/opensearch-project/OpenSearch-Dashboards/assets/17714150/57cb6e86-de4e-4dc5-811d-e7ece60379b2
After removing the arrow down icon, the data source selectable component renders correctly

[Multiple Datasource] Remove arrow down icon from data source selectable component

---

CHANGELOG.md
src/core/public/index.ts
src/core/public/utils/debounce.test.ts
src/core/public/utils/debounce.ts
src/core/public/utils/index.ts
src/plugins/workspace/opensearch_dashboards.json
src/plugins/workspace/public/application.tsx
src/plugins/workspace/public/components/delete_workspace_modal/__snapshots__/delete_workspace_modal.test.tsx.snap
src/plugins/workspace/public/components/delete_workspace_modal/delete_workspace_modal.test.tsx
src/plugins/workspace/public/components/delete_workspace_modal/delete_workspace_modal.tsx
src/plugins/workspace/public/components/delete_workspace_modal/index.ts
src/plugins/workspace/public/components/utils/workspace.test.ts
src/plugins/workspace/public/components/utils/workspace.ts
src/plugins/workspace/public/components/workspace_list/__snapshots__/index.test.tsx.snap
src/plugins/workspace/public/components/workspace_list/index.test.tsx
src/plugins/workspace/public/components/workspace_list/index.tsx
src/plugins/workspace/public/components/workspace_list_app.tsx
src/plugins/workspace/public/plugin.test.ts
src/plugins/workspace/public/plugin.ts

In this PR, a new page will be added to workspace module. This page shows all workspaces in a table, user can view the name, id, description and features of each workspace. And users could search workspace through inputing name.
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/6132
- Clone the latest code and run yarn osd bootstrap
- Modify config/opensearch_dashboards.yml add workspace.enabled: true
- Run yarn start --no-base-path
- Visit [workspace list page](http://localhost:5601/app/workspace_list)

[Workspace] Add workspace list page

---

CHANGELOG.md
src/plugins/data_source/server/client/client_config.test.ts
src/plugins/data_source/server/client/client_config.ts
src/plugins/data_source/server/legacy/client_config.test.ts
src/plugins/data_source/server/legacy/client_config.ts
src/plugins/data_source/server/util/tls_settings_provider.test.ts
src/plugins/data_source/server/util/tls_settings_provider.ts

Fixes the logic in TLS configuration for multiple datasources to match the behavior of [opensearch_client_config.ts](https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/src/core/server/opensearch/legacy/opensearch_client_config.ts) which sets the `ca` portion of the ssl config to `undefined` (instead of empty list) when the `datasource.ssl.certificateAuthorities` setting is not set in `opensearch_dashboards.yml`.
- https://github.com/opensearch-project/OpenSearch-Dashboards/issues/6281

Fix sslConfig for multiple datasource to handle when certificateAuthorities is unset

---

CHANGELOG.md
config/opensearch_dashboards.yml
src/plugins/data_source/config.ts
src/plugins/data_source/server/client/client_config.test.ts
src/plugins/data_source/server/client/client_config.ts
src/plugins/data_source/server/legacy/client_config.test.ts
src/plugins/data_source/server/legacy/client_config.ts
src/plugins/data_source/server/util/tls_settings_provider.test.ts
src/plugins/data_source/server/util/tls_settings_provider.ts

Manual backport of #6171 to 2.x.

[Backport 2.x] [Multiple Datasources] Add TLS configuration for multiple data sources (#6171)

---

CHANGELOG.md
src/plugins/data_source_management/public/components/data_source_menu/__snapshots__/create_data_source_menu.test.tsx.snap
src/plugins/data_source_management/public/components/data_source_menu/data_source_menu.tsx
src/plugins/data_source_management/public/components/data_source_selectable/__snapshots__/data_source_selectable.test.tsx.snap
src/plugins/data_source_management/public/components/data_source_selectable/data_source_selectable.test.tsx
src/plugins/data_source_management/public/components/data_source_selectable/data_source_selectable.tsx
src/plugins/data_source_management/public/components/data_source_selectable/index.ts
src/plugins/data_source_management/public/components/data_source_selector/__snapshots__/data_source_selector.test.tsx.snap
src/plugins/data_source_management/public/mocks.ts

This change moves data source selectable to its own folder, fix test and a few type errors for data source selectable component
https://github.com/opensearch-project/OpenSearch-Dashboards/assets/17714150/402d3969-07d0-439d-a606-09b5fcf01c36
The following were performed in the video:
1. enable data source 
2. go to search relevance which mounted data source selectable component, select a data source from the menu, and it should show the option as selected and also reflect in the button text

[Multiple Datasource] Move data source selectable to its own folder, fix test and a few type errors for data source selectable component

---

src/plugins/data_source_management/public/components/data_source_menu/__snapshots__/create_data_source_menu.test.tsx.snap
src/plugins/data_source_management/public/components/data_source_menu/__snapshots__/data_source_selectable.test.tsx.snap
src/plugins/data_source_management/public/components/data_source_menu/data_source_selectable.tsx

This change backports 74e0df3b86e5d70b11a7c2eb03082b09e0f985c5

[Manual][Backport 2.x][Multiple Datasource] Remove arrow down icon from data source selectable component

---

CHANGELOG.md
src/plugins/data_source_management/public/components/data_source_multi_selectable/data_source_multi_selectable.tsx

The multi-selectable component does not call the callback function on initial load of the component. This means that plugins cannot initially fetch the dataSourceIds when first rendering the page. This PR makes a call to the callback function upon `componentDidMount()`
Closes #6324 
https://github.com/opensearch-project/OpenSearch-Dashboards/assets/73027756/2c258196-6cb9-499f-8143-5fc19c73eeeb
In the `multi-select` component, a `console.log()` statement was added to the callback function and this callback function was passed into the `multi-select` component. Because the log statement was called without any selection changes, it shows that the callback function was called when the `multi-select` component initially loaded.

[Multiple Datasource] Pass selected data sources to plugin consumers when the multi-select component initially loads

---

CHANGELOG.md
src/plugins/data_source_management/public/components/data_source_selector/__snapshots__/data_source_selector.test.tsx.snap
src/plugins/data_source_management/public/components/data_source_selector/create_data_source_selector.test.tsx
src/plugins/data_source_management/public/components/data_source_selector/create_data_source_selector.tsx
src/plugins/data_source_management/public/components/data_source_selector/data_source_selector.test.tsx
src/plugins/data_source_management/public/components/data_source_selector/data_source_selector.tsx
src/plugins/data_source_management/public/components/utils.test.ts
src/plugins/data_source_management/public/components/utils.ts
src/plugins/data_source_management/public/mocks.ts
src/plugins/data_source_management/public/plugin.ts
src/plugins/dev_tools/public/application.tsx
src/plugins/home/public/application/components/tutorial_directory.js

*  add the default icon in the selector
* Add a showDefault function that plugins team can use and get the Default datasource
https://github.com/opensearch-project/OpenSearch-Dashboards/assets/53279298/64cc706e-a468-466d-b3ad-a9516d8ae63c

[Multiple Datasource] Enhanced data source selector with default datasource shows as first choice

---

CHANGELOG.md
src/plugins/data_source_management/public/components/data_source_menu/create_data_source_menu.tsx
src/plugins/data_source_management/public/components/data_source_menu/data_source_menu.tsx
src/plugins/data_source_management/public/components/data_source_menu/types.ts
src/plugins/data_source_management/public/components/data_source_selectable/__snapshots__/data_source_selectable.test.tsx.snap
src/plugins/data_source_management/public/components/data_source_selectable/data_source_selectable.test.tsx
src/plugins/data_source_management/public/components/data_source_selectable/data_source_selectable.tsx
src/plugins/data_source_management/public/components/utils.ts
src/plugins/data_source_management/public/plugin.test.ts
src/plugins/data_source_management/public/plugin.ts

Modify seletable picker in datasource management to show the default datasource
https://github.com/opensearch-project/OpenSearch-Dashboards/assets/53279298/979a66de-a8be-4d16-903c-6a8ea962628b

Add default icon for selectable component and make sure the default datasource shows automatically

---

CHANGELOG.md
src/plugins/data_source_management/public/components/data_source_menu/__snapshots__/create_data_source_menu.test.tsx.snap
src/plugins/data_source_management/public/components/data_source_menu/create_data_source_menu.test.tsx
src/plugins/data_source_management/public/components/data_source_menu/create_data_source_menu.tsx
src/plugins/data_source_management/public/components/data_source_menu/data_source_menu.test.tsx
src/plugins/data_source_management/public/components/data_source_menu/data_source_menu.tsx
src/plugins/data_source_management/public/components/data_source_menu/types.ts
src/plugins/data_source_management/public/components/data_source_selector/__snapshots__/create_data_source_selector.test.tsx.snap
src/plugins/data_source_management/public/components/data_source_selector/create_data_source_selector.test.tsx
src/plugins/data_source_management/public/components/data_source_selector/create_data_source_selector.tsx
src/plugins/data_source_management/public/components/data_source_selector/data_source_selector.tsx
src/plugins/data_source_management/public/mocks.ts
src/plugins/data_source_management/public/plugin.ts

- Read `data_source.hideLocalCluster` setting from `opensearch_dashboards.yml`, and always use this value to decide if to hide local cluster in `DataSourceSelector` and `DataSourceMenu`. This is expected behaviour because hide/show local cluster in data source visual components should be consistent across anywhere that consumes those components.
- make `hideLocalHost` an optional property of `DataSourceSelector` and `DataSourceMenu`
- Update related unit tests
#6336 
https://github.com/opensearch-project/OpenSearch-Dashboards/assets/32652829/2c224539-8bfa-44f1-b165-c96c999275e9

[MD]Read hideLocalCluster setting from yml and set in data source selector and data source menu

---

integtest.sh

This is for Build/Infra team to dry run Jenkins CI by directly cloning OSD repo to run cypress tests within the repository. 
After this dryrun, we should integrate this changes to main and 2.x branches. This would require additional work at Infra for enabling this specifically for OSD as plugins are still pulling tests from FTR.
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/6316
Work with Infra team to make sure the tests are executed as part of their pipeline.

[Tests] Add integtest.sh script for build to trigger Dashboards cypress tests

---

CHANGELOG.md
src/plugins/data_source_management/public/components/data_source_menu/data_source_menu.tsx
src/plugins/data_source_management/public/components/data_source_multi_selectable/__snapshots__/data_source_filter_group.test.tsx.snap
src/plugins/data_source_management/public/components/data_source_multi_selectable/__snapshots__/data_source_multi_selectable.test.tsx.snap
src/plugins/data_source_management/public/components/data_source_multi_selectable/data_source_filter_group.test.tsx
src/plugins/data_source_management/public/components/data_source_multi_selectable/data_source_filter_group.tsx
src/plugins/data_source_management/public/components/data_source_multi_selectable/data_source_multi_selectable.test.tsx
src/plugins/data_source_management/public/components/data_source_multi_selectable/data_source_multi_selectable.tsx
src/plugins/data_source_management/public/components/data_source_option.test.tsx
src/plugins/data_source_management/public/components/data_source_option.tsx

Add default icon in multi-selectable picker and fix a bug in when datasource length is 0, localcluster would not be added. 
https://github.com/opensearch-project/OpenSearch-Dashboards/assets/53279298/161a22a2-e4ac-4f51-b7c8-93c83950a197

[MD]Add default icon in multi-selectable picker

---

CHANGELOG.md
src/plugins/data_source_management/public/components/data_source_menu/types.ts
src/plugins/data_source_management/public/components/data_source_selectable/__snapshots__/data_source_selectable.test.tsx.snap
src/plugins/data_source_management/public/components/data_source_selectable/data_source_selectable.test.tsx
src/plugins/data_source_management/public/components/data_source_selectable/data_source_selectable.tsx

- when there's options available,  add OpenSearch cluster group label to the top of options in DataSourceSelectable dropdown.
- when there's no options, don't render the opensearch cluster group label
https://github.com/opensearch-project/OpenSearch-Dashboards/assets/32652829/a6e7fe9d-8f5e-47b8-9d94-5466a4d70d60
part of https://github.com/opensearch-project/OpenSearch-Dashboards/issues/6370

[MD] Add OpenSearch cluster group label to top of single selectable dropdown

---

CHANGELOG.md
config/opensearch_dashboards.yml
src/plugins/application_config/server/opensearch_config_client.test.ts
src/plugins/application_config/server/opensearch_config_client.ts
src/plugins/application_config/server/plugin.test.ts
src/plugins/application_config/server/plugin.ts
src/plugins/application_config/server/types.ts
src/plugins/csp_handler/server/csp_handlers.test.ts
src/plugins/csp_handler/server/csp_handlers.ts

Address the comments from this issue https://github.com/opensearch-project/OpenSearch-Dashboards/issues/6300
This PR updates the parameters to the ` getConfigurationClient` function and adds a cache.
closes https://github.com/opensearch-project/OpenSearch-Dashboards/issues/6300
closes https://github.com/opensearch-project/OpenSearch-Dashboards/issues/6341
call the get API
```
curl -X GET 'http://localhost:5601/api/appconfig/csp.rules'
{"value":"frame-ancestors https://example-site.org"}%
```
Then call the get API again.
```
curl -X GET 'http://localhost:5601/api/appconfig/csp.rules'
{"value":"frame-ancestors https://example-site.org"}%
```
We find two entries in the logs where the first one doesn't show cache entry but the second one shows cache entry.
```
server    log   [02:13:58.836] …
```

Improve dynamic configurations by adding cache and simplifying client fetch

---

CHANGELOG.md
src/core/public/doc_links/doc_links_service.ts
src/plugins/visualizations/public/embeddable/disabled_lab_visualization.tsx
src/plugins/visualizations/public/plugin.ts
src/plugins/visualizations/public/services.ts

This PR completes
https://github.com/opensearch-project/OpenSearch-Dashboards/pull/5462
Please refer to the above PR for more details
Partical https://github.com/opensearch-project/OpenSearch-Dashboards/issues/3386

[OSCI] Removed KUI usage in visualizations -- Completion of Original PR

---

src/plugins/dashboard/public/application/components/dashboard_listing/__snapshots__/dashboard_listing.test.tsx.snap
src/plugins/dashboard/public/application/components/dashboard_top_nav/__snapshots__/dashboard_top_nav.test.tsx.snap

This PR updates two snapshots
1. src/plugins/dashboard/public/application/components/dashboard_top_nav/dashboard_top_nav.test.tsx this one breaks due to #6360
2. src/plugins/dashboard/public/application/components/dashboard_listing/dashboard_listing.test.tsx this one breaks due to #6360

Fix test in PR 6360

---

CHANGELOG.md
src/core/public/saved_objects/saved_objects_client.ts
src/core/server/saved_objects/export/get_sorted_objects_for_export.ts
src/core/server/saved_objects/import/check_conflicts.ts
src/core/server/saved_objects/import/create_saved_objects.test.ts
src/core/server/saved_objects/import/create_saved_objects.ts
src/core/server/saved_objects/import/types.ts
src/core/server/saved_objects/routes/bulk_create.ts
src/core/server/saved_objects/routes/create.ts
src/core/server/saved_objects/routes/export.ts
src/core/server/saved_objects/routes/find.ts
src/core/server/saved_objects/serialization/types.ts
src/core/server/saved_objects/service/lib/search_dsl/query_params.ts
src/core/server/saved_objects/service/lib/search_dsl/search_dsl.ts
src/core/server/saved_objects/service/saved_objects_client.ts
src/core/server/saved_objects/types.ts
src/plugins/workspace/common/constants.ts
src/plugins/workspace/server/plugin.test.ts
src/plugins/workspace/server/plugin.ts
src/plugins/workspace/server/saved_objects/integration_tests/workspace_id_consumer_wrapper.test.ts
src/plugins/workspace/server/saved_objects/saved_objects_wrapper_for_check_workspace_conflict.ts
src/plugins/workspace/server/saved_objects/workspace_id_consumer_wrapper.test.ts
src/plugins/workspace/server/saved_objects/workspace_id_consumer_wrapper.ts
src/plugins/workspace/server/saved_objects/workspace_saved_objects_client_wrapper.ts
src/plugins/workspace/server/workspace_client.ts

Support workspace in saved objects client in server side to unified the way to append workspace id in request payload.
closes #6130
- Using the branch to bootstrap
- enabled `workspace.enabled` to true
- Start OSD by using `yarn start --no-base-path` to make sure no random base path will be appended
- Navigate to devTools
- Insert test workspaces by calling
```
PUT .kibana/_doc/workspace:foo
{
"type": "workspace",
"workspace": {
"name": "foo"
}
}
PUT .kibana/_doc/workspace:bar
{
"type": "workspace",
"workspace": {
"name": "bar"
}
}
```
- Visit the saved objects management page: `http://localhost:5601/w/foo/app/management/opensearch-dashboards/objects`
- You will find nothing can be found in this workspace.
- Import by using the [file](https://github.com/opensearch-project/OpenSearch-Dashbo …

[Workspace] Support workspace in saved objects client in server side. 

---

CHANGELOG.md
src/core/server/index.ts
src/core/server/saved_objects/service/lib/repository.mock.ts
src/core/server/saved_objects/service/lib/repository.test.js
src/core/server/saved_objects/service/lib/repository.ts
src/core/server/saved_objects/service/saved_objects_client.test.js
src/core/server/saved_objects/service/saved_objects_client.ts
src/plugins/workspace/server/integration_tests/routes.test.ts
src/plugins/workspace/server/routes/index.ts
src/plugins/workspace/server/workspace_client.ts

backport 735424bcaabfc752453c4d514ddd5d4b4f1b6d6d from #6013

[Backport 2.x] [Workspace] Delete saved objects by workspace

---

CHANGELOG.md
src/plugins/data_source/server/routes/data_source_connection_validator.test.ts
src/plugins/data_source/server/routes/data_source_connection_validator.ts

Data source validation should pass as long as response code is `200` even if response body is empty, for example:
```
{
body: '',
statusCode: 200,
headers: {
'content-type': 'text/plain; charset=UTF-8',
'content-length': '0',
'x-envoy-upstream-service-time': '44',
date: 'Wed, 10 Apr 2024 06:10:28 GMT',
server: 'aoss-amazon-m',
'x-request-id': '284bf59f-4601-9ce9-ba7b-2c2282e34c17'
},
meta: {
context: null,
request: { params: [Object], options: {}, id: 1 },
name: 'opensearch-js',
connection: {
url: 'https://vywd1o523wrumu9h3q05.gamma-us-east-1.aoss.amazonaws.com/',
id: 'https://vywd1o523wrumu9h3q05.gamma-us-east-1.aoss.amazonaws.com/',
headers: {},
deadCount: 0,
resurrectTimeout: 0,
_openRequests: 0,
status: 'alive',
roles: [Object]
},
attempts: 0,
aborted: false
}
}
``` …

Validation succeed as long as status code in response is 200

---

src/plugins/workspace/common/constants.ts
src/plugins/workspace/opensearch_dashboards.json
src/plugins/workspace/public/application.tsx
src/plugins/workspace/public/components/workspace_fatal_error/__snapshots__/workspace_fatal_error.test.tsx.snap
src/plugins/workspace/public/components/workspace_fatal_error/index.ts
src/plugins/workspace/public/components/workspace_fatal_error/workspace_fatal_error.test.tsx
src/plugins/workspace/public/components/workspace_fatal_error/workspace_fatal_error.tsx
src/plugins/workspace/public/plugin.test.ts
src/plugins/workspace/public/plugin.ts
src/plugins/workspace/public/types.ts

Backport 0cc91ab3ed89ed72552a29e503cab2dab324a073 from #6154

[Backport 2.x][Workspace] Validate if workspace exists when setup inside a workspace

---

CHANGELOG.md
src/plugins/data_source/common/data_sources/types.ts
src/plugins/data_source/server/client/configure_client_utils.ts
src/plugins/data_source_management/public/types.ts

Removed duplicate data source attribute interface from data source management plugin.
Partially resolves #6204
https://github.com/opensearch-project/OpenSearch-Dashboards/assets/63824432/e3294170-0ff5-4602-9c00-85ad15487517
Above recording performs following steps and verify this changes doesn't introduce regressions.
- Create data source with `Username & Password` authentication type.
- Verify Test connection works while creating data source.
- Go to View/Edit data source screen.
- Verify Test connection still works.
- Change title of data source and save. Data source management page reflects modified changes.
- Using dev tool, verify all the attributes of data source including data source version, installed plugin list etc are saved in system index (Dashboards meta storage).

Remove duplicate data source attribute interface

---

CHANGELOG.md
examples/multiple_data_source_examples/public/components/data_source_view_example.tsx
src/plugins/data_source_management/public/components/constants.tsx
src/plugins/data_source_management/public/components/data_source_menu/__snapshots__/data_source_menu.test.tsx.snap
src/plugins/data_source_management/public/components/data_source_menu/data_source_menu.tsx
src/plugins/data_source_management/public/components/data_source_menu/types.ts
src/plugins/data_source_management/public/components/data_source_view/__snapshots__/data_source_view.test.tsx.snap
src/plugins/data_source_management/public/components/data_source_view/data_source_view.test.tsx
src/plugins/data_source_management/public/components/data_source_view/data_source_view.tsx
src/plugins/data_source_management/public/components/utils.test.ts
src/plugins/data_source_management/public/components/utils.ts
src/plugins/data_source_management/public/mocks.ts

Refactor read-only component to cover more edge cases
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/6393
1. activeOption={[{id: ''}]} with hideLocalCluster is set to true in yaml 
Toast: Data source is not available
2. activeOption={[{id: 'invalid'}]}
Toast: Failed to fetch data source
3. activeOption={[{id: ''}]}   with hideLocalCluster is set to false in yaml 
Show local cluster
4. activeOption={[{id: 'valid id'}]}  
show selected cluster
5. activeOption={[{id: 'valid id', iabel:"show label"}]} 
show selected cluster with label name
6. When valid id pass in, but it has been filtered out
activeOption: [{ id: '6304d1d0-f826-11ee-ab60-439c91fde80b', label:'show label' }],
dataSourceFilter: (ds) => {return ds.id != '6304d1d0-f826-11ee-ab60-439c91fde80b'},
toast: …

Refactor read-only component to cover more edge cases

---

DEVELOPER_GUIDE.md

This change adds a section in the dev guides about pull request, and it is based on observations when reviewing PRs, and the intent is to use current guide to illustrate the best practice and a reference to help improve the pull request quality. It might not capture everything but can be a good start.

Add dev guide for pull request

---

src/core/public/http/http_service.test.ts
src/core/public/http/http_service.ts
src/core/utils/workspace.test.ts
src/core/utils/workspace.ts
src/plugins/workspace/public/plugin.ts
src/plugins/workspace/server/plugin.ts

Backport 0dce00a806bf8815ca84802541010767b6b3a8bd from #6233

[Backport 2.x][Workspace] Add base path when parsing url in http service

---

CHANGELOG.md
config/opensearch_dashboards.yml
src/plugins/application_config/server/routes/index.test.ts
src/plugins/application_config/server/routes/index.ts

During https://github.com/opensearch-project/OpenSearch-Dashboards/pull/6364/files, we simplify the input to `getConfigurationClient` from a client to a request. We were focusing on the use case of other plugins to onboard onto it. However, we also have API use case which we missed during the related PR. So, this PR is to fix the issue by passing request into the function instead of a client. 
Currently it is not failing because the `asScoped` function doesn't fail. Check the code reference here https://github.com/opensearch-project/OpenSearch-Dashboards/blob/eef417c03e7c4d34e85c70edb6c2079528ebc683/src/core/server/opensearch/client/cluster_client.ts#L137 It just treats it as using default headers and then doesn't pass user information to get a real scoped client.
Enable the following in …

fix dynamic config API calls to pass correct input

---

CHANGELOG.md
src/plugins/data_source_management/opensearch_dashboards.json
src/plugins/data_source_management/public/components/data_source_menu/create_data_source_menu.test.tsx
src/plugins/data_source_management/public/components/data_source_menu/create_data_source_menu.tsx
src/plugins/data_source_management/public/components/data_source_menu/data_source_menu.tsx
src/plugins/data_source_management/public/components/data_source_menu/types.ts
src/plugins/data_source_management/public/components/data_source_selectable/__snapshots__/data_source_selectable.test.tsx.snap
src/plugins/data_source_management/public/components/data_source_selectable/data_source_selectable.test.tsx
src/plugins/data_source_management/public/components/data_source_selectable/data_source_selectable.tsx
src/plugins/data_source_management/public/components/data_source_selector/data_source_selector.test.tsx
src/plugins/data_source_management/public/components/drop_down_header/__snapshots__/drop_down_header.test.tsx.snap
src/plugins/data_source_management/public/components/drop_down_header/drop_down_header.scss
src/plugins/data_source_management/public/components/drop_down_header/drop_down_header.test.tsx
src/plugins/data_source_management/public/components/drop_down_header/drop_down_header.tsx
src/plugins/data_source_management/public/components/drop_down_header/index.ts
src/plugins/data_source_management/public/components/utils.ts
src/plugins/data_source_management/public/plugin.ts

- Add dropdown header to data source single selector. This header includes
- a counter showing the count of datasource options avaliable
- a link with text "Manage", that honors SPA(single page application) to redirect to data source management page 
- Fix bug of opensearch cluster group label being rendered multiple times when toggling between options
- Add and update related unit tests
#6429 
https://github.com/opensearch-project/OpenSearch-Dashboards/assets/32652829/2a90a064-a279-4f05-bcd6-f0ea2be9a143

[MD] Add dropdown header to data source single selector

---

CHANGELOG.md
src/plugins/data_source_management/public/components/button_title.scss
src/plugins/data_source_management/public/components/data_source_menu/__snapshots__/create_data_source_menu.test.tsx.snap
src/plugins/data_source_management/public/components/data_source_selectable/__snapshots__/data_source_selectable.test.tsx.snap
src/plugins/data_source_management/public/components/data_source_selectable/data_source_selectable.tsx

Modify the button of selectable component to fix the title overflow issue

Modify the button of selectable component to fix the title overflow issue

---

CHANGELOG.md
src/plugins/workspace/opensearch_dashboards.json
src/plugins/workspace/public/plugin.test.ts
src/plugins/workspace/public/plugin.ts

Hide datasource and settings menu in dashboard management when in workspace
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/6453
In workspace
Not in workspace
When set workspace feature enabled in YML and entering workspace, the data source and advanced settings menu will be hidden. These two menus will show after exiting workspace.

Hide datasource and settings menu in dashboard management when in workspace

---

examples/multiple_data_source_examples/public/application.tsx
examples/multiple_data_source_examples/public/components/data_source_list_active_example.tsx
examples/multiple_data_source_examples/public/components/data_source_list_all_example.tsx
examples/multiple_data_source_examples/public/components/home.tsx
src/plugins/data_source_management/public/components/data_source_aggregated_view/__snapshots__/data_source_aggregated_view.test.tsx.snap
src/plugins/data_source_management/public/components/data_source_aggregated_view/data_source_aggregated_view.scss
src/plugins/data_source_management/public/components/data_source_aggregated_view/data_source_aggregated_view.test.tsx
src/plugins/data_source_management/public/components/data_source_aggregated_view/data_source_aggregated_view.tsx
src/plugins/data_source_management/public/components/data_source_menu/__snapshots__/data_source_menu.test.tsx.snap
src/plugins/data_source_management/public/components/data_source_menu/data_source_menu.test.tsx
src/plugins/data_source_management/public/components/data_source_menu/data_source_menu.tsx
src/plugins/data_source_management/public/components/data_source_menu/types.ts

Based on discussion from UX, this PR will refactor the `DataSourceAggregatedView`. 
**TODO:**
N/A
https://github.com/opensearch-project/OpenSearch-Dashboards/assets/73027756/cdfb6a2d-c153-4159-bc25-ec37393729a3
https://github.com/opensearch-project/OpenSearch-Dashboards/assets/73027756/94f09d29-457d-41ea-bc3d-4e809a052da7
Used the developer example plugin to test 3 scenarios of `DataSourceAggregatedView`:
- **When there is an `activeDataSourceId` and `displayAllCompatibleDataSources: false`**: This will render the switch to show only the selected components
- **When nothing is selected and `displayAllCompatibleDataSources: false`**: This will render the switch and show an empty state
- **When `displayAllCompatibleDataSources: true`**: The `activeDataSourceIds` is ignored, all datasources …

[MDS] Refactor DataSourceAggregatedView

---

src/core/public/saved_objects/saved_objects_client.ts
src/core/server/index.ts
src/core/server/mocks.ts
src/core/server/plugins/plugin_context.test.ts
src/core/server/plugins/types.ts
src/core/server/saved_objects/index.ts
src/core/server/saved_objects/service/lib/repository.test.js
src/core/server/saved_objects/service/lib/repository.ts
src/core/server/saved_objects/service/lib/search_dsl/query_params.test.ts
src/core/server/saved_objects/service/lib/search_dsl/query_params.ts
src/core/server/saved_objects/service/lib/search_dsl/search_dsl.ts
src/core/server/saved_objects/types.ts
src/plugins/workspace/common/constants.ts
src/plugins/workspace/server/integration_tests/routes.test.ts
src/plugins/workspace/server/permission_control/client.mock.ts
src/plugins/workspace/server/permission_control/client.test.ts
src/plugins/workspace/server/permission_control/client.ts
src/plugins/workspace/server/plugin.test.ts
src/plugins/workspace/server/plugin.ts
src/plugins/workspace/server/routes/index.ts
src/plugins/workspace/server/saved_objects/index.ts
src/plugins/workspace/server/saved_objects/integration_tests/workspace_saved_objects_client_wrapper.test.ts
src/plugins/workspace/server/saved_objects/workspace_saved_objects_client_wrapper.test.ts
src/plugins/workspace/server/saved_objects/workspace_saved_objects_client_wrapper.ts
src/plugins/workspace/server/types.ts
src/plugins/workspace/server/utils.test.ts
src/plugins/workspace/server/utils.ts
src/plugins/workspace/server/workspace_client.ts

backport fb31b2def6a6200425492d772a8d0b1bdfcbe132 from #6052 
This PR is for manual backport #6052 to 2.x branch.
#6051 
See #6052 
- skip

[Backport 2.x][Workspace]Add permission control logic for workspace

---

changelogs/fragments/6527.yml
src/plugins/workspace/server/saved_objects/workspace_id_consumer_wrapper.test.ts
src/plugins/workspace/server/saved_objects/workspace_id_consumer_wrapper.ts
src/plugins/workspace/server/saved_objects/workspace_saved_objects_client_wrapper.test.ts
src/plugins/workspace/server/saved_objects/workspace_saved_objects_client_wrapper.ts

when doing permission check, it will filter workspace list and verify there at least have 1 workspace user have permission, otherwise it will throw exception.
The bug is that, if we pass an empty array, that will go through this check and throw exception.
#6528
- fix: permission check failed with empty workspace for find method

[BUG] Fix permission check failed with empty workspace for find method

---

changelogs/fragments/6544.yml
src/plugins/saved_objects_management/opensearch_dashboards.json
src/plugins/saved_objects_management/public/management_section/mount_section.tsx
src/plugins/saved_objects_management/public/management_section/objects_table/components/__snapshots__/flyout.test.tsx.snap
src/plugins/saved_objects_management/public/management_section/objects_table/components/flyout.test.tsx
src/plugins/saved_objects_management/public/management_section/objects_table/components/flyout.tsx
src/plugins/saved_objects_management/public/management_section/objects_table/saved_objects_table.tsx
src/plugins/saved_objects_management/public/management_section/saved_objects_table_page.tsx
src/plugins/saved_objects_management/public/plugin.ts

- Add `dataSourceManagement` as an optional plugin of saved obeect manamgent plugin
- get picker compoenent by `const DataSourceSelector = dataSourceManagement.ui `, instead of direct inport
- Make Datasource selector non-clearable
- remove the usage of `hideLocalCluster`, and no need pass to DataSourceSelector as props
- this change will also let the default label to be rendered successfully
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/6369
fix https://github.com/opensearch-project/OpenSearch-Dashboards/issues/6546
- With datasource enabled and localCluster hidden and no avaliable data sources. It should disable the import button
- With datasource enabled, and localCluster shown, no other avaliable data sources.
- With datasource enabled, and LocalCluster shown, …

Refactor saved object management plugin to use datasourceManagement ui API to get DataSourceSelector

---

CHANGELOG.md
src/plugins/data_source_management/public/components/data_source_selectable/__snapshots__/data_source_selectable.test.tsx.snap
src/plugins/data_source_management/public/components/data_source_selectable/data_source_selectable.tsx
src/plugins/data_source_management/public/components/data_source_view/__snapshots__/data_source_view.test.tsx.snap
src/plugins/data_source_management/public/components/data_source_view/data_source_view.tsx
src/plugins/data_source_management/public/components/drop_down_header/__snapshots__/drop_down_header.test.tsx.snap
src/plugins/data_source_management/public/components/drop_down_header/drop_down_header.tsx

fix on data source selectable and readonly component are not consistent
Related Issue: https://github.com/opensearch-project/OpenSearch-Dashboards/issues/6535
Describe the bug
* The height of the popover header should be consistent between the read-only and selectable
* The stroke around the header looks better in the read-only popover, the floating line between the search field and the header looks a bit weird. This might be a part of next item.
* It looks like additional padding is added to the selectable popover content
- fix: fix on data source selectable and readonly component are not consistent

Fix on data source selectable and readonly component are not consistent

---

examples/multiple_data_source_examples/public/components/data_source_list_active_example.tsx
examples/multiple_data_source_examples/public/components/data_source_list_all_example.tsx
src/plugins/data_source_management/public/components/data_source_aggregated_view/__snapshots__/data_source_aggregated_view.test.tsx.snap
src/plugins/data_source_management/public/components/data_source_aggregated_view/data_source_aggregated_view.scss
src/plugins/data_source_management/public/components/data_source_aggregated_view/data_source_aggregated_view.tsx
src/plugins/data_source_management/public/components/data_source_menu/types.ts
src/plugins/data_source_management/public/components/data_source_selectable/__snapshots__/data_source_selectable.test.tsx.snap
src/plugins/data_source_management/public/components/data_source_view/__snapshots__/data_source_view.test.tsx.snap
src/plugins/data_source_management/public/components/drop_down_header/__snapshots__/drop_down_header.test.tsx.snap
src/plugins/data_source_management/public/components/drop_down_header/drop_down_header.tsx

Refactors the UI Components for the datasource dropdown menu and the aggregate view. Specifically, the `disabled` cursor is removed and the dropdown header has the text vertically aligned. Some minor enhancements also made to aggregate view as well.
#6533 
https://github.com/opensearch-project/OpenSearch-Dashboards/assets/73027756/c59f67c3-9f5d-49f1-a185-6cc8ae9a2887
- skip

[MDS] Refactor dropdown header + Aggregate view UI

---

changelogs/fragments/6524.yml
src/plugins/workspace/server/saved_objects/integration_tests/saved_objects_wrapper_for_check_workspace_conflict.test.ts
src/plugins/workspace/server/saved_objects/saved_objects_wrapper_for_check_workspace_conflict.test.ts
src/plugins/workspace/server/saved_objects/saved_objects_wrapper_for_check_workspace_conflict.ts

This PR handles data sources and advanced settings specially to make `global objects` will be correctly handled inside workspace.
For 2.14:
- Always list data sources from global.
- Prevent data sources being created inside workspace.
- Prevent data sources being imported inside workspace.
For the long future:
- Prevent advanced settings being created inside workspace.
- Prevent advanced settings being imported inside workspace.
For the visualizations and dashboards that rely on the data sources, when importing, the reference id won't be regenerated per https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/src/core/server/saved_objects/import/regenerate_ids.ts#L41. So if users import visualizations along with data sources into a workspace, only the visualizations will be …

[Workspace] Handle data sources and advanced settings as global object.

---

src/plugins/data_source_management/public/components/data_source_selectable/__snapshots__/data_source_selectable.test.tsx.snap
src/plugins/data_source_management/public/components/data_source_selectable/data_source_selectable.tsx

Disables the keyboard icon badge in the `DataSourceSelectable` component. Also sets the `singleSelection` to `"always"`.
https://github.com/opensearch-project/OpenSearch-Dashboards/assets/73027756/45518171-ed68-4013-b913-b4c39bbf8323
Clicked and used `Tab` + arrow keys to check that the icon is disabled.
- skip

[MDS] Update Selectable props

---

src/plugins/workspace/opensearch_dashboards.json
src/plugins/workspace/public/utils.test.ts
src/plugins/workspace/public/utils.ts

User can choose the feature of Dashboards Management when user create/update a workspace.
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/6574
1. Clone the latest code and run yarn osd bootstrap
2. Modify config/opensearch_dashboards.yml, add workspace.enabled: true
3. Run yarn start --no-base-path
4. Create a workspace choose the feature of Dashboard Management
- feat: [Workspace] Make dashboards management available

[Workspace] Make dashboards management available

---

src/plugins/data_source_management/public/components/data_source_menu/create_data_source_menu.test.tsx
src/plugins/data_source_management/public/components/data_source_menu/create_data_source_menu.tsx
src/plugins/data_source_management/public/components/data_source_menu/index.ts
src/plugins/data_source_management/public/components/utils.ts
src/plugins/data_source_management/public/index.ts
src/plugins/data_source_management/public/plugin.ts
src/plugins/navigation/public/top_nav_menu/__snapshots__/top_nav_menu.test.tsx.snap
src/plugins/navigation/public/top_nav_menu/top_nav_menu.test.tsx
src/plugins/navigation/public/top_nav_menu/top_nav_menu.tsx

In this change, we changed to pass data source menu to top nav via function instead of using the component, this way we avoid coupling the plugin level props into the top nav menu component
https://github.com/opensearch-project/OpenSearch-Dashboards/assets/17714150/b0090572-06ec-4580-bef9-ca599ee02019
The following steps were performed in the recording:
1. mount data source list all view along with the topnav menu, will see the component mounted, default data source is shown, no local cluster is showing since hide local cluster setting is true
2. mount data source list active view along with the topnav menu, will see the component mounted, default data source is shown , no local cluster is showing since hide local cluster setting is true
3. mount data source single readonly along with the …

[Multiple Datasource] Pass data source menu to top nav via function instead of using component

---

.github/workflows/build_and_test_workflow.yml

Bump `codecov/codecov-action` to v4.
PRs originating from forked repos will not need a token:
`The PR is happening in a forked repo. Using tokenless upload.`
However, PRs from within the repo, ie from feature branches or backports, will require a token.
- skip

Bump `codecov/codecov-action` to v4

---

src/plugins/workspace/public/plugin.ts

When user is in workspace ,dashboard management section will filter data source management menu. Currently the filter logic judges wrong id, which is data source instead data source management.
- skip

Fix wrong data source management filter id

---

CHANGELOG.md
changelogs/fragments/6427.yml
src/core/public/application/application_service.test.ts
src/core/public/application/application_service.tsx
src/core/public/application/index.ts
src/core/public/application/integration_tests/application_service.test.tsx
src/core/public/application/types.ts
src/core/public/chrome/chrome_service.tsx
src/core/public/chrome/nav_links/to_nav_link.test.ts
src/core/public/chrome/nav_links/to_nav_link.ts
src/core/public/core_system.ts
src/core/public/index.ts
src/plugins/home/public/plugin.ts
src/plugins/opensearch_dashboards_overview/public/plugin.ts
src/plugins/workspace/public/components/workspace_menu/workspace_menu.test.tsx
src/plugins/workspace/public/components/workspace_menu/workspace_menu.tsx
src/plugins/workspace/public/plugin.ts
src/plugins/workspace/public/utils.test.ts
src/plugins/workspace/public/utils.ts

Home page, as well as workspace create page / workspace list page, which is supposed to be only visited out of any workspace, now is enabled to be accessed by clicking the home icon or enter the url manually in the browser.
This PR introduces a new field `workspaceAvailability` inside App, which indicates the availability of the application based on workspace. This field can bring two benefits:
1. When navigate between apps, plugins and core application are using the `navigateToApp` method. By using the workspaceAvailability field, workspace is able to do the hard navigation in a central place.
2. The workspaceAvailability field can be used in workspace create page to filter applications that should not be visible inside workspace. For now we filter out home overview page and all the …

[Workspace] Add workspaceAvailability field into application

---

changelogs/fragments/6625.yml
src/plugins/workspace/public/utils.test.ts
src/plugins/workspace/public/utils.ts

User can not choose the feature of dashboard overview when create/update a workspace.
closes https://github.com/opensearch-project/OpenSearch-Dashboards/issues/6624
1. Clone the latest code and run yarn osd bootstrap
2. Modify config/opensearch_dashboards.yml, add workspace.enabled: true
3. Run yarn start --no-base-path
4. Create/update a workspace
- feat: [Workspace] Hide dashboard overview

[Workspace] Hide dashboard overview

---

src/plugins/workspace/public/components/workspace_menu/workspace_menu.test.tsx
src/plugins/workspace/public/components/workspace_menu/workspace_menu.tsx

Revert the changes inside [src/plugins/workspace/public/components/workspace_menu](https://github.com/opensearch-project/OpenSearch-Dashboards/pull/6427/files#diff-907ad2efa095285762230d1f2131f64d24c6f03e80f2a5a1ea4122a73a4cf20b) from #6427 as it introduces a bug that the left navigation won't close after clicking any of the menu inside the collapsedNavHeader.
- skip

[Workspace] fix: Navigate to apps by using hard refresh in collasibleNavHeader

---

.github/workflows/build_and_test_workflow.yml

ChromeDriver hasn't been doing a good job of keeping up with Chrome releases. This has broken our CI. Until confidence in the ChromeDriver release pipeline is restored, this change locks down the version of Chrome we use in our CI.
1. Look at the ***`Stable`*** column of [Linux](https://chromiumdash.appspot.com/releases?platform=Linux) releases. Linux has a lot less releases than Windows.
2. Hit the ***`i`*** next to the major version you want. From experience, the minor and patch versions don't matter in this process.
3. Take note of ***`Branch Base Position`***. In this case, I was looking for v122 and the number was `1250580`.
4. Open Chromium's snapshot repository for [Windows](https://commondatastorage.googleapis.com/chromium-browser-snapshots/index.html?prefix=Win_x64/) and …

Lock Chrome version until ChromeDriver's release pipeline is fixed

---

src/core/server/saved_objects/import/check_conflict_for_data_source.test.ts
src/core/server/saved_objects/import/check_conflict_for_data_source.ts
src/core/server/saved_objects/import/create_saved_objects.test.ts
src/core/server/saved_objects/import/create_saved_objects.ts
src/core/server/saved_objects/import/types.ts
src/core/server/saved_objects/import/utils.test.ts
src/core/server/saved_objects/import/utils.ts
src/plugins/vis_type_timeseries/server/lib/services.ts
src/plugins/vis_type_timeseries/server/lib/test_utils/test_params.json
src/plugins/vis_type_timeseries/server/lib/timeseries_visualization_client_wrapper.test.ts
src/plugins/vis_type_timeseries/server/lib/timeseries_visualization_client_wrapper.ts
src/plugins/vis_type_timeseries/server/plugin.ts

This PR adds datasource references to TSVB visualizations, which are needed to successfully export/import the object in MDS world. This PR also adds import logic to select a datasource.
Closes #6290
**Recording:**
https://github.com/opensearch-project/OpenSearch-Dashboards/assets/73027756/96f1711f-bee7-44b6-8034-6dd385bfc1a0
**Test case steps:**
1. Add sample data
2. Navigate to the TSVB edit page and change the datasource 
3. Go to saved objects management page and navigate to the visualization
4. In references, this should be modified to add the correct datasource
5. If the datasource is updated in the TSVB edit page, so too will the datasource reference
6. If the local cluster is used, the datasource reference will be removed.
**Test cases:**
1. Non-MDS TSVB visualization import to …

[MDS] TSVB Add import logic

---

CHANGELOG.md
src/plugins/data_source_management/public/components/data_source_aggregated_view/__snapshots__/data_source_aggregated_view.test.tsx.snap
src/plugins/data_source_management/public/components/data_source_aggregated_view/data_source_aggregated_view.tsx
src/plugins/data_source_management/public/components/data_source_menu/__snapshots__/create_data_source_menu.test.tsx.snap
src/plugins/data_source_management/public/components/data_source_menu/__snapshots__/data_source_menu.test.tsx.snap
src/plugins/data_source_management/public/components/data_source_selectable/__snapshots__/data_source_selectable.test.tsx.snap
src/plugins/data_source_management/public/components/data_source_selectable/data_source_selectable.test.tsx
src/plugins/data_source_management/public/components/data_source_selectable/data_source_selectable.tsx
src/plugins/data_source_management/public/components/data_source_view/__snapshots__/data_source_view.test.tsx.snap
src/plugins/data_source_management/public/components/data_source_view/data_source_view.tsx
src/plugins/data_source_management/public/components/popover_button/popover_button.test.tsx
src/plugins/data_source_management/public/components/popover_button/popover_button.tsx

Extract the button component for datasource picker to avoid duplicate code
* Add multiple datasources and click on button to see if it work as expected
- fix: Extract the button component for datasource picker to avoid duplicate code

Extract the button component for datasource picker to avoid duplicate code

---

src/plugins/data_source/server/data_source_service.mock.ts
src/plugins/data_source/server/plugin.ts
src/plugins/data_source/server/routes/fetch_data_source_metadata.test.ts
src/plugins/data_source/server/saved_objects/data_source_saved_objects_client_wrapper.test.ts
src/plugins/data_source/server/saved_objects/data_source_saved_objects_client_wrapper.ts
src/plugins/data_source/server/util/constants.ts

Add endpoint validation to create data source API, by testing if endpoint is reachable, using the same logic as what's behind "test connection" feature
#6517 
1. go to create datasource page, and create one with invalid OpenSearch endpoint, e.g. google.com
2. click test connection, it should fail as expected
3. click create data source, it should fail too, as the endpoint is not a valid endpoint
4. switch to use a valid opensearch domain
5. both test connection and create data source should pass
- feat: Add endpoint validation to create data source API

[MD] Add endpoint validation to create data source API

---

changelogs/fragments/6648.yml
src/plugins/data_source/server/plugin.ts

Fix datasource conntection failure introduced by https://github.com/opensearch-project/OpenSearch-Dashboards/commit/0c114cea86127a8d445c1299d51924459b36c981#diff-a01a6007a1a466a29810fbf0689bc607c3c3dfc9d3f7713da9bbf653beb92ef8R176
- fix: Fix datasource  test connect error

Fix datasource conntection failure

---

changelogs/fragments/6648.yml
src/plugins/data_source/server/plugin.ts

manually backport commit b29d90e8277b878b1d534ce22cb6c03170f18746 of  https://github.com/opensearch-project/OpenSearch-Dashboards/pull/6648
- skip

[Manual backport 2.x][MD]Fix datasource connection failure (#6648)

---

CHANGELOG.md
src/plugins/region_map/opensearch_dashboards.json
src/plugins/region_map/public/choropleth_layer.js
src/plugins/region_map/public/region_map_type.js
src/plugins/region_map/public/region_map_visualization.js
src/plugins/region_map/public/services.ts
src/plugins/region_map/server/routes/opensearch.ts

This PR adds the ability to use multi data source in Region maps. In API level, this PR contains updates for:
```
POST api/geospatial/_indices
POST api/geospatial/_search
POST api/geospatial/_mappings
```
Part of https://github.com/opensearch-project/dashboards-maps/issues/584
https://github.com/opensearch-project/OpenSearch-Dashboards/assets/90288540/332cbfde-199d-4949-b38d-d4d7f2c75e2f
Tests will be added in functional test repo in another PR
- skip

Support multi data source in Region map

---

packages/osd-std/src/clean.test.ts
packages/osd-std/src/clean.ts
packages/osd-std/src/index.ts
src/core/server/legacy/logging/legacy_logging_server.test.ts
src/core/server/legacy/logging/legacy_logging_server.ts
src/core/server/logging/layouts/conversions/message.ts
src/core/server/logging/layouts/json_layout.test.ts
src/core/server/logging/layouts/json_layout.ts
src/core/server/logging/layouts/pattern_layout.test.ts

Backport https://github.com/opensearch-project/OpenSearch-Dashboards/commit/c89d3047d46ca809b6540c0fab8db33c6e736c09 from https://github.com/opensearch-project/OpenSearch-Dashboards/pull/6402.

[Manual Backport 1.3] Replace control characters before logging (#6402)

---

changelogs/fragments/6669.yml
src/plugins/workspace/server/plugin.ts
src/plugins/workspace/server/saved_objects/workspace_ui_settings_client_wrapper.test.ts
src/plugins/workspace/server/saved_objects/workspace_ui_settings_client_wrapper.ts

A new wrapper, workspace_ui_settings, has been introduced by workspace plugin. When a user attempts to access an invalid workspace, OSD will display plain JSON instead of a user-friendly web page. This PR primarily addresses the issue by adding a `try catch` wrapper to the `client.get` method.
As well as an error log in OSD:
- Use the branch to bootstrap and enable workspace feature flag
- Type an invalid url like `http://localhost:5601/w/123/app/workspace_overview`
- An error page with error message saying: `Saved object [workspace/123] not found` should be found.
- fix: optimization on handling invalid workspace id in workspace_ui_settings wrapper

[Workspace] Fix: optimization on handling invalid workspace id in workspace_ui_settings wrapper

---

changelogs/fragments/6668.yml
src/plugins/workspace/server/saved_objects/integration_tests/saved_objects_wrapper_for_check_workspace_conflict.test.ts
src/plugins/workspace/server/saved_objects/saved_objects_wrapper_for_check_workspace_conflict.test.ts
src/plugins/workspace/server/saved_objects/saved_objects_wrapper_for_check_workspace_conflict.ts

When importing data sources and configuration into a workspace with overwrite: true, we will prevent the creation of such objects. However, to ensure that objects dependent on the disallowed ones continue to function properly, we must leave their references untouched.
When user tries to import with `overwrite: true`, the logic will go into https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/src/core/server/saved_objects/import/check_conflicts.ts#L90, and in order to keep the references untouched, we just need to make sure the logic won't go into the branch of https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/src/core/server/saved_objects/import/check_conflicts.ts#L105 , which sets a new id reference to the current item. And the result it is consumed …

[Workspace] Fix: keep disallowed types when importing with overwrite

---

CHANGELOG.md
src/plugins/vis_builder/public/application/utils/get_top_nav_config.test.tsx
src/plugins/vis_builder/public/application/utils/get_top_nav_config.tsx
src/plugins/vis_builder/public/application/utils/use/use_saved_vis_builder_vis.ts
src/plugins/vis_builder/public/embeddable/vis_builder_embeddable.tsx
src/plugins/vis_builder/public/plugin.ts
src/plugins/vis_builder/public/saved_visualizations/transforms.ts
src/plugins/visualizations/public/index.ts

- Save filter and query in vb
- Clean filterManager when start vb
- Add opensearch_dashboards_context to embeddable. This can add filter and query in the expression.
* https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5643 This issue is about filter and query are not saved.
The fix is this part in the src/plugins/vis_builder/public/application/utils/get_top_nav_config.tsx
```
const searchSourceInstance = savedVisBuilderVis.searchSourceFields;
searchSourceInstance.query = data.query.queryString.getQuery() || null;
searchSourceInstance.filter = data.query.filterManager.getFilters() || null;
savedVisBuilderVis.searchSourceFields = searchSourceInstance;
```
VisBuilder is using searchSourceFields to save states. This is different from Discover which uses searchSource. This fix …

[VisBuilder ] Fix filter and query bugs in the saved objects

---

changelogs/fragments/6636.yml
src/plugins/vis_builder/public/application/components/top_nav.tsx

Before this PR, can't save when filter or query change. 
After this PR: 
1) if the canvas is empty, can not save filter and query updates. This is expected due to empty canvas error `The canvas is empty. Add some aggregations before saving` 
2) if the canvas is not empty, can save filter and query updates.
https://github.com/opensearch-project/OpenSearch-Dashboards/assets/79961084/e2c970a1-b6d6-4829-9020-14d8e389878c
3) for embedded vis builder in dashboard, when edit vb, update filter and query can also enable save button
https://github.com/opensearch-project/OpenSearch-Dashboards/assets/79961084/ac20eae8-0ded-4817-a56f-24156b0eb75f
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5645
We will need to add some cypress tests. Here is the meta issue to track …

[BUG] Allow Save in Top Nav Menu to capture filter and query

---

.lycheeignore

Fixes broken link cheker
- skip

[Chore] Fix Link checker for adobe urls

---

changelogs/fragments/6683.yml
src/plugins/discover/public/application/components/data_grid/data_grid_table.tsx
src/plugins/discover/public/application/components/default_discover_table/default_discover_table.tsx
src/plugins/discover/public/application/components/default_discover_table/table_header.tsx
src/plugins/discover/public/application/components/default_discover_table/table_row.tsx
test/functional/apps/dashboard/dashboard_time_picker.js
test/functional/apps/home/_sample_data.ts

This change addresses three problems by lazy-loading additional rows when infinitely scrolling the table:
1. While a page size of 10 helped speed up rendering, scrolling users encountered the bottom of the table too often. By continuing to load a page but lazy-loading 4 additional pages (for a total of 5), that frequency is reduced.
2. As new rows were mounted, their content pushed cell boundaries and caused column widths to change; this was unpleasant and distracting. After the first page is loaded, the columns are allowed to adjust to the content and then the dimensions are fixed to prevent that.
3. Allow the paginated experience have the 50 pages that were previously allocated to it.
TBA
https://github.com/opensearch-project/OpenSearch-Dashboards/assets/3527403/ec727395-8b4c-4632-a2e7-7 …

Optimize scrolling behavior of Discover table

---

src/legacy/ui/ui_render/bootstrap/startup.js.hbs

Fixes `undefined` value in font family for next theme. The key should be `v8` not `default`. Skipping changelog entry as this is a follow-up fix to https://github.com/opensearch-project/OpenSearch-Dashboards/pull/5652, which hasn't yet been released.
Before:
After:
Validated locally. Reviewers can test by inspecting the generated `/startup.js` file when using the next theme and validating that the font-family starts with `Source Sans 3`, not `undefined`.
- skip

fix (startup): fix font theme key

---

src/plugins/dev_tools/public/plugin.ts

register right navigation for dev tool only when console is enabled
console is disabled
console is enabled
1. use `yarn start --console.enabled=false`, dev tool and top right navigation won't be registered.
2. use  `yarn start`, dev tool and top right navigation will both be registered.
- skip

fix: register right navigation for dev tool only when console is enabled

---

changelogs/fragments/6712.yml
config/opensearch_dashboards.yml
src/core/public/chrome/ui/header/right_navigation_button.tsx
src/core/server/mocks.ts
src/core/server/opensearch_dashboards_config.ts
src/core/server/plugins/plugin_context.test.ts
src/core/server/plugins/types.ts
src/legacy/server/config/schema.js
src/plugins/console/server/plugin.ts
src/plugins/dev_tools/public/plugin.ts

https://github.com/opensearch-project/OpenSearch-Dashboards/pull/6712
1. Add `opensearchDashboards.futureNavigation` config and control dev tool top right nav button.
2. Mark rightNavigationButton component as experimental.

[Manual Backport 2.x] feat: add config for topRightNavigation

---

changelogs/fragments/6678.yml
src/plugins/data_source_management/public/components/constants.tsx
src/plugins/data_source_management/public/components/data_source_aggregated_view/data_source_aggregated_view.test.tsx
src/plugins/data_source_management/public/components/data_source_aggregated_view/data_source_aggregated_view.tsx
src/plugins/data_source_management/public/components/data_source_multi_selectable/data_source_multi_selectable.tsx
src/plugins/data_source_management/public/components/data_source_selectable/data_source_selectable.test.tsx
src/plugins/data_source_management/public/components/data_source_selectable/data_source_selectable.tsx
src/plugins/data_source_management/public/components/no_data_source/__snapshots__/no_data_source.test.tsx.snap
src/plugins/data_source_management/public/components/no_data_source/no_data_source.test.tsx
src/plugins/data_source_management/public/components/no_data_source/no_data_source.tsx
src/plugins/data_source_management/public/components/utils.test.ts
src/plugins/data_source_management/public/components/utils.ts

This PR modifies the toast + popover message to cover the edge case that datasources exist but all datasources are filtered out by the `dataSourceFilter` for the multi-select, selectable, and aggregated view (both read-all and read-select) components
N/A
Toast message + popover should be shown below.
All testing was done when `data_sources.enabled: true` and `data_source.hideLocalCluster: true` (these are the only two configurations that can show the `NoDataSources` component + toast.
Both cases should show the `Manage data sources` button.
- This should show the message `No data sources connected yet. Connect your data sources to get started.` 
- This should show the message `No compatible data sources are available. Add a compatible data source.`
- fix: [MDS] Add a new message to data …

[MDS] Modify toast + popover warning to include incompatible datasources

---

changelogs/fragments/6759.yml
src/plugins/discover/public/application/components/sidebar/lib/field_filter.ts

This change is aimed at making the  **Search Field Name Filter** in Discover Case Insensitive. 
- Navigate to Discover Page
- Type a Field Name in the Search a Field Name search bar
- Validate the field shown in the left navigation pane contains the Field name (irrespective of the case)
- feat: Make Field Name Search Filter Case Insensitive

Make Field Name Search Filter Case Insensitive

---

changelogs/fragments/6752.yml
src/plugins/data_source_management/public/components/data_source_error_menu/__snapshots__/data_source_error_menu.test.tsx.snap
src/plugins/data_source_management/public/components/data_source_error_menu/data_source_error_menu.test.tsx
src/plugins/data_source_management/public/components/data_source_item/data_source_item.test.tsx
src/plugins/data_source_management/public/components/data_source_multi_selectable/data_source_multi_selectable.test.tsx

Add test for data_source_error_menu, data_source_item, data_source_multi_selectable
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/6748
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/6749
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/6750
```
PASS  src/plugins/data_source_management/public/components/data_source_multi_selectable/data_source_multi_selectable.test.tsx (5.229 s)
DataSourceMultiSelectable
✓ should render normally with local cluster not hidden (9 ms)
✓ should render normally with local cluster hidden (1 ms)
✓ should show toasts when exception happens (2 ms)
✓ should callback when onChange happens (227 ms)
✓ should return correct state when ui Settings provided (2 ms)
✓ should return correct state when ui Settings …
```

[Multiple Datasource Test] Add test for error_menu, item, data_source_multi_selectable

---

.github/CODEOWNERS
MAINTAINERS.md
changelogs/fragments/6788.yml

Here are zhyuanqi's current merge contributions, total contributions, and issues:
PR： https://github.com/opensearch-project/OpenSearch-Dashboards/pulls?q=is%3Apr+author%3Azhyuanqi+is%3Amerged
Review: https://github.com/opensearch-project/OpenSearch-Dashboards/pulls?q=is%3Apr+reviewed-by%3Azhyuanqi
Issues: https://github.com/opensearch-project/OpenSearch-Dashboards/issues?q=is%3Aissue+author%3Azhyuanqi
- doc: Add zhyuanqi as maintainer

add @zhyuanqi as a maintainer

---

.github/CODEOWNERS
MAINTAINERS.md
changelogs/fragments/6790.yml

This change moves @BSFishy to emeritus maintainer.
- doc: Move @BSFishy to emeritus maintainer

Move @BSFishy to emeritus maintainer

---

changelogs/fragments/6799.yml
docs/index.html
docs/openapi/README.md
docs/openapi/saved_objects/index.html
docs/openapi/saved_objects/saved_objects.yml

This change adds OpenAPI specification for get and create saved object APIs, and also added a readme with instructions about how to spin off swagger UI
Related to https://github.com/opensearch-project/OpenSearch-Dashboards/issues/6719
Below is after running `npx serve` locally in the folder where the yaml file is located
- doc: Add OpenAPI specification for GET and CREATE saved object API

Add OpenAPI specification for get and create saved object APIs 

---

changelogs/fragments/6776.yml
src/plugins/workspace/server/integration_tests/routes.test.ts
src/plugins/workspace/server/workspace_client.ts

enclose workspace name with double quotes when doing duplication check, so that it will not interpret by simply query syntax and do match it with exact match (workspace.name field type is `keyword`)
```
GET .kibana/_search
{
"profile": "true", 
"query": {
"simple_query_string": {
"query": "\"demo workspace\"",
"fields": ["workspace.name"]
}
}
}
```
It will convert to `TermQuery` that's exact match.
```json
"profile": {
"shards": [
{
"id": "[qYfwnwnoTiqalgsnAT9rjA][.kibana_12][0]",
"inbound_network_time_in_millis": 0,
"outbound_network_time_in_millis": 0,
"searches": [
{
"query": [
{
"type": "TermQuery",
"description": "workspace.name:demo workspace",
"time_in_nanos": 9585,
"breakdown": {
...
}
}
]
...
}
],
"aggregations": []
}
]
}
``` …

[Workspace] Fix workspace name duplication check

---

changelogs/fragments/6721.yml
src/core/server/saved_objects/service/lib/repository.ts
src/plugins/usage_collection/common/constants.ts
src/plugins/usage_collection/server/config.ts
src/plugins/usage_collection/server/plugin.ts
src/plugins/usage_collection/server/report/store_report.test.ts
src/plugins/usage_collection/server/report/store_report.ts
src/plugins/usage_collection/server/routes/index.ts
src/plugins/usage_collection/server/routes/report_metrics.ts
src/plugins/usage_collection/server/types.ts

This PR introduces Server Side batching of UI metric reports sent by clients to reduce the number of updates taking place at OpenSearch.
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/6375
- Enable UI Metric Collector by setting the usageCollection.uiMetric.enabled to true 
- Ascertain the ui_metric in usage section is empty when you call the `/api/stats?extended=true&legacy=true&exclude_usage=false`
- Make a POST call to the `/api/ui_metric/report` with the following request body `{"report":{"reportVersion":1,"uiStatsMetrics":{"console-count-GET_cat.indices":{"key":"console-count-GET_cat.indices","appName":"console","eventName":"GET_cat.indices","type":"count","stats":{"min":0,"max":1,"avg":0.5,"sum":21}}}}}`
- Call …

Add Server Side batching for UI Metric Collectors

---

changelogs/fragments/6822.yml
src/plugins/data_source/server/saved_objects/data_source_saved_objects_client_wrapper.test.ts
src/plugins/data_source/server/saved_objects/data_source_saved_objects_client_wrapper.ts

- Fix endpoint validation by passing in request when creating datasource client. Even tho request is an optional param, but there might be data source auth types registered that from external plugin, that will depend on the request. So we still need to pass it in when creating the client. Note that for existing MDS auth types, noauth, basic auth, sigV4, they don't depend on "request".
- added test
- fix: fix endpoint validation by passing in request when creating datasource client

[MD] Fix server sider endpoint validation by passing in request when creating datasource client

---

changelogs/fragments/6782.yml
src/plugins/data/common/data_frames/data_frame_utils.test.ts
src/plugins/data/common/data_frames/utils.ts

provides a formatting util function meant to convert quick range time (such as 'now-15m') to datetimes that can be understood. 
related to: https://github.com/kavilla/qlDashboards/pull/4 
- fix: Quickrange selection fix

fix for quickrange to use datemath to parse datetime strings

---

changelogs/fragments/6777.yml
src/plugins/vis_type_vega/public/data_model/vega_parser.ts

With unsupported type `ppl`
The error message before:
`url: {"%type%": "${type}"} is not supported`
It should be:
`url: {"%type%": "ppl"} is not supported`
- fix: error message is not formatted in vis_type_vega url parser.

fix vega visualization error message not been formatted

---

changelogs/fragments/6851.yml
src/plugins/home/server/services/sample_data/data_sets/util.test.ts
src/plugins/home/server/services/sample_data/data_sets/util.ts

This PR is for fixing #6850 , there are two changes in this PR.
1. Add back references update for index pattern saved objects when import sample data
2. Add unit tests to verify references has been updated when generate sample data by data source method
#6850 
Now data source connection will be exists in index patterns list after sample data imported. 
1. Checkout the branch code and run `yarn osd bootstrap`
2. Add `data_source.enabled: true` to `config/opensearch_dashboards.yml` 
3. Run `yarn start --no-base-path` start OSD server
4. Add some data source in the [data source management page](http://localhost:5601/app/management/opensearch-dashboards/dataSources)
5. Go to [import sample data page](http://localhost:5601/app/home#/tutorial_directory) select new added data source
6. Click …

Fix index pattern data source reference not updated in sample data

---

changelogs/fragments/6855.yml
docs/_sidebar.md
docs/openapi/saved_objects/saved_objects.yml

Add example in create API for create index pattern, vega visualizatinn, dashboards for docs
- doc: Add example for saved object creation part for openapi doc.

Add example in create API for create index pattern, vega visualizatinn, dashboards for docs

---

changelogs/fragments/6856.yml
docs/openapi/saved_objects/saved_objects.yml

Add openAPI doc for saved_object find api
- doc: Add openAPI doc for saved_object find api

Add openAPI doc for saved_object find api

---

changelogs/fragments/6859.yml
docs/openapi/saved_objects/saved_objects.yml

This change adds OpenAPI specification for bulk create and bulk update saved object APIs.
Related to https://github.com/opensearch-project/OpenSearch-Dashboards/issues/6719
bulk create
bulk update
run npx serve and verify the api via swagger UI
- doc: Add OpenAPI specification for bulk create and bulk update saved object APIs

Add OpenAPI specification for bulk create and bulk update saved object APIs

---

changelogs/fragments/6860.yml
docs/openapi/saved_objects/saved_objects.yml

Add OpenAPI specification for bulk_get saved object APIs
- doc: Add OpenAPI specification for bulk_get saved object APIs

Add OpenAPI specification for bulk_get saved object APIs

---

changelogs/fragments/6864.yml
docs/openapi/saved_objects/saved_objects.yml

This change adds OpenAPI specification for update, delete and migrate saved object API.
Related to https://github.com/opensearch-project/OpenSearch-Dashboards/issues/6719
update
delete
migrate
run npx serve and see the specification being used in swagger
- doc: Add OpenAPI specification for update, delete and migrate saved object API

Add OpenAPI specification for update, delete and migrate saved object API

---

changelogs/fragments/6855.yml
docs/openapi/saved_objects/saved_objects.yml

Add example in create API for create index pattern, vega visualizatinn, dashboards for docs
https://github.com/opensearch-project/OpenSearch-Dashboards/pull/6855
Auto backport failed, so manually generated this file. 
Removed the docs/_sidebar.md change as the docs/_sidebar.md does not exists in branch 2.x

[Backport 2.x] Add example in create API for create index pattern, vega visualizatinn, dashboards for docs

---

changelogs/fragments/6879.yml
examples/multiple_data_source_examples/public/components/data_source_view_example.tsx

This change fix the bug introduced by #6827 which added new prop but then removed.
fixes https://github.com/opensearch-project/OpenSearch-Dashboards/issues/6878
data source view example
After the fix, running dashboards locally and the error reported went away, data source view example renders successfully
- fix: remove unused import and property which broke compilation

[Bug] Remove unused import and property

---

changelogs/fragments/6843.yml
src/plugins/data_source_management/public/components/constants.tsx
src/plugins/data_source_management/public/components/data_source_aggregated_view/data_source_aggregated_view.tsx
src/plugins/data_source_management/public/components/data_source_multi_selectable/data_source_multi_selectable.tsx
src/plugins/data_source_management/public/components/data_source_selectable/data_source_selectable.tsx
src/plugins/data_source_management/public/components/data_source_selector/data_source_selector.tsx
src/plugins/data_source_management/public/components/data_source_table/data_source_table.tsx
src/plugins/data_source_management/public/components/data_source_view/data_source_view.tsx
src/plugins/data_source_management/public/components/edit_data_source/edit_data_source.tsx
src/plugins/data_source_management/public/components/utils.test.ts
src/plugins/data_source_management/public/components/utils.ts
src/plugins/data_source_management/public/index.ts
src/plugins/data_source_management/public/mocks.ts
src/plugins/data_source_management/public/plugin.ts

1. Add getDefaultDataSourceId and getDefaultDataSourceId$ function, unify in DSM and export in setup for other plugins to use
2. Unify default data source ui settings id
https://github.com/opensearch-project/dashboards-assistant/pull/191#discussion_r1616799996
- refactor: Unify getDefaultDataSourceId and export

[Multi Datasource] Unify getDefaultDataSourceId and export

---

changelogs/fragments/6811.yml
src/plugins/vis_builder/public/application/components/data_tab/dropbox.scss
src/plugins/visualizations/public/persisted_state/persisted_state.ts

This aims to fix the following Bugs in Vis builder.
1. https://github.com/opensearch-project/OpenSearch-Dashboards/issues/6680
2. https://github.com/opensearch-project/OpenSearch-Dashboards/issues/6679
1. https://github.com/opensearch-project/OpenSearch-Dashboards/issues/6680
2. https://github.com/opensearch-project/OpenSearch-Dashboards/issues/6679
Follow the steps mentioned in the above issues to check the expected behaviour.
https://github.com/opensearch-project/OpenSearch-Dashboards/assets/38322563/ef43fac7-04b3-47cc-8820-5d55aa1d9f37
- fix: Bug Fixes for Vis Builder

Bug Fixes for Vis Builder

---

changelogs/fragments/6770.yml
packages/osd-plugin-generator/package.json
yarn.lock

https://github.com/opensearch-project/OpenSearch-Dashboards/issues/6769
- security: [CVE-2024-33883] Bump ejs from `3.1.7` to `3.1.10`

[CVE-2024-33883] Bump ejs from `3.1.7` to `3.1.10`

---

changelogs/fragments/6780.yml
src/plugins/discover/public/migrate_state.ts
src/plugins/discover/public/migrate_states.test.ts

Allow migrate global state. I also thought about capture all other states besides `_g`, `_a, and `_q` like customized states, but our current helper func requiring us to know the key in advance. Given customized keys might have various formats, it is easy to make new bugs. 
```
export function getStatesFromOsdUrl(
url: string = window.location.href,
keys?: string[]
): Record<string, unknown> {
const query = parseUrlHash(url)?.query;
if (!query) return {};
const decoded: Record<string, unknown> = {};
Object.entries(query)
.filter(([key]) => (keys ? keys.includes(key) : true))
.forEach(([q, value]) => {
decoded[q] = decodeState(value as string);
});
return decoded;
}
```
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/6766 …

[Discover][Bug] Migrate global state from legacy URL

---

changelogs/fragments/6908.yml
src/plugins/data_source_management/public/components/utils.test.ts
src/plugins/data_source_management/public/components/utils.ts

In https://github.com/opensearch-project/OpenSearch-Dashboards/pull/6237/files, we introduced default data source, and expect that if default data source is not set, the get call to uisettings would return null, which is not always the case. See in the recordings that for cases that a default data source is accidentally removed from UI, the data source id is empty string from `api/opensearch-dashboards/settings` API call. Thus instead of checking if the returned value is exactly null, we need to check if it is not blank/empty. 
fixes #6835
https://github.com/opensearch-project/OpenSearch-Dashboards/assets/17714150/1bf891b2-2e4b-4625-b840-f876ae14dfab
In the recording, the following steps were performed:
- enable data source
before change:
- check the api/opensearch-dashboards/settings …

[BUG] fix default data source bug

---

changelogs/fragments/6492.yml
package.json
yarn.lock

Bumps the tar package from 6.1.13 to 6.2.1. It is a complete version of https://github.com/opensearch-project/OpenSearch-Dashboards/pull/6397 which is linked to CVE(https://github.com/opensearch-project/OpenSearch-Dashboards/issues/6488) mentioned here.
- security: [CVE-2024-28863] Bump tar from 6.1.11 to 6.2.1

Bump tar from 6.1.13 to 6.2.1

---

config/opensearch_dashboards.yml

Workspace is not compatible with multi-tenancy feature, when user enable workspace it's better to disable multi-tenancy. Add comments and disable multi-tenancy instruction for `workspace.enabled` configuration.
partial of https://github.com/opensearch-project/security-dashboards-plugin/issues/1819
#4944 
- skip

Add disable multi-tenancy instruction when enable workspace

---

changelogs/fragments/6928.yml
src/core/server/saved_objects/export/get_sorted_objects_for_export.test.ts
src/core/server/saved_objects/export/get_sorted_objects_for_export.ts

We want to avoid exposing data source credentials during export, even tho they are encrypted values.
The data source objects in the exported `nd.json` file will look like below, with credentials fields replaced with placeholder values. Import will still succeed.
```
{
"attributes": {
"auth": {
"type": "username_password",
"credentials": {
"password": "pleaseUpdateCredentials",
"username": "pleaseUpdateCredentials"
},
},
"dataSourceVersion": "",
"description": "",
"endpoint": "https://search-new-m6-nbkrrsakxmzqk3oay3olromnzi.us-west-2.es.amazonaws.com/",
"installedPlugins": [],
"title": "test1"
},
"id": "18abe7e0-2297-11ef-b143-fdc11e1ac86d",
"migrationVersion": {
"data-source": "2.4.0"
},
"references": [],
"type": "data-source",
"updated_at": "2024-06-04T17:23:02.110Z",
"version": …
```

[MD]Use placeholder for data source credentials fields when export saved object

---

src/core/server/index.ts
src/core/server/saved_objects/import/index.ts
src/core/server/saved_objects/import/utils.test.ts
src/core/server/saved_objects/import/utils.ts
src/plugins/home/server/services/sample_data/data_sets/util.test.ts
src/plugins/home/server/services/sample_data/data_sets/util.ts

Modify the adding sample data part for timeline to add data source name if customer has enabled MDS
https://github.com/opensearch-project/OpenSearch-Dashboards/pull/6123
https://github.com/opensearch-project/OpenSearch-Dashboards/assets/53279298/5866ecc2-d5bf-4ef9-bb61-026fb7649ef9
Please see screenshot
- fix: Modify the adding sample data part for timeline

Modify the adding sample data part for timeline

---

plugins-extra/query_enhancements/common/index.ts
plugins-extra/query_enhancements/public/plugin.tsx
plugins-extra/query_enhancements/public/query_assist/components/call_outs.tsx
plugins-extra/query_enhancements/public/query_assist/components/query_assist_bar.tsx
plugins-extra/query_enhancements/public/query_assist/components/query_assist_input.tsx
plugins-extra/query_enhancements/public/query_assist/components/submit_button.tsx
plugins-extra/query_enhancements/public/query_assist/hooks/use_generate.ts
plugins-extra/query_enhancements/public/query_assist/utils/create_extension.tsx
plugins-extra/query_enhancements/server/routes/query_assist/agents.ts
src/plugins/data/public/ui/query_editor/_query_editor.scss
src/plugins/data/public/ui/query_editor/query_editor.tsx
src/plugins/data/public/ui/query_editor/query_editor_top_row.tsx
src/plugins/data/public/ui/search_bar_extensions/index.ts
src/plugins/data/public/ui/search_bar_extensions/index.tsx
src/plugins/data/public/ui/search_bar_extensions/search_bar_extension.test.tsx
src/plugins/data/public/ui/search_bar_extensions/search_bar_extension.tsx
src/plugins/data/public/ui/search_bar_extensions/search_bar_extensions.test.tsx
src/plugins/data/public/ui/search_bar_extensions/search_bar_extensions.tsx

Addresses most of the comments in #6894 and #6895
* pass dependencies to isEnabled func
* add lazy and memo to search bar extensions
* move ppl specific strings out from query assist
* prevent setstate after hook unmounts
* add max-height to search bar extensions
* prevent setstate after component unmounts
* move ml-commons API to common/index.ts
* improve i18n and accessibility usages
* add hard-coded suggestions for sample data indices
Pending items:
- add tests to query assist
- extract `AGENT_REQUEST_OPTIONS` to UI settings https://github.com/opensearch-project/OpenSearch-Dashboards/pull/6895#discussion_r1626635544
- add advanced settings for disabling all search bar extensions https://github.com/opensearch-project/OpenSearch-Dashboards/pull/6895#discussion_r1626615166

[Discover-next] Address comments for search bar extensions and query assist

---

changelogs/fragments/6940.yml
src/plugins/home/server/services/sample_data/data_sets/util.test.ts
src/plugins/home/server/services/sample_data/data_sets/util.ts

This PR adds TSVB support for "Add Sample Data" when MDS is enabled 
Closes #6936 
https://github.com/opensearch-project/OpenSearch-Dashboards/assets/73027756/8d6e5006-63e3-46e0-bbfe-2d0d0dd115d8
https://github.com/opensearch-project/OpenSearch-Dashboards/assets/73027756/2e0a0346-4a49-41af-b990-fdc0869e6f06
```bash
$ yarn test:jest src/plugins/home/server/services/sample_data/data_sets/util.test.ts
yarn run v1.22.22
$ scripts/use_node scripts/jest src/plugins/home/server/services/sample_data/data_sets/util.test.ts
ciGroups []
jest-haste-map: duplicate manual mock found: index
The following files share their name; please delete one of them:
* <rootDir>/src/plugins/vis_type_vega/public/expressions/__mocks__/index.ts
* <rootDir>/src/core/server/saved_objects/import/__mocks__/index.ts
PASS …
```

[MDS] Fix sample data to use datasources for TSVB visualizations

---

CHANGELOG.md
src/core/server/saved_objects/import/import_saved_objects.test.ts
src/core/server/saved_objects/import/import_saved_objects.ts
src/core/server/saved_objects/import/types.ts
src/core/server/saved_objects/import/validate_object_id.test.ts
src/core/server/saved_objects/import/validate_object_id.ts
src/core/server/saved_objects/routes/import.ts
src/plugins/saved_objects_management/public/lib/import_file.ts
src/plugins/saved_objects_management/public/management_section/objects_table/components/flyout.test.tsx
src/plugins/saved_objects_management/public/management_section/objects_table/components/flyout.tsx
src/plugins/workspace/server/saved_objects/integration_tests/saved_objects_wrapper_for_check_workspace_conflict.test.ts

Do not support import data source object to Local cluster when not enable data source
Do not support import data source object to Local cluster when not enable data source
https://github.com/opensearch-project/OpenSearch-Dashboards/pull/6395
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/6115

[Manual Backport 2.x] [Multiple DataSource] Do not support import data source object to Local cluster when not enable data source 

---

changelogs/fragments/6920.yml
src/plugins/data_source_management/public/service/data_source_selection_service.test.ts
src/plugins/data_source_management/public/service/data_source_selection_service.ts
src/plugins/navigation/public/top_nav_menu/__snapshots__/top_nav_menu.test.tsx.snap

Add removedComponentIds for data source selection service. 
In the implementation of some selector components,  it may call onSelect function in promise.then or after await, which could be executed later than componentWillUnmount. 
If some components do not use memorize and frequently unmount and mount, it is possible that the set function is triggered   and selected data source stored after the componentWillUnmount emit. The security analytics page is currently known which may cause this problem.
No UI updates
- feat: [Multi DataSource] Add removedComponentIds for data source selection service

[Multi DataSource] Add removedComponentIds for data source selection service

---

CHANGELOG.md
package.json

Coming from downstream where we recently added json5 for a feature, our distribution build is failing due to an [outdated json5 version](https://github.com/opensearch-project/dashboards-observability/issues/1861#issuecomment-2151148902) used here. We could downgrade our dependency, but considering that the json5 changelog has [no breaking changes for the core API](https://github.com/json5/json5/blob/main/CHANGELOG.md), it seems more straightforward to update it here directly.
Resolves build failures in https://github.com/opensearch-project/dashboards-observability/issues/1861.
N/A
Trusting CI to catch any issues on this one; according to the json5 changelog this is a no-op.
- skip: update json5 dependency from 1.0.1 to 2.2.3

Update json5 dependency

---

config/opensearch_dashboards.yml
package.json
plugins-extra/query_enhancements/common/index.ts
plugins-extra/query_enhancements/public/plugin.tsx
plugins-extra/query_enhancements/public/search/sql_async_search_interceptor.ts
plugins-extra/query_enhancements/server/plugin.ts
plugins-extra/query_enhancements/server/routes/index.ts
plugins-extra/query_enhancements/server/search/async/sql_async_facet.ts
plugins-extra/query_enhancements/server/search/async/sql_async_jobs_facet.ts
plugins-extra/query_enhancements/server/search/sql/sql_async_search_strategy.ts
src/plugins/data/common/constants.ts
src/plugins/data/common/data_frames/_df_cache.ts
src/plugins/data/common/data_frames/_session_cache.ts
src/plugins/data/common/data_frames/types.ts
src/plugins/data/common/data_frames/utils.ts
src/plugins/data/common/query/types.ts
src/plugins/data/common/search/search_source/fetch/get_search_params.ts
src/plugins/data/common/search/search_source/search_source.ts
src/plugins/data/common/types.ts
src/plugins/data/public/query/query_string/query_string_manager.ts
src/plugins/data/public/search/search_service.ts
src/plugins/data/public/search/types.ts
src/plugins/data/public/ui/query_editor/query_editor.tsx
src/plugins/data/public/ui/query_editor/query_editor_top_row.tsx
src/plugins/data/public/ui/query_string_input/query_string_input.tsx
src/plugins/data/public/ui/settings/settings.ts
src/plugins/data/server/search/search_service.ts
src/plugins/data/server/ui_settings.ts

* Adding direct query support to external datasources in Discover using query enhancements.
* Created new language for async queries
* Modify existing polling logic from `dashboards-observability`
Pending items:
* Loading state indicators
* Use `UI_SETTINGS` for polling interval
* Stop calls to [this line](https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/src/plugins/data/public/search/search_service.ts#L150) to avoid error toasts when querying external datasource
Duplicate of #6906, reopening on clean branch

[Discover-Next] Async Queries Implemention

---

changelogs/fragments/6948.yml
src/plugins/home/server/services/sample_data/data_sets/logs/saved_objects.ts
src/plugins/home/server/services/sample_data/data_sets/util.ts

Currently visual consistency sample dashboard is failing, see [future playground](https://future.playground.opensearch.org/app/dashboards#/view/685e7470-23b8-11ef-8207-97463748ffab_c39012d0-eb7a-11ed-8e00-17d7d50cd7b2?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-7d,to:now))&_a=(description:'',filters:!(),fullScreenMode:!f,options:(hidePanelTitles:!f,useMargins:!t),query:(language:kuery,query:''),timeRestore:!t,title:'Visual%20Consistency%20Dashboard_aos11',viewMode:view))
This PR fixes the issue by
- refactor the static sample visualizations objects of web log Visual Consistency dashboards to support data source
- Add handling for visbuilder type to support data source by updating references
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/6857 …

Fix web log sample visualization & vis-builder not rendering with data source issue

---

src/plugins/data_explorer/public/components/app.tsx
src/plugins/data_explorer/public/components/app_container.tsx
src/plugins/data_explorer/public/utils/use/shallow_equal.test.ts
src/plugins/data_explorer/public/utils/use/shallow_equal.ts
src/plugins/discover/public/application/view_components/utils/use_search.ts

This PR avoids re-rendering the entire AppContainer when data services update. The re-render is caused by history object which is in AppMountParameters. This history object is part of the application's routing context and can change frequently as the url is updated by query, filter or time range. Each change in the history object could potentially trigger a re-render of the AppContainer and its child components.
With this PR, the AppContainer will not be re-loaded. Instead, each component, like Canvas and Panel, will be re-rendered based on the updates from data.
NA
* new workflow
https://github.com/opensearch-project/OpenSearch-Dashboards/assets/79961084/ab505ca5-4045-4813-8f88-16b8df2733e1
- feat: [Data Explorer] Allow render from View directly, not from Data Explorer

[Data Explorer] Allow render from View directly, not from Data Explorer

---

packages/osd-pm/dist/index.js
yarn.lock

Replaced version spam in the lockfile with the greatest one used for each pattern to combine entries.
Rebuilt @osd/pm to consume the updated packages.
Cannot bump `aws-sdk` beyond 2.1313.0 because of a deprecation error message added.
Cannot bump `@types/lodash` because of its impact.
- skip

[2.x] Cleanup yarn.lock

---

changelogs/fragments/6964.yml
src/core/public/overlays/sidecar/components/sidecar.scss

Update sidecar z-index from 1000 to 1001.
The mask in UI component will cover the entire screen, even if their child element flyout has left or right, they will still cover the entire screen. As a container independent of OSD, sidecar should not be blocked by redundant masks.
Before
After
- fix: Update z-index of sidecar container to make it more than mask, from 1000 to 1001.

Update sidecar z-index style

---

src/core/server/saved_objects/import/check_conflict_for_data_source.test.ts
src/core/server/saved_objects/import/check_conflict_for_data_source.ts
src/core/server/saved_objects/import/create_saved_objects.test.ts
src/core/server/saved_objects/import/create_saved_objects.ts
src/core/server/saved_objects/import/import_saved_objects.ts

Modify the import for timeline visualization to includes data source name in MDS scenario
https://github.com/opensearch-project/OpenSearch-Dashboards/pull/6919
https://github.com/opensearch-project/OpenSearch-Dashboards/assets/53279298/fa6df05f-d93c-4bc2-9ffc-8a84678a6bc5
https://github.com/opensearch-project/OpenSearch-Dashboards/assets/53279298/d7f131e5-8cf1-44b2-a70c-2fa9bb8140a4
https://github.com/opensearch-project/OpenSearch-Dashboards/assets/53279298/2cb59bef-5589-416e-87e7-6fad3758d5e1
- fix: Modify the import for timeline visualization to includes data source name in MDS scenario

Modify the import for timeline visualization to includes data source name in MDS scenario

---

plugins-extra/query_enhancements/public/search/sql_async_search_interceptor.ts
plugins-extra/query_enhancements/server/routes/index.ts
plugins-extra/query_enhancements/server/search/async/sql_async_facet.ts
plugins-extra/query_enhancements/server/search/ppl/ppl_search_strategy.ts
src/plugins/data/common/search/search_source/fetch/get_search_params.ts
src/plugins/data/common/search/search_source/search_source.ts
src/plugins/data/public/search/search_service.ts
src/plugins/data/server/search/search_service.ts

* Stops index pattern from being created when selecting external datasource
* Checks to see if `datasource.name` exists before creating dataframe
* Handles PPL error in request
#6957

[WIP] Async Queries Followup

---

changelogs/fragments/6385.yml
changelogs/fragments/6395.yml
changelogs/fragments/6919.yml

Adding missing change log for the following PRs:
https://github.com/opensearch-project/OpenSearch-Dashboards/pull/6395
https://github.com/opensearch-project/OpenSearch-Dashboards/pull/6919
https://github.com/opensearch-project/OpenSearch-Dashboards/pull/6385
- skip

Add missing change log for 2.15 MDS PRs

---

src/plugins/data/public/ui/filter_bar/filter_bar.tsx
src/plugins/data/public/ui/query_string_input/legacy_language_switcher.tsx
src/plugins/data/public/ui/query_string_input/query_bar_top_row.tsx
src/plugins/discover/public/application/components/data_grid/data_grid_table.tsx
src/plugins/discover/public/application/components/default_discover_table/table_header.tsx
src/plugins/discover/public/application/components/default_discover_table/table_header_column.tsx
src/plugins/discover/public/application/components/default_discover_table/table_row.tsx
src/plugins/discover/public/application/components/doc_viewer_links/doc_viewer_links.tsx
src/plugins/discover/public/application/components/sidebar/discover_sidebar.tsx
src/plugins/discover/public/application/components/table/table_row.tsx
src/plugins/discover/public/application/components/top_nav/get_top_nav_links.tsx
src/plugins/discover/public/application/view_components/canvas/index.tsx
src/plugins/navigation/public/top_nav_menu/top_nav_menu_data.tsx
src/plugins/navigation/public/top_nav_menu/top_nav_menu_item.tsx

Manual backport of https://github.com/opensearch-project/OpenSearch-Dashboards/pull/6898
- skip

[Manual Backport 2.x] Add missing aria-label for discover page

---

src/plugins/vis_builder/public/application/components/data_tab/utils/get_available_fields.test.ts
src/plugins/vis_builder/public/application/components/data_tab/utils/get_available_fields.ts

Add Scripted Field Support in Vis Builder.    
https://github.com/opensearch-project/OpenSearch-Dashboards/assets/38322563/332a8663-fa5c-4612-aeff-5c6c2564f633
1. Create an Index pattern with scripted fields
2. Navigate to Vis Builder and verify if the scripted field is available in the left side panel
- feat: Add Scripted Field Support in Vis Builder

Add Scripted Field Support in Vis Builder

---

changelogs/fragments/6983.yml
src/plugins/discover/public/application/components/default_discover_table/helper.test.tsx
src/plugins/discover/public/application/components/default_discover_table/helper.tsx
src/plugins/discover/public/application/components/doc_viewer/doc_viewer_render_tab.tsx

https://github.com/opensearch-project/OpenSearch-Dashboards/issues/6982
- fix: [Discover] Check if the timestamp is already included to remove duplicate col

[BUG][Discover] Check if the timestamp is already included to remove duplicate col

---

changelogs/fragments/7058.yml
src/plugins/discover/public/application/components/default_discover_table/default_discover_table.tsx

The last column on a table wider than the screen was crushed.
Fixes #7056

[Discover] Allow the last column of a table wider than the window to show up properly

---

changelogs/fragments/7069.yml
src/plugins/vis_type_timeline/server/lib/fetch_data_source_id.test.ts
src/plugins/vis_type_timeline/server/lib/fetch_data_source_id.ts

Based in UX requirement, update error message in timeline visualization when MDS disabled.
#7000 
- fix: Update error message in timeline visualization when MDS disabled

Update error message in timeline visualization when MDS disabled

---

changelogs/fragments/7087.yml
packages/osd-ui-framework/src/global_styling/mixins/_global_mixins.scss
src/plugins/vis_type_vislib/public/vislib/components/tooltip/_hierarchical_tooltip_formatter.js

Remove angular related comment and code
- fix: Remove angular related comment and code

Remove angular related comment and code

---

changelogs/fragments/7106.yml
package.json
src/plugins/data/common/data_frames/utils.ts
src/plugins/data/common/index_patterns/index_patterns/index_patterns.ts
src/plugins/data/common/search/search_source/search_source.ts
src/plugins/data/public/search/search_service.ts
src/plugins/data/server/search/search_service.ts

Parses user string between `::datasource::` to get the data source Then appends the dataSourceId in the meta.
Also creates the data frame before the interceptor to keep the meta info passed around.
If this gets accepted follow ups need to happen:
* should be ensuring the virtual index pattern includes the data source name with the index pattern name to avoid conflicts and a weird state.
* some reason dataframe is being always wiped out the first call in the search source. need to fix so that the schema is persisted
* weird initial load state. likely just too many things at once so we should make sure the usual and fresh experience is respected
* better indicator on the datasource, or just autocomplete that displays all the datasource connections when user types initial `::`.
Rebase of …

[Discover-Next] Adding datasources support for dataframes

---

src/plugins/discover/public/application/utils/state_management/discover_slice.test.tsx
src/plugins/discover/public/application/utils/state_management/discover_slice.tsx
src/plugins/discover/public/application/view_components/canvas/discover_table.tsx
src/plugins/discover/public/application/view_components/canvas/index.tsx
src/plugins/discover/public/application/view_components/canvas/top_nav.tsx
src/plugins/discover/public/application/view_components/context/index.tsx
src/plugins/discover/public/application/view_components/panel/index.tsx
src/plugins/discover/public/url_generator.ts
src/plugins/vis_builder/public/application/components/top_nav.tsx
src/plugins/vis_builder/public/application/utils/state_management/visualization_slice.test.ts
src/plugins/vis_builder/public/application/utils/state_management/visualization_slice.ts
src/plugins/vis_builder/public/plugin.ts
src/plugins/vis_builder/public/types.ts
src/plugins/vis_builder/server/capabilities_provider.ts

* add save query logic in Discover
* add save query logic in VisBuilder
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5942
- fix: Load saved queries into Discover correctly
* discover save query
https://github.com/opensearch-project/OpenSearch-Dashboards/assets/79961084/939cce87-a711-45c9-b38f-207c8a4e350d
* visbuilder save query
https://github.com/opensearch-project/OpenSearch-Dashboards/assets/79961084/ca88a01d-0214-4b51-a0e2-951bf848ceae

[Discover] Allow save query to load correctly in Discover

---

changelogs/fragments/7100.yml
src/core/server/plugins/discovery/plugin_manifest_parser.test.ts
src/core/server/plugins/discovery/plugin_manifest_parser.ts
src/core/server/plugins/plugin.test.ts
src/core/server/plugins/plugin.ts
src/core/server/plugins/types.ts
src/plugins/data_source/common/data_sources/types.ts
src/plugins/index_pattern_management/opensearch_dashboards.json
src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/components/step_data_source/components/header/header.tsx
src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/types.ts
src/plugins/index_pattern_management/public/components/utils.ts

* This PR is to add support of `Version Decoupling` in `Index Patterns Dashboards Plugin`
* This is achieved mainly by add a new entry `supportedOSDataSourceVersions` in the plugin manifest file
*  For `Index Patterns Plugin` it would support all versions of OS clusters so the supported range would be `>=1.0.0`
* The current behavior is to filter out the incompatible data sources out of the data source list.
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/7099
https://github.com/opensearch-project/OpenSearch-Dashboards/assets/99905560/883852c5-51a2-4b50-9226-f84d873721b0
- fix: [MDS][Version Decoupling] Add support of Version Decoupling in Index Patterns Dashboards Plugin

[Multiple Datasource][Version Decoupling] Support Version Decoupling in Index Patterns Dashboards Plugin

---

changelogs/fragments/7077.yml
src/plugins/data/public/ui/query_editor/query_editor.tsx
src/plugins/data/public/ui/query_editor/query_editor_extensions/query_editor_extensions.tsx
src/plugins/data/public/ui/query_editor/query_editor_top_row.tsx

Follow up for #7034, this PR
- addresses https://github.com/opensearch-project/OpenSearch-Dashboards/pull/7034#discussion_r1646749538
- addresses https://github.com/opensearch-project/OpenSearch-Dashboards/pull/7034#discussion_r1646750783
- fixes render order
- QueryEditorExtensions requires the container divs to be mounted first,
but in the previous implementation, extensions will be mounted first and
it relied on rerendering of queryEditorTopRow. Moving them into query
editor fixes the render order and ensures refs are set.
@AMoo-Miki I didn't use the object check `'[object Object]' !== Object.prototype.toString.call(configMap)`. I don't know what access user has, but if an attacker can arbitrarily alter `configMap`, the code will still break with something like
```tsx
configMap={
new …
```

Fix object empty check and minor perf issue in query editor extensions

---

changelogs/fragments/7060.yml
src/core/public/chrome/README.md
src/core/public/chrome/chrome_service.mock.ts
src/core/public/chrome/chrome_service.test.ts
src/core/public/chrome/chrome_service.tsx
src/core/public/chrome/index.ts
src/core/public/chrome/nav_group/index.ts
src/core/public/chrome/nav_group/nav_group_service.test.ts
src/core/public/chrome/nav_group/nav_group_service.ts
src/core/public/chrome/utils.test.ts
src/core/public/chrome/utils.ts
src/core/public/core_system.ts
src/core/public/index.ts
src/core/server/ui_settings/settings/navigation.test.ts
src/core/server/ui_settings/settings/navigation.ts
src/core/types/index.ts
src/core/types/nav_group.ts
src/core/utils/default_app_categories.ts
src/core/utils/default_nav_groups.ts
src/core/utils/index.ts
src/plugins/dashboard/public/application/components/dashboard_listing/__snapshots__/dashboard_listing.test.tsx.snap
src/plugins/dashboard/public/application/components/dashboard_top_nav/__snapshots__/dashboard_top_nav.test.tsx.snap
src/plugins/home/server/ui_settings.ts

This PR mainly introduces new interface to register and get useCases from chrome service, and it is a fundamental change for the new navigation.
closes #7061 
No UI changes.
As there is no place using the new interfaces introduced in this PR. You can refer to the test cases here:
src/core/public/chrome/chrome_service.test.ts
- feat: Introduce new interface for group

[navigation-next] feat: introduce new interface for group

---

changelogs/fragments/7149.yml
yarn.lock

* This one is to fix `SNYK-JS-AXIOS-6144788` by bump up `axios` to `1.7.2`
https://security.snyk.io/vuln/SNYK-JS-AXIOS-6144788
- security: [SNYK-JS-AXIOS-6144788] Bump axios to `1.7.2`

[CVE] Bump up axios to 1.7.2 to fix SNYK-JS-AXIOS-6144788

---

changelogs/fragments/7153.yml
yarn.lock

https://nvd.nist.gov/vuln/detail/CVE-2024-37890 requests to bump ws from `8.5.0` to `8.17.1` and from `7.5.7` to `7.5.10`
```
The vulnerability was fixed in ws@8.17.1 (e55e510) and backported to ws@7.5.10 (22c2876), ws@6.2.3 (eeb76d3), and ws@5.2.4 (4abd8f6). 
```
```
=> Found "ws@8.17.1"
- "_project_#@percy#cli#@percy#cli-command#@percy#core" depends on it
- Hoisted from "_project_#@percy#cli#@percy#cli-command#@percy#core#ws"
info Disk size without dependencies: "180KB"
info Disk size with unique dependencies: "180KB"
info Disk size with transitive dependencies: "180KB"
info Number of shared dependencies: 0
=> Found "jsdom#ws@7.5.10"
info This module exists because "_project_#jest#@jest#core#jest-config#jest-environment-jsdom#jsdom" depends on it.
info …
```

[CVE-2024-37890] Bump ws from `8.5.0` to `8.17.1` and from `7.5.7` to `7.5.10`

---

changelogs/fragments/7146.yml
src/core/server/plugins/discovery/plugin_manifest_parser.test.ts
src/core/server/plugins/discovery/plugin_manifest_parser.ts
src/core/server/plugins/plugin.test.ts
src/core/server/plugins/plugin.ts
src/core/server/plugins/types.ts
src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/components/step_data_source/components/header/header.test.tsx
src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/components/step_data_source/components/header/header.tsx
src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/types.ts
src/plugins/index_pattern_management/public/components/utils.ts

* This PR is to add support of `Version Decoupling` in `Index Patterns Dashboards Plugin`
* This PR is to add a new entry `requiredOSDataSourcePlugins` in the plugin manifest file
* The current behavior is to filter out the incompatible data sources out of the data source list.
* As called out in https://github.com/opensearch-project/OpenSearch-Dashboards/issues/7099#issuecomment-2202055323, will improve the general code coverage of Index Pattern plugin in separate changes.
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/7099
https://github.com/opensearch-project/OpenSearch-Dashboards/assets/99905560/23b11cf0-1f02-45e5-b75a-0511fa6bf3d3
- fix: [MDS][Version Decoupling] Add support of required backend plugins check on data sources

[Multiple Datasource][Version Decoupling] Add support of required backend plugins check on data sources

---

changelogs/fragments/7157.yml
src/plugins/data/public/ui/query_editor/_query_editor.scss
src/plugins/data/public/ui/query_editor/query_editor.tsx
src/plugins/data/public/ui/query_editor/query_editor_top_row.tsx
src/plugins/data/public/ui/search_bar/create_search_bar.tsx
src/plugins/data/public/ui/search_bar/search_bar.tsx
src/plugins/data/public/ui/types.ts
src/plugins/data/public/ui/ui_service.ts

Enables the editor to let plugins to mount their own data source component to the data source container.
Related to:
https://github.com/kavilla/queryEnhancements/pull/29
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/7129
`yarn start:enhancements`
- feat: query editor and dataframes datasources container

[Discover-next] add datasource container

---

changelogs/fragments/7152.yml
src/core/public/application/application_service.test.ts
src/core/public/application/types.ts
src/core/public/chrome/nav_links/to_nav_link.test.ts

In new overview page, we are showing description of each feature, in that case, we need to add a field `description` so that plugins can give the description for their features.
No UI changes
Only field change.
- feat: add description field in App.

[navigation-next]feat: add description field in App.

---

changelogs/fragments/7172.yml
src/plugins/data_source_management/public/components/data_source_aggregated_view/data_source_aggregated_view.test.tsx
src/plugins/data_source_management/public/components/data_source_aggregated_view/data_source_aggregated_view.tsx
src/plugins/data_source_management/public/components/data_source_menu/create_data_source_menu.test.tsx
src/plugins/data_source_management/public/components/data_source_multi_selectable/data_source_multi_selectable.test.tsx
src/plugins/data_source_management/public/components/data_source_multi_selectable/data_source_multi_selectable.tsx
src/plugins/data_source_management/public/components/data_source_selectable/data_source_selectable.test.tsx
src/plugins/data_source_management/public/components/data_source_selectable/data_source_selectable.tsx
src/plugins/data_source_management/public/components/data_source_selector/create_data_source_selector.test.tsx
src/plugins/data_source_management/public/components/data_source_selector/data_source_selector.test.tsx
src/plugins/data_source_management/public/components/data_source_selector/data_source_selector.tsx
src/plugins/data_source_management/public/components/utils.ts

* This one is to add fields `dataSourceVersion` and `installedPlugins` in all data source viewers.
* These two metadata would be consumed by plugins to perform data source filtering and decoupling check
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/7099
- fix: [MDS][Version Decoupling] Add dataSourceVersion' and  'installedPlugins in viewer returns

[Multiple Datasource][Version Decoupling] Add data source version and installed plugins in MDS data source viewer returns

---

changelogs/fragments/7183.yml
src/plugins/data/public/ui/query_editor/query_editor_extensions/query_editor_extension.test.tsx
src/plugins/data/public/ui/query_editor/query_editor_extensions/query_editor_extension.tsx

Query Assist feature depends on QueryEditorExtensions and datasource connections service. The change to the currently selected connection will be exposed through an observable ([ref](https://github.com/kavilla/queryEnhancements/blob/3543d510abe29464dd5aae9cc86418cc631ec653/public/data_source_connection/services/connections_service.ts#L75)), changing `isEnabled` to an observable makes it easier to update when the selected connection changes.
https://github.com/opensearch-project/OpenSearch-Dashboards/pull/7034#discussion_r1641572479
- feat: [QueryEditorExtensions] change `isEnabled` to an observable

[Discover-next] (QueryEditorExtensions) change isEnabled to an observable 

---

config/opensearch_dashboards.yml

Add a config in `opensearch_dashbaords.yml` file to force enable new nav/home and make the item in advanced setting read only. This is useful when workspace is enabled, that would help user have better UI experience for workspace.
```
uiSettings:
overrides:
"home:useNewHomePage": true
```
- skip

[Workspace]Add instruction for force enable new navigation for workspace

---

.github/workflows/build_and_test_workflow.yml
changelogs/fragments/7197.yml

Noticed here:
https://github.com/opensearch-project/OpenSearch-Dashboards/pull/7196
That we are running the full suite of tests even though CODEOWNERS was just changed.
n/a
- chore: Skip running tests for updates in CODEOWNERS

[OE] skip running tests if CODEOWNERS was change

---

changelogs/fragments/7192.yml
src/plugins/dashboard/public/application/components/dashboard_listing/__snapshots__/dashboard_listing.test.tsx.snap
src/plugins/dashboard/public/application/components/dashboard_top_nav/top_nav/__snapshots__/clone_modal.test.js.snap
src/plugins/dashboard/public/application/components/dashboard_top_nav/top_nav/clone_modal.tsx
src/plugins/dashboard/public/application/utils/get_no_items_message.tsx
src/plugins/data/public/ui/saved_query_form/save_query_form.tsx
src/plugins/discover/public/application/components/data_grid/data_grid_table_flyout.tsx
src/plugins/discover/public/application/components/top_nav/__snapshots__/open_search_panel.test.tsx.snap
src/plugins/discover/public/application/components/top_nav/open_search_panel.tsx
src/plugins/inspector/public/ui/__snapshots__/inspector_panel.test.tsx.snap
src/plugins/inspector/public/ui/inspector_panel.tsx
src/plugins/management/public/components/landing/landing.tsx
src/plugins/opensearch_dashboards_react/public/overview_page/overview_page_header/__snapshots__/overview_page_header.test.tsx.snap
src/plugins/opensearch_dashboards_react/public/overview_page/overview_page_header/overview_page_header.tsx
src/plugins/saved_objects/public/save_modal/__snapshots__/saved_object_save_modal.test.tsx.snap
src/plugins/saved_objects/public/save_modal/saved_object_save_modal.tsx
src/plugins/saved_objects_management/public/management_section/object_view/components/__snapshots__/header.test.tsx.snap
src/plugins/saved_objects_management/public/management_section/object_view/components/header.tsx
src/plugins/saved_objects_management/public/management_section/objects_table/components/__snapshots__/header.test.tsx.snap
src/plugins/saved_objects_management/public/management_section/objects_table/components/header.tsx
src/plugins/visualize/public/application/utils/get_table_columns.tsx

Refactor to use semantic headers for page, modal & flyout
- refactor: [Look&Feel]  Refactor to use semantic headers for page, modal & flyout

[Look&Feel] Refactor to use semantic headers for page, modal & flyout

---

changelogs/fragments/7235.yml
src/core/public/chrome/nav_group/nav_group_service.ts
src/core/public/index.ts
src/core/utils/default_nav_groups.ts
src/core/utils/index.ts

This PR will add all use case and enable plugins to declare itself visible in `all` use case.
- feat: Add all use case

[Navigation-next] Add all use case

---

changelogs/fragments/7232.yml
src/plugins/dev_tools/public/application.tsx
src/plugins/discover/public/application/components/doc_viewer/__snapshots__/doc_viewer.test.tsx.snap
src/plugins/discover/public/application/components/doc_viewer/doc_viewer.tsx
src/plugins/home/public/application/components/feature_directory.js
src/plugins/home/public/application/components/tutorial_directory.js
src/plugins/index_pattern_management/public/components/edit_index_pattern/tabs/tabs.tsx
src/plugins/index_pattern_management/public/components/field_editor/components/scripting_help/__snapshots__/help_flyout.test.tsx.snap
src/plugins/index_pattern_management/public/components/field_editor/components/scripting_help/help_flyout.tsx
src/plugins/vis_type_timeseries/public/application/components/vis_picker.js

Find all usage of `EuiTabs` and `EuiTabbedContent` and update them to use size small if not already.
- refactor: [Look&Feel] Use small EuiTabs and EuiTabbedContent across the board

[Look&Feel] Use small EuiTabs and EuiTabbedContent across the board

---

changelogs/fragments/7242.yml
src/plugins/workspace/public/plugin.test.ts
src/plugins/workspace/public/plugin.ts

This PR is for registering workspace settings under setup and settings. The workspace settings will link to the workspace list page. To support display link in the left navigation, need to update link status to visible when nav group enabled.
#7244
All changes working fine in the [feature/navigation-next](https://github.com/opensearch-project/OpenSearch-Dashboards/tree/feature/navigation-next) branch. Need to checkout the code and rebase `feature/navigation-next` branch.
Another way is to refer the `src/plugins/workspace/public/plugin.test.ts` unit test file. All changes have been covered in it.
- feat: [Workspace] Register workspace settings under setup and settings

[Workspace]Register workspace settings under setup and settings

---

changelogs/fragments/7213.yml
src/plugins/workspace/opensearch_dashboards.json
src/plugins/workspace/public/components/workspace_creator/workspace_creator.test.tsx
src/plugins/workspace/public/components/workspace_creator/workspace_creator.tsx
src/plugins/workspace/public/components/workspace_form/select_data_source_panel.tsx
src/plugins/workspace/public/components/workspace_form/types.ts
src/plugins/workspace/public/components/workspace_form/workspace_form.test.tsx
src/plugins/workspace/public/components/workspace_form/workspace_form.tsx
src/plugins/workspace/public/components/workspace_updater/workspace_updater.test.tsx
src/plugins/workspace/public/components/workspace_updater/workspace_updater.tsx
src/plugins/workspace/public/plugin.ts
src/plugins/workspace/public/types.ts

Hide select data source panel for non dashboard admin or when data source is disabled in workspace create/edit page
Non OSD admin
OSD admin
Dashboard admin and data source is enabled
Set username in `opensearchDashboards.dashboardAdmin.users` and `data_source.enabled: true`  in YML, then go to workspace create page or edit page, you will see select data source panel
Non Dashboard admin
Set other username in `opensearchDashboards.dashboardAdmin.users` in YML(If you don't set a value you will still be treated as dashboard admin), then go to workspace create page or edit page, you won't see select data source panel.
Data source disabled
Set `data_source.enabled: false` in YML, then go to workspace create page or edit page, you won't see select data source panel.
- feat: Hide select data …

[Workspace] Disable select data source panel for non dashboard admin in workspace create/edit page

---

changelogs/fragments/7107.yml
src/plugins/vis_builder/public/application/components/data_tab/config_panel.tsx
src/plugins/vis_builder/public/application/components/data_tab/constants.ts
src/plugins/vis_builder/public/application/components/data_tab/drag_drop/add_field_to_configuration.ts
src/plugins/vis_builder/public/application/components/data_tab/drag_drop/move_field_between_schemas.ts
src/plugins/vis_builder/public/application/components/data_tab/drag_drop/reorder_fields_within_schema.ts
src/plugins/vis_builder/public/application/components/data_tab/drag_drop/replace_field_in_configuration.ts
src/plugins/vis_builder/public/application/components/data_tab/dropbox.scss
src/plugins/vis_builder/public/application/components/data_tab/dropbox.tsx
src/plugins/vis_builder/public/application/components/data_tab/field.test.tsx
src/plugins/vis_builder/public/application/components/data_tab/field.tsx
src/plugins/vis_builder/public/application/components/data_tab/field_selector.scss
src/plugins/vis_builder/public/application/components/data_tab/field_selector.test.tsx
src/plugins/vis_builder/public/application/components/data_tab/field_selector.tsx
src/plugins/vis_builder/public/application/components/data_tab/index.tsx
src/plugins/vis_builder/public/application/components/data_tab/schema_to_dropbox.tsx
src/plugins/vis_builder/public/application/components/data_tab/use/use_dropbox.tsx
src/plugins/vis_builder/public/application/components/data_tab/utils/get_valid_aggregations.tsx
src/plugins/vis_builder/public/application/components/draggable_accordion.scss
src/plugins/vis_builder/public/application/components/draggable_accordion.tsx

This change aims to enhance the drag and drop functionality present within Vis-Builder. The enhancements are 
- Users can drag a new field from left panel and drop it over an existing field (replacing the existing field)
- User can move a selected field from one axis to an empty axis
- User can move a selected field from one axis to another axis replacing an existing field.
To support the Drag and Drop functionality the custom Drag and Drop containers were converted to Draggable and Droppable Components (part of OUI). Besides the OUIAccordion didn't support Dragging of the elements present within the accordion hence instead of using it a custom version of Accordion was used. 
#7015
https://github.com/opensearch-project/OpenSearch-Dashboards/assets/38322563/c559858b-0fb1-419c-b78c-27ca2393a …

Add Drag & Drop Across Axis Functionality to Vis Builder

---

changelogs/fragments/7270.yml
docs/openapi/index_patterns/index.html
docs/openapi/index_patterns/index_patterns.yml

Add OpenAPI specification for API for retrieving fields of index pattern
N/A
Go to the docs/openapi/index_patterns directory, and run `npx serve`, check webpage rendered on http://localhost:3000    
- doc: Add OpenAPI specification for API for retrieving fields of index patterns

Add OpenAPI specification for API for retrieving fields of index pattern

---

src/plugins/console/public/application/components/console_menu.tsx
src/plugins/data/public/ui/filter_bar/filter_item.tsx
src/plugins/data/public/ui/filter_bar/filter_options.tsx
src/plugins/discover/public/application/view_components/canvas/index.tsx
src/plugins/embeddable/public/lib/panel/panel_header/panel_actions/add_panel/saved_object_finder_create_new.tsx
src/plugins/index_pattern_management/public/components/create_button/create_button.tsx
src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/components/step_index_pattern/components/indices_list/indices_list.tsx
src/plugins/inspector/public/ui/inspector_view_chooser.tsx
src/plugins/inspector/public/views/data/components/download_options.tsx
src/plugins/inspector/public/views/requests/components/request_selector.tsx
src/plugins/saved_objects/public/finder/saved_object_finder.tsx
src/plugins/share/public/components/share_context_menu.tsx
src/plugins/share/public/components/url_panel_content.tsx
src/plugins/vis_default_editor/public/components/agg_add.tsx

Hold for @kgcreative and Viraj's signoff.

Condence context menus

---

changelogs/fragments/7188.yml
src/plugins/data_source_management/common/index.ts
src/plugins/data_source_management/public/components/constants.tsx
src/plugins/data_source_management/public/plugin.ts
src/plugins/workspace/server/plugin.ts
src/plugins/workspace/server/saved_objects/workspace_ui_settings_client_wrapper.test.ts
src/plugins/workspace/server/saved_objects/workspace_ui_settings_client_wrapper.ts
src/plugins/workspace/server/types.ts
src/plugins/workspace/server/utils.test.ts
src/plugins/workspace/server/utils.ts
src/plugins/workspace/server/workspace_client.test.ts
src/plugins/workspace/server/workspace_client.ts

Manual backport https://github.com/opensearch-project/OpenSearch-Dashboards/pull/7188
- skip

[Manual Backport][2.x][Workspace] [Data Source] feat: support workspace level default data source

---

src/plugins/embeddable/public/lib/panel/panel_header/panel_actions/add_panel/add_panel_flyout.tsx
src/plugins/embeddable/public/lib/panel/panel_header/panel_options_menu.tsx
src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/components/step_index_pattern/components/indices_list/__snapshots__/indices_list.test.tsx.snap
src/plugins/share/public/components/__snapshots__/share_context_menu.test.tsx.snap
src/plugins/visualizations/public/wizard/__snapshots__/new_vis_modal.test.tsx.snap
src/plugins/visualizations/public/wizard/type_selection/type_selection.tsx

Validate if all pattern guidances are applied in Dashboards,  and add what's missing. (except small buttons and inputs, which will be worked on separately)
Below are the items covered by with this PR
- skip

[Look&Feel] Apply missing pattern guidance to Dashboards experience

---

src/plugins/opensearch_dashboards_utils/public/history/redirect_when_missing.tsx

This PR removes unnecessary markdown rendering when handling [SavedObjectNotFound](https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/src/plugins/opensearch_dashboards_utils/common/errors/errors.ts#L51-L70) errors. The error rendering occurs [here](https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/src/plugins/opensearch_dashboards_utils/public/history/redirect_when_missing.tsx#L96-L123) and unnecessarily renders the text as markdown when the message will always be plain text based on the error type. 
- All CI checks pass
- chore: Remove unnecessary markdown rendering

Remove unnecessary markdown rendering

---

changelogs/fragments/7214.yml
config/opensearch_dashboards.yml
src/plugins/data_source/common/data_sources/types.ts
src/plugins/data_source/config.ts
src/plugins/data_source/server/plugin.ts
src/plugins/data_source_management/public/components/data_source_table/__snapshots__/data_source_table.test.tsx.snap
src/plugins/data_source_management/public/components/data_source_table/data_source_table.test.tsx
src/plugins/data_source_management/public/components/data_source_table/data_source_table.tsx
src/plugins/data_source_management/public/components/edit_data_source/components/edit_form/edit_data_source_form.test.tsx
src/plugins/data_source_management/public/components/edit_data_source/components/edit_form/edit_data_source_form.tsx
src/plugins/data_source_management/public/components/edit_data_source/components/header/header.test.tsx
src/plugins/data_source_management/public/components/edit_data_source/components/header/header.tsx
src/plugins/data_source_management/public/components/edit_data_source/edit_data_source.test.tsx
src/plugins/data_source_management/public/components/edit_data_source/edit_data_source.tsx
src/plugins/saved_objects_management/public/management_section/mount_section.tsx

Manual backport https://github.com/opensearch-project/OpenSearch-Dashboards/pull/7214
delete conflict file:
- src/plugins/data_source_management/public/components/data_source_home_panel/data_source_home_panel.tsx
- src/plugins/data_source_management/public/components/data_source_home_panel/data_source_home_panel.test.tsx
- skip

[Manual Backport][2.x][Data Source] Restrict to manage data source on the DSM UI

---

changelogs/fragments/7307.yml
src/plugins/data_source_management/public/components/edit_data_source/components/edit_form/edit_data_source_form.tsx
src/plugins/data_source_management/public/components/edit_data_source/components/update_aws_credential_modal/update_aws_credential_modal.test.tsx
src/plugins/data_source_management/public/components/edit_data_source/components/update_aws_credential_modal/update_aws_credential_modal.tsx
src/plugins/data_source_management/public/components/edit_data_source/components/update_password_modal/__snapshots__/update_password_modal.test.tsx.snap
src/plugins/data_source_management/public/components/edit_data_source/components/update_password_modal/update_password_modal.test.tsx
src/plugins/data_source_management/public/components/edit_data_source/components/update_password_modal/update_password_modal.tsx

Disable the input fields on the edit data source form when data_source.manageableBy is set to none. For OpenSearch connections.
No Authentication - data_source.manageableBy: "none"
No Authentication - data_source.manageableBy: "all"
Username and Password Authentication - data_source.manageableBy: "none"
Username and Password Authentication - data_source.manageableBy: "all"
AWS Authentication - data_source.manageableBy: "none"
AWS Authentication - data_source.manageableBy: "all"
1. data_source.enabled: true
data_source.manageableBy: "none"
2. yarn start
3. Use data source management
- feat: Disable inputs in edit data source screen when data_source.manageableBy is none

Disable input in edit data source when data_source.manageableBy is none

---

changelogs/fragments/7318.yml
src/plugins/workspace/public/components/workspace_form/use_workspace_form.test.ts
src/plugins/workspace/public/components/workspace_form/use_workspace_form.ts
src/plugins/workspace/public/components/workspace_form/workspace_detail_form.tsx
src/plugins/workspace/public/components/workspace_form/workspace_form.tsx
src/plugins/workspace/public/components/workspace_form/workspace_use_case.test.tsx
src/plugins/workspace/public/components/workspace_form/workspace_use_case.tsx
src/plugins/workspace/public/components/workspace_list/index.test.tsx
src/plugins/workspace/public/components/workspace_list/index.tsx
src/plugins/workspace/public/plugin.ts
src/plugins/workspace/public/utils.test.ts
src/plugins/workspace/public/utils.ts

The use case of workspace can only be one specific use case or all use case. This PR mainly includes below changes:
1. Modify multi use case selection to single and add "all use case" option
2. Avoid application been set to Inaccessible when workspace using all use case and application in any use case
3. Avoid nav group been hidden when workspace using all use case
#7319 
- Check out branch and Run `yarn osd boostrap`
- Add below config to the `opensearch_dashboards.yml`
```
uiSettings.overrides["home:useNewHomePage"]: true
```
- Run `yarn start --no-base-path` and login with admin user
- Go to [workspace create page](http://localhost:5601/app/workspace_create)
- Fill workspace unique name and select All use case
- Click create workspace and it will jump to …

[Workspace]Add "All use case" option to workspace form

---

changelogs/fragments/7309.yml
src/plugins/data/public/ui/query_editor/__snapshots__/language_selector.test.tsx.snap
src/plugins/data/public/ui/query_editor/_language_selector.scss
src/plugins/data/public/ui/query_editor/_query_editor.scss
src/plugins/data/public/ui/query_editor/language_selector.test.tsx
src/plugins/data/public/ui/query_editor/language_selector.tsx
src/plugins/data/public/ui/query_editor/query_editor.tsx
src/plugins/data/public/ui/query_editor/query_editor_btn_collapse.tsx
src/plugins/data/public/ui/query_editor/query_editor_extensions/query_editor_extension.tsx
src/plugins/data/public/ui/query_editor/query_editor_top_row.tsx
src/plugins/data/public/ui/saved_query_management/saved_query_management_component.tsx
src/plugins/query_enhancements/public/search/ppl_search_interceptor.ts
src/plugins/query_enhancements/public/search/sql_search_interceptor.ts

New query enhancement UI. 
#7038 
https://github.com/user-attachments/assets/c6079810-d38e-4b6e-b272-d16e5ddbdf5f
- feat: Update query enhancement UI

New Query Enhancement UI

---

changelogs/fragments/7328.yml
src/plugins/dev_tools/public/index.scss

As part of new left navigation Workbench would be moved to dev tools. To make this happen we have registered workbench based on the new nav condition. The css in devtools is making the tabs justify apart `justify-content: space-between;`. Removing this css is fixing the UI and keeping it as expected. This PR removes the unnecessary css on dev tools Tab.
Related Workbench PR: https://github.com/opensearch-project/dashboards-query-workbench/pull/349 
Before:
After:
1. Load dashboards core in local setup
2. Add workbench plugin from main/2.x branch
3. Add the feature flag for new nav. 
4. Move to dev tools and looks at the tabs spacing. 
- fix: [Navigation] Update dev tools tab css for new left navigation

[Navigation] Update dev tools tab css for new left navigation

---

changelogs/fragments/7347.yml
src/plugins/dev_tools/public/application.tsx
src/plugins/dev_tools/public/index.scss

The issue was introduced by https://github.com/opensearch-project/OpenSearch-Dashboards/commit/4c619067f2d1f85afd9ad3f67af15d8f42c3e4da
Before:
After:
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/7349
- fix: data source selector in dev tools tab moved to left

fix: data source selector in dev tools tab moved to left

---

changelogs/fragments/7237.yml
src/core/public/chrome/index.ts
src/core/public/chrome/recently_accessed/recently_accessed_service.ts
src/core/public/chrome/ui/header/index.ts
src/core/public/chrome/ui/index.ts
src/core/public/index.ts
src/plugins/dashboard/public/application/utils/use/use_saved_dashboard_instance.test.ts
src/plugins/dashboard/public/application/utils/use/use_saved_dashboard_instance.ts
src/plugins/discover/public/application/view_components/utils/use_search.ts
src/plugins/discover/public/saved_searches/types.ts
src/plugins/home/public/application/components/homepage/sections/recent_work.tsx
src/plugins/home/public/application/home_render.tsx
src/plugins/home/public/index.ts
src/plugins/saved_objects/public/saved_object/helpers/save_saved_object.ts
src/plugins/saved_objects_management/opensearch_dashboards.json
src/plugins/saved_objects_management/public/management_section/recent_work.test.tsx
src/plugins/saved_objects_management/public/management_section/recent_work.tsx
src/plugins/saved_objects_management/public/plugin.ts
src/plugins/vis_builder/public/application/utils/use/use_saved_vis_builder_vis.ts
src/plugins/vis_builder/public/saved_visualizations/_saved_vis.ts
src/plugins/visualize/public/application/utils/use/use_saved_vis_instance.test.ts
src/plugins/visualize/public/application/utils/use/use_saved_vis_instance.ts

Add recent works section in new home page.
https://github.com/user-attachments/assets/b0fa655f-4328-41fd-bc47-1818c18e7a27
https://github.com/user-attachments/assets/b7b9f7dd-a913-4a1c-b161-df69e0ad8151
- Go to the advanced settings page to enable new home page.
- Go to home page, you should see the recent items section is displayed in home page.
- feat: [navigation-next] add recent works in new homepage

[navigation-next] feat: add recent works in new homepage

---

changelogs/fragments/7329.yml
src/plugins/data_source_management/public/components/direct_query_data_sources_components/direct_query_data_connection/__snapshots__/manage_direct_query_data_connections_table.test.tsx.snap
src/plugins/data_source_management/public/components/direct_query_data_sources_components/direct_query_data_connection/manage_direct_query_data_connections_table.tsx
src/plugins/dev_tools/public/application.tsx
src/plugins/home/public/application/components/tutorial_directory.js
src/plugins/query_enhancements/public/data_source_connection/components/connections_bar.tsx
src/plugins/saved_objects_management/public/management_section/objects_table/components/__snapshots__/flyout.test.tsx.snap
src/plugins/saved_objects_management/public/management_section/objects_table/components/flyout.tsx
src/plugins/vis_type_timeseries/public/application/components/index_pattern.js

I see a 2px height diff which is problem with the `DataSourceSelector` component.
- skip

Compress data source selector on management's data sources page

---

changelogs/fragments/7341.yml
src/plugins/data/public/ui/apply_filters/apply_filter_popover_content.tsx
src/plugins/vis_builder/public/application/components/data_tab/field_bucket.test.tsx
src/plugins/vis_builder/public/application/components/data_tab/field_bucket.tsx
src/plugins/vis_builder/public/application/components/data_tab/field_details.tsx
src/plugins/vis_default_editor/public/components/sidebar/controls.tsx

Applies look and feel pattern guidance to components in visBuilder. 
| Scope | Before (v7Light) | After (v7Light) | Before (v8dark) | After (v8dark) |
| ----- | ----- | ----- | ----- | ----- |
| Flyover: Update icon | <img width="323" alt="Flyover Update v7 Light Before" src="https://github.com/user-attachments/assets/073a5a8d-9fa9-42e4-bda7-ba72fb6ae0c9"> | <img width="323" alt="Flyover Update v7 Light Post" src="https://github.com/user-attachments/assets/1cfb226d-5810-4cd7-b3e4-068184e0f7f3"> | <img width="323" alt="Flyover Update v8 Dark Before" src="https://github.com/user-attachments/assets/9da2e0a0-b64b-4558-bb0d-4ca38379741a"> | <img width="323" alt="Flyover Update v8 Dark Post" src="https://github.com/user-attachments/assets/5188b652-1112-47d1-90e2-a8ae643f9c48"> |
| Modal: …

[Look&Feel] Apply missing guidance for visBuilder

---

changelogs/fragments/7341.yml
src/plugins/data/public/ui/apply_filters/apply_filter_popover_content.tsx
src/plugins/vis_builder/public/application/components/data_tab/field_bucket.test.tsx
src/plugins/vis_builder/public/application/components/data_tab/field_bucket.tsx
src/plugins/vis_builder/public/application/components/data_tab/field_details.tsx
src/plugins/vis_default_editor/public/components/sidebar/controls.tsx

[Manual] [Backport 2.x] [Look&Feel] Apply missing guidance for visBuilder

---

changelogs/fragments/7357.yml
src/plugins/workspace/public/components/workspace_list/__snapshots__/index.test.tsx.snap
src/plugins/workspace/public/components/workspace_list/index.test.tsx
src/plugins/workspace/public/components/workspace_list/index.tsx
src/plugins/workspace/public/components/workspace_menu/workspace_menu.test.tsx
src/plugins/workspace/public/components/workspace_menu/workspace_menu.tsx

Only dashboard admin can create workspace, this PR hide create workspace entry in workspace menu and workspace list.
#7358 
- Workspace Menu
- Workspace list
- Checkout branch code and run `yarn osd bootstrap`
- Add below config to `config/opensearch_dashboards.yml`
```
opensearchDashboards.dashboardAdmin.users: ['dashboard_admin']
uiSettings.overrides["home:useNewHomePage"]: true
```
- Login with admin account and click left bottom workspace picker
- The Create workspace button should not be displayed
- Click "view all" to workspace list page
- The Create workspace button should not be displayed
- Remove `opensearchDashboards.dashboardAdmin.users` in `config/opensearch_dashboards.yml`
- …

[Workspace]Hide create workspace button for non dashboard admin

---

src/plugins/data/public/data_sources/datasource/types.ts
src/plugins/data/public/data_sources/default_datasource/default_datasource.test.ts
src/plugins/data/public/data_sources/default_datasource/default_datasource.ts

In `DataSourceSelectable` component, for current selected data source of type `DataSourceOption`, calling `await selectedSource?.ds.getDataSet()` returned all data sets with only `id` and `title`, now added corresponding `dataSourceId` to data set so that by selecting from the dropdown, I can tell what's the current select data set's data source id.
With dataSourceAdded, `await selectedSource?.ds.getDataSet()` should return:
- skip

add dataSourceId to dataSet

---

changelogs/fragments/7356.yml
src/core/public/chrome/ui/header/__snapshots__/collapsible_nav_group_enabled.test.tsx.snap
src/core/public/chrome/ui/header/collapsible_nav_group_enabled.tsx
src/core/utils/default_app_categories.ts
src/core/utils/default_nav_groups.ts
src/plugins/advanced_settings/public/plugin.ts
src/plugins/dev_tools/public/plugin.ts
src/plugins/management/public/plugin.ts
src/plugins/workspace/public/components/workspace_menu/workspace_menu.tsx
src/plugins/workspace/public/plugin.test.ts
src/plugins/workspace/public/plugin.ts

This PR fix the issues:
- fix: [navigation-next] Fix issues.

[navigation-next] Fix issues.

---

changelogs/fragments/7357.yml
src/plugins/workspace/public/components/workspace_list/__snapshots__/index.test.tsx.snap
src/plugins/workspace/public/components/workspace_list/index.test.tsx
src/plugins/workspace/public/components/workspace_list/index.tsx
src/plugins/workspace/public/components/workspace_menu/workspace_menu.test.tsx
src/plugins/workspace/public/components/workspace_menu/workspace_menu.tsx

Manual backport #7357 to 2.x, only conflict with `src/plugins/workspace/public/components/workspace_list/index.tsx`

[Manual][Backport 2.x][Workspace]Hide create workspace button for non dashboard admin

---

src/core/public/application/types.ts
src/plugins/data/public/ui/query_editor/query_editor_top_row.tsx
src/plugins/data/public/ui/query_string_input/query_bar_top_row.tsx
src/plugins/data/public/ui/search_bar/create_search_bar.tsx
src/plugins/data/public/ui/search_bar/search_bar.tsx
src/plugins/data_explorer/public/components/__snapshots__/app_container.test.tsx.snap
src/plugins/data_explorer/public/components/app_container.scss
src/plugins/data_explorer/public/components/app_container.tsx
src/plugins/data_explorer/public/components/constants.ts
src/plugins/discover/common/index.ts
src/plugins/discover/public/application/components/top_nav/get_top_nav_links.tsx
src/plugins/discover/public/application/view_components/canvas/discover_canvas.scss
src/plugins/discover/public/application/view_components/canvas/index.tsx
src/plugins/discover/public/application/view_components/canvas/top_nav.tsx
src/plugins/navigation/public/top_nav_menu/top_nav_menu.tsx
src/plugins/navigation/public/top_nav_menu/top_nav_menu_data.tsx

This PR aims to introduce a new Nav bar in Discover that would contain the Date Picker as well as the Navigation links that are currently part of headers. The Navigation Links have been replaced with the corresponding Icons to provide a modern UX. These setting are currently controlled by **query:enhancements:enabled** Advanced Setting Flag and would be visible when the above flag is turned on. 
- Turn on the **query:enhancements:enabled** Setting in the Advanced Settings Section of Dashboards
- Navigate to Discover Page
- Check the updated UI 
- feat: Add a New Nav Bar to Discover

Move TopNavLinks to new Nav Bar Discover

---

changelogs/fragments/7396.yml
src/plugins/data_source_management/public/components/edit_data_source/components/header/header.test.tsx
src/plugins/data_source_management/public/components/edit_data_source/components/header/header.tsx

No restriction on setting default data source.
- fix: [DataSource] No restriction on setting default data source

[Bug][DataSource] No restriction on setting default data source

---

changelogs/fragments/7420.yml
src/plugins/data_source_management/public/components/data_source_view/data_source_view.tsx
src/plugins/data_source_management/public/components/utils.ts

* This one adds new returned fields `datasourceversion` and `installedplugins` in `DataSourceView`
* This also fix the current filter logic to ensure filter is applied as expected
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/7099
- fix: [Version Decoupling] Add data source version and installed plugins in data source viewer returns

[Multiple Datasource][Version Decoupling] Add data source version and installed plugins in data source viewer returns

---

changelogs/fragments/7405.yml
src/plugins/workspace/public/components/workspace_menu/workspace_menu.test.tsx
src/plugins/workspace/public/components/workspace_menu/workspace_menu.tsx

Clicking workspace with all use case in the picker should navigate to workspace detail page
- fix: [Bug][Workspace] Navigate to detail page when clicking all use case workspace

[Bug][Workspace] Navigate to detail page when clicking all use case workspace

---

src/plugins/workspace/public/components/workspace_detail_app.tsx
src/plugins/workspace/public/utils.test.ts
src/plugins/workspace/public/utils.ts

Remove the breadcrumbs enricher reset when out a workspace, the enricher will set by nav group service if we are in data administration or settings and setup pages
There has 3 cases
1. nav group is enable + workspace enable + in a workspace -> workspace enricher 
2. nav group is enable + workspace enable + out a workspace -> nav group enricher
3. nav group is enable  + workspace disabled -> nav group enricher
#7359 bug in #7360
- skip

[Workspace]Fix breadcrumbs not set properly when out a workspace

---

src/plugins/data_source_management/public/components/data_source_home_panel/__snapshots__/data_source_home_panel.test.tsx.snap
src/plugins/data_source_management/public/components/data_source_home_panel/data_source_home_panel.test.tsx
src/plugins/data_source_management/public/components/data_source_home_panel/data_source_home_panel.tsx
src/plugins/data_source_management/public/components/direct_query_data_sources_components/connection_detail/direct_query_connection_detail.test.tsx
src/plugins/data_source_management/public/components/direct_query_data_sources_components/connection_detail/direct_query_connection_detail.tsx
src/plugins/data_source_management/public/components/direct_query_data_sources_components/direct_query_data_connection/__snapshots__/manage_direct_query_data_connections_table.test.tsx.snap
src/plugins/data_source_management/public/components/direct_query_data_sources_components/direct_query_data_connection/manage_direct_query_data_connections_table.test.tsx
src/plugins/data_source_management/public/components/direct_query_data_sources_components/direct_query_data_connection/manage_direct_query_data_connections_table.tsx
src/plugins/data_source_management/public/components/utils.ts
src/plugins/data_source_management/server/routes/data_connections_router.ts

This PR will be forwardported into both `main` and `2.x`
[2.16] Fix minor issues for Direct Query Datasource

[2.16] Fix minor issues for Direct Query Datasource

---

yarn.lock

Bump browserslist to fix 
```
FAIL  packages/osd-plugin-helpers/src/integration_tests/build.test.ts (19.15 s)
● builds a generated plugin into a viable archive
expect(received).toMatchInlineSnapshot(snapshot)
Snapshot name: `builds a generated plugin into a viable archive 2`
- Snapshot  - 3
+ Received  + 9
" info deleting the build and target directories
info running @osd/optimizer
│ info initialized, 0 bundles cached
│ info starting worker [1 bundle]
-  │ succ 1 bundles compiled successfully after <time>
-  info copying assets from `public/assets` to build
-  info copying server source into the build and converting with babel
+  │ warn worker stderr Browserslist: caniuse-lite is outdated. Please run:
+  │ warn worker stderr   npx update-browserslist-db@latest
+  │ warn worker stderr …
```

Bump browserslist from `4.22.1` to `4.23.2` to resolve integration test error

---

changelogs/fragments/6674.yml
src/plugins/vis_type_metric/public/components/__snapshots__/metric_vis_component.test.tsx.snap
src/plugins/vis_type_metric/public/components/metric_vis_component.tsx
src/plugins/vis_type_metric/public/metric_vis_renderer.tsx
src/plugins/vis_type_table/public/components/table_vis_app.test.tsx
src/plugins/vis_type_table/public/components/table_vis_app.tsx
src/plugins/vis_type_table/public/table_vis_renderer.tsx
src/plugins/vis_type_table/public/utils/get_table_ui_state.ts

This issue is caused by the callback behavior in ReactExpressionRenderer. The callback to ReactExpressionRenderer to update `isLoading` state is lost if we wrap the render vis with VisualizationContainer.
```
return (
<div {...dataAttrs} className={classes}>
{state.isEmpty && <EuiLoadingChart mono size="l" />}
{state.isLoading && <EuiProgress size="xs" color="accent" position="absolute" />}
{!state.isLoading &&
state.error &&
renderError &&
renderError(state.error.message, state.error)}
<div
className="expExpressionRenderer__expression"
style={expressionStyles}
ref={mountpoint}
/>
</div>
);
```
This PR moved VisualizationContainer directly in MetricVisComponent. When put VisualizationContainer directly in the MetricVisComponent, all the lifecycle methods and hooks within …

[VisBuilder][BUG] Flat render structure in Metric and Table Vis

---

yarn.lock

Backport PR:
https://github.com/opensearch-project/OpenSearch-Dashboards/pull/7444
NA
- skip

[2.x][Manual Backport] Bump browserslist from 4.22.1 to 4.23.2 to resolve integ test error

---

yarn.lock

Backport PR
https://github.com/opensearch-project/OpenSearch-Dashboards/pull/7444
NA
- skip

[2.16][Manual Backport] Bump browserslist from 4.22.1 to 4.23.2 to resolve integ test error

---

changelogs/fragments/7309.yml
src/plugins/data/public/ui/query_editor/__snapshots__/language_selector.test.tsx.snap
src/plugins/data/public/ui/query_editor/_language_selector.scss
src/plugins/data/public/ui/query_editor/_query_editor.scss
src/plugins/data/public/ui/query_editor/language_selector.test.tsx
src/plugins/data/public/ui/query_editor/language_selector.tsx
src/plugins/data/public/ui/query_editor/query_editor.tsx
src/plugins/data/public/ui/query_editor/query_editor_btn_collapse.tsx
src/plugins/data/public/ui/query_editor/query_editor_extensions/query_editor_extension.tsx
src/plugins/data/public/ui/query_editor/query_editor_top_row.tsx
src/plugins/data/public/ui/saved_query_management/saved_query_management_component.tsx
src/plugins/query_enhancements/public/search/ppl_search_interceptor.ts
src/plugins/query_enhancements/public/search/sql_search_interceptor.ts

Manual backport of https://github.com/opensearch-project/OpenSearch-Dashboards/pull/7309

[Manual backport 2.x] New Query Enhancement UI

---

src/plugins/data_source_management/public/components/direct_query_data_sources_components/connection_detail/access_control_tab.tsx
src/plugins/data_source_management/public/components/direct_query_data_sources_components/connection_detail/direct_query_connection_detail.tsx

This PR will be forward port into both main and 2.x
Fix access control tab fetching for remote cluster
- correct the behavior of fetching remote cluster roles instead of local for direct query datasource

[2.16 MDS]Fix access control tab fetching for remote cluster

---

changelogs/fragments/7207.yml
src/plugins/discover/public/application/components/default_discover_table/_table_cell.scss
src/plugins/discover/public/application/components/default_discover_table/table_cell.tsx

add `white-space: pre-wrap;` back to table cell to fix regression in #7177
fixes #7177
- fix: break new lines in table cell in legacy discover

fix(discover): break new lines in table cell

---

changelogs/fragments/7435.yml
src/plugins/workspace/public/components/workspace_detail/workspace_updater.tsx

Add permission validation at workspace detail page
If `permissionEnabled` is not added to the props of the `WorkspaceDetailForm`, input data (such as duplicate IDs) will not be validated by `useWorkspaceForm` when the user adds the same user ID to 'Manage Access and Permissions'
- fix: [Bug][Workspace] Add permission validation at workspace detail page

[Bug][Workspace] Add permission validation at workspace detail page

---

src/plugins/data/public/ui/query_editor/query_editor.tsx
src/plugins/data/public/ui/query_editor/query_editor_extensions/query_editor_extension.test.tsx
src/plugins/data/public/ui/query_editor/query_editor_extensions/query_editor_extension.tsx
src/plugins/data/public/ui/query_editor/query_editor_extensions/query_editor_extensions.test.tsx
src/plugins/data/public/ui/query_editor/query_editor_top_row.tsx
src/plugins/data/public/ui/search_bar/create_search_bar.tsx
src/plugins/data/public/ui/search_bar/search_bar.tsx
src/plugins/discover/public/application/view_components/canvas/top_nav.tsx
src/plugins/query_enhancements/public/query_assist/components/query_assist_banner.test.tsx
src/plugins/query_enhancements/public/query_assist/components/query_assist_banner.tsx
src/plugins/query_enhancements/public/query_assist/components/query_assist_bar.tsx
src/plugins/query_enhancements/public/query_assist/utils/create_extension.test.tsx
src/plugins/query_enhancements/public/query_assist/utils/create_extension.tsx

- fix(queryEditorExtensions): use dataset manager to determine external datasource
- previously it used the dataSource passed in from search bar, it is no longer accurate
- also Remove datasource and indexpattern in query editor extension dependencies
- fix(queryAssist): enable click to change language in banner
- fix(queryAssist): hide query assist bar if editor is collapsed
- skip

Fix UI and detection of external data source in query assist

---

src/plugins/data/public/antlr/dql/code_completion.ts
src/plugins/data/public/autocomplete/providers/query_suggestion_provider.ts
src/plugins/data/public/ui/query_editor/query_editor.tsx

[Auto Suggest] DQL Updates

---

changelogs/fragments/7497.yml
src/plugins/data_source_management/public/components/direct_query_data_sources_components/direct_query_data_connection/manage_direct_query_data_connections_table.test.tsx
src/plugins/data_source_management/public/components/direct_query_data_sources_components/direct_query_data_connection/manage_direct_query_data_connections_table.tsx

The datasource picker in zero etl datasource panel should repect the configuration of `data_source.hideLocalCluster: true`
https://github.com/user-attachments/assets/0ee0369c-7fcc-410e-b749-a80cced256e0
- fix: [MDS] Fix the hide local cluster config

[MDS] Fix the hide local cluster config

---

changelogs/fragments/7493.yml
src/core/public/chrome/ui/header/__snapshots__/header.test.tsx.snap
src/core/public/chrome/ui/header/header.test.tsx
src/core/public/chrome/ui/header/header.tsx
test/plugin_functional/test_suites/dashboard_listing_plugin/dashboard_listing_plugin.ts

Reverts addition of EuiTooltip for header menu button, due to bug where tooltip will always pop up when menu is closed or user navigates to another page.
#7483
| Before (v7Light) | After (v7Light) | Before (v8dark) | After (v8dark) |
| ----- | ----- | ----- | ----- |
| <img width="205" alt="Menu v7 Light Before" src="https://github.com/user-attachments/assets/8f43018c-04e5-4842-8414-0f4083d52b89"> | <img width="205" alt="Menu v7 Light Post" src="https://github.com/user-attachments/assets/5b8cc67c-1c39-4a35-bafa-3f7e51bed4ad"> | <img width="205" alt="Menu v8 Dark Before" src="https://github.com/user-attachments/assets/0ef74cb5-365c-4ac1-97bb-4d38a3a766a6"> | <img width="205" alt="Menu v8 Dark Post" src="https://github.com/user-attachments/assets/d64d845b-eefa-4973-97dd-f8bfec0358c7"> |
- …

[Look&Feel] Revert tooltip addition for navigation menu

---

src/plugins/discover/public/application/components/default_discover_table/table_cell.tsx

Discover table cell buttons got larger, this just makes them match previous size. See screenshots below. 
The positioning difference wrt to border is likely due to padding change (although when I changed padding, I made sure these buttons showed up in the same place, so not sure if something else changed).
N/A
Change:
Playground:
Validated in discover locally vs playground
- skip

fix: use xs buttons for discover table cell filter buttons

---

changelogs/fragments/7542.yml
src/plugins/data/public/ui/dataset_navigator/dataset_navigator.tsx
src/plugins/data/public/ui/dataset_navigator/lib/utils/fetch_data_sources.ts
src/plugins/data/public/ui/dataset_navigator/lib/utils/fetch_external_data_sources.ts

* Update datasources fetch function to include local cluster
* Check for duplicates when fetching external datasources (in the case local cluster is added as a datasource)
* Clean up types in `DataSetNavigator` so items are displayed properly
- fix: fix tables not displaying in navigator and add local cluster to datasources

[Discover 2.0] Updating fetch functions to include local cluster

---

changelogs/fragments/7541.yml
package.json
yarn.lock

Fix bootstrapping error due to babel error. Changed necessary dependencies versions to compatible ones specific to 2.x. This change is specifically for 2.x, these dependencies are compatible on main.
- fix: Fix babel error

Fix babel error

---

src/core/public/chrome/ui/header/__snapshots__/header.test.tsx.snap
src/core/public/chrome/ui/header/header.test.tsx
src/core/public/chrome/ui/header/header.tsx
test/plugin_functional/test_suites/dashboard_listing_plugin/dashboard_listing_plugin.ts

Cherry picked #7493. Manually changed `test/plugin_functional/test_suites/dashboard_listing_plugin/dashboard_listing_plugin.ts` because of lack of User Theme popover button in 2.x.

[Manual] [Backport 2.x] [Look&Feel] Revert tooltip addition for navigation menu

---

src/core/public/chrome/ui/header/__snapshots__/header.test.tsx.snap
src/core/public/chrome/ui/header/header.test.tsx
src/core/public/chrome/ui/header/header.tsx
test/plugin_functional/test_suites/dashboard_listing_plugin/dashboard_listing_plugin.ts

Cherry picked #7493. Manually changed `test/plugin_functional/test_suites/dashboard_listing_plugin/dashboard_listing_plugin.ts` because of lack of User Theme popover button in 2.x.

[Manual] [Backport 2.16] [Look&Feel] Revert tooltip addition for navigation menu

---

package.json
src/plugins/data/public/antlr/opensearch_sql/code_completion.ts
src/plugins/data/public/query/dataset_manager/dataset_manager.ts
src/plugins/data/public/query/query_service.ts
src/plugins/data/public/query/state_sync/connect_to_query_state.test.ts
src/plugins/data/public/query/state_sync/connect_to_query_state.ts
src/plugins/data/public/query/state_sync/create_global_query_observable.ts
src/plugins/data/public/query/state_sync/sync_state_with_url.test.ts
src/plugins/data/public/query/state_sync/sync_state_with_url.ts
src/plugins/data/public/ui/dataset_navigator/_dataset_navigator.scss
src/plugins/data/public/ui/dataset_navigator/create_dataset_navigator.tsx
src/plugins/data/public/ui/dataset_navigator/dataset_navigator.tsx
src/plugins/data/public/ui/query_editor/_query_editor.scss
src/plugins/data/public/ui/query_editor/query_editor.tsx
src/plugins/data/public/ui/query_editor/query_editor_top_row.tsx
src/plugins/data/public/ui/ui_service.ts
src/plugins/discover/public/application/view_components/canvas/top_nav.tsx
src/plugins/discover/public/application/view_components/panel/index.tsx
src/plugins/discover/public/application/view_components/utils/update_search_source.ts
src/plugins/discover/public/application/view_components/utils/use_index_pattern.ts
src/plugins/discover/public/application/view_components/utils/use_search.ts
src/plugins/query_enhancements/common/constants.ts
src/plugins/query_enhancements/public/plugin.tsx
src/plugins/query_enhancements/public/query_assist/components/query_assist_bar.tsx
src/plugins/query_enhancements/public/query_assist/utils/create_extension.test.tsx
src/plugins/query_enhancements/public/query_assist/utils/create_extension.tsx
src/plugins/query_enhancements/public/search/ppl_search_interceptor.ts
src/plugins/query_enhancements/public/search/sql_search_interceptor.ts

For a lot of indices I give it a max height on the popover. Also using memoization helps a lot with the performance and rerendering.
n/a
locally
- fix: dataset explorer performance and handling overflow

[discover-next][bug] add max height to dataset navigator and use memoization

---

src/plugins/dashboard/public/application/components/dashboard_top_nav/__snapshots__/dashboard_top_nav.test.tsx.snap
src/plugins/data/public/query/dataset_manager/dataset_manager.mock.ts
src/plugins/data/public/query/dataset_manager/dataset_manager.test.ts
src/plugins/data/public/query/mocks.ts
src/plugins/data/public/ui/dataset_navigator/create_dataset_navigator.tsx
src/plugins/data/public/ui/query_editor/query_editor.tsx
src/plugins/query_enhancements/public/query_assist/_index.scss
src/plugins/query_enhancements/public/query_assist/components/__snapshots__/call_outs.test.tsx.snap
src/plugins/query_enhancements/public/query_assist/components/call_outs.tsx
src/plugins/query_enhancements/public/query_assist/components/query_assist_banner.tsx
src/plugins/query_enhancements/public/query_assist/components/query_assist_bar.tsx
src/plugins/query_enhancements/public/query_assist/utils/create_extension.test.tsx
src/plugins/query_enhancements/public/query_assist/utils/create_extension.tsx

- this commit added `skip(1)` back to dataset manager observable: https://github.com/opensearch-project/OpenSearch-Dashboards/pull/7492/commits/fef6156f92096e178a3e28a97c221ca344d70d28, we need to revert changes done in https://github.com/opensearch-project/OpenSearch-Dashboards/pull/7464#discussion_r1690583570
- revert dataset manager observable usage in query assist to support `skip(1)`
- revert dataset manager tests
- #7546 removed query editor header div, this PR adds it back to enable query editor extensions
- skip

Fix query assist after #7492, #7546, #7540

---

changelogs/fragments/7565.yml
src/core/server/saved_objects/service/lib/included_fields.test.ts
src/core/server/saved_objects/service/lib/included_fields.ts
src/core/server/saved_objects/service/lib/repository.test.js

this PR will add workspaces and permissions fields into saved objects _bulk_get response
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/7564
- fix: [Workspace]Add workspaces and permissions fields into saved objects _bulk_get response

[Workspace]Add workspaces and permissions fields into saved objects _bulk_get response

---

packages/osd-stylelint-config/config/global_selectors.json
src/core/public/notifications/toasts/toasts_api.tsx
src/plugins/data/public/search/search_interceptor.ts
src/plugins/data/public/ui/dataset_navigator/_dataset_navigator.scss
src/plugins/data/public/ui/dataset_navigator/dataset_navigator.tsx
src/plugins/data/public/ui/query_editor/editors/default_editor/index.tsx

- Fixes Dataset picker style to show the scrollbar correctly
- Fixes the search error toast to only show up once
- skip

[Discover next] Fixes dataset navigator menu styling & search error toast

---

changelogs/fragments/7567.yml
src/plugins/data/public/ui/dataset_navigator/dataset_navigator.tsx

* Adds back in logic for displaying databases when loading is successful
- fix: fixes databases not being displayed upon success

[Discover 2.0] Loading fix for databases

---

changelogs/fragments/7449.yml
changelogs/fragments/7523.yml
src/core/public/chrome/ui/header/recent_items.tsx
src/plugins/index_pattern_management/public/components/edit_index_pattern/source_filters_table/components/table/__snapshots__/table.test.tsx.snap
src/plugins/index_pattern_management/public/components/edit_index_pattern/source_filters_table/components/table/table.tsx
src/plugins/saved_objects_management/public/management_section/objects_table/components/__snapshots__/table.test.tsx.snap
src/plugins/saved_objects_management/public/management_section/objects_table/components/table.tsx
src/plugins/vis_augmenter/public/view_events_flyout/components/event_vis_item_icon.tsx

Applies small padding on popovers for index management page. Also adds OUI tooltip to icons to Index Pattern Source Filters table to match other tables under index management.
Added the `smallPopoverPadding = s` attribute to the following popovers:
| Scope | Before (v7Light) | After (v7Light) | Before (v8Dark) | After (v8Dark) |
| ----- | ----- | ----- | ----- | ----- |
| Saved Objects Export | <img width="251" alt="Saved Objects Export v7 Light Before" src="https://github.com/user-attachments/assets/64a36cab-2efa-4b50-b882-da33b47c5263"> | <img width="251" alt="Saved Objects Export v7 Light After" src="https://github.com/user-attachments/assets/b2318b3f-c41a-4faf-928c-4d1d3d1bc1d1"> | <img width="251" alt="Saved Objects Export v8 Dark Before" …

[Look&Feel] Apply small popover padding and add Oui tooltip
