opensearch-project/OpenSearch-Dashboards

README.md

Update RC state to GA state
[#577](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/577)

Update readme for dashboards 1.0.0

---

README.md

Update RC state to GA state for 1.x
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/577
https://github.com/opensearch-project/OpenSearch-Dashboards/pull/579

[1.x] Update Readme for dashboards 1.0.0

---

README.md

Update RC state to GA state for 1.0
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/577
https://github.com/opensearch-project/OpenSearch-Dashboards/pull/579
- [] New functionality includes testing.

[1.0] Update Readme for dashboards 1.0.0

---

src/core/PRINCIPLES.md

Replace words in PRINCIPLES.md

[Bug] replace words in PRINCIPLES.md

---

src/core/PRINCIPLES.md

Replace words in PRINCIPLES.md
https://github.com/opensearch-project/OpenSearch-Dashboards/pull/599

[1.x][Bug] replace words in PRINCIPLES.md

---

src/core/PRINCIPLES.md

Replace words in PRINCIPLES.md
https://github.com/opensearch-project/OpenSearch-Dashboards/pull/599

[1.0][Bug] replace words in PRINCIPLES.md

---

packages/opensearch-datemath/readme.md

/packages/opensearch-datemath/readme.md still has old concepts.
This PR replaces the word Kibana to OpenSearch Dashboards.

[Bug] Replace words in /packages/opensearch-datemath/readme.md

---

MAINTAINERS.md

[1.x] Update MAINTAINERS.md (#600)

---

CONTRIBUTING.md

Signed-off-by: Tommy Markley markleyt@amazon.com
Backport of #598 to 1.x.

[1.x] Update CONTRIBUTING.md (#598)

---

README.md

[1.x] Clean up README.md (#596)

---

src/plugins/data/public/ui/filter_bar/_index.scss
src/plugins/data/public/ui/filter_bar/filter_bar.tsx
src/plugins/data/public/ui/filter_bar/filter_editor/_filter_editor.scss
src/plugins/data/public/ui/filter_bar/filter_editor/_index.scss
src/plugins/data/public/ui/filter_bar/filter_editor/index.tsx
src/plugins/data/public/ui/filter_bar/filter_editor/phrase_value_input.tsx
src/plugins/data/public/ui/filter_bar/filter_editor/phrases_values_input.tsx
src/plugins/data/public/ui/filter_bar/filter_editor/range_value_input.tsx
src/plugins/data/public/ui/filter_bar/filter_editor/value_input_type.tsx
src/plugins/data/public/ui/filter_bar/filter_item.tsx

* use full width
* Update width
* observer
Backport PR:
https://github.com/opensearch-project/OpenSearch-Dashboards/pull/352
Signed-off-by: galangel <gal0angel@gmail.com>
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/351

[1.x] Increase filters popover size and use full width in form components

---

DEVELOPER_GUIDE.md
README.md

[1.x] Add Getting Started section to the Developer Guide (#685)

---

src/plugins/index_pattern_management/public/components/field_editor/__snapshots__/field_editor.test.tsx.snap

[1.x] Update FieldEditor test snapshots (#691)

---

TESTING.md

Adding TESTING.md to the project as referenced in the README.
The content is some general information about testing and should not
be considered exhaustive.
Backport PR:
https://github.com/opensearch-project/OpenSearch-Dashboards/pull/713
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/667

[1.x][Docs] Added TESTING.md (#713)

---

SECURITY.md

Adding SECURITY.md as it is defined in the README. Will inform developers
how to report security issues.
Backport PR:
https://github.com/opensearch-project/OpenSearch-Dashboards/pull/715
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/714

[1.x][Docs] Added SECURITY.md

---

package.json
yarn.lock

[1.x] Upgrade `tar` from 4.4.13/6.0.2 to 6.1.6 (#704)

---

.dockerignore
DEVELOPER_GUIDE.md

Signed-off-by: Denys Vitali <denys@denv.it>
Backport of #299 to 1.x.

[1.x] docs(docker): add .dockerignore, add build instructions (#299)

---

TESTING.md

Fix TESTING.md wording
Backport PR: https://github.com/opensearch-project/OpenSearch-Dashboards/pull/770

[Backport] [1.x] Update TESTING.md (#770)

---

TESTING.md

Fix TESTING.md wording
Backport PR: https://github.com/opensearch-project/OpenSearch-Dashboards/pull/770

[Backport][1.1] Update TESTING.md (#770)

---

release-notes/opensearch-dashboards.release-notes-1.1.0.md

Add release note for 1.1.0

---

release-notes/opensearch-dashboards.release-notes-1.1.0.md

[1.1] Add release note for 1.1.0

---

package.json

Version bump from 1.1 to 1.2.
n/a

[Version] Increment to 1.2

---

package.json

Version bump from 1.1 to 1.2.
Backport PR:
https://github.com/opensearch-project/OpenSearch-Dashboards/pull/802
n/a

[1.x][Version] Increment to 1.2

---

release-notes/opensearch-dashboards.release-notes-1.1.0.md

Update release note OSD 1.1

---

.github/workflows/dco.yml

https://github.com/opensearch-project/OpenSearch-Dashboards/issues/834

Ensure DCO Workflow Check

---

.github/workflows/dco.yml

Issue Resolved:
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/834
Backport PR:
https://github.com/opensearch-project/OpenSearch-Dashboards/pull/841

[1.x] Ensure DCO Workflow Check

---

packages/osd-ui-shared-deps/package.json

This package was missing from release build so have to add it to this
package.
Brought in by custom branding. Needs to be backported.
n/a

[Release] add axios dependency to UI package

---

packages/osd-ui-shared-deps/package.json

This package was missing from release build so have to add it to this
package.
Brought in by custom branding.
Backport PR:
https://github.com/opensearch-project/OpenSearch-Dashboards/pull/922

[1.x][Release] add axios dependency to UI package

---

packages/osd-ui-shared-deps/package.json

This package was missing from release build so have to add it to this
package.
Brought in by custom branding.
Backport PR:
https://github.com/opensearch-project/OpenSearch-Dashboards/pull/922

[1.2][Release] add axios dependency to UI package

---

release-notes/opensearch-dashboards.release-notes-1.2.0.md

This is the backport PR for https://github.com/opensearch-project/OpenSearch-Dashboards/pull/944
Signed-off-by: Neumann <neumanns@amazon.com>

Add release notes for Dashboards 1.2.0 (#944)

---

package.json

Version bump from 1.2 to 2.0
n/a

[Version] Increment to 2.0

---

cypress/integration/osd-bundle/check_advanced_settings.js
cypress/integration/osd-bundle/check_default_page.js
cypress/integration/osd-bundle/check_filter_and_query.js
scripts/bwctest-osd.sh

Add some sample bwc tests for test purpose. We will use these sample tests to hook up with Jenkins pipelines and use odfe-1.13.2 as a sample test version to verify bwc tests can be run automatically .
tests include the following cases:
verify default page work
verify advanced savings work
verify filter and query work

[Backwards Compatibility][OSD bundle]check advanced_settings, default page and filter&query

---

DEVELOPER_GUIDE.md
README.md

Use the Dashboards logo instead of the OpenSearch logo.
#1025

Use the OpenSearch Dashboards logo in the READMEs

---

.eslintrc.js
src/plugins/embeddable/.storybook/main.js
src/plugins/opensearch_dashboards_react/public/code_editor/.storybook/main.js

Reverts commit 86d13f85e54a1f323cf7bde0b7f9c5c763be0d72
N/A

Revert "Fixes incorrect license headers (#1131)"

---

src/plugins/opensearch_dashboards_utils/docs/state_containers/react/connect.md

Signed-off-by: Thilo-Alexander Ginkel <tg@tgbyte.de>
This PR fixes the `createStateContainerReactHelpers` documentation to match the implementation.
#1197

Fix createStateContainerReactHelpers documentation (closes #1197)

---

.github/workflows/pr_check_workflow.yml

[Backport 1.x] Run build and test workflow on all branches (#1222)

---

release-notes/opensearch-dashboards.release-notes-1.3.0.md

Add release notes for Dashboards 1.3.0

---

package.json

Increment to the next patch version 1.3.1
Version bumps have been done for main branch and 1.x branch.

Bump the version to 1.3.1

---

src/core/server/rendering/rendering_service.tsx

Setup HTTP Agent in the render portion when it did not need to be
it just needed a one time setup for the life time of the server.
Also if this fails to read the keys then it would fail. But it's
only used for custom branding. We shouldn't failed for custom branding
just rely on default branding.
Issue Resolved:
https://discuss.opendistrocommunity.dev/t/is-opensearch-dashboard-server-certificate-and-key-required-to-be-reloaded-everytime-when-gui-is-accessed/9069/13
Setup HTTP Agent in the render portion when it did not need to be
it just needed a one time setup for the life time of the server.
Also if this fails to read the keys then it would fail. But it's
only used for custom branding. We shouldn't failed for custom branding
just rely …

[Branding] allow for SSL setup failures

---

TESTING.md

Exposes the [readme](https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/src/core/TESTING.md) on conventions and best practices for writing tests to the root of the project where it is easier to find.

Chore: Exposes testing readme at the root level

---

release-notes/opensearch-dashboards.release-notes-1.3.1.md

Adds 1.3.1 release notes

---

package.json

Bump version to next patch version
n/a

[Build] bump to 1.2.1

---

package.json

Signed-off-by: Abhinav Gupta <abhng@amazon.com>
Version bump from 1.3.1 to 1.3.2
Post release activity - https://github.com/opensearch-project/opensearch-build/issues/1885

[Build] Bumps version from 1.3.1 to 1.3.2

---

src/core/server/opensearch/client/client_config.ts
src/core/server/opensearch/opensearch_config.ts
src/dev/build/tasks/os_packages/docker_generator/resources/bin/opensearch-dashboards-docker

* Cleans up whitespace, reduces delta of the changes.
Follow-up from #1347

Cleans up changes from memory circuit breaker PR

---

package.json

Bump to next patch version
n/a

[Build] bump to 1.1.1

---

README.md

Adds code coverage and GitHub Actions badges to README
Resolves #1035

Adds code coverage and GitHub Actions badges

---

package.json

Increment from 2.0 to 2.1.
n/a

[Version] Increment to 2.1

---

release-notes/opensearch-dashboards.release-notes-2.0.0-rc1.md

add release note for 2.0.0-rc1

---

.github/workflows/pr_check_workflow.yml
yarn.lock

Backport 6ec2182c3de581027eccb19d3d1938a7c8789261 from #1410

[Backport 1.x] Bumps chromedriver to v100 (#1410)

---

.github/workflows/pr_check_workflow.yml

Backport 6ec2182c3de581027eccb19d3d1938a7c8789261 from #1410

[Backport 1.3] Bumps chromedriver to v100

---

release-notes/opensearch-dashboards.release-notes-1.3.2.md

Adds release notes - new format introduced for 2.0-rc1.
N/A - last step for #1527

Adds 1.3.2 release notes

---

package.json

Bump version to 1.3.3
Part of post release task for https://github.com/opensearch-project/opensearch-build/issues/1882

Bump version to 1.3.3

---

release-notes/opensearch-dashboards.release-notes-2.0.0.md

* Exact copy of 2.0.0-rc1 release notes.
* New changes between RC1 and GA must be added as PRs are merged.
Resolves #1566

Adds v2.0.0 release notes

---

release-notes/opensearch-dashboards.release-notes-2.0.0.md

* Adds a missed CVE fix.
* Re-categorizes the chromedriver bump.
* Removes a PR follow-up for the memory circuit breaker change.
N/A

Fixes omissions/errors in v2.0.0 release notes

---

.lycheeexclude
src/plugins/data/public/index.ts
src/plugins/data/public/public.api.md
src/plugins/data/public/search/errors/timeout_error.test.tsx
src/plugins/data/public/search/errors/timeout_error.tsx
src/plugins/data/public/search/search_interceptor.ts

Backport 8bc8d14dddb455d6a64b15e7d3bffa47b3b5ac2b from #1599

[Backport 1.3] Removes irrelevant upsell in the timeout message

---

.github/workflows/create_doc_issue.yml

since this workflow need to be triggered for PR's coming from external forks, we need to allow it to run on the target environment

fix(Workflow): Fixes needs-documentation label workflow

---

.github/workflows/pr_check_workflow.yml
TESTING.md
bwctest.sh
cypress/integration/with-security/check_loaded_data.js
cypress/integration/with-security/helpers/generate_data.js
cypress/integration/without-security/check_loaded_data.js
cypress/integration/without-security/helpers/generate_data.js
dev-tools/get-version.sh
package.json
scripts/bwc/generate_test_data.sh
scripts/bwc/opensearch_dashboards_service.sh
scripts/bwc/utils.sh
scripts/bwctest_osd.sh

Add backwards compatibility tests to github workflow for PRs.
Also, fix for checking status of OpenSearch Dashboards since
api/status/ is not protected.
Also, enable ability to create test data since migration from
1.0.0 to 3.0.0 is not supported for OpenSearch currently.
Issue:
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1465
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1651
Backport PR:
https://github.com/opensearch-project/OpenSearch-Dashboards/pull/1624

[Backport 2.x][CI][BWC] add BWC tests to github actions (#1624)

---

release-notes/opensearch-dashboards.release-notes-1.3.3.md

Adds v1.3.3 release notes
N/A - step for https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1680

Adds v1.3.3 release notes

---

TYPESCRIPT.md
packages/osd-eslint-import-resolver-opensearch-dashboards/lib/get_project_root.js
src/core/server/saved_objects/migrations/README.md

Fixes formatting and typos in documentation
Resolves #592

Fixes formatting and typos in documentation

---

package.json

https://github.com/opensearch-project/opensearch-build/issues/2101
Part of https://github.com/opensearch-project/opensearch-build/issues/2101
Bump version to 1.3.4

[Release 1.3.3] Version increment to 1.3.4

---

release-notes/opensearch-dashboards.release-notes-2.0.1.md

v2.0.1 release notes
N/A
All v2.0.1 issues and PRs: https://github.com/opensearch-project/OpenSearch-Dashboards/issues?q=label%3Av2.0.1+

Adds v2.0.1 release notes

---

package.json

Bump the version to 2.0.2
Part of post release task for https://github.com/opensearch-project/opensearch-build/issues/2165

Bump the version to 2.0.2

---

src/plugins/wizard/public/application/components/data_tab/field_selector_field.scss
src/plugins/wizard/public/application/components/data_tab/field_selector_field.tsx

Updates the Field Selector UI
New: 
-

[D&D] Updates Field selector

---

src/plugins/navigation/README.md
src/plugins/wizard/README.md

- Updates the D&D readme
- Adds a section for the `TopNavMenu` component in navigation plugin's readme
none

[D&D] Adds a few readme's

---

src/plugins/wizard/public/application/_util.scss
src/plugins/wizard/public/application/_variables.scss
src/plugins/wizard/public/application/app.scss
src/plugins/wizard/public/application/components/data_tab/field_selector.tsx
src/plugins/wizard/public/application/components/data_tab/utils/get_available_fields.ts
src/plugins/wizard/public/application/components/data_tab/utils/index.ts
src/plugins/wizard/public/application/components/side_nav.scss
src/plugins/wizard/public/application/components/top_nav.scss

- Fixes the available field selector to filter similar to the visualize app
- Fixes scss lint errors

[D&D] Fix scss lint and available fields

---

src/plugins/wizard/public/application/components/data_tab/field_selector.tsx
src/plugins/wizard/public/application/components/data_tab/secondary_panel.tsx
src/plugins/wizard/public/application/components/data_tab/use/use_dropbox.tsx
src/plugins/wizard/public/application/components/top_nav.tsx
src/plugins/wizard/public/application/utils/use/index.ts
src/plugins/wizard/public/application/utils/use/use_index_pattern.tsx

Remove useIndexPattern hook in favor of useIndexPatterns
fixes #1917

[D&D] Fix index pattern state and loading

---

.github/workflows/pr_check_workflow.yml
cypress/integration/with-security/check_filter_and_query.js
cypress/integration/without-security/check_filter_and_query.js

Backport https://github.com/opensearch-project/OpenSearch-Dashboards/commit/7ff2d4de9517badcd67199adc6f8fbc720c45e59 from https://github.com/opensearch-project/OpenSearch-Dashboards/pull/1948

[Backport 2.x] [CI] Clean up for BWC tests & run only on PRs for backports

---

CODE_OF_CONDUCT.md

Updates code of conduct.
#1897
Signed-off-by: Bandini Bhopi <bandinib@amazon.com>

[Docs] Updates Code of Conduct

---

package.json

Version increment to 1.3.5
Part of post release task for https://github.com/opensearch-project/opensearch-build/issues/2205

Version increment to 1.3.5

---

package.json

Increment version from 2.1.0 to 2.1.1 and updated the branch to be 2.1 for
docs for example:
https://opensearch.org/docs/2.1/dashboards/index/
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1771

[Version] Increment to 2.1.1

---

src/plugins/credential_management/public/components/breadcrumbs.ts
src/plugins/credential_management/public/components/create_credential_wizard/create_credential_wizard.tsx
src/plugins/credential_management/public/components/credential_table/credentials_table.tsx
src/plugins/credential_management/public/components/edit_credential/edit_credential.tsx
src/plugins/credential_management/public/components/edit_credential/edit_credential_page.tsx
src/plugins/credential_management/public/components/types.ts
src/plugins/credential_management/public/components/utils.ts
src/plugins/credential_management/public/management_app/mount_management_section.tsx
src/plugins/data_source/server/saved_objects/credential_saved_objects_type.ts

Signed-off-by: Louis Chu <clingzhi@amazon.com>
Fix breadcrumb on listing page
#2060

[MD] Fix breadcrumb on listing page and update credential saved object mapping

---

src/plugins/data/common/index_patterns/index_patterns/__snapshots__/index_patterns.test.ts.snap
src/plugins/data/common/index_patterns/index_patterns/index_patterns.ts
src/plugins/data/common/index_patterns/types.ts
src/plugins/data/public/index_patterns/index_patterns/index_patterns_api_client.ts
src/plugins/data/server/index_patterns/fetcher/index_patterns_fetcher.ts
src/plugins/data/server/index_patterns/fetcher/lib/field_capabilities/field_capabilities.ts
src/plugins/data/server/index_patterns/fetcher/lib/opensearch_api.ts
src/plugins/data/server/index_patterns/fetcher/lib/resolve_time_pattern.ts
src/plugins/data/server/index_patterns/routes.ts
src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/components/step_index_pattern/step_index_pattern.tsx
src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/components/step_time_field/step_time_field.tsx
src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/create_index_pattern_wizard.tsx
src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/lib/get_indices.ts
src/plugins/index_pattern_management/public/components/index_pattern_table/index_pattern_table.tsx
src/plugins/index_pattern_management/server/routes/resolve_index.ts

Integrate index pattern with new data client
- Get indices
- Get field for wildcard
- Get filed for time pattern
NOTE: All the todo part shall be replace with the new data client after issue # is resolved.
- The failed build test is not due to this PR. Refer to previous commits for verification.
```
FAIL  packages/osd-config-schema/src/types/stream_type.test.ts
● #defaultValue › returns default when undefined
```

[MD][IP] Integrate index pattern with new data client

---

src/plugins/data_source/common/data_sources/types.ts
src/plugins/data_source/server/saved_objects/data_source.ts

- Add noAuth to dataSource attributes
- Remove attributes don't require index on

Add noAuth to dataSource attributes

---

src/plugins/data/opensearch_dashboards.json
src/plugins/data/server/index_patterns/fetcher/lib/opensearch_api.ts
src/plugins/data/server/index_patterns/routes.ts
src/plugins/index_pattern_management/server/routes/resolve_index.ts

Replace previous data client placeholders in IPM after data client code merged in.
- Tested with index pattern management
-   Able to load indices from other datasource
-   Able to load fields from other datasource

[MD][IP] Integration sequel - replace data client placeholders

---

src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/lib/get_indices.test.ts
src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/lib/get_indices.ts

Update getIndicesViaSearch with datasource.
- Pass datasource id to searchClient
#2151

[MD][IP] Update getIndicesViaSearch with datasource

---

.github/workflows/build_and_test_workflow.yml
bwctest.sh

[CI][Tests] add BWC tests for 2.3.0

---

package.json

Signed-off-by: Peter Zhu <zhujiaxi@amazon.com>
Bump 2.2 branch version to be 2.2.1
Part of opensearch-project/opensearch-build#2271

Bump 2.2 branch version to be 2.2.1

---

src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/components/step_data_source/components/header/header.scss
src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/components/step_data_source/components/header/header.tsx

Update configure data source per UX input

[MD][IP] Update configure data source per UX input

---

release-notes/opensearch-dashboards.release-notes-1.3.5.md

add release note for 1.3.5

---

release-notes/opensearch-dashboards.release-notes-2.2.1.md

- [ x] New functionality includes testing.

add release note for 2.2.1

---

src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/components/step_data_source/__snapshots__/step_data_source.test.tsx.snap
src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/components/step_data_source/components/header/__snapshots__/header.test.tsx.snap
src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/components/step_data_source/components/header/header.test.tsx
src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/components/step_data_source/components/header/header.tsx
src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/components/step_data_source/step_data_source.test.tsx
src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/components/step_data_source/step_data_source.tsx

Add  step data source UI test.
Steps:
1. Write UI test. e.g. `component.test.tsx`;
2. Run `yarn test:jest <path to test file>` e.g. .`./step_data_source.test.tsx` -- This will generate the `component.test.tsx.snap`
Readings that could help:
- https://acesmndr.medium.com/testing-react-functional-components-with-hooks-using-enzyme-f732124d320a
- https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/TESTING.md#unit-tests

[MD]Add step data source UI test

---

.github/workflows/pr_check_workflow.yml

[2.x] fix 2.x bwc by restoring 1.3.2

---

package.json
src/core/server/opensearch/version_check/ensure_opensearch_version.test.ts
src/core/server/opensearch/version_check/ensure_opensearch_version.ts

Cherry-pick the healthcheck bug fixes #2277 

[1.3-healthcheck] Cherry-pick the healthcheck bug fixes #2277

---

package.json

Signed-off-by: CCongWang <wangcong@umich.edu>
* Modify the version in package.json to match 1.2.0 release
N/A

modify the version in package.json

---

release-notes/opensearch-dashboards.release-notes-2.3.0.md

Signed-off-by: Louis Chu <clingzhi@amazon.com>
Add v2.3.0 release note
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/2299

Add v2.3.0 release notes

---

package.json

Signed-off-by: Lu Yu <nluyu@amazon.com>
change version in package.json
NA 
- [ x] New functionality includes testing.
- [x ] All tests pass
- [x ] Commits are signed per the DCO using --signoff

change version in package.json

---

package.json

Update package.json version for this branch.

[1.0-healthcheck] Update package.json version

---

DEVELOPER_GUIDE.md
package.json
src/dev/build/args.test.ts
src/dev/build/args.ts
src/dev/build/build_distributables.ts
src/dev/build/cli.ts
src/dev/build/lib/build.test.ts
src/dev/build/lib/config.test.ts
src/dev/build/lib/config.ts
src/dev/build/lib/platform.ts
src/dev/build/tasks/clean_tasks.ts
src/dev/build/tasks/create_archives_task.ts
src/dev/build/tasks/nodejs/clean_node_builds_task.ts
src/dev/build/tasks/nodejs/download_node_builds_task.ts
src/dev/build/tasks/nodejs/extract_node_builds_task.ts
src/dev/build/tasks/nodejs/verify_existing_node_builds_task.ts
src/dev/build/tasks/notice_file_task.ts

Backport https://github.com/opensearch-project/OpenSearch-Dashboards/pull/795

[Backport 1.0] De-Couple Dashboards linux building process

---

src/plugins/data_source_management/public/components/breadcrumbs.test.ts
src/plugins/data_source_management/public/components/create_data_source_wizard/__snapshots__/create_data_source_wizard.test.tsx.snap
src/plugins/data_source_management/public/components/create_data_source_wizard/components/create_form/__snapshots__/create_data_source_form.test.tsx.snap
src/plugins/data_source_management/public/components/create_data_source_wizard/components/create_form/create_data_source_form.test.tsx
src/plugins/data_source_management/public/components/create_data_source_wizard/components/create_form/create_data_source_form.tsx
src/plugins/data_source_management/public/components/create_data_source_wizard/components/header/__snapshots__/header.test.tsx.snap
src/plugins/data_source_management/public/components/create_data_source_wizard/components/header/header.test.tsx
src/plugins/data_source_management/public/components/create_data_source_wizard/components/header/header.tsx
src/plugins/data_source_management/public/components/create_data_source_wizard/create_data_source_wizard.test.tsx
src/plugins/data_source_management/public/components/create_data_source_wizard/create_data_source_wizard.tsx
src/plugins/data_source_management/public/components/loading_mask/__snapshots__/loading_mask.test.tsx.snap
src/plugins/data_source_management/public/components/loading_mask/loading_mask.test.tsx
src/plugins/data_source_management/public/components/utils.test.ts
src/plugins/data_source_management/public/components/utils.ts
src/plugins/data_source_management/public/components/validation/datasource_form_validation.test.ts
src/plugins/data_source_management/public/mocks.ts

Adding unit test cases for Create data source & other misc files in data source management
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/2019
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/2020

[MD] Datasource Management - Create data source - Unit tests

---

src/plugins/data_source_management/public/components/create_button/__snapshots__/create_button.test.tsx.snap
src/plugins/data_source_management/public/components/create_button/create_button.test.tsx
src/plugins/data_source_management/public/components/data_source_table/__snapshots__/data_source_table.test.tsx.snap
src/plugins/data_source_management/public/components/data_source_table/data_source_table.test.tsx
src/plugins/data_source_management/public/components/data_source_table/data_source_table.tsx

Signed-off-by: Yibo Wang <yibow@amazon.com>
Adding unit test cases for datasource table listing page.
#2019

[MD] datasource management-datasource table-UTs

---

src/plugins/data_source_management/public/components/create_data_source_wizard/components/create_form/__snapshots__/create_data_source_form.test.tsx.snap
src/plugins/data_source_management/public/components/create_data_source_wizard/components/create_form/create_data_source_form.test.tsx
src/plugins/data_source_management/public/components/utils.test.ts
src/plugins/data_source_management/public/mocks.ts

… git
removing invalid urls as CI fails on link checker for inavlid urls in git
PR #2334

removing invalid urls as CI fails on link checker for inavlid urls in git

---

README.md

It removes the typo in the README. 

fix 2402 | remove extra typo from readme.

---

whitesource.config

Updating WS scans to ignore BWC artifacts in `cypress`

---

package.json

Version increment to 1.3.6
Part of https://github.com/opensearch-project/opensearch-build/issues/2650

Version Increment to 1.3.6

---

CHANGELOG.md
MAINTAINERS.md

Signed-off-by: Neumann <neumanns@amazon.com>
Moving Tommy to Emeritus status. Advised to keep Amazon affiliation.

Updating @tmarkley to Emeritus status

---

CHANGELOG.md
MAINTAINERS.md

Signed-off-by: Yan Zeng <zengyan@amazon.com>
Add @kristenTian as maintainer.

Add @kristenTian as maintainer.

---

CHANGELOG.md
packages/osd-plugin-helpers/README.md
packages/osd-plugin-helpers/src/cli.ts
packages/osd-plugin-helpers/src/contexts.ts
packages/osd-plugin-helpers/src/tasks/clean.ts
packages/osd-plugin-helpers/src/tasks/create_archive.ts
packages/osd-plugin-helpers/src/tasks/index.ts
packages/osd-plugin-helpers/src/tasks/optimize.ts
packages/osd-plugin-helpers/src/tasks/update_versions.ts
packages/osd-plugin-helpers/src/tasks/write_public_assets.ts
packages/osd-plugin-helpers/src/tasks/write_server_files.ts
packages/osd-plugin-helpers/src/tasks/yarn_install.ts

Backport 48fe60b40661c0bb19ed73d3426f5d5ec418887c from #2398

[Backport 2.x][Plugin Helpers] Facilitate version changes (#2398)

---

packages/osd-plugin-helpers/README.md
packages/osd-plugin-helpers/src/cli.ts
packages/osd-plugin-helpers/src/contexts.ts
packages/osd-plugin-helpers/src/tasks/clean.ts
packages/osd-plugin-helpers/src/tasks/create_archive.ts
packages/osd-plugin-helpers/src/tasks/index.ts
packages/osd-plugin-helpers/src/tasks/optimize.ts
packages/osd-plugin-helpers/src/tasks/update_versions.ts
packages/osd-plugin-helpers/src/tasks/write_public_assets.ts
packages/osd-plugin-helpers/src/tasks/write_server_files.ts
packages/osd-plugin-helpers/src/tasks/yarn_install.ts

Backport 48fe60b40661c0bb19ed73d3426f5d5ec418887c from #2398

[Backport 1.3] [Plugin Helpers] Facilitate version changes (#2398)

---

yarn.lock

Backport 9c7304786bf7edf4c667d5f487b93905ff18549c from #2322

[Backport 1.3] Update caniuse (#2322)

---

yarn.lock

Backport 9c7304786bf7edf4c667d5f487b93905ff18549c from #2322

[Backport 1.x] Update caniuse (#2322)

---

packages/osd-plugin-helpers/README.md
packages/osd-plugin-helpers/src/cli.ts
packages/osd-plugin-helpers/src/contexts.ts
packages/osd-plugin-helpers/src/tasks/clean.ts
packages/osd-plugin-helpers/src/tasks/create_archive.ts
packages/osd-plugin-helpers/src/tasks/index.ts
packages/osd-plugin-helpers/src/tasks/optimize.ts
packages/osd-plugin-helpers/src/tasks/update_versions.ts
packages/osd-plugin-helpers/src/tasks/write_public_assets.ts
packages/osd-plugin-helpers/src/tasks/write_server_files.ts
packages/osd-plugin-helpers/src/tasks/yarn_install.ts

Backport 48fe60b40661c0bb19ed73d3426f5d5ec418887c from #2398

[backport 1.x] [Plugin Helpers] Facilitate version changes (#2398)

---

CHANGELOG.md
config/opensearch_dashboards.yml

Backport commit 60efd3bacab8a092bacb5842854d41bf48423fdc from #2428

[Backport 2.x] [MD]Add sample config for multi data source in yml config template (#2428)

---

package.json

Increment Dashboards version to 1.3.7
Part of post release task for https://github.com/opensearch-project/opensearch-build/issues/2650

Increment Dashboards version to 1.3.7

---

CHANGELOG.md
src/plugins/index_pattern_management/opensearch_dashboards.json
src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/components/step_data_source/components/header/__snapshots__/header.test.tsx.snap
src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/components/step_data_source/components/header/header.test.tsx
src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/components/step_data_source/components/header/header.tsx
src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/components/step_data_source/step_data_source.tsx
src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/components/step_index_pattern/components/header/header.scss
src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/components/step_index_pattern/components/header/header.tsx
src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/components/step_index_pattern/step_index_pattern.tsx
src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/types.ts
src/plugins/index_pattern_management/public/components/utils.ts
src/plugins/index_pattern_management/public/types.ts

Backport commit 4095e123d77182bed213fedf41be00ccaffd34a7 from #2505

[Backport 2.x] [MD] Address UX comments for index pattern pages

---

CHANGELOG.md
src/plugins/data/common/index_patterns/index_patterns/index_pattern.ts
src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/components/step_data_source/components/header/__snapshots__/header.test.tsx.snap
src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/components/step_data_source/components/header/header.scss
src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/components/step_data_source/components/header/header.test.tsx
src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/components/step_data_source/components/header/header.tsx

Backport ac07159c6e4e9444bb5f20ce54cdf4e42d219038 from #2527

[Backport 2.x] [MD] Update copy on index patten config DS step (#2527)

---

CHANGELOG.md
src/plugins/wizard/public/application/_variables.scss
src/plugins/wizard/public/application/app.scss
src/plugins/wizard/public/application/app.tsx
src/plugins/wizard/public/application/components/data_tab/config_panel.scss
src/plugins/wizard/public/application/components/data_tab/config_panel.tsx
src/plugins/wizard/public/application/components/data_tab/field_selector.scss
src/plugins/wizard/public/application/components/data_tab/field_selector.tsx
src/plugins/wizard/public/application/components/data_tab/field_selector_field.scss
src/plugins/wizard/public/application/components/data_tab/field_selector_field.tsx
src/plugins/wizard/public/application/components/data_tab/index.scss
src/plugins/wizard/public/application/components/data_tab/index.tsx
src/plugins/wizard/public/application/components/data_tab/schema_to_dropbox.tsx
src/plugins/wizard/public/application/components/data_tab/secondary_panel.tsx
src/plugins/wizard/public/application/components/data_tab/title.tsx
src/plugins/wizard/public/application/components/left_nav.tsx
src/plugins/wizard/public/application/components/option.scss
src/plugins/wizard/public/application/components/option.tsx
src/plugins/wizard/public/application/components/right_nav.tsx
src/plugins/wizard/public/application/components/searchable_dropdown.scss
src/plugins/wizard/public/application/components/searchable_dropdown.tsx
src/plugins/wizard/public/application/components/side_nav.scss
src/plugins/wizard/public/application/components/top_nav.scss
src/plugins/wizard/public/application/components/top_nav.tsx
src/plugins/wizard/public/application/components/workspace.scss
src/plugins/wizard/public/application/components/workspace.tsx
src/plugins/wizard/public/embeddable/disabled_visualization.scss
src/plugins/wizard/public/embeddable/disabled_visualization.tsx

Backport https://github.com/opensearch-project/OpenSearch-Dashboards/pull/2581 to 2.x

[Backport 2.x] Change classname prefix wiz to vb (#2581)

---

CHANGELOG.md
src/core/public/doc_links/doc_links_service.ts
src/plugins/data_source_management/public/management_app/compoenent/experimental_callout/experimental_callout.tsx

https://github.com/opensearch-project/OpenSearch-Dashboards/issues/2593

[MD]Update MD data source documentation link

---

.github/workflows/changelog_verifier.yml

Allows skipping changelog verification.

Add `Skip-Changelog` label to skip changelog verification on certain PRs

---

.github/workflows/backport.yml

Update backport workflow to ignore changelog conflicts

---

CHANGELOG.md
packages/osd-pm/src/utils/validate_dependencies.ts
src/core/server/saved_objects/migrations/core/index_migrator.test.ts
src/core/server/saved_objects/migrations/core/opensearch_index.ts
src/dev/notice/cli.js
src/plugins/apm_oss/server/tutorial/instructions/apm_server_instructions.ts
src/plugins/data/README.md

backport 82f82a197426d94bb9ec126c1d9b3fc736fddca3 from #2638

[Backport 2.x] Removed Leftover X Pack references

---

CHANGELOG.md
src/plugins/maps_legacy/public/map/map_messages.js

[Legacy Maps Plugin] Prevent reverse-tabnabbing

---

src/core/public/saved_objects/simple_saved_object.ts
src/plugins/vis_builder/public/application/components/data_tab/use/use_dropbox.tsx
src/plugins/vis_builder/public/application/components/option.tsx
src/plugins/vis_builder/public/application/components/workspace.tsx
src/plugins/vis_builder/public/application/utils/state_management/store.ts
src/plugins/vis_builder/public/application/utils/state_management/visualization_slice.ts
src/plugins/vis_builder/public/application/utils/use/index.ts
src/plugins/vis_builder/public/application/utils/use/use_aggs.ts
src/plugins/vis_builder/public/application/utils/validate_schema_state.ts
src/plugins/vis_builder/public/embeddable/vis_builder_embeddable.tsx
src/plugins/vis_builder/public/services/type_service/types.ts
src/plugins/vis_builder/public/services/type_service/visualization_type.tsx
src/plugins/vis_builder/public/visualizations/metric/to_expression.ts
src/plugins/vis_builder/public/visualizations/vislib/area/to_expression.ts
src/plugins/vis_builder/public/visualizations/vislib/common/create_vis.ts
src/plugins/vis_builder/public/visualizations/vislib/common/types.ts
src/plugins/vis_builder/public/visualizations/vislib/histogram/to_expression.ts
src/plugins/vis_builder/public/visualizations/vislib/line/to_expression.ts

* Fixes auto time interval
* Fixes change datasource while editing agg
* Misc fixes
* Updates Changelog
* Correctly sets timerange
* Fixes rebase
(cherry picked from commit 7a41d9475451be7ae3125590645b0b9a73e8dbb3)
Signed-off-by: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
Signed-off-by: github-actions[bot] …

[Backport 2.4][Vis Builder] Bug fixes for datasource picker and auto time interval

---

SECURITY.md

Any CVE package upgrade may be miss-handled by over-looking sub dependency update which keeps the vulnerability. The above addition provides a HOW-TO and hence reduces the burden on the maintainers.

Security-CVEs fixes guidelines

---

.github/workflows/backport.yml
CHANGELOG.md

Backport 810307c960dfffcc080521d6cb9dc608699032be from https://github.com/opensearch-project/OpenSearch-Dashboards/pull/2766

[Backport 2.x] [CI] update backport custom branch name (#2766)

---

CHANGELOG.md
release-notes/opensearch-dashboards.release-notes-2.4.0.md

Add missing CHANGELOG for 2.4

---

CHANGELOG.md
release-notes/opensearch-dashboards.release-notes-2.4.0.md

Update release note and CHANGELOG for 2842

---

package.json

Bump version to 2.4.1
Part of post release activity for https://github.com/opensearch-project/opensearch-build/issues/2649

Bump version to 2.4.1

---

release-notes/opensearch-dashboards.release-notes-2.4.0.md

The release notes are in the 2.4 branch and 2.4.0 tag but not in main or 2.x which is our usual standard.
Instead of cherry-picking commits I have just copied over the file.
n/a
~~- [ ] New functionality includes testing.~~
~~- [ ] New functionality has been documented.~~
~~- [ ] Update [CHANGELOG.md](./../CHANGELOG.md)~~

Add 2.4.0 release notes

---

CHANGELOG.md
src/plugins/maps_legacy/public/map/map_messages.js

Backport c28674388b20bcf386fc68f47fc73d0de9465259 from #2934

[Backport 1.3 - Manual] [Backport 1.x] [Legacy Maps Plugin] Prevent reverse-tabnabbing (#2934) (#2540)

---

.github/workflows/backport.yml
CHANGELOG.md

Backport 810307c960dfffcc080521d6cb9dc608699032be from https://github.com/opensearch-project/OpenSearch-Dashboards/pull/2766

[Backport 1.x][CI] update backport custom branch name (#2766)

---

CHANGELOG.md
package.json
yarn.lock

backport 68baac19664decd8b1cb0a35fa82ba0e9af4f658 from #2640

[Manual] [Backport 1.x] Bump minimatch to 3.0.5 and [IBM X-Force ID: 220063] unset-value to 2.0.1

---

CHANGELOG.md
packages/osd-plugin-helpers/README.md
packages/osd-plugin-helpers/src/cli.ts

Backport 9b7023f87bc58ce751d7e7fa74f968497738c9ca from #2943.

[Backport 1.3] [Doc] Correct "help" command to reflect actual behaviour

---

CHANGELOG.md
package.json
yarn.lock

backport 21a9e7f2cf7742a301aabb501aea5c7a99ab070f from #2946

[Backport 1.3 - Manual]  [Manual] [Backport 1.x] Bump minimatch to 3.0.5 and [IBM X-Force ID: 220063] unset-value to 2.0.1 (#2640) (#2946)

---

package.json

Backport 3f576df2bd4b24d623d3c8cd7a9109ccd30cfcae from #2963

[Backport 1.x][Windows] Make `yarn pkg-version` work across platforms (#2963)

---

release-notes/opensearch-dashboards.release-notes-2.4.1.md

Based on https://github.com/opensearch-project/OpenSearch-Dashboards/compare/2.4.0...2.4

[Chore] Add 2.4.1 release notes

---

MAINTAINERS.md

Signed-off-by: dblock <dblock@amazon.com>
- Fixed boktorbb alias.
- Added missing last names.
- Made prettier.

Fix boktorbb alias.

---

CHANGELOG.md
package.json

Signed-off-by: Sayali Gaikawad <gaiksaya@amazon.com>
Bump version to 2.4.2 as a part of pending post release activities 

Increment version to 2.4.2

---

package.json

Signed-off-by: Mohammad Qureshi <47198598+qreshi@users.noreply.github.com>
Bump 2.2 branch to `2.2.2` to be up-to-date with the newest tracked version on the branch.

Bump to version 2.2.2

---

CHANGELOG.md
src/plugins/data_source/server/client/client_config.test.ts
src/plugins/data_source/server/legacy/client_config.test.ts

[MD] Update dummy url in tests to follow lychee url allowlist
#3075

[MD] Update dummy url in tests to follow lychee url allowlist

---

CHANGELOG.md
package.json

Signed-off-by: Sayali Gaikawad <gaiksaya@amazon.com>
Bump version to 1.3.8 as a part of pending post release activity

Increment version to 1.3.8

---

.github/workflows/build_and_test_workflow.yml
CHANGELOG.md
NOTICE.txt
package.json
src/dev/build/tasks/notice_file_task.ts
src/dev/notice/cli.js
src/dev/notice/generate_notice_from_source.ts

* Aligns NOTICE with rules outlined in https://github.com/opensearch-project/.github/issues/21.
* Adds NOTICE validation to the build and test workflow.
* Fixes product name discrepancies between repository NOTICE file and the generated NOTICE file for the build.
* I was going to template-ize the build and test workflow file but someone is already working on it for https://github.com/opensearch-project/OpenSearch-Dashboards/issues/2991
Resolves #765

Updates NOTICE file, adds validation to GitHub CI

---

.github/workflows/build_and_test_workflow.yml
CHANGELOG.md

This will provide insight into failures

[CI] Record functional test artifacts in case of failure

---

CHANGELOG.md
package.json
src/dev/jest/config.js
yarn.lock

Co-authored-by: Anan Zhuang <ananzh@amazon.com>
Co-authored-by: Josh Romero <rmerqg@amazon.com>
Co-authored-by: Qingyang(Abby) Hu <abigailhu2000@gmail.com>
(cherry picked from commit e9485f6ad5031a5a54c2fd1cba1e2cadc2bdef2c)
https://github.com/opensearch-project/OpenSearch-Dashboards/pull/2967

[Backport 2.x][Manual]Adds retrying flaky jest tests (#2967)

---

CHANGELOG.md
src/plugins/vis_builder/public/application/components/data_tab/utils/get_available_fields.test.ts
src/plugins/vis_builder/public/application/components/data_tab/utils/get_field_details.test.ts

Adds missing unit tests for field utilities
#2380

[VisBuilder] Adds field unit tests

---

MAINTAINERS.md

Signed-off-by: dblock <dblock@amazon.com>
(cherry picked from commit f1a659f58fb01d0aa37ba858a01ec8304a7a9614)

[Backport 2.x] [Manual] Fix boktorbb alias. (#3085)

---

CHANGELOG.md
src/plugins/data_source_management/public/components/create_data_source_wizard/components/create_form/create_data_source_form.tsx
src/plugins/data_source_management/public/components/edit_data_source/components/header/header.tsx

Update test connection button text per UX input.

[MD]Update test connection button text

---

CHANGELOG.md

[Backport 2.5] [Manual] Update changelog changes on 2.x branch for 2.5 release (#3243)

---

release-notes/opensearch-dashboards.release-notes-2.5.0.md

Updates to release notes 2.5.0
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/3230
Ref: https://github.com/opensearch-project/OpenSearch-Dashboards/issues/3174

Update release notes text and include new changes in the release notes 2.5.0

---

packages/osd-optimizer/src/worker/webpack.config.ts

Fix comment grammar
https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3076#discussion_r1063941693

[Chore] fix comment typo

---

.eslintrc.js
.gitignore
TESTING.md
bwctest.sh
cypress/integration/with-security/check_advanced_settings.js
cypress/integration/with-security/check_default_page.js
cypress/integration/with-security/check_filter_and_query.js
cypress/integration/with-security/check_loaded_data.js
cypress/integration/with-security/check_timeline.js
cypress/integration/with-security/plugins/.gitignore
cypress/integration/without-security/check_advanced_settings.js
cypress/integration/without-security/check_default_page.js
cypress/integration/without-security/check_filter_and_query.js
cypress/integration/without-security/check_loaded_data.js
cypress/integration/without-security/check_timeline.js
cypress/integration/without-security/plugins/.gitignore
package.json
scripts/bwctest_osd.sh

https://github.com/opensearch-project/OpenSearch-Dashboards/pull/1190
#3262

[Backport 1.x][BWC] Updates to BWC tests

---

.github/workflows/pr_check_workflow.yml
CHANGELOG.md

Manual backport of the https://github.com/opensearch-project/OpenSearch-Dashboards/pull/2966
Fixes https://github.com/opensearch-project/OpenSearch-Dashboards/issues/2451

[Backport 1.x] Add Windows CI to the GitHub workflow

---

package.json

Increment 2.5 branch to 2.5.1 after release
Post release activity for https://github.com/opensearch-project/opensearch-build/issues/2908

Increment 2.5 branch to 2.5.1 after release

---

MAINTAINERS.md

Coming from opensearch-project/.github#121, updated MAINTAINERS.md to match opensearch-project recommended format. Also modify this file to include all the missing updates.
Since we won't include this in release, ignore CHANGELOG.

[1.x] Update MAINTAINERS.md

---

CHANGELOG.md
NOTICE.txt
src/dev/notice/generate_notice_from_source.ts

* Follow-up on #3051
Resolves #765

Corrects NOTICE file copyright date range

---

CHANGELOG.md
package.json

Signed-off-by: Divya Madala <divyaasm@amazon.com>
Bump version to 1.3.9 as a part of pending post release activity

Increment version to 1.3.9

---

release-notes/opensearch-dashboards.release-notes-2.6.0.md

https://github.com/opensearch-project/OpenSearch-Dashboards/issues/3447

Add 2.6 release note

---

CHANGELOG.md
src/plugins/vis_type_timeseries/README.md

Fixes a small typo in TSVB README.md file.
n/a

[Docs] fix typo in TSVB README

---

CHANGELOG.md
DEVELOPER_GUIDE.md
packages/osd-opensearch/src/artifact.js
packages/osd-opensearch/src/artifact.test.js

Backport 81a5fadca1b5417c204b94c94a7b6e3196be95dd from https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3537

[Backport][2.x] [Dev] enable `opensearch snapshot` for Darwin (#3537)

---

CHANGELOG.md

Sync from 1.x, include past releases
Reviewers, please ignore any bulleted items L58 and below - these come directly from existing release notes so any updates are out of scope of this PR.

Chore: Update changelog for 1.3.9 release

---

package.json

Bump version from 2.6.0 to 2.7.0
part of https://github.com/opensearch-project/OpenSearch-Dashboards/issues/3447

Chore: bump version to 2.7.0

---

CHANGELOG.md
package.json

Bump version to 1.3.10 as a part of pending post release 13.9 activity

Increment version to 1.3.10

---

.github/pull_request_template.md

Adds an example to show how issues can be linked to PR's so that PR's auto close issues that are linked. This requires the pr description to follow the format https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

Updates the PR template to give an example linking issues with PR's

---

CHANGELOG.md
src/core/public/chrome/ui/header/__snapshots__/header.test.tsx.snap
src/core/public/chrome/ui/header/__snapshots__/header_help_menu.test.tsx.snap
src/core/public/chrome/ui/header/header.tsx
src/core/public/chrome/ui/header/header_help_menu.tsx

[Manual Backport 2.x] Add tooltip to help icon (#3626)

---

package.json

Updates branch name in package.json

Chore: Updates branch name

---

release-notes/opensearch-dashboards.release-notes-2.7.0.md

Forwardport 2.7.0 release notes from https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3875
Part of https://github.com/opensearch-project/OpenSearch-Dashboards/issues/3776

[Forwardport main] Add 2.7.0 release notes

---

release-notes/opensearch-dashboards.release-notes-2.7.0.md

- Add welcome/thank you section for first-time contributors
- Fix link that pointed to issue instead of PR
- Add entry for OUI bump
Part of https://github.com/opensearch-project/OpenSearch-Dashboards/issues/3776

Chore (release notes): polish 2.7.0 notes

---

CHANGELOG.md
src/core/public/chrome/ui/header/__snapshots__/header.test.tsx.snap
src/core/public/chrome/ui/header/header.tsx
src/core/public/chrome/ui/header/header_help_menu.tsx

Add tooltip to menu icon
Manual backport of #3626

[Manual Backport 1.x] Add tooltip to help icon

---

package.json
src/core/public/chrome/ui/header/__snapshots__/header.test.tsx.snap
src/core/public/chrome/ui/header/__snapshots__/header_help_menu.test.tsx.snap
src/core/public/chrome/ui/header/header_help_menu.tsx

Fixes header icon change
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/3909

Fix header icon

---

packages/opensearch-eslint-config-opensearch-dashboards/README.md
scripts/jest.js
scripts/jest_integration.js
src/dev/jest/junit_reporter.js

Updates links to ensure linkchecker will pass.

Docs (Jest): Update jest documentation links

---

.github/CODEOWNERS
MAINTAINERS.md

backport ccac24e4c3e4cfeba514ff378842c58b9445c0c6 from #3792

[Manual Backport 1.x] Update MAINTAINERS.md and CODEOWNERS

---

.github/.codecov.yml
CHANGELOG.md

Fixes code coverage workflow failures for the project test due to indirect flakey changes
none

Adds threshold to code coverage changes for project

---

.github/pull_request_template.md

Updates the PR template to add sections for how to validate the change and screenshots if needed

Updates PR template for screenshots and test instructions

---

release-notes/opensearch-dashboards.release-notes-1.3.10.md

Add 1.3.10 release note

---

CHANGELOG.md
MAINTAINERS.md

Adding Tao and Zilong to MAINTAINERS

Adding Tao and Zilong to MAINTAINERS

---

.lycheeexclude

This test URL is now 410 GONE. Excludes 4  URLs and fixes 5 errors.
N/A
before:
```
📝 Summary
---------------------
🔍 Total.........9960
✅ Successful......93
⏳ Timeouts.........0
🔀 Redirected.......0
👻 Excluded......9862
🚫 Errors...........5
```
after:
```
📝 Summary
---------------------
🔍 Total.........9959
✅ Successful......93
⏳ Timeouts.........0
🔀 Redirected.......0
👻 Excluded......9866
+ echo ::set-output name=exit_code::0
🚫 Errors...........0
```

chore (lychee): Add company.net to exclusion list

---

src/plugins/data_source_management/public/components/create_data_source_wizard/components/create_form/create_data_source_form.tsx

[MD] Update authentication helper text in create data source flow
resolves https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4173

[MD] Update authentication helper text in create data source flow

---

src/core/public/plugins/plugins_service.test.ts
src/core/server/plugins/discovery/plugin_manifest_parser.test.ts
src/core/server/plugins/discovery/plugin_manifest_parser.ts
src/core/server/plugins/integration_tests/plugins_service.test.ts
src/core/server/plugins/plugin.test.ts
src/core/server/plugins/plugin.ts
src/core/server/plugins/plugin_context.test.ts
src/core/server/plugins/plugins_service.test.ts
src/core/server/plugins/plugins_system.test.ts
src/core/server/plugins/plugins_system.ts
src/core/server/plugins/types.ts

This reverts commit e85ea81b4274450a69548bb8a6d14a8c59281606.

Revert "Adds plugin manifest config to define OpenSearch plugin dependency and verifies if it is installed (#3116) (#4195)"

---

CHANGELOG.md
package.json

Increment version to 1.3.11 in 1.3 branch as the prerequiste for 1.3.11 patch release 
N/A

Increment version to 1.3.11 in 1.3 branch

---

.github/workflows/backport.yml
CHANGELOG.md

Upgrade the backport workflow
* Copy over the labels from the original PR
* Label the backport PR with `autocut`
* Label a PR that fails to backport
https://github.com/AMoo-Miki/OpenSearch-Dashboards/pull/16

Upgrade the backport workflow

---

CHANGELOG.md
src/plugins/saved_objects_management/public/management_section/objects_table/components/__snapshots__/relationships.test.tsx.snap
src/plugins/saved_objects_management/public/management_section/objects_table/components/relationships.scss
src/plugins/saved_objects_management/public/management_section/objects_table/components/relationships.tsx

Fixed relationships header overflow
Issue to track - https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4288
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/3967

[CCI] Fix relationships header overflow

---

src/plugins/dashboard/public/plugin.tsx

When clicking on the dashboard page tab, should redirect to stack management page if there is no index pattern detected.

[Dashboard De-Angular] No index pattern routing

---

package.json

Bump version from 2.8.0 to 2.8.1
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4074

Bump version to 2.8.1

---

release-notes/opensearch-dashboards.release-notes-1.3.11.md

Adds a missed change to the release notes

Updates Release notes for 1.3.11

---

config/opensearch_dashboards.yml
src/plugins/saved_objects_management/public/management_section/objects_table/components/__snapshots__/relationships.test.tsx.snap

1. Updates setting in config to default to true
2. Updates single failing jest snapshot

[Feature Anywhere] Update default setting; fix single snapshot

---

.github/CODEOWNERS
CHANGELOG.md
MAINTAINERS.md

Matt has been the primary maintainer for OUI since he joined the team but has recently made significant contributions to OSD too. Here is some of his work https://github.com/opensearch-project/OpenSearch-Dashboards/pulls?q=is:pr+author:BSFishy+is:closed. He also often offers his thoughts and suggestions on OSD issues and proposals https://github.com/opensearch-project/OpenSearch-Dashboards/issues?q=is:issue+commenter:BSFishy+is:closed. Apart from responding to issues and creating meaningful PR’s Matt has also been involved in reviewing a surprisingly large number of PR’s even though his review does not count towards the 2 PR criteria. https://github.com/opensearch-project/OpenSearch-Dashboards/pulls?page=1&q=is:pr+involves:BSFishy.

Adding Matt as a maintainer

---

src/plugins/visualizations/public/embeddable/visualize_embeddable.ts

Add comment about decoupling from embeddables plugin

Add comment about decoupling from embeddables plugin

---

.github/workflows/build_and_test_workflow.yml
CHANGELOG.md
bwctest.sh
cypress/integration/with-security/helpers/generate_data.js
cypress/integration/without-security/helpers/generate_data.js

[Manual][Backport 2.x]Merge [CI][Tests] Add BWC tests for 2.7 and 2.8

---

release-notes/opensearch-dashboards.release-notes-2.9.0.md

Add v2.9.0 release note
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4486

Add v2.9.0 release notes

---

CHANGELOG.md
src/plugins/saved_objects_management/public/management_section/object_view/components/__snapshots__/intro.test.tsx.snap
src/plugins/saved_objects_management/public/management_section/object_view/components/__snapshots__/not_found_errors.test.tsx.snap
src/plugins/saved_objects_management/public/management_section/object_view/components/intro.tsx
src/plugins/saved_objects_management/public/management_section/object_view/components/not_found_errors.tsx
src/plugins/saved_objects_management/public/management_section/objects_table/components/__snapshots__/flyout.test.tsx.snap
src/plugins/saved_objects_management/public/management_section/objects_table/components/__snapshots__/relationships.test.tsx.snap
src/plugins/saved_objects_management/public/management_section/objects_table/components/flyout.tsx
src/plugins/saved_objects_management/public/management_section/objects_table/components/import_summary.scss
src/plugins/saved_objects_management/public/management_section/objects_table/components/relationships.tsx

Added new or removed extra tags and styles in `saved_objects_management` plugin
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/3967

[CCI] Add new or remove extra tags and styles in `saved_objects_management` plugin

---

CHANGELOG.md
package.json

Bump OSD core version from 1.3.11 to 1.3.12

Increment version to 1.3.12

---

.lycheeexclude

Link in copyright header must be preserved, but we shouldn't check for it

Test (linkchecker): Exclude checking dead link

---

CHANGELOG.md
package.json

Post 1.3.12 release task - Bump OSD core version from 1.3.12 to 1.3.13

Increment version to 1.3.13

---

.github/CODEOWNERS
CHANGELOG.md
MAINTAINERS.md

Following the process described in [`opensearch-project/.github/RESPONSIBILITIES.md`](https://github.com/opensearch-project/.github/blob/main/RESPONSIBILITIES.md#becoming-a-maintainer), I nominated Sirazh Gabdullin (@curq) as co-maintainer. Existing maintainers have voted and agreed to this nomination.
---
I’d like to nominate [Sirazh Gabdullin](https://github.com/curq) as a maintainer for the OpenSearch Dashboards repo. Sirazh has contributed 10 merged PRs, which is by far the most by a single external contributor, and has helped enhance and fix both the dev tools console and the data table visualization. Here is some of his work https://github.com/opensearch-project/OpenSearch-Dashboards/pulls?q=is%3Apr+author%3Acurq+is%3Aclosed+.  In addition, he helped us refine the OUI compliance …

Add @curq as co-maintainer

---

.github/workflows/build_and_test_workflow.yml
CHANGELOG.md
bwctest.sh

Test data generated with:
yarn test:bwc -o https://artifacts.opensearch.org/releases/bundle/opensearch/2.8.0/opensearch-2.8.0-linux-x64.tar.gz -d https://artifacts.opensearch.org/releases/bundle/opensearch-dashboards/2.8.0/opensearch-dashboards-2.8.0-linux-x64.tar.gz -g true
yarn test:bwc -o https://artifacts.opensearch.org/releases/bundle/opensearch/2.9.0/opensearch-2.9.0-linux-x64.tar.gz -d https://artifacts.opensearch.org/releases/bundle/opensearch-dashboards/2.9.0/opensearch-dashboards-2.9.0-linux-x64.tar.gz -g true

[Tests] Add BWC tests for 2.9 and 2.10 versions

---

README.md

Changed a Typo in README.md file
fixes #4768

Updated README.md to fix the Communication guide Link

---

CHANGELOG.md
yarn.lock

Bump lmdb from 2.8.0 to 2.8.5
#4735

Bump lmdb from 2.8.0 to 2.8.5

---

CHANGELOG.md
src/plugins/discover/public/application/view_components/canvas/top_nav.tsx

Fix breadcrumb for data explorer. 
resolves #4779 
https://github.com/opensearch-project/OpenSearch-Dashboards/assets/43937633/2476a7ea-4dab-4a55-aae9-b2f78c25e186

[Data Explorer] Fix breadcrumb for data explorer

---

src/plugins/dashboard/public/application/components/dashboard_listing/__snapshots__/dashboard_listing.test.tsx.snap
src/plugins/dashboard/public/application/components/dashboard_top_nav/__snapshots__/dashboard_top_nav.test.tsx.snap

2 PRs that passed on their own, interfered with each other's snapshots: https://github.com/opensearch-project/OpenSearch-Dashboards/pull/4761 and https://github.com/opensearch-project/OpenSearch-Dashboards/pull/4796 
This change fixes that.

Fix snapshots that didn't get updated between PRs

---

README.md

cherry pick 061e4767404691719d2c3a276f7600ebbf91e37e from #4769

[Manual Backport 2.x] Updated README.md (#4769)

---

.lycheeexclude

cherrypick b0383221d79445f0a0da4b0fb573f88fc0930818 from #4720

[Manual Backport 1.3] Test (linkchecker): Exclude checking dead link (#4720)

---

src/plugins/discover/public/application/view_components/canvas/top_nav.tsx

https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4888

[Data Explorer][Discover 2.0] Allow Top Nav to update based on index pattern change

---

package.json
packages/osd-ui-framework/package.json
packages/osd-ui-shared-deps/package.json
test/interpreter_functional/plugins/osd_tp_run_pipeline/package.json
test/plugin_functional/plugins/osd_sample_panel_action/package.json
test/plugin_functional/plugins/osd_tp_custom_visualizations/package.json
yarn.lock

Bump OUI to `1.3.0-rc.2`
Part of preparation for https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4584 and https://github.com/opensearch-project/oui/issues/958

Bump OUI to `1.3.0-rc.1`

---

CHANGELOG.md
release-notes/opensearch-dashboards.release-notes-1.3.13.md

Chore: Add 1.3.13 release notes

---

CHANGELOG.md
MAINTAINERS.md

Add Bandini as maintainer
n/a
n/a
n/a

Add Bandini as maintainer

---

test/functional/apps/home/_navigation.ts
test/functional/apps/home/_sample_data.ts

Fix CiGroup6 failures for data explorer
resolves #5124

[Data Explorer] Fix ci group6

---

DEVELOPER_GUIDE.md
package.json

Backport 46d7c2d8c1f3af737697ee984d31ea1cccf85494 from https://github.com/opensearch-project/OpenSearch-Dashboards/pull/5067

[Manual Backport 2.x] Update yarn install step from dev guide

---

DEVELOPER_GUIDE.md
package.json

Backport 46d7c2d8c1f3af737697ee984d31ea1cccf85494 from https://github.com/opensearch-project/OpenSearch-Dashboards/pull/5067

[Manual Backport 1.3] Update yarn install step from dev guide (#5067)

---

packages/osd-stylelint-config/config/global_selectors.json
packages/osd-stylelint-config/config/restricted_properties.json
src/plugins/data_explorer/public/components/app_container.scss
src/plugins/discover/public/application/components/sidebar/discover_field.scss
src/plugins/discover/public/application/components/sidebar/discover_field.tsx
src/plugins/discover/public/application/components/sidebar/discover_sidebar.scss
src/plugins/discover/public/application/view_components/canvas/discover_canvas.scss

Makes the mobile view a little more nicer. Allows for the query bar to be accessible at all screen widths.
See attached video for changes.
https://github.com/opensearch-project/OpenSearch-Dashboards/assets/20453492/9b197973-a8b0-49b5-9b8d-32617453a25d

[Discover] Fixes mobile layout

---

src/plugins/discover/public/application/helpers/popularize_field.ts
src/plugins/discover/public/application/view_components/canvas/discover_table.tsx
src/plugins/discover/public/application/view_components/panel/index.tsx

Adds popular field to discover
Add and remove fileds in dociver and see the popular field column populate

[Discover] Adds popular field to discover

---

CHANGELOG.md
package.json

~- [ ] All tests pass~
~- [ ] `yarn test:jest`~
~- [ ] `yarn test:jest_integration`~
~- [ ] New functionality includes testing.~
~- [ ] New functionality has been documented.~

[Version] Bumps version to 2.12.0

---

CHANGELOG.md
package.json

Version bump from 2.11.0 to 2.11.1

---

.github/CODEOWNERS
CHANGELOG.md

Adding Bandini to CODEOWNERS, this is follow up PR with #5113

Add new MAINTAINERS to CODEOWNERS file

---

.github/workflows/build_and_test_workflow.yml
CHANGELOG.md
src/dev/build/args.test.ts
src/dev/build/args.ts
src/dev/build/cli.ts
src/dev/build/lib/fs.ts
src/dev/build/tasks/create_archives_sources_task.ts
src/dev/build/tasks/nodejs/__snapshots__/download_node_builds_task.test.ts.snap
src/dev/build/tasks/nodejs/download_node_builds_task.test.ts
src/dev/build/tasks/nodejs/download_node_builds_task.ts
src/dev/build/tasks/nodejs/extract_node_builds_task.test.ts
src/dev/build/tasks/nodejs/extract_node_builds_task.ts
src/dev/build/tasks/nodejs/node_shasums.test.ts
src/dev/build/tasks/nodejs/verify_existing_node_builds_task.test.ts

Backport 89dc0512ed27ce2ea1d296ec17bfce3644114e6b from #5455.
Also, updated CHANGELOG.
Closes #5466

[Manual backport] Enhance darwin-arm64 release (#5455)

---

CHANGELOG.md
release-notes/opensearch-dashboards.release-notes-2.11.1.md

Add Release Notes and update CHANGELOG.md for 2.11.1

---

src/plugins/home/config.ts
src/plugins/home/public/application/components/home_app.js
src/plugins/home/server/index.ts

iteration to make the homepage configurable

[feat/2.11/os-assistant] Make new homepage configurable

---

CHANGELOG.md
package.json

Post 1.3.13 release task - Bump OSD core version from 1.3.13 to 1.3.14

[1.3] Increment to 1.3.14

---

CHANGELOG.md
release-notes/opensearch-dashboards.release-notes-1.3.14.md

Add release notes and update changelog

Add 1.3.14 release notes

---

CHANGELOG.md
package.json

Increment version to 1.3.15

---

.github/CODEOWNERS
CHANGELOG.md
MAINTAINERS.md

Move @seanneumann to emeritus maintainer

---

yarn.lock

[2.11] Update caniuse to `1.0.30001580`

---

packages/osd-stylelint-config/config/global_selectors.json
src/plugins/data_explorer/public/components/app_container.scss
src/plugins/data_explorer/public/components/app_container.tsx
src/plugins/data_explorer/public/components/no_view.tsx
src/plugins/data_explorer/public/components/sidebar/index.scss
src/plugins/data_explorer/public/components/sidebar/index.tsx
src/plugins/data_explorer/public/index.scss
src/plugins/data_explorer/public/index.ts
src/plugins/discover/public/application/components/chart/histogram/histogram.tsx
src/plugins/discover/public/application/components/data_grid/data_grid_table.tsx
src/plugins/discover/public/application/components/default_discover_table/_doc_table.scss
src/plugins/discover/public/application/components/default_discover_table/_table_cell.scss
src/plugins/discover/public/application/components/default_discover_table/_table_header.scss
src/plugins/discover/public/application/components/default_discover_table/table_header_column.tsx
src/plugins/discover/public/application/components/doc_views/context_app.tsx
src/plugins/discover/public/application/components/sidebar/discover_field.scss
src/plugins/discover/public/application/components/sidebar/discover_sidebar.scss
src/plugins/discover/public/application/components/sidebar/discover_sidebar.tsx
src/plugins/discover/public/application/view_components/canvas/index.tsx
src/plugins/discover/public/embeddable/search_embeddable_component.tsx

A bunch of UI fixes on top of the legacy table

Initial UI fixes for discover

---

src/plugins/discover/public/application/components/data_grid/data_grid_table_cell_value.tsx
src/plugins/discover/public/application/components/top_nav/table_feedbacks_panel.tsx

* Current
```
categoryWomen's Clothing currencyEUR customer_first_nameSelena customer_full_nameSelena Duncan customer_genderFEMALE customer_id42 customer_last_nameDuncan customer_phone day_of_weekWednesday day_of_week_i2 emailselena@duncan-family.zzz manufacturerTigress Enterprises order_dateJan 30, 2024 @ 18:51:22.000 order_id568106 products.base_price32.99, 8.99 products.discount_percentage0 products.quantity1, 1 products.manufacturerTigress Enterprises, Tigress Enterprises products.tax_amount0 products.product_id8,745, 15,742 products.categoryWomen's Clothing, Women's Clothing products.skuZO0068700687, ZO0101301013 products.taxless_price32.99, 8.99 products.unit_discount_amount0 products.min_price17.15, 4.94 products._idsold_product_568106_8745, …
```

[Discover with Legacy Table] fix copy issue and open feedbacks in a new tab

---

src/plugins/discover/public/application/components/data_grid/data_grid_table.tsx
src/plugins/discover/public/application/components/default_discover_table/default_discover_table.tsx
src/plugins/discover/public/application/components/default_discover_table/table_rows.tsx

Changes table optimization to lazy loading

[Discover] Fixes table optimization

---

src/plugins/discover/public/application/helpers/breadcrumbs.ts

Fix breadcrumb navigation on context page for both legacy and data grid table
https://github.com/opensearch-project/OpenSearch-Dashboards/assets/43937633/1d31acab-582e-4e34-846d-60ec9515f705

Fix breadcrumb navigation on context page for both legacy and data grid table

---

src/plugins/discover/public/application/components/top_nav/table_feedbacks_panel.tsx

update feedback msg

---

src/plugins/discover/public/application/components/data_grid/data_grid_table.tsx
src/plugins/discover/public/application/components/data_grid/data_grid_table_cell_value.tsx
src/plugins/discover/public/application/components/default_discover_table/default_discover_table.tsx
src/plugins/discover/public/application/components/default_discover_table/helper.tsx
src/plugins/discover/public/application/components/default_discover_table/table_header.tsx
src/plugins/discover/public/application/components/default_discover_table/table_header_column.tsx
src/plugins/discover/public/application/components/default_discover_table/table_rows.tsx
src/plugins/discover/public/application/components/doc_views/context_app.tsx
src/plugins/discover/public/application/utils/state_management/common.test.ts
src/plugins/discover/public/application/utils/state_management/common.ts
src/plugins/discover/public/application/utils/state_management/discover_slice.test.tsx
src/plugins/discover/public/application/utils/state_management/discover_slice.tsx
src/plugins/discover/public/application/view_components/canvas/discover_table.tsx
src/plugins/discover/public/embeddable/search_embeddable_component.tsx

* sorting
https://github.com/opensearch-project/OpenSearch-Dashboards/assets/79961084/fb2b6230-093e-41d5-a258-e3d8d1f07a65
* default sort & short dots
https://github.com/opensearch-project/OpenSearch-Dashboards/assets/79961084/36c5bd18-2612-4b92-8a12-7ef62091c4ce

Resolve sorting and two Settings: default sort & short dots

---

src/plugins/discover/public/application/components/data_grid/data_grid_table.tsx
src/plugins/discover/public/application/components/default_discover_table/default_discover_table.tsx
src/plugins/discover/public/application/components/default_discover_table/helper.tsx
src/plugins/discover/public/application/components/default_discover_table/table_header.tsx
src/plugins/discover/public/application/components/default_discover_table/table_header_column.tsx
src/plugins/discover/public/application/view_components/canvas/discover_table.tsx
src/plugins/discover/public/application/view_components/utils/get_sort_for_search_source.ts
src/plugins/discover/public/embeddable/types.ts
src/plugins/discover/public/saved_searches/types.ts

[Discover] Legacy table type fixes

---

CHANGELOG.md
src/plugins/opensearch_dashboards_overview/public/components/overview/__snapshots__/overview.test.tsx.snap
src/plugins/opensearch_dashboards_overview/public/components/overview/overview.test.tsx

* add more tests for overview
* add more tests for overview
* add to CHANGELOG
* change log
---------
Signed-off-by: Thanh Le <lechithanh2003@gmail.com>
Co-authored-by: Josh Romero <rmerqg@amazon.com>
(cherry picked from commit 9ba5cf54576724f48afde224c90d83ba504608ea)

[Manual][Backport 2.x][OSCI][ADD] More tests for overview (#5418)

---

src/plugins/discover/public/application/components/top_nav/__snapshots__/table_feedbacks_panel.test.tsx.snap

add missing snapshot

---

test/plugin_functional/test_suites/doc_views/doc_views.ts

Fix pluign ftr tests

---

.github/CODEOWNERS
MAINTAINERS.md

cherry picked 6710ec3eb1417a5cdf65e01074fc658ea27d7e2a from #5634

[Manual Backport 1.3] Move @seanneumann to emeritus maintainer (#5634)

---

DEVELOPER_GUIDE.md
src/cli/serve/serve.js

cherry picked 1a0cf47fe646458938e0892e4ed73326d581a122 from #5736

[Manual backport 2.x][Security] Updates dev guide for security (#5736)

---

src/plugins/discover/public/application/components/data_grid/data_grid_table_cell_value.test.tsx

Update snapshot for fixing failed ciGroup3.

Update snapshot for failed ciGroup3

---

test/functional/apps/dashboard/dashboard_filter_bar.js
test/functional/apps/dashboard/dashboard_filtering.js
test/functional/apps/dashboard/dashboard_state.js
test/functional/apps/dashboard/dashboard_time_picker.js

Fix functional 3 and 4 for discover legacy

---

package.json

Updates 2.12 branch name in the package.json

Updates 2.12 branch name in the package.json

---

src/plugins/discover/public/application/components/data_grid/_data_grid_table.scss
src/plugins/discover/public/application/components/data_grid/data_grid_table.tsx

[Discover] Update fonts of the datagrid

---

release-notes/opensearch-dashboards.release-notes-2.12.0.md

Add release note for 2.12

---

CHANGELOG.md

Update changelog placing 2.12 into it's own section.
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5257

[Chore] Update changelog post 2.12

---

package.json

Bump version to 2.13.0.
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5257

[2.x] Increment version to 2.13.0

---

CHANGELOG.md

[Manual backport 2.x] [Chore] Update changelog post 2.12 (#5931)

---

CHANGELOG.md
src/plugins/maps_legacy/server/ui_settings.ts

Fix link to documentation for geoHash precision

---

.github/CODEOWNERS
CHANGELOG.md
MAINTAINERS.md

Here are BionIT's current merge contributions, total contributions, and issues:
[Successfully merging numerous pull requests (PRs)](https://github.com/opensearch-project/OpenSearch-Dashboards/pulls?q=is%3Apr+author%3ABionIT+is%3Amerged)
[Providing valuable reviews for PRs](https://github.com/opensearch-project/OpenSearch-Dashboards/pulls?q=is%3Apr+reviewed-by%3ABionIT)
[Addressing and resolving various issues](https://github.com/opensearch-project/OpenSearch-Dashboards/issues?q=is%3Aissue+author%3ABionIT)
N/A

[Admin] Add @BionIT as a maintainer

---

.github/workflows/build_and_test_workflow.yml

There was an issue with the glob pattern causing the workflow to fail. This fixes it

[CI] Fixes buid and test workflow

---

release-notes/opensearch-dashboards.release-notes-1.3.15.md

Add release notes for 1.3.15

---

.github/CODEOWNERS
CHANGELOG.md
MAINTAINERS.md

Move @kristenTian to emeritus maintainer

Move @kristenTian to emeritus maintainer

---

CHANGELOG.md

Cleaning up 2.12 changelog tot reflect actual changes and moving unreleased changes to its section.

Update 2.12 changelog to reflect correct change list and move unreleased ones to its section

---

release-notes/opensearch-dashboards.release-notes-2.13.0.md

Add release notes for 2.13.0

---

package.json
yarn.lock

(cherry picked from commit 8c4f49a2200bb4622aea3ff70bb7a8c96983af5d)

[Manual][Backport 2.x][CVE-2020-36604] Employ a patched version of hoek that addresses CVE-2020-36604 (#6148)

---

release-notes/opensearch-dashboards.release-notes-2.13.0.md

Update release notes for 2.13

---

.github/CODEOWNERS
CHANGELOG.md
MAINTAINERS.md

Here are xinruiba's current merge contributions, total contributions, and issues:
[Successfully merging numerous pull requests (PRs)](https://github.com/opensearch-project/OpenSearch-Dashboards/pulls?q=is%3Apr+author%3Axinruiba+is%3Amerged)
[Providing valuable reviews for PRs](https://github.com/opensearch-project/OpenSearch-Dashboards/pulls?q=is%3Apr+reviewed-by%3Axinruiba)
[Addressing and resolving various issues](https://github.com/opensearch-project/OpenSearch-Dashboards/issues?q=is%3Aissue+author%3Axinruiba)

[Admin] Add @xinruiba as a maintainer

---

.github/workflows/cypress_workflow.yml

Setting legacy browser when running Cypress tests.

[CI][Tests] set legacy browser warning

---

package.json

[2.x] Increment version to 2.14.0

---

.lycheeexclude

https://github.com/opensearch-project/OpenSearch-Dashboards/issues/6412

Fix Lint Checker error due to unvisiable URL

---

CHANGELOG.md
package.json

Increment the version to 1.3.16
Part of https://github.com/opensearch-project/opensearch-build/issues/4531

Increment the version to 1.3.16

---

src/plugins/workspace/public/plugin.test.ts
src/plugins/workspace/public/plugin.ts
src/plugins/workspace/public/workspace_client.mock.ts
src/plugins/workspace/public/workspace_client.test.ts
src/plugins/workspace/public/workspace_client.ts

Manual backport 4b89ad0683e208875842626ccfb46d80525644ed from #6094.

[Backport 2.x] [Workspace] Add a workspace client in workspace plugin

---

src/plugins/data_source_management/opensearch_dashboards.json
src/plugins/data_source_management/public/components/data_source_menu/create_data_source_menu.test.tsx
src/plugins/data_source_management/public/components/data_source_menu/create_data_source_menu.tsx
src/plugins/data_source_management/public/components/data_source_menu/data_source_menu.tsx
src/plugins/data_source_management/public/components/data_source_menu/types.ts
src/plugins/data_source_management/public/components/data_source_selectable/__snapshots__/data_source_selectable.test.tsx.snap
src/plugins/data_source_management/public/components/data_source_selectable/data_source_selectable.test.tsx
src/plugins/data_source_management/public/components/data_source_selectable/data_source_selectable.tsx
src/plugins/data_source_management/public/components/data_source_selector/data_source_selector.test.tsx
src/plugins/data_source_management/public/components/drop_down_header/__snapshots__/drop_down_header.test.tsx.snap
src/plugins/data_source_management/public/components/drop_down_header/drop_down_header.scss
src/plugins/data_source_management/public/components/drop_down_header/drop_down_header.test.tsx
src/plugins/data_source_management/public/components/drop_down_header/drop_down_header.tsx
src/plugins/data_source_management/public/components/drop_down_header/index.ts
src/plugins/data_source_management/public/components/utils.ts
src/plugins/data_source_management/public/plugin.ts

Manual backport a1c8b8c437e34d186f3bc44436f71b62371432f1

[Manual][Backport 2.x][MD] Add dropdown header to Data source single selector (#6431)

---

examples/multiple_data_source_examples/public/components/data_source_list_active_example.tsx
examples/multiple_data_source_examples/public/components/data_source_list_all_example.tsx
src/plugins/data_source_management/public/components/data_source_aggregated_view/__snapshots__/data_source_aggregated_view.test.tsx.snap
src/plugins/data_source_management/public/components/data_source_aggregated_view/data_source_aggregated_view.scss
src/plugins/data_source_management/public/components/data_source_aggregated_view/data_source_aggregated_view.tsx
src/plugins/data_source_management/public/components/data_source_menu/types.ts
src/plugins/data_source_management/public/components/data_source_selectable/__snapshots__/data_source_selectable.test.tsx.snap
src/plugins/data_source_management/public/components/data_source_view/__snapshots__/data_source_view.test.tsx.snap
src/plugins/data_source_management/public/components/drop_down_header/__snapshots__/drop_down_header.test.tsx.snap
src/plugins/data_source_management/public/components/drop_down_header/drop_down_header.tsx

Manual backport of e34ca2b from #6541 
* Refactor dropdown header + aggregate view UI
Signed-off-by: Huy Nguyen <73027756+huyaboo@users.noreply.github.com>
* Refactor dropdown to use OuiPopoverTitle
Signed-off-by: Huy Nguyen <73027756+huyaboo@users.noreply.github.com>
* Update snapshots
Signed-off-by: Huy Nguyen <73027756+huyaboo@users.noreply.github.com>
* Refactor titleComponent
Signed-off-by: Huy Nguyen <73027756+huyaboo@users.noreply.github.com>
* Update snapshots
Signed-off-by: Huy Nguyen <73027756+huyaboo@users.noreply.github.com>
---------
Signed-off-by: Huy Nguyen <73027756+huyaboo@users.noreply.github.com>
(cherry picked from commit e34ca2b593ecf8d8c6caf547381cdddf5548a53c)
- skip

[Manual backport 2.x][MDS] Refactor dropdown header + Aggregate view UI (#6541)

---

src/plugins/data/public/data_sources/datasource/datasource.ts
src/plugins/data/public/data_sources/datasource/factory.ts
src/plugins/data/public/data_sources/datasource/index.ts
src/plugins/data/public/data_sources/datasource/types.ts
src/plugins/data/public/data_sources/datasource_selector/datasource_selectable.test.tsx
src/plugins/data/public/data_sources/datasource_selector/datasource_selectable.tsx
src/plugins/data/public/data_sources/datasource_selector/types.ts
src/plugins/data/public/data_sources/datasource_services/datasource_service.ts
src/plugins/data/public/data_sources/datasource_services/index.ts
src/plugins/data/public/data_sources/datasource_services/types.ts
src/plugins/data/public/data_sources/default_datasource/default_datasource.ts
src/plugins/data/public/data_sources/register_default_datasource.ts
src/plugins/data/public/index.ts
src/plugins/data_explorer/public/components/sidebar/index.tsx

This is not the PR ready for review, its purpose is for merging to a feature branch for mid term bug bash.

[Discover - Testing purpose only] data selector enhancement

---

src/plugins/data/common/opensearch_query/opensearch_query/index.ts

Missed an unused creation of an initial implementation related to MQL

[MQL] Cleanup unused helper function

---

src/plugins/data_source_management/public/components/data_source_column/data_source_column.test.tsx
src/plugins/data_source_management/public/components/data_source_column/data_source_column.tsx
src/plugins/data_source_management/public/plugin.ts

[MD]Fix data source link to point to correct page, and use in page redirect instead of reloading
#6581 
#6582 
1. create a data source and create index pattern with this data source
2. go to index pattern page, and click the data source name link under column "Data source connection", it should redirect to the corresponding data source detail page, without triggering a page reload.
3. Test the change works for dropdown header, and no data source component, since global var `DSM_APP_ID` is being used at those places. See below gif
- fix: Fix data source link to point to correct page, and use in page redirect instead of reloading

[MD]Fix data source link to point to correct page, and use in page redirect instead of reloading

---

src/plugins/data_source_management/public/plugin.ts
src/plugins/workspace/public/plugin.ts

Workspace depends on DSM id to filter, update DSM id in workspace accordingly DSM change.
- skip

[Workspace] fix: update DSM id in workspace

---

src/plugins/data/common/opensearch_query/opensearch_query/build_opensearch_query.ts
src/plugins/data/public/ui/query_string_input/language_switcher.tsx

fix language change issue

---

src/plugins/data/public/ui/query_string_input/query_bar_top_row.tsx

address issue with no query ui enhancement on validation

---

src/legacy/ui/ui_render/bootstrap/startup.js.hbs

This reverts commit 3c78162a04e611f1797638e54e06a0ceb8e89746.

Revert "fix (startup): fix font theme key (#6703) (#6707)"

---

.github/CODEOWNERS
MAINTAINERS.md
changelogs/fragments/6798.yml

Add @mengweieric as maintainer.
- doc: add mengweieric as maintainer

add @mengweieric as maintainer

---

CHANGELOG.md
package.json

Increment core version to 1.3.17

Increment version to 1.3.17

---

src/plugins/data/public/ui/filter_bar/_global_filter_group.scss
src/plugins/data/public/ui/query_editor/_index.scss
src/plugins/data/public/ui/query_editor/_language_switcher.scss
src/plugins/data/public/ui/query_editor/_query_editor.scss
src/plugins/data/public/ui/query_editor/fetch_index_patterns.ts
src/plugins/data/public/ui/query_editor/index.tsx
src/plugins/data/public/ui/query_editor/language_switcher.tsx
src/plugins/data/public/ui/query_editor/no_data_popover.tsx
src/plugins/data/public/ui/query_editor/query_editor.tsx
src/plugins/data/public/ui/query_editor/query_editor_top_row.tsx
src/plugins/data/public/ui/search_bar/search_bar.tsx

Adding the query editor. Only a little amount of clean up but clean up more, styling and include data source selection.
Will open an issue and proposal which will talk about the configurations, Advanced Settings, user preferences, rollback solutions that we be utilized by work here.
In that proposal, I will explain more, but for the sake of the feature branch, I will like source the [qlDashboards](https://github.com/kavilla/qlDashboards) into OSD only in the feature branch (for now).

[Data][Ui] Query Editor

---

CHANGELOG.md
release-notes/opensearch-dashboards.release-notes-1.3.17.md

Add release notes for 1.3.17

---

package.json

Increment version to 2.15.0
- fix: Update the branch for next release

[2.x] Increment version to 2.15.0

---

changelogs/fragments/6885.yml
docs/openapi/saved_objects/saved_objects.yml

Add OpenAPI specifications for resolve import errors api
- doc: Add OpenAPI specifications for resolve import errors api

Add OpenAPI specifications for resolve import errors api

---

CHANGELOG.md
release-notes/opensearch-dashboards.release-notes-1.3.17.md

Update release notes for 1.3.17

Update release notes for 1.3.17

---

plugins-extra/query_enhancements/common/index.ts
plugins-extra/query_enhancements/public/search/sql_search_interceptor.ts
plugins-extra/query_enhancements/server/plugin.ts
plugins-extra/query_enhancements/server/search/ppl/ppl_facet.ts
plugins-extra/query_enhancements/server/search/sql/sql_facet.ts
plugins-extra/query_enhancements/server/ui_settings.ts
src/cli/cluster/cluster_manager.ts
src/dev/precommit_hook/casing_check_config.js
src/plugins/data/common/constants.ts
src/plugins/data/public/ui/search_bar/create_search_bar.tsx
src/plugins/data/public/ui/search_bar/search_bar.tsx
src/plugins/data/public/ui/settings/settings.ts
src/plugins/data/public/ui/ui_service.ts
src/plugins/data/server/ui_settings.ts
src/plugins/data_explorer/public/components/sidebar/index.tsx

Still working on the re-render of the data source selector though.
But at least wanted to put the toggle here first.

[discover-next] some lint clean up and added override toggle

---

src/plugins/data/public/ui/query_editor/query_editor.tsx
src/plugins/data/public/ui/query_string_input/query_string_input.tsx
src/plugins/data/public/ui/search_bar/search_bar.tsx
src/plugins/data/public/ui/settings/settings.ts
src/plugins/data/public/ui/ui_service.ts
src/plugins/data_explorer/public/components/sidebar/index.tsx

fix the advanced settings to update the components accurately

[discover-next] fix advanced settings

---

changelogs/fragments/6954.yml

Add changelog for PR 6954
- skip

Add changelog for PR 6954

---

changelogs/fragments/6167.yml
changelogs/fragments/6898.yml

Add changelog for:
* #6898
*  #6167 
- skip

Add changelog for #6898

---

package.json

Bump 2.x to 2.16.0

---

docs/_sidebar.md

This changes is auto generated after running `yarn docs:generateDevDocs` to update sidebar in docs
NA
run `npx serve` and see the doc site
- skip

update docs sidebar

---

release-notes/opensearch-dashboards.release-notes-2.15.0.md

Update release notes for 2.15

---

changelogs/fragments/7060.yml
src/core/public/chrome/README.md
src/core/public/chrome/chrome_service.mock.ts
src/core/public/chrome/chrome_service.test.ts
src/core/public/chrome/chrome_service.tsx
src/core/public/chrome/index.ts
src/core/public/chrome/nav_group/index.ts
src/core/public/chrome/nav_group/nav_group_service.test.ts
src/core/public/chrome/nav_group/nav_group_service.ts
src/core/public/chrome/utils.test.ts
src/core/public/chrome/utils.ts
src/core/public/core_system.ts
src/core/public/index.ts
src/core/types/index.ts
src/core/types/nav_group.ts
src/core/utils/default_app_categories.ts
src/core/utils/default_nav_groups.ts
src/core/utils/index.ts
src/plugins/dashboard/public/application/components/dashboard_listing/__snapshots__/dashboard_listing.test.tsx.snap
src/plugins/dashboard/public/application/components/dashboard_top_nav/__snapshots__/dashboard_top_nav.test.tsx.snap
src/plugins/home/server/ui_settings.ts

Manual backport 5212f09b780459c8212697a419d5651b83361d6d from #7060

[Backport 2.x][navigation-next] feat: introduce new interface for group (#7060)

---

src/plugins/data/public/plugin.ts
src/plugins/data/public/ui/query_editor/query_editor.tsx
src/plugins/opensearch_dashboards_react/public/code_editor/code_editor.tsx

dql Antlr autocomplete

---

CHANGELOG.md
package.json

Increment version to 1.3.18
Part of https://github.com/opensearch-project/opensearch-build/issues/4763

Increment version to 1.3.18

---

.github/CODEOWNERS
MAINTAINERS.md
changelogs/fragments/7196.yml

Adding Viraj as a maintainer
- doc: add Viraj as maintainer

[admin] add Viraj to be a maintainer

---

src/plugins/data/public/ui/saved_query_management/saved_query_list_item.tsx
src/plugins/saved_objects/public/finder/saved_object_finder.tsx

- refactor: [Look&feel] Use small List Groups

[Look&feel] Use small List Groups

---

.github/workflows/add-untriaged.yml

The untriage label workflow was sometimes missing the label. e.g. https://github.com/opensearch-project/OpenSearch-Dashboards/issues/7216
Here is a test run for the workflow: https://github.com/ashwin-pc/OpenSearch-Dashboards/actions/runs/9887112288/job/27308169353
- skip

[OE] Improved untriaged workflow

---

src/plugins/opensearch_dashboards_react/public/table_list_view/table_list_view.tsx

[Look&Feel] Update dashboards & visualization list title to use standard size

---

changelogs/fragments/7166.yml
src/core/public/chrome/chrome_service.mock.ts
src/core/public/chrome/chrome_service.tsx
src/core/public/chrome/nav_group/nav_group_service.test.ts
src/core/public/chrome/nav_group/nav_group_service.ts
src/core/public/chrome/ui/header/__snapshots__/header.test.tsx.snap
src/core/public/chrome/ui/header/__snapshots__/header_breadcrumbs.test.tsx.snap
src/core/public/chrome/ui/header/header.test.tsx
src/core/public/chrome/ui/header/header.tsx
src/core/public/chrome/ui/header/header_breadcrumbs.test.tsx
src/core/public/chrome/ui/header/header_breadcrumbs.tsx
src/plugins/dashboard/public/application/components/dashboard_listing/__snapshots__/dashboard_listing.test.tsx.snap
src/plugins/dashboard/public/application/components/dashboard_top_nav/__snapshots__/dashboard_top_nav.test.tsx.snap
src/plugins/workspace/public/plugin.ts

Backport 0215e322d9bd6e6e41015db7770f95df89d6eb0b from #7166 
- skip

[Backport 2.x][Navigation-Next] Add current nav group into chrome service

---

changelogs/fragments/7273.yml
src/core/utils/default_app_categories.ts

- feat: [navigation-next] Add new category

[navigation-next] Add new category

---

src/plugins/discover/public/application/view_components/utils/use_search.ts

Fixes recently accessed for saved search by adding chrome back.
https://github.com/opensearch-project/OpenSearch-Dashboards/pull/6167/files#diff-663ffea1a92b4c32f69ad6a65f15d9b07ae759bc026568db627d950842fcad07L74 has delete chrome variable accidentally, it will cause recentlyAccessed have undefined exception
```
if (savedSearchInstance?.id) {
chrome.recentlyAccessed.add(
savedSearchInstance.getFullPath(),
savedSearchInstance.title,
savedSearchInstance.id
);
}
```
1. go to saved objects management page and filter by search
2. choose one and click, it will navigate to discover page
3. the search should appeared in recentlyAccess section on left navigation
- skip

Fixes recently accessed for saved search

---

changelogs/fragments/7339.yml
src/core/utils/default_app_categories.ts

detect will be renamed to configure and the order has some adjustment.
- feat: [navigation-next] update category

[navigation-next] feat: update category

---

changelogs/fragments/7045.yml
src/core/public/chrome/index.ts
src/core/public/chrome/recently_accessed/index.ts
src/core/public/index.ts
src/plugins/workspace/common/constants.ts
src/plugins/workspace/public/components/workspace_menu/workspace_menu.test.tsx
src/plugins/workspace/public/components/workspace_menu/workspace_menu.tsx
src/plugins/workspace/public/plugin.test.ts
src/plugins/workspace/public/plugin.ts
src/plugins/workspace/public/recent_workspace_manager.test.ts
src/plugins/workspace/public/recent_workspace_manager.ts

Manual backport https://github.com/opensearch-project/OpenSearch-Dashboards/pull/7045
conflict file: src/plugins/workspace/public/components/workspace_menu/workspace_menu.tsx
- skip

[Manual Backport][2.x][Workspace] Refactor the UI of workspace picker

---

changelogs/fragments/7363.yml
package.json
packages/osd-ui-framework/package.json
packages/osd-ui-shared-deps/package.json
test/interpreter_functional/plugins/osd_tp_run_pipeline/package.json
test/plugin_functional/plugins/osd_sample_panel_action/package.json
test/plugin_functional/plugins/osd_tp_custom_visualizations/package.json
yarn.lock

Bump OUI to 1.8.0

---

changelogs/fragments/7356.yml
src/core/public/chrome/ui/header/__snapshots__/collapsible_nav_group_enabled.test.tsx.snap
src/core/public/chrome/ui/header/collapsible_nav_group_enabled.tsx
src/core/utils/default_app_categories.ts
src/core/utils/default_nav_groups.ts
src/plugins/advanced_settings/public/plugin.ts
src/plugins/dev_tools/public/plugin.ts
src/plugins/management/public/plugin.ts
src/plugins/workspace/public/components/workspace_menu/workspace_menu.tsx
src/plugins/workspace/public/plugin.test.ts
src/plugins/workspace/public/plugin.ts

[navigation-next] Fix issues. (#7356) (#7377)

---

.github/CODEOWNERS
MAINTAINERS.md
changelogs/fragments/7458.yml

Adding Sean as a maintainer
- doc: add Sean as maintainer

[admin] add Sean to be a maintainer

---

changelogs/fragments/7149.yml
yarn.lock

Backport PR:
https://github.com/opensearch-project/OpenSearch-Dashboards/pull/7149
---------
Signed-off-by: Zilong Xia <zilongx@amazon.com>
Co-authored-by: opensearch-changeset-bot[bot] <154024398+opensearch-changeset-bot[bot]@users.noreply.github.com>
(cherry picked from commit 027122ef196fc958da1a565d6f2f4823d9e0ea44)

[2.x][Manual Backport 2.x] Bump up axios to 1.7.2 to fix SNYK-JS-AXIOS-6144788 (#7149)

---

.lycheeignore
src/plugins/dashboard/public/application/components/dashboard_listing/dashboard_listing.test.tsx
src/plugins/data/public/antlr/shared/utils.test.ts
src/plugins/data/public/query/dataset_manager/dataset_manager.ts
src/plugins/data/public/query/state_sync/connect_to_query_state.test.ts
src/plugins/data/public/query/state_sync/connect_to_query_state.ts
src/plugins/data/public/query/state_sync/sync_state_with_url.test.ts
src/plugins/data/public/query/state_sync/sync_state_with_url.ts
src/plugins/data/public/ui/dataset_navigator/dataset_navigator.tsx
src/plugins/query_enhancements/server/search/sql_search_strategy.test.ts

Address the test failures.
n/a
- skip

[tests][discover-next] update the tests and async nature of the dataset navigator

---

changelogs/fragments/7425.yml
src/plugins/data/public/ui/dataset_navigator/dataset_navigator.tsx
src/plugins/data/public/ui/query_editor/_query_editor.scss
src/plugins/data/public/ui/query_editor/query_editor.tsx
src/plugins/data/public/ui/saved_query_management/__snapshots__/saved_query_management_component.test.tsx.snap
src/plugins/data/public/ui/saved_query_management/saved_query_management_component.tsx

More styling on query enhancement UI
- skip

More styling on query enhancement UI

---

src/core/public/chrome/ui/header/collapsible_nav_group_enabled.tsx

Make the left nav align with the hamburger icon on the top left.
- skip

[navigation-next]feat: make collapsed new left nav align with hamburger icon

---

src/plugins/data/public/ui/filter_bar/_global_filter_group.scss

Remove height on global styling of top nav.

Remove height on global styling of top nav

---

.github/CODEOWNERS
MAINTAINERS.md
changelogs/fragments/7553.yml

Adding Joshua as a maintainer.
- doc: add Joshua as maintainer

[admin] add Joshua to be a maintainer

---

package.json
packages/osd-ui-framework/package.json
packages/osd-ui-shared-deps/package.json
test/interpreter_functional/plugins/osd_tp_run_pipeline/package.json
test/plugin_functional/plugins/osd_sample_panel_action/package.json
test/plugin_functional/plugins/osd_tp_custom_visualizations/package.json
yarn.lock

Bump OUI to 1.8.1

---

examples/embeddable_examples/public/multi_task_todo/multi_task_todo_component.tsx
src/core/public/chrome/ui/header/recent_items.tsx

[Look&Feel] apply small list pattern guidance to remaning OSD experiences

---

docs/_sidebar.md

Add missing doc entry to `docs/_sidebar.md`
- skip

fix: add missing doc entry for content management plugin

---

src/plugins/workspace/public/components/workspace_detail/workspace_detail.test.tsx

feat: fix unit test error

---

CHANGELOG.md
package.json

Increment version to 1.3.18
Part of https://github.com/opensearch-project/opensearch-build/issues/4888

Increment version to 1.3.19

---

package.json
packages/osd-ui-framework/package.json
packages/osd-ui-shared-deps/package.json
src/core/public/chrome/ui/header/__snapshots__/header.test.tsx.snap
src/core/public/chrome/ui/header/__snapshots__/recent_items.test.tsx.snap
src/core/public/chrome/ui/header/header.scss
src/core/public/chrome/ui/header/header.tsx
src/core/public/chrome/ui/header/header_controls_container.scss
src/core/public/chrome/ui/header/recent_items.scss
src/core/public/chrome/ui/header/recent_items.tsx
src/plugins/data/public/ui/filter_bar/_global_filter_group.scss
src/plugins/navigation/public/top_nav_menu/_index.scss
src/plugins/navigation/public/top_nav_menu/top_nav_control_item.tsx
src/plugins/navigation/public/top_nav_menu/top_nav_menu.tsx
test/interpreter_functional/plugins/osd_tp_run_pipeline/package.json
test/plugin_functional/plugins/osd_sample_panel_action/package.json
test/plugin_functional/plugins/osd_tp_custom_visualizations/package.json
yarn.lock

Revisit updated header spacing
Also:
* Bump OUI to 1.10.0
- skip

Revisit updated header spacing

---

src/core/public/chrome/ui/header/header.scss

Readjust spacing of header
- skip

Readjust spacing of header

---

src/plugins/workspace/public/services/use_case_service.test.ts

[navigation]fix: unit test failure introduced by #7749

---

src/plugins/data/public/query/query_string/dataset_service/lib/index_type.ts
src/plugins/data/public/ui/dataset_selector/dataset_selector.tsx

- Fetch index patterns correctly
- Show the correct languages in index picker
- skip

[Disocver Next] Fixes language selection for indices +1

---

src/plugins/data/common/constants.ts
src/plugins/data/public/query/query_string/dataset_service/dataset_service.mock.ts
src/plugins/data/public/query/query_string/dataset_service/lib/index_pattern_type.ts
src/plugins/data/public/query/query_string/language_service/language_service.mock.ts
src/plugins/data/public/query/query_string/query_string_manager.mock.ts
src/plugins/data/public/query/query_string/query_string_manager.test.ts
src/plugins/query_enhancements/public/query_assist/utils/create_extension.tsx

Updates mocks to the latest values expected.
n/a

[discover] Updates to mocks for tests and ci

---

release-notes/opensearch-dashboards.release-notes-1.3.19.md

Added release notes for 1.3.19
Part of https://github.com/opensearch-project/opensearch-build/issues/4888
-  skip

Added release notes for 1.3.19

---

src/plugins/content_management/public/components/page_render.tsx
src/plugins/content_management/public/components/section_input.test.ts
src/plugins/content_management/public/components/section_input.ts
src/plugins/content_management/public/components/section_render.tsx
src/plugins/home/public/application/components/__snapshots__/home_list_card.test.tsx.snap
src/plugins/home/public/application/components/home_list_card.tsx
src/plugins/home/public/application/home_render.tsx
src/plugins/saved_objects_management/public/management_section/recent_work.tsx
src/plugins/workspace/public/components/service_card/__snapshots__/workspace_list_card.test.tsx.snap
src/plugins/workspace/public/components/service_card/workspace_list_card.tsx

tweaks the new homepage styles

---

src/plugins/data/public/query/query_string/language_service/get_query_control_links.tsx

Happened to see the DQL doc link is incorrect, changed to use the link from docLinksService
- skip

fix: broken dql doc link

---

changelogs/fragments/7870.yml
src/plugins/data/common/data_frames/utils.ts
src/plugins/data/public/query/query_string/dataset_service/lib/index_pattern_type.ts
src/plugins/data/public/query/query_string/dataset_service/lib/index_type.ts
src/plugins/query_enhancements/common/constants.ts
src/plugins/query_enhancements/common/types.ts
src/plugins/query_enhancements/common/utils.ts
src/plugins/query_enhancements/public/datasets/s3_handler.ts
src/plugins/query_enhancements/public/search/ppl_search_interceptor.ts
src/plugins/query_enhancements/public/search/sql_search_interceptor.ts
src/plugins/query_enhancements/server/routes/index.ts
src/plugins/query_enhancements/server/search/ppl_search_strategy.ts
src/plugins/query_enhancements/server/search/sql_search_strategy.test.ts
src/plugins/query_enhancements/server/search/sql_search_strategy.ts

Clean up interceptor and strategies. Re-add aggregations working for PPL language
n/a
- fix: clean up language search interceptors and fix aggs for PPL

[discover] registered languages interceptor clean up and aggs

---

changelogs/fragments/7870.yml
src/plugins/data/common/data_frames/utils.ts
src/plugins/data/public/query/query_string/dataset_service/lib/index_pattern_type.ts
src/plugins/data/public/query/query_string/dataset_service/lib/index_type.ts
src/plugins/query_enhancements/common/constants.ts
src/plugins/query_enhancements/common/types.ts
src/plugins/query_enhancements/common/utils.ts
src/plugins/query_enhancements/public/datasets/s3_handler.ts
src/plugins/query_enhancements/public/search/ppl_search_interceptor.ts
src/plugins/query_enhancements/public/search/sql_search_interceptor.ts
src/plugins/query_enhancements/server/routes/index.ts
src/plugins/query_enhancements/server/search/ppl_search_strategy.ts
src/plugins/query_enhancements/server/search/sql_search_strategy.test.ts
src/plugins/query_enhancements/server/search/sql_search_strategy.ts

Backport 9b8266f178270e0e93aa82fa1e2f9c8c15737238 from #7870

[Backport 2.x] [discover] registered languages interceptor clean up and aggs (#7870)

---

changelogs/fragments/7857.yml
src/plugins/workspace/public/components/workspace_initial/__snapshots__/workspace_initial.test.tsx.snap
src/plugins/workspace/public/components/workspace_initial/workspace_initial.tsx

[](refactor: workspace initial page)
Light mode
Dark mode
no admin
- refactor: [Workspace] workspace initial page

[Workspace] refactor: workspace initial page

---

src/core/public/chrome/ui/header/header.scss

[Page header]Make header bottom border line only render for application header

---

src/plugins/data/public/query/query_string/dataset_service/lib/index_pattern_type.test.ts
src/plugins/data/public/ui/dataset_selector/configurator.tsx
src/plugins/query_enhancements/public/datasets/s3_type.ts

bad rebase caused only conflict was the dataset.
n/a
- skip

[discover][bug] configurator dataset issue

---

src/plugins/data_source_management/public/components/data_source_home_panel/data_source_home_panel.test.tsx
src/plugins/data_source_management/public/components/data_source_home_panel/data_source_home_panel.tsx
src/plugins/data_source_management/public/components/data_source_table/__snapshots__/data_source_table.test.tsx.snap
src/plugins/data_source_management/public/components/data_source_table/data_source_table.test.tsx
src/plugins/data_source_management/public/components/data_source_table/data_source_table.tsx
src/plugins/data_source_management/public/components/direct_query_data_sources_components/direct_query_data_connection/__snapshots__/manage_direct_query_data_connections_table.test.tsx.snap
src/plugins/data_source_management/public/components/direct_query_data_sources_components/direct_query_data_connection/direct_query_table.scss
src/plugins/data_source_management/public/components/direct_query_data_sources_components/direct_query_data_connection/manage_direct_query_data_connections_table.test.tsx
src/plugins/data_source_management/public/components/direct_query_data_sources_components/direct_query_data_connection/manage_direct_query_data_connections_table.tsx
src/plugins/data_source_management/public/components/utils.ts
src/plugins/data_source_management/public/mocks.ts
src/plugins/data_source_management/public/types.ts

Open a new pull request since previous pr was deleted accidentally.(https://github.com/opensearch-project/OpenSearch-Dashboards/pull/7912)
This pr implement new design for data source table in Admin->Data Sources Page:
- Add two fields related connections and type to the table.
- Add a Type Filter besides search bar
- Update direct query connections table with nested view showing direct queries connections sublist.
- Show Delete Connections button when selecting data sources.
- skip

[New]feat: add related connections and nested view to datasource table.

---

changelogs/fragments/8076.yml
src/core/server/utils/auth_info.ts
src/plugins/home/common/constants.ts
src/plugins/home/public/plugin.ts
src/plugins/workspace/public/services/use_case_service.test.ts
src/plugins/workspace/public/services/use_case_service.ts

[navigation]feat: add `sample data` menu back (#8076)

---

CHANGELOG.md

The backport bot didn't include `CHANGELOG.md` changes in #8066  for some reason. This PR adds them in manually.
- skip

Manually Adding CHANGELOG.md Changes

---

package.json
yarn.lock

Bump browserslist to prevent integration test errors
- skip

Bump browserslist to prevent integration test errors

---

src/plugins/discover/public/application/view_components/utils/use_search.ts

[Manual backport 2.17] Sync query and filter when refreshing discover page

---

src/plugins/data_source/common/data_connections/data_connection_saved_object_attributes.ts
src/plugins/data_source/server/saved_objects/data_connection.ts

Fix data-connection objects title in saved-objects page
NA
Tested by rendering the saved objects list page.
- fix: Fix the data-connection objects title

Fix data-connection objects title in saved-objects page

---

changelogs/fragments/8225.yml
package.json

Post 2.17 release action to bump version to next
Post 2.17 release action to bump version to next
- fix: Update the version post release 2.17

Post 2.17 to bump version to next

---

changelogs/fragments/8246.yml
package.json
packages/osd-ui-framework/package.json
packages/osd-ui-shared-deps/package.json
src/core/public/chrome/ui/header/__snapshots__/header.test.tsx.snap
src/plugins/data_source_management/public/components/data_source_table/__snapshots__/data_source_table.test.tsx.snap
src/plugins/data_source_management/public/components/direct_query_data_sources_components/direct_query_data_connection/__snapshots__/manage_direct_query_data_connections_table.test.tsx.snap
test/interpreter_functional/plugins/osd_tp_run_pipeline/package.json
test/plugin_functional/plugins/osd_sample_panel_action/package.json
test/plugin_functional/plugins/osd_tp_custom_visualizations/package.json
yarn.lock

Updates oui to 1.13
N/A
N/A
builds
- chore: Update oui to 1.13

chore: Update oui to 1.13

---

changelogs/fragments/8215.yml
src/plugins/workspace/public/components/home_get_start_card/use_case_card_title.tsx

Use workspace type icons for workspace avatars
Workspace selector on homepage cards - use compressed input
After fixing the issue
- fix: Fix: use workspace type icons and compressed input

[Bug] Fix: use workspace type icons and compressed input

---

docs/multi-datasource/high_level_design.md

remove unnecessary multiple data source doc link

---

.lycheeignore

Exclude https://sites.google.com/site/murmurhash from link check since it becomes unavailable
- skip

chore: Exclude https://sites.google.com/site/murmurhash from link check

---

package.json

Bump version from 2.17.0 to 2.17.1

Increment version to 2.17.1

---

changelogs/fragments/8236.yml
src/plugins/advanced_settings/public/plugin.ts
src/plugins/advanced_settings/server/plugin.ts

Backport 5ea00ad54184d5cb6bd4ecd5f96ae8155ddde84b from #8236

[Manual backport 2.x][Workspace] Drop user personal settings page (#8236)

---

.github/workflows/delete_backport_branch.yml

Refactor branch deletion for backports as current workflow has been failing 2 months.
https://github.com/opensearch-project/OpenSearch-Dashboards/actions/workflows/delete_backport_branch.yml
The author of the currently used action specified that it is no longer maintained. https://github.com/SvanBoxel/delete-merged-branch/issues/257#issuecomment-2182261868
Hence, refactoring to use GH scripts. Works as expected. See https://github.com/gaiksaya/opensearch-build-libraries/actions/runs/10930031518

Refactor branch deletion workflow for backport branches

---

src/plugins/data/public/ui/query_editor/query_editor_top_row.tsx
src/plugins/data/public/ui/query_string_input/_query_bar.scss
src/plugins/data/public/ui/query_string_input/query_bar_top_row.tsx

(cherry picked from commit 8db6a165f55aeded58e0220680dde3030b1097d1)
- skip

[Manual backport 2.x][Page Header]Fix responsiveness for dashboards & visualization app headers (#8329)

---

CHANGELOG.md
changelogs/fragments/8274.yml
changelogs/fragments/8346.yml
docs/_sidebar.md
release-notes/opensearch-dashboards.release-notes-2.17.1.md

Add release notes for 2.17.1
- doc: Add release notes for 2.17.1

Add release notes for 2.17.1

---

CHANGELOG.md
changelogs/fragments/8274.yml
changelogs/fragments/8346.yml
release-notes/opensearch-dashboards.release-notes-2.17.1.md

[Manual backport 2.17] Add release notes for 2.17.1

---

MAINTAINERS.md
changelogs/fragments/8415.yml

Add Hailong Cui(Hailong-am) as maintainer 
- doc: add Hailong-am as maintainer

add Hailong-am as maintainer

---

changelogs/fragments/8435.yml
src/plugins/home/public/application/components/home_list_card.test.tsx
src/plugins/home/public/application/components/home_list_card.tsx
src/plugins/home/public/application/home_render.test.tsx
src/plugins/home/public/application/home_render.tsx

Remove what's new card in workspace overview page
two PRs in alerting-dashboard-plugin and security-analytics-dashboard-plugin
- fix: [Workspace]Remove what's new card in workspace overview page

[Workspace] Remove whats new in workspace overview page

---

changelogs/fragments/8392.yml
src/core/public/i18n/i18n_eui_mapping.tsx
src/core/server/rendering/views/template.tsx

Fix dynamic uses of i18n in core
- fix: Fix dynamic uses of i18n in core

Fix dynamic uses of i18n in core

---

src/plugins/data/public/data_sources/constants.tsx
src/plugins/data/public/data_sources/datasource_selector/data_selector_refresher.tsx
src/plugins/data/public/data_sources/datasource_selector/datasource_selectable.tsx
src/plugins/data/public/query/query_string/language_service/lib/default_language_reference.tsx
src/plugins/data/public/query/query_string/language_service/lib/query_result.tsx
src/plugins/data/public/search/errors/timeout_error.test.tsx
src/plugins/data/public/search/errors/timeout_error.tsx
src/plugins/data/public/ui/query_editor/query_editor.tsx
src/plugins/data/public/ui/query_string_input/language_switcher.tsx

Fix dynamic uses of i18n and correct unprefixed and duplicate i18n identifiers in data plugin
- fix: Fix dynamic uses of i18n and correct unprefixed and duplicate i18n identifiers in data plugin

Fix dynamic uses of i18n and correct unprefixed and duplicate i18n identifiers in data plugin

---

changelogs/fragments/8423.yml
src/dev/i18n/extract_default_translations.d.ts
src/dev/i18n/extractors/index.d.ts
src/dev/i18n/index.ts
src/dev/i18n/tasks/check_default_messages_in_files.ts
src/dev/i18n/tasks/check_files_for_untracked_translations.ts
src/dev/i18n/tasks/index.ts
src/dev/i18n/utils/index.ts
src/dev/i18n/utils/utils.js
src/dev/precommit_hook/check_i18n.js
src/dev/precommit_hook/index.js
src/dev/run_precommit_hook.js

Cherry picked commit 520313988c02323f9190cd93ccaa8a632744d358 from #8423

[manual backport 2.x] Add precommit hook to validate i18n (#8423)

---

changelogs/fragments/8529.yml
src/core/public/chrome/ui/header/recent_items.tsx

Update the title of header recent menu
- fix: Update the title of header recent menu

[Page Header] Update the title of recent menu

---

changelogs/fragments/8564.yml
package.json
packages/osd-ui-framework/package.json
packages/osd-ui-shared-deps/package.json
test/interpreter_functional/plugins/osd_tp_run_pipeline/package.json
test/plugin_functional/plugins/osd_sample_panel_action/package.json
test/plugin_functional/plugins/osd_tp_custom_visualizations/package.json
yarn.lock

Update oui to 1.16
oui fixes:
- Filter icon being unreadable
- tooltip background in v9 dark being wrong
- updated v9 sidenav background color
N/A
Tested locally
-  chore: Update oui to 1.16

chore: Update oui to 1.16

---

changelogs/fragments/8640.yml
package.json
packages/osd-ui-framework/package.json
packages/osd-ui-shared-deps/package.json
test/interpreter_functional/plugins/osd_tp_run_pipeline/package.json
test/plugin_functional/plugins/osd_sample_panel_action/package.json
test/plugin_functional/plugins/osd_tp_custom_visualizations/package.json
yarn.lock

Updates oui to 1.17
N/A
N/A
Tested locally
- chore: Update oui to 1.17

chore: Update oui to 1.17

---

src/plugins/data/public/plugin.ts
src/plugins/data/public/query/query_service.ts
src/plugins/data/public/query/query_string/language_service/lib/dql_language.ts
src/plugins/data/public/query/query_string/language_service/lib/lucene_language.ts
src/plugins/data/public/query/query_string/query_string_manager.ts
src/plugins/data/public/query/types.ts
src/plugins/data/public/services.ts
src/plugins/visualize/public/application/utils/utils.ts

Fix Queries of Unsupported types appearing on Visualize Search Bar.
https://github.com/user-attachments/assets/f9bdfad0-957f-4da0-bd20-ca0998a99d06
https://github.com/user-attachments/assets/df6ac254-976b-41cc-8195-a4c251265164
- skip

Fix Queries of Unsupported types appearing on Visualize & Vis Builder Search Bar

---

changelogs/fragments/8682.yml
src/plugins/data/public/query/query_string/language_service/lib/language_reference.tsx
src/plugins/data/public/ui/dataset_selector/configurator.tsx
src/plugins/data/public/ui/dataset_selector/dataset_explorer.tsx
src/plugins/data/public/ui/dataset_selector/dataset_selector.tsx
src/plugins/data/public/ui/query_editor/__snapshots__/language_selector.test.tsx.snap
src/plugins/data/public/ui/query_editor/editors/default_editor/index.tsx
src/plugins/data/public/ui/query_editor/editors/shared.tsx
src/plugins/data/public/ui/query_editor/language_selector.tsx
src/plugins/data/public/ui/query_editor/query_editor.tsx
src/plugins/discover/public/application/components/no_index_patterns/no_index_patterns.tsx

Add some data test subject for discover cypress test; might have more later.
- feat: Add data test subject for discover cypress test

Add data test subject for discover cypress test

---

changelogs/fragments/8709.yml
src/core/server/index.ts
src/plugins/share/server/routes/goto.ts

Reverts opensearch-project/OpenSearch-Dashboards#8709

Revert "[workspace]fix: make goto router support workspace"

---

src/plugins/data/public/query/query_string/query_history.ts
src/plugins/data/public/query/query_string/query_string_manager.ts

Update QueryHistory to use sessionStorage
NA
- skip

Update QueryHistory to use sessionStorage

---

src/plugins/discover/public/application/components/no_results/no_results.tsx
src/plugins/query_enhancements/public/plugin.tsx

- guard against empty `tabs` in `DiscoverNoResult` to prevent crash when there are no sample queries
- convert SQL sample queries to add them to PPL
- skip

[Discover] add sample queries for PPL

---

changelogs/fragments/8783.yml
src/core/public/chrome/chrome_service.test.ts
src/core/public/chrome/chrome_service.tsx

Backport e11b4013599fa5fe39097275a53e68a39de44570 from #8783 
- skip

[Backport 2.x] fix: staled closure inside chrome_service

---

changelogs/fragments/8833.yml
src/plugins/workspace/public/components/workspace_list/index.tsx

this pr adds test id for workspace multi-deletion button
- fix: adds test id for workspace multi-deletion button

[workspace] Add test id for workspace multi-deletion button

---

changelogs/fragments/8682.yml
src/plugins/data/public/ui/dataset_selector/configurator.tsx
src/plugins/data/public/ui/dataset_selector/dataset_explorer.tsx
src/plugins/data/public/ui/dataset_selector/dataset_selector.tsx
src/plugins/data/public/ui/query_editor/__snapshots__/language_selector.test.tsx.snap
src/plugins/data/public/ui/query_editor/editors/default_editor/index.tsx
src/plugins/data/public/ui/query_editor/language_selector.tsx
src/plugins/discover/public/application/components/no_index_patterns/no_index_patterns.tsx

Manual backport of https://github.com/opensearch-project/OpenSearch-Dashboards/pull/8682

[Manual backport 2.x] Add data test subject for discover cypress test (#8682)

---

src/plugins/data/public/query/query_string/dataset_service/lib/index_pattern_type.ts

Re-enable serverless mds support for index pattern
na
na
na
- skip

Re-enable serverless mds support for index pattern

---

package.json

Bump version to 2.19 for 2.x branch
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/8073#issuecomment-2484200877
- skip

Bump version to 2.19 for 2.x branch

---

changelogs/fragments/8744.yml
changelogs/fragments/8882.yml
package.json
yarn.lock

cherry picked commit 78204a09479b72603034b5a6cda309e02bf98e57 from #8744
cherry picked commit d94fad2f3b2fd7388a3ea08857d92b28bfb1866d from #8882

[Manual backport 2.x] #8744 #8882

---

changelogs/fragments/9003.yml
src/plugins/workspace/server/saved_objects/integration_tests/workspace_id_consumer_wrapper.test.ts
src/plugins/workspace/server/saved_objects/workspace_id_consumer_wrapper.test.ts
src/plugins/workspace/server/saved_objects/workspace_id_consumer_wrapper.ts

Clear the attribute of error objects
- skip

[Workspace] Clear the attribute of error objects

---

CHANGELOG.md
release-notes/opensearch-dashboards.release-notes-1.3.20.md

Update release notes for 1.3.20
- skip

Update release notes for 1.3.20

---

release-notes/opensearch-dashboards.release-notes-1.3.20.md

Added release notes for 1.3.20
Part of https://github.com/opensearch-project/opensearch-build/issues/4990
- skip

Added release notes for 1.3.20

---

src/plugins/data_explorer/public/components/sidebar/index.tsx

Adds a data-test-subj on `src/plugins/data_explorer/public/components/sidebar/index.tsx,` which is necessary for running https://github.com/opensearch-project/OpenSearch-Dashboards/pull/9128 successfully.
- skip

add data-test-subj

---

changelogs/fragments/9159.yml
src/plugins/console/server/routes/api/console/proxy/create_handler.ts

Fix Unhandled Error Response of dev tool with MDS
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/9148
- fix: fix Unhandled Error Response of dev tool with MDS

 Fix Unhandled Error Response of dev tool with MDS

---

changelogs/fragments/9172.yml
package.json
packages/osd-ui-framework/package.json
packages/osd-ui-shared-deps/package.json
test/interpreter_functional/plugins/osd_tp_run_pipeline/package.json
test/plugin_functional/plugins/osd_sample_panel_action/package.json
test/plugin_functional/plugins/osd_tp_custom_visualizations/package.json
yarn.lock

Updates oui to 1.19
N/A
N/A
Built locally
- chore: Update oui to 1.19

chore: Update oui to 1.19

---

changelogs/fragments/9159.yml
src/plugins/console/server/routes/api/console/proxy/create_handler.ts

* Fix Unhandled Error Response of dev tool with MDS
* Changeset file for PR #9159 created/updated
---------
Co-authored-by: opensearch-changeset-bot[bot] <154024398+opensearch-changeset-bot[bot]@users.noreply.github.com>
(cherry picked from commit 32b0602cac0b0a5879d56b48e7d8587362e3b5eb)
- skip

[Backport 2.x] Fix Unhandled Error Response of dev tool with MDS (#9159)

---

changelogs/fragments/9226.yml
config/opensearch_dashboards.yml
src/plugins/workspace/config.ts
src/plugins/workspace/server/plugin.ts
src/plugins/workspace/server/workspace_client.test.ts
src/plugins/workspace/server/workspace_client.ts

In some cases, the admin may not want too many workspaces, this PR is to add a validation when users try to create workspace to see if the workspaces has exceeds the limitation, if yes, abort the create request.
- Enable workspaces: `workspace.enabled: true`
- Enable maximum workspaces limitation: `workspace.maximum_workspaces: 1`
- Create 1 workspace
- Create another workspace, you should see the error toast.
- feat: enable maximum workspaces

[Workspace]feat: enable maximum workspaces

---

changelogs/fragments/9236.yml
src/plugins/data_source_management/public/components/data_source_table/__snapshots__/data_source_table.test.tsx.snap
src/plugins/data_source_management/public/components/data_source_table/data_source_table.test.tsx
src/plugins/data_source_management/public/components/data_source_table/data_source_table.tsx
src/plugins/data_source_management/public/mocks.ts

Adding a check for null and undefined description in data source table component
fixes https://github.com/opensearch-project/OpenSearch-Dashboards/issues/9235
Adding a additional test case to cover the empty description scenarios
- fix: Solve console error on the page when the data source has an empty description

Fixing console error when the data source has an empty description

---

changelogs/fragments/9265.yml
cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/time_range_selection.spec.js
cypress/utils/apps/query_enhancements/commands.js
cypress/utils/apps/query_enhancements/shared.js
cypress/utils/apps/query_enhancements/time_range_selection.js

Add Tests for Relative, Quick & Absolute Time Range Selection
- https://github.com/opensearch-project/OpenSearch-Dashboards/issues/8941
- https://github.com/opensearch-project/OpenSearch-Dashboards/issues/8943
- feat: Add Tests for Relative and Quick Select Time Range Selection

Add Tests for Relative and Quick Select Time Range Selection

---

changelogs/fragments/9302.yml
yarn.lock

Updates the cross-spawn dependency in the yarn.lock file. 
- chore: Updates the cross-spawn dependency in the yarn.lock

Update cross-spawn dependecy in yarn.lock

---

changelogs/fragments/9407.yml
package.json

Version Bump from 2.19.0 to 2.19.1

Version Bump from 2.19.0 to 2.19.1

---

changelogs/fragments/9382.yml
src/plugins/discover/public/application/components/doc/doc.tsx

Fix view single document page content padding
Before
After
- chore: Fix view single document page content padding

[Discover] chore: Fix view single document page content padding

---

changelogs/fragments/9433.yml
cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/queries_ui.spec.js
cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/saved_queries.spec.js
cypress/utils/apps/data_explorer/commands.js
cypress/utils/apps/query_enhancements/saved_queries.js

Fix flakieness in cypress tests
- test: Fix flakieness in cypress tests

Fix flakieness in cypress tests

---

CHANGELOG.md
changelogs/fragments/9325.yml
changelogs/fragments/9407.yml
changelogs/fragments/9412.yml
changelogs/fragments/9447.yml
release-notes/opensearch-dashboards.release-notes-2.19.1.md

Add release notes for 2.19.1, changelog

Add release notes for 2.19.1

---

changelogs/fragments/9462.yml
src/plugins/data_importer/public/components/__snapshots__/data_importer_app.test.tsx.snap
src/plugins/data_importer/public/components/__snapshots__/import_type_selector.test.tsx.snap
src/plugins/data_importer/public/components/data_importer_app.test.tsx
src/plugins/data_importer/public/components/data_importer_app.tsx
src/plugins/data_importer/public/lib/cat_indices.test.ts
src/plugins/data_importer/public/lib/cat_indices.ts
src/plugins/data_importer/public/lib/import_file.test.ts
src/plugins/data_importer/public/lib/import_file.ts
src/plugins/data_importer/public/lib/import_text.test.ts
src/plugins/data_importer/public/lib/import_text.ts
src/plugins/data_importer/public/lib/preview.ts
src/plugins/data_importer/public/types.ts
src/plugins/data_importer/server/routes/cat_indices.ts
src/plugins/data_importer/server/routes/import_file.ts
src/plugins/data_importer/server/routes/import_text.ts
src/plugins/data_importer/server/routes/preview.ts

This PR does several things
- Removes system indexes (any index name that starts with `.`) from the index name selector
- Refactor cat indices into separate file
- Properly hide the delimiter selector; the selector is only shown when the file uploaded is a `csv` file or if the text box file type selector is a `csv` type
- Fix the text selector by passing in the `createMode` parameter
Checked that `.kibana` indexes aren't in the selector
1. Added different types of files `.ndjson`, `.json`, and `.csv` 
2. Checked that the delimiter is only shown in the `.csv` file
1. Selected different types of files `.ndjson`, `.json`, and `.csv` 
2. Checked that the delimiter is only shown in the `.csv` file
-fix: Remove system indexes from the index name selector

Refactor changes

---

changelogs/fragments/9464.yml
src/plugins/query_enhancements/public/query_assist/components/query_assist_summary.tsx

This pr organizes generated summary by using markdown format
- fix: organizing generated summary by using markdown format

[Workspace] organizing generated summary by using markdown format

---

changelogs/fragments/9481.yml
src/plugins/query_enhancements/common/config.ts
src/plugins/query_enhancements/public/query_assist/components/query_assist_summary.tsx
src/plugins/query_enhancements/public/query_assist/utils/create_extension.test.tsx
src/plugins/query_enhancements/public/query_assist/utils/create_extension.tsx

Added a new config `queryEnhancements.queryAssist.summary.branding.label: 'AI Assistant'` to allow customize the panel title
- feat: allow to customize discover summary panel title

feat: allow to customize discover summary panel title

---

yarn.lock

Fix failed functional test:
NA
- skip

Fix failed build integration test by update caniuse-lite version in yarn.lock

---

src/plugins/data_importer/README.md
src/plugins/data_importer/public/components/data_importer_app.tsx
src/plugins/data_importer/public/lib/cat_indices.test.ts
src/plugins/data_importer/public/lib/import_file.test.ts
src/plugins/data_importer/public/lib/preview_file.test.ts
src/plugins/data_importer/public/lib/preview_file.ts
src/plugins/data_importer/server/plugin.ts
src/plugins/data_importer/server/routes/cat_indices.ts

This PR:
- Adds tests and changes test descriptions to make them more meaningful
- Refactors several functions to remove unnecessary arguments and/or make them more writeable
- Update `README.md`
All data importer related tests pass

Add more tests + general refactoring

---

src/plugins/data_importer/server/routes/preview.ts
src/plugins/data_importer/server/utils/util.test.ts
src/plugins/data_importer/server/utils/util.ts

This PR changes `nested_objects.limit` to `depth.limit` to ensure that object layers do not exceed the cluster settings. This check also returns a default value even if the call to get the `_cluster/settings` fails.

Use `depth.limit` instead of `nested_objects.limit` as the validation for deeply nested objects

---

changelogs/fragments/9519.yml
src/plugins/query_enhancements/public/query_assist/components/query_assist_summary.test.tsx
src/plugins/query_enhancements/public/query_assist/components/query_assist_summary.tsx

Fixed one regression and one failed test for discovery summary
- fix: discover summary regression when result is empty

fixed an regression and failed test

---

changelogs/fragments/9523.yml
src/plugins/discover/public/application/view_components/canvas/discover_table.tsx
src/plugins/discover/public/application/view_components/canvas/index.tsx

Previously, we were filtering display columns in `DiscoverPanel` by comparing `indexPattern` with `columns`, then updates `columns` stored in useSelector. However, due to `indexPattern` and `columns` are store in two different data store(`useDiscoverContext` and `useSelector`), they are **not** always in sync. 
When loading a save search, mid state `indexPattern` (`undefined`) cause a undetermined `columns` overrides the actual saved columns. 
This PR move columns filter to `DiscoverTable`, filtering display columns without updating `useSelector`.
Resolve a issue that cause selected columns not being load from saved search
Before
https://github.com/user-attachments/assets/d75b10f4-ec06-4492-9562-2d0d0094fa6a
After
https://github.com/user-attachments/assets/84650819-98a9-484b-bc35-c38b4324d …

[Discover] fix: Correctly show selected cols from saved search

---

src/plugins/data_importer/public/components/preview_table.tsx
src/plugins/data_importer/server/routes/preview.ts

This PR fixes the server response so that the data can be rendered again the table view

Fix table not rendering data

---

.github/workflows/performance_testing.yml
changelogs/fragments/9534.yml

Add pull request write permission for github token in bundle ci script
- fix: pr permission write access

Add pull request write permission for github token 

---

changelogs/fragments/9553.yml
src/plugins/query_enhancements/public/query_assist/components/query_assist_summary.tsx

discover summary should use markdown
- fix: use markdown in discover summary

[workspace] discover summary should use markdown

---

changelogs/fragments/9552.yml
src/plugins/query_enhancements/public/query_assist/components/query_assist_bar.tsx
src/plugins/query_enhancements/public/query_assist/components/query_assist_input.tsx
src/plugins/query_enhancements/public/query_assist/components/query_assist_summary.tsx

1. clear discover summary if t2ppl failed
2. removed the placeholder of last ask question
- fix: clear discover summary if t2ppl failed
- fix: query-assist removed the placeholder of last ask question

fix: clear discover summary if t2ppl failed

---

src/plugins/query_enhancements/public/query_assist/components/query_assist_summary.tsx

Renamed from `fetch_summary_success` -> `generated`

rename discover summary metric name

---

src/plugins/query_enhancements/server/search/promql_search_strategy.ts

This is to improve prometheus auto-step calculation and handle the no result cases.
The auto-step calculation ensures that the samples are approximately constant across various query time frames. In this case it targets 500 samples to graph. If a `step` parameter is provided in the request it will be respected in favor of the auto-step.
- skip

improve prometheus auto-step calculation and result handling

---

src/plugins/discover/public/application/components/visualizations/vislib/line/to_expression.ts
src/plugins/discover/public/application/view_components/canvas/discover_visualization.tsx

Update visualization when there is change

Update visualization when there is change

---

changelogs/fragments/9525.yml
docs/_sidebar.md
docs/plugins/discover/getting_started_with_discover.md

Just a quick getting started with Discover 2.0. Still need to verify some of the actions with the data source and workspaces creation.
n/a
n/a
n/a
- doc: getting started with Discover 2.0

[doc] getting started with Discover 2.0

---

src/plugins/discover/public/application/components/visualizations/vislib/line/to_expression.ts

Fix legend names so they show which series and their corresponding field.
Also fix the layout so only three columns max for legends for better readability.

Fix legend name and layout

---

src/plugins/query_enhancements/server/connections/clients/base_connection_client.ts
src/plugins/query_enhancements/server/connections/clients/promql_connection_client.ts
src/plugins/query_enhancements/server/connections/managers/prometheus_manager.ts
src/plugins/query_enhancements/server/routes/resources/routes.ts

Add alertmanager and alert group resources to query enhancement endpoints for retrieving alert group resources from prometheus.

[Prometheus] Add alertmanager and alert group resources

---

src/plugins/discover/public/application/utils/state_management/discover_slice.tsx
src/plugins/discover/public/application/view_components/canvas/discover_visualization.tsx
src/plugins/discover/public/application/view_components/canvas/discover_visualization_save_modal.tsx
src/plugins/discover/public/application/view_components/utils/use_search.ts
src/plugins/discover/public/build_services.ts
src/plugins/discover/public/embeddable/constants.ts
src/plugins/discover/public/embeddable/metric_embeddable.tsx
src/plugins/discover/public/embeddable/metric_embeddable_component.tsx
src/plugins/discover/public/embeddable/metric_embeddable_factory.tsx
src/plugins/discover/public/embeddable/search_embeddable.tsx
src/plugins/discover/public/embeddable/search_embeddable_component.tsx
src/plugins/discover/public/embeddable/types.ts
src/plugins/discover/public/opensearch_dashboards_services.ts
src/plugins/discover/public/plugin.ts
src/plugins/discover/public/saved_metric_viz/_saved_metric_viz.ts
src/plugins/discover/public/saved_metric_viz/index.ts
src/plugins/discover/public/saved_metric_viz/saved_metric_viz.ts
src/plugins/discover/public/saved_metric_viz/types.ts
src/plugins/discover/server/saved_objects/index.ts
src/plugins/discover/server/saved_objects/metric.ts
src/plugins/saved_objects_management/public/register_services.ts

Save metric visualization as saved metric type; and be able to add to a new or existing dashboard. 
https://github.com/user-attachments/assets/6af9b3ac-713f-4a5f-aaa8-8a1f38317ade

Save metric viz and add to dashboard

---

changelogs/fragments/9516.yml
src/plugins/data/common/data_frames/utils.test.ts
src/plugins/data/common/data_frames/utils.ts
src/plugins/discover/public/application/components/sidebar/metrics_sidebar.tsx
src/plugins/discover/public/application/view_components/canvas/discover_visualization.tsx
src/plugins/discover/public/application/view_components/canvas/discover_visualization_save_modal.tsx
src/plugins/discover/public/application/view_components/utils/use_prometheus.ts

This is to
1. Make small styling improvements
2. Update save visual copy
3. Include a recent bugfix to add data frame null checks during response parsing
- skip

Prometheus demo polish and query fix

---

changelogs/fragments/9523.yml
src/plugins/discover/public/application/view_components/canvas/discover_table.tsx
src/plugins/discover/public/application/view_components/canvas/index.tsx

manual 2.x backport of https://github.com/opensearch-project/OpenSearch-Dashboards/pull/9523
---------
Signed-off-by: Joey Liu <jiyili@amazon.com>
Co-authored-by: opensearch-changeset-bot[bot] <154024398+opensearch-changeset-bot[bot]@users.noreply.github.com>
Co-authored-by: SuZhou-Joe <suzhou@amazon.com>
(cherry picked from commit 9f0a27e813c0fb0f56d7a0e67b3dd89efc12ef79)

[Manual backport 2.x] Correctly show selected cols from saved search (#9523)

---

.github/CODEOWNERS
MAINTAINERS.md

Add wanglam as maintainer.
- skip

feat: add wanglam as maintainer of OSD

---

CHANGELOG.md
changelogs/fragments/9304.yml
changelogs/fragments/9420.yml
changelogs/fragments/9465.yml
changelogs/fragments/9467.yml
changelogs/fragments/9497.yml
changelogs/fragments/9525.yml
changelogs/fragments/9531.yml
changelogs/fragments/9575.yml
changelogs/fragments/9581.yml
changelogs/fragments/9601.yml
changelogs/fragments/9618.yml
changelogs/fragments/9623.yml
changelogs/fragments/9628.yml
changelogs/fragments/9634.yml
changelogs/fragments/9637.yml
changelogs/fragments/9647.yml
changelogs/fragments/9649.yml
changelogs/fragments/9655.yml
docs/_sidebar.md
release-notes/opensearch-dashboards.release-notes-3.0.0-beta1.md

Adds Release Notes for `3.0.0-beta`
- skip

Add Release Notes for 3.0.0-beta1

---

changelogs/fragments/9674.yml
src/plugins/data_source/server/legacy/http_aws_es/connector.js
src/plugins/data_source/server/legacy/http_aws_es/connector.test.js

Extend essential property to generated request
fixes #9673
- fix: copy essential property to generated request

Fix: copy essential property to generated request

---

changelogs/fragments/9681.yml
package.json
yarn.lock

[CVE-2025-27789] Bump @babel/runtime,@babel/helpers and @babel/runtime-corejs3
- security: [CVE-2025-27789] Bump @babel/runtime,@babel/helpers and @babel/runtime-corejs3

[CVE-2025-27789] Bump @babel/runtime,@babel/helpers and @babel/runtime-corejs3

---

changelogs/fragments/9678.yml
src/plugins/data_source/server/legacy/http_aws_es/connector.js
src/plugins/data_source/server/legacy/http_aws_es/connector.test.js

https://github.com/opensearch-project/OpenSearch-Dashboards/issues/9679
- fix: Fix connect queryparams resulting in signer error

Fix connect queryparams resulting in signer error

---

src/plugins/data_importer/server/utils/determine_mapping.test.ts

Fix + re-enable determineMapping tests

---

src/plugins/data_source/common/data_sources/types.ts
src/plugins/data_source_management/public/components/data_source_table/__snapshots__/data_source_table.test.tsx.snap
src/plugins/data_source_management/public/components/data_source_table/data_source_table.scss
src/plugins/data_source_management/public/components/data_source_table/data_source_table.test.tsx
src/plugins/data_source_management/public/components/data_source_table/data_source_table.tsx
src/plugins/data_source_management/public/components/direct_query_data_sources_components/direct_query_data_connection/manage_direct_query_data_connections_table.tsx
src/plugins/data_source_management/public/components/utils.ts
src/plugins/data_source_management/public/mocks.ts
src/plugins/query_enhancements/common/constants.ts
src/plugins/query_enhancements/server/routes/data_source_connection/routes.ts
src/plugins/workspace/public/components/data_source_association/association_data_source_modal.scss
src/plugins/workspace/public/components/data_source_association/association_data_source_modal.test.tsx
src/plugins/workspace/public/components/data_source_association/association_data_source_modal.tsx
src/plugins/workspace/public/utils.test.ts
src/plugins/workspace/public/utils.ts

This PR aims at showing the cross cluster connections for Opensearch Connections in Data Sources and Workspaces Page. 
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/9578
Data Sources pages:
Workspace Creation page:
- Create a Domain with remote connections (https://opensearch.org/docs/latest/search-plugins/cross-cluster-search/, https://docs.aws.amazon.com/opensearch-service/latest/developerguide/cross-cluster-search.html)
- Run the application in query enhancements turned on. (`yarn start:enhancements --no-base-path` & with following options in opensearh_dashboards.yml `
opensearch.ignoreVersionMismatch: true
data_source.enabled: true
`)
- Add the domain with remote connections as a Data Source to the Application
- Navigate to the data sources …

[Cross-Cluster-Search] Show cross cluster connections in Data Sources and Workspaces page

---

changelogs/fragments/9699.yml
package.json

Bump version to 2.19.2
- chore: Version bump from 2.19.1 to 2.19.2

Bump version to 2.19.2

---

changelogs/fragments/9701.yml
src/plugins/discover/public/actions/abort_data_query_action.test.ts
src/plugins/discover/public/actions/abort_data_query_action.ts
src/plugins/discover/public/application/view_components/utils/use_search.ts
src/plugins/discover/public/build_services.ts
src/plugins/query_enhancements/public/plugin.tsx
src/plugins/query_enhancements/public/query_assist/components/query_assist_bar.test.tsx
src/plugins/query_enhancements/public/query_assist/components/query_assist_bar.tsx
src/plugins/query_enhancements/public/query_assist/hooks/use_generate.test.ts
src/plugins/query_enhancements/public/query_assist/hooks/use_generate.ts
src/plugins/query_enhancements/public/services/index.ts
src/plugins/query_enhancements/public/types.ts
src/plugins/ui_actions/public/index.ts
src/plugins/ui_actions/public/plugin.ts
src/plugins/ui_actions/public/triggers/abort_data_query_trigger.ts
src/plugins/ui_actions/public/triggers/index.ts

New implementation  
https://github.com/user-attachments/assets/3905ba10-21d5-4f85-9a9c-08ce72d93462
- fix: cancel existing query when new natural language prompt is being generated-new

Cancel existing query when new natural language prompt is being generated-new

---

CHANGELOG.md
changelogs/fragments/9659.yml
changelogs/fragments/9694.yml
changelogs/fragments/9699.yml
release-notes/opensearch-dashboards.release-notes-2.19.2.md

Add release notes for 2.19.2
- skip

Add release notes for 2.19.2

---

.github/workflows/build_and_test_workflow.yml

- chore: Update Java version in github CI

Fix Ci failure due to Java version

---

src/plugins/workspace/server/workspace_client.mock.ts
ts_error_baseline.json

Update base line error list to fix CI
- skip

Update base line error list to fix CI

---

changelogs/fragments/9789.yml
cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/04/queries_ui.spec.js
package.json

Bump to 3.1.0
- chore: bump version to 3.1.0

bump 3.1.0

---

ts_error_baseline.json

Update baseline TS error to unblock CI.
- skip

Update baseline TS error

---

.github/workflows/links_checker.yml
.lycheeignore
lychee.toml
ts_error_baseline.json

Fix broken CI job, update base line error list touched by #9848
- skip

Fix broken CI job

---

changelogs/fragments/9849.yml
cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/explore/03/field_display_filtering.spec.js
src/plugins/explore/public/application/legacy/discover/application/components/chart/hits_counter/hits_counter.tsx
src/plugins/explore/public/application/legacy/discover/application/components/doc_viewer/doc_viewer.tsx
src/plugins/explore/public/application/legacy/discover/application/components/doc_viewer/doc_viewer_render_tab.tsx
src/plugins/explore/public/application/legacy/discover/application/components/doc_viewer/doc_viewer_tab.tsx
src/plugins/explore/public/application/legacy/discover/application/components/download_csv/download_csv.tsx
src/plugins/explore/public/application/legacy/discover/application/components/download_csv/use_download_csv.ts
src/plugins/explore/public/application/legacy/discover/application/components/results_action_bar/results_action_bar.tsx
src/plugins/explore/public/application/legacy/discover/application/components/sidebar/discover_sidebar.test.tsx
src/plugins/explore/public/application/legacy/discover/application/components/sidebar/discover_sidebar.tsx
src/plugins/explore/public/application/legacy/discover/application/components/sidebar/lib/field_calculator.test.ts
src/plugins/explore/public/application/legacy/discover/application/components/sidebar/lib/field_calculator.ts
src/plugins/explore/public/application/legacy/discover/application/components/sidebar/lib/get_details.ts
src/plugins/explore/public/application/legacy/discover/application/view_components/canvas/index.tsx
src/plugins/explore/public/application/legacy/discover/application/view_components/utils/use_search.ts
src/plugins/explore/public/application/legacy/discover/opensearch_dashboards_services.ts
src/plugins/explore/public/components/data_table/explore_data_table.tsx
src/plugins/explore/public/components/tabs/tabs.scss
src/plugins/explore/public/components/tabs/tabs.stories.tsx
src/plugins/explore/public/components/tabs/tabs.tsx
src/plugins/explore/public/helpers/data_table_helper.tsx
src/plugins/explore/public/plugin.ts

Add tabs in explore, add data table to log tab
- feat: Add tabs in explore, introduce logs tab

[Explore] Add tabs in explore, add data table to log tab

---

changelogs/fragments/9857.yml
package.json
src/plugins/explore/public/components/data_table/data_table.test.tsx
src/plugins/explore/public/components/doc_viewer/doc_viewer.test.tsx
yarn.lock

Update @testing-library/user-event version
```
PASS  src/plugins/explore/public/components/doc_viewer/doc_viewer.test.tsx
DocViewer
✓ render empty if docViewsRegistry is empty (12 ms)
✓ render tab content (244 ms)
PASS  src/plugins/explore/public/components/data_table/data_table.test.tsx (6.315 s)
DefaultDiscoverTable
✓ should render the correct number of rows initially (78 ms)
✓ should load more rows when scrolling to the bottom (69 ms)
✓ should display the sample size callout when all rows are rendered (611 ms)
✓ Should restart rendering when new data is available (110 ms)
✓ should pagination (420 ms)
```
- fix: Update @testing-library/user-event version

Update @testing-library/user-event version

---

changelogs/fragments/9843.yml
package.json

Version bump from 2.19.2 to 2.19.3
- chore: Version bump from 2.19.2 to 2.19.3

Bump version to 2.19.3

---

src/core/server/ui_settings/saved_objects/permission_controlled_ui_settings_wrapper.test.ts
src/core/server/ui_settings/saved_objects/permission_controlled_ui_settings_wrapper.ts

Change from using alias to relative path. 
This is to avoid plugins that does not modify babel config due to recent change in aliasing from failing the test cases.
- skip

[Chore] Remove alias in permission controlled UI settings wrapper

---

changelogs/fragments/9901.yml
src/plugins/explore/public/application/app.tsx
src/plugins/explore/public/application/register_tabs.ts
src/plugins/explore/public/application/utils/state_management/selectors/index.ts
src/plugins/explore/public/components/data_table/explore_data_table.tsx
src/plugins/explore/public/components/tabs/action_bar/action_bar.tsx
src/plugins/explore/public/components/tabs/logs_tab.tsx
src/plugins/explore/public/components/tabs/tabs.scss
src/plugins/explore/public/components/tabs/tabs.tsx
src/plugins/explore/public/components/tabs/vis_tab.tsx
src/plugins/explore/public/components/visualizations/utils/to_expression.ts
src/plugins/explore/public/components/visualizations/visualization_container.tsx
src/plugins/explore/public/services/tab_registry/tab_registry_service.ts

Consume tab registry service and related state in explore tabs
- feat: Consume tab registry service and related state in explore tabs

Consume tab registry service and related state in explore tabs

---

changelogs/fragments/9912.yml
src/plugins/explore/public/components/visualizations/heatmap/heatmap_vis_config.ts
src/plugins/explore/public/components/visualizations/heatmap/heatmap_vis_options.tsx
src/plugins/explore/public/components/visualizations/line/line_vis_config.ts
src/plugins/explore/public/components/visualizations/line/line_vis_options.tsx
src/plugins/explore/public/components/visualizations/metric/metric_vis_config.ts
src/plugins/explore/public/components/visualizations/metric/metric_vis_options.tsx
src/plugins/explore/public/components/visualizations/pie/pie_vis_config.ts
src/plugins/explore/public/components/visualizations/pie/pie_vis_options.tsx
src/plugins/explore/public/components/visualizations/scatter/scatter_vis_config.ts
src/plugins/explore/public/components/visualizations/scatter/scatter_vis_options.tsx
src/plugins/explore/public/components/visualizations/utils/use_visualization_types.ts
src/plugins/explore/public/components/visualizations/visualization.stories.tsx
src/plugins/explore/public/components/visualizations/visualization.test.tsx
src/plugins/explore/public/components/visualizations/visualization.tsx
src/plugins/explore/public/components/visualizations/visualization_container.tsx

Improved the TS types of explore visualization related interfaces
- refactor: refactor TS types of explore visualization related interfaces

[Explore] Fix explore vis types

---

changelogs/fragments/9932.yml
src/plugins/explore/public/application/app.tsx
src/plugins/explore/public/application/legacy/discover/application/view_components/canvas/discover_chart_container.tsx
src/plugins/explore/public/application/legacy/discover/application/view_components/panel/index.tsx
src/plugins/explore/public/application/utils/state_management/actions/query_actions.ts

Introduce `histogramResultsProcessor` to process raw result for histogram UI
Update `createSearchSourceWithQuery` to correctly process histogram aggregation 
Fixed a issue that changing time interval of histogram in Explore have no effect
Fixed a issue that time format of histogram x-axis in Explore is incorrect
Before:
After:
- fix: fix histogram UI in Explore

[Explore] fix histogram UI

---

changelogs/fragments/9920.yml
src/plugins/explore/public/components/visualizations/bar/bar_exclusive_vis_options.stories.tsx
src/plugins/explore/public/components/visualizations/bar/bar_exclusive_vis_options.test.tsx
src/plugins/explore/public/components/visualizations/bar/bar_exclusive_vis_options.tsx
src/plugins/explore/public/components/visualizations/bar/bar_vis_config.test.ts
src/plugins/explore/public/components/visualizations/bar/bar_vis_config.ts
src/plugins/explore/public/components/visualizations/bar/bar_vis_options.stories.tsx
src/plugins/explore/public/components/visualizations/bar/bar_vis_options.test.tsx
src/plugins/explore/public/components/visualizations/bar/bar_vis_options.tsx
src/plugins/explore/public/components/visualizations/bar/to_expression.test.ts
src/plugins/explore/public/components/visualizations/bar/to_expression.ts
src/plugins/explore/public/components/visualizations/rule_repository.ts
src/plugins/explore/public/components/visualizations/types.ts
src/plugins/explore/public/components/visualizations/utils/use_visualization_types.ts
src/plugins/explore/public/components/visualizations/visualization_container.tsx
src/plugins/explore/public/components/visualizations/visualization_registry.ts

Bar charts with style panel. Updated the following three rules
1 metric + 1 category --> bar
Ex: stats min(products.base_price) by manufacturer
1 metric + 2 category(low cardinality) --> stacked bar
Ex: stats min(products.base_price) by manufacturer, customer_gender
1 metric + 2 category(high cardinality) --> heatmap
Ex: stats min(products.base_price) by manufacturer, customer_gender
- feat: Add bar chart with style panel

[Explore vis] Bar chart with vis controls

---

src/plugins/explore/public/components/visualizations/README.md
src/plugins/explore/public/components/visualizations/RULES.md

Add two readmes for how to register new chart type and new rules and a outline of the current predefined rules
- feat: Add explore vis developer doc

Explore vis developer doc

---

src/plugins/data/public/antlr/opensearch_ppl/code_completion_simplified.test.ts
src/plugins/data/public/antlr/opensearch_ppl/simplified_ppl_grammar/opensearch_ppl_autocomplete.ts

Remove FieldName Suggestion directly after a FieldName in Field list. 
Before:
After:
- fix: Remove FieldName Suggestion directly after a FieldName in Field list

Remove FieldName Suggestion directly after a FieldName in Field list

---

changelogs/fragments/9972.yml
src/plugins/explore/public/application/components/query_panel.tsx
src/plugins/explore/public/application/legacy/discover/application/components/panel/canvas_panel.tsx
src/plugins/explore/public/application/pages/logs/logs_page.scss
src/plugins/explore/public/application/pages/logs/logs_page.test.tsx
src/plugins/explore/public/application/pages/logs/logs_page.tsx
src/plugins/explore/public/application/pages/metrics/metrics_page.scss
src/plugins/explore/public/application/pages/metrics/metrics_page.test.tsx
src/plugins/explore/public/application/pages/metrics/metrics_page.tsx
src/plugins/explore/public/application/pages/traces/traces_page.scss
src/plugins/explore/public/application/pages/traces/traces_page.test.tsx
src/plugins/explore/public/application/pages/traces/traces_page.tsx
yarn.lock

Adjust panels layout on Explore page
- fix: Adjust panels layout on Explore page

[Explore] Fix: Adjust panels layout

---

changelogs/fragments/9973.yml
src/plugins/explore/public/components/visualizations/area/area_vis_config.ts
src/plugins/explore/public/components/visualizations/area/area_vis_options.tsx
src/plugins/explore/public/components/visualizations/area/to_expression.ts
src/plugins/explore/public/components/visualizations/rule_repository.ts
src/plugins/explore/public/components/visualizations/utils/use_visualization_types.ts
src/plugins/explore/public/components/visualizations/visualization_container.tsx
src/plugins/explore/public/components/visualizations/visualization_registry.ts

Add area chart as available chart types under multiple rules. 
https://github.com/user-attachments/assets/7f369ba6-5636-4fdb-8e52-ff2843e41407
https://github.com/user-attachments/assets/15877456-6fe2-4eac-92d4-815e07f89b9a
- feat: Add area chart as available chart types

[Explore Vis] Add area chart as available chart types

---

changelogs/fragments/9978.yml
src/plugins/explore/public/application/legacy/discover/application/components/top_nav/open_search_panel.tsx
src/plugins/explore/public/application/legacy/discover/application/view_components/canvas/top_nav.tsx
src/plugins/explore/public/application/utils/hooks/use_saved_explore.ts
src/plugins/explore/public/application/utils/state_management/slices/ui_slice.ts
src/plugins/explore/public/application/utils/state_management/utils/url.ts
src/plugins/explore/public/types/saved_explore_types.ts
src/plugins/explore/server/saved_objects/explore.ts

Support loading state from object
- feat: Support loading state from object

[Explore] feat: support loading state from object

---

src/plugins/explore/public/application/legacy/discover/application/components/top_nav/get_top_nav_links.tsx
src/plugins/explore/public/application/legacy/discover/application/components/top_nav/open_search_panel.tsx
src/plugins/explore/public/application/legacy/discover/application/view_components/canvas/top_nav.tsx
src/plugins/explore/public/application/pages/logs/logs_page.tsx
src/plugins/explore/public/application/pages/metrics/metrics_page.tsx
src/plugins/explore/public/application/pages/traces/traces_page.tsx
src/plugins/explore/public/types.ts

minor type and prop changes

---

src/plugins/explore/public/application/legacy/discover/application/components/top_nav/get_top_nav_links.tsx
src/plugins/explore/public/application/legacy/discover/application/view_components/canvas/top_nav.tsx

remove inspect from top nav

---

src/plugins/explore/public/application/index.tsx
src/plugins/explore/public/application/pages/logs/logs_page.tsx
src/plugins/explore/public/application/pages/metrics/metrics_page.tsx
src/plugins/explore/public/application/pages/traces/traces_page.tsx
src/plugins/explore/public/assets/sparkle_mark.svg
src/plugins/explore/public/build_services.ts
src/plugins/explore/public/components/results_summary/results_summary.test.tsx
src/plugins/explore/public/components/results_summary/results_summary.tsx
src/plugins/explore/public/components/results_summary/results_summary_panel.scss
src/plugins/explore/public/components/results_summary/results_summary_panel.tsx
src/plugins/explore/public/plugin.ts
src/plugins/explore/public/types.ts

[Explore] Add AI summary component in explore plugin 

---

src/plugins/explore/public/components/visualizations/rule_repository.ts
src/plugins/explore/public/components/visualizations/types.ts
src/plugins/explore/public/components/visualizations/visualization.tsx
src/plugins/explore/public/components/visualizations/visualization_container.tsx
src/plugins/explore/public/components/visualizations/visualization_empty_state.tsx
src/plugins/explore/public/components/visualizations/visualization_registry.ts

[Explore] Add fields selection when there is no rule matched

---

src/plugins/dashboard/public/application/components/dashboard_top_nav/top_nav/show_add_panel_popover.tsx
src/plugins/dashboard/public/application/utils/get_nav_actions.tsx
src/plugins/dashboard/public/index.ts
src/plugins/dashboard/public/plugin.tsx
src/plugins/dashboard/public/types.ts
src/plugins/dashboard/public/ui_triggers.ts
src/plugins/explore/opensearch_dashboards.json
src/plugins/explore/public/helpers/visualization_action_menu.tsx
src/plugins/explore/public/plugin.ts
src/plugins/visualizations/opensearch_dashboards.json
src/plugins/visualizations/public/plugin.ts
src/plugins/visualizations/public/vis_types/types_service.ts
src/plugins/visualizations/public/wizard/new_vis_actions.tsx

https://github.com/user-attachments/assets/c1b1eb74-b237-44af-b4a3-a3389290b59b

[Explore] add new create panel dropdown to dashboard

---

src/plugins/explore/public/application/legacy/discover/application/components/top_nav/get_top_nav_links.tsx
src/plugins/explore/public/application/legacy/discover/application/view_components/canvas/top_nav.tsx
src/plugins/explore/public/application/utils/state_management/slices/ui/ui_slice.ts
src/plugins/explore/public/components/visualizations/utils/use_visualization_types.ts
src/plugins/explore/public/components/visualizations/visualization_empty_state.tsx
src/plugins/explore/public/embeddable/explore_embeddable.tsx
src/plugins/explore/public/embeddable/explore_embeddable_component.tsx
src/plugins/explore/public/embeddable/explore_embeddable_factory.tsx
src/plugins/explore/public/saved_explore/transforms.ts
src/plugins/explore/public/types/saved_explore_types.ts

feat: add table for explore embeddable
Code will be refined later, this is mainly for functionality. 
- feat: Add table for explore embeddable

[Explore]feat: add table for explore embeddable

---

src/plugins/explore/public/application/legacy/discover/application/view_components/canvas/top_nav.tsx
src/plugins/explore/public/application/utils/state_management/selectors/index.ts
src/plugins/explore/public/components/top_nav/top_nav_links/get_top_nav_links.ts
src/plugins/explore/public/components/top_nav/top_nav_links/top_nav_open/open_search_panel/open_search_panel.tsx
src/plugins/explore/public/components/top_nav/top_nav_links/top_nav_save/top_nav_save.tsx
src/plugins/explore/public/components/visualizations/utils/use_visualization_types.ts
src/plugins/explore/public/embeddable/explore_embeddable.tsx
src/plugins/explore/public/embeddable/explore_embeddable_component.tsx
src/plugins/explore/public/saved_explore/transforms.ts
src/plugins/explore/public/types/saved_explore_types.ts
src/plugins/explore/server/saved_objects/explore.ts

1. Fix top nav save not work after top nav refactor
2. Add active tab storage
3. Implement save with new state management
4. Remove extra search source creation
5. Update vis view url
- skip

[Explore] Add tab storage and fix nav save

---

src/plugins/explore/public/application/legacy/discover/application/view_components/canvas/top_nav.tsx
src/plugins/explore/public/application/pages/logs/logs_page.tsx
src/plugins/explore/public/application/pages/metrics/metrics_page.tsx
src/plugins/explore/public/application/pages/traces/traces_page.tsx
src/plugins/explore/public/application/utils/hooks/use_page_initialization.ts
src/plugins/explore/public/application/utils/hooks/use_saved_explore.ts

Moved side effects to `useInitPage` hook to make `useSavedExplore` hook reusable and side-effect-free

[Explore] Refactor use saved explore hook

---

src/plugins/explore/public/components/visualizations/area/area_vis_config.ts
src/plugins/explore/public/components/visualizations/area/area_vis_options.tsx
src/plugins/explore/public/components/visualizations/area/to_expression.ts
src/plugins/explore/public/components/visualizations/bar/bar_vis_options.tsx
src/plugins/explore/public/components/visualizations/line/line_vis_options.tsx
src/plugins/explore/public/components/visualizations/metric/metric_vis_options.tsx
src/plugins/explore/public/components/visualizations/pie/pie_exclusive_vis_options.tsx
src/plugins/explore/public/components/visualizations/pie/pie_vis_config.ts
src/plugins/explore/public/components/visualizations/pie/pie_vis_options.tsx
src/plugins/explore/public/components/visualizations/pie/to_expression.ts
src/plugins/explore/public/components/visualizations/style_panel/axes/axes.tsx
src/plugins/explore/public/components/visualizations/style_panel/custom_ranges.tsx
src/plugins/explore/public/components/visualizations/style_panel/grid/grid.tsx
src/plugins/explore/public/components/visualizations/style_panel/legend/legend.tsx
src/plugins/explore/public/components/visualizations/style_panel/threshold/threshold.tsx
src/plugins/explore/public/components/visualizations/style_panel/tooltip/tooltip.tsx

Update Area, Pie and Metric style panel UI

Update Area, Pie and Metric style panel UI

---

src/plugins/explore/public/components/experience_banners/classic_experience_banner/classic_experience_banner.tsx
src/plugins/query_enhancements/public/query_assist/components/query_assist_banner.tsx

update banner font

---

src/plugins/explore/public/application/legacy/discover/application/components/chart/chart.tsx
src/plugins/explore/public/components/query_panel/components/footer/date_time_selector.tsx
src/plugins/explore/public/components/query_panel/components/footer/index.tsx
src/plugins/explore/public/components/query_panel/query_panel.tsx

Adds the execute query logic to the histogram and date picker quick select menu
- skip

[Explore] Add execute dispatch to histogram and quick select

---

src/plugins/explore/public/application/utils/hooks/use_page_initialization.ts
src/plugins/explore/public/components/visualizations/visualization.tsx
src/plugins/explore/public/components/visualizations/visualization_container.tsx

[Explore] tweaks visualization panel styles

---

src/plugins/data/public/query/saved_query/saved_query_service.ts
src/plugins/explore/public/components/query_panel/components/editor_stack/editor_stack.tsx
src/plugins/explore/public/components/query_panel/components/editor_stack/prompt_editor.tsx
src/plugins/explore/public/components/query_panel/components/footer/index.scss
src/plugins/explore/public/components/query_panel/hooks/index.ts
src/plugins/explore/public/components/query_panel/hooks/use_query_assist/index.ts
src/plugins/explore/public/components/query_panel/hooks/use_query_assist/use_query_assist.ts
src/plugins/explore/public/components/query_panel/index.scss
src/plugins/explore/public/components/query_panel/query_panel.tsx
src/plugins/explore/public/components/query_panel/utils/constants.ts
src/plugins/explore/public/components/query_panel/utils/error.ts

- This reworks #9957 with the query_enhancements removed
- It is still buggy but will allow users to test the prompt for now. I will fix the bugs in a future PR

rework 9957

---

changelogs/fragments/10048.yml
src/plugins/explore/public/application/legacy/discover/application/components/sidebar/discover_sidebar.test.tsx
src/plugins/explore/public/application/legacy/discover/application/components/sidebar/discover_sidebar.tsx
src/plugins/explore/public/application/legacy/discover/application/components/sidebar/lib/group_fields.test.ts
src/plugins/explore/public/application/legacy/discover/application/components/sidebar/lib/group_fields.ts
src/plugins/explore/public/application/legacy/discover/application/view_components/panel/index.tsx

Update fields selector grouping, replace `selected` `popular` and `available` grouping with `result` and `schema` grouping
- feat: Update fields selector grouping

[Explore] Update fields selector grouping

---

src/plugins/explore/public/components/visualizations/heatmap/heatmap_vis_options.tsx
src/plugins/explore/public/components/visualizations/scatter/scatter_exclusive_vis_options.test.tsx
src/plugins/explore/public/components/visualizations/scatter/scatter_exclusive_vis_options.tsx
src/plugins/explore/public/components/visualizations/scatter/scatter_vis_config.ts
src/plugins/explore/public/components/visualizations/scatter/scatter_vis_options.tsx
src/plugins/explore/public/components/visualizations/scatter/to_expression.ts

this pr updates  scatter style panel UI
- fix: Update scatter style panel UI

[Explore] Update scatter style panel UI

---

src/plugins/explore/public/application/utils/state_management/__mocks__/chart_utils.ts
src/plugins/explore/public/application/utils/state_management/slices/tab/tab_slice.test.ts
src/plugins/explore/public/components/query_panel/editor_stack/edit_toolbar/edit_toolbar.test.tsx
src/plugins/explore/public/components/query_panel/mock_provider.mocks.tsx

there were some broken unit tests after several of our changes

fix some broken unit tests

---

src/plugins/explore/public/application/utils/hooks/use_page_initialization.ts
src/plugins/explore/public/components/top_nav/top_nav.tsx
src/plugins/explore/public/embeddable/explore_embeddable.tsx
src/plugins/explore/public/embeddable/explore_embeddable_factory.tsx
src/plugins/explore/public/plugin.ts

1. fix saved explore cannot open from a dashboard
2. fix build fail due to importing unused scss

[Explore] fix saved explore cannot open from a dashboard

---

src/plugins/explore/public/components/data_table/explore_data_table.tsx
src/plugins/explore/public/components/visualizations/bar/bar_exclusive_vis_options.tsx
src/plugins/explore/public/components/visualizations/bar/bar_vis_options.tsx
src/plugins/explore/public/components/visualizations/chart_type_selector.tsx
src/plugins/explore/public/components/visualizations/heatmap/heatmap_exclusive_vis_options.tsx
src/plugins/explore/public/components/visualizations/line/exclusive_style.tsx
src/plugins/explore/public/components/visualizations/metric/metric_vis_options.tsx
src/plugins/explore/public/components/visualizations/scatter/scatter_exclusive_vis_options.tsx
src/plugins/explore/public/components/visualizations/style_panel/axes/axes.tsx
src/plugins/explore/public/components/visualizations/style_panel/axes/axes_selector.tsx
src/plugins/explore/public/components/visualizations/style_panel/axes_options.tsx
src/plugins/explore/public/components/visualizations/style_panel/basic_vis_options.tsx
src/plugins/explore/public/components/visualizations/style_panel/chart_type_switcher.tsx
src/plugins/explore/public/components/visualizations/style_panel/custom_ranges.tsx
src/plugins/explore/public/components/visualizations/style_panel/general_vis_options.tsx
src/plugins/explore/public/components/visualizations/style_panel/standard_axes_options.tsx
src/plugins/explore/public/components/visualizations/style_panel/style_accordion.tsx
src/plugins/explore/public/components/visualizations/style_panel/threshold/threshold.tsx
src/plugins/explore/public/components/visualizations/style_panel/threshold_options.tsx
src/plugins/explore/public/components/visualizations/style_panel/utils.tsx
src/plugins/explore/public/components/visualizations/visualization.tsx

[Explore] tweaks styles panel and use compressed style components

---

changelogs/fragments/10092.yml
src/plugins/explore/public/application/legacy/discover/application/components/sidebar/discover_sidebar.tsx
src/plugins/explore/public/application/legacy/discover/application/view_components/panel/index.tsx
src/plugins/explore/public/application/pages/logs/logs_page.tsx
src/plugins/explore/public/components/chart/_histogram.scss
src/plugins/explore/public/components/chart/chart.tsx
src/plugins/explore/public/components/chart/discover_chart_container.scss
src/plugins/explore/public/components/chart/discover_chart_container.tsx
src/plugins/explore/public/components/chart/histogram/histogram.tsx
src/plugins/explore/public/components/chart/timechart_header/timechart_header.tsx

Changes this PR contains:
1. Update explore chart UI
2. Remove add index pattern related UI from fields selector
3. Fix a issue showing empty white panel when query result does not contain time fields
- feat: Update explore chart UI

[Explore] Update explore chart UI

---

src/plugins/explore/public/application/utils/state_management/actions/query_actions.test.ts
src/plugins/explore/public/application/utils/state_management/actions/query_actions.ts
src/plugins/query_enhancements/public/search/ppl_search_interceptor.ts

support key-value

---

changelogs/fragments/10096.yml
src/plugins/explore/public/application/register_tabs.ts
src/plugins/explore/public/components/tabs/tabs.scss
src/plugins/explore/public/components/visualizations/visualization.tsx
src/plugins/explore/public/components/visualizations/visualization_container.scss
src/plugins/explore/public/components/visualizations/visualization_container.tsx

Update Viz tab scroll and resize behavior
https://github.com/user-attachments/assets/f08717a6-5a95-4514-9c2a-a6d22452da86
- fix: Update Viz tab scroll and resize behavior

[Explore] fix Viz tab scroll and resize behavior

---

src/plugins/explore/public/components/query_panel/utils/use_top_editor/use_top_editor.ts

fix options for top_editor

---

src/plugins/query_enhancements/public/plugin.tsx

https://github.com/opensearch-project/OpenSearch-Dashboards/pull/9953#discussion_r2166043524 changed PPL language `fields.filterable` to `undefined`. Rather than the language overriding `filterable` as true or false, `undefined` allows `filterable` to come from fields, which is the behavior we want for languages that support filters.
But setting it as `undefined` also enabled filtering in classic discover, where we don't have filter support for PPL.
This PR makes the PPL language filterable value to be dynamic. If the current app id is explore or dashboards, then it is `undefined` and will use the value from individual fields, otherwise PPL is not filterable.
- skip

[Explore] only allow PPL to be filterable in explore and dashboards

---

changelogs/fragments/10095.yml
src/plugins/data/public/antlr/opensearch_ppl/code_completion.ts
src/plugins/data/public/antlr/opensearch_ppl/code_completion_simplified.test.ts
src/plugins/data/public/antlr/opensearch_ppl/ppl_documentation.ts
src/plugins/data/public/autocomplete/providers/query_suggestion_provider.ts
src/plugins/explore/public/components/query_panel/utils/use_shared_editor/use_shared_editor.ts
src/plugins/opensearch_dashboards_react/public/code_editor/editor_theme.ts

- Add Documentations for PPL Commands
https://github.com/user-attachments/assets/bfa09385-3d7b-4bbd-ba2c-8c1cfab1f838
- feat: Add Documentations for PPL Commands

Add Documentations for PPL Commands

---

src/plugins/data/public/antlr/shared/utils.test.ts
src/plugins/data/public/antlr/shared/utils.ts

Filter out Null Values in Suggestions
- fix: Filter out Null Values in Suggestions

Filter out Null Values in Suggestions

---

changelogs/fragments/10113.yml
src/plugins/explore/public/components/chart/chart.test.tsx
src/plugins/explore/public/components/chart/chart.tsx

fixed a issue that cause chart time range update unexpectedly
- fix: Fixed a issue that cause chart time range update unexpectedly

[Explore] fix a issue that cause chart time range update unexpectedly

---

src/plugins/explore/public/components/visualizations/chart_type_selector.test.tsx
src/plugins/explore/public/components/visualizations/style_panel/axes/axes_selector.tsx
src/plugins/explore/public/components/visualizations/visualization_container.test.tsx
src/plugins/explore/public/components/visualizations/visualization_container.tsx
src/plugins/explore/public/components/visualizations/visualization_container_utils.test.ts

[Explore] Fix axes select not get update when we click switch axes button and add unit tests

---

changelogs/fragments/10127.yml
packages/osd-monaco/src/ppl/constants.ts
src/plugins/opensearch_dashboards_react/public/code_editor/editor_theme.ts

Fix Antlr to Moncao Token Mappings
- fix: Fix Antlr to Moncao Token Mappings

Fix Antlr to Moncao Token Mappings

---

src/plugins/explore/public/application/utils/state_management/actions/reset_explore_state/reset_explore_state.test.ts
src/plugins/explore/public/application/utils/state_management/actions/reset_explore_state/reset_explore_state.ts
src/plugins/explore/public/components/top_nav/top_nav.tsx
src/plugins/explore/public/components/top_nav/top_nav_links/get_top_nav_links.test.ts
src/plugins/explore/public/components/top_nav/top_nav_links/get_top_nav_links.ts
src/plugins/explore/public/components/top_nav/top_nav_links/top_nav_new/top_nav_new.test.ts
src/plugins/explore/public/components/top_nav/top_nav_links/top_nav_new/top_nav_new.ts

[Explore] Fix new

---

package.json
packages/osd-monaco/src/ppl/language.ts
packages/osd-ui-framework/package.json
packages/osd-ui-shared-deps/package.json
src/plugins/data/public/antlr/opensearch_ppl/code_completion.ts
src/plugins/data/public/antlr/opensearch_ppl/code_completion_simplified.test.ts
src/plugins/data/public/antlr/opensearch_ppl/constants.ts
src/plugins/explore/public/components/query_panel/utils/use_shared_editor/use_shared_editor.ts
test/interpreter_functional/plugins/osd_tp_run_pipeline/package.json
test/plugin_functional/plugins/osd_sample_panel_action/package.json
test/plugin_functional/plugins/osd_tp_custom_visualizations/package.json
yarn.lock

- Reorder Autocomplete Suggestions
- Minor Cleanup
- OUI Version bump to 1.20.0 
- fix: Reorder Autocomplete Suggestions

Reorder Autocomplete Suggestions

---

src/plugins/explore/public/application/utils/state_management/actions/query_editor/on_editor_run/call_agent/call_agent.test.ts
src/plugins/explore/public/application/utils/state_management/actions/query_editor/on_editor_run/call_agent/call_agent.ts
src/plugins/explore/public/application/utils/state_management/selectors/query_editor/query_editor.test.ts
src/plugins/explore/public/application/utils/state_management/selectors/query_editor/query_editor.ts
src/plugins/explore/public/application/utils/state_management/slices/query_editor/query_editor_slice.test.ts
src/plugins/explore/public/application/utils/state_management/slices/query_editor/query_editor_slice.ts
src/plugins/explore/public/application/utils/state_management/utils/redux_persistence.ts
src/plugins/explore/public/components/query_panel/editor_stack/editor_stack.test.tsx
src/plugins/explore/public/components/query_panel/editor_stack/editor_stack.tsx
src/plugins/explore/public/components/query_panel/editor_stack/top_editor/top_editor.scss
src/plugins/explore/public/components/query_panel/editor_stack/top_editor/top_editor.tsx
src/plugins/explore/public/components/query_panel/mock_provider.mocks.tsx

- got a bug ticket that when prompt is being translated to PPL, there is no loading indicator.

[Explore] Loader for prompt to query

---

changelogs/fragments/10158.yml
src/plugins/explore/public/application/pages/logs/logs_page.test.tsx
src/plugins/explore/public/application/pages/logs/logs_page.tsx
src/plugins/explore/public/application/pages/metrics/metrics_page.test.tsx
src/plugins/explore/public/application/pages/metrics/metrics_page.tsx
src/plugins/explore/public/application/pages/traces/traces_page.test.tsx
src/plugins/explore/public/application/pages/traces/traces_page.tsx
src/plugins/explore/public/components/container/bottom_container/bottom_container.test.tsx
src/plugins/explore/public/components/container/bottom_container/bottom_container.tsx

Moving `Topnav` component out from the `ResizableContainer` to prevent it from constantly re-render. Which will prevent unnecessary saved object fetch and top nav loading icon flicker
- fix: Fix a issue causing unnecessary saved object fetch and top nav loading icon flicker flicker

[Explore] Fix a issue causing unnecessary saved object fetch and top nav loading icon flicker

---

src/plugins/explore/public/components/visualizations/area/area_vis_config.test.ts
src/plugins/explore/public/components/visualizations/area/area_vis_options.test.tsx
src/plugins/explore/public/components/visualizations/area/to_expression.test.ts
src/plugins/explore/public/components/visualizations/bar/bar_exclusive_vis_options.test.tsx
src/plugins/explore/public/components/visualizations/bar/bar_vis_config.test.ts
src/plugins/explore/public/components/visualizations/bar/to_expression.test.ts
src/plugins/explore/public/components/visualizations/heatmap/heatmap_chart_utils.test.ts
src/plugins/explore/public/components/visualizations/heatmap/heatmap_exclusive_vis_options.tsx
src/plugins/explore/public/components/visualizations/heatmap/heatmap_vis_config.test.ts
src/plugins/explore/public/components/visualizations/heatmap/heatmap_vis_options.test.tsx
src/plugins/explore/public/components/visualizations/line/to_expression.test.ts
src/plugins/explore/public/components/visualizations/metric/to_expression.test.ts
src/plugins/explore/public/components/visualizations/pie/pie_vis_options.test.tsx
src/plugins/explore/public/components/visualizations/pie/to_expression.test.ts
src/plugins/explore/public/components/visualizations/rule_repository.test.ts
src/plugins/explore/public/components/visualizations/scatter/scatter_vis_config.test.tsx
src/plugins/explore/public/components/visualizations/scatter/scatter_vis_options.test.tsx
src/plugins/explore/public/components/visualizations/scatter/to_expression.test.ts
src/plugins/explore/public/components/visualizations/utils/to_expression.test.ts
src/plugins/explore/public/components/visualizations/visualization.test.tsx
src/plugins/explore/public/components/visualizations/visualization.tsx
src/plugins/explore/public/components/visualizations/visualization_container.test.tsx
src/plugins/explore/public/components/visualizations/visualization_registry.test.ts

Fix unit tests and add coverage for explore vis

Fix unit tests and add coverage for explore vis

---

changelogs/fragments/10140.yml
src/plugins/explore/public/application/legacy/discover/application/components/sidebar/discover_field_search.tsx
src/plugins/explore/public/application/legacy/discover/application/components/sidebar/lib/field_filter.test.ts
src/plugins/explore/public/application/legacy/discover/application/components/sidebar/lib/field_filter.ts
src/plugins/explore/public/components/chart/chart.test.tsx
src/plugins/explore/public/components/data_table/explore_data_table.tsx
src/plugins/explore/public/components/tabs/action_bar/action_bar.test.tsx
src/plugins/explore/public/components/tabs/action_bar/download_csv/download_csv.tsx
src/plugins/explore/public/components/tabs/action_bar/results_action_bar/results_action_bar.test.tsx
src/plugins/explore/public/components/tabs/action_bar/results_action_bar/results_action_bar.tsx
src/plugins/explore/public/components/visualizations/add_to_dashboard_button.tsx

1. Change fields selector default setting to show missing fields
2. Some component style update 
3. Disable inspect button due to data consistency issue
- feat: Change fields selector default setting to show missing fields

[Explore] Change fields selector default setting to show missing fields

---

src/plugins/explore/public/components/chart/chart.test.tsx
src/plugins/explore/public/components/chart/discover_chart_container.test.tsx
src/plugins/explore/public/components/chart/histogram/histogram.test.tsx
src/plugins/explore/public/components/chart/histogram/type.test.ts
src/plugins/explore/public/components/chart/utils/create_histogram_configs.test.ts
src/plugins/explore/public/components/tabs/patterns_tab.test.tsx
src/plugins/explore/public/components/visualizations/visualization_container.tsx
src/plugins/explore/public/url_generator.ts

1. Improve UT coverage in chart component
2. Fix some lint and type error
- skip

[Explore] Improve UT coverage in chart component

---

src/plugins/explore/public/application/utils/state_management/store.ts
src/plugins/explore/public/components/query_panel/query_panel.scss

- ts errors and padding for query_panel folder

[Explore] Ts errors and padding

---

src/plugins/explore/public/components/top_nav/top_nav_links/top_nav_open/open_search_panel/open_search_panel.test.tsx
src/plugins/explore/public/components/top_nav/top_nav_links/top_nav_save/top_nav_save.test.tsx
src/plugins/explore/public/components/top_nav/top_nav_links/top_nav_share/helpers.test.ts

Improve UT coverage for topNav component
- skip

[Explore] Improve UT coverage for topNav component

---

src/plugins/explore/public/application/utils/state_management/actions/query_actions.test.ts

fix ut for query_action

---

src/plugins/explore/public/application/legacy/discover/application/components/doc_viewer/__snapshots__/doc_viewer.test.tsx.snap
src/plugins/explore/public/components/container/bottom_container/bottom_container.test.tsx
src/plugins/explore/public/components/data_table/explore_data_table.test.tsx
src/plugins/explore/public/components/fields_selector/discover_field.test.tsx
src/plugins/explore/public/components/fields_selector/discover_field_details.test.tsx
src/plugins/explore/public/components/fields_selector/discover_sidebar.test.tsx
src/plugins/explore/public/components/top_nav/top_nav_links/top_nav_share/helpers.test.ts
src/plugins/explore/public/helpers/view_component_utils/filter_columns.test.ts

Fix UT mock import route due to recent file location change
- skip

[Explore] Fix UT mock

---

src/plugins/explore/public/application/legacy/discover/application/components/doc_viewer/__snapshots__/doc_viewer.test.tsx.snap
src/plugins/explore/public/application/legacy/discover/application/components/doc_viewer/doc_viewer.test.tsx
src/plugins/explore/public/components/visualizations/bar/bar_vis_options.test.tsx

[Explore] Fix type and ut

---

src/plugins/explore/public/components/visualizations/bar/bar_vis_options.test.tsx

Some tests were unintentionally updated. Although the tests currently pass, they do not comply with new bar_styles_options. This PR fixes them.
- skip

[Explore] fix bar tests

---

changelogs/fragments/10282.yml
cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/explore/04/queries_ui.spec.js
cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/04/queries_ui.spec.js

Modify the documentation link tests to test for a particular pattern for URL and checking if the URL works instead of validating with a specific version.
- fix: Make documentation link tests more robust

Fix Doc Version Tests

---

package.json

Bump to 3.2.0
chore: bump version to 3.2.0

Increment version to 3.2.0

---

changelogs/fragments/10274.yml
cypress/utils/apps/explore/autocomplete.js
cypress/utils/apps/query_enhancements/autocomplete.js
src/plugins/data/public/antlr/opensearch_ppl/code_completion.ts
src/plugins/data/public/antlr/opensearch_ppl/code_completion_simplified.test.ts
src/plugins/data/public/antlr/opensearch_ppl/constants.ts
src/plugins/data/public/antlr/shared/constants.ts
src/plugins/opensearch_dashboards_react/public/code_editor/code_editor.test.tsx
src/plugins/opensearch_dashboards_react/public/code_editor/code_editor.tsx

- Segregate Keywords into Commands, Operators , Functions in Suggestions
- Show documentation panel by default in suggestion wizard
https://github.com/user-attachments/assets/68b667bf-c9b9-4f80-ad01-aae36933df4d
- feat: Segregate Keywords into subCategory and Show docs panel by default

[Explore] Segregate Keywords into Commands, Operators , Functions in Suggestions

---

src/plugins/explore/public/components/top_nav/top_nav.tsx

[explore] - new search to search

---

changelogs/fragments/10302.yml
cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/explore/03/field_display_filtering.spec.js
cypress/utils/apps/explore/autocomplete.js

- Add Tests for Filter In/ Filter Out Actions in Explore
- test: Add Tests for Filter In/ Filter Out Actions in Explore

Add Tests for Filter In/ Filter Out Actions in Explore

---

changelogs/fragments/10307.yml
cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/explore/02/saved_queries.spec.js

Unskip saved queries test for explore
- test: Unskip saved queries test for explore

[TEST] Unskip saved queries test for explore

---

src/plugins/explore/public/components/visualizations/visualization_container.test.tsx
src/plugins/explore/public/components/visualizations/visualization_container.tsx
src/plugins/explore/public/components/visualizations/visualization_empty_state.test.tsx
src/plugins/explore/public/components/visualizations/visualization_empty_state.tsx

[Explore] Add empty state component when no rule matched

---

changelogs/fragments/10313.yml
changelogs/fragments/10321.yml
src/plugins/explore/public/application/utils/hooks/use_initial_query_execution.test.tsx
src/plugins/explore/public/application/utils/hooks/use_initial_query_execution.ts
src/plugins/explore/public/application/utils/hooks/use_timefilter_subscription.test.tsx
src/plugins/explore/public/application/utils/hooks/use_timefilter_subscription.ts
src/plugins/explore/public/application/utils/state_management/actions/export_actions.test.ts
src/plugins/explore/public/application/utils/state_management/selectors/query_editor/query_editor.test.ts
src/plugins/explore/public/application/utils/state_management/slices/index.ts
src/plugins/explore/public/application/utils/state_management/slices/meta/index.ts
src/plugins/explore/public/application/utils/state_management/slices/meta/meta_slice.test.ts
src/plugins/explore/public/application/utils/state_management/slices/meta/meta_slice.ts
src/plugins/explore/public/application/utils/state_management/store.test.ts
src/plugins/explore/public/application/utils/state_management/store.ts
src/plugins/explore/public/application/utils/state_management/utils/redux_persistence.test.ts
src/plugins/explore/public/application/utils/state_management/utils/redux_persistence.ts
src/plugins/explore/public/application/utils/state_management/utils/state_comparison.test.ts
src/plugins/explore/public/application/utils/state_management/utils/state_comparison.ts

https://github.com/opensearch-project/OpenSearch-Dashboards/pull/10313
-> Resolved merge conflicts
- feat: [Explore] Implement bidirectional URL-Redux synchronization

[Explore] Implement bidirectional URL-Redux synchronization (fixed conflicts)

---

changelogs/fragments/10323.yml
cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/explore/02/saved_queries.spec.js
src/plugins/explore/public/components/query_panel/query_panel_widgets/save_query/save_query.test.tsx
src/plugins/explore/public/components/query_panel/query_panel_widgets/save_query/save_query.tsx

correctly update time filter when loading save query
- fix: correctly update time filter when loading save query

[Explore] fix: correctly update time filter when loading save query

---

cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/explore/06/build_vis.spec.js
cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/explore/06/rule_matching_vis.spec.js
cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/explore/06/vis_type_switch.spec.js
src/plugins/explore/public/components/visualizations/chart_type_selector.tsx
src/plugins/explore/public/components/visualizations/visualization_empty_state.tsx

[Explore] Add cypress test for chart type and field selectors

---

changelogs/fragments/10328.yml
src/plugins/explore/public/application/utils/state_management/utils/state_comparison.test.ts
yarn.lock

1. fixed linting error of new discover state of tab slice
2. update caniuse version
- test: fixed linting error of new discover state of tab slice
- test: update caniuse version

[Explore] fixed linting error of new discover state of tab slice

---

changelogs/fragments/10365.yml
src/plugins/explore/public/components/visualizations/visualization_empty_state.test.tsx
src/plugins/explore/public/components/visualizations/visualization_empty_state.tsx

- fix: discover visualization empty state should use correct PPL

[Explore] update discover visualization empty state

---

changelogs/fragments/10387.yml
cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/explore/05/autocomplete_ui.spec.js
cypress/utils/apps/explore/autocomplete.js

Fix Autocomplete Tests to accomodate for AI mode.
- test: Fix Autocomplete Tests to accomodate for AI mode

Fix Autocomplete Tests

---

src/plugins/data/public/antlr/prompt/code_completion.ts
src/plugins/explore/public/components/query_panel/query_panel_editor/use_query_panel_editor/use_query_panel_editor.ts

Update the Insertion Text for Fields in NL Autocomplete, such that selecting a field should auto append a equals sign and trigger the value suggestion.
https://github.com/user-attachments/assets/abec3761-fe20-40d0-b7e3-d3b3ff8b961f
- fix: Update the Insertion Text for Fields in NL Autocomplete

Update the Insertion Text for Fields in NL Autocomplete

---

changelogs/fragments/10400.yml
src/plugins/visualizations/public/wizard/new_vis_actions.test.tsx
src/plugins/visualizations/public/wizard/new_vis_actions.tsx

- fix: it should only show index selector when needed

fix to only show index selector when needed

---

changelogs/fragments/10419.yml
src/plugins/explore/public/application/utils/state_management/actions/detect_optimal_tab/detect_optimal_tab.test.ts
src/plugins/explore/public/components/visualizations/chart_type_selector.tsx
src/plugins/explore/public/components/visualizations/rule_repository.test.ts
src/plugins/explore/public/components/visualizations/rule_repository.ts
src/plugins/explore/public/components/visualizations/style_panel/axes/axes_selector.test.tsx
src/plugins/explore/public/components/visualizations/style_panel/axes/axes_selector.tsx
src/plugins/explore/public/components/visualizations/types.ts
src/plugins/explore/public/components/visualizations/visualization_builder.ts
src/plugins/explore/public/components/visualizations/visualization_builder_utils.test.ts
src/plugins/explore/public/components/visualizations/visualization_builder_utils.ts
src/plugins/explore/public/components/visualizations/visualization_registry.test.ts
src/plugins/explore/public/components/visualizations/visualization_registry.ts
src/plugins/explore/public/components/visualizations/visualization_render.tsx
src/plugins/explore/public/embeddable/explore_embeddable.test.tsx
src/plugins/explore/public/embeddable/explore_embeddable.tsx
src/plugins/explore/public/services/visualization_registry_service.test.ts

Refactor visualization registry to remove the usage of `matchIndex`
- refactor: update visualization registry to remove the usage of `matchIndex`

[Explore] Refactor visualization registry

---

cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/explore/05/autocomplete_ui.spec.js
cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/05/autocomplete_ui.spec.js
cypress/utils/apps/explore/autocomplete.js
cypress/utils/apps/query_enhancements/autocomplete.js
src/plugins/data/common/index_patterns/fields/index_pattern_field.ts
src/plugins/data/common/index_patterns/types.ts
src/plugins/data/common/search/search_source/types.ts
src/plugins/data/public/antlr/opensearch_ppl/code_completion.ts
src/plugins/data/public/antlr/opensearch_sql/code_completion.ts
src/plugins/data/public/antlr/prompt/code_completion.test.ts
src/plugins/data/public/antlr/prompt/code_completion.ts
src/plugins/data/public/antlr/shared/utils.test.ts
src/plugins/data/public/antlr/shared/utils.ts
src/plugins/explore/public/application/utils/state_management/actions/query_actions.test.ts
src/plugins/explore/public/application/utils/state_management/actions/query_actions.ts
src/plugins/explore/public/components/fields_selector/lib/field_calculator.ts
src/plugins/explore/public/components/fields_selector/lib/get_details.ts
src/plugins/query_enhancements/public/search/ppl_search_interceptor.ts

Currently for larger datasets the process of fetching column Values is quite slow , making the autocomplete experience quite laggy. This PR introduces the following in a bid to reduce the wait time. 
- We introduce 2 new fields to IndexPattern **autoCompleteValues** and **topAggValues**
Whenever a value suggestion is triggered the following flow is executed
- If we already have results cached in autoCompleteValues we show those values
- If we don't have results cached, we try to showcase the  **Top Five Values** computed by sidebar to user and fire an async query to fetch column values from the API and update the cache in background
- In case we don't have **Top Five Values**, we synchronously fire the query to fetch column values and update the cache
Comparison:
Before: …

Optimize Value Suggestions in Autocomplete

---

changelogs/fragments/10453.yml
cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/02/language_specific_display.spec.js
src/plugins/data/public/ui/query_editor/query_editor.tsx

This adds a test for the fix made as part of this https://github.com/opensearch-project/OpenSearch-Dashboards/pull/10446. 
- test:  Add Cypress Test for Enter key behaviour in Query Editor

[Query Enhancements] Add Cypress Test for Enter key behaviour

---

changelogs/fragments/10449.yml
cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/explore/06/add_vis_to_dashboard.spec.js
cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/explore/06/rule_matching_vis.spec.js
cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/explore/06/rule_matching_vis_metric.spec.js
cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/explore/06/vis_type_switch.spec.js
cypress/utils/commands.explore.js
src/plugins/explore/public/components/query_panel/query_panel_widgets/language_reference/language_reference.tsx
src/plugins/explore/public/components/visualizations/metric/metric_vis_config.test.tsx
src/plugins/explore/public/components/visualizations/metric/metric_vis_config.ts
src/plugins/explore/public/components/visualizations/metric/metric_vis_options.test.tsx
src/plugins/explore/public/components/visualizations/metric/metric_vis_options.tsx
src/plugins/explore/public/components/visualizations/metric/to_expression.test.ts
src/plugins/explore/public/components/visualizations/metric/to_expression.ts
src/plugins/explore/public/components/visualizations/rule_repository.ts
src/plugins/explore/public/components/visualizations/style_panel/axes/axes_selector.tsx
src/plugins/explore/public/components/visualizations/style_panel/value/value_calculation_selector.test.tsx
src/plugins/explore/public/components/visualizations/style_panel/value/value_calculation_selector.tsx
src/plugins/explore/public/components/visualizations/types.ts
src/plugins/explore/public/components/visualizations/utils/font_size_input_field.tsx
src/plugins/explore/public/components/visualizations/utils/utils.test.ts
src/plugins/explore/public/components/visualizations/utils/utils.ts
src/plugins/explore/public/components/visualizations/visualization_builder.ts

Update metric visualization to support sparkline
- feat: update metric viz to support sparkline

[Explore] Metric viz with sparkline

---

changelogs/fragments/10478.yml
src/plugins/data_importer/common/constants.ts
src/plugins/data_importer/public/plugin.ts

Moving Data Importer plugin to Data Administration under settings
- When workspaces are enabled
- When workspaces are disabled
- fix: Move the Data Importer plugin to Data Administration under settings

Moving Data Importer to Data Administration under settings

---

changelogs/fragments/10465.yml
src/plugins/explore/public/components/visualizations/bar/bar_chart_utils.test.ts
src/plugins/explore/public/components/visualizations/bar/bar_chart_utils.ts
src/plugins/explore/public/components/visualizations/bar/bar_vis_config.test.ts
src/plugins/explore/public/components/visualizations/bar/bar_vis_config.ts
src/plugins/explore/public/components/visualizations/bar/bar_vis_options.test.tsx
src/plugins/explore/public/components/visualizations/bar/bar_vis_options.tsx
src/plugins/explore/public/components/visualizations/bar/bucket_options.test.tsx
src/plugins/explore/public/components/visualizations/bar/bucket_options.tsx
src/plugins/explore/public/components/visualizations/bar/to_expression.test.ts
src/plugins/explore/public/components/visualizations/bar/to_expression.ts
src/plugins/explore/public/components/visualizations/heatmap/heatmap_chart_utils.test.ts
src/plugins/explore/public/components/visualizations/heatmap/heatmap_chart_utils.ts
src/plugins/explore/public/components/visualizations/heatmap/heatmap_exclusive_vis_options.test.tsx
src/plugins/explore/public/components/visualizations/heatmap/heatmap_exclusive_vis_options.tsx
src/plugins/explore/public/components/visualizations/heatmap/heatmap_vis_config.test.ts
src/plugins/explore/public/components/visualizations/heatmap/heatmap_vis_config.ts
src/plugins/explore/public/components/visualizations/rule_repository.ts
src/plugins/explore/public/components/visualizations/types.ts
src/plugins/explore/public/components/visualizations/utils/collections.ts

This pr adds histogram
1. numerical  histogram
https://github.com/user-attachments/assets/55a5583b-3297-4330-88f9-0506265c8175
2. time-series histogram
https://github.com/user-attachments/assets/a529526a-175f-447a-8602-3c2720116bb9
4. single value bar
https://github.com/user-attachments/assets/e9a31f86-698b-4726-9aa3-9e1d2a34b35c
5. categorical histogram
- feat: add histogram

[Explore] add histogram

---

changelogs/fragments/10503.yml
cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/explore/05/recent_queries.spec.js
cypress/utils/apps/explore/autocomplete.js
cypress/utils/apps/explore/shared_links.js
packages/osd-monaco/src/monaco.ts
packages/osd-monaco/src/ppl/formatter.test.ts
packages/osd-monaco/src/ppl/formatter.ts
packages/osd-monaco/src/ppl/language.ts
src/plugins/explore/public/components/query_panel/query_panel_editor/use_query_panel_editor/editor_options/query_editor_options.ts

This PR adds PPL Formatter. User can use `Shift+ option+ F` to trigger formatting of the document.
https://github.com/user-attachments/assets/99e13455-e236-4429-b846-56d0191fd8cc
- feat: Add PPL Formatter in Query panel

Add PPL Formatter

---

changelogs/fragments/10497.yml
src/plugins/explore/public/components/visualizations/gauge/gauge_chart_utils.ts
src/plugins/explore/public/components/visualizations/gauge/gauge_vis_config.test.tsx
src/plugins/explore/public/components/visualizations/gauge/gauge_vis_config.ts
src/plugins/explore/public/components/visualizations/gauge/gauge_vis_options.test.tsx
src/plugins/explore/public/components/visualizations/gauge/gauge_vis_options.tsx
src/plugins/explore/public/components/visualizations/gauge/to_expression.ts
src/plugins/explore/public/components/visualizations/metric/metric_vis_config.ts
src/plugins/explore/public/components/visualizations/metric/metric_vis_options.test.tsx
src/plugins/explore/public/components/visualizations/metric/metric_vis_options.tsx
src/plugins/explore/public/components/visualizations/metric/to_expression.test.ts
src/plugins/explore/public/components/visualizations/metric/to_expression.ts
src/plugins/explore/public/components/visualizations/style_panel/unit/collection.test.ts
src/plugins/explore/public/components/visualizations/style_panel/unit/collection.ts
src/plugins/explore/public/components/visualizations/style_panel/unit/style.scss
src/plugins/explore/public/components/visualizations/style_panel/unit/unit_panel.test.tsx
src/plugins/explore/public/components/visualizations/style_panel/unit/unit_panel.tsx
src/plugins/explore/public/components/visualizations/types.ts

this pr adds units panel for gauge and metric.
https://github.com/user-attachments/assets/ae170b83-a510-4026-9a4c-e4586720f73b
https://github.com/user-attachments/assets/262e5589-d4e8-4307-ac2f-00eda27b03ae
- fix: add units panel for gauge and metric

[Explore]add units panel for gauge and metric

---

src/plugins/data/common/datasets/types.ts
src/plugins/data/public/ui/dataset_selector/dataset_explorer.tsx
src/plugins/data/public/ui/dataset_selector/dataset_table.test.tsx
src/plugins/data/public/ui/dataset_selector/dataset_table.tsx

In #8255, we added multi-select table for selecting multiple children as the next data structure. But it's not flexible enough, and there's no support for customizing that table component.
This PR allows each data structure to provide a custom UI component for how to select its `children` as the next data structure.
The interface is 
```tsx
export interface DataStructure {
...
/** Whether data structure supports multi-selecting children. The selected
* children will be combined using {@link DatasetTypeConfig['combineDataStructures']} */
multiSelect?: boolean;
/** Custom component to select children and create next data structure or
* dataset. multiSelect will be ignored if using custom component */
DataStructureCreator?: React.ComponentType<DataStructureCreatorProps>;
```
```tsx
export …
```

[Query enhancements] support custom component to create data structure

---

src/plugins/explore/public/application/legacy/discover/application/components/no_results/no_results.scss
src/plugins/explore/public/application/legacy/discover/application/components/no_results/no_results.tsx

[Explore] bring up sample queries

---

package.json

Bump version to 2.19.4
- chore: bump version to 2.19.4

Bump version to 2.19.4

---

baselines/lighthouse_baseline.json
packages/osd-optimizer/limits.yml

Update limits for lighthouse and bundle.
- skip

Update limits for lighthouse and bundle

---

changelogs/fragments/10622.yml
src/plugins/explore/server/index.ts
src/plugins/home/public/application/components/explore_experience.tsx
src/plugins/home/public/application/components/home_app.js

* add i18n
* enhanced UI
* change session storage to local storage
- feat: Enhance explore modal UI

Enhance explore modal UI with local storage logic

---

changelogs/fragments/10624.yml
src/plugins/chat/README.md
src/plugins/chat/public/index.ts
src/plugins/chat/public/plugin.ts
src/plugins/chat/server/index.ts
src/plugins/context_provider/README.md
src/plugins/context_provider/public/index.ts
src/plugins/context_provider/public/plugin.ts

Mark context provider and chat as experimental
NA
- feat: chat(feat): mark context provider and chat as experimental

chat(feat): mark context provider and chat as experimental
