opensearch-project/OpenSearch-Dashboards

changelogs/fragments/7585.yml, src/plugins/query_enhancements/public/plugin.tsx
Disabling showing the surrounding doc links for PPL that require specific DSL queries.
n/a
- fix: do not show surround doc links for PPL
=> [discover-next] disable show doc links for PPL

src/plugins/home/public/application/components/__snapshots__/sample_data_view_data_button.test.js.snap, src/plugins/home/public/application/components/sample_data_view_data_button.js, src/plugins/vis_type_vega/public/components/vega_actions_menu.tsx, src/plugins/vis_type_vega/public/components/vega_help_menu.tsx
Found 2 places that we need to use small context Menu. Along with #7057 , Now we have applied small context menu across the whole OSD codebase
- skip
=> [Look&Feel] Use small context menu across the board

changelogs/fragments/7613.yml, src/plugins/home/public/plugin.ts
We lost sample data in the design of new left navigation and this PR is trying to bring it back because import sample data is a very useful feature in OSD to quickly setup some dashboards and visualizations.
- Go to advanced settings and turn on new home page feature flag.
- Find the entry in all of the use cases.
- fix: [navigation] add sample data to left navigation
=> [navigation]fix: add sample data to left navigation

changelogs/fragments/7624.yml, src/plugins/content_management/public/components/card_container/card_container.tsx, src/plugins/content_management/public/components/card_container/card_embeddable.tsx, src/plugins/content_management/public/components/card_container/card_list.tsx, src/plugins/content_management/public/components/card_container/types.ts, src/plugins/content_management/public/components/section_input.ts, src/plugins/content_management/public/services/content_management/types.ts
The column size was hard coded to 4 previously, now changed so that it can be configured, this addressed the issue when there are more than 4 cards, cards will be displayed in multiple rows
Before
After
- fix: [contentManagement] display cards by specifying a column size or display all cards in one row
=> fix: get start section cards not aligned

src/plugins/management/common/contants.ts, src/plugins/management/public/management_sections_service.test.ts, src/plugins/management/public/management_sections_service.ts, src/plugins/management/server/capabilities_provider.ts
The `Dashboards management` section id(`opensearch-dashboards`) of `Management` category doesn't match the id(`opensearchDashboards`) defined in `capabilities`, the consequence is the following code will never work for apps of `Dashboards management`. Even set the capability of the app to false, the nav link still displayed on the UI(it does redirect to home page when accessing the link).
```typescript
this.getAllSections().forEach((section) => {
if (capabilities.management.hasOwnProperty(section.id)) {
const sectionCapabilities = capabilities.management[section.id];
section.apps.forEach((app) => {
if (sectionCapabilities.hasOwnProperty(app.id) && sectionCapabilities[app.id] !== true) {
app.disable();
}
});
}
});
```
The original PR introduced the `id` change is …
=> fix bug: management section id not match the key defined in capabilities

changelogs/fragments/7575.yml, src/plugins/content_management/README.md
Add documentation for dynamic page creation
- doc: Add documentation for dynamic page creation
=> [Doc] Documentation of content management plugin

changelogs/fragments/7633.yml, src/plugins/content_management/public/components/section_input.test.ts, src/plugins/content_management/public/components/section_input.ts, src/plugins/content_management/public/services/content_management/content_management_service.ts, src/plugins/content_management/public/services/content_management/page.test.ts, src/plugins/content_management/public/services/content_management/page.ts
Instead of throw error when register section or content with the same id, now changed to override the existing ones.
- feat: register section and content with the same id will not throw error but overrides the exist one
=> fix: do not throw exception if content provider id exists

src/plugins/data_source_management/public/components/data_source_home_panel/__snapshots__/data_source_home_panel.test.tsx.snap, src/plugins/data_source_management/public/components/data_source_home_panel/data_source_home_panel.tsx, src/plugins/data_source_management/public/components/direct_query_data_sources_components/acceleration_management/__snapshots__/acceleration_details_flyout.test.tsx.snap, src/plugins/data_source_management/public/components/direct_query_data_sources_components/acceleration_management/acceleration_details_flyout.tsx, src/plugins/data_source_management/public/components/direct_query_data_sources_components/connection_detail/direct_query_connection_detail.tsx, src/plugins/workspace/public/components/workspace_detail/__snapshots__/workspace_detail.test.tsx.snap, src/plugins/workspace/public/components/workspace_detail/workspace_detail.tsx
=> [Look&Feel] Apply small tabs pattern guidance to remaining OSD experiences

changelogs/fragments/7600.yml, src/core/server/http/http_tools.test.ts, src/core/server/http/http_tools.ts, src/core/server/http/index.ts
This PR adds a new util function to `src/core/server/http/http_tools.ts`, and the util function should be used by security plugin or other customized authentication plugin to generate the correct redirect url after login.
partial closes: https://github.com/opensearch-project/security-dashboards-plugin/issues/2069
Only serve side code changes involved.
The consumer logic is inside https://github.com/opensearch-project/security-dashboards-plugin/pull/2072
- feat: Add a util function to generate the relative redirectUrl.
=> Add a util function to generate the relative redirectUrl 

changelogs/fragments/7618.yml, src/core/public/chrome/ui/header/__snapshots__/collapsible_nav_group_enabled.test.tsx.snap, src/core/public/chrome/ui/header/collapsible_nav_group_enabled.test.tsx, src/core/utils/default_nav_groups.ts, src/plugins/dashboard/public/plugin.tsx, src/plugins/data_source_management/public/plugin.ts, src/plugins/discover/public/plugin.ts, src/plugins/home/public/plugin.ts, src/plugins/index_pattern_management/public/plugin.ts, src/plugins/saved_objects_management/public/plugin.ts, src/plugins/visualize/public/plugin.ts, src/plugins/workspace/common/constants.ts, src/plugins/workspace/public/components/home_get_start_card/use_case_footer.test.tsx, src/plugins/workspace/public/components/workspace_creator/workspace_creator.test.tsx, src/plugins/workspace/public/components/workspace_detail/workspace_detail.test.tsx, src/plugins/workspace/public/components/workspace_detail/workspace_updater.test.tsx, src/plugins/workspace/public/components/workspace_form/workspace_form.test.tsx, src/plugins/workspace/public/components/workspace_form/workspace_use_case.test.tsx, src/plugins/workspace/public/components/workspace_list/index.test.tsx, src/plugins/workspace/public/components/workspace_menu/workspace_menu.test.tsx, src/plugins/workspace/public/plugin.ts, src/plugins/workspace/public/services/use_case_service.ts, src/plugins/workspace/public/utils.test.ts
For 2.17, we are using
- `essentials` to replace `analytics`.
- `Analytics (All)` to replace `all`.
- feat: use essentials as the nav group name
=> [navigation]feat: replace analytics nav group with essentials

changelogs/fragments/7619.yml, src/core/public/chrome/index.ts, src/core/public/chrome/nav_group/nav_group_service.ts, src/core/public/chrome/ui/header/__snapshots__/collapsible_nav_group_enabled.test.tsx.snap, src/core/public/chrome/ui/header/collapsible_nav_group_enabled.scss, src/core/public/chrome/ui/header/collapsible_nav_group_enabled.test.tsx, src/core/public/chrome/ui/header/collapsible_nav_group_enabled.tsx, src/core/public/chrome/utils.test.ts, src/core/public/chrome/utils.ts, src/core/public/index.ts, src/plugins/management/public/plugin.ts, src/plugins/workspace/public/plugin.ts
This PR mainly address 3 issues related to new left navigation.
- Make parent item unclickable in left nav.
- Hide parent item in landing page.
- Filter out hidden nav group when detecting if current application belongs to only one nav group.
https://github.com/user-attachments/assets/90e50ab9-7795-4336-8324-79413a262526
https://github.com/user-attachments/assets/5f5420d0-dbf3-4c62-9d88-adf7b22be1ed
https://github.com/user-attachments/assets/8ba717f8-53c3-4bc6-832a-e91d15852fe3
- feat: make parent item unclickable and fix duplicate items in landing page.
=> [navigation]feat: make parent item unclickable and fix duplicate items in landing page.

changelogs/fragments/7503.yml, src/plugins/embeddable/common/types.ts, src/plugins/embeddable/public/lib/panel/embeddable_panel.test.tsx, src/plugins/embeddable/public/lib/panel/embeddable_panel.tsx, src/plugins/embeddable/public/lib/panel/panel_header/panel_header.tsx
Similar to the existing options `hidePanelTitles` which hide embeddable panel titles, this PR introduced a new option `hidePanelActions` to hide the embeddable action button, this is useful for embeddable panels that don't have action, right now, action button always shows even when there was no action:
With this PR, it's possible to hide the action button by specifying `{hidePanelActions: true}` in embeddable input
- feat: provide new embeddable option to hide embeddable panel action button
=> feat: provide new embeddable option to hide embeddable panel action button

changelogs/fragments/7671.yml, src/plugins/workspace/common/__tests__/utils.test.ts, src/plugins/workspace/common/utils.ts, src/plugins/workspace/public/components/workspace_form/types.ts, src/plugins/workspace/public/components/workspace_form/utils.test.ts, src/plugins/workspace/public/components/workspace_form/utils.ts, src/plugins/workspace/public/components/workspace_form/workspace_form_error_callout.test.tsx, src/plugins/workspace/public/components/workspace_form/workspace_form_error_callout.tsx, src/plugins/workspace/public/components/workspace_menu/workspace_menu.tsx, src/plugins/workspace/server/routes/index.ts
This PR for fixing page crashed after invalid color be assigned to avatar component in the Workspace Menu component.
#7672
1.Go to 'Create workspace' page
2.Fill workspace name and select use case, input a invalid color.
3.Click on 'Create workspace' button
4.Workspace should not be created with invalid color, it should show form error
- fix: [Workspace]Fix page crash caused by invalid workspace color
=> [Workspace]Fix page crash caused by invalid workspace color

changelogs/fragments/7651.yml, src/plugins/content_management/public/components/card_container/types.ts, src/plugins/content_management/public/components/section_input.test.ts, src/plugins/content_management/public/components/section_input.ts, src/plugins/content_management/public/components/types.ts, src/plugins/content_management/public/plugin.ts, src/plugins/content_management/public/services/content_management/content_management_service.test.ts, src/plugins/content_management/public/services/content_management/content_management_service.ts, src/plugins/content_management/public/services/content_management/page.test.ts, src/plugins/content_management/public/services/content_management/page.ts, src/plugins/content_management/public/services/content_management/types.ts, src/plugins/content_management/public/types.ts
This PR makes it possible to update the section input after the page is rendered, for example, when rendering a dashboard on the page, we need to apply the date range, filter and query on the fly.
- feat: [contentManagement] allow to update section input after page rendered
=> feat: [contentManagement] allow to update section input after page rendered

changelogs/fragments/7691.yml, src/plugins/opensearch_dashboards_react/public/table_list_view/table_list_view.tsx
Allow customizing `restrictWidth` and `paddingSize` of `TableListView`
- feat: Allow customizing `restrictWidth` and `paddingSize` of `TableListView`
=> Allow customizing `restrictWidth` and `paddingSize` of `TableListView`

changelogs/fragments/7702.yml, src/plugins/saved_objects_management/public/management_section/recent_work.test.tsx, src/plugins/saved_objects_management/public/management_section/recent_work.tsx, src/plugins/saved_objects_management/public/plugin.ts
In this pr, I refractor the assets list in the homepage.
1. empty state
2. Look
3. filtering
4. Title tooltip
- feat: refractor the homepage assets list section
=> [WorkSpace] Refractor homepage assets list section

changelogs/fragments/7697.yml, src/plugins/management/opensearch_dashboards.json, src/plugins/management/public/components/feature_cards/__snapshots__/feature_cards.test.tsx.snap, src/plugins/management/public/components/feature_cards/feature_cards.test.tsx, src/plugins/management/public/components/feature_cards/feature_cards.tsx, src/plugins/management/public/landing_page_application.test.tsx, src/plugins/management/public/plugin.ts, src/plugins/workspace/opensearch_dashboards.json, src/plugins/workspace/public/components/workspace_creator/workspace_creator.test.tsx, src/plugins/workspace/public/components/workspace_creator/workspace_creator.tsx, src/plugins/workspace/public/components/workspace_creator_app.tsx, src/plugins/workspace/public/components/workspace_detail/__snapshots__/workspace_detail.test.tsx.snap, src/plugins/workspace/public/components/workspace_detail/workspace_detail.test.tsx, src/plugins/workspace/public/components/workspace_detail/workspace_detail.tsx, src/plugins/workspace/public/components/workspace_detail_app.tsx, src/plugins/workspace/public/components/workspace_list/__snapshots__/index.test.tsx.snap, src/plugins/workspace/public/components/workspace_list/index.test.tsx, src/plugins/workspace/public/components/workspace_list/index.tsx, src/plugins/workspace/public/plugin.ts, src/plugins/workspace/public/types.ts
Integrate new page header for workspace pages, including
1. workspace create page
2. workspace list page
3. workspace detail page header
4. settings and setup landing page
5. data administration page
This is first phase of integration, the integration of remaining pages will be proposed in later PRs.
- feat: Integrate new page header for workspace pages
=> [Workspace][Page header] Integrate new page header for workspace pages

changelogs/fragments/7699.yml, docs/_sidebar.md, src/plugins/workspace/public/components/workspace_detail/workspace_detail.test.tsx
Add a unit test to indicate React is anti-xss
- feat: add a unit test case to indicate React is anti-xss
=> [workspace]feat: add a unit test case to indicate React is anti-xss

changelogs/fragments/7686.yml, docs/_sidebar.md, packages/osd-i18n/src/core/i18n.test.ts, packages/osd-i18n/src/core/i18n.ts, src/core/public/application/scoped_history.test.ts, src/core/public/application/scoped_history.ts, src/core/public/core_system.ts, src/core/public/locale_helper.test.ts, src/core/public/locale_helper.ts, src/core/public/osd_bootstrap.test.mocks.ts, src/core/public/osd_bootstrap.test.ts, src/core/public/osd_bootstrap.ts, src/dev/jest/config.js, src/legacy/server/i18n/index.ts, src/legacy/ui/ui_render/ui_render_mixin.js, src/legacy/ui/ui_render/ui_render_mixin.test.js
The main issue was the inability to dynamically change the locale in OpenSearch Dashboards. Currently we need to update config file and i18nrc.json.
This PR allows  users to switch to a different locale (e.g., from English to Chinese) by appending or modifying the 'i18n-locale' parameter in the URL.
* getAndUpdateLocaleInUrl: If a non-default locale is found, this function reconstructs the URL with the locale parameter in the correct position.
* updated the ScopedHistory class, allowing it to detect locale changes and trigger reloads as necessary.
* modify the i18nMixin, which sets up the i18n system during server startup, to register all available translation files during server startup, not just the current locale.
* update the uiRenderMixin to accept requests for any registered locale …
=> Change the locale dynamically by adding &i18n-locale to URL

changelogs/fragments/7721.yml, src/plugins/navigation/public/top_nav_menu/_index.scss, src/plugins/navigation/public/top_nav_menu/top_nav_menu.tsx
Allow `screenTitle` to be present when SearchBar is not in Application header
- feat: Allow `screenTitle` to be present when SearchBar is not in Application header
=> Allow `screenTitle` to be present when SearchBar is not in Application header

changelogs/fragments/7723.yml, src/core/public/chrome/ui/header/header_controls_container.scss, src/plugins/navigation/public/top_nav_menu/top_nav_control_data.tsx, src/plugins/navigation/public/top_nav_menu/top_nav_control_item.tsx
Simplify `TopNavControlDescriptionData` to to be followed by links
- feat: Simplify `TopNavControlDescriptionData` to to be followed by links
=> Simplify `TopNavControlDescriptionData` to to be followed by links

src/core/public/chrome/ui/header/__snapshots__/header.test.tsx.snap, src/core/public/chrome/ui/header/header.tsx, src/core/public/chrome/ui/header/header_breadcrumbs.tsx, src/core/public/chrome/ui/header/recent_items.tsx
Update Recent popover to always render breadcrumbs with full length, no matter of header variants. While for page header, also keep the existing breadcrumbs on the top, with last leaf cut off
https://github.com/user-attachments/assets/0c4c32e6-5668-4566-8225-89a698de4ce5
- skip
=> Update Recent popover to always render breadcrumbs with full length

src/plugins/data/common/datasets/types.ts, src/plugins/data/public/index.ts, src/plugins/data/public/query/index.tsx, src/plugins/data/public/query/mocks.ts, src/plugins/data/public/query/query_service.ts, src/plugins/data/public/query/query_string/dataset_manager/dataset_manager.mock.ts, src/plugins/data/public/query/query_string/dataset_manager/dataset_manager.test.ts, src/plugins/data/public/query/query_string/dataset_manager/dataset_manager.ts, src/plugins/data/public/query/query_string/dataset_manager/index.ts, src/plugins/data/public/query/query_string/query_string_manager.ts, src/plugins/data/public/query/state_sync/create_global_query_observable.ts, src/plugins/data/public/query/state_sync/types.ts
Updating the discover interfaces and move dataset manager into the proper location within the querystring manager.
=> [discover] update interfaces and move dataset manager

changelogs/fragments/7655.yml, src/core/public/chrome/chrome_service.tsx, src/core/public/chrome/ui/header/__snapshots__/collapsible_nav_group_enabled.test.tsx.snap, src/core/public/chrome/ui/header/__snapshots__/header.test.tsx.snap, src/core/public/chrome/ui/header/collapsible_nav_group_enabled.scss, src/core/public/chrome/ui/header/collapsible_nav_group_enabled.test.tsx, src/core/public/chrome/ui/header/collapsible_nav_group_enabled.tsx, src/core/public/chrome/ui/header/collapsible_nav_group_enabled_top.test.tsx, src/core/public/chrome/ui/header/collapsible_nav_group_enabled_top.tsx, src/core/public/chrome/ui/header/header.test.tsx, src/core/public/chrome/ui/header/header.tsx, src/core/utils/default_app_categories.ts, src/core/utils/default_nav_groups.ts, src/plugins/advanced_settings/public/plugin.ts, src/plugins/data_source_management/public/plugin.ts, src/plugins/home/public/plugin.ts, src/plugins/index_pattern_management/public/plugin.test.ts, src/plugins/index_pattern_management/public/plugin.ts, src/plugins/management/public/plugin.ts, src/plugins/saved_objects_management/public/plugin.ts, src/plugins/visualize/public/plugin.ts, src/plugins/workspace/public/plugin.test.ts, src/plugins/workspace/public/plugin.ts, src/plugins/workspace/public/services/use_case_service.ts, src/plugins/workspace/public/utils.ts
Manualy backport 6877beaadd517207722c261181c1751bfa5bfb40 from #7655 
- skip
=> [Backport 2.x] [navigation] Left navigation collective

yarn.lock
=> [CVE-2024-37890][1.3] Bump ws from `6.2.2` to `6.2.3` and from `7.5.3` to `7.5.10`

yarn.lock
=> [1.3][CVE-2024-28863] Bump tar from `6.1.11` to `6.2.1`

package.json, yarn.lock
=> [1.3][CVE-2024-28849] Bump follow-redirects from `1.15.2` to `1.15.6`

package.json, yarn.lock
=> [1.3][CVE-2024-29041] Bump express from 4.18.2 to 4.19.2

src/plugins/data/common/index.ts, src/plugins/data/common/storage/index.ts, src/plugins/data/common/storage/storage.ts, src/plugins/data/public/plugin.ts, src/plugins/data/public/query/lib/add_to_query_log.ts, src/plugins/data/public/query/lib/get_query_log.ts, src/plugins/data/public/query/persisted_log/persisted_log.ts, src/plugins/data/public/query/query_service.ts, src/plugins/data/public/query/query_string/query_history.ts, src/plugins/data/public/query/query_string/query_string_manager.test.ts, src/plugins/data/public/query/query_string/query_string_manager.ts, src/plugins/data/public/query/state_sync/connect_to_query_state.test.ts, src/plugins/data/public/query/state_sync/sync_state_with_url.test.ts, src/plugins/data/public/query/timefilter/time_history.ts, src/plugins/data/public/query/timefilter/timefilter_service.ts, src/plugins/data/public/types.ts, src/plugins/data/public/ui/query_string_input/no_data_popover.tsx, src/plugins/data/public/ui/query_string_input/query_bar_top_row.tsx, src/plugins/data/public/ui/query_string_input/query_string_input.test.tsx, src/plugins/data/public/ui/query_string_input/query_string_input.tsx, src/plugins/data/public/ui/search_bar/create_search_bar.tsx, src/plugins/data/public/ui/search_bar/search_bar.tsx, src/plugins/data/public/ui/settings/settings.ts, src/plugins/data/public/ui/ui_service.ts
* Created a more advanced storage class for data plugin 
* Refactor logics from previous storage usages
* Add Query History class for future recent query use
- feat: Add a unified storage class for data plugin
=> Add an unified storage class for data plugin

changelogs/fragments/7768.yml, src/plugins/workspace/public/components/workspace_detail/workspace_detail.tsx
This pr address the bug in the workspace_detail_page, which due to the change of parameter declaration in delete_workspace_modal
- fix: fix the parameter misalignment in the workspace_detail_page
=> [Workspace]fix the parameter misalignment error in the workspace_detail_page

src/plugins/content_management/public/components/card_container/card_list.tsx, src/plugins/content_management/public/components/card_container/types.ts, src/plugins/content_management/public/components/section_input.test.ts, src/plugins/content_management/public/components/section_input.ts, src/plugins/content_management/public/services/content_management/types.ts
```diff
{
id: SECTIONS.GET_STARTED,
order: 1000,
title: 'Define your path forward with OpenSearch',
kind: 'card',
+ columns: 3,
+ wrap: false,
}
```
https://github.com/user-attachments/assets/7668dc13-0097-4898-a1e4-2246d744cae6
```diff
{
id: SECTIONS.GET_STARTED,
order: 1000,
title: 'Define your path forward with OpenSearch',
kind: 'card',
+ columns: 3,
+ wrap: true,
}
```
```diff
contentManagement.registerContentProvider({
id: 'whats_new_cards',
getContent: () => ({
id: 'whats_new',
kind: 'custom',
order: 3,
+     width: 24,
+     height: 20,
render: () =>
React.createElement(HomeListCard, {
config: WHATS_NEW_CONFIG,
}),
}),
getTargetArea: () => HOME_CONTENT_AREAS.SERVICE_CARDS,
});
```
- feat: [contentManagement] allow to customize card section columns and dashboards panel size
=> feat: card section and dashboards section UX improvements

changelogs/fragments/7527.yml, src/plugins/vis_builder/public/application/components/data_tab/config_panel.tsx, src/plugins/vis_builder/public/application/components/data_tab/constants.ts, src/plugins/vis_builder/public/application/components/data_tab/dropbox.tsx, src/plugins/vis_builder/public/application/components/data_tab/index.tsx, src/plugins/vis_builder/public/application/components/data_tab/schema_to_dropbox.tsx, src/plugins/vis_builder/public/application/components/data_tab/use/use_dropbox.tsx
This PR aims to enhance the user experience in Vis Builder by highlighting the droppable areas when a user starts dragging a field and fixing the bug which removed this feature. 
https://github.com/user-attachments/assets/48a915a2-886a-44e2-8412-d93604c4b31b
- Navigate to Vis Builder Page 
- Start Dragging a Field from the left side field panel 
- You should see all the droppable areas highlighted
- fix: Not highlighting Droppable Areas while dragging a field
=> [Vis-Builder] Fix Droppable Areas not highlighting while dragging a Field

src/plugins/data/public/ui/filter_bar/filter_options.test.tsx, src/plugins/data/public/ui/filter_bar/filter_options.tsx
- remove the save query button
- create a new menu button called "saved queries" and make it conditionally render with newhome toggle
- remove popover header "Filters"
- add separator horizontal rule
- skip
=> [Page Header]Make saved queries a context menu item in filter options instead of a button

src/plugins/advanced_settings/public/header_user_theme_menu.tsx, src/plugins/newsfeed/public/components/newsfeed_header_nav_button.scss, src/plugins/newsfeed/public/components/newsfeed_header_nav_button.tsx, src/plugins/newsfeed/public/plugin.tsx
Adapt the newsfeed button to the updated header. This "plugin" is virtually disabled by removing the manifest file.
Also:
* renamed a private variable with theme's menu button for consistency
- feat: Adapt the newsfeed button to the updated header
=> Adapt the newsfeed button to the updated header

changelogs/fragments/7686.yml, packages/osd-i18n/src/core/i18n.test.ts, packages/osd-i18n/src/core/i18n.ts, src/core/public/application/scoped_history.test.ts, src/core/public/application/scoped_history.ts, src/core/public/locale_helper.test.ts, src/core/public/locale_helper.ts, src/core/public/osd_bootstrap.test.mocks.ts, src/core/public/osd_bootstrap.test.ts, src/core/public/osd_bootstrap.ts, src/dev/jest/config.js, src/legacy/server/i18n/index.ts, src/legacy/ui/ui_render/ui_render_mixin.js, src/legacy/ui/ui_render/ui_render_mixin.test.js
https://github.com/opensearch-project/OpenSearch-Dashboards/pull/7686
=> [2.x manual backport]Change the locale dynamically by adding &i18n-locale to URL (#7686)

src/core/server/ui_settings/settings/theme.ts, src/core/server/ui_settings/types.ts, src/core/server/ui_settings/ui_settings_client.test.ts, src/core/server/ui_settings/ui_settings_client.ts, src/core/server/ui_settings/ui_settings_config.ts, src/legacy/ui/ui_render/ui_render_mixin.js, src/plugins/opensearch_dashboards_react/public/table_list_view/table_list_view.tsx, test/functional/apps/visualize/_custom_branding.ts, test/plugin_functional/test_suites/dashboard_listing_plugin/dashboard_listing_plugin.ts, yarn.lock
This PR is originally from https://github.com/opensearch-project/OpenSearch-Dashboards/pull/6730. We simply update the tests.
There are a couple different fixes here, which can be viewed separately by looking at the separate commits. But the root cause of https://github.com/opensearch-project/OpenSearch-Dashboards/issues/6704 was primarily the fact that the implementation of `getOverridesOrDefault` assumed the wrong object shape for the `overrides` property, when it tried to access a `value` property instead of just the value itself. Note that the existing unit test also had this same error.
Because the `ui_render_mixin` is an old legacy `.js` file, there's not much help from typescript, so I also added some enforcement to make sure we're always sending boolean values to the template. …
=> [Rebase #6730 and fix tests] Fix/UI settings overrides

changelogs/fragments/7796.yml, src/core/public/chrome/ui/header/header.scss
Fix new header allowing their single-child's overflowing
- fix: Fix new header allowing their single-child's overflowing
=> Fix new header allowing their single-child's overflowing

changelogs/fragments/7801.yml, src/plugins/navigation/public/top_nav_menu/top_nav_control_data.tsx, src/plugins/navigation/public/top_nav_menu/top_nav_control_item.tsx
Add `flush` to `TopNavControlLinkData`
- feat: Add `flush` to `TopNavControlLinkData`
=> Add `flush` to `TopNavControlLinkData`

changelogs/fragments/7804.yml, src/plugins/query_enhancements/server/routes/query_assist/agents.test.ts, src/plugins/query_enhancements/server/routes/query_assist/agents.ts
Fix bug https://github.com/opensearch-project/OpenSearch-Dashboards/issues/7803
#7803
=> Fix query assistant fetching agent bug

changelogs/fragments/7795.yml, src/plugins/workspace/public/components/workspace_form/workspace_form.tsx, src/plugins/workspace/public/components/workspace_form/workspace_permission_setting_input.test.tsx, src/plugins/workspace/public/components/workspace_form/workspace_permission_setting_input.tsx, src/plugins/workspace/public/components/workspace_form/workspace_permission_setting_panel.test.tsx, src/plugins/workspace/public/components/workspace_form/workspace_permission_setting_panel.tsx
"Adjust the appearance of the workspace collaborator section according to the new design."
- feat: Adjust the appearance of collaborator panel
=> [Workspace] Adjust the appearance of collaborator panel

changelogs/fragments/7802.yml, src/core/public/chrome/ui/header/__snapshots__/collapsible_nav_group_enabled.test.tsx.snap, src/core/public/chrome/ui/header/collapsible_nav_group_enabled.scss, src/core/public/chrome/ui/header/collapsible_nav_group_enabled.tsx, src/plugins/home/public/application/components/home_icon.test.tsx, src/plugins/home/public/application/components/home_icon.tsx, src/plugins/home/public/plugin.ts, src/plugins/saved_objects_management/public/plugin.ts, src/plugins/visualize/public/plugin.ts, src/plugins/workspace/public/components/workspace_menu/workspace_menu.tsx, src/plugins/workspace/public/plugin.test.ts, src/plugins/workspace/public/plugin.ts, src/plugins/workspace/public/services/use_case_service.test.ts, src/plugins/workspace/public/services/use_case_service.ts
- feat: add home icon in left bottom
=> [navigation]feat: add home icon in left bottom

changelogs/fragments/7811.yml, package.json, yarn.lock
[CVE-2017-16100] Use a patched version of `dns-sync`
The library hasn't been updated in years. Even though an [upstream PR](https://github.com/skoranga/node-dns-sync/pull/10) was created, due to the criticality of the CVE, until upstream package is updated a patched version is employed.
- security: [CVE-2017-16100] Use a patched version for the `dns-sync` dependency
=> [CVE-2017-16100] Use a patched version of `dns-sync`

changelogs/fragments/7529.yml, src/plugins/opensearch_dashboards_react/public/table_list_view/edit_action_dropdown.test.tsx, src/plugins/opensearch_dashboards_react/public/table_list_view/edit_action_dropdown.tsx, src/plugins/opensearch_dashboards_react/public/table_list_view/table_list_view.tsx, src/plugins/vis_builder/public/application/components/data_tab/secondary_panel.tsx, src/plugins/vis_builder/public/application/utils/breadcrumbs.ts, src/plugins/vis_builder/public/application/utils/get_top_nav_config.tsx, src/plugins/vis_builder/public/application/utils/state_management/metadata_slice.ts, src/plugins/vis_builder/public/application/utils/state_management/redux_persistence.test.tsx, src/plugins/vis_builder/public/application/utils/state_management/store.ts, src/plugins/vis_builder/public/application/utils/use/use_can_save.ts, src/plugins/vis_builder/public/application/utils/use/use_saved_vis_builder_vis.ts, src/plugins/visualize/public/application/components/visualize_listing.tsx, src/plugins/visualize/public/application/utils/construct_vis_builder_path.ts, src/plugins/visualize/public/application/utils/contruct_vis_builder_path.test.ts, test/plugin_functional/test_suites/dashboard_listing_plugin/dashboard_listing_plugin.ts
In this PR, we aim to migrate legacy visualization objects compatible with VisBuilder to VisBuilder objects, enabling users to directly open these legacy objects in VisBuilder. The method involves constructing a URL that navigates directly to the VisBuilder page rendering the object. Key changes to the existing codebase include:
1. Adding a new function, `visbuilderEditItem`, triggered when users click the `Import to VisBuilder` button. This function takes a legacy visualization item as input, migrating the states from the visualization object to those required in the VisBuilder URL by calling `constructVisBuilderPath`, and then navigates to the VisBuilder app with the constructed path to complete the migration.
2. Modifying the existing user interface in Visualize, allowing users to …
=> [VisBuilder-Next] Migrate legacy visualizations to visbuilder by mapping the url

src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/create_index_pattern_wizard.tsx, src/plugins/index_pattern_management/public/components/edit_index_pattern/edit_index_pattern.tsx, src/plugins/index_pattern_management/public/components/edit_index_pattern/index_header/index_header.tsx, src/plugins/index_pattern_management/public/components/index_pattern_table/index_pattern_table.tsx
Fix the adoption of the new header in the index pattern management pages
---
- skip
=> Fix the adoption of the new header in the index pattern management pages

changelogs/fragments/7812.yml, src/plugins/embeddable/public/lib/panel/panel_header/panel_options_menu.tsx
Reverts back to an xs icon button for dashboard panel options.
N/A
Before
After
tested locally
- fix: correct size of dashboard panel options icon button
=> fix: correct size of dashboard panel options icon button

changelogs/fragments/7817.yml, src/plugins/workspace/public/types.ts, src/plugins/workspace/public/utils.test.ts, src/plugins/workspace/public/utils.ts
This PR is for fixing maximum call stack error in use case service, separate a function to compare features using `sort` instead of using `Array.property.some`. 
The root cause of this bug should be error features compare result see below example:
```
// use case 1
{
features:[{id:"1"},{id:"2"}]
}
// use case 2
{
features:[{id:"1"},{id:"2"}]
}
```
The result should be `true` which means two use case should be equal. But the old compare logic will return `false`. We should change `b.features.some` to `b.features.every`, then the result would be correct. Using `some` and `every` to implement the compare logic would be a little bit complicated, it can't handle duplicate features. So we change to use `sort` to compare the use case.
#7820 
No UI changes
- Clone branch code and run `yarn osd …
=> [Workspace]Fix maximum call stack error in use case service

changelogs/fragments/7841.yml, src/plugins/workspace/common/constants.ts, src/plugins/workspace/public/components/workspace_form/use_workspace_form.test.ts, src/plugins/workspace/public/components/workspace_form/use_workspace_form.ts, src/plugins/workspace/public/components/workspace_form/utils.ts, src/plugins/workspace/public/utils.ts
This PR is for removing default appended features logic for workspace create and update page. For now only `workspace_detail` will be appended to the features array in the workspace form. But the `workspace_detail` feature already been added to workspace's use case in [this code](https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/src/plugins/workspace/public/services/use_case_service.ts#L83-L88). Which means the `workspace_detail` feature will always be able to access inside workspace, then we don't need to append by default.
#7844
No UI changes
- Clone branch code and run `yarn osd bootstrap --single-version ignore`
```
uiSettings:
overrides: …
```
=> [Workspace]Remove default appended features

changelogs/fragments/7842.yml, src/plugins/workspace/public/components/home_get_start_card/use_case_footer.tsx, src/plugins/workspace/public/components/workspace_detail/__snapshots__/workspace_detail.test.tsx.snap, src/plugins/workspace/public/components/workspace_detail/association_data_source_modal.tsx, src/plugins/workspace/public/components/workspace_detail/opensearch_connections_table.tsx, src/plugins/workspace/public/components/workspace_form/workspace_detail_form_details.tsx, src/plugins/workspace/public/components/workspace_initial/__snapshots__/workspace_initial.test.tsx.snap, src/plugins/workspace/public/components/workspace_initial/workspace_initial.tsx, src/plugins/workspace/public/components/workspace_menu/workspace_menu.tsx
Use "small" buttons, "compressed" form inputs and small padding on popovers
- refactor: [Workspace] Use small button, small padding and compressed.
=> [Refactor] [Workspace] Use small button, small padding and compressed.

CHANGELOG.md, release-notes/opensearch-dashboards.release-notes-1.3.19.md
=> Update release notes for 1.3.19

changelogs/fragments/7853.yml, src/plugins/data/public/ui/query_editor/query_editor_top_row.tsx, src/plugins/data_explorer/public/components/app_container.tsx, src/plugins/discover/public/application/view_components/canvas/top_nav.tsx
Fixed the Nav bar layout in Discover when Query Enhancement flag is on. 
Case 1: When Query Enhancement is ON and New Home Page is ON
Case 2: When Query Enhancement is ON and New Home Page is OFF
Case 3: When Query Enhancement is OFF and New Home Page is ON
Case 4: When Query Enhancement is OFF and New Home Page is OFF
- fix: Nav bar layout in Discover when Query Enhancement Flag is On
=> Fix Nav Bar layout in New Discover

changelogs/fragments/7802.yml, packages/osd-pm/dist/index.js, src/core/public/chrome/ui/header/__snapshots__/collapsible_nav_group_enabled.test.tsx.snap, src/core/public/chrome/ui/header/collapsible_nav_group_enabled.scss, src/core/public/chrome/ui/header/collapsible_nav_group_enabled.tsx, src/plugins/home/public/application/components/home_icon.test.tsx, src/plugins/home/public/application/components/home_icon.tsx, src/plugins/home/public/plugin.ts, src/plugins/saved_objects_management/public/plugin.ts, src/plugins/visualize/public/plugin.ts, src/plugins/workspace/public/components/workspace_menu/workspace_menu.tsx, src/plugins/workspace/public/plugin.test.ts, src/plugins/workspace/public/plugin.ts, src/plugins/workspace/public/services/use_case_service.test.ts, src/plugins/workspace/public/services/use_case_service.ts
Backport 106b64cd1e85df979fa8b78269b25f10057d284c from #7802.
- skip
=> [Backport 2.x][navigation]feat: add home icon in left bottom (#7802)

src/core/public/index.ts, src/core/public/saved_objects/simple_saved_object.ts, src/plugins/workspace/public/components/workspace_list/__snapshots__/index.test.tsx.snap, src/plugins/workspace/public/components/workspace_list/index.test.tsx, src/plugins/workspace/public/components/workspace_list/index.tsx, src/plugins/workspace/public/types.ts, src/plugins/workspace/public/utils.test.ts, src/plugins/workspace/public/utils.ts
Add data source and owners column to workspace list page table
Go to workspace name and then you would see new column.
- feat: add data source and owners column to workspace list page table
=> [Workspace] feat: add data source and owners column to workspace list page table

changelogs/fragments/7865.yml, package.json, packages/osd-ui-framework/package.json, packages/osd-ui-shared-deps/package.json, test/interpreter_functional/plugins/osd_tp_run_pipeline/package.json, test/plugin_functional/plugins/osd_sample_panel_action/package.json, test/plugin_functional/plugins/osd_tp_custom_visualizations/package.json, yarn.lock
Updates oui to get latest updates
N/A
N/A
Validated things build
- chore: Update oui to 1.12
=> chore: Update oui to 1.12

src/plugins/data_source_management/opensearch_dashboards.json, src/plugins/data_source_management/public/components/breadcrumbs.ts, src/plugins/data_source_management/public/components/create_data_source_wizard/components/create_form/create_data_source_form.tsx, src/plugins/data_source_management/public/components/create_data_source_wizard/components/header/header.tsx, src/plugins/data_source_management/public/components/create_data_source_wizard/create_data_source_wizard.tsx, src/plugins/data_source_management/public/components/data_source_creation_panel/create_data_source_panel.test.tsx, src/plugins/data_source_management/public/components/data_source_creation_panel/create_data_source_panel.tsx, src/plugins/data_source_management/public/components/data_source_home_panel/__snapshots__/data_source_home_panel.test.tsx.snap, src/plugins/data_source_management/public/components/data_source_home_panel/data_source_home_panel.test.tsx, src/plugins/data_source_management/public/components/data_source_home_panel/data_source_home_panel.tsx, src/plugins/data_source_management/public/components/data_source_table/__snapshots__/data_source_table.test.tsx.snap, src/plugins/data_source_management/public/components/data_source_table/data_source_table.tsx, src/plugins/data_source_management/public/components/direct_query_data_sources_components/connection_detail/direct_query_connection_detail.tsx, src/plugins/data_source_management/public/components/direct_query_data_sources_components/direct_query_data_connection/__snapshots__/manage_direct_query_data_connections_table.test.tsx.snap, src/plugins/data_source_management/public/components/direct_query_data_sources_components/direct_query_data_connection/manage_direct_query_data_connections_table.tsx, src/plugins/data_source_management/public/components/direct_query_data_sources_components/direct_query_data_source_configuration/__snapshots__/query_permissions.test.tsx.snap, src/plugins/data_source_management/public/components/direct_query_data_sources_components/direct_query_data_source_configuration/amazon_s3/__snapshots__/configure_amazon_s3_data_source.test.tsx.snap, src/plugins/data_source_management/public/components/direct_query_data_sources_components/direct_query_data_source_configuration/amazon_s3/configure_amazon_s3_data_source.tsx, src/plugins/data_source_management/public/components/direct_query_data_sources_components/direct_query_data_source_configuration/configure_direct_query_data_sources.tsx, src/plugins/data_source_management/public/components/direct_query_data_sources_components/direct_query_data_source_configuration/prometheus/__snapshots__/configure_prometheus_data_source.test.tsx.snap, src/plugins/data_source_management/public/components/direct_query_data_sources_components/direct_query_data_source_configuration/prometheus/configure_prometheus_data_source.tsx, src/plugins/data_source_management/public/components/direct_query_data_sources_components/direct_query_data_source_configuration/query_permissions.tsx, src/plugins/data_source_management/public/components/edit_data_source/components/edit_form/edit_data_source_form.tsx, src/plugins/data_source_management/public/components/edit_data_source/components/header/header.tsx, src/plugins/data_source_management/public/components/edit_data_source/edit_data_source.test.tsx, src/plugins/data_source_management/public/components/edit_data_source/edit_data_source.tsx, src/plugins/data_source_management/public/management_app/mount_management_section.test.tsx, src/plugins/data_source_management/public/management_app/mount_management_section.tsx, src/plugins/data_source_management/public/types.ts
Implement new page header and Look&Feel UI changes for Admin->Data Sources page. 
-  In data sources home page, change connection type tabs to button groups, and mount it on the top controls.
-  Mount create data source button and other action buttons on the top.
-  Remove duplicate head titles.
-  For connect s3 and connect prometheus page, change to one step page instead of previous two steps(Configure/Review) pages.
- Make search bar, button, title to use small or compressed property.
New Page
- skip
=> [Page Header]Implement new page header for admin data sources page

changelogs/fragments/7842.yml, src/plugins/workspace/public/components/home_get_start_card/use_case_footer.tsx, src/plugins/workspace/public/components/workspace_detail/__snapshots__/workspace_detail.test.tsx.snap, src/plugins/workspace/public/components/workspace_detail/association_data_source_modal.tsx, src/plugins/workspace/public/components/workspace_detail/opensearch_connections_table.tsx, src/plugins/workspace/public/components/workspace_form/workspace_detail_form_details.tsx, src/plugins/workspace/public/components/workspace_initial/__snapshots__/workspace_initial.test.tsx.snap, src/plugins/workspace/public/components/workspace_initial/workspace_initial.tsx, src/plugins/workspace/public/components/workspace_menu/workspace_menu.tsx
Use small button, small padding and compressed.
Manual backport https://github.com/opensearch-project/OpenSearch-Dashboards/pull/7842
- skip
=> [Manual Backport][2.x][Workspace] Use small button, small padding and compressed.

src/plugins/query_enhancements/public/query_assist/utils/create_extension.tsx
This allows query assist to show up on indices from supported datasource and prevents multiple calls to get available languages
- skip
=> fix(queryAssist): allow dataset with `DATA_SOURCE` type

docs/openapi/README.md, src/core/public/overlays/modal/index.ts, src/core/public/overlays/modal/modal_service.tsx, src/plugins/data/public/ui/dataset_selector/_dataset_configurator.scss, src/plugins/data/public/ui/dataset_selector/_dataset_selector.scss, src/plugins/data/public/ui/dataset_selector/_index.scss, src/plugins/data/public/ui/dataset_selector/configurator.tsx, src/plugins/data/public/ui/dataset_selector/dataset_explorer.tsx, src/plugins/data/public/ui/dataset_selector/dataset_selector.tsx, src/plugins/data/public/ui/query_editor/_query_editor.scss, src/plugins/data/public/ui/query_editor/editors/default_editor/_default_editor.scss, src/plugins/data/public/ui/query_editor/editors/default_editor/index.tsx, src/plugins/data/public/ui/query_editor/editors/shared.tsx
Fixes Discover UI issues with the data selector and query bar 
1. Dataseletor wdth now stays constant unless smaller than window
2. Querybar matches the mocks better
https://github.com/user-attachments/assets/30a6e8f2-62f3-44fd-ac70-22e1f84da5c8
- skip
=> [Discover 2.0] UI Fixes

src/plugins/data/public/query/query_string/dataset_service/lib/utils.test.ts, src/plugins/query_enhancements/public/query_assist/utils/create_extension.test.tsx, src/plugins/query_enhancements/public/query_assist/utils/create_extension.tsx
enable tests for query assist extension and add tests for injecting meta to data structures
closes #7860
- skip
=> add tests for query assist extension and data structures utils

src/core/public/chrome/ui/header/__snapshots__/header.test.tsx.snap, src/core/public/chrome/ui/header/header.scss, src/core/public/chrome/ui/header/header.tsx, src/plugins/data/public/ui/filter_bar/_global_filter_group.scss, src/plugins/data/public/ui/filter_bar/filter_bar.tsx, src/plugins/data/public/ui/search_bar/create_search_bar.tsx, src/plugins/data/public/ui/search_bar/search_bar.tsx, src/plugins/navigation/public/top_nav_menu/top_nav_menu.tsx
- create a portal for filter bar component to render on its own row
- Add a  reference point that next to header
- Note that for discover, we still need filter bar to render as part of the SearchBar component
- with filters
- without filters
- skip
=> [Page Header]Render filter bar in full width with application header

changelogs/fragments/7873.yml, docs/_sidebar.md, src/core/utils/default_nav_groups.ts, src/plugins/home/public/application/components/home_list_card.test.tsx, src/plugins/home/public/application/components/sample_data/sample_data_card.test.tsx, src/plugins/workspace/README.md, src/plugins/workspace/common/constants.ts, src/plugins/workspace/public/components/home_get_start_card/use_case_footer.test.tsx, src/plugins/workspace/public/components/use_case_overview/setup_overview.test.tsx, src/plugins/workspace/public/components/workspace_form/workspace_detail_form_details.tsx, src/plugins/workspace/public/plugin.test.ts
This PR is to make the id of the essentials user case semantically aligned with the name of the use case to reduce confusion.
- feat: align essentials use case id
=> [Workspace]feat: align essentials use case id

src/core/public/chrome/ui/header/__snapshots__/collapsible_nav_group_enabled.test.tsx.snap, src/core/public/chrome/ui/header/collapsible_nav_group_enabled.tsx
Hide the scrollbar when the new left nav is collapsed.
- skip
=> [navigation]fix: only show scrollbar when expanded

changelogs/fragments/7901.yml, src/core/server/config/service/config_store_client/opensearch_config_store.test.ts, src/core/server/config/service/config_store_client/opensearch_config_store_client.ts
Fixes bootstrap within `2.x` branch caused by #7194 . This is due to `@opensearch-project/opensearch` major version difference between `main` and `2.x`, which has interface changes that break bootstrap (#3464).
- fix: Fix bootstrap errors in 2.x
=> Fix issue when bootstrapping on 2.x

changelogs/fragments/7858.yml, src/plugins/workspace/server/plugin.test.ts, src/plugins/workspace/server/plugin.ts
Revert new home page ui setting for workspace default route.
```
uiSettings:
overrides:
"home:useNewHomePage": true
```
and
```
```
are enabled/disabled at the same time.
We do not handle the case where useNewHomePage and workspace are inconsistent.
- fix: [Workspace] Revert new home page ui setting for workspace default route
=> [Bug][Workspace]fix: revert new home page ui setting for workspace default route

packages/osd-stylelint-config/config/global_selectors.json, src/plugins/data/public/query/query_string/language_service/_recent_query.scss, src/plugins/data/public/query/query_string/language_service/recent_query.tsx, src/plugins/data/public/query/query_string/query_history.ts, src/plugins/data/public/ui/dataset_selector/_dataset_configurator.scss, src/plugins/data/public/ui/dataset_selector/_dataset_explorer.scss, src/plugins/data/public/ui/dataset_selector/_dataset_selector.scss, src/plugins/data/public/ui/query_editor/query_editor.tsx
This PR contains the following changes:
- Fixes recent query to not show duplicates
- Fixes recent query styles
- Fixed Data selector height issue
https://github.com/user-attachments/assets/6fdbfdee-299f-4972-ba47-0e7a8f84cb82
- skip
=> [Discover 2.0] Fixed recent query and Data Selector styles

changelogs/fragments/7917.yml, src/plugins/data/common/constants.ts, src/plugins/data/public/query/query_string/dataset_service/dataset_service.ts, src/plugins/data/public/query/query_string/dataset_service/lib/index_pattern_type.ts, src/plugins/data/public/query/query_string/dataset_service/lib/index_type.ts, src/plugins/data/public/query/query_string/dataset_service/types.ts, src/plugins/data/public/ui/dataset_selector/advanced_selector.tsx, src/plugins/data/public/ui/dataset_selector/dataset_explorer.tsx, src/plugins/data/public/ui/dataset_selector/dataset_selector.tsx, src/plugins/query_enhancements/public/datasets/s3_handler.ts
Update the S3 type config.
This PR contains:
* Browsing connections, databases, tables
* Creating a dataset from a table and setting the string correctly.
This PR does NOT:
* Cache data structures
* Use session ID for querying
* Re-add async polling to search interceptor
n/a
- feat: add S3 data exploration for connections, databases, and tables
=> [discover] S3 data connection

changelogs/fragments/7913.yml, src/plugins/workspace/public/components/workspace_list/__snapshots__/index.test.tsx.snap, src/plugins/workspace/public/components/workspace_list/index.tsx
In this pr, I make a small change for the work list table followed by Trineo: Fit and Finish Guidance :
1. compress input
2. change back text size to xs, according to "Please DO NOT increase the size of existing extra-small text that is associated with tables, form elements, or where we may have intentionally chosen an extra-small size"
- fix: refactor the style for the work list table
=> [workspace] refine style of workspace list table

src/plugins/navigation/public/top_nav_menu/top_nav_menu.tsx
Fix the Run button placement when no date picker was being shown.
Case1: When QE is OFF and New Home Page is OFF
Without date picker
With date Picker
Case2 : When QE Is OFF and New Home Page is ON
Without date picker
With date picker
Case 3: When QE is ON and New Home Page is ON
Without date picker
With date picker
Case 4: When QE is ON and New Home Page is OFF
Without Date picker
With date Picker
- skip
=> Fix Run button position when datepicker is not visible

changelogs/fragments/7529.yml, src/plugins/opensearch_dashboards_react/public/table_list_view/edit_action_dropdown.test.tsx, src/plugins/opensearch_dashboards_react/public/table_list_view/edit_action_dropdown.tsx, src/plugins/opensearch_dashboards_react/public/table_list_view/table_list_view.tsx, src/plugins/vis_builder/public/application/components/data_tab/secondary_panel.tsx, src/plugins/vis_builder/public/application/utils/breadcrumbs.ts, src/plugins/vis_builder/public/application/utils/get_top_nav_config.tsx, src/plugins/vis_builder/public/application/utils/state_management/metadata_slice.ts, src/plugins/vis_builder/public/application/utils/state_management/redux_persistence.test.tsx, src/plugins/vis_builder/public/application/utils/state_management/store.ts, src/plugins/vis_builder/public/application/utils/use/use_can_save.ts, src/plugins/vis_builder/public/application/utils/use/use_saved_vis_builder_vis.ts, src/plugins/visualize/public/application/components/visualize_listing.tsx, src/plugins/visualize/public/application/utils/construct_vis_builder_path.ts, src/plugins/visualize/public/application/utils/contruct_vis_builder_path.test.ts, test/plugin_functional/test_suites/dashboard_listing_plugin/dashboard_listing_plugin.ts
=> [Manual Backport 2.x][VisBuilder-Next] Migrate legacy visualizations to visbuilder by mapping the url (#7529)

src/plugins/data/public/ui/dataset_selector/dataset_explorer.tsx
add data source management link in data selector
- skip
=> fix(discover): add data source management link in data selector

src/core/server/config/index.ts, src/core/server/config/mocks.ts, src/core/server/config/service/config_store_client/dummy_config_store_client.test.ts, src/core/server/config/service/config_store_client/dummy_config_store_client.ts, src/core/server/config/service/configuration_client.mock.ts, src/core/server/config/utils/utils.ts, src/core/server/mocks.ts, src/plugins/data_source/server/routes/fetch_data_source_metadata.test.ts, src/plugins/data_source/server/routes/test_connection.test.ts, src/plugins/usage_collection/server/routes/integration_tests/stats.test.ts, src/plugins/workspace/server/integration_tests/duplicate.test.ts
This PR separates `mock` files from `index`, which fixes the build artifact not bootstrapping
closes #7911
Built artifact and it starts (`opensearch` was not started hence the `ECONNREFUSED` error)
```bash
05:57:45 opensearch-dashboards-3.0.0-SNAPSHOT-linux-x64 ±|mock-fix ✗|→ ./bin/opensearch-dashboards
log   [17:57:52.601] [info][plugins-service] Plugin "applicationConfig" is disabled.
log   [17:57:52.604] [info][plugins-service] Plugin "cspHandler" is disabled.
log   [17:57:52.605] [info][plugins-service] Plugin "dataSource" is disabled.
log   [17:57:52.605] [info][plugins-service] Plugin "visTypeXy" is disabled.
log   [17:57:52.606] [info][plugins-service] Plugin "workspace" is disabled.
log   [17:57:52.651] [info][dynamic-config-service] registering middleware to inject context to …
```
=> Fix dynamicConfigService mock import

changelogs/fragments/7954.yml, src/plugins/workspace/server/routes/index.test.ts
The `dynamicConfigServiceMock` has been changed in [this PR](https://github.com/opensearch-project/OpenSearch-Dashboards/pull/7922/files). Current PR is for fixing `dynamicConfigServiceMock` was missing error. This PR will import dynamicConfigServiceMock from `core/server/mocks` directly.
#7955
No UI Changes
- Clone branch and Run `yarn osd bootstrap`
- Run `yarn test:jest src/plugins/workspace/server/routes/index.test.ts`
- All cases should be passed
- fix: [Workspace]dynamicConfigServiceMock not found in workspace routes UT
=> [Workspace]Fix dynamicConfigServiceMock import path in workspace routes UT

changelogs/fragments/7805.yml, src/core/public/chrome/chrome_service.tsx, src/core/public/chrome/ui/header/__snapshots__/header.test.tsx.snap, src/core/public/chrome/ui/header/header.test.tsx, src/core/public/chrome/ui/header/header.tsx, src/core/public/chrome/ui/header/recent_items.test.tsx, src/core/public/chrome/ui/header/recent_items.tsx
In this pr, I refactor the style of recent items card in the header by
1. Enable maxHeight; if exceeded, the menu will become scrollable.
2. Display associated icons.
3. The workspace name will be attached to the asset.
4. Allow setting preferences for the number of recent items displayed.
https://github.com/user-attachments/assets/dd8a364d-abd2-4274-a647-cd9bc6942e44
empty state
- feat: refractor the style of recent items card
=> [Workspace] Refactor the style of recent items card in the header

src/plugins/data/public/query/query_string/query_string_manager.ts, src/plugins/query_enhancements/server/utils/facet.ts
This changes fixes the following bugs
- SQL Search not working for IndexPatterns with Wildcards in the name
- Intial Page Load was not working for Non DQL default language
https://github.com/user-attachments/assets/0d3f4929-8a05-45ab-bcb2-3d4fe3a4c576
- skip
=> Discover Bug Fixes

src/plugins/discover/public/application/view_components/utils/update_search_source.ts
Right now in new discover, if user adds/removes two fields on the left quickly, it will crash with
```
Something went wrong
Try refreshing the page. If that doesn't work, go back to the previous page or clear your session data.
Clear your session
Go back
Cannot read properties of undefined (reading 'type')
Version: 3.0.0
Build: 9007199254740991
TypeError: Cannot read properties of undefined (reading 'type')
```
console error
```
fatal_errors_service.tsx:89 TypeError: Cannot read properties of undefined (reading 'type')
at isDefault (is_default.ts:33:1)
at updateSearchSource (update_search_source.ts:32:1)
at async use_search.ts:101:1
at async use_search.ts:193:1
```
I believe this happens because cache is being updated when user adds a field, and the index pattern is not available in the …
=> fix(discover): disable cache only on `indexPatterns.get` to prevent crash

src/plugins/data/public/query/query_string/dataset_service/dataset_service.mock.ts, src/plugins/data/public/query/query_string/dataset_service/lib/index_pattern_type.ts, src/plugins/data/public/query/query_string/dataset_service/types.ts, src/plugins/data/public/query/query_string/language_service/language_service.ts, src/plugins/data/public/query/query_string/query_string_manager.ts, src/plugins/data/public/ui/dataset_selector/configurator.tsx, src/plugins/data/public/ui/query_editor/language_selector.tsx
Currently the advanced dataset selector allows user to change language, but it doesn't affect UI on submit. this PR fixes it
- skip
=> fix(discover): switch language based on dataset selection

changelogs/fragments/7986.yml, src/plugins/workspace/public/components/workspace_detail/data_source_connection_table.scss, src/plugins/workspace/public/components/workspace_detail/data_source_connection_table.tsx
The previous code did not add a specific classname for `[id^="row"][id$="expansion"]`, which resulted the SCSS file affecting the global UI. Therefore, add a specific classname to it so that it only takes effect in the table in the workspace details section.
- fix: Fix workspace detail classname definition
=> [Bug] [Workspace]Fix workspace detail classname definition

changelogs/fragments/7823.yml, src/core/public/chrome/ui/header/collapsible_nav_group_enabled.tsx, src/core/public/chrome/ui/header/collapsible_nav_group_enabled_top.scss, src/core/public/chrome/ui/header/collapsible_nav_group_enabled_top.test.tsx, src/core/public/chrome/ui/header/collapsible_nav_group_enabled_top.tsx, src/plugins/content_management/public/mocks.ts, src/plugins/workspace/public/components/home_get_start_card/setup_get_start_card.scss, src/plugins/workspace/public/components/home_get_start_card/setup_get_start_card.tsx, src/plugins/workspace/public/components/use_case_overview/setup_overview.scss, src/plugins/workspace/public/components/use_case_overview/setup_overview.tsx, src/plugins/workspace/public/components/workspace_creator/workspace_form_summary_panel.test.tsx, src/plugins/workspace/public/components/workspace_creator/workspace_form_summary_panel.tsx, src/plugins/workspace/public/components/workspace_menu/workspace_menu.test.tsx, src/plugins/workspace/public/components/workspace_menu/workspace_menu.tsx, src/plugins/workspace/public/components/workspace_picker_content/workspace_picker_content.tsx, src/plugins/workspace/public/plugin.test.ts, src/plugins/workspace/public/plugin.ts, src/plugins/workspace/public/types.ts, src/plugins/workspace/public/utils.test.ts, src/plugins/workspace/public/utils.ts
=> [navigation] Add workspace icon to left nav / workspace picker menu / home page. (#7823)

changelogs/fragments/7925.yml, src/plugins/data_source/common/data_connections/data_connection_saved_object_attributes.ts, src/plugins/data_source/common/data_connections/index.ts, src/plugins/data_source/server/plugin.ts, src/plugins/data_source/server/saved_objects/data_connection.ts, src/plugins/data_source/server/saved_objects/index.ts
Today MDS plugin only supports OpenSearch datasources. With the new saved-object type data-connection, the intention is to allow the external data connections like CloudWatch and Security Lake.
NA
NA
Saved objects API testing sample inputs (unit tests added as well):
```
1. Create:
Input: 
POST http://localhost:5601/api/saved_objects/data-connection/12345
{
"attributes": {
"connectionId": "security-lake",
"type": "AWS CloudWatch"
}
}
Output: 
{
"type":  "data-connection",
"id":  "1234567",
"attributes":  {
"connectionId":  "security-lake",
"type":  "AWS CloudWatch"
},
"references":  [],
"updated_at":  "2024-08-29T21:38:20.344Z"
}
2. Update
Input:
PUT http://localhost:5601/api/saved_objects/data-connection/12345
{
"attributes": {
"connectionId": "security-lake",
"type": "AWS CloudWatch"
} …
```
=> Add Data connection saved-object type for external connections

src/plugins/query_enhancements/public/datasets/s3_type.test.ts, src/plugins/query_enhancements/public/datasets/s3_type.ts, src/plugins/query_enhancements/server/utils/facet.ts
Updated so the session ID gets correctly passed along to speed up subsequent queries. Also set the connection title to the datasource meta field to be used as originally interfaced.
n/a
- skip
=> [discover] pass connection title correctly and set session id

changelogs/fragments/7951.yml, src/plugins/data/public/index.ts, src/plugins/data/public/query/query_string/index.ts, src/plugins/data/public/query/query_string/language_service/index.ts, src/plugins/data/public/query/query_string/language_service/lib/index.ts, src/plugins/data/public/query/query_string/language_service/lib/query_result.tsx, src/plugins/data/public/query/query_string/query_string_manager.ts, src/plugins/data/public/ui/query_editor/query_editor.tsx, src/plugins/data/public/ui/query_editor/query_editor_top_row.tsx, src/plugins/data/public/ui/search_bar/create_search_bar.tsx, src/plugins/data/public/ui/search_bar/search_bar.tsx, src/plugins/data/public/ui/types.ts, src/plugins/data/public/ui/ui_service.ts, src/plugins/discover/public/application/view_components/canvas/index.tsx, src/plugins/discover/public/application/view_components/canvas/top_nav.tsx, src/plugins/discover/public/application/view_components/utils/index.tsx, src/plugins/discover/public/application/view_components/utils/use_search.ts, src/plugins/discover/public/index.ts, src/plugins/inspector/common/adapters/request/request_responder.ts, src/plugins/navigation/public/top_nav_menu/top_nav_menu.tsx, src/plugins/query_enhancements/common/utils.ts, src/plugins/query_enhancements/public/search/ppl_search_interceptor.ts, src/plugins/query_enhancements/server/routes/index.ts, src/plugins/query_enhancements/server/search/ppl_search_strategy.ts, src/plugins/query_enhancements/server/search/sql_search_strategy.test.ts, src/plugins/query_enhancements/server/search/sql_search_strategy.ts
Add query result and query execution time to the query editor footer. 
TODO:
- query error UI in the follow up PR
https://github.com/user-attachments/assets/39004f4a-18f8-42b8-8f2d-20c130168520
- feat: Add query result and time to the query editor footer
=> Add query result and time to the query editor footer

changelogs/fragments/7989.yml, src/plugins/saved_objects_management/public/management_section/objects_table/__snapshots__/saved_objects_table.test.tsx.snap, src/plugins/saved_objects_management/public/management_section/objects_table/components/__snapshots__/header.test.tsx.snap, src/plugins/saved_objects_management/public/management_section/objects_table/components/header.test.tsx, src/plugins/saved_objects_management/public/management_section/objects_table/components/header.tsx, src/plugins/saved_objects_management/public/management_section/objects_table/saved_objects_table.tsx
Hide saved object import button in the save object management page(assets page)when user is outside workspace.
Related issue https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4944
outside workspace
inside a workspace
- refactor: Hide saved object import button when user is outside workspace
=> [Workspace]Hide saved object import button when user is outside workspace

changelogs/fragments/7992.yml, src/core/public/chrome/ui/header/__snapshots__/header.test.tsx.snap, src/core/public/chrome/ui/header/header.tsx, src/core/public/chrome/ui/header/header_breadcrumbs.test.tsx, src/core/public/chrome/ui/header/header_breadcrumbs.tsx, src/plugins/workspace/public/utils.ts
Hide the home breadcrumbs when we are in a workspace, but keep it in recent popover
- feat: [Workspace] Hide home breadcrumbs when in a workspace
=> [Workspace] Hide first home breadcrumbs within workspace

src/core/utils/default_nav_groups.ts, src/plugins/home/public/application/components/use_case_card.test.ts, src/plugins/home/public/application/components/use_case_card.ts, src/plugins/home/public/application/home_render.test.tsx, src/plugins/home/public/application/home_render.tsx, src/plugins/saved_objects_management/public/management_section/recent_work.tsx, src/plugins/workspace/common/constants.ts, src/plugins/workspace/public/components/use_case_overview/setup_overview.test.tsx
This pr can be divided as 2 parts:
1. add use case cards when workspace is disabled
2. refine the style of recent_work in the home page, fix the line break issue that occurs when the screen becomes excessively large.
1. add use case cards when workspace is disabled
2. fix the line break issue that occurs when the screen becomes excessively large
before:
now:
- feat: add use case cards when workspace is disabled, refine the style of recent_work in the home page.
=> [Workspace] add use case cards when workspace is disabled, refine the style of recent_work in the home page.

src/core/public/chrome/ui/header/header_breadcrumbs.tsx
fix 2.x osd bootstrap issue for backport PR https://github.com/opensearch-project/OpenSearch-Dashboards/pull/8015
=> Fix 2.x issue

src/plugins/query_enhancements/server/utils/facet.test.ts, src/plugins/query_enhancements/server/utils/facet.ts
Deconstructing the dataSource caused an exception when no dataSource was set with the query. This can be the case with index patterns that are created and pointed to the `default`. Most times the default is the local cluster so there is no data source object in the query the case of the local.
Accessing by dot notation with null operator fixes this issue. Adding tests to prevent this happening again.
With query enhancements enabled we should considered ensuring index patterns always have a datasource object in the query.
Index patterns failed on SQL and PPL
URL:
`query:(dataset:(id:d3d7af60-4c81-11e8-b3d7-01146121b73d,timeFieldName:timestamp,title:opensearch_dashboards_sample_data_flights,type:INDEX_PATTERN),` 
- local
- unit tests
- skip
=> [discover] undefined datasource fix for index patterns for PPL and SQL

.github/CODEOWNERS, MAINTAINERS.md, changelogs/fragments/8025.yml
Add Huy(huyaboo) as maintainer
NA
N/A
NA
- doc: add Huy as maintainer
=> add Huy as maintainer

changelogs/fragments/8026.yml, yarn.lock
Bump `micromatch` from 4.0.7 to 4.0.8
- security: Bump `micromatch` from 4.0.7 to 4.0.8
=> Bump `micromatch` from 4.0.7 to 4.0.8

changelogs/fragments/8043.yml, src/plugins/workspace/server/saved_objects/workspace_saved_objects_client_wrapper.test.ts, src/plugins/workspace/server/saved_objects/workspace_saved_objects_client_wrapper.ts
This PR is for adding permission validation in saved objects client's `get` or `bulkGet` methods. Currently, a user can call `get` / `bulkGet` with data source id for global data source (not assigned to any workspace). These two methods will throw error when operating on these global data sources. 
#8044
No UI changes
- Clone branch code and run `yarn osd bootstrap --single-version ignore`
```
uiSettings:
overrides:
```
- Login with admin user
- Create a data source and record the data source id
- Create a `test-user` with `kibanauser` backend roles
- Call …
=> [Workspace]Deny get or bulkGet for global data source

src/plugins/data_source_management/public/components/create_button/create_button.test.tsx, src/plugins/data_source_management/public/components/create_button/create_button.tsx, src/plugins/data_source_management/public/components/data_source_home_panel/__snapshots__/data_source_home_panel.test.tsx.snap, src/plugins/data_source_management/public/components/data_source_home_panel/__snapshots__/data_source_page_header.test.tsx.snap, src/plugins/data_source_management/public/components/data_source_home_panel/data_source_home_panel.test.tsx, src/plugins/data_source_management/public/components/data_source_home_panel/data_source_home_panel.tsx, src/plugins/data_source_management/public/components/data_source_home_panel/data_source_page_header.test.tsx, src/plugins/data_source_management/public/components/data_source_home_panel/data_source_page_header.tsx, src/plugins/data_source_management/public/components/data_source_table/__snapshots__/data_source_table.test.tsx.snap, src/plugins/data_source_management/public/components/data_source_table/data_source_table.tsx, src/plugins/data_source_management/public/components/direct_query_data_sources_components/direct_query_data_connection/__snapshots__/manage_direct_query_data_connections_table.test.tsx.snap, src/plugins/data_source_management/public/components/direct_query_data_sources_components/direct_query_data_connection/manage_direct_query_data_connections_table.test.tsx, src/plugins/data_source_management/public/components/direct_query_data_sources_components/direct_query_data_connection/manage_direct_query_data_connections_table.tsx, src/plugins/data_source_management/public/components/utils.ts, src/plugins/data_source_management/public/constants.ts
This pr implement displaying direct query connections of local cluster in different scenarios:
- Display direct query connections when multiple data source is disabled.
- Display direct query connections when multiple data source is enabled.
Also solve a small bug when directing to direct query data source details page.
Data Source Enabled
- The local cluster can not be selected and deleted, it's read-only and un-clickable. However, the direct query connections under local cluster can be clicked.
Data Source Disabled
- skip
=> display direct query connections of local cluster in data sources page

src/plugins/data_source_management/public/components/create_button/create_button.test.tsx, src/plugins/data_source_management/public/components/create_button/create_button.tsx, src/plugins/data_source_management/public/components/data_source_home_panel/__snapshots__/data_source_home_panel.test.tsx.snap, src/plugins/data_source_management/public/components/data_source_home_panel/__snapshots__/data_source_page_header.test.tsx.snap, src/plugins/data_source_management/public/components/data_source_home_panel/data_source_home_panel.test.tsx, src/plugins/data_source_management/public/components/data_source_home_panel/data_source_home_panel.tsx, src/plugins/data_source_management/public/components/data_source_home_panel/data_source_page_header.test.tsx, src/plugins/data_source_management/public/components/data_source_home_panel/data_source_page_header.tsx, src/plugins/data_source_management/public/components/data_source_table/__snapshots__/data_source_table.test.tsx.snap, src/plugins/data_source_management/public/components/data_source_table/data_source_table.tsx, src/plugins/data_source_management/public/components/direct_query_data_sources_components/direct_query_data_connection/__snapshots__/manage_direct_query_data_connections_table.test.tsx.snap, src/plugins/data_source_management/public/components/direct_query_data_sources_components/direct_query_data_connection/manage_direct_query_data_connections_table.test.tsx, src/plugins/data_source_management/public/components/direct_query_data_sources_components/direct_query_data_connection/manage_direct_query_data_connections_table.tsx, src/plugins/data_source_management/public/components/utils.ts, src/plugins/data_source_management/public/constants.ts
Backport https://github.com/opensearch-project/OpenSearch-Dashboards/commit/e62142256484ca56382ca46b6394ed874b5a10e9 from https://github.com/opensearch-project/OpenSearch-Dashboards/pull/8059.
=> [Manual backport 2.17]display direct query connections of local cluster in data sources page (#8059)

changelogs/fragments/8045.yml, src/plugins/data/public/ui/query_editor/_query_editor.scss, src/plugins/data/public/ui/query_editor/query_editor_extensions/query_editor_extensions.tsx, src/plugins/query_enhancements/public/query_assist/_index.scss
When the react portal was created asynchronously within the same container, the order of query editor extensions cannot not be guaranteed. As react portal append the rendered component to the same container at the time when it's mounted. To fix the issue, now rendering the extension to different pre-ordered container.
This PR also introduced a few style changes so that multiple extensions can be render horizontally: 
- fix: order of query editor extensions not working
=> fix: order of query editor extensions not working

changelogs/fragments/7953.yml, src/core/server/ui_settings/create_or_upgrade_saved_config/create_or_upgrade_saved_config.ts, src/core/server/ui_settings/ui_settings_client.ts, src/core/server/ui_settings/utils.ts, src/core/types/ui_settings.ts, src/plugins/advanced_settings/server/saved_objects/user_ui_settings_client_wrapper.ts, src/plugins/workspace/public/components/workspace_list/index.tsx
This PR is a quick follow up on user settings PR [comments](https://github.com/opensearch-project/OpenSearch-Dashboards/pull/8057#issuecomment-2334446649)
It includes 
1. mark user settings as experimental
2. add i18n support for user settings page
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/8072
- skip
=> Mark user personal settings as experimental

changelogs/fragments/8079.yml, src/plugins/workspace/public/components/workspace_creator/workspace_creator_form.tsx, src/plugins/workspace/public/components/workspace_form/workspace_detail_form_details.tsx
This PR is for fixing workspace description field error when name invalid in the workspace create and detail page. 
#8081 
- Clone branch code and run `yarn osd bootstrap --single-version ignore`
```
uiSettings:
overrides:
```
- Login and visit workspace create page
- Input a invalid workspace name, such as "Observability~!@"
- Click "Create workspace" button
- Workspace name should show error and workspace description should not show error
- Input a valid workspace name, and click "Create workspace" button
- Go to the created workspace page and click "Edit" button
- Input a in valid workspace name and click …
=> [Workspace]Fix workspace description error when name invalid

src/plugins/dashboard/public/application/components/dashboard_top_nav/dashboard_top_nav.tsx, src/plugins/dashboard/public/application/embeddable/empty/dashboard_empty_screen.scss, src/plugins/discover/public/application/view_components/canvas/top_nav.tsx, src/plugins/opensearch_dashboards_react/public/table_list_view/table_list_view.tsx, src/plugins/vis_builder/public/application/components/top_nav.tsx, src/plugins/visualize/public/application/components/visualize_listing.tsx, src/plugins/visualize/public/application/components/visualize_top_nav.tsx
The changes in the PR aims at improving the look and feel of the Application header.
- Change the titles of new Dashboard - New dashboard, Visualization - New visualization, Discover - New search
- Fix padding & spacing issues in visualization landing page
- Fix margin for the Add an existing object to the dashboard wizard
- Fix header look and feel changes for Discover, Dashboards and Visualization Pages
=> Fix header look and feel changes

changelogs/fragments/8076.yml, docs/_sidebar.md, src/core/server/utils/auth_info.ts, src/plugins/home/common/constants.ts, src/plugins/home/public/plugin.ts, src/plugins/workspace/public/services/use_case_service.test.ts, src/plugins/workspace/public/services/use_case_service.ts
In release 2.17 we won't make import sample data into a modal so we need to add the menu back.
- feat: [navigation] Add `sample data` menu back
=> [navigation]feat: add `sample data` menu back

src/plugins/data/public/ui/filter_bar/_global_filter_group.scss, src/plugins/navigation/public/top_nav_menu/_index.scss
Drop the arbitrary space to the left of the search bar and only apply a max-width to the title when the screen is not wide (xxl).
- skip
=> Readjust space between the search bar and the actions

changelogs/fragments/8082.yml, docs/_sidebar.md, src/plugins/discover/public/application/view_components/utils/use_index_pattern.ts
Fix an infinite loop cause discover hang.
https://github.com/opensearch-project/OpenSearch-Dashboards/blob/cedba8e5c1275606b6ffdb1fd94c040decc3d4a5/src/plugins/discover/public/application/view_components/utils/use_index_pattern.ts#L47-L66
From the url below, we can see indexPattern is empty string. Based on the logic above,
`
http://localhost:5601/app/data-explorer/discover#?_a=(discover:(columns:!(_source),isDirty:!f,sort:!()),metadata:(indexPattern:'',view:discover))&_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-15m,to:now))`
If `newId` is empty, `indexPatternIdFromState` will be empty string, when line 64 `handleIndexPattern();` execute, it will go to same condition path and have infinite loop.
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/7626 …
=> [Discover]Fix infinite loop cause discover hang

src/plugins/data/public/ui/query_editor/_query_editor.scss, src/plugins/data/public/ui/query_editor/query_editor_extensions/query_editor_extensions.tsx
This is a follow up of https://github.com/opensearch-project/OpenSearch-Dashboards/pull/8045. With this PR, it only creates the query extension container when the container not exists, this will avoid creating duplicate containers.
- skip
=> fix: it should not create multiple query editor extension container

changelogs/fragments/8086.yml, src/plugins/workspace/public/components/workspace_detail/workspace_bottom_bar.test.tsx, src/plugins/workspace/public/components/workspace_detail/workspace_bottom_bar.tsx, src/plugins/workspace/public/components/workspace_detail/workspace_detail.tsx, src/plugins/workspace/public/components/workspace_detail_app.tsx, src/plugins/workspace/public/components/workspace_form/data_source_connection_table.tsx, src/plugins/workspace/public/components/workspace_form/workspace_permission_setting_panel.tsx
Fix page display errors:
- DQC table in workspace detail page
- `Add collaborator` button in workspace detail page
Add loading status when user update workspace.
Fix table error:
Fix button error:
After updating workspace, it will show the loading state.
- fix: [Workspace]Fix page display errors and add loading status
=> [Bug][Workspace]Fix page display errors and add loading status

CHANGELOG.md, package.json, yarn.lock
Cherry-picked dcd170aa7d6ee0d09bbd0f8d397a93e5a73d8f67 from #7811
=> [Manual backport 1.3][CVE-2017-16100] Use a patched version of `dns-sync` (#7811)

changelogs/fragments/8008.yml, docs/_sidebar.md, release-notes/opensearch-dashboards.release-notes-2.17.0.md, src/plugins/data_source_management/public/components/direct_query_data_sources_components/connection_detail/direct_query_connection_detail.test.tsx, src/plugins/data_source_management/public/components/direct_query_data_sources_components/connection_detail/direct_query_connection_detail.tsx, src/plugins/data_source_management/public/components/direct_query_data_sources_components/integrations/__snapshots__/setup_integration.test.tsx.snap, src/plugins/data_source_management/public/components/direct_query_data_sources_components/integrations/create_integration_helpers.ts, src/plugins/data_source_management/public/components/direct_query_data_sources_components/integrations/installed_integrations_table.tsx, src/plugins/data_source_management/public/components/direct_query_data_sources_components/integrations/setup_integration.tsx, src/plugins/data_source_management/public/management_app/mount_management_section.tsx
Signed-off-by: Ryan Liang <jiallian@amazon.com>### Description
[MDS]Add MDS support for Integration
* Relate: https://github.com/opensearch-project/dashboards-observability/pull/2051
In the above screenshot, it shows successful integration of a remote cluster. The network tab shows the cluster id that matches the cluster id in search bar.
- feat: [MDS]Add MDS support for Integration
=> [MDS]Add MDS support for Integration

changelogs/fragments/8060.yml, src/plugins/discover/public/application/components/default_discover_table/default_discover_table.test.tsx, src/plugins/discover/public/application/components/default_discover_table/default_discover_table.tsx
When rendering infinite scrolling PPL/SQL in the new Discover UI, the rendering was stalling and entering an infinite loading loop. The root cause turns out to be that there's a small amount of fade-out at the bottom of the OSD application:
This was causing an issue with the progress bar observer responsible for loading the next batch of rows: it had `threshold: 1.0` set which meant that it would only trigger if the progress bar is 100% visible. This isn't a problem for DQL where large amounts of data records have a limit disclaimer at the bottom:
But when that disclaimer isn't present (for PPL and SQL), this fade effect would cover the progress bar, causing it not to meet the `1.0` threshold:
In addition to fixing the bug, this PR adds a batch of unit tests for the discover table.
N/A …
=> Fix row rendering in infinite scroll

docs/_sidebar.md, src/plugins/data/public/ui/dataset_selector/configurator.tsx, src/plugins/discover/public/application/view_components/utils/use_search.ts
Cache dataset is an async function that ends up creating the temporary index pattern. The temporary index pattern was not created and was causing an exception so the index pattern was never updated.
The index pattern not being updated didn't trigger the hooks to update the other parts of the app.
Available fields from previous selection are persisted when only index is changed, not index pattern
- skip
=> [discover] wait for dataset to created before emitted update

src/plugins/discover/public/application/view_components/utils/use_index_pattern.ts
Fix refresh when selecting an index. Previously, discover will be stuck on loading.
- fix: Fix refresh on index
=> [Discover] Fix refresh on index 

src/plugins/dashboard/public/application/utils/create_dashboard_container.tsx, src/plugins/dashboard/public/application/utils/get_nav_actions.tsx, src/plugins/dashboard/public/plugin.tsx, src/plugins/data/public/query/query_string/language_service/lib/dql_language.ts, src/plugins/data/public/query/query_string/language_service/lib/lucene_language.ts, src/plugins/data/public/query/query_string/language_service/types.ts, src/plugins/discover/public/application/components/top_nav/__snapshots__/open_search_panel.test.tsx.snap, src/plugins/discover/public/application/components/top_nav/open_search_panel.tsx, src/plugins/discover/public/embeddable/search_embeddable_factory.tsx, src/plugins/embeddable/public/plugin.tsx, src/plugins/query_enhancements/public/plugin.tsx, src/plugins/saved_objects/public/finder/saved_object_finder.tsx, src/plugins/visualizations/public/plugin.ts, src/plugins/visualizations/public/services.ts, src/plugins/visualizations/public/wizard/new_vis_modal.tsx, src/plugins/visualizations/public/wizard/search_selection/search_selection.tsx, src/plugins/visualizations/public/wizard/show_new_vis.tsx
This PR aims to filter out unsupported Saved Searches (SQL and PPL based Saved Queries are not supported for Visualization) across the application namely in Dashboards and Visualize.
Saved Search in Discover (contains all SQL, PPL, DQL, Lucene Searches)
Saved Search in Dashboards (contains DQL, Lucene based searches)
Saved Search in Visualize (contains DQL, Lucene based searches)
- skip
=> Filter Saved Search Based on AppName Supported by Language

changelogs/fragments/8118.yml, src/plugins/data_source_management/server/saved_objects/data_source_premission_client_wrapper.ts
This PR fixed the issue:
```
log   [18:03:38.100] [error][http] TypeError: this.savedObjectsClient.get is not a function
at UiSettingsClient.read (/usr/share/opensearch-dashboards/src/core/server/ui_settings/ui_settings_client.js:202:50)
at UiSettingsClient.getUserProvided (/usr/share/opensearch-dashboards/src/core/server/ui_settings/ui_settings_client.js:94:53)
at UiSettingsClient.getRaw (/usr/share/opensearch-dashboards/src/core/server/ui_settings/ui_settings_client.js:138:37)
at UiSettingsClient.getAll (/usr/share/opensearch-dashboards/src/core/server/ui_settings/ui_settings_client.js:86:28)
at UiSettingsClient.get (/usr/share/opensearch-dashboards/src/core/server/ui_settings/ui_settings_client.js:82:28)
at /usr/share/opensearch-dashboards/src/core/server/core_app/core_app.js:57:63
at …
```
=> fix: data source permission client wrapper error of not returning explicitly the saved object client functions

changelogs/fragments/8118.yml, src/plugins/data_source_management/server/saved_objects/data_source_premission_client_wrapper.ts
=> [Manual backport] [Backport 2.17] data source permission client wrapper error of not returning explicitly the saved object client functions

changelogs/fragments/8118.yml, src/plugins/data_source_management/server/saved_objects/data_source_premission_client_wrapper.ts
=> [Manual backport] [Backport 2.x] data source permission client wrapper error of not returning explicitly the saved object client functions

src/plugins/data/common/datasets/types.ts, src/plugins/data/public/query/query_string/dataset_service/types.ts, src/plugins/query_enhancements/public/search/ppl_search_interceptor.ts, src/plugins/query_enhancements/public/search/sql_search_interceptor.ts
Extended Dataset type config to provide search options like strategy to shift the strategy provided by language to the dataset itself.
=> Extended Dataset type config to provide search options like strategy

changelogs/fragments/8100.yml, src/plugins/data/public/ui/query_editor/language_selector.tsx, src/plugins/data/public/ui/query_editor/query_editor.tsx, src/plugins/data/public/ui/types.ts
Remove unsupported languages for dataset in language selector
- fix: Remove unsupported languages for dataset
=> Remove unsupported languages for dataset

changelogs/fragments/8108.yml, src/plugins/input_control_vis/public/components/vis/__snapshots__/range_control.test.tsx.snap, src/plugins/input_control_vis/public/components/vis/range_control.tsx
Correctly size of disabled ValidatedDualRange components in InputControl visualizations
Before:
After:
- fix: Correct the size of disabled ValidatedDualRange components in InputControl visualizations
=> Correct the size of disabled ValidatedDualRange components in InputControl visualizations

src/core/server/ui_settings/routes/delete.ts, src/core/server/ui_settings/routes/get.ts, src/core/server/ui_settings/routes/set.ts, src/core/server/ui_settings/routes/set_many.ts
1. Allow unknown query parameter for ui settings route
functional test set ui settings with tenant specified
https://github.com/opensearch-project/opensearch-dashboards-functional-test/blob/c9884bf615b9ab50c013abda4f878f7899a9d1d8/cypress/utils/commands.js#L483-L506
calling `api/opensearch-dashboards/settings` with query parameter 
```
curl --request POST \
--url 'http://localhost:5601/api/opensearch-dashboards/settings?security_tenant=global&scope=global' \
--header 'Authorization: Basic YWRtaW46YWRtaW4=' \
--header 'Content-Type: application/json' \
--header 'osd-xsrf: osd-fetch' \
--data '{
"changes": {
"defaultIndex": "logstash-*"
}
}' -v
Note: Unnecessary use of -X or --request, POST is already inferred.
* Host localhost:5601 was resolved.
* IPv6: ::1
* IPv4: 127.0.0.1
*   Trying …
```
=> Allow unknown query parameter for ui settings route

changelogs/fragments/8167.yml, src/plugins/discover/public/application/components/data_grid/data_grid_table.tsx
Fix Discover Embeddable not showing _source when all other column are removed.
Issue Before the fix 
https://github.com/user-attachments/assets/41ddde2e-c05d-4928-beda-f08eb651e20c
After Fix
https://github.com/user-attachments/assets/9967192c-628f-471d-b655-ea2ce5bdba01
- Navigate to Dashboards page
- Add a discover Save Search which contains multiple columns
- Remove all the columns 
- Check if _source column is displayed
- fix: Discover Embeddable not showing _source when all other column are removed
=> Fix Discover Embeddable not showing _source when all other column are removed

changelogs/fragments/8168.yml, src/plugins/discover/public/application/view_components/utils/use_search.ts
This PR resolves previously identified three similar bugs when using legacy discover:
Query and filter failed to persist when: 
* refresh the page
* switching between default discover table and datagrid
* using the share link
https://github.com/user-attachments/assets/2b8e5b54-756a-4435-ba52-284e7c875616
- fix: Sync query and filter when refreshing discover page
=> Sync query and filter when refreshing discover page

changelogs/fragments/8184.yml, src/core/server/config/service/config_store_client/opensearch_config_store.test.ts, src/core/server/config/service/config_store_client/opensearch_config_store_client.ts, src/core/server/config/utils/utils.test.ts, src/core/server/config/utils/utils.ts
This PR fixes a bug that can occur if the alias `.opensearch_dashboards_dynamic_config` exists but not the index `opensearch_dashboards_dynamic_config_N`. In particular the following test cases are as follows:
| **Alias present?** | **Alias points to what index(es)?**                       | **Expected behavior**           |
|----------------|-------------------------------------------------------|-----------------------------|
| No             | No index                                              | Create new index with alias |
| No             | `.opensearch_dashboards_dynamic_config_N`               | Update index with alias     |
| No             | `.opensearch_dashboards_dynamic_config_1`               | Update index with alias     |
| Yes            | Multiple indexes …
=> [Dynamic Config] Fix bug when attempting dynamic config index creation

changelogs/fragments/7178.yml, src/plugins/discover/public/application/components/default_discover_table/table_cell.tsx
see #7176. `osdDocTable__limitedHeight` class isn't associated with any style, use `truncate-by-height` to truncate. 
@AMoo-Miki  `osdDocTable__limitedHeight` was added in 1ba45a7c738e912dc7671079650445a69dd73e18, any concerns with this?
closes #7176
before
after
- fix: truncate height of table cell in legacy discover
=> fix(discover): truncate height of table cell

changelogs/fragments/8176.yml, package.json, yarn.lock
Cherry-picked ... from #8197 
- skip
=> [Manual backport 2.17] [CVE-2024-45296] Bump path-to-regexp to 1.9.0, 3.3.0, and 6.3.0 #8197 

changelogs/fragments/8200.yml, src/plugins/data_source/common/index.ts, src/plugins/data_source/opensearch_dashboards.json, src/plugins/workspace/common/constants.ts, src/plugins/workspace/common/types.ts, src/plugins/workspace/common/utils.ts, src/plugins/workspace/public/workspace_client.ts, src/plugins/workspace/server/routes/index.ts, src/plugins/workspace/server/saved_objects/integration_tests/saved_objects_wrapper_for_check_workspace_conflict.test.ts, src/plugins/workspace/server/saved_objects/saved_objects_wrapper_for_check_workspace_conflict.test.ts, src/plugins/workspace/server/saved_objects/saved_objects_wrapper_for_check_workspace_conflict.ts, src/plugins/workspace/server/saved_objects/workspace_saved_objects_client_wrapper.test.ts, src/plugins/workspace/server/saved_objects/workspace_saved_objects_client_wrapper.ts, src/plugins/workspace/server/utils.ts, src/plugins/workspace/server/workspace_client.test.ts, src/plugins/workspace/server/workspace_client.ts
Update workspace server to support data connection type
This is a PR picked from https://github.com/opensearch-project/OpenSearch-Dashboards/pull/8013, as we want to separate frontend and server changes and merge server changes first for testing, so we extract server changes from https://github.com/opensearch-project/OpenSearch-Dashboards/pull/8013 and create this PR.
post http://localhost:6601/api/workspaces
```
{
"attributes": {
"name": "workspace-name1",
"color": "#54B399",
"features": [
"use-case-observability"
]
},
"settings": {
"dataSources": [],
"dataConnections": [
"12345" // data connection object id
],
"permissions": {
"library_write": {
"users": [
"%me%"
]
},
"write": {
"users": [
"%me%"
]
}
}
}
}
```
Result
```
{
"success": true,
"result": {
"id": "_IlxNR"
}
}
```
put …
=> [Workspace] feat: update workspace server to support data connection type

changelogs/fragments/8176.yml, changelogs/fragments/8197.yml, package.json, yarn.lock
[CVE-2024-45296] Bump path-to-regexp to 1.9.0, 3.3.0, and 6.3.0 
- security: [CVE-2024-45296] Bump `path-to-regexp` to 1.9.0, 3.3.0, and 6.3.0
=> [CVE-2024-45296] Bump path-to-regexp to 1.9.0, 3.3.0, and 6.3.0 

changelogs/fragments/7891.yml, src/plugins/discover/public/application/components/no_results/no_results.tsx
Updates empty prompt in Discover. Comments out the Lucene Query Message prompt due to https://github.com/opensearch-project/OpenSearch-Dashboards/issues/8149.
| Before | After |
| ----- | ----- |
| <img width="1510" alt="No Results Before" src="https://github.com/user-attachments/assets/2ab8b904-c7f6-4796-a106-d2898ca63797"> | <img width="1510" alt="No Results Post" src="https://github.com/user-attachments/assets/cf13dd36-ee83-4011-93d2-6998586ae0ab"> |
- refactor: [Look&Feel] Updated Discover No Results panel
=> [Look&Feel] Updated Discover No Results panel

changelogs/fragments/8188.yml, src/plugins/workspace/public/components/delete_workspace_modal/delete_workspace_modal.tsx, src/plugins/workspace/public/components/workspace_detail/__snapshots__/workspace_detail.test.tsx.snap, src/plugins/workspace/public/components/workspace_detail/select_data_source_panel.test.tsx, src/plugins/workspace/public/components/workspace_detail/select_data_source_panel.tsx, src/plugins/workspace/public/components/workspace_detail/workspace_detail.tsx, src/plugins/workspace/public/components/workspace_detail/workspace_detail_connection_table.test.tsx, src/plugins/workspace/public/components/workspace_detail/workspace_detail_connection_table.tsx, src/plugins/workspace/public/components/workspace_detail/workspace_detail_panel.tsx, src/plugins/workspace/public/components/workspace_form/constants.ts, src/plugins/workspace/public/components/workspace_form/data_source_connection_table.tsx, src/plugins/workspace/public/components/workspace_form/workspace_detail_form.tsx, src/plugins/workspace/public/components/workspace_form/workspace_permission_setting_input.tsx, src/plugins/workspace/public/components/workspace_form/workspace_permission_setting_panel.tsx
This PR fix a bunch of UI bugs in workspace detail page, here are the list of changes:
- Update toast message on remove association flow
- Fix data source connection selected items not clear after canceled
- Update "Remove data source(s)" to "Remove data association(s)"
- Update collaborator form group title and description
- Make input readOnly instead of disabled
- Reduce the gap between associate button
- Move form error banner inside tab content
- Update hr margin in tab content
- Update gap between tab header and content
- Add copy tooltip for copy workspace id
- Update "Owner" to "Owners"
- Update use case icon in workspace detail page
- Type workspace name in workspace delete workspace modal
- Render `&mdash;` when description is empty
- Clone branch code and run `yarn osd …
=> [Workspace]Fix workspace detail UI bugs

changelogs/fragments/8213.yml, src/plugins/workspace/public/components/workspace_detail/workspace_detail.tsx
This PR is for adding "Delete workspace" tooltip for workspace settings top right delete button. 
https://github.com/user-attachments/assets/e5370d89-c1f9-4186-b2f7-ff7f165b415b
- Clone branch code and run `yarn osd bootstrap --single-version ignore`
```
uiSettings:
overrides:
```
- Create a workspace and then will redirect to the workspace use case overview page
- Open the left navigation, click "Workspace settings"
- Hover on top right Delete button, the tooltip should be displayed
- feat: [Workspace]Add tooltip in workspace settings top delete button
=> [Workspace]Add tooltip in workspace settings top delete button

changelogs/fragments/8223.yml, src/core/public/chrome/ui/header/header.scss
When overlays are positioned, the body becomes positioned relative. The margin on the feature page header vertically offset the body, which caused absolutely positioned overlays (like tooltips) to be 12px lower than expected. Using padding avoids this offset.
N/A
Before:
After:
This should resolve the dropdown issue we were seeing as well.
Tested locally
- fix: fix overlay offsets on pages with feature header
=> fix: fix overlay offsets on pages with feature header

package.json, yarn.lock
Cherry-picked 22f1d4614f8fff67b270ccf6c5ca70fd22f11961 from #8102
- skip
=> [Manual backport 2.x] Bump browserslist to prevent integration test errors (#8102)

src/plugins/query_enhancements/public/search/ppl_search_interceptor.ts
Piped functions in ppl were not running
https://app.asana.com/0/1208080319527398/1208216692717508/f
=> [Bug] Fix ppl commands

changelogs/fragments/8232.yml, src/plugins/data/common/field_formats/utils/as_pretty_string.test.ts, src/plugins/data/common/field_formats/utils/as_pretty_string.ts
Use @osd/std to prettify objects for display
Fixes #8211
Follow steps in #8211
- fix: Use @osd/std to prettify objects for display
=> Use @osd/std to prettify objects for display

src/plugins/discover/public/application/components/chart/chart.tsx, src/plugins/discover/public/application/components/data_grid/data_grid_table.tsx
This PR aims at accomplishing following things 
1. Remove the Enable the legacy Discover Table setting when we have the QueryEnhancement flag turned ON
2. Set the legacy Discover Table as default when QueryEnhancement flag is turned ON irrespective of users preference of Enable the legacy Discover toggle
3. When QueryEnhancement flag is turned OFF respect users preference of Enable the legacy Discover toggle while displaying the discover table
https://github.com/user-attachments/assets/61fb33dd-3597-4de8-ae07-49edfda1a01f
-  Follow the steps shown in the above video to validate various scenarios listed above
- skip
=> Set Legacy Discover Table as Default for Discover 2.0 Experience 

changelogs/fragments/8236.yml, src/plugins/advanced_settings/public/plugin.ts, src/plugins/advanced_settings/server/plugin.ts
Drop user personal settings page, user still could set personal default workspace in workspace list page
- fix: [Workspace] drop user personal settings page
=> [Workspace] Drop user personal settings page

changelogs/fragments/8217.yml, src/plugins/workspace/public/components/workspace_initial/__snapshots__/workspace_initial.test.tsx.snap, src/plugins/workspace/public/components/workspace_initial/workspace_initial.tsx
- Remove the vertical centering. Add extra large padding to the top of the page.
- Update the content to match figma (h1 and the paragraph)
- Make the space between the label and the popout icon smaller for the "Learn more from documentation"
- Add "External link" icon to the playgound link
- The spacing between the panel and the "Settings and setup" link should be 16px - medium
- fix: Fix initial page UI issues
=> [Bug] Fix initial page UI issues

changelogs/fragments/8212.yml, src/plugins/data/public/query/query_string/language_service/lib/__snapshots__/query_result.test.tsx.snap, src/plugins/data/public/query/query_string/language_service/lib/query_result.test.tsx, src/plugins/data/public/query/query_string/language_service/lib/query_result.tsx, src/plugins/data/public/ui/query_editor/query_editor.tsx, src/plugins/discover/public/application/view_components/utils/use_search.ts, yarn.lock
* when a query takes longer than 3s to complete, a loading indicator will appear after 3s and will also show a time counter; the completion time will show in seconds.
* when a query takes less than 1s to complete, the completion time will be shown in miliseconds. 
https://github.com/user-attachments/assets/60e9d207-7cd4-4e14-b0f6-42a5a6e6c993
- feat: Add loading indicator and counter to query result
=> Add loading indicator and counter to query result

changelogs/fragments/8274.yml, src/core/public/styles/_base.scss
Temporary fix for Chrome's problem with rendering mask images.
OUI provides the mask-image which Chrome 129 fails to render correctly.
It is not known if or when Chrome will fix this. Since almost all of these classes
are applied to elements with scrollbars where their content contained, containing the
paint is a safe solution.
Pulled from https://github.com/opensearch-project/oui/pull/1414
Fixes #8250
Follow steps on #8250
- fix: Add a temporary fix for a bug with Chrome 129 when handling mask-image
=> Temporary fix for a bug with Chrome 129 when handling mask-image

changelogs/fragments/8252.yml, src/plugins/data/public/query/query_string/language_service/lib/recent_query.tsx, src/plugins/data/public/query/query_string/language_service/types.ts, src/plugins/data/public/query/query_string/query_history.ts
Fix the bug of running recent query jump to another language.
- fix: Run recent query button work properly
=> Fix running recent query button

changelogs/fragments/8299.yml, src/plugins/data/opensearch_dashboards.json
Expose datasets and data_frames directories for specific imports. This will ensure that external plugins consuming the data plugins can import from these sub directories to avoid importing complete common code 
- fix: Expose datasets and data_frames directories for specific imports
=> Expose datasets and data_frames directories for specific imports

src/plugins/usage_collection/public/mocks.ts
=> test(usage_collection): expose a function to mock plugin start

src/core/public/chrome/ui/header/__snapshots__/header.test.tsx.snap, src/core/public/chrome/ui/header/collapsible_nav_group_enabled.tsx, src/core/public/chrome/ui/header/header.tsx
OUI v13.0 introduces xxl and xxxl, and it breaks the behavior of responsiveness break points when the screen is larger than 1679px. Comply 2 components with the new introduced `hideFor` classes to fix the issue.
https://github.com/user-attachments/assets/1197ca3d-22a5-47da-bd0d-af38e93532d7
- skip
=> [navigation]fix: add xxl and xxxl for left nav responsiveness

changelogs/fragments/8189.yml, src/core/public/chrome/nav_group/nav_group_service.test.ts, src/core/public/chrome/nav_group/nav_group_service.ts
This PR is to fix the bug that:
1. current nav group will be mapped to global system nav group even if user is in a workspace.
https://github.com/user-attachments/assets/08052f01-98ae-4f90-8cf3-337be011ef47
2. current nav group will be mapped to a nav group even when user is out of a workspace.
https://github.com/user-attachments/assets/d0f06152-24ee-4599-9bf4-ff82854467dd
- fix: current nav group will be mapped to global system nav group even if user is in a workspace.
- fix: current nav group will be mapped to a nav group even when user is out of a workspace.
=> [navigation]fix: optimize the logic to detect current nav group

src/core/public/chrome/ui/header/header.scss, src/plugins/data/public/ui/filter_bar/_global_filter_group.scss, src/plugins/navigation/public/top_nav_menu/__snapshots__/top_nav_menu.test.tsx.snap, src/plugins/navigation/public/top_nav_menu/top_nav_menu.tsx
[Page Header]Add responsiveness for application header
https://github.com/user-attachments/assets/09de669e-99f8-4ed9-a0b1-439ca3addc10
=> [Page Header]Add responsiveness for application header

changelogs/fragments/8320.yml, src/core/public/chrome/ui/header/__snapshots__/collapsible_nav.test.tsx.snap, src/core/public/chrome/ui/header/__snapshots__/header.test.tsx.snap, src/core/public/chrome/ui/header/collapsible_nav.tsx, src/core/public/chrome/ui/header/header.tsx, src/plugins/data/public/ui/query_editor/_query_editor.scss, src/plugins/data/public/ui/query_string_input/_query_bar.scss, src/plugins/home/public/application/components/_solutions_section.scss, src/plugins/opensearch_dashboards_overview/public/components/_overview.scss, src/plugins/vis_default_editor/public/_default.scss, src/plugins/vis_default_editor/public/_sidebar.scss
[New breakpoints were added to OUI](https://github.com/opensearch-project/oui/commit/b8a9daa3edc9e6af0b4b07ef5b6a19a5b4410cd3) but OSD did not respect them, causing some bugs. This tries to address that by looking for consumption of breakpoints and just treating largest sizes like xl.
This incorporates https://github.com/opensearch-project/OpenSearch-Dashboards/pull/8289.
N/A
N/A
Tested some of these cases locally.
- fix: update osd to respect new oui breakpoints
=> fix: update osd to respect new oui breakpoints

changelogs/fragments/8227.yml, src/plugins/navigation/public/top_nav_menu/_index.scss, src/plugins/navigation/public/top_nav_menu/top_nav_menu.tsx
Change page title of application headers to h1 and xs
- feat: Adjust semantics and sizing of page titles in application headers
=> Change page title of application headers to h1 and xs

changelogs/fragments/8222.yml, src/plugins/data/public/data_sources/datasource_selector/data_selector_refresher.tsx, src/plugins/data/public/data_sources/datasource_selector/datasource_selectable.tsx, src/plugins/data/public/ui/dataset_selector/dataset_selector.tsx, src/plugins/data/public/ui/query_editor/__snapshots__/language_selector.test.tsx.snap, src/plugins/data/public/ui/query_editor/_query_editor.scss, src/plugins/data/public/ui/query_editor/editors/shared.tsx, src/plugins/data/public/ui/query_editor/language_selector.tsx, src/plugins/data/public/ui/query_editor/query_editor.tsx, src/plugins/data/public/ui/query_string_input/_query_bar.scss, src/plugins/discover/public/application/components/sidebar/discover_field_search.tsx, src/plugins/discover/public/application/components/sidebar/discover_sidebar.scss
* Make use of compressed fields components
* Update query editor padding to center fit the text
* Update data explorer side bar search field
Data explorer with query enhancements enabled:
Data explorer with query enhancements disabled:
- fix: Update data explorer ui to use compressed components
=> Update data explorer ui to use compressed components

changelogs/fragments/8346.yml, yarn.lock
[CVE-2024-45801] Bump `dompurify` from 3.0.11 to 3.1.6
-security: [CVE-2024-45801] Bump `dompurify` from 3.0.11 to 3.1.6
=> [CVE-2024-45801] Bump `dompurify` from 3.0.11 to 3.1.6

src/plugins/data/public/ui/query_editor/query_editor_top_row.tsx, src/plugins/data/public/ui/query_string_input/_query_bar.scss, src/plugins/data/public/ui/query_string_input/query_bar_top_row.tsx
- [Page Header]Fix responsiveness issue for dashboards & visualization app header
https://github.com/user-attachments/assets/35f4eb5a-9ba4-4b00-8241-63a667d7fa31
- skip
=> [Page Header]Fix responsiveness issue for dashboards & visualization app headers

changelogs/fragments/8334.yml, src/plugins/data/public/ui/query_editor/_query_editor.scss, src/plugins/data/public/ui/query_editor/query_editor.tsx, src/plugins/data/public/ui/query_editor/query_editor_extensions/query_editor_extension.tsx, src/plugins/data/public/ui/query_editor/query_editor_extensions/query_editor_extensions.test.tsx, src/plugins/data/public/ui/query_editor/query_editor_extensions/query_editor_extensions.tsx, src/plugins/query_enhancements/public/query_assist/components/query_assist_button.tsx
Move the rendering of query extension control buttons to extension component to align with the existing pattern.
- refactor: move the render of query extension control buttons to extension component
=> refactor: move the render of query extension control buttons to extension component

changelogs/fragments/8331.yml, src/plugins/data/public/ui/query_editor/_query_editor.scss
This one line change fixed an issue of the query input on discover page that the input background container didn't not shrink when resizing, see the screen records:
Before:
https://github.com/user-attachments/assets/4acee382-adeb-4b1b-91f3-7b6f846772e1
After:
https://github.com/user-attachments/assets/ca2cffc9-846d-4a34-a390-924e7a37e00e
- fix: discover query input background not shrink when window resize
=> fix discover input background not shrink

changelogs/fragments/8315.yml, src/plugins/workspace/public/components/workspace_list/index.tsx
Hide delete button for non osd admins in workspace list
- fix: Hide delete button for non osd admins in workspace list
=> [Worksapce] Hide delete button for non osd admins in workspace list

changelogs/fragments/8375.yml, src/plugins/workspace/public/components/workspace_creator/creator_details_panel.tsx, src/plugins/workspace/public/components/workspace_creator/workspace_creator.test.tsx, src/plugins/workspace/public/components/workspace_creator/workspace_creator_form.tsx, src/plugins/workspace/public/components/workspace_form/fields/workspace_name_field.tsx
This PR is for updating details panel UI in workspace create page. Move the color, name and description input in the same panel like screenshot below.
```
uiSettings:
overrides:
```
- Login with admin user and go to workspace create page by bottom left menu
- The workspace details panel should be displayed like screenshot above
- The name, color and description field should work as expected
- feat: [Workspace]Update details panel UI in workspace create page
=> [Workspace]Update details panel UI in workspace create page

src/plugins/workspace/public/components/workspace_creator/workspace_creator_form.tsx, src/plugins/workspace/public/components/workspace_form/select_data_source_panel.tsx, src/plugins/workspace/public/components/workspace_form/workspace_permission_setting_input.tsx
Refactor data source association panel
before
after
- feat: Refactor data source association panel
=> [Workspace] Refactor data source association panel

changelogs/fragments/8286.yml, src/core/public/chrome/ui/header/collapsible_nav_group_enabled.test.tsx, src/core/public/chrome/ui/header/collapsible_nav_group_enabled.tsx, src/core/public/chrome/ui/header/header.test.tsx, src/core/public/chrome/ui/header/header.tsx
When new left nav is enabled, we should remember the state of the left nav.
https://github.com/user-attachments/assets/e87479c9-ed15-427b-8a5a-f39d7236d150
- feat: [navigation] remember state when expand / collapse left nav
=> [navigation]feat: remember state when expand / collapse left nav

src/core/public/chrome/ui/header/collapsible_nav_group_enabled.tsx, src/core/public/chrome/ui/header/collapsible_nav_group_enabled_top.tsx, src/plugins/workspace/public/components/workspace_menu/workspace_menu.scss, src/plugins/workspace/public/components/workspace_menu/workspace_menu.test.tsx, src/plugins/workspace/public/components/workspace_menu/workspace_menu.tsx, src/plugins/workspace/public/components/workspace_picker_content/workspace_picker_content.tsx, src/plugins/workspace/public/components/workspace_selector/workspace_selector.test.tsx, src/plugins/workspace/public/components/workspace_selector/workspace_selector.tsx, src/plugins/workspace/public/index.ts, src/plugins/workspace/public/plugin.test.ts, src/plugins/workspace/public/plugin.ts
This pr:
1. adds workspace selectors to left nav bar when inside of a workspace
2. updates the UI of workspace picker content to the newest design
1. the workspace list only appears in homepage
https://github.com/user-attachments/assets/a5cca6b0-710b-41de-ac98-f2296c188402
2. workspace selector
https://github.com/user-attachments/assets/d61b067d-4f2c-40e4-9595-985ff43c19ce
3. left bottom popover
https://github.com/user-attachments/assets/9150379f-fcce-4ab1-a7e6-10c74d8099b1
- feat: add workspace selector to left nav bar
=> [workspace]feat/add workspace selector to left nav bar.

src/plugins/workspace/public/components/home_get_start_card/use_case_card_title.tsx, src/plugins/workspace/public/components/workspace_column/workspace_column.tsx, src/plugins/workspace/public/components/workspace_creator_app.tsx, src/plugins/workspace/public/components/workspace_detail/workspace_detail.tsx, src/plugins/workspace/public/components/workspace_detail_app.tsx, src/plugins/workspace/public/components/workspace_fatal_error/workspace_fatal_error.tsx, src/plugins/workspace/public/components/workspace_form/fields/workspace_name_field.tsx, src/plugins/workspace/public/components/workspace_form/utils.ts, src/plugins/workspace/public/components/workspace_form/workspace_form_error_callout.tsx, src/plugins/workspace/public/components/workspace_form/workspace_permission_setting_input.tsx, src/plugins/workspace/public/components/workspace_form/workspace_permission_setting_panel.tsx, src/plugins/workspace/server/permission_control/client.ts, src/plugins/workspace/server/saved_objects/workspace_saved_objects_client_wrapper.ts
Fix unprefixed and duplicate i18n identifiers in workspace plugin
- fix: Fix unprefixed and duplicate i18n identifiers in workspace plugin
=> Fix unprefixed and duplicate i18n identifiers in workspace plugin

changelogs/fragments/8407.yml, src/plugins/visualize/public/application/components/visualize_listing.tsx, src/plugins/visualize/public/application/components/visualize_top_nav.tsx, src/plugins/visualize/public/application/utils/get_top_nav_config.tsx
Fix duplicate i18n identifiers in visualize plugin
- fix: Fix duplicate i18n identifiers in visualize plugin
=> Fix duplicate i18n identifiers in visualize plugin

src/plugins/data/public/ui/index_pattern_select/index_pattern_select.test.tsx, src/plugins/data_explorer/opensearch_dashboards.json, src/plugins/data_explorer/public/components/app_container.tsx, src/plugins/data_explorer/public/plugin.ts, src/plugins/data_explorer/public/services.ts, src/plugins/data_explorer/public/types.ts, src/plugins/data_explorer/public/ui_metric/constants.ts, src/plugins/data_explorer/public/ui_metric/index.ts, src/plugins/data_explorer/public/ui_metric/report_ui_metric.ts, src/plugins/discover/opensearch_dashboards.json, src/plugins/discover/public/application/view_components/utils/use_search.ts, src/plugins/discover/public/opensearch_dashboards_services.ts, src/plugins/discover/public/plugin.ts, src/plugins/discover/public/ui_metric/constants.ts, src/plugins/discover/public/ui_metric/index.ts, src/plugins/discover/public/ui_metric/report_ui_metric.ts
The PR aims at capturing following UI Metrics. 
1.  No of times discover has been loaded
2. No of times new discover has been loaded
3. No of times each datasource type queries have been executed
4. No of times each language queries have been executed
1. Set usageCollection.uiMetric.enabled to true
5. Call the API /api/stats?extended=true&legacy=true&exclude_usage=false
6. Verify the ui_metric doesn't contain an entry corresponding to Discover
7. Navigate to Discover
8. Interact with Discover change the datasources, language
9. Wait for 90s
10. Call the API /api/stats?extended=true&legacy=true&exclude_usage=false and verify ui_metric contains an entry corresponding to Discover with the metrics corresponding to above interaction
- skip
=> Add UI Metric for Discover 2.0

changelogs/fragments/8268.yml, src/plugins/workspace/server/plugin.ts, src/plugins/workspace/server/routes/duplicate.ts, src/plugins/workspace/server/routes/index.test.ts, src/plugins/workspace/server/routes/index.ts, src/plugins/workspace/server/saved_objects/integration_tests/workspace_id_consumer_wrapper.test.ts, src/plugins/workspace/server/saved_objects/integration_tests/workspace_saved_objects_client_wrapper.test.ts, src/plugins/workspace/server/saved_objects/workspace_id_consumer_wrapper.test.ts, src/plugins/workspace/server/saved_objects/workspace_id_consumer_wrapper.ts, src/plugins/workspace/server/types.ts, src/plugins/workspace/server/workspace_client.mock.ts
We need to validate the workspace ids users pass, if it is not valid, we should just throw a 400 error and save the resource of our search engine.
- feat: validate if the workspaces param is valid or not when consume it in the wrapper.
=> [workspace]feat: validate workspace when find objects

src/plugins/saved_objects_management/public/management_section/objects_table/components/__snapshots__/table.test.tsx.snap, src/plugins/saved_objects_management/public/management_section/objects_table/components/flyout.tsx, src/plugins/saved_objects_management/public/management_section/objects_table/components/table.tsx
Fix duplicate i18n identifier in savedObjectsManagement plugin
- fix: Fix duplicate i18n identifier in savedObjectsManagement plugin
=> Fix duplicate i18n identifier in savedObjectsManagement plugin

changelogs/fragments/8398.yml, src/plugins/index_pattern_management/public/components/breadcrumbs.ts, src/plugins/index_pattern_management/public/components/index_pattern_table/index_pattern_table.tsx
Fix dynamic uses of i18n in indexPatternManagement plugin
- fix: Fix dynamic uses of i18n in indexPatternManagement plugin
=> Fix dynamic uses of i18n in indexPatternManagement plugin

src/plugins/data/public/ui/index_pattern_select/index_pattern_select.test.tsx
Fix flaky IndexPatternSelect test in data plugin
- test: Fix flaky IndexPatternSelect test in data plugin
=> Fix flaky IndexPatternSelect test in data plugin

changelogs/fragments/8403.yml, src/plugins/home/server/ui_settings.ts
Fix dynamic uses of i18n in home plugin
- fix: Fix dynamic uses of i18n in home plugin
=> Fix dynamic uses of i18n in home plugin

changelogs/fragments/8408.yml, src/plugins/management/public/components/settings_icon.tsx
Fix unprefixed i18n identifiers in management plugin
- fix: Fix unprefixed i18n identifiers in management plugin
=> Fix unprefixed i18n identifiers in management plugin

changelogs/fragments/8409.yml, src/plugins/vis_augmenter/public/actions/plugin_resource_delete_action.ts, src/plugins/vis_augmenter/public/actions/saved_object_delete_action.ts, src/plugins/vis_augmenter/public/view_events_flyout/actions/open_events_flyout_action.ts, src/plugins/vis_augmenter/public/view_events_flyout/actions/view_events_option_action.tsx, src/plugins/vis_augmenter/server/plugin.ts
Fix unprefixed and duplicate i18n identifiers in visAugmenter plugin
- fix: Fix unprefixed and duplicate i18n identifiers in visAugmenter plugin
=> Fix unprefixed and duplicate i18n identifiers in visAugmenter plugin

changelogs/fragments/8393.yml, src/plugins/console/public/application/components/import_flyout.tsx, src/plugins/console/public/application/containers/editor/legacy/console_editor/editor.tsx
Fix dynamic uses of i18n and correct duplicate i18n identifiers in console plugin
- fix: Fix dynamic uses of i18n and correct duplicate i18n identifiers in console plugin
=> Fix dynamic uses of i18n and correct duplicate i18n identifiers in console plugin

changelogs/fragments/8404.yml, src/plugins/opensearch_dashboards_react/public/table_list_view/edit_action_dropdown.tsx
Fix dynamic uses of i18n in opensearchDashboardsReact plugin
- fix: Fix dynamic uses of i18n in opensearchDashboardsReact plugin
=> Fix dynamic uses of i18n in opensearchDashboardsReact plugin

src/plugins/vis_type_timeline/server/series_functions/graphite.js, src/plugins/vis_type_timeline/server/series_functions/graphite.test.js
Fix dynamic uses of i18n in visTypeTimeline plugin
- fix: Fix dynamic uses of i18n in visTypeTimeline plugin
=> Fix dynamic uses of i18n in visTypeTimeline plugin

changelogs/fragments/8401.yml, src/plugins/dashboard/public/application/components/dashboard_top_nav/dashboard_top_nav.tsx
Fix unprefixed i18n identifiers in dashboard plugin
- fix: Fix unprefixed i18n identifiers in dashboard plugin
=> Fix unprefixed i18n identifiers in dashboard plugin

src/plugins/data/public/ui/dataset_selector/dataset_explorer.tsx
Makes `defaultMessage` a string literal and removes space at the end.
- skip
=> [i18n] Fix i18n String in New Discover Cache Time

changelogs/fragments/8445.yml, src/plugins/workspace/public/components/workspace_form/workspace_use_case.test.tsx, src/plugins/workspace/public/components/workspace_form/workspace_use_case_flyout.test.tsx, src/plugins/workspace/public/components/workspace_form/workspace_use_case_flyout.tsx, src/plugins/workspace/public/services/use_case_service.test.ts, src/plugins/workspace/public/services/use_case_service.ts, src/plugins/workspace/public/types.ts, src/plugins/workspace/public/utils.test.ts, src/plugins/workspace/public/utils.ts
This PR is for fixing hidden features not accessible due to #8413 . The use case selector refactor PR modified the features array and removed features not displayed in the flyout. These features should be accessed even they not displayed in the use case flyout (such as: getting started, overview, all custom features).
No UI Changes.
```
uiSettings:
overrides:
```
- Login with admin user and go to workspace create page by bottom left menu
- The use case selector panel and use case flyout …
=> [Workspace]Fix use case hidden features not accessible

changelogs/fragments/8422.yml, src/plugins/workspace/public/application.tsx, src/plugins/workspace/public/components/utils/workspace.test.ts, src/plugins/workspace/public/components/utils/workspace.ts, src/plugins/workspace/public/components/workspace_creator/workspace_creator.test.tsx, src/plugins/workspace/public/components/workspace_creator/workspace_creator.tsx, src/plugins/workspace/public/components/workspace_list/__snapshots__/index.test.tsx.snap, src/plugins/workspace/public/components/workspace_list/default_workspace.test.tsx, src/plugins/workspace/public/components/workspace_list/index.test.tsx, src/plugins/workspace/public/components/workspace_list/index.tsx, src/plugins/workspace/public/utils.ts
1. support use case as router search populate for workspace create and list page
2. remove owners column in workspace list page
Go to workspace create/list page and use useCase search, for example
http://localhost:6601/app/workspace_list#/?useCase=Security%20Analytics , then you could see security use case to be populated.
- feat: Support use case populate for workspace create and list page
=> [Workspace] feat: support use case populate for workspace create and list page

changelogs/fragments/8461.yml, src/plugins/workspace/public/components/workspace_creator/workspace_create_action_panel.test.tsx, src/plugins/workspace/public/components/workspace_creator/workspace_create_action_panel.tsx, src/plugins/workspace/public/components/workspace_creator/workspace_creator.test.tsx, src/plugins/workspace/public/components/workspace_creator/workspace_creator.tsx, src/plugins/workspace/public/components/workspace_creator/workspace_creator_form.tsx, src/plugins/workspace/public/components/workspace_creator/workspace_form_summary_panel.test.tsx, src/plugins/workspace/public/components/workspace_creator/workspace_form_summary_panel.tsx, src/plugins/workspace/public/components/workspace_form/data_source_connection_table.tsx, src/plugins/workspace/public/components/workspace_form/select_data_source_panel.test.tsx, src/plugins/workspace/public/components/workspace_form/select_data_source_panel.tsx
This PR is for adding required restriction for data source selector in workspace creation page. The create workspace button will be disabled if no data sources assigned. It added a empty prompt message for indicate this behavior when no data source assigned. This PR also removed the populated workspace name.
```
uiSettings:
overrides:
```
- Login with admin user and go to workspace create page by bottom left menu
- No workspace name will be populated
- The create workspace button should …
=> [Workspace]Restrict at least one data source in workspace creation page

changelogs/fragments/8397.yml, src/plugins/query_enhancements/public/query_assist/components/call_outs.tsx, src/plugins/query_enhancements/public/query_assist/components/query_assist_banner.tsx, src/plugins/query_enhancements/public/query_assist/components/query_assist_summary.tsx, src/plugins/query_enhancements/public/query_assist/utils/create_extension.tsx, src/plugins/query_enhancements/public/query_editor/query_language_reference.tsx
Fix dynamic uses of i18n and correct unprefixed i18n identifiers in queryEnhancements plugin
- fix: Fix dynamic uses of i18n and correct unprefixed i18n identifiers in queryEnhancements plugin
=> Fix dynamic uses of i18n and correct unprefixed i18n identifiers in queryEnhancements plugin

changelogs/fragments/8396.yml, src/plugins/discover/public/application/components/chart/chart.tsx, src/plugins/discover/public/application/components/default_discover_table/table_cell.tsx, src/plugins/discover/public/application/components/default_discover_table/table_header_column.tsx, src/plugins/discover/public/application/components/sidebar/discover_sidebar.tsx
Fix dynamic uses of i18n in discover plugin
- fix: Fix dynamic uses of i18n in discover plugin
=> Fix dynamic uses of i18n in discover plugin

src/plugins/advanced_settings/public/management_app/__snapshots__/advanced_settings.test.tsx.snap, src/plugins/advanced_settings/public/management_app/advanced_settings.tsx, src/plugins/advanced_settings/public/management_app/components/search/__snapshots__/search.test.tsx.snap, src/plugins/advanced_settings/public/management_app/components/search/search.tsx, src/plugins/saved_objects_management/public/management_section/objects_table/components/__snapshots__/table.test.tsx.snap, src/plugins/saved_objects_management/public/management_section/objects_table/components/table.tsx
Compress the OuiSearchBar instances used on Advanced Settings and Saved Object Management pages
Also:
* Fix spacing of the search bar on Advanced Settings page
Note: An OUI update will be required before these kick in.
| Before | After |
|--------|------|
| ![Assets before](https://github.com/user-attachments/assets/bbeea2ca-0179-48af-a517-98339974a3d7) | ![Assets after](https://github.com/user-attachments/assets/363f2dfe-df22-48e5-ab19-139ebe2f0e17) |
| Before | After |
|--------|------|
| ![New Settings before](https://github.com/user-attachments/assets/3825a109-4b79-408f-8a71-ddde41b3f65f) | ![New Settings after](https://github.com/user-attachments/assets/6b472a68-b147-4141-9a12-1628a298c384) |
| ![old settings before](https://github.com/user-attachments/assets/2ad25e2c-232e-40b6-bf9e-0 …
=> Compress the OuiSearchBar instances used on Advanced Settings and Saved Object Management pages

changelogs/fragments/8406.yml, src/plugins/vis_type_vega/public/data_model/search_api.ts
Fix unprefixed i18n identifiers in visTypeVega plugin
- fix: Fix unprefixed i18n identifiers in visTypeVega plugin
=> Fix unprefixed i18n identifiers in visTypeVega plugin

changelogs/fragments/8399.yml, src/plugins/vis_builder/public/application/components/top_nav.tsx, src/plugins/vis_builder/public/application/utils/get_top_nav_config.tsx, src/plugins/vis_builder/public/application/utils/use/use_can_save.ts, src/plugins/vis_builder/public/application/utils/use/use_saved_vis_builder_vis.ts, src/plugins/vis_builder/public/embeddable/vis_builder_embeddable_factory.tsx, src/plugins/vis_builder/public/visualizations/metric/components/metric_viz_options.tsx, src/plugins/vis_builder/public/visualizations/metric/metric_viz_type.ts, src/plugins/vis_builder/public/visualizations/table/components/table_viz_options.tsx, src/plugins/vis_builder/public/visualizations/table/table_viz_type.ts, src/plugins/vis_builder/public/visualizations/vislib/area/area_vis_type.ts, src/plugins/vis_builder/public/visualizations/vislib/area/components/area_vis_options.tsx, src/plugins/vis_builder/public/visualizations/vislib/common/basic_vis_options.tsx, src/plugins/vis_builder/public/visualizations/vislib/histogram/components/histogram_vis_options.tsx, src/plugins/vis_builder/public/visualizations/vislib/histogram/histogram_vis_type.ts, src/plugins/vis_builder/public/visualizations/vislib/line/components/line_vis_options.tsx, src/plugins/vis_builder/public/visualizations/vislib/line/line_vis_type.ts, src/plugins/vis_builder/server/plugin.ts
Fix dynamic uses of i18n and correct unprefixed and duplicate i18n identifiers in visBuilder plugin
- fix: Fix dynamic uses of i18n and correct unprefixed and duplicate i18n identifiers in visBuilder plugin
=> Fix dynamic uses of i18n and correct unprefixed and duplicate i18n identifiers in visBuilder plugin

changelogs/fragments/8412.yml, examples/embeddable_examples/public/list_container/list_container_factory.ts, examples/embeddable_examples/public/todo/todo_ref_embeddable_factory.tsx, examples/expressions_example/common/expression_functions/action/quick_form_fn.ts, examples/multiple_data_source_examples/public/components/data_source_via_top_nav_menu.tsx, examples/search_examples/public/components/app.tsx, examples/state_containers_examples/public/with_data_services/components/app.tsx
Fix unprefixed i18n identifiers in examples
- fix: Fix unprefixed i18n identifiers in examples
=> Fix unprefixed i18n identifiers in examples

changelogs/fragments/8402.yml, src/plugins/data_source_management/public/components/data_source_creation_panel/create_data_source_panel.tsx
Fix incorrect use of TopNavControlDescriptionData in dataSourceManagement plugin
- fix: Fix incorrect use of TopNavControlDescriptionData in dataSourceManagement plugin
=> Fix incorrect use of TopNavControlDescriptionData in dataSourceManagement plugin

changelogs/fragments/8483.yml, examples/ui_actions_explorer/public/app.tsx, src/plugins/workspace/public/components/workspace_form/select_data_source_panel.tsx
This PR is for updating inconsistent i18n key names in workspace plugin and examples. These keys should start with "workspace" instead of "workspaces" according #8423 
- fix: Fix inconsistent i18n key names in workspace and examples
=> Fix inconsistent i18n key names in workspace and examples

changelogs/fragments/8480.yml, package.json, packages/osd-ui-framework/package.json, packages/osd-ui-shared-deps/package.json, src/core/public/chrome/ui/header/collapsible_nav_group_enabled.scss, src/core/public/chrome/ui/header/variables.scss, src/plugins/data_source_management/public/components/data_source_table/__snapshots__/data_source_table.test.tsx.snap, src/plugins/data_source_management/public/components/direct_query_data_sources_components/direct_query_data_connection/__snapshots__/manage_direct_query_data_connections_table.test.tsx.snap, src/plugins/workspace/public/components/workspace_selector/workspace_selector.scss, test/interpreter_functional/plugins/osd_tp_run_pipeline/package.json, test/plugin_functional/plugins/osd_sample_panel_action/package.json, test/plugin_functional/plugins/osd_tp_custom_visualizations/package.json, yarn.lock
Updates oui to 1.15 + updates side nav background color to use official oui variable
N/A
Validated changes picked up
- chore: Update oui to 1.15 and consume $ouiSideNavBackgroundColor
=> chore: Update oui to 1.15 and consume $ouiSideNavBackgroundColor

changelogs/fragments/8484.yml, src/plugins/workspace/public/components/workspace_creator/workspace_creator_form.test.tsx, src/plugins/workspace/public/components/workspace_creator/workspace_creator_form.tsx, src/plugins/workspace/public/components/workspace_form/workspace_use_case.tsx
This PR include two changes in workspace use case selector.
1. Remove the workspace name populated logic after use case selected
2. Reduce gaps between use case cards
```
uiSettings:
overrides:
```
- Login with admin user and go to workspace create page by bottom left menu
- The use case selector should displayed like screenshot above
- The workspace name should be be populated after use case changed
- feat: [Workspace]Remove workspace name populate after use case selected
=> [Workspace]Remove workspace name populate after use case selected

changelogs/fragments/8368.yml, src/plugins/data/public/search/search_service.ts
This is quick fix for the issue that the search strategy passed to data.search() API been completely ignored when query enhancement is enabled and the localStorage has a language preserved.
For example, selecting a language from discover language selector will make data.search() called with a specific strategy to use the language config stored in localStorage which is unexpected.
With this fix, language config is only used when search strategy is not passed explicitly.
Sharing my two cents:
1. I think it's better the `language` is passed as a parameter to `data.search()` instead of reading directly from query string manager(which has default value from local storage that different feature could share the same value). I think `data.search()` needs to be UI/feature-agnostic
2. I'm fine with …
=> fix(queryEnhancements): data.search() should not ignore the `strategy` passed as parameter

changelogs/fragments/8486.yml, src/plugins/workspace/public/components/add_collaborators_modal/add_collaborators_modal.test.tsx, src/plugins/workspace/public/components/add_collaborators_modal/add_collaborators_modal.tsx, src/plugins/workspace/public/components/add_collaborators_modal/index.ts, src/plugins/workspace/public/components/add_collaborators_modal/workspace_collaborator_input.test.tsx, src/plugins/workspace/public/components/add_collaborators_modal/workspace_collaborator_input.tsx, src/plugins/workspace/public/components/add_collaborators_modal/workspace_collaborators_panel.test.tsx, src/plugins/workspace/public/components/add_collaborators_modal/workspace_collaborators_panel.tsx, src/plugins/workspace/public/constants.ts, src/plugins/workspace/public/index.ts, src/plugins/workspace/public/plugin.test.ts, src/plugins/workspace/public/plugin.ts, src/plugins/workspace/public/register_default_collaborator_types.test.tsx, src/plugins/workspace/public/register_default_collaborator_types.tsx, src/plugins/workspace/public/services/index.ts, src/plugins/workspace/public/services/workspace_collaborator_types_service.test.ts, src/plugins/workspace/public/services/workspace_collaborator_types_service.ts, src/plugins/workspace/public/types.ts
This PR is for adding `WorkspaceCollaboratorTypesService` to allow set customized collaborator types. These types will be used in the workspace settings refactor PR. It allow customized different UI when adding collaborators in workspace detail page. This PR added a `setCollaboratorTypes` method in workspace setup return value to customize the collaborator using interface below.
```ts
export interface WorkspaceCollaboratorType {
id: string;
name: string;
buttonLabel: string;
getDisplayedType?: (collaborator: WorkspaceCollaborator) => boolean;
onAdd: ({ onAddCollaborators }: OnAddOptions) => Promise<void>;
}
export interface WorkspacePluginSetup {
setCollaboratorTypes: (collaboratorTypes: WorkspaceCollaboratorType[]) => void;
getAddCollaboratorsModal: () => typeof AddCollaboratorsModal;
} …
```
=> [Workspace]Add WorkspaceCollaboratorTypesService and AddCollaboratorsModal

changelogs/fragments/8490.yml, package.json, yarn.lock
[CVE-2024-39338] Bump axios from 1.7.2 to 1.7.7
Bump chokidar from 3.5.3 to 3.6.0
[SNYK-JS-MOCHA-2863123] Bump mocha from 10.1.0 to 10.7.3
[CVE-2024-42459][CVE-2024-42460][CVE-2024-42461] Bump elliptic from 6.5.4 to 6.5.7
- security: [CVE-2024-39338] Bump axios from 1.7.2 to 1.7.7
- security: [SNYK-JS-MOCHA-2863123] Bump mocha from 10.1.0 to 10.7.3
- security: [CVE-2024-42459][CVE-2024-42460][CVE-2024-42461] Bump elliptic from 6.5.4 to 6.5.7
- chore: Bump chokidar from 3.5.3 to 3.6.0
=> Bump axios, chokidar, mocha, and elliptic

changelogs/fragments/8503.yml, src/plugins/home/public/application/components/tutorial_directory.js
This page forgot to pass the feature flag to the data source menu component.
The local cluster option will still be present even if we set the hideLocalCluster as true
- fix: pass hide local cluster flag to data source menu in sample data page
=> Fix: pass hide local cluster flag to data source menu in sample data page

changelogs/fragments/8489.yml, src/core/public/chrome/ui/header/__snapshots__/collapsible_nav_group_enabled.test.tsx.snap, src/core/public/chrome/ui/header/collapsible_nav_group_enabled.scss, src/core/public/chrome/ui/header/collapsible_nav_group_enabled.tsx
Remove the shadow style and only show the border when left nav expanded.
- feat: update border style when new left nav expanded
=> [navigation]feat: update border style when new left nav expanded

changelogs/fragments/8460.yml, src/plugins/data_source_management/public/components/data_source_home_panel/__snapshots__/data_source_home_panel.test.tsx.snap, src/plugins/data_source_management/public/components/data_source_home_panel/data_source_home_panel.tsx
Replace segmented button with tabs for OpenSearch connections and Direct query connections
before:
After:
- fix: Replace segmented button with tabs for OpenSearch connections and Direct query connections
=> [Fix] Replace segmented button with tabs for OpenSearch connections and Direct query connections

changelogs/fragments/8481.yml, src/plugins/data/common/data_frames/types.ts, src/plugins/data/common/search/search_source/search_source.ts, src/plugins/data/common/utils/helpers.ts, src/plugins/discover/public/application/view_components/utils/use_search.ts, src/plugins/query_enhancements/common/types.ts, src/plugins/query_enhancements/common/utils.ts, src/plugins/query_enhancements/public/search/sql_search_interceptor.ts, src/plugins/query_enhancements/server/routes/index.ts, src/plugins/query_enhancements/server/search/sql_async_search_strategy.ts
Currently for async search we depend on the search strategy to start the query and poll for results and resolve once the query completes/fails but since can to the order of 1 to 2 min, the frontend will timeout. This PR adds logic in frontend to poll for the results once the query is started.
The search strategy's search method will be invoked with the query id when polling for results, else it should start search for the given query.
Tested using local setup and neo app 
- feat: Add logic to poll for async query result
=> Poll for results from frontend for async search

packages/osd-ui-shared-deps/theme_config.d.ts, packages/osd-ui-shared-deps/theme_config.js, src/core/server/http/http_server.mocks.ts, src/core/server/rendering/__snapshots__/rendering_service.test.ts.snap, src/core/server/rendering/rendering_service.test.ts, src/core/server/rendering/rendering_service.tsx, src/core/server/rendering/views/styles.tsx, src/core/server/ui_settings/ui_settings_client.test.ts, src/core/server/ui_settings/ui_settings_client.ts, src/core/server/ui_settings/ui_settings_config.ts, src/legacy/ui/ui_render/bootstrap/template.js.hbs, src/legacy/ui/ui_render/ui_render_mixin.js
Allow temporarily overriding the `themeTag`  via the query-string
Also:
* Fix `getOverrideOrDefault` not correctly returning overridden values
Note: This change is only going to `2.x` because the handling of UiSettings in `main` is not back-portable and needs to be revisited.
Note: Tests are yet to be added.
- feat: Allow temporarily overriding the `themeTag`  via the query-string
- fix: Fix `getOverrideOrDefault` not correctly returning overridden values
=> Allow overriding the themeTag temporarily via the query-string

changelogs/fragments/8524.yml, src/plugins/workspace/public/application.tsx, src/plugins/workspace/public/plugin.ts
This PR is for fixing page crashed in the analytics use case overview and essential use case overview. The root cause was using `this` inside a normal function. Since use case overview page doesn't need collaboratorTypes service, just remove it from the depend services list. 
```
uiSettings:
overrides:
```
- Login with admin user
- Go to analytics use case overview page, page should not crashed
- Go to essential use case overview page, page should not crashed
- fix: [Workspace]Analytics …
=> [Workspace]Analytics use case overview and essential use case overview crashed

changelogs/fragments/8166.yml, src/plugins/dashboard/public/application/components/dashboard_top_nav/__snapshots__/dashboard_top_nav.test.tsx.snap, src/plugins/data/public/mocks.ts, src/plugins/data/public/query/query_string/dataset_service/dataset_service.test.ts, src/plugins/data/public/query/query_string/dataset_service/dataset_service.ts, src/plugins/data/public/query/query_string/dataset_service/lib/index_type.ts, src/plugins/data/public/query/query_string/language_service/types.ts, src/plugins/data/public/ui/dataset_selector/configurator.tsx, src/plugins/data_explorer/public/components/app_container.tsx, src/plugins/query_enhancements/public/plugin.tsx
* Fixes blank row at bottom of Discover, thanks @ashwin-pc @AMoo-Miki for the change
* Fixes an issue where indexes were able to be selected with a placeholder time field, which would cause issues
* Disables time field selector in index pattern configurator if the index pattern already has a time field.
- fix: Fixes UI issues in Discover and data configurator
=> [Discover] UI Updates to Dataset Configurator

src/plugins/data/public/query/query_string/dataset_service/types.ts, src/plugins/data/public/ui/dataset_selector/dataset_explorer.tsx, src/plugins/data/public/ui/dataset_selector/dataset_table.test.tsx, src/plugins/data/public/ui/dataset_selector/dataset_table.tsx
#8255 added a `DatasetTable` component to allow a `DatasetTypeConfig` to define if user can select and query multiple datasets. Discover currently only references one dataset (see #8362), so `DatasetTable` combines multiple selected datasets into a single one for Discover.
The `title` of the combined datasets will be used as part of the SQL/PPL query
https://github.com/opensearch-project/OpenSearch-Dashboards/blob/cf7cb5bb5f6be4a7e83fa0ab71d98f843cfc67f0/src/plugins/query_enhancements/public/plugin.tsx#L73-L75
https://github.com/opensearch-project/OpenSearch-Dashboards/blob/cf7cb5bb5f6be4a7e83fa0ab71d98f843cfc67f0/src/plugins/query_enhancements/public/plugin.tsx#L92-L94
and this syntax can be different for each dataset type. This PR allows the `DatasetTypeConfig` to define how should the …
=> [Discover] support custom callback to combine multiple dataset selections

changelogs/fragments/8501.yml, src/plugins/workspace/public/components/workspace_creator/workspace_form_summary_panel.test.tsx, src/plugins/workspace/public/components/workspace_detail/__snapshots__/workspace_detail.test.tsx.snap, src/plugins/workspace/public/components/workspace_detail/workspace_detail.test.tsx, src/plugins/workspace/public/components/workspace_detail_app.tsx, src/plugins/workspace/public/components/workspace_form/__snapshots__/add_collaborator_button.test.tsx.snap, src/plugins/workspace/public/components/workspace_form/__snapshots__/workspace_collaborator_table.test.tsx.snap, src/plugins/workspace/public/components/workspace_form/add_collaborator_button.test.tsx, src/plugins/workspace/public/components/workspace_form/add_collaborator_button.tsx, src/plugins/workspace/public/components/workspace_form/constants.ts, src/plugins/workspace/public/components/workspace_form/types.ts, src/plugins/workspace/public/components/workspace_form/use_workspace_form.test.ts, src/plugins/workspace/public/components/workspace_form/use_workspace_form.ts, src/plugins/workspace/public/components/workspace_form/utils.test.ts, src/plugins/workspace/public/components/workspace_form/utils.ts, src/plugins/workspace/public/components/workspace_form/workspace_collaborator_table.test.tsx, src/plugins/workspace/public/components/workspace_form/workspace_collaborator_table.tsx, src/plugins/workspace/public/components/workspace_form/workspace_detail_form.tsx, src/plugins/workspace/public/components/workspace_form/workspace_form_context.tsx, src/plugins/workspace/public/components/workspace_form/workspace_permission_setting_input.test.tsx, src/plugins/workspace/public/components/workspace_form/workspace_permission_setting_input.tsx, src/plugins/workspace/public/components/workspace_form/workspace_permission_setting_panel.test.tsx, src/plugins/workspace/public/constants.ts
add collaborator table to workspace detail page
Go to workspace detail page, then test the related changes.
- feat: add collaborator table to workspace detail page
=> [Workspace]feat: add collaborator table to workspace detail page

changelogs/fragments/8530.yml, src/plugins/visualizations/public/wizard/new_vis_modal.tsx
Fix the issue that when adding a new visualization, the visualization id would be decoded and leads to not found.
- fix: Encode searchId as it tends to be decoded after adds into url.
=> Encode searchId as it tends to be decoded after adds into url

changelogs/fragments/8504.yml, src/plugins/vis_type_timeseries/public/application/components/aggs/_agg_row.scss, src/plugins/vis_type_timeseries/public/application/components/aggs/moving_average.js, src/plugins/vis_type_timeseries/public/application/components/aggs/serial_diff.js, src/plugins/vis_type_timeseries/public/application/components/aggs/top_hit.js, src/plugins/vis_type_timeseries/public/application/components/panel_config/gauge.js, src/plugins/vis_type_timeseries/public/application/components/panel_config/table.js, src/plugins/vis_type_timeseries/public/application/components/panel_config/timeseries.js, src/plugins/vis_type_timeseries/public/application/components/vis_types/timeseries/config.js, src/plugins/vis_type_timeseries/public/application/components/vis_types/timeseries/vis.js, src/plugins/vis_type_timeseries/public/application/visualizations/constants/chart.js, src/plugins/vis_type_timeseries/public/metrics_type.ts
Allow hiding the TSVB axis for time series
Also:
* Compress non-OUI input fields in TSVB visualizations
* Allow setting scale of each axis for TSVB time series
Fixes #1929
| Before | After |
|--------|-------|
| ![Before](https://github.com/user-attachments/assets/b50cc2ec-8455-4592-b895-eb0cf625c35d) | ![After](https://github.com/user-attachments/assets/e1f5354e-e85f-48a5-afcb-7e4d7886a86c)
- feat: Allow hiding the TSVB axis for time series visualizations
- fix: Compress non-OUI input fields in TSVB visualizations
- feat: Allow setting scale of each axis for TSVB time series
=> Allow hiding the TSVB axis for time series

src/plugins/discover/public/plugin.ts
This PR aims at hiding showDoc links for unsupported Query languages. 
https://github.com/user-attachments/assets/c62b151c-9498-404f-a67e-39b339654d0f
- skip
=> Hide Doc links for Unsupported Langauges

src/plugins/data/common/constants.ts, src/plugins/data/public/plugin.ts, src/plugins/data/public/query/query_service.ts, src/plugins/data/public/query/query_string/dataset_service/dataset_service.mock.ts, src/plugins/data/public/query/query_string/dataset_service/dataset_service.test.ts, src/plugins/data/public/query/query_string/dataset_service/dataset_service.ts, src/plugins/data/public/query/state_sync/connect_to_query_state.test.ts, src/plugins/data/public/query/state_sync/sync_state_with_url.test.ts, src/plugins/data/public/query/types.ts, src/plugins/data/public/ui/dataset_selector/dataset_selector.test.tsx, src/plugins/data/public/ui/dataset_selector/dataset_selector.tsx, src/plugins/data/public/ui/dataset_selector/index.test.tsx, src/plugins/data/public/ui/dataset_selector/index.tsx, src/plugins/data/server/ui_settings.ts
Adds recent datasets to dataset selector. Also fixes an issue where we were able to select an index without specifying a time field option.
- feat: Adds recently selected data to data selector
=> [Discover] Adding Recent Datasets

changelogs/fragments/8545.yml, src/core/public/index.ts, src/core/public/workspace/index.ts, src/core/public/workspace/types.ts, src/core/public/workspace/workspaces_service.mock.ts, src/core/public/workspace/workspaces_service.test.ts, src/core/public/workspace/workspaces_service.ts, src/plugins/data_source_management/public/components/data_source_table/data_source_table.test.tsx, src/plugins/data_source_management/public/components/data_source_table/data_source_table.tsx, src/plugins/data_source_management/public/components/direct_query_data_sources_components/direct_query_data_connection/manage_direct_query_data_connections_table.test.tsx, src/plugins/data_source_management/public/components/direct_query_data_sources_components/direct_query_data_connection/manage_direct_query_data_connections_table.tsx, src/plugins/data_source_management/public/mocks.ts, src/plugins/workspace/public/components/data_source_association/data_source_association.test.tsx, src/plugins/workspace/public/components/data_source_association/data_source_association.tsx, src/plugins/workspace/public/components/workspace_detail/association_data_source_modal.test.tsx, src/plugins/workspace/public/components/workspace_detail/association_data_source_modal.tsx, src/plugins/workspace/public/components/workspace_detail/select_data_source_panel.tsx, src/plugins/workspace/public/components/workspace_form/select_data_source_panel.tsx, src/plugins/workspace/public/workspace_client.ts, src/plugins/workspace/server/routes/index.ts, src/plugins/workspace/server/types.ts, src/plugins/workspace/server/workspace_client.ts
This PR refactored the data source management page to include:
1. Added a button to page header to associate data source to current workspace
2. Added a table action set default data source when inside a workspace
3. Added a table action to dissociate data source from the current workspace
https://github.com/user-attachments/assets/58a0177e-1265-4e67-ae6f-98d210ab394d
- feat: refactor data source list page to include data source association features for workspace
=> Refactor workspace datasource association

changelogs/fragments/8541.yml, src/plugins/workspace/public/components/workspace_selector/workspace_selector.scss, src/plugins/workspace/public/components/workspace_selector/workspace_selector.tsx
This pr fixes the workspace selector jump that occurs when hovering and clicking.
Before:
https://github.com/user-attachments/assets/ac72b982-87f1-4fd6-885b-d8c242bb07bd
After:
https://github.com/user-attachments/assets/e3aecc24-9d0b-4934-a8d4-9846f0c83952
- fix: the workspace selector jump that occurs when hovering and clicking.
=> [workspace]fix the workspace selector jump that occurs when hovering and clicking.

src/plugins/workspace/public/components/workspace_form/workspace_collaborator_table.test.tsx, src/plugins/workspace/public/components/workspace_form/workspace_collaborator_table.tsx
This pr adds last admin validation when trying to delete collaborators
1. if user tries to delete the last admin:
2. other cases:
- feat: add last admin validation when deleting collaborators
=> [workspace]add last admin validation when deleting collaborators

src/plugins/data/server/dql_telemetry/route.ts, src/plugins/vis_type_timeseries/server/lib/timeseries_visualization_client_wrapper.ts
Handles internal Server Error that were being thrown. 
- skip
=> Handle Server Side Errors

changelogs/fragments/8537.yml, src/plugins/data_source_management/public/components/utils.ts, src/plugins/data_source_management/server/routes/data_connections_router.ts, src/plugins/data_source_management/server/routes/index.ts
- Mute the non-mds endpoints for direct query data connections when MDS is enabled
- Use mds data connection endpoint instead for fetching local cluster direct query content
* Relate https://github.com/opensearch-project/OpenSearch-Dashboards/issues/8536
- fix: [MDS] Mute the non-mds endpoints for direct query data connections
=> [MDS] Mute the non-mds endpoints for direct query data connections

changelogs/fragments/8603.yml, package.json, packages/osd-std/package.json, yarn.lock
Upgrade JSON11 from 1.1.2 to 2.0.0 to ensure UTF-8 safety when stringifying JSON data.
Fixes #7367
- fix: Upgrade JSON11 from 1.1.2 to 2.0.0 to ensure UTF-8 safety when stringifying JSON data
=> Upgrade JSON11 from 1.1.2 to 2.0.0

src/plugins/data/public/query/query_string/dataset_service/lib/index_pattern_type.ts, src/plugins/data/public/query/query_string/dataset_service/lib/index_type.ts, src/plugins/data/public/query/query_string/dataset_service/types.ts, src/plugins/discover/public/application/view_components/utils/use_search.ts, src/plugins/query_enhancements/public/datasets/s3_type.ts
This introduces a searchOnPageLoad preference for each dataset type. 
- When Advanced setting of searchOnPageLoad is OFF we respect the Advanced setting 
- When Advanced setting of searchOnPageLoad is ON we respect the selected dataset's searchOnLoad preference
For this demonstration below I have explicitly updated the `searchOnLoad` preference for indexes to be false.
https://github.com/user-attachments/assets/78cb0c86-959d-4b2a-b6d1-88874ac483eb
- skip
=> Add SearchOnLoad Preference for dataset

changelogs/fragments/8607.yml, src/plugins/workspace/public/components/workspace_creator/creator_details_panel.tsx, src/plugins/workspace/public/components/workspace_form/utils.test.ts, src/plugins/workspace/public/components/workspace_form/utils.ts, src/plugins/workspace/public/components/workspace_form/workspace_detail_form_details.tsx, src/plugins/workspace/public/components/workspace_form/workspace_form_error_callout.test.tsx, src/plugins/workspace/public/components/workspace_form/workspace_form_error_callout.tsx
Limit workspace colors to just those in color picker swatch.
- feat: Limit workspace colors
=> [Workspace] Limit workspace colors

changelogs/fragments/8619.yml, src/plugins/workspace/public/components/workspace_list/__snapshots__/index.test.tsx.snap, src/plugins/workspace/public/components/workspace_list/index.tsx
fine-tune workspace list page compressed style to align with compressed table
Go to workspace list page then see the UI change.
- refactor: Fine-tune workspace list page compressed style to align with compressed table
=> [Workspace] fine-tune workspace list page compressed style to align with compressed table

changelogs/fragments/8617.yml, config/opensearch_dashboards.yml, src/plugins/workspace/common/constants.ts, src/plugins/workspace/server/plugin.test.ts, src/plugins/workspace/server/utils.test.ts, src/plugins/workspace/server/utils.ts
Update default workspace permission and support wildcard.
1. Without configuring OSD admin in the `config.yml`, anyone will not be OSD admin.
2. Support wildcard `*` in users config. With configuring `*` in the `config.yml` (`opensearchDashboards.dashboardAdmin.users: ["*"]`), anyone will be OSD admin.
- refactor: [Workspace] Update default OSD admin config permission and support wildcard.
=> [Workspace] Update default workspace permission and users config support wildcard

changelogs/fragments/8606.yml, src/plugins/content_management/public/components/section_input.test.ts, src/plugins/content_management/public/components/section_input.ts
Fix content management render dashboard with duplicate visualizations
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/8605
Before
After
- fix: [workspace]fix content management render dashboard with duplicate visualizations
=> [Workspace] Fix content management render dashboard with duplicate visualizations

changelogs/fragments/8624.yml, src/plugins/content_management/public/components/section_render.tsx, src/plugins/content_management/public/plugin.ts, src/plugins/content_management/public/services/content_management/page.test.ts, src/plugins/content_management/public/services/content_management/page.ts, src/plugins/content_management/public/types.ts
1. Add a Page API to allow remove section
2. Removed an unnecessary `<OuiSpace />` if card section title is not shown
https://github.com/user-attachments/assets/ef7ecf2d-b2be-4d9d-9eae-51419cb740cd
- feat: (contentManagement) Add a Page API to allow remove section
=> feat(contentManagement): expose page API to allow remove section

changelogs/fragments/8600.yml, src/core/public/chrome/ui/header/__snapshots__/header.test.tsx.snap, src/core/public/chrome/ui/header/header.scss, src/core/public/chrome/ui/header/header.tsx
Fixes padding and responsive behavior of page header on feature pages
- Second row had incorrect right/left margin
- Title was wrapping too quickly
- Titles without breaks won’t wrap
- Noticed title wasn’t aligned vertically center
- Health/Badge isn’t aligned vertically center
- Not spacing between left/right content on larger screens
- Vertical spacing between on smaller screens is large/inconsistent due to eui responsive header behavior
Tested locally + had UX validate
- fix: Fix padding and responsive behavior of page header
=> fix: Fix padding and responsive behavior of page header

src/plugins/data/public/index.ts, src/plugins/data/public/ui/dataset_selector/dataset_selector.tsx, src/plugins/data/public/ui/dataset_selector/index.test.tsx, src/plugins/data/public/ui/dataset_selector/index.tsx, src/plugins/data/public/ui/index.ts, src/plugins/data/public/ui/query_editor/_query_editor.scss, src/plugins/data/public/ui/query_editor/query_editor.tsx, src/plugins/data_explorer/public/components/app_container.tsx, src/plugins/data_explorer/public/components/sidebar/index.tsx, src/plugins/discover/public/application/components/sidebar/lib/get_index_pattern_field_list.ts
Move DatasetSelector from data plugin queryString comp to DataExplorer
NA
NA
- skip
=> Move DatasetSelector from data plugin queryString comp to DataExplorer

changelogs/fragments/8592.yml, src/plugins/workspace/public/components/workspace_menu/workspace_menu.test.tsx, src/plugins/workspace/public/components/workspace_picker_content/workspace_picker_content.tsx, src/plugins/workspace/public/components/workspace_selector/workspace_selector.scss, src/plugins/workspace/public/components/workspace_selector/workspace_selector.test.tsx, src/plugins/workspace/public/components/workspace_selector/workspace_selector.tsx
This pr addresses following issues to the workspace selector:
1. workspace content are first sorted by most recently visited. Unvisited workspaces will be sorted alphabetically
2. workspace selector has the similar style with data source selector
3. resolve issues affecting the display of the workspace selector on mobile
the background color of the workspace selector takes euiSideNavBackgroundColor
the background color of  data source selector  takes euiHeaderBackgroundColor
1. workspace content
2. on mobile
3. In theme V7
workspace selector：
Dark mode: 
data source selector：
5. In theme V9
workspace selector：
Dark mode: 
data source selector：
6. In theme next
workspace selector：
Dark mode: 
data source selector：
- fix: workspace selector style alignment
=> [workspace]Fix workspace selector style alignment

changelogs/fragments/8614.yml, src/plugins/home/public/application/components/sample_data/sample_data_card.test.tsx, src/plugins/home/public/application/components/sample_data/sample_data_card.tsx, src/plugins/home/public/application/components/usecase_overview/search_use_case_setup.test.tsx, src/plugins/home/public/application/components/usecase_overview/search_use_case_setup.tsx, src/plugins/workspace/public/components/use_case_overview/get_started_cards.tsx, src/plugins/workspace/public/components/use_case_overview/setup_overview.scss, src/plugins/workspace/public/components/use_case_overview/setup_overview.test.tsx, src/plugins/workspace/public/components/use_case_overview/setup_overview.tsx
Updates getting started cards:
- Updates quantity to avoid having more than will fit on a page 
- Updates content to be consistent
- Updates visual design to be consistent + use new styling
Callouts:
- This requires an oui update for new icons so please hold off on merging until the next oui bump.
- This intentionally tries to use OuiCards as they are today as we haven't designed a getting started component. All changes are only for getting started card use cases, so other cards aren't impact. I did override some oui styles as that seemed like the simplest option until we're able to create a dedicated component.
N/A
essentials
search
all
observability (updated in separate pr but including here for completion)
security analytics (updated in separate pr but including here for completion) …
=> fix: Update content and styling of use case getting started cards

changelogs/fragments/8641.yml, src/plugins/home/server/services/sample_data/routes/install.test.ts, src/plugins/home/server/services/sample_data/routes/install.ts
This PR is for fixing 500 error when import sample data to a not permitted workspace. It should return a forbidden error.
```
uiSettings:
overrides:
```
- Login with admin user
- Visit internal users page and create a test-user
- Visit a existing workspace settings page and add test-user as a read-only collaborator
- Open an incognito window and login with test-user
- Goto the sample data page of the same workspace
- Click "Add data" button, it should show error like screenshot below
- …
=> [Workspace]Response forbidden error for not permitted workspace

src/plugins/workspace/public/components/workspace_form/workspace_collaborator_table.test.tsx, src/plugins/workspace/public/components/workspace_form/workspace_collaborator_table.tsx
This pr adds admin validation when changing the last administrator to a lesser access.
https://github.com/user-attachments/assets/489a23ec-8f8e-44bb-85cc-652290d51935
- feat: Add admin validation when changing the last administrator to a lesser access
=> [workspace]add admin validation when changing the last administrator to a lesser access

changelogs/fragments/8648.yml, src/plugins/saved_objects_management/public/management_section/objects_table/components/__snapshots__/duplicate_result_flyout.test.tsx.snap, src/plugins/saved_objects_management/public/management_section/objects_table/components/duplicate_result_flyout.tsx, src/plugins/saved_objects_management/public/management_section/objects_table/saved_objects_table.test.tsx, src/plugins/saved_objects_management/public/management_section/objects_table/saved_objects_table.tsx
Reproduce steps:
1. Login with admin user
2. Create a test_user
3. Assign test_user to specific workspace with Read and write permission
4. Login with test_user in another window and open assets page in specific workspace
5. Open copy assets modal select current workspace
6. Revoke "Read and write" for test_user in another window
7. Click "Copy" button in test_user window you will see screenshot like below
Error screenshot:
https://github.com/user-attachments/assets/383b2093-05f6-4b4b-b928-fee107924bce
- fix: [Workspace] Workspace assets page crashed after library_write permission revoked
=> [Workspace] Workspace assets page crashed after library_write permission revoked

changelogs/fragments/8651.yml, src/core/public/chrome/ui/header/collapsible_nav_group_enabled.scss, src/plugins/data/public/index.ts, src/plugins/data/public/ui/dataset_selector/_dataset_selector.scss, src/plugins/data/public/ui/dataset_selector/dataset_selector.tsx, src/plugins/data/public/ui/dataset_selector/index.tsx, src/plugins/data/public/ui/filter_bar/_global_filter_group.scss, src/plugins/data/public/ui/filter_bar/filter_options.tsx, src/plugins/data/public/ui/index.ts, src/plugins/data/public/ui/query_editor/_query_editor.scss, src/plugins/data/public/ui/query_editor/editors/default_editor/_default_editor.scss, src/plugins/data/public/ui/query_editor/editors/default_editor/index.tsx, src/plugins/data/public/ui/query_string_input/_query_bar.scss, src/plugins/data/public/ui/query_string_input/query_bar_top_row.tsx, src/plugins/data_explorer/public/components/app_container.scss, src/plugins/data_explorer/public/components/sidebar/index.scss, src/plugins/data_explorer/public/components/sidebar/index.tsx, src/plugins/discover/public/application/components/chart/_histogram.scss, src/plugins/discover/public/application/components/chart/timechart_header/timechart_header.tsx, src/plugins/discover/public/application/components/default_discover_table/_table_cell.scss, src/plugins/discover/public/application/components/default_discover_table/_table_header.scss, src/plugins/discover/public/application/components/sidebar/discover_field_search.tsx, src/plugins/discover/public/application/components/sidebar/discover_sidebar.scss, src/plugins/discover/public/application/components/sidebar/discover_sidebar.tsx, src/plugins/discover/public/application/view_components/canvas/discover_canvas.scss, src/plugins/discover/public/application/view_components/canvas/index.tsx, src/plugins/navigation/public/top_nav_menu/_index.scss
Update Discover appearance
| ![old l](https://github.com/user-attachments/assets/4d7ab708-12ae-40f9-8b83-0ad4f1c8eabc) | ![old p](https://github.com/user-attachments/assets/c2becba6-3f31-45a3-a752-5fdba22ec1cc) |
|---|---|
| ![new l](https://github.com/user-attachments/assets/8047b416-f90c-41c7-83d4-7f1086b7ca9c) | ![new p](https://github.com/user-attachments/assets/03c35402-bacf-43f3-b004-815bd717e58d) |
|---|---|
| `query:enhancements:enabled: false` | `home:useNewHomePage: false` |
|---|---|
| ![no enh](https://github.com/user-attachments/assets/78c6d096-b3df-4fe4-8b97-ca07f9aafb04) | ![legacy](https://github.com/user-attachments/assets/ddd13fc1-fcf3-4b6d-90c5-f0dfdf46c67e) |
|---|---|
|  ![new pd](https://github.com/user-attachments/assets/ac0ad3f3-edee-43bc-a8c4-e1f3466d9a9e) |---| …
=> Update Discover appearance

changelogs/fragments/8555.yml, src/plugins/data/common/utils/helpers.ts
This PR refactors the polling logic for async search in Discover to poll for the query status once the current call resolves. 
Currently we fire a polling request every 5 seconds irrespective of whether the previous status check call completed or not.
This will ensure we make fewer polling calls
N/A
Tested using local setup
- fix: Refactored polling logic to poll for results once current request completes
=> [Async search Discover] Poll for results when current request completes

src/plugins/data/common/index_patterns/index_patterns/ensure_default_index_pattern.ts, src/plugins/data/public/index.ts, src/plugins/data/public/query/query_string/dataset_service/dataset_service.ts, src/plugins/data/public/ui/_common.scss, src/plugins/data/public/ui/_index.scss, src/plugins/data/public/ui/dataset_selector/advanced_selector.tsx, src/plugins/data/public/ui/dataset_selector/configurator.tsx, src/plugins/data/public/ui/dataset_selector/dataset_selector.tsx, src/plugins/data/public/ui/dataset_selector/index.test.tsx, src/plugins/data/public/ui/dataset_selector/index.tsx, src/plugins/data/public/ui/index.ts, src/plugins/data/public/ui/no_index_patterns/index.ts, src/plugins/data/public/ui/no_index_patterns/no_index_patterns_panel.tsx, src/plugins/data_explorer/public/components/sidebar/index.tsx, src/plugins/data_explorer/public/index.ts, src/plugins/data_explorer/public/utils/state_management/metadata_slice.ts, src/plugins/data_explorer/public/utils/state_management/redux_persistence.test.tsx, src/plugins/data_explorer/public/utils/state_management/store.ts, src/plugins/discover/public/application/components/top_nav/get_top_nav_links.tsx, src/plugins/discover/public/application/view_components/canvas/index.tsx, src/plugins/discover/public/application/view_components/canvas/top_nav.tsx, src/plugins/index_pattern_management/public/components/edit_index_pattern/edit_index_pattern.tsx
This PR primarily addresses the scenario when no index patterns (general) is available in the Discover view.
Instead of redirecting users to the index management page, it introduces a new "No Index Patterns" panel.
This panel provides users with the option to open a data selector and add index patterns
directly from the Discover view, improving the user experience for new or empty deployments.
To achieve, we move the selectedDataset state from ConnectedDatasetSelector to the app container's
state management. This allows the AdvancedSelector, opened from the AppContainer, to update
the dataset state effectively. Key changes include:
* Implementing NoIndexPatternsPanel and AdvancedSelector components.
* Refactoring dataset state management in AppContainer and Sidebar.
* Modifying …
=> Improve Empty State Handling: Add No Index Patterns Panel with Data Selection in Discover View

changelogs/fragments/8616.yml, src/plugins/data/public/query/query_string/dataset_service/lib/index_pattern_type.ts, src/plugins/data/public/query/query_string/dataset_service/lib/index_type.ts, src/plugins/data/public/query/query_string/dataset_service/types.ts, src/plugins/data/public/query/query_string/language_service/lib/dql_language.ts, src/plugins/data/public/query/query_string/language_service/lib/lucene_language.ts, src/plugins/data/public/query/query_string/language_service/types.ts, src/plugins/data/public/ui/_common.scss, src/plugins/discover/public/application/components/no_results/no_results.scss, src/plugins/discover/public/application/components/no_results/no_results.tsx, src/plugins/discover/public/application/view_components/canvas/index.tsx, src/plugins/query_enhancements/public/datasets/s3_type.ts, src/plugins/query_enhancements/public/plugin.tsx
* Adds support for dataset types to return a list of sample queries
* Update Discover no results page to display listed sample queries and saved queries
- feat: Adds sample queries and saved queries to Discover no results page
=> [Discover]Sample Queries and Saved Queries in No Results Page

changelogs/fragments/8659.yml, src/plugins/discover/public/application/view_components/utils/use_index_pattern.ts
When using Discover with query enhancement enabled, deleting an index pattern from Index Management does not properly update the "Recently selected data" list in Discover. This causes the UI to become stuck in a "Searching" state when attempting to use Discover after deleting an index pattern.
Handle the error case where the use index patterns hook caught error when enhancements was enabled.
Now it goes to the next available index pattern
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/8612
re-creation steps in issue
- fix: Discover UI stuck on searching after failing to find deleted index pattern
=> [bug] Discover UI stuck on searching after deleting index pattern

src/plugins/data/public/ui/filter_bar/filter_options.tsx, src/plugins/data/public/ui/query_editor/__snapshots__/language_selector.test.tsx.snap, src/plugins/data/public/ui/query_editor/editors/default_editor/index.tsx, src/plugins/data/public/ui/query_editor/language_selector.tsx, src/plugins/data/public/ui/search_bar/search_bar.tsx, src/plugins/discover/public/application/components/no_index_patterns/no_index_patterns.scss, src/plugins/discover/public/application/view_components/canvas/index.tsx, src/plugins/discover/public/application/view_components/canvas/top_nav.tsx
Post https://github.com/opensearch-project/OpenSearch-Dashboards/pull/8665
Fix No data selected appearance
Also:
* Fix some React errors
- skip
=> Fix No data selected appearance

changelogs/fragments/8674.yml, src/plugins/data/public/query/query_string/query_string_manager.ts
The issue happens when for example PPL is selected in discover, then navigate to visualization create page, a warning toast is displayed, see screenshot.
When saving the visualization, the `language: "PPL"` is stored, though the current UI shows DQL is used, see screenshot
It will only use the cached language selection from localStorage if the current app supports the language.
- fix: fixed unsupported language is used from localStorage
=> fix: fixed unsupported language issue due to cached language in localStorage

changelogs/fragments/8685.yml, src/plugins/data/public/ui/query_editor/language_selector.tsx
Optimize the language selector preventing too many renders and potentially setting of the language triggering an update.
n/a
- fix: Optimize rendering the Discover language options
=> [discover] optimize rendering language options

changelogs/fragments/8565.yml, src/plugins/data/common/data_frames/types.ts, src/plugins/data/common/utils/helpers.ts, src/plugins/data/public/query/query_string/language_service/lib/__snapshots__/query_result.test.tsx.snap, src/plugins/data/public/query/query_string/language_service/lib/_recent_query.scss, src/plugins/data/public/query/query_string/language_service/lib/query_result.tsx, src/plugins/data/public/ui/query_editor/_query_editor.scss, src/plugins/data/public/ui/query_editor/editors/shared.tsx, src/plugins/data/public/ui/query_editor/query_editor.tsx, src/plugins/discover/public/application/view_components/utils/use_search.ts, src/plugins/query_enhancements/common/index.ts, src/plugins/query_enhancements/server/routes/index.ts, src/plugins/query_enhancements/server/search/sql_async_search_strategy.ts
* Adds footer bar in multiline editor to single line editor when editor is focused
* Fixes query result component not displaying errors
* Correctly surfaces errors from async search strategy
- feat: Adds editor footer to single line editor on focus
=> [Discover] Add Footer Bar for Single Line Editor

src/plugins/data/common/search/search_source/create_search_source.ts, src/plugins/data/public/index.ts, src/plugins/discover/public/application/utils/state_management/discover_slice.tsx, src/plugins/discover/public/application/view_components/utils/use_search.ts, src/plugins/query_enhancements/public/plugin.tsx
Preventing any errors being thrown because of the index pattern not existing in the case of saved search was created with a dataset.
Also fix issue that prevented saved search instance not being set even though loaded properly.
The original fix that was removed fixed a previous issue but subsequent updates and refactors required an update that was uncaught.
n/a
* verified saved search is loading for PPL
* verified reload working for  non index pattern
* verified short url working for non index pattern
* verified copy url working for non index pattern 
- skip
=> [bug] set saved search instance for Discover based on dataset

changelogs/fragments/8693.yml, src/plugins/home/server/services/sample_data/data_sets/otel/index.ts
Update otel sample data description
Currently OTEL sample data works only with OS 2.13+ domains, this text adds a line for users to mention the compatible domains. Long term: We'll remove this description warning and make the sample data compatible with all the OS versions. 
- fix: Update OTEL sample data description with compatible OS version
=> [Sample data] Update otel sample data description

src/plugins/data/public/query/query_string/language_service/lib/__snapshots__/query_result.test.tsx.snap
Adds a missing snapshot from #8565. No need for a backport, the manual backport #8691 includes the change.
- skip
=> [CI] Adding Missing Snapshot for `query_result.test.tsx`

changelogs/fragments/8565.yml, src/plugins/data/common/data_frames/types.ts, src/plugins/data/common/utils/helpers.ts, src/plugins/data/public/query/query_string/language_service/lib/__snapshots__/query_result.test.tsx.snap, src/plugins/data/public/query/query_string/language_service/lib/_recent_query.scss, src/plugins/data/public/query/query_string/language_service/lib/query_result.tsx, src/plugins/data/public/ui/query_editor/_query_editor.scss, src/plugins/data/public/ui/query_editor/editors/shared.tsx, src/plugins/data/public/ui/query_editor/query_editor.tsx, src/plugins/discover/public/application/view_components/utils/use_search.ts, src/plugins/query_enhancements/server/routes/index.ts, src/plugins/query_enhancements/server/search/sql_async_search_strategy.ts
https://github.com/opensearch-project/OpenSearch-Dashboards/pull/8565
* initial commit for single line editor footer
* fixing styling and functionality
* Changeset file for PR #8565 created/updated
* fixing bug with error not showing up in footer
* fixing loading state thanks ashwinpc
* trying to surface errors
* adding new error for error state
* Revert "fixing loading state thanks ashwinpc"
This reverts commit 64b5969954a8419dce4c1ccc111147336df7e37b.
* correctly passing async search strat errors
=> [2.x-manual-backport][Discover] Add Footer Bar for Single Line Editor (#8565)

changelogs/fragments/8469.yml, config/opensearch_dashboards.yml, src/plugins/data/config.ts, src/plugins/data/public/plugin.ts, src/plugins/data/public/query/query_service.ts, src/plugins/data/public/query/saved_query/saved_query_service.test.ts, src/plugins/data/public/query/saved_query/saved_query_service.ts, src/plugins/data/public/query/saved_query/types.ts, src/plugins/data/public/services.ts, src/plugins/data/public/ui/_index.scss, src/plugins/data/public/ui/filter_bar/filter_options.tsx, src/plugins/data/public/ui/saved_query_flyouts/open_saved_query_flyout.tsx, src/plugins/data/public/ui/saved_query_flyouts/save_query_flyout.tsx, src/plugins/data/public/ui/saved_query_flyouts/saved_query_card.tsx, src/plugins/data/public/ui/saved_query_flyouts/saved_query_flyouts.scss, src/plugins/data/public/ui/saved_query_form/helpers.tsx, src/plugins/data/public/ui/saved_query_form/index.ts, src/plugins/data/public/ui/saved_query_form/save_query_form.tsx, src/plugins/data/public/ui/saved_query_management/delete_saved_query_confirmation_modal.tsx, src/plugins/data/public/ui/saved_query_management/saved_query_list_item.tsx, src/plugins/data/public/ui/saved_query_management/saved_query_management_component.test.tsx, src/plugins/data/public/ui/saved_query_management/saved_query_management_component.tsx, src/plugins/data/public/ui/search_bar/search_bar.tsx, src/plugins/data/server/index.ts, src/plugins/data/server/saved_objects/query.ts
=> [Backport 2.x] Saved queries new UI (#8469)

changelogs/fragments/8709.yml, src/core/server/index.ts, src/plugins/share/server/routes/goto.ts
This PR is to fix the issue that short url `goto` router is not supporting workspace.
https://github.com/user-attachments/assets/4d6a47d9-963c-4478-95c7-c1206db9c461
https://github.com/user-attachments/assets/a1696eaf-f2d7-487b-aca9-89b5e972963d
Please follow the step shown in the video.
- fix: make goto router support workspace
=> [workspace]fix: make goto router support workspace

changelogs/fragments/8708.yml, src/core/public/doc_links/doc_links_service.ts, src/plugins/advanced_settings/public/management_app/__snapshots__/advanced_settings.test.tsx.snap, src/plugins/dashboard/public/application/components/dashboard_top_nav/__snapshots__/dashboard_top_nav.test.tsx.snap, src/plugins/data/public/query/query_string/language_service/lib/language_reference.test.tsx, src/plugins/data/public/query/query_string/language_service/lib/language_reference.tsx, src/plugins/data/public/ui/query_editor/__snapshots__/language_selector.test.tsx.snap, src/plugins/query_enhancements/public/plugin.tsx, src/plugins/query_enhancements/public/query_editor_extensions/ppl_language_reference.tsx, src/plugins/query_enhancements/public/query_editor_extensions/sql_language_reference.tsx
- Modify the search bar info box content for sql/ppl
- The info box will only show up when it is user's first time to select SQL/PPL
- Change the language picker's title from "SQL" into "OpenSearch SQL" 
* Relate https://github.com/opensearch-project/OpenSearch-Dashboards/pull/8702
* we can close the above since this PR reflects the new design from UIUX
Version Final:
https://github.com/user-attachments/assets/5a34c5a6-0504-4771-a949-f1bb00bf0d3a
- fix: [Discover] Modify the search bar info box content for sql/ppl #8708
=> [Discover] Modify the search bar info box content for sql/ppl

changelogs/fragments/8713.yml, config/opensearch_dashboards.yml, src/plugins/data/public/autocomplete/providers/value_suggestion_provider.ts, src/plugins/data/server/autocomplete/value_suggestions_route.ts
Value suggestion api did not have the MDS support added that in the api
=> [Enhancement] Update auto-complete-api-with-mds

changelogs/fragments/8719.yml, src/core/server/index.ts, src/plugins/share/public/services/share_menu_manager.tsx, src/plugins/share/server/routes/lib/short_url_assert_valid.test.ts, src/plugins/share/server/routes/lib/short_url_assert_valid.ts
This PR is to fix the issue that short url `goto` router is not supporting workspace.
https://github.com/user-attachments/assets/4d6a47d9-963c-4478-95c7-c1206db9c461
https://github.com/user-attachments/assets/a1696eaf-f2d7-487b-aca9-89b5e972963d
- fix: generate short url with workspace info
=> fix: generate short url with workspace info

src/plugins/query_enhancements/server/routes/data_source_connection/routes.ts
Update connections API error handling to use 503 for service unavailability. Previously, the API would return 500 Internal Server Error for cases like "No Living connections", which could be misleading to clients. Now it returns 503 Service Unavailable, which more accurately represents the nature of the failure.
NA
NA
- skip
=> Update connections API error handling to use 503 for service unavailability

changelogs/fragments/8680.yml, src/plugins/workspace/public/components/workspace_form/workspace_collaborator_table.tsx
Update change access modal display name from access level value to access level name
Before
After
Go to workspace collaborators page.
- refactor: Update change access modal display name
=> [Workspace] Refactor: update change access modal display name

changelogs/fragments/8712.yml, src/plugins/data/public/query/query_string/language_service/language_service.ts, src/plugins/data/public/query/query_string/query_string_manager.test.ts, src/plugins/data/public/query/query_string/query_string_manager.ts, src/plugins/data/public/ui/dataset_selector/advanced_selector.tsx, src/plugins/data/public/ui/dataset_selector/configurator.tsx, src/plugins/data/public/ui/dataset_selector/dataset_selector.test.tsx, src/plugins/data/public/ui/dataset_selector/dataset_selector.tsx, src/plugins/data/public/ui/dataset_selector/index.test.tsx, src/plugins/data/public/ui/dataset_selector/index.tsx, src/plugins/data/public/ui/query_editor/__snapshots__/language_selector.test.tsx.snap, src/plugins/data/public/ui/query_editor/language_selector.test.tsx, src/plugins/data/public/ui/query_editor/language_selector.tsx, src/plugins/data/public/ui/query_editor/query_editor.tsx
* Makes the query editor a React functional component which helps with state
* Update language selector to not rely on a props.query to force re-render relying on observers
* Update dataset selector to update the language and dataset instead of just updating the dataset and then the dataset eventually triggering the now removed props.query for the language selector to update intime.
* update recent dataset on query update
n/a
- refactor: [discover] query editor and language selector state fixes
=> [discover] query editor and language selector state fixes

changelogs/fragments/8707.yml, src/plugins/discover/public/application/view_components/utils/use_search.ts
Saved query workflow 
```
useSavedQuery → populateStateFromSavedQuery with new saved query → queryString.setQuery(new saved query)
useSavedQuery → populateStateFromSavedQuery with new saved query → filterManager.setFilters(new saved query)
```
Then they are clean out in use_search
```
useEffect(() => {
(async () => {
const savedSearchInstance = await getSavedSearchById(savedSearchId);
const query =
savedSearchInstance.searchSource.getField('query') ||
data.query.queryString.getDefaultQuery();
const isEnhancementsEnabled = await uiSettings.get('query:enhancements:enabled');
if (isEnhancementsEnabled && query.dataset) {
let pattern = await data.indexPatterns.get(
query.dataset.id,
query.dataset.type !== 'INDEX_PATTERN'
);
if (!pattern) {
await …
```
=> [BUG][Discover] Ensure save query loaded properly from asset

changelogs/fragments/8724.yml, src/plugins/data/public/query/saved_query/saved_query_service.ts, src/plugins/query_enhancements/public/search/ppl_search_interceptor.ts
This PR fixes two issues:
1. Passes required params when polling for PPL results
2. Saves dataset in saved query when query enhancements is enabled
- fix: Polling for PPL results; Saved dataset to saved queries
=> fixed ppl polling; save dataset in saved queries

changelogs/fragments/8743.yml, src/plugins/query_enhancements/common/utils.ts, src/plugins/query_enhancements/server/search/ppl_search_strategy.ts, src/plugins/query_enhancements/server/utils/facet.ts
In query enhancements facet, the fetch errors are caught and returned as 
```js
{ success: false, data: Error }
```
https://github.com/opensearch-project/OpenSearch-Dashboards/blob/c66b698360ee57db1e88d955d5cdb50f00af27aa/src/plugins/query_enhancements/server/utils/facet.ts#L90-L96
https://github.com/opensearch-project/OpenSearch-Dashboards/blob/c66b698360ee57db1e88d955d5cdb50f00af27aa/src/plugins/query_enhancements/server/utils/facet.ts#L64-L70
But `describeQuery` is not checking if success is true, and will process the Error object as `IPPLEventsDataSource` or `IPPLVisualizationDataSource`, causing internal server error.
https://github.com/opensearch-project/OpenSearch-Dashboards/blob/c66b698360ee57db1e88d955d5cdb50f00af27aa/src/plugins/query_enhancements/server/utils/facet.ts#L107-L108 …
=> [Discover] fix error handling in query enhancement facet

changelogs/fragments/8755.yml, src/plugins/discover/public/application/components/default_discover_table/_table_cell.scss
Prevent wrapping of time fields which causes an overlap when languages are changed in the query editor.
Note: Discover still needs to allow triggering a re-render for a better solution.
https://github.com/user-attachments/assets/2e90c92c-6a62-4bdc-8b38-0687b12861ba
https://github.com/user-attachments/assets/7b9ce339-b06a-4c37-9f2e-fe9dfe29a186
- fix: Fix time field wrapping overlap on language change in Discover table
=> [Discover] Prevent wrapping of time fields

src/plugins/data/public/query/query_string/query_history.ts, src/plugins/data/public/query/query_string/query_string_manager.ts
This is a backport PR for https://github.com/opensearch-project/OpenSearch-Dashboards/pull/8733
The original PR is a follow up fix for the comment: https://github.com/opensearch-project/OpenSearch-Dashboards/pull/8723#discussion_r1819916999
NA
- skip
=> [2.x Manual Backport] Follow up on 8723 comment (#8733)

changelogs/fragments/8742.yml, yarn.lock
[CVE-2024-48948] Bump `elliptic` from 6.5.7 to 6.6.0
NOTE: While this is categorized as a low severity security-wise, the annoyance it could cause administrators of OSD might be big.
- security: [CVE-2024-48948] Bump `elliptic` from 6.5.7 to 6.6.0
=> [CVE-2024-48948] Bump `elliptic` from 6.5.7 to 6.6.0

changelogs/fragments/8708.yml, src/core/public/doc_links/doc_links_service.ts, src/plugins/advanced_settings/public/management_app/__snapshots__/advanced_settings.test.tsx.snap, src/plugins/dashboard/public/application/components/dashboard_top_nav/__snapshots__/dashboard_top_nav.test.tsx.snap, src/plugins/data/public/query/query_string/language_service/lib/language_reference.test.tsx, src/plugins/data/public/query/query_string/language_service/lib/language_reference.tsx, src/plugins/data/public/ui/query_editor/__snapshots__/language_selector.test.tsx.snap, src/plugins/query_enhancements/public/plugin.tsx, src/plugins/query_enhancements/public/query_editor_extensions/ppl_language_reference.tsx, src/plugins/query_enhancements/public/query_editor_extensions/sql_language_reference.tsx
Manual backport: [Discover] Modify the search bar info box content for sql/ppl
* Relate #8708 
* Close #8715
=> [Manual Backport 2.x][Discover] Modify the search bar info box content for sql/ppl

src/plugins/query_enhancements/server/routes/data_source_connection/routes.ts, src/plugins/query_enhancements/server/search/sql_async_search_strategy.ts, src/plugins/query_enhancements/server/search/sql_search_strategy.test.ts, src/plugins/query_enhancements/server/search/sql_search_strategy.ts, src/plugins/query_enhancements/server/utils/facet.test.ts
This is a followup PR for https://github.com/opensearch-project/OpenSearch-Dashboards/pull/8743 and https://github.com/opensearch-project/OpenSearch-Dashboards/pull/8725. There are more APIs not correctly handling errors and throws the default 500 internal server error code, and this PR fixes `/api/enhancements/jobs` and SQL search strategy to throw the correct error
- skip
=> [Discover] fix error handling for sql and jobs APIs

src/plugins/data/public/query/query_string/dataset_service/lib/index_type.ts, src/plugins/query_enhancements/public/datasets/s3_type.test.ts, src/plugins/query_enhancements/public/datasets/s3_type.ts
Filters out OpenSearch Serverless Collections after fetching data sources
- skip
=> [Discover] Filter out OpenSearch Serverless Collections

changelogs/fragments/8771.yml, src/plugins/query_enhancements/server/search/ppl_async_search_strategy.ts
This PR is a follow up on https://github.com/opensearch-project/OpenSearch-Dashboards/pull/8706 based on error handling updates for SQL async jobs API https://github.com/opensearch-project/OpenSearch-Dashboards/pull/8765
- fix: Fix error handling for ppl jobs API
=> [Discover] Fix error handling for ppl jobs API

changelogs/fragments/8706.yml, src/plugins/query_enhancements/common/constants.ts, src/plugins/query_enhancements/public/datasets/s3_type.test.ts, src/plugins/query_enhancements/public/datasets/s3_type.ts, src/plugins/query_enhancements/public/plugin.tsx, src/plugins/query_enhancements/public/search/ppl_search_interceptor.ts, src/plugins/query_enhancements/public/search/sql_search_interceptor.ts, src/plugins/query_enhancements/server/plugin.ts, src/plugins/query_enhancements/server/routes/data_source_connection/routes.ts, src/plugins/query_enhancements/server/search/index.ts, src/plugins/query_enhancements/server/search/ppl_async_search_strategy.ts
Backport PR:
https://github.com/opensearch-project/OpenSearch-Dashboards/pull/8706
From original PR:
* add support for async ppl to discover
* Changeset file for PR #8706 created/updated
* update s3_type test to add PPL as supported lang
* fix lint error
---------
=> [Manual backport 2.x] Add support for async ppl to discover (#8706)

CHANGELOG.md, package.json
Increment version to 1.3.20
Part of 1.3.20 release
=> Increment version to 1.3.20

changelogs/fragments/8771.yml, src/plugins/query_enhancements/server/search/ppl_async_search_strategy.ts
Backport PR:
https://github.com/opensearch-project/OpenSearch-Dashboards/pull/8771
From 8771:
* fix error handling for ppl jobs API
=> [2.x-manual-bp][Discover] Fix error handling for ppl jobs API (#8771)

src/plugins/data/public/query/query_string/dataset_service/lib/index_type.ts, src/plugins/query_enhancements/public/datasets/s3_type.test.ts, src/plugins/query_enhancements/public/datasets/s3_type.ts
Removes default cluster from index and S3 dataset types cluster lists
- skip
=> [Discover] Remove Default Cluster 

changelogs/fragments/8783.yml, src/core/public/chrome/chrome_service.test.ts, src/core/public/chrome/chrome_service.tsx
Fix staled closure issue inside chrome_service. The staled closure is toggling the chrome from visible to unvisible and visible in a short time and it makes the page header remount multiple times.
https://github.com/user-attachments/assets/59ebc932-0157-47fa-859b-fcdfa4fd7359
https://github.com/user-attachments/assets/3cc608bd-0427-4623-af6a-462816514754
- fix: staled closure inside chrome_service
=> fix: staled closure inside chrome_service

changelogs/fragments/8781.yml, src/plugins/query_enhancements/server/search/ppl_async_search_strategy.ts, src/plugins/query_enhancements/server/search/sql_async_search_strategy.ts
Update async search response type
This is a fast followup PR for https://github.com/opensearch-project/OpenSearch-Dashboards/pull/8777 based on the comment https://github.com/opensearch-project/OpenSearch-Dashboards/pull/8777#discussion_r1824956184. Adds a type check on response of jobs API in async search strategies. 
- fix: Update async search response type
=> [Discover] Update async search response type

src/plugins/data/public/query/query_string/dataset_service/lib/index_type.test.ts, src/plugins/data/public/query/query_string/dataset_service/lib/index_type.ts, src/plugins/query_enhancements/public/datasets/s3_type.test.ts, src/plugins/query_enhancements/public/datasets/s3_type.ts
* Uses `semver` to filter out data sources with invalid versions or versions that are lower than `1.0.0`.
* Adding tests for `index_type.ts`
- skip
=> [Discover] Update Version Filter for Data Sources

.github/workflows/cypress_workflow.yml, package.json, src/plugins/data/public/ui/dataset_selector/configurator.tsx, src/plugins/data/public/ui/dataset_selector/dataset_selector.tsx
Add query enhancement cypress tests workflow to github CI to test discover 2.0 functionalities: 
- sql, ppl queries
- dataset selector
- ...
The tests can be added under folder `cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/query_enhancement` in the functional repo, and will be run in ciGroup10 in the CI.
- feat: Add query enhancement cypress tests to Github CI
=> Add query enhancement cypress tests to Github CI

changelogs/fragments/8799.yml, src/plugins/data/public/query/query_string/dataset_service/dataset_service.test.ts, src/plugins/data/public/query/query_string/dataset_service/dataset_service.ts, src/plugins/data/public/query/query_string/dataset_service/types.ts, src/plugins/query_enhancements/public/datasets/s3_type.ts, src/plugins/query_enhancements/public/query_assist/utils/create_extension.test.tsx, src/plugins/query_enhancements/public/query_assist/utils/create_extension.tsx
Makes caching dataset options optional. Enables it only for s3 since its metadtata calls are slower.
Additinal fix: When caching was no longer optional, qury assist api calls held the Clusters menu in a perpetual loading state causing the menu to not load. This fixes that by timing out only the is enabled queries to not prevent that menu from loading.
See unit test.
Or for Manual testing:
- Open Discover
- Open the advanced data selector
- Select index patterns, the menu shoud always fire a network request
- Select Indices, the menu should always fire a network request
- Select S3, the menu should only fire the query oince
- fix: [Discover] Makes cachign dataset options optional and configurable by the dataset type
=> [Discover] Makes caching dataset options optional

changelogs/fragments/8803.yml, src/plugins/data/public/ui/query_editor/query_editor.tsx
The Query editor and similarly auto complete use the query state to corretcly query the Datasource. However the query state value used by different parts of the editor UI are out of sync. This PR clearly demarcates which instance of the query you are using and calls out why that is the rught query object to reference.
It also addresses a quirk of monaco which after initialization does not use the latest value of the query object resulting in incorrect  values being used for language and dataset. This is fixed by using useRef to store a referenc of the object that the monaco callback can use when the shortcut commands are fired.
1. When the user is using the single line editor, they type a word and hit enter, the query clears the current value. Ths is because the monaco callback on`Enter` …
=> [Discover] Query editor state sync fixes

changelogs/fragments/8744.yml, package.json, yarn.lock
Revert back to using the official release of `vega-interpreter`
Note: Our PR was merged into their 1.0.5 release so we can stop using the patched version.
- chore: Revert back to using the official release of `vega-interpreter`
=> Revert back to using the official release of `vega-interpreter`

src/plugins/discover/public/application/components/uninitialized/uninitialized.tsx
ciGroup6 sometimes failed to find refresh data button though this element is on DOM.
I tried a different way to find the element https://github.com/opensearch-project/opensearch-dashboards-functional-test/pull/1615 but seems still flaky. Among 3 times running, see 1 failure and 2 success. Seems the ultimate robust way to fix it is to add `data-test-subj`. I also test 3 times, all success.
NA
- skip
=> [ciGroup6 fix] add data-test-subj for refresh data button in discover

src/plugins/data/public/query/query_string/dataset_service/dataset_service.test.ts, src/plugins/data/public/query/query_string/dataset_service/dataset_service.ts
With workspaces disabled, recent datasets works fine. However the dataset service does not have the concept of workspaces yet so instead of adding a new feature we are opting for recent datasets not yielding any results. The dataset selector already handles displaying or not if no recent datasets.
Follow up issue:
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/8814
n/a
locally and jest tests
- skip
=> [discover] temporarily disable recent datasets

changelogs/fragments/8827.yml, src/plugins/query_enhancements/public/datasets/s3_type.ts, src/plugins/query_enhancements/public/plugin.tsx
Remove `head 10` for PPL default query to unblock cypress test failures
- test: Remove head 10 for PPL default query to unblock cypress test failures
=> Remove `head 10` for PPL default query to unblock cypress test failures

changelogs/fragments/8137.yml, src/plugins/workspace/common/constants.ts, src/plugins/workspace/server/plugin.test.ts, src/plugins/workspace/server/plugin.ts, src/plugins/workspace/server/utils.test.ts, src/plugins/workspace/server/utils.ts
Integrate dashboard admin with dynamic config(https://github.com/opensearch-project/OpenSearch-Dashboards/pull/7194)
If you do not config users/groups, anyone will not be dashboard admin.
```
opensearchDashboards.dashboardAdmin.groups: []
opensearchDashboards.dashboardAdmin.users: []
```
If your backend role is admin, you will be dashboard admin.
```
opensearchDashboards.dashboardAdmin.groups: ["admin"]
opensearchDashboards.dashboardAdmin.users: []
```
If your login is admin, you will be dashboard admin.
```
opensearchDashboards.dashboardAdmin.groups: []
opensearchDashboards.dashboardAdmin.users: ["admin"]
```
If you do not config users as *, anyone will be dashboard admin.
```
opensearchDashboards.dashboardAdmin.groups: []
opensearchDashboards.dashboardAdmin.users: ["*"]
```
- refactor: …
=> [Workspace] Integrate dashboard admin with dynamic config

changelogs/fragments/8834.yml, src/plugins/index_pattern_management/public/components/edit_index_pattern/index_header/index_header.test.tsx, src/plugins/saved_objects_management/public/management_section/saved_objects_table_page.tsx, src/plugins/saved_objects_management/public/utils.test.ts, src/plugins/saved_objects_management/public/utils.ts
Add unit tests for inspect page url (https://github.com/opensearch-project/OpenSearch-Dashboards/pull/8718)
- refactor: [Workspace] Add unit tests for inspect page url
=> [Workspace] Add unit tests for inspect page url

changelogs/fragments/8848.yml, src/plugins/data/public/query/query_string/dataset_service/types.ts, src/plugins/data/public/ui/filter_bar/filter_options.tsx, src/plugins/data/public/ui/saved_query_flyouts/open_saved_query_flyout.test.tsx, src/plugins/data/public/ui/saved_query_flyouts/open_saved_query_flyout.tsx, src/plugins/data/public/ui/saved_query_management/saved_query_management_component.tsx, src/plugins/data/public/ui/search_bar/create_search_bar.tsx, src/plugins/data/public/ui/search_bar/search_bar.tsx, src/plugins/discover/public/application/components/no_results/no_results.tsx
- Instead of loading template queries through saved objects api, this pr changes it so that we can load template queries in through the getSampleQuery function directly
- Updates URL state when opening a saved query so datapicker state is correct
- Updates getSampleQuery interface so it can also return a promise
```
PASS  src/plugins/data/public/ui/saved_query_flyouts/open_saved_query_flyout.test.tsx
OpenSavedQueryFlyout
✓ should render the flyout with correct tabs and content (58 ms)
✓ should filter saved queries based on search input (29 ms)
✓ should select a query when clicking on it and enable the "Open query" button (14 ms)
✓ should call handleQueryDelete when deleting a query (21 ms)
✓ should handle pagination controls correctly (43 ms)
Test Suites: 1 passed, 1 total
Tests:       5 …
```
=> Fix template queries loading and update getSampleQuery interface

src/plugins/data/public/query/query_string/language_service/lib/query_result.test.tsx, src/plugins/data/public/query/query_string/language_service/lib/query_result.tsx, src/plugins/discover/public/application/view_components/canvas/index.tsx, src/plugins/discover/public/application/view_components/utils/use_search.test.tsx, src/plugins/discover/public/application/view_components/utils/use_search.ts
Duplicated code was introduced by https://github.com/opensearch-project/OpenSearch-Dashboards/pull/8565 to run the same logic regardless of `if` condition, possibly due to merge conflict? https://github.com/opensearch-project/OpenSearch-Dashboards/blob/c8278f3729cacaa6d77985adbc67920b2663877f/src/plugins/data/public/query/query_string/language_service/lib/query_result.tsx#L62-L94
It causes UI to show loading even when status is not loading. This PR fixes it
Additionally, this PR changes loading behavior to be
1. when there are no results, running the query shows loading in query editor footer and below
2. when there are results, running the query shows loading in query editor footer with previous query results
- skip
=> [Discover] Fix discover query loading state

changelogs/fragments/8857.yml, src/plugins/saved_objects_management/common/types.ts, src/plugins/saved_objects_management/public/utils.test.ts, src/plugins/saved_objects_management/public/utils.ts, src/plugins/saved_objects_management/server/lib/find_relationships.test.ts, src/plugins/saved_objects_management/server/lib/find_relationships.ts
1. When workspace and new home page are disable, clicking the inspect button will show 404 error.
2. When workspace and new home page are enabled, clicking the inspect button in the relationship page will go to the global inspect page.
After solving the issue 1, clicking inspect button will go to the inspect page
After solving the issue 2, clicking inspect button in the relationship will go to the workspace inspect page.
- fix: [Workspace][Bug] Fix inspect page url error.
=> [Workspace][Bug] Fix inspect page url error

changelogs/fragments/8867.yml, src/plugins/data/public/query/query_string/language_service/lib/__snapshots__/query_result.test.tsx.snap, src/plugins/data/public/query/query_string/language_service/lib/query_result.tsx
If an error message is too long, the message body overflows. PR adds a max height and a scroll wheel to error message body.
https://github.com/user-attachments/assets/aed34dec-aee7-41f4-bba0-a1c2f474b0ba
- fix: Add max height and scroll to error message body
=> [Discover] Add max height and scroll to error message body

changelogs/fragments/8863.yml, src/plugins/discover/public/application/view_components/canvas/index.tsx
Currently, an error query will display no result.
This PR change to keep previous query result if current query result in error.
If the query result in error, it will keep the previous query result without updating the canvas
https://github.com/user-attachments/assets/f72b8a74-ad71-4261-8493-fc5e3b24a74b
If the first query result in error, it will show the refresh data screen. 
https://github.com/user-attachments/assets/3bb6aa48-5707-4ba3-8044-954b02d41d79
- fix: Keep previous query result if current query result in error
=> Keep previous query result if current query result in error

changelogs/fragments/8839.yml, packages/osd-std/src/json.test.ts, packages/osd-std/src/json.ts, scripts/postinstall.js
Fix a typo while inspecting values for large numerals in OSD and the JS client
Note:
Since JS client 2.x has breaking changes, we cannot adopt it immediately and cannot wait for it to be fixed; hence the client is patched with the commit.
- fix: Fix a typo while inspecting values for large numerals in OSD and the JS client
=> Fix a typo while inspecting values for large numerals in OSD and the JS client

changelogs/fragments/8871.yml, src/plugins/discover/public/application/view_components/utils/use_search.test.tsx, src/plugins/discover/public/application/view_components/utils/use_search.ts
Required a double click on search and then also potentially loading issue.
n/a
Unit tests. Also was able to recreate the bug. Switch the index pattern type config to not search on page load then switch off settings. I was able to run into the bug that required me to click twice to actually get results
- fix: Search on page load out of sync state when clicking submit.
=> [Discover] Dataset search on page load issues

changelogs/fragments/8866.yml, src/plugins/data/public/query/query_string/language_service/language_service.mock.ts, src/plugins/data/public/ui/query_editor/query_editor_top_row.test.tsx, src/plugins/data/public/ui/query_editor/query_editor_top_row.tsx
Hides date picker in situations where it is unsupported (when using languages/dataset types that explicitly say that it's not supported)
https://github.com/user-attachments/assets/b33de83b-cfda-4016-9616-766ffc285df1
- fix: Hide Date Picker for Unsupported Types
=> [Discover] Hide Date Picker For Unsupported Types

src/dev/generate_release_note.ts
Currently, the release note generation script (`scripts/generate_release_note`) fails entirely if any single changelog fragment has invalid formatting or YAML syntax errors. This causes the entire process to abort, preventing the generation of release notes even when most fragments are valid.
For example, if a fragment has incorrect YAML indentation:
```yaml
feat:
- "[navigation] Adjust the appearances..." # incorrect indentation
```
This PR modifies the release note generation script to:
* continue processing when encountering invalid fragments instead of aborting
* add error handling around file reading, fragment validation, and YAML parsing
* report failed fragments with detailed error messages
The changes make the script more resilient while maintaining strict validation rules. …
=> [Bug] Make release note generation more resilient by gracefully handling invalid changelog fragments

src/plugins/data/public/ui/filter_bar/filter_options.tsx, src/plugins/data/public/ui/saved_query_flyouts/open_saved_query_flyout.test.tsx, src/plugins/data/public/ui/saved_query_flyouts/open_saved_query_flyout.tsx, src/plugins/data/public/ui/saved_query_management/saved_query_management_component.tsx, src/plugins/data/public/ui/search_bar/create_search_bar.tsx, src/plugins/data/public/ui/search_bar/search_bar.tsx
1. Addressed comment https://github.com/opensearch-project/OpenSearch-Dashboards/pull/8848#discussion_r1840286560
2. Added try/catch block.
- skip
=> Adjusted source of QueryStringManager functions for flyout.

.github/workflows/build_and_test_workflow.yml, .github/workflows/cypress_workflow.yml, .github/workflows/release_cypress_workflow.yml, changelogs/fragments/8855.yml
actions/upload-artifact@v3 is scheduled for deprecation on November 30, 2024, upgrade it to v4.
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/8823
- fix: upgrade actions/upload-artifact to v4
=> [chore]upgrade actions/upload-artifact to v4

changelogs/fragments/8883.yml, src/plugins/data/public/ui/saved_query_flyouts/open_saved_query_flyout.tsx, src/plugins/data/public/ui/saved_query_flyouts/save_query_flyout.tsx, src/plugins/data/public/ui/saved_query_form/helpers.tsx, src/plugins/data/public/ui/saved_query_form/save_query_form.tsx, src/plugins/data/public/ui/search_bar/lib/populate_state_from_saved_query.test.ts, src/plugins/data/public/ui/search_bar/lib/populate_state_from_saved_query.ts, src/plugins/data/public/ui/search_bar/search_bar.tsx
Opening a saved query that has no dataset stored with it, resets the currently selected dataset in the picker which breaks the query experience since the user will need to reselect the dataset which will then reset the query.
This PR adds a check for this case and retains the currently selected dataset
Tested using local setup
https://github.com/user-attachments/assets/0637bb93-5db6-40d5-82bd-ad31ae917b62
- fix: Retain currently selected dataset when opening saved query without dataset info
=> Use currently selected data source when no source attached to saved query

changelogs/fragments/8896.yml, src/plugins/data/public/query/query_string/dataset_service/types.ts, src/plugins/data/public/query/query_string/query_string_manager.test.ts, src/plugins/data/public/query/query_string/query_string_manager.ts
This PR adds framework to get the default query for a dataset and language combination from the dataset. If not provided we fallback to the defaults from the language service for each language.
Tested using local setup
- feat: Added framework to get default query string using dataset and language combination
=> Added framework to get default query string using dataset and language combination

changelogs/fragments/8899.yml, src/plugins/data/public/ui/saved_query_flyouts/open_saved_query_flyout.tsx, src/plugins/data/public/ui/saved_query_management/saved_query_management_component.tsx
For query templates we don't want to run them when they load because they need user input to be valid. Currently Discover does not support a good way to avoid running the query on load.
To avoid this, this PR only lets the user copy the query, which can then be pastes into the Discover editor for modification before running them.
https://github.com/user-attachments/assets/52508d7a-a9fd-4c8e-b4d0-1c3bc0f159c4
Tested changes locally
- fix: Only support copy action for query templates
=> Only support copy for query templates

.github/workflows/cypress_workflow.yml, package.json, src/plugins/data/public/ui/dataset_selector/configurator.tsx, src/plugins/data/public/ui/dataset_selector/dataset_selector.tsx
Manual backport of https://github.com/opensearch-project/OpenSearch-Dashboards/pull/8703
=> [Manual backport 2.x] Add query enhancement cypress tests to Github CI (#8703)

changelogs/fragments/8872.yml, src/plugins/data/public/query/query_string/dataset_service/lib/index_type.test.ts, src/plugins/data/public/query/query_string/dataset_service/lib/index_type.ts, src/plugins/query_enhancements/public/datasets/s3_type.test.ts, src/plugins/query_enhancements/public/datasets/s3_type.ts
Allow extract index name for both serverless and non-serverless clusters Allow different key formats:
- datasource-id::TIMESERIES::<index-name>:0
- datasource-id::<index-name>:0
- <index-name> (non-serverless case)
NA
https://github.com/user-attachments/assets/127b851c-23db-4d65-9751-63b307332b3c
NA 
- fix: Remove filter out serverless cluster and add support to extract index name
=> Remove filter out serverless cluster and add support to extract index name

src/plugins/query_enhancements/public/datasets/s3_type.test.ts, src/plugins/query_enhancements/public/datasets/s3_type.ts
Reenable filter for s3
na
na
na
- skip
=> Reenable filter for s3

changelogs/fragments/8915.yml, src/plugins/vis_augmenter/public/plugin.ts, src/plugins/vis_augmenter/public/services.ts, src/plugins/vis_augmenter/public/utils/utils.test.ts, src/plugins/vis_augmenter/public/utils/utils.ts, src/plugins/vis_augmenter/public/view_events_flyout/actions/view_events_option_action.tsx, src/plugins/vis_type_vislib/public/line_to_expression.ts, src/plugins/visualizations/public/embeddable/visualize_embeddable.ts
Do not display if the datasource attached to the index pattern has a not compatible engine version. In this case we expect `.0` utilizing semver checking by version 1.0.0 should be sufficient to solving this problem since the data source we want to filter returns version `.0` which we first released on 1.0.0
n/a
- unit tests
- verified on machine pointing to this data source with this version number
- fix: do not support data sources with no version for vis augmenter
=> [augmenter] do not support datasources with no version

src/plugins/discover/public/application/components/default_discover_table/default_discover_table.tsx
Mitigate the incorrect layout of Discover due to a race condition between loading column definition and data.
Note: This is not a final solution and simply masks the race condition which needs to be fixed separately. Perhaps a better UX would contrast `indexOfRenderedData` with `indexPattern` and prevent the re-layout. I did not do that because its potential unknown impact on all the scenarios.
https://github.com/user-attachments/assets/3554f300-a125-4e84-a483-5dd159d8a21f
https://github.com/user-attachments/assets/f2a24f8b-3993-4ed6-b250-03d1a3f0e2d3
- fix: Fix incorrect layout of Discover due to a race condition between loading column definition and data
=> Mitigate the incorrect layout of Discover due to a race condition between loading column definition and data

changelogs/fragments/8900.yml, src/core/public/chrome/ui/header/recent_items.test.tsx, src/core/public/chrome/ui/header/recent_items.tsx
1. optimize recent items 
2. filter out items whose workspace is deleted
No UI change
1. Update internal users to emit app updaters and recent items would not send extra request
2. Filter out items whose workspace is deleted
- feat: Optimize recent items and filter out items whose workspace is deleted
=> [Workspace] feat: optimize recent items and filter out items whose workspace is deleted

changelogs/fragments/8951.yml, packages/osd-monaco/src/xjson/lexer_rules/opensearchsql.ts
Fixes SQL monaco monarch tokens by separating the states for single quoted and double quoted strings so that both can appear properly
Previously:
https://github.com/user-attachments/assets/0c38bf82-07ca-4dcf-92af-93a57481353f
Fixed:
https://github.com/user-attachments/assets/299b74d3-ca27-46d6-9098-caaaeb31af5f
- fix: SQL syntax highlighting double quotes
=> [Auto Suggest] SQL Syntax Highlighting fix

changelogs/fragments/8993.yml, cypress.config.js, cypress.config.ts, package.json
When migrating to cypress v12, we saw a small number of regressions due compilation failures in cypress. This change is to resolve this class of issue. Once resolved in this branch I'll create a PR to merge the cypress 12 upgrade in main.
**Details**
By default, cypress' internal webpack preprocessor doesn't allow imports without file extensions. This makes our life a bit hard since if any file in our testing dependency graph has an import without the .js extension our cypress build will fail.
This configuration relaxes this a bit by allowing imports without file extension
ex. import module from './module'
- fix: support imports without extensions in cypress webpack build
=> fix: support imports without extensions in cypress webpack build

changelogs/fragments/8930.yml, src/plugins/discover/public/application/view_components/utils/use_search.test.tsx, src/plugins/discover/public/application/view_components/utils/use_search.ts
Upon Discover mount (when `getSavedSearchById` is called), we were either setting the query to be the saved search, if it exists, or the default query. In this PR, I updated the logic such that we use the current query instead, which should be the single entry point that also handles the default query state.
- fix: Update saved search initialization logic to use current query instead of default query
=> [Discover] Fix Initialization if No Saved Query

src/plugins/query_enhancements/common/utils.test.ts, src/plugins/query_enhancements/common/utils.ts, src/plugins/query_enhancements/server/search/ppl_async_search_strategy.ts, src/plugins/query_enhancements/server/search/ppl_search_strategy.test.ts, src/plugins/query_enhancements/server/search/ppl_search_strategy.ts, src/plugins/query_enhancements/server/search/sql_async_search_strategy.ts, src/plugins/query_enhancements/server/search/sql_search_strategy.ts
The previous PR https://github.com/opensearch-project/OpenSearch-Dashboards/pull/8743 added `handleFacetError` if date_histogram aggregation failed, because otherwise the code will process the response as data, and calling `rawAggs.data.datarows` caused NPE. 
The problem is that some PPL queries will not have a date_histogram, for example `source = table | stats count()`, and failure is expected. So it should not throw error there. This PR changes `handleFacetError` to `continue`, and renames `handleFacetError` to `throwFacetError`.
- skip
added unit tests and locally tested
=> [Discover] fix PPL to not throw error if aggregation query fails

src/plugins/query_enhancements/server/routes/index.test.ts, src/plugins/query_enhancements/server/routes/index.ts
use status 503 if search strategy throws 500 to indicate downstream service failure
when opensearch is down, send a request to enhancements api:
before
```sh
❯ curl -X POST 'http://localhost:5601/api/enhancements/search/sql' -H 'Content-Type: application/json' -H 'osd-xsrf: osd-fetch' -d '{"query":{ "query": "b", "language": "language", "format": "format" }}'
{"statusCode":500,"error":"Internal Server Error","message":"An internal server error occurred."}%
```
after
```sh
❯ curl -X POST 'http://localhost:5601/api/enhancements/search/sql' -H 'Content-Type: application/json' -H 'osd-xsrf: osd-fetch' -d '{"query":{ "query": "b", "language": "language", "format": "format" }}'
{"statusCode":503,"error":"Service Unavailable","message":"Error: No Living connections"}%
```
- skip
=> [Query enhancements] use status 503 if search strategy throws 500

changelogs/fragments/8915.yml, src/plugins/vis_augmenter/public/plugin.ts, src/plugins/vis_augmenter/public/services.ts, src/plugins/vis_augmenter/public/utils/utils.test.ts, src/plugins/vis_augmenter/public/utils/utils.ts, src/plugins/vis_augmenter/public/view_events_flyout/actions/view_events_option_action.tsx, src/plugins/vis_type_vislib/public/line_to_expression.ts, src/plugins/visualizations/public/embeddable/visualize_embeddable.ts
This reverts commit 539675e688061e689b362801bcb05a3ef78431b2.
There is a known issue with the bundled JS after this change, when trying to render eligible visualizations. The AD/Alerting options fail to render, due to issues fetching the underlying `getIndexPatterns` fn within `isEligibleForVisLayers`. This is due to how the JS modules are bundled along with a mismatch on when these functions are defined in `setup()`/`start()` phases of the plugins.
Future work to add this functionality in a safe manner is tracked in #8924.
- skip
=> Revert "[augmenter] do not support datasources with no version (#8915)"

changelogs/fragments/8611.yml, package.json, yarn.lock
See https://github.com/opensearch-project/OpenSearch-Dashboards/issues/8379 for the problem.
In http, `url.format()` is used to format query object into URL
https://github.com/opensearch-project/OpenSearch-Dashboards/blob/64ed61bd9709b62d4fbc3de98656570e7e6bc782/src/core/public/http/fetch.ts#L151-L154
This method does not work correctly on browser side, that if `query` is
```json
{ "a": "a", "b": [], "c": "c" }
```
instead of `?a=a&c=c`, it returns `?a=a&&c=c`. The root cause is somewhere inside [`querystring.stringify`](https://github.com/defunctzombie/node-url/blob/v0.10.3/url.js#L376) in the `url` module, and updating `url` to latest 0.11.4 fixes this behavior (possibly because url changed to `qs` instead of `querystring`).
`url` npm module is introduced by `aws-sdk`, and in latest …
=> bump `url` to 0.11.4

package.json, yarn.lock
Resolve CVE-2024-45590 by bumping` body-parser` from `1.19.0` to `1.20.3` 
Resolve CVE-2024-45296 by bumping a vary of `path-to-regexp` to required versions
NA
```
ubuntu@ip-172-31-21-67:~/work/OpenSearch-Dashboards$ yarn why body-parser
[1/4] Why do we have the module "body-parser"...?
warning Resolution field "typescript@4.0.2" is incompatible with requested version "typescript@~4.8.4"
=> Found "body-parser@1.20.3"
- "_project_#@percy#agent" depends on it
- Hoisted from "_project_#@percy#agent#body-parser"
- Hoisted from "_project_#@percy#agent#express#body-parser"
info Disk size without dependencies: "260KB"
info Disk size with unique …
```
=> [CVE-2024-45590][CVE-2024-45296] Resolve cves for 1.3 by bumping `body-parser` and `path-to-regexp` 

changelogs/fragments/8842.yml, src/plugins/home/public/application/opensearch_dashboards_services.ts, src/plugins/home/public/application/sample_data_client.js, src/plugins/home/public/application/sample_data_client.test.js, src/plugins/home/public/plugin.ts, src/plugins/home/server/services/sample_data/routes/uninstall.ts
This PR addresses the issue of error toasts appearing on the sample data page when installing or uninstalling sample data. The root cause was that the user did not have permission to update UI settings at the workspace level. The changes in this PR include:
1. Remove saved objects first when uninstalling sample data.
2. Disable the behavior of updating the default index pattern UI setting for non workspace admin when installing or uninstalling sample data inside a workspace.
No UI Changes
1. Clone the branch and run `yarn osd bootstrap --single-version loose`.
2. Add the following configurations to `config/opensearch_dashboards.yml`:
```
uiSettings:
overrides:
```
3. Run `yarn start --no-base-path`. …
=> [Workspace]Fix error toasts in sample data page

packages/osd-plugin-generator/template/public/components/app.tsx.ejs
- following the [plugin generator guide](https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/packages/osd-plugin-generator/README.md), once you have created a plugin, navigate to your plugin on the dashboard, and you will see a blank page:
- Inspecting the console will reveal the issue
fixes https://github.com/opensearch-project/OpenSearch-Dashboards/issues/8918
- After making this change, i have created a plugin again via `node scripts/generate_plugin --name my_plugin_name -y`, and upon navigating to my new plugin's page, the page correctly renders:
- skip
=> fix: update the osd-plugin-generator template to reference the correct button

changelogs/fragments/8932.yml, src/plugins/data/public/query/query_string/dataset_service/dataset_service.mock.ts, src/plugins/data/public/query/query_string/dataset_service/types.ts, src/plugins/data/public/query/query_string/language_service/types.ts, src/plugins/data/public/ui/dataset_selector/configurator.test.tsx, src/plugins/data/public/ui/dataset_selector/configurator.tsx, src/plugins/data/public/ui/query_editor/query_editor_top_row.test.tsx, src/plugins/data/public/ui/query_editor/query_editor_top_row.tsx, src/plugins/query_enhancements/common/types.ts, src/plugins/query_enhancements/common/utils.ts, src/plugins/query_enhancements/public/search/ppl_search_interceptor.ts, src/plugins/query_enhancements/public/search/sql_search_interceptor.ts, src/plugins/query_enhancements/server/routes/index.ts
Continue on https://github.com/opensearch-project/OpenSearch-Dashboards/pull/8917
This PR
- allows dataset to override `hideDatePicker` per language for custom logic to insert time filter into query
- disables submit button if time field is not selected in dataset configurator
closes https://github.com/opensearch-project/OpenSearch-Dashboards/pull/8917
- feat: Support custom logic to insert time filter based on dataset type
=> [Discover] Support custom logic to insert time filter based on dataset type

src/plugins/data/public/ui/query_editor/language_selector.tsx
* Adds `queryEditorLanguageOptions` data-test-subj on `src/plugins/data/public/ui/query_editor/language_selector.tsx`
* Adds support for some tests that will be merged to main in the future, from the cypress-unification branch.
- skip
=> TESTID-140: add queryEditorLanguageOptions data-test-subj on language_selector.tsx

changelogs/fragments/9034.yml, src/plugins/discover/public/application/view_components/utils/use_search.ts
Fix the saved search loading issue in 2.17 when query enhancement is not enabled.
https://github.com/user-attachments/assets/e075e531-cd21-48a9-9b2b-242d73f02ef3
- fix: Fix saved search loading issue
=> Fix saved search loading issue

changelogs/fragments/8611.yml, package.json, yarn.lock
cherry picked commit 41ac8ab6c9c5162b3ea419f22fa4173e6d6ad9e5 from #8611
=> [Manual bckport 2.x] bump `url` to 0.11.4 (#8611)

cypress/utils/dashboards/commands.js, cypress/utils/dashboards/remove_workspace.js, cypress/utils/dashboards/setup_workspace.js, cypress/utils/dashboards/workspace-plugin/commands.js, cypress/utils/dashboards/workspace-plugin/constants.js
This PR adds certain workspace utility for the new Discover Experience with workspaces and query enhancements enabled. 
- skip
=> Add workspace utility 

changelogs/fragments/9074.yml, cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/query_enhancements/a_check.spec.js, cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/query_enhancements/dataset_selector.spec.js, cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/query_enhancements/queries.spec.js, cypress/utils/apps/commands.js, cypress/utils/apps/index.d.ts, cypress/utils/apps/query_enhancements/commands.js, cypress/utils/apps/query_enhancements/index.d.ts, cypress/utils/dashboards/commands.js, cypress/utils/dashboards/index.d.ts
Refactors/additions for Cypress Query Enhancements
- update the custom command `waitForLoader` to take optional arg `isEnhancement: boolean`
- remove the `cy.wait()` within `waitForLoader` to speed up the command
- remove the now redundant `waitForLoaderNewHeader` command and refactor its' usage to be `waitForLoader(true)`
- add typescript typings to some of our custom commands
- refactor createWorkspaceIndexPatterns
- conditionally call `cy.get('[type="data-source"]').contains(dataSource).click();` if `dataSource` prop is provided. This is because if your ws only has one data source, then this step is not visible in the UI, and this utility will fail
- add optional arg `indexPatternHasTimefield: boolean`. This is needed because if the index pattern you select does not have a timefield, …
=> refactor some query-enhancement utility functions, add some missing typings

.github/workflows/build_and_test_workflow.yml, changelogs/fragments/9064.yml, docs/_sidebar.md, src/dev/license_checker/config.ts, yarn.lock
Add checks for out of sync lockfile and dev docs.
Validate the licensing imposed by dependencies.
Improve validation of the licensing imposed by dependencies.
- infra: Add checks for out of sync lockfile and dev docc to the CI
- infra: Validate the licensing imposed by dependencies during CI
- chore: Bump actions used by build and test workflows
- feat: Improve validation of the licensing imposed by dependencies.
=> Improve CI checks on PRs

changelogs/fragments/9082.yml, cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/query_enhancements/constants.js, cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/query_enhancements/dataset_selector.spec.js, cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/query_enhancements/queries.spec.js, cypress/support/e2e.js, cypress/utils/commands.js, cypress/utils/constants.js, cypress/utils/dashboards/commands.js, package.json
* dataset_selector.spec.js
https://github.com/user-attachments/assets/214f8b2c-d6f0-4302-8073-8f141849e92f
* queries.spec.js
https://github.com/user-attachments/assets/d5b3006c-4d71-4af0-9f8a-0ebf21467a6f
Note:
```
const scopedHistoryNavigationError = /^[^(ScopedHistory instance has fell out of navigation scope)]/;
Cypress.on('uncaught:exception', (err) => {
/* returning false here prevents Cypress from failing the test */
if (scopedHistoryNavigationError.test(err.message)) {
return false;
}
});
```
is from https://github.com/opensearch-project/OpenSearch-Dashboards/pull/9047
NA
- test: Re-enable dataset_selector.spec.js under workspace in ciGroup10
=> Re-enable dataset_selector.spec.js and queries.spec.js under workspace

changelogs/fragments/9116.yml, src/plugins/workspace/public/plugin.ts
Hide collaborators page on nav when newHomePage is disabled
Before
After
Disable new home page, then go to home page navigation, the collaborator nav link will be hidden.
- fix: Hide collaborators page on nav when newHomePage is disabled
=> [Workspace] fix: hide collaborators page on nav when newHomePage is disabled

DEVELOPER_GUIDE.md, changelogs/fragments/9080.yml, docs/_sidebar.md
An alternative to developing locally and setting up OpenSearch locally
by pointing to a running cluster.
n/a
- doc: update dev guide to connect to external cluster
=> [docs] update dev guide to connect to external cluster

changelogs/fragments/9059.yml, src/plugins/data_source_management/public/components/data_source_menu/data_source_menu.tsx, src/plugins/data_source_management/public/components/data_source_menu/types.ts, src/plugins/data_source_management/public/components/data_source_selectable/data_source_selectable.tsx, src/plugins/data_source_management/public/components/drop_down_header/drop_down_header.test.tsx, src/plugins/data_source_management/public/components/drop_down_header/drop_down_header.tsx, src/plugins/dev_tools/public/application.tsx, src/plugins/dev_tools/public/dev_tools_icon.tsx
This pr addresses the issue of inactive "Manage" link in the data source selector when opening DevTools. Now, clicking the link will direct users to opensearch-dashboards/dataSources.
https://github.com/user-attachments/assets/0d5572e6-078d-4fab-8709-ece38c990246
- fix: inactive manage link in the data source selector when opening DevTools
=> [workspace] fix: manage link does not do anything

src/plugins/home/public/application/components/sample_data_set_card.js, src/plugins/home/public/application/components/sample_data_view_data_button.js
This PR disables "add" button and "remove" button at sample data card for read-only users.
- feat: Disable buttons in sample data cards for read-only users
=> Disable buttons in sample data cards for read-only users

changelogs/fragments/9024.yml, src/plugins/dashboard/public/plugin.tsx, src/plugins/visualize/public/plugin.ts, src/plugins/workspace/public/plugin.test.ts, src/plugins/workspace/public/plugin.ts
This pr addresses:
1. Prevent user from visiting dashboards / visualizations when out of a workspace by setting WorkspaceAvailability
- fix: Prevent user from visiting dashboards / visualizations when out of a workspace
=> [Workspace] fix:Prevent user from visiting dashboards / visualizations when out of a workspace

changelogs/fragments/9153.yml, src/plugins/discover/public/application/components/no_results/no_results.tsx
This is to resolve a bug where a `0` is rendered in discover when there are no results. This is due to the following logic
`{tabs.length && (...` which leads the `0` to be rendered as React will only skip rendering `false`, `null`, or `undefined` values in the render template.
- fix: 0 rendered in discover when there are no results
=> fix: 0 rendered in discover when there are no results

changelogs/fragments/9164.yml, src/plugins/data_source_management/public/components/direct_query_data_sources_components/direct_query_data_connection/__snapshots__/manage_direct_query_data_connections_table.test.tsx.snap, src/plugins/data_source_management/public/components/direct_query_data_sources_components/direct_query_data_connection/manage_direct_query_data_connections_table.test.tsx, src/plugins/data_source_management/public/components/direct_query_data_sources_components/direct_query_data_connection/manage_direct_query_data_connections_table.tsx, src/plugins/data_source_management/public/types.ts
Support to dissociate data connection object since DSM list has supported to display
There is no UI changes in this PR, after this PR users could dissociate DQS in workspace DSM list direct query connections tab.
Go to data source management list page in workspace, then you could associate and dissociate DQS object.
This change has been tested in local and related unit tests have been added.
- feat: Support to dissociate data connection object since DSM list has supported to display
=> [Workspace] Support to dissociate data connection object since DSM list has supported to display

changelogs/fragments/9145.yml, src/core/public/doc_links/doc_links_service.ts, src/plugins/advanced_settings/public/management_app/__snapshots__/advanced_settings.test.tsx.snap, src/plugins/dashboard/public/application/components/dashboard_top_nav/__snapshots__/dashboard_top_nav.test.tsx.snap, src/plugins/data/public/ui/query_editor/__snapshots__/language_selector.test.tsx.snap, src/plugins/workspace/public/components/workspace_collaborators/workspace_collaborators.tsx, src/plugins/workspace/public/components/workspace_form/__snapshots__/workspace_privacy_flyout.test.tsx.snap, src/plugins/workspace/public/components/workspace_form/workspace_privacy_flyout.test.tsx, src/plugins/workspace/public/components/workspace_form/workspace_privacy_flyout.tsx
Add a "Learn More" flyout providing additional information to the collaborators page.
- feat: Add a "Learn More" flyout providing additional information to the collaborators page.
=> Add a learn more flyout to the collaborators page

src/plugins/workspace/public/components/workspace_form/workspace_privacy_setting_panel.tsx
This PR fixes the syntax of the UI text checkbox when adding collaborators after workspace creation.
- skip
=> Update text in workspace collaborators text box

changelogs/fragments/9187.yml, src/plugins/data_source_management/public/components/edit_data_source/components/edit_form/edit_data_source_form.tsx, src/plugins/data_source_management/public/components/edit_data_source/components/header/header.test.tsx, src/plugins/data_source_management/public/components/edit_data_source/components/header/header.tsx, src/plugins/data_source_management/public/components/edit_data_source/edit_data_source.test.tsx, src/plugins/data_source_management/public/components/edit_data_source/edit_data_source.tsx, src/plugins/index_pattern_management/public/components/edit_index_pattern/edit_index_pattern.tsx
When a user has read-only access to a workspace
the user shouldn't:
1. set an index pattern as default
2. set a data source as default
1. read-only user try to set an index pattern as default
https://github.com/user-attachments/assets/73318f86-ed78-464f-985c-3a779d2883c1
3.  read-only user try to set a data source as default
https://github.com/user-attachments/assets/ac1b7483-d647-43b8-9e39-2b6a81a9b694
- fix: fix set as default error in data source and index pattern
=> [workspace] fix set as default error in data source and index pattern

changelogs/fragments/9189.yml, src/plugins/workspace/server/integration_tests/duplicate.test.ts, src/plugins/workspace/server/integration_tests/routes.test.ts, src/plugins/workspace/server/routes/duplicate.ts, src/plugins/workspace/server/workspace_client.ts
Update workspace not found message to generic message which not include workspace information
```
curl --request GET \
--url http://localhost:5601/api/workspaces/you%20system%20id%20down \
--header 'Content-Type: application/json' \
--header 'osd-xsrf: 1'
{
"success": false,
"error": "workspace not found"
}
```
- fix: Update workspace not found message to generic message
=> [Workspace] update workspace not found message to generic message

cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/saved_search.spec.js, cypress/utils/apps/data_explorer/commands.js, cypress/utils/apps/data_explorer/index.d.ts, cypress/utils/apps/query_enhancements/saved_search.js
[This test case under Saved Search](https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/saved_search.spec.js#L132) have been flaky and failing more often than not for the permutation: `DatasetType: INDEX_PATTERN, language: OpenSearch SQL`. This is not reproducible for me locally, however looking at the videos, the issue seem to appear that the query language is changing to SQL automatically for some reason instead of staying as PPL. I am adding a step in the test to wait for the page to be loaded before loading.
- skip
=> [Fix] Saved Search Integ Test Update: update saving a new saved search test spec

changelogs/fragments/9167.yml, src/plugins/data/public/index.ts, src/plugins/data/public/query/state_sync/connect_to_query_state.test.ts, src/plugins/data/public/query/state_sync/connect_to_query_state.ts, src/plugins/data/public/query/state_sync/index.ts, src/plugins/data/public/query/state_sync/use_connect_to_query_state.test.ts, src/plugins/data/public/query/state_sync/use_connect_to_query_state.ts, src/plugins/discover/public/application/view_components/canvas/top_nav.tsx, src/plugins/vis_builder/public/application/components/top_nav.tsx
`OsdUrlStateStorage` subscription in `TopNav` is not properly cleaned up, which is causing `ScopedHistory` throwing error and potential memory leak.
-fixes https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5476
Before
https://github.com/user-attachments/assets/c79a6cba-4c52-45c8-8664-168923d1308a
After
https://github.com/user-attachments/assets/272f88a5-7302-4271-bff3-cc70bb75578d
- fix: Cleanup OsdUrlStateStorage subscription in TopNav
=> [Discover] [Vizbuilder] fix: Cleanup OsdUrlStateStorage subscription in TopNav

src/plugins/data/public/ui/query_editor/query_editor.tsx
Adds the necessary `data-test-subj` required for TESTID-51
- skip
=> add data-test-subjs that are required for TESTID-51

.github/workflows/cypress_workflow.yml, changelogs/fragments/9209.yml
Cypress should only install the version defined in package.json. 
Cigroup11 failture on main and 2.x because `env: 'cypress': Permission denied` because cypress is installing version 14
- fix: Fix cypress version error on ciGroup11
=> Remove bypass of getting cypress cache

cypress/utils/apps/query_enhancements/field_display_filtering.js
These functions that I am removing are unused and also redundant since we have these custom commands: https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/cypress/utils/apps/query_enhancements/commands.js#L142-L187
- skip
=> chore: remove unused/redundant functions from field_display_filtering_utils

changelogs/fragments/9237.yml, src/plugins/workspace/public/components/data_source_association/association_data_source_modal.test.tsx, src/plugins/workspace/public/components/data_source_association/association_data_source_modal.tsx, src/plugins/workspace/public/components/workspace_creator/workspace_creator.test.tsx, src/plugins/workspace/public/components/workspace_form/select_data_source_panel.test.tsx, src/plugins/workspace/public/utils.test.ts, src/plugins/workspace/public/utils.ts, src/plugins/workspace/server/saved_objects/workspace_id_consumer_wrapper.ts
This  pr fixes the bug of incorrect classification for data connections and optimizes operations by removing the fetching DQC when user associates an OpenSearch data source(only one step)
https://github.com/user-attachments/assets/fae29ee2-65ca-48fb-bfc2-2087c0139da9
- fix: bug that mistakenly classify data connection
=> [workspace]fix the bug that mistakenly classify data connection

cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/saved_queries_flyout.spec.js, cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/saved_queries_popover.spec.js
This PR #9150 updated the namespace of some of our cypress utils, but there were some changes that happened in parallel did not get updated, which will cause all tests to fail (ex: https://github.com/opensearch-project/OpenSearch-Dashboards/actions/runs/12932986740/job/36070528788?pr=9261)
- skip
=> update cy.createInitialWorkspaceWithDataSource -> cy.osd.createInitialWorkspaceWithDataSource

changelogs/fragments/9269.yml, src/core/public/chrome/ui/header/__snapshots__/header.test.tsx.snap, src/core/public/chrome/ui/header/header.tsx, src/core/public/overlays/sidecar/components/sidecar.scss
update sidecar style to align with new page header
Old page header is still working well.
Before
After
Before
After
Install assistant and switch dock mode to verify.
- fix: Update sidecar style to align with new page header
=> style: Update sidecar style to align with new page header

changelogs/fragments/9259.yml, src/core/public/http/fetch.ts, src/core/public/http/types.ts, src/plugins/workspace/public/utils.test.ts, src/plugins/workspace/public/utils.ts
Fix bug: In a workspace, and try to associate direct query connection, it will fail to get dqc and return 403 error
Issue: https://github.com/opensearch-project/OpenSearch-Dashboards/issues/9257
https://github.com/user-attachments/assets/3bfc7f73-e5d9-4bc2-98ec-77b5a8988a53
- fix: DQC can not be assigned to a workspace due to validation
=> [Workspace]DQC can not be assigned to a workspace due to validation 

changelogs/fragments/9275.yml, src/core/public/chrome/ui/header/header.tsx, src/core/public/chrome/ui/header/recent_items.test.tsx, src/core/public/chrome/ui/header/recent_items.tsx
When constructing the link for recent items, workspace feature flag is required. This PR is to pass workspace feature flag to all the places calling `createRecentNavLink`.
https://github.com/user-attachments/assets/2d1c239d-5c63-4086-bd71-23ec8a4f8d72
https://github.com/user-attachments/assets/9aa9347a-d2d6-49cf-bfe6-61ea8819305a
- fix: Recent item links are not correctly constructed
=> [Workspace]fix: recent item links are not correctly constructed

package.json
The `dashboard_sanity_test.spec.js` test file was recently changed to `dashboard_sanity_test.spec.ts` in #9150. Initially, we thought that it was caused by a Cypress caching issue, fixed in #9209. This PR bumps Cypress run command for CI group 11 in `package.json` to the correct file name. 
- skip
=> [CI] Update CI Group 11 Run Command

changelogs/fragments/9248.yml, src/plugins/data/public/ui/query_editor/query_editor.tsx
* When using keyboard shortcuts to run a query in Discover 2.0, the date range gets reverted to Discover's last date range state. Since there is no date range passed into the `onSubmit()` function from the editor shortcut, the `QueryEditorTopRow` uses the props passed from the search bar as dates, which may be out of sync compared to the query service state. This PR passes in the correct date form the query service.
* Additionally, in the multiline editor, the `query` object was being used to construct the new query. This PR updates it to match the single line editor, which uses the `queryRef` defined in the same file.
-fix: Fix Discover query editor enter shortcuts reverting date range
=> [Discover] Query Editor Shortcut Fires Incorrect Query

cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/saved_queries.spec.js
Add Todo Comment for workaround that was added to avoid rarely occurring issue. 
The issue is that the Date Picker is expected to be visible when DQL is selected, however it doesn't appear. To workaround this issue, we have to reselect the data source then the query language. This leads to the Date Picker appearing.
Relates to #9229. 
With OSD running, run yarn run cypress open. In E2E specs, you will see 1 new test spec1 saved_queries.spec.js. Run that spec.
- skip
=> [TESTID-125,126,127,128,129] Saved Query Test Scope Add Todo for Workaround

changelogs/fragments/9263.yml, src/plugins/data/common/osd_field_types/osd_field_types.ts, src/plugins/data/public/query/query_string/language_service/language_service.ts, src/plugins/data/public/query/query_string/language_service/types.ts, src/plugins/discover/public/application/components/default_discover_table/helper.test.tsx, src/plugins/discover/public/application/components/default_discover_table/helper.tsx, src/plugins/query_enhancements/public/plugin.tsx
Disable sorting on columns header for PPL and SQL, 
Currently sorting on Discover table columns header does not support PPL and SQL, disable it until we build sorting support for PPL and SQL.
[](https://github.com/user-attachments/assets/54af55a3-1ec4-4b60-a060-13cec4403e24)
- chore: Disable sorting on Discover table columns header for PPL and SQL
=> [Discover]chore: disable sorting on columns header for PPL and SQL

.github/workflows/cypress_workflow.yml, changelogs/fragments/9255.yml, cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/simple_dataset_selector.spec.js, cypress/utils/apps/query_enhancements/constants.js, cypress/utils/apps/query_enhancements/saved.js, cypress/utils/apps/query_enhancements/simple_dataset_selector.js, package.json
Add Tests for Simple Dataset Selector 
Split Ci group 10 into 2 parts CI group 10 and CI group 12 to reduce the time taken by the combined Ci group 10 to run.
- feat: Add Tests for Simple Dataset Selector
=> Add Tests for Simple dataset Selector

changelogs/fragments/9321.yml, cypress/fixtures/query_enhancements/data_logs_1/data_logs_large_time_1.mapping.json, cypress/fixtures/query_enhancements/data_logs_1/data_logs_large_time_2.mapping.json, cypress/fixtures/query_enhancements/data_logs_1/data_logs_small_no_time_1.mapping.json, cypress/fixtures/query_enhancements/data_logs_1/data_logs_small_no_time_2.mapping.json, cypress/fixtures/query_enhancements/data_logs_1/data_logs_small_time_1.mapping.json, cypress/fixtures/query_enhancements/data_logs_1/data_logs_small_time_2.mapping.json, cypress/fixtures/query_enhancements/data_logs_2/data_logs_large_time_1.mapping.json, cypress/fixtures/query_enhancements/data_logs_2/data_logs_large_time_2.mapping.json, cypress/fixtures/query_enhancements/data_logs_2/data_logs_small_no_time_1.mapping.json, cypress/fixtures/query_enhancements/data_logs_2/data_logs_small_no_time_2.mapping.json, cypress/fixtures/query_enhancements/data_logs_2/data_logs_small_time_1.mapping.json, cypress/fixtures/query_enhancements/data_logs_2/data_logs_small_time_2.mapping.json, cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/a_check.spec.js, cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/queries.spec.js, cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/saved_search_in_dashboards.spec.js, cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/sidebar.spec.js, cypress/scripts/generate_data/generate_all_data.sh, cypress/scripts/generate_data/index.js, cypress/scripts/generate_data/test_data_generator.js, cypress/utils/apps/query_enhancements/dataset_selector.js, cypress/utils/apps/query_enhancements/saved.js, cypress/utils/apps/query_enhancements/saved_queries.js
* Random id generation in TestDataGenerator
```
function generateRandomId(length = 20) {
return Array.from({ length }, () => ID_CHARS[Math.floor(Math.random() * ID_CHARS.length)]).join(
''
);
}
```
* Add a unique field to test modifyColumnsOnSwitch
There is an advanced settings for discover called `modifyColumnsOnSwitch`. By default (turn on), this settings will remove columns that are not available in the new index pattern when switch. Therefore we need a different field for time_1 data and time_2 data.
* Update mapping and include a never present field to test hide missing values
There is another feature called `hide missing values` in discover. An example to verify this feature
```
PUT a
{
"mappings": {
"properties": {
"field_always_present": {
"type": "keyword"
}, …
```
=> Update cypress data to have random id, missing value fields and unique field

.github/CODEOWNERS, MAINTAINERS.md, docs/_sidebar.md
Add Justin (angle943) as a maintainer
- doc: Add Justin (angle943) as maintainer
=> Add Justin as a maintainer

changelogs/fragments/9298.yml, src/plugins/discover/public/application/components/chart/_histogram.scss, src/plugins/discover/public/application/components/default_discover_table/_doc_table.scss, src/plugins/discover/public/application/view_components/canvas/discover_canvas.scss
Improve scrolling experience on Discover page:
1. Make vertical scrolling happen inside table rather instead of the entire right panel.(This change also bring horizontal scrolling to the bottom of the viewport instead of staying at the end of the page)
2. Make table header sticky.
1. If user scroll down the table on Discover the entire view scrolls down. The user is not able to see their columns that they have selected nor can they even see the query that they ran.
2. There is no indication of overflow horizontally wise the user will not know that they can scroll and depending on their setup that might not even be able to scroll horizontally 
https://github.com/user-attachments/assets/4e03f1c8-c589-4aa4-b3c2-8f8fbefe5917
- feat: Improve scrolling experience on Discover page.
=> [Discover] chore: Improve scrolling experience

cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/dataset_selector.spec.js, cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/field_display_filtering.spec.js, cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/language_specific_display.spec.js, cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/saved_queries.spec.js, cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/saved_search.spec.js, cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/saved_search_in_dashboards.spec.js, cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/time_range_selection.spec.js, cypress/utils/apps/query_enhancements/dataset_selector.js, cypress/utils/apps/query_enhancements/saved.js, cypress/utils/apps/query_enhancements/saved_queries.js, cypress/utils/constants.js
Update tests to only use data-logs-1.
This is done because there are issues with migration to Neo when using data-logs-2
- skip
=> [TEST] update tests to use only data-logs-1

src/core/public/chrome/ui/header/recent_items.tsx
Recent assets is a global component sitting in page header, and it will call get to retrieve metadata of objects inside / outside workspace. As we introduce a more strict rule that will deny cross-workspace calls, we need to remove the workspace prefix inside the calls from recent assets.
- skip
=> [Workspace]bugfix: remove workspace prefix when calling `get` in recent assets

changelogs/fragments/9343.yml, src/plugins/data/public/query/query_string/dataset_service/lib/index_type.ts
Discover data selector does not distinguish between clusters and collections, so we should call it data sources instead of just clusters.
- fix: Change from cluster to data sources for dataset selector column
=> Change from `Cluster` to `Data sources` for Indexes type in dataset selector column

changelogs/fragments/9352.yml, cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/shared_links.spec.js, cypress/utils/apps/query_enhancements/shared_links.js
The issue is only limit to cypress. Could be race condition or component state synchronize issues. Need further investigation. This PR adds a tmp fix (openShareMenuWithRetry helper):
* Added retry mechanism with verification
* Added explicit waits for animations
* Added better error handling and logging
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/9351
- test: Add retry mechanism for flaky share menu test
=> Add retry mechanism for flaky share menu test

changelogs/fragments/9314.yml, cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/language_specific_display.spec.js
- @maosaic recently fixed a bug to hide sorting options for PPL and SQL language: #9263
- This is adding to the `language_specific_display` test to ensure that the sort only appears for appropriate languages
- test: test sort in language_specific_display
=> add a check for the sort visibility in language_specific_display

.github/workflows/cypress_workflow.yml, changelogs/fragments/9366.yml
Updates the GitHub Actions workflow to use actions/cache@v4 instead of the deprecated v1. This change prevents future workflow interruptions when v1 is discontinued.
Addresses the deprecation warning:
"Error: This request has been automatically failed because it uses a deprecated version of actions/cache: v1"
- fix: Update actions/cache from v1 to v4 to address deprecation warning
=> Update actions/cache from v1 to v4 to address deprecation warning

src/plugins/region_map/server/routes/opensearch.ts
Handle invalid geospatial request in region map
=> Handle invalid geospatial request in region map

changelogs/fragments/9316.yml, src/plugins/dashboard/public/application/utils/use/use_dashboard_app_state.tsx, src/plugins/data/public/index.ts, src/plugins/data/public/query/state_sync/index.ts, src/plugins/data/public/query/state_sync/sync_state_with_url.test.ts, src/plugins/data/public/query/state_sync/use_sync_state_with_url.test.ts, src/plugins/data/public/query/state_sync/use_sync_state_with_url.ts, src/plugins/discover/public/application/components/top_nav/get_top_nav_links.tsx, src/plugins/discover/public/application/view_components/canvas/top_nav.tsx, src/plugins/saved_objects/public/save_modal/saved_object_save_modal.tsx
Properly clean up sync URL subscription in Discover plugin topNav component.
Changes this PR contains:
1. Create `useSyncQueryStateWithUrl` hook which automatically cancel sync URL subscription.
2. Invoke `useSyncQueryStateWithUrl` from `topNav` component, so the URL subscription will be properly clean up when user navigate away from Discover page.
3. ~Rewrite `SavedObjectSaveModal` as functional component.~
fixes #9309 
Before
https://github.com/user-attachments/assets/f9602bd5-2294-402d-bfd1-80d740dba757
After
https://github.com/user-attachments/assets/176a1ec6-b9fc-4fa0-ac7e-edb049eccd34
- fix: Clean up sync URL subscription in Discover plugin topNav
=> [Discover] fix: Clean up sync URL subscription in Discover plugin topNav

changelogs/fragments/9344.yml, docs/_sidebar.md, src/plugins/data/public/index.ts, src/plugins/data/public/query/query_string/index.ts, src/plugins/data/public/query/query_string/language_service/index.ts, src/plugins/data/public/query/query_string/language_service/lib/__snapshots__/query_result.test.tsx.snap, src/plugins/data/public/query/query_string/language_service/lib/query_result.tsx, src/plugins/data/public/ui/query_editor/_query_editor.scss, src/plugins/data/public/ui/query_editor/editors/default_editor/_default_editor.scss, src/plugins/data/public/ui/query_editor/editors/default_editor/index.tsx, src/plugins/data/public/ui/query_editor/editors/shared.tsx, src/plugins/data/public/ui/query_editor/query_editor.tsx
Improve query editor loading UX:
1. Spinner in editor footer will show immediately when query start. (time elapsed text will show 3s later)
2. Added a progress bar in query editor
3. Update loading text font
https://github.com/user-attachments/assets/4e85fe12-f8be-4bc9-a79f-6f9e801492e4
https://github.com/user-attachments/assets/8e489cfb-dbfa-4f3f-b0b3-97a30d33eb8c
- chore: Update query editor loading UI
=> [Discover] chore: Update query editor loading UI

changelogs/fragments/9152.yml, src/plugins/vis_type_vega/public/data_model/ppl_parser.test.ts, src/plugins/vis_type_vega/public/data_model/ppl_parser.ts, src/plugins/vis_type_vega/public/data_model/vega_parser.ts
This PR introduces time range filter support to Vega visualizations with PPL queries. When `"%timefield%"` is specified, the time range filter from the dashboard will be applied to the PPL query automatically.
Vega visualizations with PPL queries did not respect the time range set on the dashboard. Regardless of the selected time range, the query remained unaffected.
With the addition of `"%timefield%"`, changing the time range filter on a dashboard now impacts Vega visualizations with PPL queries.
```diff
{
"$schema": "https://vega.github.io/schema/vega-lite/v5.json",
"data": {
"url": {
+            "%timefield%": "timestamp",
"%type%": "ppl",
"body": {
"query": "source=opensearch_dashboards_sample_data_logs | stats count() as request_count by extension | sort -request_count"
}
}
}
}
``` …
=> feat(vis_type_vega): support reading time field

changelogs/fragments/9396.yml, cypress/utils/apps/query_enhancements/saved.js
To workaround [a bug](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/9131), a reload was added. Now that the bug has been resolved, the reload no longer needs to be there.
closes #9131
With OSD running, run yarn run cypress open. In E2E specs, you will see saved_search.spec.js. Run the test spec.
- test: remove unnecessary reload in saved_search test.
=> Remove reload in saved_search spec as bug has been resolved

src/plugins/data_importer/common/constants.ts, src/plugins/data_importer/config.ts, src/plugins/data_importer/public/components/data_importer_app.tsx, src/plugins/data_importer/public/lib/preview.ts, src/plugins/data_importer/public/types.ts, src/plugins/data_importer/server/parsers/csv_parser.test.ts, src/plugins/data_importer/server/parsers/csv_parser.ts, src/plugins/data_importer/server/parsers/file_parser_service.test.ts, src/plugins/data_importer/server/parsers/json_parser.test.ts, src/plugins/data_importer/server/parsers/json_parser.ts, src/plugins/data_importer/server/parsers/ndjson_parser.test.ts, src/plugins/data_importer/server/parsers/ndjson_parser.ts, src/plugins/data_importer/server/parsers/test_utils/csv_test_cases.ts, src/plugins/data_importer/server/parsers/test_utils/ndjson_test_cases.ts, src/plugins/data_importer/server/plugin.ts, src/plugins/data_importer/server/routes/cat_indices.ts, src/plugins/data_importer/server/routes/import_text.ts, src/plugins/data_importer/server/routes/preview.ts, src/plugins/data_importer/server/types.ts, src/plugins/data_importer/server/utils/util.test.ts, src/plugins/data_importer/server/utils/util.ts
This PR adds two new routes:
- `_preview`
- `_cat_indices`
And modifies two routes:
- `_import_file`
- `_import_text`
in order to support a file-preview like experience. Chiefly, the `_preview` route is used for parsing the file and returning the best guess index mapping that the documents will have. This PR does not cover the case where the existing index mapping and predicted index mapping differ. This is up to UI
=> Add support for file preview

cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/sidebar.spec.js
Follow-up #9386 comment: https://github.com/opensearch-project/OpenSearch-Dashboards/pull/9386#discussion_r1957666189
Follow-up PR:
https://github.com/opensearch-project/OpenSearch-Dashboards/pull/9386
- skip
=> [Follow-up #9386] Add TODO and omit for hide missing values for SQL and PPL

.github/workflows/build_and_test_workflow.yml, .github/workflows/cypress_workflow.yml, .github/workflows/cypress_workflow_with_s3.yml, .github/workflows/release_cypress_workflow.yml
Enable overwrite on upload artifact
when upgrade `actions/upload-artifact` from v3 to v4, by default it disabled overwrite on upload artifact, which can break our CI action.
```
Run actions/upload-artifact@v4
/usr/bin/docker exec  67b6fe2ab6755c4ac4d8f3ce17062864e8c76474287aff42e172161441b98545 sh -c "cat /etc/*release | grep ^ID"
With the provided path, there will be 6 files uploaded
Artifact name is valid!
Root directory input is valid!
Error: Failed to CreateArtifact: Received non-retryable error: Failed request: (409) Conflict: an artifact with this name already exists on the workflow run
```
Ref: https://github.com/actions/upload-artifact/blob/main/docs/MIGRATION.md#overwriting-an-artifact
- skip
=> Enable overwrite on upload artifact

changelogs/fragments/9405.yml, src/plugins/discover/public/application/components/chart/histogram/histogram.tsx
Make colour of discover histogram match theme
Before
After
- chore: Make colour of discover histogram match theme
=> [Discover]: Make colour of discover histogram match theme

changelogs/fragments/9355.yml, cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/s3_dataset.spec.js, cypress/utils/apps/query_enhancements/constants.js, src/plugins/query_enhancements/common/utils.ts, src/plugins/query_enhancements/server/routes/data_source_connection/routes.ts, src/plugins/query_enhancements/server/utils/plugins.ts
When ongoing S3 queries are aborted in Discover, the backend job should also be canceled/deleted. This PR uses the SQL plugin API to delete ongoing jobs to cancel them.
- feat: Deletes S3 Jobs in Backend when Original Query is Canceled
=> [Discover] Cancel S3 Queries Using SQL Plugin

src/plugins/data/common/datasets/types.ts, src/plugins/data/public/query/query_string/dataset_service/dataset_service.ts, src/plugins/data/public/ui/dataset_selector/_dataset_table.scss, src/plugins/data/public/ui/dataset_selector/_index.scss, src/plugins/data/public/ui/dataset_selector/dataset_table.test.tsx, src/plugins/data/public/ui/dataset_selector/dataset_table.tsx
Sometimes a data structure contains other metadata, it would be helpful to display them as descriptions to the user. Examples can be user defined descriptions, tags, or associated resources. 
This PR adds a optional description field for data structures, and it is displayed in the dataset table. Currently it does not add it to dataset selector but can be done in the future.
unit tests added
- skip
=> [Discover] support description in data-structures

changelogs/fragments/9379.yml, cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/inspect.spec.js, src/plugins/data/common/constants.ts, src/plugins/data/common/data_frames/utils.test.ts, src/plugins/data/common/data_frames/utils.ts, src/plugins/data/common/index_patterns/index_patterns/index_pattern.ts, src/plugins/data/common/search/aggs/buckets/date_histogram.ts, src/plugins/data/common/search/aggs/utils/calculate_auto_time_expression.ts, src/plugins/data/common/search/opensearch_search/types.ts, src/plugins/data/common/search/search_source/search_source.ts, src/plugins/data/public/query/query_string/dataset_service/lib/index_type.ts, src/plugins/data/public/query/query_string/language_service/types.ts, src/plugins/discover/public/application/view_components/utils/use_search.ts, src/plugins/query_enhancements/public/plugin.tsx
When sending PPL requests, the time based fields are rendered in wrong time zone, and it looks like DQL and PPL are getting different results. We should format the PPL search response to the same format as DQL search response to indicate it is in UTC so the time fields can be formatted and rendered correctly in the discover table according to user defined time zone in advanced setting.
For example, previously 
```
// PPL search response
"order_date": "2025-02-13 00:51:50"
// DQL search response
"order_date": "2025-02-13T00:51:50+00:00”
```
resolves #9104 
Before: 
PPL render time field in the wrong timezone
https://github.com/user-attachments/assets/f0e24d6e-6560-4897-9d3b-5b41c780b26e
After: 
PPL and DQL return and render same results for default timezone or user defined timezone …
=> Render PPL time column using the correct time zone

changelogs/fragments/9436.yml, src/plugins/query_enhancements/public/plugin.tsx
Format PPL to include mili-seconds in date fields. 
Actual data: 2022-06-15T10:12:52.382Z
Previously: 
Jun 15, 2022 @ 03:12:52.000 (current browser timezone)
After PR: 
Jun 15, 2022 @ 03:12:52.382 (current browser timezone)
- fix: Make PPL handle miliseconds in date fields
=> Format PPL date fields to `YYYY-MM-DDTHH:mm:ss.SSSZ`

cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/03/inspect.spec.js, cypress/utils/apps/query_enhancements/inspect.js
in differing environments, the way PPL is sorted comes through differently, causing our tests to fail. This enforces that we specify the sort for both PPL and SQL
- skip
=> [TEST] add setting sort for PPL and SQL for inspect.spec

changelogs/fragments/9446.yml, packages/osd-ui-shared-deps/index.d.ts, packages/osd-ui-shared-deps/index.js
#7625 has deprecated various `CssDistFilename` from `osd-ui-shared-deps`. For 3.0 release, we are removing them from the codebase.
Part of #9253.
- breaking: remove `CssDistFilename`
=> remove deprecated CssDistFilename for 3.0

packages/osd-dev-utils/package.json, packages/osd-ui-shared-deps/package.json, yarn.lock
Bump axios from 0.28.1 to 0.29.0 in 2.x
```
yarn why axios
yarn why v1.22.21
[1/4] 🤔  Why do we have the module "axios"...?
[2/4] 🚚  Initialising dependency graph...
warning Resolution field "typescript@4.0.2" is incompatible with requested version "typescript@~4.5.2"
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "axios@0.29.0"
info Has been hoisted to "axios"
- "workspace-aggregator-712dbdc8-f238-4c64-9eb7-5bb044cdcd99" depends on it
- Hoisted from "_project_#@osd#ui-shared-deps#axios"
- Hoisted from "_project_#@osd#dev-utils#axios"
info Disk size without dependencies: "1.14MB"
info Disk size with unique dependencies: "1.3MB"
info Disk size with transitive dependencies: "1.68MB"
info Number of shared dependencies: 7
=> Found …
```
=> Bump axios from 0.28.1 to 0.29.0 in 2.x

changelogs/fragments/9412.yml, package.json, packages/osd-dev-utils/package.json, yarn.lock
Bump markdown-it from 12.3.2 to 13.0.2
```
yarn why markdown-it
yarn why v1.22.21
[1/4] 🤔  Why do we have the module "markdown-it"...?
[2/4] 🚚  Initialising dependency graph...
warning Resolution field "typescript@4.6.4" is incompatible with requested version "typescript@4.0.2"
warning Resolution field "typescript@4.6.4" is incompatible with requested version "typescript@4.0.2"
warning Resolution field "typescript@4.6.4" is incompatible with requested version "typescript@4.0.2"
warning Resolution field "typescript@4.6.4" is incompatible with requested version "typescript@4.0.2"
warning Resolution field "typescript@4.6.4" is incompatible with requested version "typescript@4.0.2"
warning Resolution field "typescript@4.6.4" is incompatible with requested version "typescript@4.0.2"
warning …
```
=> Bump markdown-it from 12.3.2 to 13.0.2

changelogs/fragments/9447.yml, package.json, yarn.lock
Bump dompurify from 3.1.6 to 3.2.4
```
=> Found "dompurify@3.2.4"
info Has been hoisted to "dompurify"
- "workspace-aggregator-4999c2e0-ed64-49ee-b921-36c0e97d5740" depends on it
- Specified in "devDependencies"
- Hoisted from "_project_#dompurify"
info Disk size without dependencies: "372KB"
info Disk size with unique dependencies: "372KB"
info Disk size with transitive dependencies: "372KB"
info Number of shared dependencies: 0
✨  Done in 1.57s.
```
CVE-2025-26791
- security: Bump dompurify from 3.1.6 to 3.2.4
=> Bump dompurify from 3.1.6 to 3.2.4

changelogs/fragments/9412.yml, package.json, packages/osd-dev-utils/package.json, yarn.lock
* Bump markdown-it from 12.3.2 to 13.0.2
Backport PR: https://github.com/opensearch-project/OpenSearch-Dashboards/pull/9412
- skip
=> [2.x-manual-backport] Bump markdown-it from 12.3.2 to 13.0.2 (#9412)

packages/osd-ui-shared-deps/theme_config.d.ts, packages/osd-ui-shared-deps/theme_config.js, src/core/server/ui_settings/settings/theme.test.ts, src/core/server/ui_settings/settings/theme.ts, src/core/server/ui_settings/ui_settings_config.ts
Allow v8/v9 as default setting
Previously setting default theme version as `v8` or `v9` in `opensearch_dashboards.yml` will fail validation.
```
FATAL  ValidationError: [config validation of [uiSettings].defaults.theme:version]: types that failed validation:
- [config validation of [uiSettings].defaults.theme:version.0]: expected value to equal [v7]
- [config validation of [uiSettings].defaults.theme:version.3]: expected value to equal [Next (preview)]
```
- skip
=> Allow v8/v9 as default setting

changelogs/fragments/9448.yml, src/core/public/http/fetch.ts, src/core/public/http/types.ts
#5592 renamed `withLongNumerals` to `withLongNumeralsSupport` in `HttpFetchOptions`. Now we are removing the deprecated `withLongNumerals` for 3.0
Part of #9253 
- breaking: remove `withLongNumerals` in `HttpFetchOptions`.
=> remove withLongNumerals in HttpFetchOptions as it is deprecated in 3.0

changelogs/fragments/9430.yml, src/plugins/query_enhancements/common/types.ts, src/plugins/query_enhancements/public/datasets/s3_type.ts
For PPL in OpenSearch / OpenSearch Spark, the typings for `byte`, `short`, `int`, `integer`, `long`, `float`, `double`, `tinyint`, `smallint`, and `bigint` need to be mapped to numeric. This PR adds the numeric mapping for `tinyint`, `smallint`, and `bigint` in the S3 dataset type.
- fix: Add mappings for tinyint, smallint, and bigint in S3 dataset type
=> [Discover] Add New Mappings for S3 Type

src/plugins/data_importer/public/application.tsx, src/plugins/data_importer/public/components/data_importer_app.tsx
This PR fixes the `Server error` that may occur if the `dataSource.hideLocalCluster` option is set to `true`. Essentially, this PR prevents a network call if there are no available data sources on startup.
Without MDS: makes the network call to `_cat/indices` as expected
With MDS, with local cluster: makes the network call to `_cat/indices` as expected
With MDS, with local cluster and a data source connected: makes the network call to `_cat/indices` as expected
With MDS, without local cluster, no datasource: no network call to `_cat/indices` as expected (with toast from the `DataSourceSelectable` component
With MDS, without local cluster, with datasource: makes the network call to `_cat/indices` as expected
=> Prevent `_cat/indices` when there is no datasource available

package.json, packages/osd-opensearch-archiver/package.json, packages/osd-opensearch-archiver/src/lib/docs/generate_doc_records_stream.ts, packages/osd-opensearch-archiver/src/lib/indices/opensearch_dashboards_index.ts, packages/osd-opensearch/package.json, yarn.lock
Upgrading the OpenSearch Client dependency from 2.x to 3.x
- skip
(This change does not affect the end user of OSD)
=> Upgrading `opensearch` client to 3.x

changelogs/fragments/9492.yml, src/plugins/query_enhancements/public/query_assist/components/query_assist_summary.tsx
This pr set the text size in generated summary S
- fix: text size in generated summary should be s
=> [Workspace] fix: text size in generated summary should be s

changelogs/fragments/9494.yml, src/plugins/query_enhancements/public/query_assist/utils/create_extension.test.tsx, src/plugins/query_enhancements/public/query_assist/utils/create_extension.tsx
This PR changes the position of the query summary and query editor.
- feat: update position of summary
=> [workspace] feat: changes the position of the query summary and query editor

package.json, src/plugins/data/public/query/query_string/dataset_service/types.ts, src/plugins/data_source/common/data_connections/data_connection_saved_object_attributes.ts, src/plugins/data_source/common/data_sources/types.ts, src/plugins/discover/public/application/components/sidebar/metrics_sidebar.tsx, src/plugins/discover/public/application/view_components/panel/index.tsx, src/plugins/discover/public/application/view_components/utils/use_prometheus.ts, src/plugins/query_enhancements/common/constants.ts, src/plugins/query_enhancements/public/assets/prometheus_mark.svg, src/plugins/query_enhancements/public/datasets/prometheus_type.ts, src/plugins/query_enhancements/public/plugin.tsx, src/plugins/query_enhancements/server/plugin.ts, src/plugins/query_enhancements/server/routes/metrics/routes.ts, src/plugins/query_enhancements/server/search/index.ts, src/plugins/query_enhancements/server/search/promql_search_strategy.ts, src/plugins/query_enhancements/server/utils/plugins.ts
This is to allow for basic prometheus data selection in Discover in our wip prometheus feature branch
What this doesn't do
- Connect to persistence for datasources/connections. I've left a TODO in the `fetchConnections` method to address in the near future 
- skip
=> Skeleton of prometheus data selection

changelogs/fragments/9511.yml, src/plugins/discover/public/application/components/data_grid/data_grid.tsx, src/plugins/discover/public/application/components/data_grid/data_grid_table.tsx, src/plugins/discover/public/application/components/data_grid/data_grid_table_cell_actions.tsx, src/plugins/discover/public/application/components/data_grid/data_grid_table_cell_value.tsx, src/plugins/discover/public/application/components/data_grid/data_grid_table_columns.tsx, src/plugins/discover/public/application/components/data_grid/data_grid_table_context.tsx, src/plugins/discover/public/application/components/data_grid/data_grid_table_docview_inspect_button.tsx, src/plugins/discover/public/application/components/data_grid/data_grid_table_flyout.tsx, src/plugins/discover/public/application/components/data_grid/data_grid_toolbar.tsx, src/plugins/discover/public/application/components/utils/local_storage.ts, src/plugins/discover/public/application/view_components/canvas/discover_chart_container.tsx, src/plugins/discover/public/embeddable/search_embeddable_component.tsx
- We are deprecating the `discover:newExperience` setting and DataGrid table for 3.0.
- Note that this newExperience does not exist in the `queryEnhanced` view.
These are the things going away for 3.0:
- We are first deprecating the option to toggle the legacy discover experience:
- And we are deprecating the "new" discover table:
- deprecate: discover:newExpereince and DataGridTable
=> deprecate the discover:newExpereince

changelogs/fragments/9507.yml, package.json, packages/osd-dev-utils/package.json, packages/osd-ui-shared-deps/package.json, yarn.lock
Resolve CVE-2025-27152 by bumping axios to 1.8.2
- security: Resolve CVE-2025-27152 by bumping axios to 1.8.2
=> Fix CVE-2025-27152 by bumping axios

changelogs/fragments/9516.yml, src/plugins/data/common/data_frames/utils.test.ts, src/plugins/data/common/data_frames/utils.ts
Fix data frame conversion error for null/undefined objects
Problem:
- `processNestedFieldEntry` function uses `Object.entries()`
- `Object.entries()` throws "Uncaught TypeError: Cannot convert undefined or null to object" when given null/undefined values
Solution:
- Added a `!value` check before calling `Object.entries()`
- Returns the value directly when `!value` is true, avoiding the error
```
data_source.enabled: true
uiSettings:
overrides:
'query:enhancements:enabled': true
```
- Login with admin user
- Visit data source page
- Create …
=> Fix data frame null or undefined object conversion error 

changelogs/fragments/9514.yml, src/core/public/chrome/ui/header/__snapshots__/header.test.tsx.snap, src/core/public/chrome/ui/header/collapsible_nav_group_enabled.scss, src/core/public/chrome/ui/header/header.tsx, src/core/public/overlays/index.ts, src/core/public/overlays/sidecar/helper.test.ts, src/core/public/overlays/sidecar/helper.ts, src/core/public/overlays/sidecar/index.ts
make nav icon style compatible with sidecar
Before
After
Open chatbot and dock to left to test the changes.
- fix: Make nav icon style compatible with sidecar
=> [Navigation] fix: make nav icon style compatible with sidecar

changelogs/fragments/9532.yml, src/plugins/query_enhancements/public/query_assist/components/query_assist_bar.tsx, src/plugins/query_enhancements/public/query_assist/utils/constant.ts, src/plugins/query_enhancements/public/query_assist/utils/index.ts, src/plugins/query_enhancements/public/query_assist/utils/prompt.test.ts, src/plugins/query_enhancements/public/query_assist/utils/prompt.ts
Append prompt for query assistant in request payload
No UI change.
Use query assistant and try it with `fail` or `error` in question then see request payload
- feat: Append prompt for query assistant in request payload
=> [Query enhancement]feat: Append prompt for query assistant in request payload

changelogs/fragments/9529.yml, src/plugins/discover/public/application/components/top_nav/open_search_panel.tsx, src/plugins/discover/public/application/view_components/utils/use_search.test.tsx, src/plugins/discover/public/application/view_components/utils/use_search.ts
Previously, when loading a snapshot URL that contains a saved search with temporary editing, the temporary editing content will not be loaded. This is because when the app getting initialize, status store in URL snapshot will be loaded first, later the async fetch result from saved search will override those temporary editing.
Ideally when loading a saved search, if it’s loaded by user click on saved search panel UI, we want to wipe current state and use the saved query states, if the saved search is loaded from user directly paste a url in browser, we want use the url snapshot state instead.
To build the ideal experience, this PR contains changes below:
1. When user click a saved search from UI panel, clean filter and query
2. When loading saved search, saved filters will apply on top of …
=> [Discover] fix: Correctly load saved search from snapshot URL

changelogs/fragments/9541.yml, src/plugins/data/public/ui/search_bar/search_bar.tsx
Query information that stores in `QueryStringManager` get pass to `SearchBarUI`, and `SearchBarUI` manipulates the `query` props and pass it to `QueryEditor`.
When loading a saved search, `Query` in `QueryStringManager` get updated three times, follow by the order `query => language => dataset`(fields of `Query`). However, the `getDerivedStateFromProps` in `SearchBarUI` will wipe query text if the saved search get loaded has different language and same dataset compare to the current query.
This PR change the comparison between "incoming" prop to "previous" prop to comparing "incoming" prop with "previous" state. In this case, loading saved search will correctly show on query editor, while switching languages will still wipe the query.
Before …
=> [Discover] fix: correctly load saved search query in query editor

cypress/utils/commands.osd.js
- when we have multiple workspaces in our test to the point where we have a paginated result of the workspaces, the tests begin failing due to the custom command `deleteAllOldWorkspaces` not knowing how to deal with the paginated links. This change fixes it so that we don't click those
- verified that it works by manually creating a lot of workspaces and having the tests still passing
- skip
=> [TEST] fix delete all old workspaces

changelogs/fragments/9465.yml, src/plugins/data_explorer/public/plugin.ts, src/plugins/discover/public/plugin.ts
This pr prevents user from visiting discover when out of a workspace  
when removing workspace in url
- fix: Prevent user from visiting discover when out of a workspace
=> [workspace] Prevent user from visiting discover when out of a workspace 

cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/03/download_csv.spec.js, cypress/utils/apps/query_enhancements/download_csv.js, cypress/utils/apps/query_enhancements/shared.js, cypress/utils/index.d.ts
- I've been noticing that the `download_csv.spec.js` is crashing in some of the CI runs, here is an example: https://github.com/opensearch-project/OpenSearch-Dashboards/actions/runs/13910917046/job/38924790602?pr=9531
- This PR breaks apart the csv tests into smaller `it` statements to reduce the num of crashes
- skip
=> [TESTS] make download_csv tests smaller to reduce the num of crashes

.github/CODEOWNERS, MAINTAINERS.md, changelogs/fragments/9467.yml
Add Joey Liu (@Maosaic) as a maintainer for the opensearch-project/OpenSearch-Dashboards repository.
Joey has demonstrated strong technical capabilities and has been making valuable contributions to our codebase.
Here are some examples of his recent contributions:
https://github.com/opensearch-project/OpenSearch-Dashboards/pull/9383
https://github.com/opensearch-project/OpenSearch-Dashboards/pull/9379
https://github.com/opensearch-project/OpenSearch-Dashboards/pull/9316
https://github.com/opensearch-project/OpenSearch-Dashboards/pull/9314
https://github.com/opensearch-project/OpenSearch-Dashboards/pull/9298
Joey has shown exceptional understanding of web development, React, and engineering principles that are crucial for developing a data analytics tool. His ability to quickly grasp …
=> Add Joey Liu (`@Maosaic`) as a maintainer

src/plugins/data/public/query/query_string/language_service/types.ts, src/plugins/discover/public/application/view_components/canvas/discover_visualization.tsx, src/plugins/query_enhancements/public/plugin.tsx
Add `showVisualization` setting in the language config, so currently discover will only render visualization for promQl based queries.
=> Add showVisualization setting in language config

src/plugins/discover/public/application/components/visualizations/vislib/line/to_expression.ts, src/plugins/query_enhancements/server/search/promql_search_strategy.ts
This is to update the prometheus query response interface to reflect a recent sql plugin change and plot all series on the same y axis/scale.
- skip
=> update prometheus response interface, plot series on same y scale

changelogs/fragments/9575.yml, src/plugins/data_source/config.ts, src/plugins/data_source_management/server/routes/data_connections_router.ts
fix potential memory leak in getDirectQueryConnections with node 20
1. enforce timeout to `2s` for the legacy client call on `ppl.dataSource`
2. use larger default client pool size `10`. Note that if single page is loading with 10+ datasources, this could still lead to server crash due to a deprecated `parseUrl` function in `url` is used in elasticsearch legacy library. However, to address this, we will need to deprecate usage of elasticsearch client, which is not currently in scope of 3.0 release.
- related issue #2220 
```
(node:504350) [DEP0170] DeprecationWarning: The URL search-data-logs-2-xrnwkouy6zb62xpw5vaarfndm4.aos.us-west-2.on.aws:443::::::::true::::::::::::: is invalid. Future versions of Node.js will throw an error.
(Use node --trace-deprecation ... to show where the warning …
```
=> Fix: fix potential memory leak in getDirectQueryConnections with node 20

src/plugins/data/public/plugin.ts, src/plugins/data/public/resources/base_resource_client.ts, src/plugins/data/public/resources/prometheus_resource_client.ts, src/plugins/data/public/resources/resource_client_factory.ts, src/plugins/data/public/types.ts, src/plugins/discover/public/application/components/visualizations/vislib/line/to_expression.ts, src/plugins/discover/public/application/view_components/utils/use_prometheus.ts, src/plugins/query_enhancements/server/connections/clients/base_connection_client.ts, src/plugins/query_enhancements/server/connections/managers/prometheus_manager.ts, src/plugins/query_enhancements/server/routes/resources/routes.ts
This is to create a clientside API to surface data connection resources. With this PR I've implemented the prometheus resource API which will be used for dynamic query suggestions. 
- skip
=> create and integrate the clientside resource client factory

src/plugins/index_pattern_management/public/components/field_editor/components/scripting_help/test_script.tsx, src/plugins/index_pattern_management/public/components/field_editor/field_editor.tsx, src/plugins/index_pattern_management/public/components/field_editor/lib/validate_script.ts, src/plugins/index_pattern_management/public/components/field_editor/types.ts, src/plugins/index_pattern_management/server/routes/preview_scripted_field.ts
feat: Add MDS support for index pattern validate script
Scripted field is a feature of index pattern that used in visualizations and display in documents. Validation is an API used for validation script when creating scripts. 
Before this PR, this API did not support MDS, so it would throw an error when operating the index pattern on a remote data source. After this PR, this error would be fixed.
No UI change
Turn on/off the MDS, and then visit index pattern script field edit page, the API won't break down any more if editing an index pattern on remote data source.
- feat: Add MDS support for index pattern validate script
=> feat: Add MDS support for index pattern validate script

changelogs/fragments/9420.yml, src/plugins/saved_objects_management/server/routes/find.test.ts, src/plugins/saved_objects_management/server/routes/find.ts, src/plugins/workspace/server/integration_tests/routes.test.ts
Given we have two workspaces (namely `first` and `second`), and each has a saved object.
We retrieve the saved objects using the following URL (using workspace prefix but no query parameters):
`/w/first/api/opensearch-dashboards/management/saved_objects/_find?type=index-pattern`
Previously, this request would return both saved objects because when no `workspace` query parameter was provided, our endpoint would pass `workspace: undefined` to the actual query, bypassing the workspace check. As a result, the backend would return all saved objects even when the original request was made under the `first` workspace context.
This PR removes the logic of passing `workspace: undefined `when there is no `workspace` query parameter. Now, the wrapper for the `_find` endpoint automatically retrieves …
=> [Workspace] Fix find saved object within a workspace without queryparams return all the saved objects

changelogs/fragments/9497.yml, cypress.config.ts, cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/01/queries.spec.js, cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/05/autocomplete_switch.spec.js, cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/05/autocomplete_ui.spec.js, cypress/utils/apps/query_enhancements/autocomplete.js, cypress/utils/apps/query_enhancements/saved.js, cypress/utils/apps/query_enhancements/saved_queries.js, package.json, packages/osd-monaco/package.json, packages/osd-monaco/src/json/worker/json.worker.ts, packages/osd-monaco/src/monaco.ts, packages/osd-monaco/src/test_setup.js, packages/osd-monaco/src/xjson/language.ts, packages/osd-monaco/webpack.config.js, packages/osd-ui-shared-deps/webpack.config.js, src/dev/jest/config.integration.js, src/dev/jest/config.js, src/dev/jest/setup/mocks.js, src/dev/jest/setup/monaco_mock.js, src/plugins/data/public/antlr/dql/code_completion.test.ts, src/plugins/data/public/ui/query_editor/_query_editor.scss, src/plugins/data/public/ui/query_editor/editors/default_editor/index.tsx, src/plugins/data/public/ui/query_editor/editors/shared.tsx, src/plugins/data/public/ui/query_editor/query_editor.tsx, src/plugins/opensearch_dashboards_react/public/code_editor/code_editor.test.tsx, src/plugins/vis_type_timeline/public/components/timeline_expression_input.tsx, yarn.lock
This PR bumps the Monaco editor from version 0.17.0 to 0.30.1, which includes significant changes to the editor's API and functionality. The changes ensure compatibility with the newer version while maintaining existing features. Here are the key changes:
* Updated Monaco editor version in package.json from ~0.17.0 to ^0.30.1
* Updated Monaco editor version in packages/osd-monaco/package.json from ~0.17.0 to ^0.30.1
* Added new dependencies in packages/osd-monaco/package.json. Check more explains for codicon.
```
file-loader: ^6.2.0
style-loader: ^1.1.3
```
* Updated import path in packages/osd-monaco/src/json/worker/json.worker.ts to match new Monaco structure
* Added CSS import `import 'monaco-editor/esm/vs/base/browser/ui/codicons/codicon/codicon.css';` for Monaco editor icons in …
=> Bump `monaco-editor` from 0.17.0 to 0.30.1

changelogs/fragments/9623.yml, package.json, packages/osd-optimizer/src/worker/webpack.config.ts, src/plugins/vis_type_vega/public/lib/vega.js, src/plugins/vis_type_vega/public/vega_request_handler.ts, yarn.lock
Pick up progress from https://github.com/opensearch-project/OpenSearch-Dashboards/pull/9579
* Changed Vega Import Path: We updated the import in src/plugins/vis_type_vega/public/lib/vega.js to use the standard browser-compatible Vega import instead of the Node.js specific version:` import * as vega from 'vega';`, instead of 'vega/build/vega-node' or 'vega/build-es5/vega'
* Updated Webpack Configuration: We modified the webpack configuration in packages/osd-optimizer/src/worker/webpack.config.ts to:
* Remove the noParse rules for Vega, allowing webpack to properly process the Vega files
* Update the exclude pattern to ensure vega-scenegraph and other Vega-related packages are properly processed by Babel
* Fixed Circular Dependency: We resolved a circular dependency issue in …
=> Bump vega from 5.23.0 to 5.32.0

changelogs/fragments/9634.yml, package.json, yarn.lock
[CVE-2024-53382](https://github.com/advisories/GHSA-968p-4wvh-cqc8)
Updates `prismjs` version as a resolution.
- security: Resolve CVE-2024-53392 by bumping prismjs to 1.30.0
=> [CVE-2024-53382] Add prismjs 1.30.0 to resolutions

changelogs/fragments/9647.yml, src/core/public/http/fetch.test.ts, src/core/public/http/fetch.ts
This PR supports returning pure fetch response when content-type in response header is `text/event-stream`. And I searched for the whole project that no API is using `text/event-stream` as its response content type. https://github.com/search?q=org%3Aopensearch-project%20text%2Fevent-stream&type=code
closes #9604 
https://github.com/opensearch-project/dashboards-assistant/pull/493
Unit test has been added, and you can find the consumer in: https://github.com/opensearch-project/dashboards-assistant/pull/493
- feat: support streaming when content type is event stream
=> feat: support streaming when content type is event stream

.github/workflows/cypress_workflow.yml, changelogs/fragments/9659.yml, config/opensearch_dashboards.yml, src/plugins/discover/public/application/components/data_grid/data_grid_table.tsx
1. In the Discover Page, sometimes if we filter the contents such that only one item is present, if we then add a field, when we then remove/disable the filter, the table doesn't resize to accommodate the original contents, i.e., it we can only see one row at a time or so.
2.  Addresses the deprecation warning in cypress:
"Error: This request has been automatically failed because it uses a deprecated version of actions/cache: v1"
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/9401
(https://drive.google.com/file/d/1zw3iitCa9jL0kmx_UOHk5WZvS-xjkRjC/view?usp=sharing)
- fix: Discover table not updating with row size when filtering out
- fix: Update actions/cache from v1 to v4 to address deprecation warning
=> Discover Grid filter fix

CHANGELOG.md, package.json, src/plugins/data_source/server/legacy/configure_legacy_client.ts, src/plugins/data_source/server/legacy/http_aws_es/connector.js, src/plugins/data_source/server/legacy/http_aws_es/connector.test.js, yarn.lock
This PR fixes an error when configuring a data source with SigV4 auth that was a regression from upgrading the aws sdk from v2 to v3 in https://github.com/opensearch-project/OpenSearch-Dashboards/pull/9641. While https://github.com/opensearch-project/OpenSearch-Dashboards/pull/9641 fixed an issue when configuring a data source with basic auth credentials after upgrading OSD Core from node18 -> node20, it broke sigv4 auth.
This PR contains the following changes.
1. Use AbortController from aws-sdk v3 to abort request
2. Remove `import { Credentials } from '@aws-sdk/client-sts';` and pass creds directly
This error was discovered on future playground with the following message:
`TypeError: request.abort is not a function`
I verified that SigV4 auth works by connecting to an AOS domain from …
=> Fix issue connecting to data source with SigV4 auth after upgrading aws sdk from v2 to v3

cypress.config.ts, cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/query_enhancements/01/saved_search.spec.js, cypress/utils/apps/query_enhancements/saved.js
Added saved search related test cases:
1. Added a test case for snapshot URL with save search.
2. Remove a workaround that require change query language before load a saved search. 
- skip
=> [TEST] Add saved search related test cases

changelogs/fragments/9603.yml, src/plugins/query_enhancements/common/utils.test.ts, src/plugins/query_enhancements/common/utils.ts, src/plugins/query_enhancements/public/search/ppl_search_interceptor.ts
Update PPL query builder to skip appending time range to ppl when not querying with source.
Resolve a issue that cause PPL query to failed unexpectedly
Before
After
-fix: Skip appending time range to ppl when not querying with source
=> Fix: Skip appending time range to ppl when not querying with source

changelogs/fragments/9676.yml, src/plugins/data_source/server/legacy/http_aws_es/connector.js, src/plugins/data_source/server/legacy/http_aws_es/connector.test.js
Summary
This PR fixes the error:
```
Elasticsearch ERROR: 2025-04-11T21:10:24Z
Error: Request error, retrying
PUT https://search-aos-215-xxxq6sjh2os6mbvxnizn5mr5yy.us-west-2.es.amazonaws.com/opensearch_dashboards_sample_data_ecommerce => headers[headerName].trim is not a function
```
Root Cause
The error occurred because the Content-Length header was set as a numeric value instead of a string. When the HTTP library calls .trim() on header values, it fails if the value isn’t a string.
```
TypeError: headers[headerName].trim is not a function
at getCanonicalHeaders (/Volumes/workplace/NeoDevStack-szhongna/src/OpenSearch-Dashboards/node_modules/@smithy/signature-v4/dist-cjs/getCanonicalHeaders.js:20:62)
at SignatureV4.signRequest (/Volumes/workplace/NeoDevStack-szhongna/src/OpenSearch-Dashboa …
```
=> Fix issue with adding sample data to data source

changelogs/fragments/9668.yml, src/plugins/data/public/ui/dataset_selector/_dataset_explorer.scss
Hide the y scroll bar to avoid the dataset selector flashing
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/9474
**Before**
https://github.com/user-attachments/assets/df1d755b-d808-4547-b452-1e330a8b8f30
**After**
https://github.com/user-attachments/assets/2e1a22ce-4b0a-43bc-9ede-cbeefdd63592
- fix: [Discover]Fix dataset selector flashing
=> [Discover]Fix dataset selector flashing

changelogs/fragments/9586.yml, src/plugins/data/public/query/query_string/language_service/lib/__snapshots__/query_result.test.tsx.snap, src/plugins/data/public/query/query_string/language_service/lib/query_result.test.tsx, src/plugins/data/public/query/query_string/language_service/lib/query_result.tsx, src/plugins/discover/public/application/view_components/canvas/top_nav.tsx, src/plugins/discover/public/application/view_components/utils/use_search.test.tsx, src/plugins/discover/public/application/view_components/utils/use_search.ts, src/plugins/query_enhancements/common/utils.ts
This PR fix a bug that causing error message in query editor to show `Cannot read properties of undefined (reading 'hasOwnProperty')` instead of the correct error message.
There are 2 major changes in this PR:
1. Correctly throw error from `fetch` result
2. Properly handle error message base on current error structure
Example error
```
{
"statusCode": 404,
"error": "Not Found",
"message": "{\n  \"error\": {\n    \"reason\": \"Error occurred in OpenSearch engine: no such index [data_logs_small_time_12]\",\n    \"details\": \"[data_logs_small_time_12] IndexNotFoundException[no such index [data_logs_small_time_12]]\\nFor more details, please send request for Json format to see the raw response from OpenSearch engine.\",\n    \"type\": \"IndexNotFoundException\"\n  },\n  \"status\": 404\n}"
} …
```
=> Fix: Correctly show error message in DQL and PPL query editor

changelogs/fragments/9665.yml, src/core/public/chrome/nav_group/nav_group_service.test.ts, src/core/public/chrome/nav_group/nav_group_service.ts, src/core/public/chrome/utils.ts, src/plugins/home/public/plugin.ts
There are some issues when workspace is disabled and new home page enabled:
1. [Left navigation] Menu stay in settings and setup when opening a visualization from assets relationship
2. [Left navigation]Add sample data under Custom category
This PR mainly fix those issues.
- Sample data is under Custom category
- When landing Dashboards / Visualization page, left navigation is in settings and setup nav group
- Sample data is under Settings and setup
- Dashboards / Visualization is inside correct nav group
https://github.com/user-attachments/assets/6d3144df-d0c4-455e-9789-89d12a6ce8d5
- fix: Menu stay in settings and setup when opening a visualization from assets relationship
- fix: Add sample data under Custom category
=> [Workspace] Fix issue when workspace is disabled

changelogs/fragments/9509.yml, src/plugins/data/public/ui/query_editor/_query_editor.scss, src/plugins/data/public/ui/query_editor/editors/default_editor/_default_editor.scss, src/plugins/query_enhancements/public/query_assist/_index.scss, src/plugins/query_enhancements/public/query_assist/components/__snapshots__/call_outs.test.tsx.snap, src/plugins/query_enhancements/public/query_assist/components/call_outs.tsx, src/plugins/query_enhancements/public/query_assist/components/query_assist_banner.tsx, src/plugins/query_enhancements/public/query_assist/components/query_assist_input.tsx
1. Compress the natural language input field (i.e., reduce height to align with the button)
2. Change the icon in the caution banner
3. Add margin to the top of the natural language input field
4. Adjust overall padding between elements within the discover summary (i.e., below header and above editor) to be more consistent
NA
Before:
After:
- fix: Fix minor UX style issues on discover summary section
=> Minor UX fixes for discover summary

changelogs/fragments/9346.yml, src/core/public/chrome/ui/header/recent_items.test.tsx, src/core/public/chrome/ui/header/recent_items.tsx
Filter out recent items which has errors(might be deleted)
**Remove [eCommerce] Sales by Gender**
- fix: [workspace] filter out recent items which have errors
=> [Workspace] Filter out recent items with errors

src/plugins/data/public/query/query_string/language_service/lib/__snapshots__/query_result.test.tsx.snap, src/plugins/data/public/query/query_string/language_service/lib/query_result.test.tsx, src/plugins/data/public/query/query_string/language_service/lib/query_result.tsx, src/plugins/discover/public/application/view_components/utils/use_search.ts, src/plugins/query_enhancements/common/utils.test.ts, src/plugins/query_enhancements/common/utils.ts
This PR fix a bug that causing error message in query editor as message[object object] instead of the correct error message .
There are 2 major changes in this PR:
Correctly throw error from fetch result
Properly handle error message base on current error structure
Fix message [object object] issue in ppl editor
Before
After
- fix: Correctly show error message in DQL and PPL query editor
=>  Fix: Correctly show error message in DQL and PPL query editor

changelogs/fragments/9605.yml, src/plugins/query_enhancements/public/query_assist/components/query_assist_bar.test.tsx, src/plugins/query_enhancements/public/query_assist/components/query_assist_bar.tsx
This pr retains previous query if input invalid questions and adds callout
https://github.com/user-attachments/assets/58b44355-3bed-45af-acd8-caad863dc906
- fix: should clear previous query if input invalid questions
=> [Discover]fix: should clear previous query if input invalid questions

changelogs/fragments/9409.yml, src/core/public/saved_objects/saved_objects_client.test.ts, src/core/public/saved_objects/saved_objects_client.ts, src/plugins/workspace/public/components/data_source_association/association_data_source_modal.tsx, src/plugins/workspace/public/components/workspace_list/index.tsx, src/plugins/workspace/public/utils.test.ts, src/plugins/workspace/public/utils.ts, src/plugins/workspace/server/saved_objects/workspace_id_consumer_wrapper.test.ts, src/plugins/workspace/server/saved_objects/workspace_id_consumer_wrapper.ts
This pr remove * when calling getDataSourcesList in data source association modal and in workspace list page.
Inside a workspace and open data source association modal, we want to find all the data sources, here we remove the client base path
in workspace list page, we also remove the client base path
- fix: remove * when calling find in data source association modal and in workspace list page
=> [workspace]remove * when calling find in data source association modal and in workspace list page

changelogs/fragments/9625.yml, src/plugins/data/public/query/query_string/query_string_manager.test.ts, src/plugins/data/public/query/query_string/query_string_manager.ts, src/plugins/data/public/query/state_sync/connect_to_query_state.ts, src/plugins/data/public/ui/dataset_selector/index.test.tsx, src/plugins/data/public/ui/dataset_selector/index.tsx, src/plugins/data/public/ui/query_string_input/query_string_input.tsx, src/plugins/discover/public/application/view_components/utils/use_search.ts
Fix a issue that can cause `Discover` fire incorrect query when switch from other plugin. There are a few problems add up to this unexpected user experience:
1. When user navigate to `Discover` using the left side navigation panel, it will always try to do a "fresh start" by loading a empty dataset with the query and language store in local storage. But because `setQuery` always try to merge the next query state into the current query state, if there is a existing dataset, it will never be replace by the empty dataset.
2. Currently, dataset is store in `queryStringManager` as part of the `query` state, and because `queryStringManager` is global, dataset state persist when user navigate to other plugin after visiting Discover.
3. Whenever the selected language changed, we need to update …
=> Fix a issue that can cause incorrect query to fire when switch plugin

changelogs/fragments/9730.yml, src/plugins/data_source/server/legacy/http_aws_es/connector.js, src/plugins/data_source/server/legacy/http_aws_es/connector.test.js
Fix SigV4 signing mismatch issue with `?v` query parameter
When you call APIs like `/_cat/indices/_hot?v`, without `=`, Node.js `querystring.parse()` sets `v: null`, not `v: ''`
But AWS expects it to be `v=`, that is, an empty string value, not null.
In this PR, we ensure when parsing query string, empty values are properly preserved. Instead of using Node `querystring.parse()`, use `URLSearchParams` which behaves properly
```
message": "Error from esClient call: {\"statusCode\":403,\"body\":{\"message\":\"The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.\\n\\nThe Canonical String for this request should have …
```
=> Fix SigV4 signing mismatch issue with `?v` query parameter

.github/workflows/cypress_workflow.yml, test/common/config.js
The CI's have been failing ever since the change in opensearch settings 
```search.concurrent_segment_search.mode: all```
Find more details here https://github.com/opensearch-project/OpenSearch/issues/18149#issuecomment-2843368856
This changes disables the above change
```search.concurrent_segment_search.mode: none```
https://github.com/opensearch-project/OpenSearch/issues/18149
- chore: Fix CI by disabling concurrent_segment_search setting
=> [Fix Failing CI] Disable Concurrent Segment Search for OpenSearch in CI

changelogs/fragments/9734.yml, src/plugins/workspace/public/plugin.test.ts, src/plugins/workspace/public/plugin.ts
Before:
```
savedObjects.permission.enabled: false
```
After:
- fix: Fix collaborators displays under custom tab on navigation when saved object permission is disabled
=> Fix collaborators displays under custom tab on left navigation when saved object permission is disabled

packages/osd-babel-preset/node_preset.js, packages/osd-babel-preset/package.json, packages/osd-optimizer/src/worker/bundle_refs_plugin.ts, packages/osd-optimizer/src/worker/webpack.config.ts, src/plugins/workspace/public/plugin.test.ts, src/plugins/workspace/public/plugin.ts, src/plugins/workspace/server/plugin.test.ts, src/plugins/workspace/server/plugin.ts, tsconfig.base.json, yarn.lock
This PR add path alias support for webpack and babel. Previously, path alias only works for importing typescript types.
1. webpack now supports `opensearch-dashboards/public` path alias
2. Refactor the current in-house path resolution in BundleRefsPlugin to use webpack internal `compiler.resolverFactory` to work with webpack path alias
3. Introduced `babel-plugin-module-resolver` to enable path alias support for babel so that we can use path alias in server side code and jest tests.
For `public` code
```
// before
import { formatUrlWithWorkspaceId } from '../../../../../src/core/public/utils';
// after
import { formatUrlWithWorkspaceId } from 'opensearch-dashboards/public/utils';
```
For `server` code
```
// before
import { fromRoot } from '../../../core/server/utils';
// after
import { …
```
=> Support path alias for webpack and babel

changelogs/fragments/9611.yml, src/plugins/query_enhancements/public/query_assist/components/query_assist_summary.tsx
1. Open discover and let the default query(1st) to run
2. After the results returned, use query assistant to generate a new ppl query(2nd)
3. The result summary is **immediately** triggered automatically without waiting for the 2nd query to return
4. The generated summary is incorrect because it uses the results of 1st query
It should wait for the 2nd query to complete, then trigger the result summary.
This is a quick fix that stop loading discover results to summary component when natural language query is not provided(the initial case). Only when the query is generated with NLQ, the results will be loaded, and the summarization then will be triggered.
For the long term, the result summary component should not rely on the UI state of discover results. There will be a follow up PR to …
=> fixed an issue that the initial result summary generated with the wrong data

src/plugins/workspace/public/components/data_source_association/association_data_source_modal.test.tsx, src/plugins/workspace/public/components/data_source_association/association_data_source_modal.tsx
OpenSearch connections were being shown when user clicked on the Associate  Direct query data sources button. This behaviour was contrary to the expectation of modal only showcasing the DQS and DQC objects. The PR is to fix this behaviour. 
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/9706
Before fix 
https://github.com/user-attachments/assets/b140b43d-69d1-416b-8f2f-171ea59182db
After fix
https://github.com/user-attachments/assets/3f9f0c4f-4466-495b-9897-2427a1272b24
- fix: filter out Opensearch Data sources in Associate Direct Query Sources Modal
=> [Fix] filter out Opensearch Data sources in Associate Direct Query Sources Modal

changelogs/fragments/9735.yml, src/core/public/overlays/sidecar/components/resizable_button.test.tsx, src/core/public/overlays/sidecar/components/resizable_button.tsx, src/core/public/overlays/sidecar/helper.ts, src/core/public/overlays/sidecar/sidecar_service.tsx
Previously, the implementation of the resize button allowed users to drag it and resize the chatbot window outside of the browser window. This meant that if users dragged the button outside of the browser window and released the mouse press, they could never resize the window back to its original size since the button was now outside of the window and could not be reached.
This PR consists of the following changes:
1. When resizing the chatbot window, prevent users from resizing the chatbot window beyond the browser window size
2. When resizing the window, if the chatbot window exceeds the window size, automatically shrink the chatbot window accordingly
Before:
https://github.com/user-attachments/assets/423fb273-7541-4835-94f1-a80de25e5d7b
After: …
=> Fix chatbot flyout cannot be resized beyond the window size

changelogs/fragments/9784.yml, packages/osd-babel-preset/node_preset.js, src/dev/build/tasks/transpile_babel_task.ts
When run `opensearch-build` to build OSD distributions, the source codes are copied to `build/opensearch-dashboards`, so the build dir is NOT the project root, the current babel path alias plugin config `babel-plugin-module-resolver` assume OSD is build from project root dir, so the resolved path for alias are incorrect at the moment if it's build from `build/opensearch-dashboards`.
To fix the issue, we will pass the build dir to `babel-plugin-module-resolver` when building OSD distributions.
- fix: path alias not properly resolved if the source code was copied and built from another directory
=> fix path alias not working for distribution builds

src/plugins/data/public/ui/dataset_selector/_dataset_explorer.scss
https://github.com/opensearch-project/OpenSearch-Dashboards/pull/9668 sets overflow-y of the top container to hidden, this breaks the dataset table with multi-selectable datasets. The scrollbar is gone and user cannot scroll the table. Additionally, 
This PR fixes it, tested both table and list, scrollbar is present and not observing flickering.
The scrollbar in "Connections" looks different in the screenshots because before this PR, the height of `.datasetExplorer` is the height of the table, and the entire `.datasetExplorer` was scrollable before #9668. After this PR, the table/list scrolling is constrained in "Test items", and scrolling table will not scroll the entire `.datasetExplorer`.
only manual testing.
Currently all scss/css are mocked in jest, and since core does not contain …
=> [Discover] Fix scroll bar not showing up for dataset table

changelogs/fragments/9818.yml, src/core/public/chrome/nav_group/nav_group_service.test.ts, src/core/public/chrome/nav_group/nav_group_service.ts, src/plugins/home/public/plugin.test.ts, src/plugins/home/public/plugin.ts
The `showInAllNavGroup` was used for nested structure of multi-levels of left navigation. Since we've flattened menus for analytics(all) use case, the property should be deprecated to reduce confusion.
For more context, please refer to #9812 .
Register `Discover` to Observability use case
- feat: deprecate showInAllNavGroup property
- feat: register search overview page to all use case by using addNavLinksToGroup
=> Feature: deprecate showInAllNavGroup property

cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/explore/03/download_csv.spec.js, cypress/utils/apps/explore/download_csv.js
- Explore test for `download_csv` was accidently going to discover page. This was discovered when debugging the failed test in https://github.com/opensearch-project/OpenSearch-Dashboards/pull/9813
- skip
=> [Explore] fix download_csv for explore

.github/workflows/cypress_workflow.yml
ciGroup15 was accidently running the `explore` script on CI/CD. This was discovered due to failure on this PR: https://github.com/opensearch-project/OpenSearch-Dashboards/pull/9813
- skip
=> [Explore] fix ciGroup15 for explore

changelogs/fragments/9848.yml, src/plugins/workspace/server/plugin.ts, src/plugins/workspace/server/saved_objects/integration_tests/workspace_id_consumer_wrapper.test.ts, src/plugins/workspace/server/saved_objects/workspace_id_consumer_wrapper.test.ts, src/plugins/workspace/server/saved_objects/workspace_id_consumer_wrapper.ts
Revert workspaces = '*' and add warning log.
But in the future, the workspace team will deprecate it.
If the request url : `http://localhost:5601/api/saved_objects/_find?fields=id&fields=title&fields=auth&fields=description&fields=dataSourceEngineType&fields=type&fields=connectionId&per_page=10000&type=data-source&type=data-connection&workspaces=*` has the `workspaces=*`, the console will show the warning.
- fix: Revert workspaces=* and add warning log
=> [Fix] Revert workspaces=* and add warning log

src/plugins/workspace/server/saved_objects/integration_tests/workspace_id_consumer_wrapper.test.ts
Add two integration tests for workspace=*
- should return all data source when find with * within a workspace
- should return all data source when find with * out a workspace
```
PASS  src/plugins/workspace/server/saved_objects/integration_tests/workspace_id_consumer_wrapper.test.ts (74.028 s)
workspace_id_consumer integration test
saved objects client related CRUD
✓ create (2102 ms)
✓ create should not append requestWorkspaceId automatically when the type is config (2096 ms)
✓ should return error when create with a not existing workspace (2104 ms)
✓ bulk create (4191 ms)
✓ should return error when bulk create with a not existing workspace (2076 ms)
✓ checkConflicts when importing ndjson (5202 ms)
✓ find by workspaces (3172 ms)
✓ should not return 400 error when find with * (2074 ms)
✓ …
```
=> [Improvement] Add two integration tests for workspace=*

MAINTAINERS.md, changelogs/fragments/9863.yml
Updates documentation to call out that maintainers should ensure CI passes for merging and to validate with other maintainers if they need to override.
Please let me know if there's a better place to add this to docs.
N/A
N/A
N/A
- doc: Update maintainer merging responsibilities
=> docs: Update maintainer responsibilies on merging

changelogs/fragments/9867.yml, src/plugins/data/common/index_patterns/index_patterns/ensure_default_index_pattern.test.ts, src/plugins/data/common/index_patterns/index_patterns/ensure_default_index_pattern.ts
The ensureDefaultIndexPattern will throw error when data source reference id is '', this PR is to enhance the method so that:
- It can correctly solve the edge case and won't throw error.
- It should update default index pattern if the reference data source's id is empty.
Able to render dashboard page, and the error will be gone once user has a valid index pattern.
- feat: make default index pattern method more robust
=> feat: make default index pattern method more robust

src/plugins/explore/public/application/app.scss, src/plugins/explore/public/application/app.tsx, src/plugins/explore/public/components/experience_banners/experience_banner_wrapper/experience_banner_wrapper.test.tsx, src/plugins/explore/public/components/experience_banners/experience_banner_wrapper/experience_banner_wrapper.tsx
- This change adds the banner into the new architecture in explore
- Previously, we leveraged the Data Plugin's Query Editor to inject the banner there. Since the new explore does not use that editor, that is no longer applicable in the new experience.
- So i manually add the banner in the new experience while refactoring the previous code to only show banner within data plugin's query editor for the classic experience
- skip
=> [Explore] Banner in query explore

test/functional/apps/visualize/_metric_chart.js
- skips the failing test and created an issue: https://github.com/opensearch-project/OpenSearch-Dashboards/issues/9878
- skip
=> Skip failing selenium test "should show Percentiles"

changelogs/fragments/9903.yml, yarn.lock
Affected versions:
brace-expansion
>=2.0.0 <2.0.2 
brace-expansion
>=1.0.0 <1.1.12 
I fixed it by deleting the entries in `yarn.lock` and running `yarn osd bootstrap` again to have it fetch the latest versions
- chore: fix CVE 2025-5889 braces-expansion
=> Fix CVE 2025-5889

CHANGELOG.md, changelogs/fragments/9903.yml, release-notes/opensearch-dashboards.release-notes-3.1.0.md
- update release notes to include #9903 as that is a CVE fix.
- skip
=> update 3.1 release-notes to include #9903

CHANGELOG.md, changelogs/fragments/9903.yml, release-notes/opensearch-dashboards.release-notes-3.1.0.md
Backport https://github.com/opensearch-project/OpenSearch-Dashboards/commit/5000f2bc064b54dc1fd138ccd8e03c08fa4bb4de from https://github.com/opensearch-project/OpenSearch-Dashboards/pull/9910.
(this is a manual backport as #9913 does not include the previous backport commit and is wrong
=> [Backport 3.1] update 3.1 release-notes to include #9903

src/plugins/data/public/index.ts, src/plugins/data/public/ui/index.ts, src/plugins/data/public/ui/query_editor/index.tsx, src/plugins/explore/public/application/app.tsx, src/plugins/explore/public/application/components/query_panel.tsx, src/plugins/explore/public/build_services.ts, src/plugins/explore/public/components/query_panel/components/footer/index.scss, src/plugins/explore/public/types.ts
https://github.com/user-attachments/assets/4e462e55-f9d8-408d-91bd-8533d7a09455
PPL autocomplete was not working in the explore plugin. When users typed in the query editor, no autocomplete suggestions appeared, unlike in the discover plugin where autocomplete worked correctly.
The PPL_Simplified autocomplete provider requires services.appName parameter now due to added `PPL_Simplified` for explore, but the explore plugin was not updated and passing this required parameter, causing the provider to return early with empty suggestions.
In this PR, I fixed the following:
* Added missing appName parameter:  Added 'explore' to the ExploreServices interface and services object creation
* Improved Type Safety: Exported getEffectiveLanguageForAutoComplete function properly to eliminate as any …
=> [Explore] Fix autocomplete service and update temp query_panel

src/plugins/explore/public/application/legacy/discover/application/view_components/canvas/top_nav.tsx, src/plugins/explore/public/application/utils/state_management/utils/redux_persistence.ts
https://github.com/user-attachments/assets/7e9f6cc6-629f-4448-9ba4-ad366fbfb748
The Explore plugin was experiencing query state synchronization conflicts due to dual state management systems
* Standard URL State Sync: Using useConnectStorageToQueryState from the data plugin in top_nav
* Redux State Management: Custom persistence logic in redux_persistence.ts
connectStorageToQueryState expects QueryState from src/plugins/data/public/query/state_sync/types.ts, but Explore uses query types from src/plugins/data/common/query/types.ts.
Option 1: Smart Language Detection
Modify connectStorageToQueryState to use context-appropriate language defaults instead of hard-coding kuery.
Option 2: Type Alignment
Update Explore's query slice to use the same QueryState type as other plugins.
Option 3: …
=> [Explore] Fix refresh by removing duplicate sync

changelogs/fragments/9854.yml, src/core/server/ui_settings/ui_settings_client.test.ts, src/core/server/ui_settings/ui_settings_client.ts, src/plugins/workspace/server/plugin.ts, src/plugins/workspace/server/saved_objects/workspace_ui_settings_client_wrapper.test.ts, src/plugins/workspace/server/saved_objects/workspace_ui_settings_client_wrapper.ts
Previously we merged https://github.com/opensearch-project/OpenSearch-Dashboards/pull/9726 but actually the PR introduced a breaking change for uiSettingClient, as well as the router: `/api/opensearch-dashboards/settings`.
This PR is trying to make the change backward compatible but also add a deprecation warning log to tell developers the incorrect call will be deprecated in next major release.
Only backend changes introduced.
- Update yml file
```yml
data_source.enabled: true
```
in opensearch_dashboards.yml file as for now only defaultDataSource is the config that has multiple scopes.
- `yarn start --no-base-path` to start OSD server
- Try to update defaultDataSource through curl
```bash
curl 'http://localhost:5601/api/opensearch-dashboards/settings' \
-H …
```
=> [UI setting] feat: keep backward compatibility for UI setting client.

src/plugins/explore/public/application/components/header_dataset_selector.tsx, src/plugins/explore/public/application/components/query_panel.tsx, src/plugins/explore/public/application/legacy/discover/application/utils/state_management/index.ts, src/plugins/explore/public/application/legacy/discover/application/view_components/utils/use_index_pattern.ts, src/plugins/explore/public/application/utils/state_management/actions/export_actions.ts, src/plugins/explore/public/application/utils/state_management/actions/query_actions.ts, src/plugins/explore/public/application/utils/state_management/middleware/query_sync_middleware.ts, src/plugins/explore/public/application/utils/state_management/slices/query_slice.ts, src/plugins/explore/public/application/utils/state_management/store.ts, src/plugins/explore/public/application/utils/state_management/utils/redux_persistence.ts, src/plugins/explore/public/components/data_table/explore_data_table.tsx, src/plugins/explore/public/components/tabs/action_bar/action_bar.tsx, src/plugins/explore/public/components/tabs/logs_tab.tsx, src/plugins/explore/public/components/tabs/tabs.tsx
Problem: PPL queries with limitations (e.g., | head 50) required clicking "Run" twice to get correct results due to timing issues between Redux state updates and global query service synchronization.
Root Cause: The executeQueries thunk was called before queryStringManager was synchronized with the new query, causing the search service to use stale query data on first execution.
Solution: Implemented Redux middleware (createQuerySyncMiddleware) that automatically syncs Redux query state with the global queryStringManager whenever query actions are dispatched.
https://github.com/user-attachments/assets/08484072-7ec7-4422-a52f-248e1e16d0cb
NA
- skip
=> [Explore] Fix: PPL queries requiring two clicks to work correctly

src/plugins/explore/public/application/utils/hooks/use_timefilter_subscription.ts
The Explore plugin had inconsistent behavior compared to Discover when the date picker was changed:
Explore: Automatically executed queries when date picker changed (e.g., from 15 minutes to 15 days)
Discover: Required manual "Run" button click after date picker changes
The Explore plugin was subscribing to timefilter.getTimeUpdate$() which fires on all time range changes, including date picker modifications.
In this PR, simply replaced `getTimeUpdate$()` with `getAutoRefreshFetch$()` to only subscribes to auto-refresh events, not date picker changes.
NA
- skip
=> [Explore] Fix: Align Explore Plugin Date Picker Behavior with Discover

src/plugins/explore/public/components/experience_banners/constants.ts, src/plugins/explore/public/components/experience_banners/new_experience_banner/new_experience_banner.test.tsx, src/plugins/explore/public/components/experience_banners/new_experience_banner/new_experience_banner.tsx
persist the removing of new experience banner
=> update new experience banner to persist the dismissed banner via localStorage

changelogs/fragments/9946.yml, src/plugins/explore/public/application/pages/logs/logs_page.tsx, src/plugins/explore/public/application/pages/metrics/metrics_page.tsx, src/plugins/explore/public/application/pages/traces/traces_page.tsx, src/plugins/explore/public/application/utils/state_management/actions/query_actions.ts, src/plugins/explore/public/components/tabs/tabs.tsx, src/plugins/explore/public/components/visualizations/visualization_container.tsx
This PR fix 2 issues:
1. Use tab id in redux state to control rendering active tab content
2. Update `executeQueries` action to properly update `executionCacheKeys`
3. Update components read `executionCacheKeys`
1. Selected tab reset to logs tab when query run
4. Switch to visualization tab does not show visualization content, unless clicking "run query" button when visualization tab is selected
- fix: Preserve selected tab when query run, correctly update cacheKeys when query run
=> [Explore] Fix: Preserve selected tab when query run, correctly update cacheKeys when query run

src/plugins/data/public/ui/query_editor/_query_editor.scss
- note this only affects classic experience.
- when there were multiple banners, the bganners were scrunched on top of each other:
- after this change, there is some padding between each banner (as well as padding to the query editor, it looked weird to be so adjacent to it):
=> add margin between the banners

src/plugins/explore/public/application/legacy/discover/application/view_components/canvas/top_nav.tsx, src/plugins/explore/public/application/pages/logs/logs_page.tsx, src/plugins/explore/public/application/pages/metrics/metrics_page.tsx, src/plugins/explore/public/application/pages/traces/traces_page.tsx
- more prop refactor for TopNav
- we don't need `onQuerySubmit` as that is props that TopNav uses for SearchBar, which we don't use.
- `showSaveQuery` is always true
- `uiSettings.get('home:useNewHomePage')` is always true for new app
=> more top nav refactor

src/plugins/data/public/antlr/opensearch_ppl/code_completion.ts, src/plugins/data/public/antlr/opensearch_ppl/code_completion_simplified.test.ts, src/plugins/data/public/antlr/shared/utils.test.ts, src/plugins/data/public/antlr/shared/utils.ts, src/plugins/explore/public/components/query_panel/components/editor_stack/resuable_editor.tsx, src/plugins/explore/public/components/query_panel/query_panel.tsx
- Devalue fields in the Autosuggestion Wizard that begin with _ (Mostly are meta fields)
- Close the Autocomplete Suggestion Wizard when using CMD + Enter to run the query 
- Switching Datasets using the Dataset picker was still showing the fields from the previous dataset
( Although the React Component was being updated the provideCompletionItem Method was using the older reference for indexPattern and dataset that was causing data from previous dataset to show up. Currently Modified the method to fetch the current dataset and indexPattern from queryString manager before firing the actual autocomplete query. This ensures that we are always getting the latest updates)
- Minor Cleanups
- fix : Resolve Autocomplete bugs
=> Fix Autocomplete Bugs 

src/plugins/saved_objects/public/finder/saved_object_finder.tsx
- our appId for the explore changed to things like `explore/logs`, `explore/traces`, etc. so we had a regression in opening old saved searches
=> make old saved search findable in open top nav panel

src/plugins/explore/public/application/components/header_dataset_selector.tsx, src/plugins/explore/public/application/components/query_panel.tsx, src/plugins/explore/public/application/pages/logs/logs_page.tsx, src/plugins/explore/public/application/pages/metrics/metrics_page.tsx, src/plugins/explore/public/application/pages/traces/traces_page.tsx, src/plugins/explore/public/application/utils/hooks/use_tab_results.test.tsx, src/plugins/explore/public/application/utils/state_management/README.md, src/plugins/explore/public/application/utils/state_management/actions/reset_explore_state/reset_explore_state.test.ts, src/plugins/explore/public/application/utils/state_management/middleware/persistence_middleware.ts, src/plugins/explore/public/application/utils/state_management/selectors/index.ts, src/plugins/explore/public/application/utils/state_management/slices/index.ts, src/plugins/explore/public/application/utils/state_management/slices/system/index.ts, src/plugins/explore/public/application/utils/state_management/slices/system/system_slice.test.ts, src/plugins/explore/public/application/utils/state_management/slices/system/system_slice.ts, src/plugins/explore/public/application/utils/state_management/slices/tab/tab_slice.test.ts, src/plugins/explore/public/application/utils/state_management/slices/tab/tab_slice.ts, src/plugins/explore/public/application/utils/state_management/slices/ui/ui_slice.test.ts, src/plugins/explore/public/application/utils/state_management/slices/ui/ui_slice.ts, src/plugins/explore/public/application/utils/state_management/store.ts, src/plugins/explore/public/application/utils/state_management/utils/redux_persistence.ts, src/plugins/explore/public/components/query_panel/components/editor_stack/resuable_editor.test.tsx, src/plugins/explore/public/components/query_panel/query_panel.test.tsx, src/plugins/explore/public/components/query_panel/query_panel.tsx, src/plugins/explore/public/components/tabs/tabs.tsx, src/plugins/explore/public/components/visualizations/visualization_container.tsx
1. **UI state pollution**: `status` and transaction state were in UI slice but persisted to URL (ephemeral state shouldn't be bookmarkable)
2. **Performance issue**: `persistReduxState` called on EVERY state change via store subscription, even for non-persisted slices
3. **Misplaced chart state**: `styleOptions` and `chartType` were in UI state but should be tab-specific under visualizations
4. **Unnecessary complexity**: Transaction system was overly complex for simple state updates
5. **Unused state**: `skipInitialFetch` was not used anywhere
- **Created system slice** for ephemeral infrastructure state (`status`) that doesn't persist to URL
- **Replaced store subscription with middleware** that only triggers persistence on specific action types (`query/`, `ui/`, `tab/`, `legacy/`)
- …
=> [Explore] Refactor Explore Redux state and improve persistence performance

src/plugins/navigation/public/top_nav_menu/top_nav_menu.tsx
Before:
After:
offending change: https://github.com/opensearch-project/OpenSearch-Dashboards/commit/627955dfe4ac8831a9ecc255431a264bb4eda253#diff-b293cb9367af92bb97c71d71cae66dcc2b12c26168fc4e4c5cf472334bcb4453R246
=> fix datepicker locaiton in classic experience

src/plugins/explore/public/application/utils/state_management/README.md, src/plugins/explore/public/application/utils/state_management/selectors/index.ts, src/plugins/explore/public/application/utils/state_management/slices/tab/tab_slice.ts, src/plugins/explore/public/application/utils/state_management/slices/ui/ui_slice.test.ts, src/plugins/explore/public/application/utils/state_management/slices/ui/ui_slice.ts, src/plugins/explore/public/application/utils/state_management/utils/redux_persistence.ts
- remove flavor from UI Slice
- We have this hook that retrieves the correct flavor from the app ID: https://github.com/opensearch-project/OpenSearch-Dashboards/blob/query_explore/src/plugins/explore/public/helpers/use_flavor_id/use_flavor_id.ts
- added expliit types on redux_persistence as i missed a flavor there but it was not typed
=> remove flavor from UI Slice

src/plugins/explore/public/application/components/header_dataset_selector.tsx, src/plugins/explore/public/application/utils/state_management/__mocks__/chart_utils.ts, src/plugins/explore/public/application/utils/state_management/__mocks__/data_factories.ts, src/plugins/explore/public/application/utils/state_management/__mocks__/index.ts, src/plugins/explore/public/application/utils/state_management/__mocks__/services.ts, src/plugins/explore/public/application/utils/state_management/__mocks__/store.ts, src/plugins/explore/public/application/utils/state_management/actions/query_actions.test.ts, src/plugins/explore/public/application/utils/state_management/middleware/query_sync_middleware.test.ts, src/plugins/explore/public/application/utils/state_management/middleware/query_sync_middleware.ts
This PR allows recent query to update when dataset is changed:
https://github.com/user-attachments/assets/ca541006-45dc-491e-9401-b436ba5f3a09
- skip
=> [Explore] Allow switch dataset to update recent query

changelogs/fragments/10055.yml, src/plugins/explore/public/components/visualizations/add_to_dashboard_modal.tsx
This pr changes name of add to dashboard modal, new name is save discover title
aligns with
- fix:  change name of add to dashboard modal
=> [Explore] change name of add to dashboard modal

src/plugins/explore/public/application/utils/state_management/middleware/query_sync_middleware.test.ts, src/plugins/explore/public/application/utils/state_management/middleware/query_sync_middleware.ts, src/plugins/explore/public/components/top_nav/top_nav.tsx
Fix a regression bug by updating middleware
- skip
=> [Explore] Fix recent query bug to allow run query update query history via middleware

.github/workflows/version-increment.yml
Adds a GitHub actions workflow to automatically bump the version in package.json once a tag is cut on the repo.
Currently tags are automatically cut by infra team as a post-release action. 
resolves https://github.com/opensearch-project/OpenSearch-Dashboards/issues/7162
Tested in my fork. PRs created:
https://github.com/gaiksaya/OpenSearch-Dashboards/pull/1
https://github.com/gaiksaya/OpenSearch-Dashboards/pull/2
- skip
=> Add auto-version increment workflow

changelogs/fragments/10152.yml, src/plugins/explore/public/components/visualizations/bar/bar_exclusive_vis_options.tsx, src/plugins/explore/public/components/visualizations/bar/bar_vis_config.ts, src/plugins/explore/public/components/visualizations/bar/bar_vis_options.tsx, src/plugins/explore/public/components/visualizations/bar/to_expression.ts
This feature introduces a "Bar Size Control Switch" to the bar chart visualization in OpenSearch Dashboards. It allows users to toggle between "Auto" and "Manual" modes for bar sizing. In "Auto" mode, Vega automatically determines the bar width and padding, optimizing the chart's appearance based on the data. In "Manual" mode, users can specify custom values for barWidth and barPadding through input fields, providing fine-grained control over the bar chart's appearance. This enhances flexibility and usability for customizing bar chart visualizations.
https://github.com/user-attachments/assets/5c64fa68-ad32-49bf-b4cf-37e9c8798701
1. Navigate to the OpenSearch Dashboards Discover Page.
2. Run a PPL query.
3. Open the "Bar Settings" accordion in the style options panel.
4. Verify that a "Bar …
=> Add Bar Size Control Switch

src/plugins/explore/public/application/utils/state_management/store.ts, src/plugins/explore/public/plugin.ts
When switching flavors or opening the explore app, the redux store will be re-created as part of the component mount/unmount lifecycle. The store should get garbage collected, but it might take time. We can reset states in the store to reduce memory usage, since it stores query results that will not be used after unmount.
- skip
=> [explore] reset store when unmounting app

src/plugins/explore/public/application/utils/state_management/actions/query_actions.test.ts
Brought coverage of query_actions from 79% to 100%
```
ananzh@88665a1f0502 OpenSearch-Dashboards % yarn test:jest --coverage --collectCoverageFrom="src/plugins/explore/public/application/utils/state_management/**/*.{ts,tsx}" --testPathPattern=src/plugins/explore/public/application/utils/state_management --coverageReporters=text
yarn run v1.22.21
$ scripts/use_node scripts/jest --coverage '--collectCoverageFrom=src/plugins/explore/public/application/utils/state_management/**/*.{ts,tsx}' --testPathPattern=src/plugins/explore/public/application/utils/state_management --coverageReporters=text
jest-haste-map: duplicate manual mock found: index
The following files share their name; please delete one of them:
* <rootDir>/src/plugins/vis_type_vega/public/expressions/__mocks__/index.ts
* …
```
=> [Explore] Reorganize and rewrite a clean query_actions.test.ts

src/plugins/data/public/ui/dataset_select/_dataset_details.scss, src/plugins/data/public/ui/dataset_select/_dataset_select.scss, src/plugins/data/public/ui/dataset_select/dataset_details.tsx, src/plugins/data/public/ui/dataset_select/dataset_select.tsx
Style updates for visual regressions. Should address the icon being not centered in the select component and then the scroll bar being present always in the explore plugin
Also includes some clean ups and add the click to data source feature in the dataset select details component (the `...`)
n/a
- skip
=> [datasets] style improvements for dataset select

src/plugins/explore/public/application/utils/state_management/actions/set_dataset/set_dataset.test.ts, src/plugins/explore/public/application/utils/state_management/actions/set_dataset/set_dataset.ts
- i noticed when you are on dual query mode, and you switch dataset, it doesn't switch back to single editor. i tried being clever by only dispatching when you need to, but this resulted in bug. so getting rid of that
=> [Explore] Fix set dataset change editor mode

src/plugins/data/public/ui/dataset_select/dataset_select.tsx
When reload page, the query panel is set twice. See before fix video. 
In the fetchDatasets function, lines 113-117 show the problem:
```
if (!initialDatasetSet.current && fetchedDataViews.length > 0) {
setSelectedDataset(fetchedDataViews[0]);
onSelect(fetchedDataViews[0]); // This is calling handleDatasetSelect during initialization!
initialDatasetSet.current = true;
}
```
The DatasetSelect component is automatically calling
onSelect (which is handleDatasetSelect in Explore) during initialization when it sets the first dataset. This happens even during page reload when we already have a dataset from the URL.
Before fix, call handleDatasetSelect in Explore then clearEditor() will reset the query panel
https://github.com/user-attachments/assets/07a5769e-45e3-43f0-a45e-9e01752b7a2e
After …
=> Fix explore plugin query panel reset on page reload due to DatasetSelect initialization

package.json, yarn.lock
Manual backport https://github.com/opensearch-project/OpenSearch-Dashboards/pull/9546 to 2.19
- skip
=> [Manual Backport 2.19] Fix GHSA-vjh7-7g9h-fjfh by bumping elliptic

changelogs/fragments/10251.yml, src/plugins/explore/public/components/experience_banners/classic_experience_banner/classic_experience_banner.scss, src/plugins/explore/public/components/experience_banners/new_experience_banner/new_experience_banner.scss
Issue - Fonts in the callout banner render too small and the vertical alignment is not centered.
Fix - Font size  changed to 14 px and  vertical center alignment for banner text.
Before - 
After
- fix: Fix font size and center alignment for banner text.
=> Fix banner text font and alignment

changelogs/fragments/10240.yml, src/core/public/chrome/nav_group/nav_group_service.ts
Previously we use 
```
extends Pick<App, 'euiIconType' | 'icon'>
```
And euiIconType / icon becomes required parameters for add applications into nav group. Change the type so that `euiIconType / icon` keep optional.
- fix: [Left navigation] fix: type to allow euiIconType / icon to be undefined
=> [Left navigation] fix: type to allow euiIconType / icon to be undefined

baselines/lighthouse_baseline.json, changelogs/fragments/10254.yml
The baseline limit for discover and dashboard has increased, so failing the lighthouse ci.  This fix would reset the baseline.
Note: Also, we gotta dig into performance degradation in discover and dashboard separately
- fix: Update lighthouse baseline limit for dashboard and discover
=> Reset baseline limit for dashboard and discover

changelogs/fragments/10260.yml, src/plugins/explore/public/application/utils/languages/ppl/get_query_string_with_source/get_query_with_source.test.ts, src/plugins/explore/public/application/utils/languages/ppl/get_query_string_with_source/get_query_with_source.ts
- we currently support the omission of "source = *". We magically append "source = *" when it is omitted. However, the times we don't append is if the query starts with:
```
source = *
search source = *
describe *
```
But we also need to not append if the query starts with:
```
show *
```
Ref: https://github.com/opensearch-project/sql/blob/main/docs/user/ppl/cmd/showdatasources.rst
- fix: do not append `source = *` when query starts with `show *`
=> [Explore] handle the PPL query that starts with "show"

changelogs/fragments/10259.yml, src/plugins/explore/public/components/query_panel/query_panel_editor/query_panel_editor.scss, src/plugins/explore/public/components/query_panel/query_panel_generated_query/query_panel_generated_query.scss, src/plugins/explore/public/components/query_panel/query_panel_generated_query/query_panel_generated_query.tsx
- some complain that the "Edit query" button was too far away from the generated PPL. Now it is right next to it. Also changed it from button to EuiBadge
- When text is normal length:
- when text is overflowing:
- refactor: change query editor ui
=> [Explore] minor update on the edit query placement

changelogs/fragments/10281.yml, src/plugins/explore/public/application/utils/hooks/use_url_state_sync.ts, src/plugins/explore/public/components/fields_selector/discover_field_header.tsx
1. On new discover, changing time filter reset url state, this commit fixed the issue
2. Also fixed a console warning for no title on ButtonIcon component
https://github.com/user-attachments/assets/8f42abe9-4c88-44aa-ac11-03685c192449
- fix: url state lost when changing time filter on new discover
- fix: console warning of no title on ButtonIcon component
=> [Explore] fix osd url state not synced correctly

changelogs/fragments/10322.yml, cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/explore/02/saved_queries.spec.js, cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/explore/05/recent_queries.spec.js, src/plugins/explore/public/components/top_nav/utils/validate_time_range.test.ts
Cigroup 12 failure due to: saved query failed to load saved time filter bug
Cigroup 15 failure due to: change in behavior of recent query(default query no longer is included in the recent query)
also include changes from @TackAdam's PR to fix the ciGroup4 failure: https://github.com/opensearch-project/OpenSearch-Dashboards/pull/10319/files
Thanks @kavilla for helping on fixing tests and enabling back cypress test videos. https://github.com/opensearch-project/OpenSearch-Dashboards/pull/10269/commits/b63bf5df0992c577cb25dfaefb468d83e762adae
- fix: fix cigroup 12 and 15
=> [TEST] Fix cigroup 12 and 15

src/plugins/query_enhancements/server/routes/resources/routes.test.ts, src/plugins/query_enhancements/server/routes/resources/routes.ts
This is a follow up improvement for https://github.com/opensearch-project/OpenSearch-Dashboards/pull/9770. It adds ResourcesRequest API type and includes `errorObj.message` in the response.
mostly type changes. updated unit test
- skip
=> [Query Enhancements] improve resources API type definition

changelogs/fragments/10332.yml, src/plugins/explore/public/components/top_nav/top_nav_links/top_nav_new/top_nav_new.test.ts, src/plugins/explore/public/components/top_nav/top_nav_links/top_nav_new/top_nav_new.ts
The "New" button in the Explore plugin's top navigation had URL state management issues when transitioning from saved explore views back to a clean state. After clicking "New" from a saved explore, the URL would retain the saved explore ID (/#/view/{savedId}) instead of navigating to the clean state (/#/).
**Root cause:** The `getNewButtonRun` function only reset Redux state via `resetExploreStateActionCreator` but did not handle URL navigation. 
This PR added URL navigation to the "New" button handler to ensure complete state reset:
```
if (services.scopedHistory) {
services.scopedHistory.push('/');
}
```
NA
https://github.com/user-attachments/assets/55684511-9462-4078-9705-41fe5d0c914f
- fix: [Explore] Fix New button URL state management issue
=> [Explore] Fix New button URL state management issue

changelogs/fragments/10333.yml, src/plugins/query_enhancements/common/utils.test.ts, src/plugins/query_enhancements/common/utils.ts, src/plugins/query_enhancements/public/search/filters/filter_utils.test.ts
Fixed PPL queries to include millisecond precision when filtering by timestamp fields. Previously, milliseconds were stripped from date filters, preventing precise time-based queries.
NA
* Before
```
WHERE timestamp >= '2025-07-30 20:30:31' AND timestamp <= '2025-07-30 20:30:31'
```
* After  
```
WHERE timestamp >= '2025-07-30 20:30:31.567' AND timestamp <= '2025-07-30 20:30:31.580'
```
https://github.com/user-attachments/assets/954122ea-ddf2-459f-8f32-0e38af582cf8
- Verified with test data containing millisecond differences
- Date picker with millisecond precision now works correctly with PPL queries
- Network requests show milliseconds in WHERE clauses
- Precise filtering returns expected document counts
- fix: Fix PPL query millisecond precision in date filtering
=> Fix PPL query millisecond precision in date filtering

changelogs/fragments/10336.yml, src/plugins/explore/public/components/top_nav/top_nav.tsx
In the Explore plugin, when users select date ranges from the date picker's "Quick select", "Commonly used", or "Recently used date ranges" options, the query execution button remains as "REFRESH" instead of changing to "UPDATE". 
The issue stems from the date picker event handling logic in query_bar_top_row.tsx. When isQuickSelection is true (for quick select options), the date picker calls onSubmit instead of onChange, which bypasses the handleQueryChange callback that dispatches setDateRange to update the Redux state.
**Before fix**
* Manual changes: onChange → handleQueryChange → setDateRange → Redux updated → Button shows "UPDATE" ✅
* Quick selections: onSubmit → handleQuerySubmit → Bypasses setDateRange → Redux not updated → Button stays "REFRESH" ❌
This PR modified the …
=> [Explore] Fix query execution button issue when use using date picker quick selections

changelogs/fragments/10337.yml, src/plugins/explore/public/components/query_panel/query_panel_generated_query/query_panel_generated_query.scss, src/plugins/explore/public/components/query_panel/query_panel_generated_query/query_panel_generated_query.test.tsx, src/plugins/explore/public/components/query_panel/query_panel_generated_query/query_panel_generated_query.tsx
- before, the generated query had a line-height set to 1, and it would show ellipses if overflowing. Now we are going to make it scrollable if needed, and never ellipses:
- refactor: change generated query UI
=> [Explore] Refactor generated query to have max height and scrollable

changelogs/fragments/10345.yml, src/plugins/data_explorer/public/utils/state_management/metadata_slice.ts
The issue was in the data-explorer's metadata slice (metadata_slice.ts). When no index patterns exist, the `data.indexPatterns.getDefault()` method throws an error instead of gracefully returning undefined. This error occurred during the data-explorer's preload phase, preventing the entire application from loading properly and stopping the discover plugin from running its conditional logic to show the no-index-patterns UI.
This PR wrapped the data.indexPatterns.getDefault() call in a try-catch block so we could continue with undefined instead of crashing the application. This ensures that when no index patterns exist, the discover plugin can properly render the DiscoverNoIndexPatterns component as intended.
When navigating to the discover plugin with no index patterns, the application …
=> Fix: Discover plugin shows empty page instead of no-index-patterns UI when no index patterns

changelogs/fragments/10347.yml, src/plugins/explore/public/components/query_panel/query_panel_widgets/language_reference/language_reference.scss, src/plugins/explore/public/components/query_panel/query_panel_widgets/language_reference/language_reference.test.tsx, src/plugins/explore/public/components/query_panel/query_panel_widgets/language_reference/language_reference.tsx
- don't throw error in language reference
- add tooltips for this button
- disable button for when we encountered unhandled language
- feat: add tooltip for language reference in explore
=> [Explore] add tooltip to language reference and don't throw error

changelogs/fragments/10360.yml, src/plugins/explore/public/components/tabs/tabs.tsx
Add error boundary to tab content
- chore: Add error boundary to tab content on Explore page
=> [Explore] add error boundary to tab content

changelogs/fragments/10357.yml, src/plugins/explore/public/application/utils/hooks/use_initial_query_execution.test.tsx, src/plugins/explore/public/application/utils/hooks/use_initial_query_execution.ts, src/plugins/explore/public/application/utils/hooks/use_page_initialization.ts, src/plugins/explore/public/components/query_panel/query_panel_widgets/language_reference/language_reference.tsx, src/plugins/explore/public/components/top_nav/top_nav.tsx, src/plugins/explore/public/components/visualizations/add_to_dashboard_button.tsx, src/plugins/explore/public/helpers/save_explore.ts
1. Fixed an issue that the updated query not properly apply when with the snapshot url of a saved search
2. Fixed an issue that the query reset to empty after saving a saved search
Before:
https://github.com/user-attachments/assets/4bc4c807-138c-4a51-9c60-8a05c6045ef6
https://github.com/user-attachments/assets/81674cc0-42a7-424a-9a71-52b3177e7ded
After:
https://github.com/user-attachments/assets/c0dcf8fc-4a82-4fc8-b177-62f9414ca186
- fix: the updated query not properly apply when with the snapshot url of a saved search
- fix: the query reset to empty after saving a saved search
=> [Explore] fix url state not properly synced with saved search

changelogs/fragments/10363.yml, packages/osd-monaco/src/ppl/language.ts, src/plugins/explore/public/components/query_panel/query_panel_editor/use_query_panel_editor/editor_options/query_editor_options.ts
Currently if we switch from PPL to AI mode and then back to PPL, the syntax highlighting does n't work. This fixes the issue.
https://github.com/user-attachments/assets/6a2c032e-6eab-4ed9-a6b7-b875e620c15c
- fix: Error Highlighting after switching languages
=> Fix Error Highlighting after switching languages

changelogs/fragments/10366.yml, src/plugins/explore/public/application/utils/state_management/actions/reset_legacy_state/index.ts, src/plugins/explore/public/application/utils/state_management/actions/reset_legacy_state/reset_legacy_state.test.ts, src/plugins/explore/public/application/utils/state_management/actions/reset_legacy_state/reset_legacy_state.ts, src/plugins/explore/public/application/utils/state_management/middleware/dataset_change_middleware.test.ts, src/plugins/explore/public/application/utils/state_management/middleware/dataset_change_middleware.ts, src/plugins/explore/public/application/utils/state_management/utils/redux_persistence.ts
- i got a bug ticket where if you are on one dataset, you select some columns, switch dataset, and download CSV, the old selected columns appear
- This was because we were not resetting the legacy state in redux. This resets it
- fix: Reset legacy state when switching dataset
=> [Explore] reset legacy state when changing dataset

changelogs/fragments/10325.yml, src/plugins/banner/public/components/global_banner.tsx
This PR ensures the banner dismissal persists for the current session.  
The hidden state is stored in `sessionStorage` and respected on reload.  
Verified working in both standard and private browser sessions.
- fixes: Banner dismissal not persisting after page reloads
1. Start OpenSearch Dashboards.
2. Enable a global banner.
3. Dismiss the banner by clicking the close button.
4. Refresh the page — verify the banner remains hidden.
5. Test the same flow in a private/incognito browser window.
6. Clear sessionStorage manually, refresh, and verify the banner reappears.
- fix: Persist banner dismissal across session reloads using sessionStorage
=> [Banner Plugin] Add cache for banner hide

changelogs/fragments/10370.yml, src/plugins/explore/public/application/utils/state_management/actions/query_editor/run_query/run_query.test.ts, src/plugins/explore/public/application/utils/state_management/actions/query_editor/run_query/run_query.ts
Allow Refresh to run query
NA
NA
- fix: [Explore] Allow Refresh to run query
=> [Explore] Allow Refresh to run query

changelogs/fragments/10369.yml, src/plugins/explore/public/components/visualizations/visualization_builder.test.ts, src/plugins/explore/public/components/visualizations/visualization_builder.ts, src/plugins/explore/public/plugin.ts
Users encounter a navigation scope error when:
1. navigate to app/explore/logs/ 
2. run any query
3. navigate to "Assets" page
4. Filter "explore" type of object
5. Click an explore object to navigate to new discover
6. Click "Update" button
The issue stems from the **VisualizationBuilder ** retaining stale references to inactive ScopedHistory instances across navigation cycles.
The fix is to implement complete cleanup of the `VisualizationBuilder` singleton on plugin unmount to ensure fresh instances are created with active `ScopedHistory` references.
Before fix:
https://github.com/user-attachments/assets/44348cbb-03a5-476a-afa5-4adbdcd4ceff
After fix:
https://github.com/user-attachments/assets/31b6398e-98fe-40e1-8285-1853c5a1d7b8
- fix: [Explore] Resolve ScopedHistory navigation scope …
=> [Explore] Resolve ScopedHistory navigation scope error in explore plugin

changelogs/fragments/10362.yml, src/plugins/explore/public/components/fields_selector/discover_sidebar.scss, src/plugins/explore/public/components/fields_selector/discover_sidebar.test.tsx, src/plugins/explore/public/components/fields_selector/discover_sidebar.tsx, src/plugins/explore/public/components/fields_selector/facet_field.test.tsx, src/plugins/explore/public/components/fields_selector/facet_field.tsx, src/plugins/explore/public/components/fields_selector/facet_list.test.tsx, src/plugins/explore/public/components/fields_selector/facet_list.tsx, src/plugins/explore/public/components/fields_selector/facet_value.scss, src/plugins/explore/public/components/fields_selector/facet_value.test.tsx, src/plugins/explore/public/components/fields_selector/facet_value.tsx, src/plugins/explore/public/components/fields_selector/field_list.test.tsx, src/plugins/explore/public/components/fields_selector/field_list.tsx, src/plugins/explore/public/components/fields_selector/lib/group_fields.test.ts, src/plugins/explore/public/components/fields_selector/lib/group_fields.ts
What are facets?
To help users quickly narrow down their search data, facets will provide access filtering commonly understood fields. Currently, we are introducing 3 default facet field(`serviceName`/`span.attributes.http@status_code`/`status.code`).
This PR introduces the UI components of facets filter.
https://github.com/user-attachments/assets/73bc6a9a-8e5f-4340-90bf-d21b96245f8b
- feat: Introduce facet filter
=> [Explore] Introduce facet filter

changelogs/fragments/10358.yml, src/plugins/explore/public/components/visualizations/area/area_vis_options.test.tsx, src/plugins/explore/public/components/visualizations/area/area_vis_options.tsx, src/plugins/explore/public/components/visualizations/area/to_expression.test.ts, src/plugins/explore/public/components/visualizations/area/to_expression.ts, src/plugins/explore/public/components/visualizations/bar/bar_vis_options.test.tsx, src/plugins/explore/public/components/visualizations/bar/bar_vis_options.tsx, src/plugins/explore/public/components/visualizations/bar/to_expression.test.ts, src/plugins/explore/public/components/visualizations/bar/to_expression.ts, src/plugins/explore/public/components/visualizations/heatmap/heatmap_vis_options.test.tsx, src/plugins/explore/public/components/visualizations/heatmap/heatmap_vis_options.tsx, src/plugins/explore/public/components/visualizations/line/line_vis_options.test.tsx, src/plugins/explore/public/components/visualizations/line/line_vis_options.tsx, src/plugins/explore/public/components/visualizations/line/to_expression.test.ts, src/plugins/explore/public/components/visualizations/line/to_expression.ts, src/plugins/explore/public/components/visualizations/pie/pie_vis_options.tsx, src/plugins/explore/public/components/visualizations/scatter/scatter_vis_options.test.tsx, src/plugins/explore/public/components/visualizations/scatter/scatter_vis_options.tsx, src/plugins/explore/public/components/visualizations/style_panel/legend/legend.test.tsx, src/plugins/explore/public/components/visualizations/style_panel/legend/legend.tsx, src/plugins/explore/public/components/visualizations/utils/utils.test.ts, src/plugins/explore/public/components/visualizations/utils/utils.ts
This PR updates date format in the chart tooltip. This change automatically determines the appropriate time unit (e.g., seconds, minutes, days) based on the actual timestamp values in the dataset.
1. Create area/line/bar charts with temporal fields using data with different time granularities (e.g., seconds, minutes, days, months).
2. Hover over data points and verify that the tooltip date format adjusts to match the inferred precision from the dataset.
3. Confirm that fallback formatting (%b %d, %Y %H:%M:%S) is applied when inference fails.
- fix: infer tooltip date format dynamically
=> [Explore] Infer tooltip date format dynamically

packages/osd-monaco/src/xjson/lexer_rules/index.ts, src/plugins/data/public/antlr/prompt/code_completion.test.ts, src/plugins/data/public/antlr/prompt/code_completion.ts, src/plugins/data/public/autocomplete/providers/query_suggestion_provider.ts, src/plugins/data/public/plugin.ts, src/plugins/explore/public/components/query_panel/query_panel_editor/use_query_panel_editor/editor_options/prompt_editor_options.ts, src/plugins/explore/public/components/query_panel/query_panel_editor/use_query_panel_editor/use_query_panel_editor.test.ts, src/plugins/explore/public/components/query_panel/query_panel_editor/use_query_panel_editor/use_query_panel_editor.ts
Features of AI Mode Auto Suggest
- Auto suggest is not triggered automatically and needs to be triggered by user explicitly using (ctrl + space)
- Auto suggest is not context aware, by default will suggest Commands and Field Names, But after a `=` will suggest a fieldValue is the ColumnName is valid
https://github.com/user-attachments/assets/99efd451-fbbb-4c00-9adf-504a4555454f
- feat: Add Autosuggest for AI Mode
=> Add Autosuggest for AI Mode

changelogs/fragments/10378.yml, package.json, yarn.lock
Bump pbkdf2 from 3.1.2 to 3.1.3
Add resolution for form-data and set to 4.0.4
CVE-2025-6545
CVE-2025-7783
- security: [CVE-2025-6545][CVE-2025-7783] Bump pbkdf2 from 3.1.2 to 3.1.3 and set form-data to 4.0.4
=> [CVE-2025-6545][CVE-2025-7783] Bump pbkdf2 from 3.1.2 to 3.1.3 and set form-data to 4.0.4

changelogs/fragments/10379.yml, src/plugins/data/public/ui/dataset_select/dataset_select.tsx, src/plugins/data/public/ui/dataset_selector/advanced_selector.tsx, src/plugins/data/public/ui/dataset_selector/dataset_explorer.tsx, src/plugins/explore/common/config.ts, src/plugins/explore/public/build_services.ts, src/plugins/explore/public/components/query_panel/query_panel_widgets/dataset_select/dataset_select.tsx, src/plugins/explore/public/types.ts
By default if no prop is passed then it will display all the types. But if the props are passed in it will only display the supported types by datasetTypeConfig.type
Also, includes the update for explore plugin to set this to only support `INDEXES` and `INDEX_PATTERN`. this is configurable with `explore.supportedTypes`
n/a
From Discover:
From Explore:
- feat: allow apps to configure available types in the dataset explorer
=> [datasets] allow apps to configure available types in the explorer

changelogs/fragments/10406.yml, src/plugins/explore/common/index.ts, src/plugins/explore/public/application/utils/state_management/actions/reset_legacy_state/reset_legacy_state.test.ts, src/plugins/explore/public/application/utils/state_management/actions/reset_legacy_state/reset_legacy_state.ts, src/plugins/explore/public/application/utils/state_management/utils/redux_persistence.test.ts, src/plugins/explore/public/application/utils/state_management/utils/redux_persistence.ts, src/plugins/explore/server/plugin.ts, src/plugins/explore/server/trace_ui_settings.ts
Add experimental default trace columns UI setting for Explore traces tab and apply it.
Add the default columns only to trace page:
https://github.com/user-attachments/assets/0afba0d0-0066-43dc-8d5d-e35cd20fbbba
-feat: Add experimental default trace columns UI setting for Explore traces tab and apply it.
=> [Explore] Traces - Trace default columns UI setting

changelogs/fragments/10408.yml, packages/osd-monaco/src/ppl/constants.ts, src/plugins/data/public/antlr/opensearch_ppl/code_completion.ts, src/plugins/data/public/antlr/opensearch_ppl/code_completion_simplified.test.ts, src/plugins/data/public/antlr/shared/utils.test.ts, src/plugins/data/public/antlr/shared/utils.ts
While using, Column Names containing @ and . , The insertion of these fields in the editor always threw an error, also we didn't get any value suggestions for such Column. 
This PR improves the insertion text of such columnName by adding `` to escape the special characters and made similar changes while fetching the values.
https://github.com/user-attachments/assets/8cd98849-d3cc-4705-b578-30cd4e87aff9
- fix: Value Suggestions for Columns containing @ and .
=> Fix Value Suggestions for Columns containing @ and .

.vscode/launch.json, changelogs/fragments/10426.yml
Signed-off-by: Huy Nguyen <73027756+huyaboo@users.noreply.github.com>
This change adds some common OSD run configurations for VSCode users. This allows for quick one-click launches with debugging capabilities:
1. Start the Dashboards server only (with default yml configurations)
2. Start the OpenSearch snapshot cluster only
3. Start both Dashboards and OpenSearch snapshot cluster together (for a one-click end-to-end debugging environment) 
Related to #9688
Ran the configurations in my VSCode IDE instance
- chore: add common Dashboards run configurations
=> Add common VSCode launch configurations to `launch.json`

changelogs/fragments/10430.yml, src/core/public/keyboard_shortcut/key_parser.ts, src/core/public/keyboard_shortcut/keyboard_shortcut_service.test.ts, src/core/public/keyboard_shortcut/keyboard_shortcut_service.ts
The PR is about add environment-based conditional logging to keyboard shortcut conflict warnings to prevent them from appearing in production builds while preserving them for development debugging.
Added `process.env.NODE_ENV !== 'production'` condition around `console.warn` in keyboard shortcut service
Updated the throw error message for invalid keyString
- fix: Update the console warn and throw error message
=> [Keyboard-shortcuts] Suppress keyboard shortcut conflict warnings in production builds

changelogs/fragments/10444.yml, src/plugins/explore/public/components/container/bottom_container/bottom_right_container/bottom_right_container.test.tsx, src/plugins/explore/public/components/container/bottom_container/bottom_right_container/bottom_right_container.tsx
Temporarily aisabling charts on Traces page, because currently these charts are built base on query result which is restricted by the query response size(`ppl` currently has limit on response with first 10k result), we want to move aggregation query base implementation, which will imrove the accuracy against large size data but will add cost by making extra query.
- chore: Disable charts in traces
=> [Explore] disable charts in traces

changelogs/fragments/10467.yml, src/plugins/vis_type_vega/public/vega_view/vega_base_view.js, src/plugins/vis_type_vega/public/vega_view/vega_tooltip.js
The Vega visualization tooltip was flashing when mouse over the chart, this PR fixed the issue, see screen records:
Before:
https://github.com/user-attachments/assets/d8fb119b-c081-44d8-a1b9-427eecc9bb4d
After:
https://github.com/user-attachments/assets/f0df19b9-dc70-4afd-b017-2b4c2332563a
- fix: vega visualization tooltip flashing when mouse move
=> [visTypeVega] Fix vega tooltip flashing

changelogs/fragments/10483.yml, src/core/public/mocks.ts, src/plugins/dashboard/public/application/components/dashboard_top_nav/__snapshots__/dashboard_top_nav.test.tsx.snap, src/plugins/explore/public/components/fields_selector/discover_field.test.tsx, src/plugins/explore/public/components/fields_selector/discover_field.tsx, src/plugins/explore/public/components/fields_selector/discover_field_bucket.tsx, src/plugins/explore/public/components/fields_selector/discover_field_details.test.tsx, src/plugins/explore/public/components/fields_selector/discover_field_details.tsx, src/plugins/explore/public/components/fields_selector/discover_field_header.tsx, src/plugins/explore/public/components/fields_selector/discover_sidebar.test.tsx, src/plugins/explore/public/components/fields_selector/discover_sidebar.tsx, src/plugins/explore/public/components/fields_selector/facet_field.test.tsx, src/plugins/explore/public/components/fields_selector/facet_field.tsx, src/plugins/explore/public/components/fields_selector/facet_list.test.tsx, src/plugins/explore/public/components/fields_selector/facet_list.tsx, src/plugins/explore/public/components/fields_selector/facet_value.tsx, src/plugins/explore/public/components/fields_selector/field_list.test.tsx, src/plugins/explore/public/components/fields_selector/field_list.tsx, src/plugins/explore/public/components/fields_selector/fields_selector_panel.tsx, src/plugins/explore/public/components/fields_selector/lib/field_calculator.test.ts, src/plugins/explore/public/components/fields_selector/lib/field_calculator.ts, src/plugins/explore/public/components/fields_selector/lib/field_filter.ts, src/plugins/explore/public/components/fields_selector/lib/get_details.ts, src/plugins/explore/public/components/fields_selector/lib/get_index_pattern_field_list.ts, src/plugins/explore/public/components/fields_selector/lib/get_warnings.ts, src/plugins/explore/public/components/fields_selector/lib/group_fields.ts, src/plugins/explore/public/components/fields_selector/lib/visualize_trigger_utils.ts
Update fields selector component interface to consume `DataView`/`DataSet` instead of `IndexPattern`.
- chore: Update dataset interface in fields selector component
=> [Explore] Update dataset interface in fields selector component

cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/explore/04/discover_traces.spec.js, cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/explore/04/traces.spec.js, cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/explore/04/traces_sanity.spec.js, cypress/utils/commands.explore.js, cypress/utils/commands.osd.js, cypress/utils/index.d.ts
- refactor some cypress custom commands for traces
- Move `setupWorkspaceAndDataSourceWithTraces` and `cleanupWorkspaceAndDataSourceAndTraces` to `explore` as these are `explore`-specific features
- add types for the two above
- Remove `navigateToTracesViaLogsUrl`
- add test to verify default columns
- add tests for correct tabs
- tests for facted fields
- tests for expansion of the trace row and gantt chart
- skip
=> [Traces] Add tests for Traces Page

changelogs/fragments/10528.yml, src/plugins/workspace/server/saved_objects/workspace_ui_settings_client_wrapper.test.ts, src/plugins/workspace/server/saved_objects/workspace_ui_settings_client_wrapper.ts
When global config setting does not exist, the wrapped update / get function will throw not found error, triggering the upgrade process which will finally calls `savedObjectsClient.create('config', '<current_workspace>_3.1.0')`, resulting in a saved object with id: <current_workspace>_3.1.0. And the workspace level config update will fail due to doc conflict check.
https://github.com/user-attachments/assets/d80a37ed-28c4-44b6-95d9-a1a487f9bae0
https://github.com/user-attachments/assets/2960a070-5dd5-45ae-9129-0a7e3d35531a
- fix: make global setting nullable when getting / updating workspace scope settings
=> fix: make global setting nullable when getting / updating workspace scope settings

changelogs/fragments/10532.yml, src/plugins/explore/public/components/tabs/error_guard/error_guard.tsx
The error ui was broken for result table.
Fix - 
The css class name was applied wrong which is reverted in the pr now.
Previous
After Fix -
Dekstop
- fix: Fix result table error ui
=> Fix result table error ui

changelogs/fragments/10540.yml, src/plugins/explore/public/application/register_tabs.ts, src/plugins/explore/public/components/patterns_table/utils/utils.test.ts, src/plugins/explore/public/components/patterns_table/utils/utils.ts, src/plugins/explore/public/components/tabs/error_guard/error_guard.tsx, src/plugins/explore/public/components/tabs/error_guard/patterns_error_guard.test.tsx, src/plugins/explore/public/components/tabs/error_guard/patterns_error_guard.tsx, src/plugins/explore/public/components/tabs/patterns_tab.tsx
Invalid query doesn't error out the page anymore (the 'errors' popping up from an incorrect query were not thrown as before), and now there is a UI page that shows the pattern query attempted.
- feat: Custom patterns error page
- fix: Prevent general query error from hiding tabs
=> [Explore] Patterns tab Error Handling updates

changelogs/fragments/10548.yml, src/plugins/explore/public/components/visualizations/theme/default_colors.ts
Enable experimental discover visualization theme by adding this to localStroage: `__DEVELOPMENT__.discover.vis.theme: experimental`, this is just for development purpose so we can rollout discover visualization theme changes which are depended by subsequence PRs without changing the current vis color palettes.
- refactor: add a flag to config discover vis theme from localStorage for development
=> [Explore] add a flag to config discover vis theme from localStorage for development

changelogs/fragments/10557.yml, src/plugins/explore/public/application/pages/logs/logs_page.tsx
Currently Discover shows a blank page when there is associated datasource (opensearch cluster) but no index-pattern. This is confusing to the user, because they should be able to still search the cluster using `Indexes` without creating an index-pattern, but they must create an index pattern first in order to see the dataset picker that will be used to pick `Indexes`.
This PR allows selecting/creating a dataset when there's no current dataset selected.
- feat: show query panel in Explore even if there are no datasets
=> [Explore] show query panel even if there are no datasets

changelogs/fragments/10573.yml, src/plugins/explore/public/application/utils/languages/ppl/default_prepare_ppl_query/default_prepare_ppl_query.test.ts, src/plugins/explore/public/application/utils/languages/ppl/get_query_string_with_source/get_query_with_source.test.ts, src/plugins/explore/public/application/utils/languages/ppl/get_query_string_with_source/get_query_with_source.ts
- when you create an index pattern of pattern "*", the auto-injection of `source=*` breaks because that is not recognized. So we are adding backticks to make it work
- chore: add backticks when source is omitted
=> [Explore] backtick the dataset name when source=* and describe=* is omitted

changelogs/fragments/10584.yml, src/plugins/discover/public/application/components/default_discover_table/table_cell.tsx, src/plugins/explore/public/application/legacy/discover/application/components/default_discover_table/table_cell.tsx, src/plugins/explore/public/components/data_table/table_cell/table_cell.tsx
This PR, 
Replaced plusInCircle → magnifyWithPlus
Replaced minusInCircle → magnifyWithMinus
Now all filter action buttons consistently use magnifyWithPlus and magnifyWithMinus icons across:
- Table cell hover overlays
- Expanded table row views
- Both explore and discover plugins
Explore 
Discover - 
- fix: Inconsistent icons in table fields
=> Fix inconsistent icons in table fields

changelogs/fragments/10590.yml, src/plugins/vis_type_vega/config.ts
Change the flag `exposeDebugObjectToWindow` which was introduced by https://github.com/opensearch-project/OpenSearch-Dashboards/pull/10511 default value to `true` to make it backward compatible
- chore: change exposeDebugObjectToWindow default value to true
=> vis(vega): default set flag exposeDebugObjectToWindow to true

changelogs/fragments/10598.yml, src/plugins/explore/public/application/utils/languages/ppl/get_query_string_with_source/get_query_with_source.test.ts, src/plugins/explore/public/application/utils/languages/ppl/get_query_string_with_source/get_query_with_source.ts
The PPL grammar defines searchCommand as follows
```
searchCommand
: (SEARCH)? (searchExpression)* fromClause? (searchExpression)*     # searchFrom
```
However when we write a query 
```
`attributes.EnvName` = "Production" SOURCE = logs-otel-v1* 
```
It gives no result. 
The issue lies with us appending source = <dataset> at the beginning of the query. 
Query Being sent:
```
"source = logs-otel-v1* `attributes.EnvName` = \"Production\" SOURCE = logs-otel-v1* | WHERE `time` >= '2024-06-23 17:39:57.609' AND `time` <= '2025-09-23 17:39:57.609'"
```
This treats the second SOURCE as a column name creating failures.
This PR fixes the Source Command detection Logic, expanding the logic to check the first | and check if it contains source = or not.
Before: …
=> Fix source command detection if we have a field expression before source

changelogs/fragments/10613.yml, packages/osd-optimizer/src/worker/run_worker.ts, scripts/build_opensearch_dashboards_platform_plugins.js
CI/CD workflows are failing with the following errors:
* Module Not Found Error:
```
Error: Cannot find module '@osd/optimizer/target/cli'
Require stack:
- /path/to/OpenSearch-Dashboards/scripts/build_opensearch_dashboards_platform_plugins.js
```
This occurs because the build_opensearch_dashboards_platform_plugins.js script directly requires @osd/optimizer/target/cli without ensuring the optimizer package has been built first. While yarn osd bootstrap should build all packages, it sometimes fails silently in CI environments, especially on Windows. 
Try to modify scripts/build_opensearch_dashboards_platform_plugins_safe.js which checks if @osd/optimizer/target/cli exists before requiring it. Automatically builds the optimizer package if missing using `yarn workspace @osd/optimizer build`. …
=> Fix CI/CD failure: Cannot find module @osd/optimizer/target/cli

changelogs/fragments/10608.yml, src/plugins/explore/public/application/pages/traces/trace_details/public/traces/span_detail_table.test.tsx, src/plugins/explore/public/application/pages/traces/trace_details/public/traces/span_detail_table.tsx
Fixes a bug where undefined spans are not handled properly when paginating through the span detail table. 
Before: 
After:
- fix: handle undefined items in span table
=> Trace:Details Handle undefined items in span table

cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/explore/05/autocomplete_ui.spec.js, cypress/utils/apps/explore/autocomplete.js, src/plugins/data/public/antlr/opensearch_ppl/code_completion.ts, src/plugins/data/public/antlr/opensearch_ppl/code_completion_simplified.test.ts, src/plugins/data/public/plugin.ts, src/plugins/data/public/query_snippet_suggestions/ppl/suggestions.test.ts, src/plugins/data/public/query_snippet_suggestions/ppl/suggestions.ts, src/plugins/data/public/query_snippet_suggestions/types.ts, src/plugins/data/public/query_snippet_suggestions/utils.test.ts, src/plugins/data/public/query_snippet_suggestions/utils.ts, src/plugins/data/public/services.ts
This PR aims at introducing Query Snippet Suggestions to the Autocomplete Service for Explore. 
We would like the augment autocomplete suggestions for users based on the past queries of users stored as Saved Searches, Recent Queries and Saved Queries. 
**Architecture:**
**Flow Diagram**
https://github.com/user-attachments/assets/36c200ce-1875-4bd7-8285-0246fa3752a8
- feat: Add Query Snippet Suggestions to Autocomplete
=> Add Query Snippet Suggestions

changelogs/fragments/10621.yml, src/plugins/explore/public/application/utils/state_management/actions/query_actions.test.ts, src/plugins/explore/public/application/utils/state_management/actions/query_actions.ts
The Column Value Caching was broken due to the wrong params being passed.
https://github.com/user-attachments/assets/2924fb79-a118-4165-9471-2da1dcec0a63
The first suggestions are the values from the hits cached, the next set are fetched from API call and cached for subsequent calls. 
- fix: Column Value Caching for Autocomplete
=> Fix Column Value Caching for Autocomplete

changelogs/fragments/10597.yml, src/plugins/explore/public/components/query_panel/query_panel_widgets/dataset_select/dataset_select.test.tsx, src/plugins/explore/public/components/query_panel/query_panel_widgets/dataset_select/dataset_select.tsx
- when switching dataset, clear editor when switching dataset. We already set the query service to be an empty string, now we gotta do so for the query editor
- fix: clear editor after dataset change in explore
=> [explore] clear editor after datset change

changelogs/fragments/10595.yml, src/plugins/console/public/application/containers/settings.tsx
- be able to update console_polling through the UI. The dataset was not being passed and an error would occur
- closes #10544 
- fix: Allow updating of console_polling through the UI
=> be able to update console_polling through the UI

changelogs/fragments/10618.yml, package.json, yarn.lock
Resolves CVE-2025-7783
- chore: Bumps cypress-request to 3.0.9
=> Bumps cypress-request to 3.0.9

changelogs/fragments/10629.yml, src/plugins/explore/public/components/doc_viewer/trace_details_view/trace_details_view.tsx
Enhances the trace detail page timeline loading state by adding a centered loading spinner with text feedback. This improves user experience by providing clear visual indication when the timeline data is being fetched.
Before
After
To verify this change:
1. Navigate to the trace detail page
2. Clear browser cache or use network throttling to slow down data loading
3. Verify that:
- A centered loading spinner appears while timeline data loads
- "Loading..." text is displayed below the spinner
- Spinner and text are properly centered on the page
- Loading state is replaced by timeline content once data loads
- feat: improve timeline loading state with spinner
=> feat(trace-details): improve timeline loading state with spinner

changelogs/fragments/10582.yml, src/plugins/explore/public/components/fields_selector/field_list.tsx
Changed the React key from field.name + index to just field.name since:
- Field names are unique and stable identifiers
- This ensures React correctly tracks each field component across re-renders
- Focus management will now work properly when fields are added/removed
https://github.com/user-attachments/assets/fdd47fed-6a1b-4c20-b3b9-f43843abc3ed
- fix:  Remove index from field key to fix column focus issue
=> Fix focus  add/remove column 

config/opensearch_dashboards.yml, src/plugins/chat/public/plugin.test.ts, src/plugins/chat/public/plugin.ts, src/plugins/chat/public/types.ts, src/plugins/context_provider/opensearch_dashboards.json, src/plugins/context_provider/public/index.ts, src/plugins/context_provider/public/plugin.ts, src/plugins/context_provider/public/types.ts, src/plugins/context_provider/server/config.ts, src/plugins/context_provider/server/index.ts, src/plugins/context_provider/server/plugin.ts, src/plugins/context_provider/server/types.ts, src/plugins/explore/opensearch_dashboards.json, src/plugins/explore/public/application/index.tsx, src/plugins/explore/public/build_services.ts, src/plugins/explore/public/components/data_table/data_table.tsx, src/plugins/explore/public/components/data_table/explore_data_table.test.tsx, src/plugins/explore/public/components/data_table/explore_data_table.tsx, src/plugins/explore/public/components/data_table/table_row/table_row.test.tsx, src/plugins/explore/public/components/data_table/table_row/table_row.tsx, src/plugins/explore/public/components/query_panel/actions/ppl_execute_query_action.test.tsx, src/plugins/explore/public/components/query_panel/actions/ppl_execute_query_action.tsx, src/plugins/explore/public/types.ts
We want to disable contextProvider and chat completely from browser and server side when no explore or when not config/ Need to use contextProvider as optionalPlugins not requiredBundles. Otherwise contextProvider will be loaded into browser. In this PR we change to use dependency injection for contextProvider. The challenge is that React hooks can't be passed through dependency injection in the traditional way because they need to be called at the component level and follow the rules of hooks. Therefore, we need to update the contextProvider plugin to 1) expose its hooks through the plugin's start interface, so they can be accessed via dependency injection 2) add a server side. Otherwise no way to read configuration from `opensearch_dashboards.yml` so plugin always loaded in browser …
=> chat(feat): implement plugin configuration controls for chat and context_provider plugins

changelogs/fragments/10595.yml, src/plugins/console/public/application/containers/settings.tsx
Backport https://github.com/opensearch-project/OpenSearch-Dashboards/commit/81d5f8199220132b2ec4252bb409a80d744cb38e from https://github.com/opensearch-project/OpenSearch-Dashboards/pull/10595.
=> [Backport 2.x] be able to update console_polling through the UI

changelogs/fragments/10661.yml, cypress/integration/core_opensearch_dashboards/opensearch_dashboards/apps/explore/01/saved_explore.spec.js, src/plugins/explore/public/application/utils/languages/ppl/default_prepare_ppl_query/default_prepare_ppl_query.test.ts, src/plugins/explore/public/application/utils/languages/ppl/get_query_string_with_source/get_query_with_source.test.ts, src/plugins/explore/public/application/utils/languages/ppl/get_query_string_with_source/get_query_with_source.ts, src/plugins/explore/public/application/utils/state_management/middleware/query_sync_middleware.test.ts
- we found two edge conditions where the PPL grammar needs updated:
https://github.com/opensearch-project/sql/issues/4444
https://github.com/opensearch-project/sql/issues/4445
- This is a temporary workaround to remedy this issue.
- If user manually types these queries in, or uses autocomplete to help them, we still show syntax error, but the query will work.
- fix: temporarily add backticks to explore's data source command
=> [Explore] add backticks to source for explore
